### PR TITLE
devguide: move into userguide as last chapter - v5

### PR DESCRIPTION
**Pull request by jufajardini**
Describe changes:
- remove mscgen dependency
- check diagram images in (added watermark to them)
- remove script for image generation

Link to redmine ticket:
https://redmine.openinfosecfoundation.org/issues/4909

Previous PR: https://github.com/OISF/suricata/pull/6975

Preview at (it doesn't render well, but I think that's not the real end result, just some bad config in my rtd)
https://suri-rtd-test.readthedocs.io/en/docs-dev-into-userguide-v5

### CODE REVIEW

**Comment by victorjulien** [comment]
I see we are dropping a script here to generate the images. Whats the process for building the images?

**Comment by jufajardini** [comment]
> I see we are dropping a script here to generate the images. Whats the process for building the images?

from command line, run:
```bash
mscgen -T png -F Arial FileName.msc 
```
Should I add that to the devguide readme file?

**Comment by jufajardini** [comment]
There's also a commit that should have been dropped. I'll add the info to the README and fix that commit history.

**Comment by victorjulien** [comment]
> > I see we are dropping a script here to generate the images. Whats the process for building the images?
> 
> from command line, run:
> 
> ```shell
> mscgen -T png -F Arial FileName.msc 
> ```
> 
> Should I add that to the devguide readme file?

This feels a bit too manual for me. Can we have a script that rebuilds all in our tree?

**Comment by jufajardini** [comment]
> > > I see we are dropping a script here to generate the images. Whats the process for building the images?
> > 
> > 
> > from command line, run:
> > ```shell
> > mscgen -T png -F Arial FileName.msc 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should I add that to the devguide readme file?
> 
> This feels a bit too manual for me. Can we have a script that rebuilds all in our tree?

I could keep the script that I was about to remove xD then, one would only have to run that.

**Comment by victorjulien** [comment]
> > > > I see we are dropping a script here to generate the images. Whats the process for building the images?
> > > 
> > > 
> > > from command line, run:
> > > ```shell
> > > mscgen -T png -F Arial FileName.msc 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Should I add that to the devguide readme file?
> > 
> > 
> > This feels a bit too manual for me. Can we have a script that rebuilds all in our tree?
> 
> I could keep the script that I was about to remove xD then, one would only have to run that.

Sounds good. Just dump it into `/scripts` w/o any further build integration (maybe `noinst`?)

**Comment by jasonish** [comment]
> > > > I see we are dropping a script here to generate the images. Whats the process for building the images?
> > > 
> > > 
> > > from command line, run:
> > > ```shell
> > > mscgen -T png -F Arial FileName.msc 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Should I add that to the devguide readme file?
> > 
> > 
> > This feels a bit too manual for me. Can we have a script that rebuilds all in our tree?
> 
> Actually we could add a CI check then too:
> 
> * call script
> * if git status shows uncommited changes, we know images are outdated
> 
> I guess this only works if the binary output is exactly the same across versions of mscgen though.

Checking that the image is newer than the source is probably good enough..

`if [ ./png-file -nt ./source-file ]; then we have an issue`...

**Comment by jufajardini** [comment]
> > > > > I see we are dropping a script here to generate the images. Whats the process for building the images?
> > > > 
> > > > 
> > > > from command line, run:
> > > > ```shell
> > > > mscgen -T png -F Arial FileName.msc 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Should I add that to the devguide readme file?
> > > 
> > > 
> > > This feels a bit too manual for me. Can we have a script that rebuilds all in our tree?
> > 
> > 
> > Actually we could add a CI check then too:
> > 
> > * call script
> > * if git status shows uncommited changes, we know images are outdated
> > 
> > I guess this only works if the binary output is exactly the same across versions of mscgen though.
> 
> Checking that the image is newer than the source is probably good enough..
> 
> `if [ ./png-file -nt ./source-file ]; then we have an issue`...

Would that be done in the `commits` workflow, when building all commits?

**Comment by jasonish** [comment]
> Would that be done in the `commits` workflow, when building all commits?

No, I'd do it in the alma-8 build that creates the distribution many of the other builds depend on. Maybe just under the duplicate SID check.

**Comment by jufajardini** [comment]
> > Would that be done in the `commits` workflow, when building all commits?
> 
> No, I'd do it in the alma-8 build that creates the distribution many of the other builds depend on. Maybe just under the duplicate SID check.

ok, thanks, I'll have a look at that.

**Comment by jufajardini** [comment]
Followed by https://github.com/OISF/suricata/pull/7161

**Pull request closed without merging**
