### PR TITLE
dns: log flags field

### PR DESCRIPTION
**Pull request by macpas**
This adds dns header's flags in eve
log.

Signed-off-by: Eric Leblond <eric@regit.org>

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-ADD DNS header's flags in eve log
-
-

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by inliniac** [comment]
@jasonish if we take this in there will have to be something similar on the Rust side I think

**Comment by jasonish** [comment]
I am all for adding the flags, I'm just not sure if adding them as a string containing the hex value is the best idea. JSON, being a serialization format it would make more sense just to log it as a number. Or perhaps break it out like the TCP flags in the flow event.

I know a number isn't as easily human read, but it is much easier read by machines and scripts.

**Comment by jasonish** [comment]
> We can still also leave this field in, so that it's easy to aggregate on and spot outliers.

I still think its more true to JSON to store it as a number rather than a string tho. But I won't fuss about it.

**Comment by macpas** [comment]
example, like tcp flags in netflow log: "tcp":{"tcp_flags":"1b","syn":true,"fin":true,"psh":true,"ack":true},

instead of 
"dns":{"type":"answer","id":44910,"flags":"0x8180","rcode":"NOERROR",.....}
you would expect this:
"dns":{"type":"answer","id":44910,"flags":"0x8180","qr":true,"rd":true,"ra":true, "rcode":"NOERROR",.....}..
so we would do it for those 5 flags: QR/AA/TC/RD/AA.
Am I right ?
or we keep the basic hex dump, maybe removing also the 0x in order to have the same display done in tcp_flags ?

**Pull request closed without merging**
