### PR TITLE
Email log backport 6.0.5/v2

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
https://redmine.openinfosecfoundation.org/issues/4931
https://redmine.openinfosecfoundation.org/issues/4894

suricata-verify-pr: 632

### CODE REVIEW

**Comment by victorjulien** [comment]
The nfs file_data commit is a feature that should not be backported.

**Comment by inashivb** [comment]
> The nfs file_data commit is a feature that should not be backported.

hmm I'm just noticing you conversation w Philippe about it on the issue. @catenacyber is https://github.com/OISF/suricata/pull/6620/files fixing the leak in master somehow? Could you please tell what's the right way to approach the issue?

**Comment by catenacyber** [comment]
> is https://github.com/OISF/suricata/pull/6620/files fixing the leak in master somehow?

Yes, it does the fix.
The bug is due to having `file.data` and later a `nfs` keyword in a signature.
The fix in master is to allow such a signature.

For the backport, I think Victor wants to error on such a signature to avoid the leak...
And yes, I am not sure what is the right way to achieve this...

**Comment by jlucovsky** [comment]
> > is https://github.com/OISF/suricata/pull/6620/files fixing the leak in master somehow?
> 
> Yes, it does the fix. The bug is due to having `file.data` and later a `nfs` keyword in a signature. The fix in master is to allow such a signature.
> 
> For the backport, I think Victor wants to error on such a signature to avoid the leak... And yes, I am not sure what is the right way to achieve this...

I've been looking at the same issue with backports to 5.0.x.

Perhaps we could flag the issue when parsing the rule and invalidate it?

**Pull request closed without merging**
