### PR TITLE
New ByteParseString* functions

### PR DESCRIPTION
**Pull request by inashivb**
Add a new set of ByteExtractParse* functions and use them for strict parsing in all parser, configuration and setup functions.

### CODE REVIEW

**Comment by victorjulien** [comment]
The prototype declarations should not be in a separate commit. Please squash https://github.com/OISF/suricata/pull/4459/commits/88c6413f66273904e9ed18a30ce72ac6d8f83e0e and https://github.com/OISF/suricata/pull/4459/commits/7f05211999ca780e132953a205bf39b9ff62911d

**Comment by victorjulien** [comment]
I think it looks good overall.

I do question my own suggestion of 'ByteParse..' naming. These are all string parsers I think, so would a naming scheme like 'StringParse...' make more sense? E.g. `StringParseUint16`.

**Comment by inashivb** [comment]
> I think it looks good overall.
> 
> I do question my own suggestion of 'ByteParse..' naming. These are all string parsers I think, so would a naming scheme like 'StringParse...' make more sense? E.g. `StringParseUint16`.

Yes, makes sense. Making the changes.

**Comment by inashivb** [comment]
Replaced with #4462

**Pull request closed without merging**
