### PR TITLE
detect: removed useless comparaison

### PR DESCRIPTION
**Pull request by Yonah125**
Describe changes:
- Removed an useless 'Not Equals' statment in a test due to the 'Equals' statment just after it.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks Yonah.
Could you use the commit writing style from : https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria#Commits

> Naming convention: prefix message with sub-system ("rule parsing: fixing foobar").

Like `detect: remove useless comparaison`

Otherwise, I approve this ;-)

**Comment by Yonah125** [comment]
And it's done ! :)

**Comment by catenacyber** [comment]
> And it's done ! :)

I meant the git commit title, not the Github Pull request title :-p

**Review by catenacyber — APPROVED** [review]
Looks good to me.
Thanks.
Did you sign the CLA ? (Contributor License Agreement)

**Comment by Yonah125** [comment]
Yes, I did

**Comment by victorjulien** [comment]
Did you set your git ID? Currently its `Yonah125 <50438152+Yonah125@users.noreply.github.com>`. Our normal way is `Firstname Lastname <email>` for proper attribution.

**Review by victorjulien — CHANGES_REQUESTED** [review]
CI fails need to be investigated.

**Comment by catenacyber** [comment]
Bet this just needs a rebase

**Comment by victorjulien** [comment]
Please create a new branch and PR, thanks!

**Pull request closed without merging**
