### PR TITLE
log/pcap: Remove sguil mode

### PR DESCRIPTION
**Pull request by jlucovsky**
Issue 6347 -- Remove sguil mode from post 7.0.x Suricata releases

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6347](https://redmine.openinfosecfoundation.org/issues/6347)

Describe changes:
- Remove sguil mode support from Suricata configuration and pcap log code
- Remove documentation mentionin sguil mode.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 181 | 201 | 111.05% |
| .flow.spare | 1961331 | 2163420 | 110.3% | 

Pipeline 17540

**Comment by victorjulien** [comment]
I think this deserves a mention in the upgrade docs, but I'm ok with doing that in a separate PR.

@ct0br0 can this get a qalab rerun? Nothing in the PR should have triggered the deviation.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17553

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #10187, thanks!

**Pull request closed without merging**
