### PR TITLE
fix: SMB stream depth setting in Rust

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4621

Fails build on some distros with old Rust.

### CODE REVIEW

**Comment by victorjulien** [comment]
PR still talks about memcap.

Also, what is the idea of the Rust errors? It seems that a basic config string parser shouldn't lead to us bumping MSRV

**Comment by victorjulien** [comment]
Can you also explain what this does in the git commits?

**Comment by inashivb** [comment]
> PR still talks about memcap.
> 
Sorry. I forgot to change the branch name. Came from there. I'll change it.

> Also, what is the idea of the Rust errors? It seems that a basic config string parser shouldn't lead to us bumping MSRV
Jason [mentioned](https://github.com/OISF/suricata/pull/6353#issuecomment-914544102) in my last PR that we are going to update our MSRV soon so I don't have to worry about these errors but if it is not happening very soon, I can change the use of the function that leads to the error.

**Comment by victorjulien** [comment]
Looking at the error are we really bumping MSRV because we're unwilling to use a constant value for megabyte, kilobyte, etc?

**Comment by inashivb** [comment]
> Looking at the error are we really bumping MSRV because we're unwilling to use a constant value for megabyte, kilobyte, etc?

I don't think so. I think Jason meant that we are going to do it anyway so this error will be gone with the bump.

**Comment by inashivb** [comment]
Replaced w #6365

**Comment by jasonish** [comment]
I thought I tried `.pow` with 1.48 and it worked, but it appears you need 1.50 at least.  So we'll have to drop is use for another year or 2.

**Pull request closed without merging**
