### PR TITLE
lua: Expose byte_extract to lua match scripts

### PR DESCRIPTION
**Pull request by benajmin**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#2871](https://redmine.openinfosecfoundation.org/issues/2871)

Describe changes:
- Allow lua match scripts to access variables defined in rule by byte_extract or byte_math

suricata-verify-pr: 591

### CODE REVIEW

**Comment by jlucovsky** [comment]
@benajmin `suricata-verify` is failing for the test case accompanying this PR.

`[2202060] 31/1/2022 -- 09:50:53 - (detect-lua.c:405) <Info> (DetectLuaMatch) -- failed to run script: ./lua-byte-math.lua:10: attempt to call field 'pack' (a nil value)`

`[2202060] 31/1/2022 -- 09:50:53 - (detect-lua.c:405) <Info> (DetectLuaMatch) -- failed to run script: ./lua-byte-extract.lua:11: attempt to call field 'pack' (a nil value)`

**Review by victorjulien — CHANGES_REQUESTED** [review]
See inline comment by Jeff

**Comment by suricata-qa** [comment]
Warning: no commits in this PR have specified the following ticket(s):
- 2871 - https://redmine.openinfosecfoundation.org/issues/2871

Please update the commit(s) and submit a new PR.

**Comment by catenacyber** [comment]
@benajmin are you planning further work on this ?

**Comment by jlucovsky** [comment]
Continued in #7660

**Pull request closed without merging**
