### PR TITLE
Reorganize C source into directories - v8

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/4353

Changes from last PR:
- Rebase.
- Move the rename of the util files into the correct commit.

This PR moves the following types of files into their
own directories:
- sources
- util
- win32
- outputs (outputs, log, alert)
- app-layer
- decoders

I think this covers the very easy to move modules.

Requires suricata-verify PR: https://github.com/OISF/suricata-verify/pull/147

Redmine issue: https://redmine.openinfosecfoundation.org/issues/3166

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/444
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/801

### CODE REVIEW

**Comment by catenacyber** [comment]
I looked at one commit and this looked straightforward like running `sed 's/util-/util\//'`
Are there more tricks ?

**Comment by jasonish** [comment]
> I looked at one commit and this looked straightforward like running `sed 's/util-/util\//'`
> Are there more tricks ?

Thats the gist of it.  When it comes to names that are the same, but in different directories you sometimes have to add ../ to resolve VPATH conflicts.

**Comment by jasonish** [comment]
The failed test is due to the code generation scripts for new app-layers, etc. I'll fix that after an OK on the code re-org.

**Comment by victorjulien** [comment]
Thinking about a split I wish I had made early: in the 'detect-' namespace, we mix lots of things. What if we put all the keywords in their own dir? E.g. `src/detect/keywords/http-uri.c`

**Comment by jasonish** [comment]
> Thinking about a split I wish I had made early: in the 'detect-' namespace, we mix lots of things. What if we put all the keywords in their own dir? E.g. `src/detect/keywords/http-uri.c`

Yes, make sense. Simple enough to -- simpler than rebasing anyways ;)

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/4749

**Pull request closed without merging**
