### PR TITLE
Next/20211122/v18

### PR DESCRIPTION
**Pull request by victorjulien**
#6627
#6626
#6622
#6620
#6617
#6616
#6614
#6608 
#6598
#6595
#6592
#6589
#6586 
#6584
#6585 
#6401

### CODE REVIEW

**Comment by victorjulien** [comment]
Related to #6584
```
thread '<unnamed>' panicked at 'Both directions are set', src/core.rs:58:13
177
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
178
fatal runtime error: failed to initiate panic, error 5
179
==35== ERROR: libFuzzer: deadly signal
180
    #0 0x5acaf4 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/ubsan/ubsan_diag_standalone.cpp:31:3
181
    #1 0x553768 in fuzzer::PrintStackTrace() cxa_noexception.cpp
182
    #2 0x538683 in fuzzer::Fuzzer::CrashCallback() cxa_noexception.cpp
183
    #3 0x7f77a74363bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
184
    #4 0x7f77a723c18a in raise (/lib/x86_64-linux-gnu/libc.so.6+0x4618a)
185
    #5 0x7f77a721b858 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x25858)
186
    #6 0xad3289 in std::sys::unix::abort_internal::h43dff3de7a4b0612 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/mod.rs:259:14
187
    #7 0xab9b7f in rust_panic /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:656:5
188
    #8 0xab9963 in std::panicking::rust_panic_with_hook::h1aad5d81db6ee3ca /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:624:5
189
    #9 0x8293e5 in std::panicking::begin_panic::_$u7b$$u7b$closure$u7d$$u7d$::h6ad70a6de29bf484 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:526:9
190
    #10 0x828c26 in std::sys_common::backtrace::__rust_end_short_backtrace::hf4fce452f748463c /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:139:18
191
    #11 0x4f843e in std::panicking::begin_panic::h0453221914fa76bd /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:525:12
192
    #12 0x915d99 in _$LT$suricata_rust..core..Direction$u20$as$u20$core..convert..From$LT$u8$GT$$GT$::from::hb2d431a0e1a11ac9 /src/suricata/rust/src/core.rs:58:13
193
    #13 0x915d99 in _$LT$T$u20$as$u20$core..convert..Into$LT$U$GT$$GT$::into::he607e24b87311ff7 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:542:9
194
    #14 0x915d99 in rs_nfs_probe /src/suricata/rust/src/nfs/nfs.rs:1801:28
195
    #15 0x5b374b in PPGetProto /src/suricata/src/app-layer-detect-proto.c
196
    #16 0x5af044 in AppLayerProtoDetectPPGetProto /src/suricata/src/app-layer-detect-proto.c:598:15
197
    #17 0x5af044 in AppLayerProtoDetectGetProto /src/suricata/src/app-layer-detect-proto.c:1570:19
198
    #18 0x5ae126 in LLVMFuzzerTestOneInput /src/suricata/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c:57:15
199
    #19 0x539c23 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp
200
    #20 0x53940a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) cxa_noexception.cpp
201
    #21 0x53b264 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
202
    #22 0x53b499 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
203
    #23 0x52aedd in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
204
    #24 0x553f22 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
205
    #25 0x7f77a721d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
206
    #26 0x5027bd in _start (build-out/fuzz_applayerprotodetectgetproto+0x5027bd)
```

**Comment by victorjulien** [comment]
@catenacyber can you see if I you can extract a pcap that triggers ^ ?

**Comment by catenacyber** [comment]
Quite a big PR :-)
Indeed I think CIFuzz is a true positive from #6584
Looking into it

**Comment by catenacyber** [comment]
Ok, I cannot craft a pcap here (that is not so much a true positive then)
The fuzz target just uses one byte of fuzzed input to use as `flags` which 

I guess I suggest this patch
```
diff --git a/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c b/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c
index 0a8095c8a..fb386e5cc 100644
--- a/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c
+++ b/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c
@@ -54,7 +54,11 @@ int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
     f->protoctx = &ssn;
     f->protomap = FlowGetProtoMapping(f->proto);
 
-    alproto = AppLayerProtoDetectGetProto(alpd_tctx, f, data+HEADER_LEN, size-HEADER_LEN, f->proto, data[0], &reverse);
+    uint8_t flags = STREAM_TOCLIENT;
+    if (data[0] & STREAM_TOSERVER) {
+        flags = STREAM_TOSERVER;
+    }
+    alproto = AppLayerProtoDetectGetProto(alpd_tctx, f, data+HEADER_LEN, size-HEADER_LEN, f->proto, flags, &reverse);
     if (alproto != ALPROTO_UNKNOWN && alproto != ALPROTO_FAILED && f->proto == IPPROTO_TCP &&
             (data[0] & STREAM_MIDSTREAM) == 0) {
         /* If we find a valid protocol at the start of a stream :
```

Or maybe having `AppLayerProtoDetectGetProto` using a bool instead of a uint8 ?

**Comment by victorjulien** [comment]
> Ok, I cannot craft a pcap here (that is not so much a true positive then) The fuzz target just uses one byte of fuzzed input to use as `flags` which
> 
> I guess I suggest this patch
> 
> ```
> diff --git a/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c b/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c
> index 0a8095c8a..fb386e5cc 100644
> --- a/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c
> +++ b/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c
> @@ -54,7 +54,11 @@ int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
>      f->protoctx = &ssn;
>      f->protomap = FlowGetProtoMapping(f->proto);
>  
> -    alproto = AppLayerProtoDetectGetProto(alpd_tctx, f, data+HEADER_LEN, size-HEADER_LEN, f->proto, data[0], &reverse);
> +    uint8_t flags = STREAM_TOCLIENT;
> +    if (data[0] & STREAM_TOSERVER) {
> +        flags = STREAM_TOSERVER;
> +    }
> +    alproto = AppLayerProtoDetectGetProto(alpd_tctx, f, data+HEADER_LEN, size-HEADER_LEN, f->proto, flags, &reverse);
>      if (alproto != ALPROTO_UNKNOWN && alproto != ALPROTO_FAILED && f->proto == IPPROTO_TCP &&
>              (data[0] & STREAM_MIDSTREAM) == 0) {
>          /* If we find a valid protocol at the start of a stream :
> ```
> 
> Or maybe having `AppLayerProtoDetectGetProto` using a bool instead of a uint8 ?

Can you do a PR for this change? I will include it in my next `next` commit, which will be coming soon

**Comment by catenacyber** [comment]
> Can you do a PR for this change? I will include it in my next `next` PR, which will be coming soon

https://github.com/OISF/suricata/pull/6632

**Pull request merged**
