### PR TITLE
Feature/smb/v19.5

### PR DESCRIPTION
**Pull request by victorjulien**
Getting to the point where I think we can merge and move from there.

Describe changes:
- improve non NT status handling
- fix an issue with SMB1 session tx handling
- improve protocol detection
- add smb to default eve-log

Still todo:
- delete logging needs to be improved
- suppress READ/WRITE/etc records for SMB2
- many other things

### CODE REVIEW

**Comment by victorjulien** [comment]
Replaces #3281

**Comment by victorjulien** [comment]
- PR victorjulien-pcap: https://buildbot.openinfosecfoundation.org/builders/victorjulien-pcap/builds/107
- PR victorjulien: https://buildbot.openinfosecfoundation.org/builders/victorjulien/builds/109

**Comment by jasonish** [comment]
I was trying to link log records together to associate them to a filename, but there doesn't appear to be a field to do this. From a quick look at https://msdn.microsoft.com/en-us/library/ee441636.aspx, it looks like there is a file_id field. Can that be logged as well?

**Comment by victorjulien** [comment]
Replaced by #3286

**Pull request closed without merging**
