### PR TITLE
Rust add snmp 03

### PR DESCRIPTION
**Pull request by chifflier**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2738

This is an update of #3581 and #3879

Describe changes (since last PR):
- All requested changes merged (copyright, keywords, snmp.community now is a v2 MPM keyword, split unit tests)

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you address https://github.com/OISF/suricata/pull/3581#issuecomment-495069112 and also include https://github.com/victorjulien/suricata/commit/8628c4f7b90682cea7dbec054c1b589755ca1c45

**Comment by chifflier** [comment]
> Can you address [#3581 (comment)](https://github.com/OISF/suricata/pull/3581#issuecomment-495069112) and also include [victorjulien@8628c4f](https://github.com/victorjulien/suricata/commit/8628c4f7b90682cea7dbec054c1b589755ca1c45)

Regarding the case of messages (comment from @jasonish ), what would be the preferred choice ? All possible messages are here: https://docs.rs/snmp-parser/0.3.0/snmp_parser/snmp/struct.PduType.html
Using lowercase means we would add `_` characters, because some PDU types(like GetRequest, GetNextRequest etc.) are made of 2 words or more.
What do you recommend ? `get_request` (or maybe `getrequest`) ?

**Comment by victorjulien** [comment]
In most places online I see the GetRequest notation, but for example wireshark seems to use 'get-request'. Not sure what to make of it.

**Comment by catenacyber** [comment]
Hi pierre @chifflier 
Hasn't SNMP a ASN1 specification https://github.com/boundary/wireshark/blob/master/asn1/snmp/snmp.asn ?

If so, should we use a code generator from ASN1 to Rust ?

**Comment by chifflier** [comment]
@victorjulien , @jasonish : I used the CamelCase notation (GetNextRequest) because it is the one from the RFC (for ex 1452), Wikipedia, etc. A few others (wireshark, cisco) seem to use dash-notation (get-next-request). It is easy to change, I leave the choice to you.

@catenacyber : sure, but this idea should be moved to https://github.com/rusticata/snmp-parser, which  is the underlying parser. FYI, this means writing an ASN.1 compiler, not exactly an easy thing: I considered writing one for https://github.com/rusticata/kerberos-parser, but there are some technical difficulties (constraints are described as free-form text, for ex).

**Comment by victorjulien** [comment]
I'm good with either notation. @jasonish, any preference?

**Comment by catenacyber** [comment]
> sure, but this idea should be moved to https://github.com/rusticata/snmp-parser, which is the underlying parser. FYI, this means writing an ASN.1 compiler, not exactly an easy thing: I considered writing one for https://github.com/rusticata/kerberos-parser, but there are some technical difficulties (constraints are described as free-form text, for ex).

Indeed.
The question is how many protocols with ASN1 specifications do we want for Suricata to see if it is worth the cost ?

**Comment by jasonish** [comment]
> I'm good with either notation. @jasonish, any preference?

How about snake_case?  For example, I believe in TLS we have "NotBefore", but we log it as "not_before".  I think its worth doing some normalization here across all protos rather than using the case from the RFC.

**Comment by chifflier** [comment]
Closing, replace by #3926

**Pull request closed without merging**
