### PR TITLE
tests/stream-tcp-list.c : Convert unittests to new FAIL/PASS API v4

### PR DESCRIPTION
**Pull request by zazie-codes**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:https://redmine.openinfosecfoundation.org/issues/6330
Update of #9741 

Describe changes:
-hanging commit message to according to guidelines
-adding  redmine ticket number in the commit body
-git author

### CODE REVIEW

**Comment by jufajardini** [comment]
> NOTE: This PR may contain new authors:
> 
> ```
> Lizaopar <oparliza@gmail.com>
> ```

I've noticed that you are using a different name format here from what you had on previous, merged, contributions. Could you please use the same author name style for all your contributions to Suricata? Otherwise, this messes up with some of our automated tools - and the commit history ;)

**Review by jufajardini — CHANGES_REQUESTED** [review]
The code changes are good, but unfortunately now the commit message is totally out of standards, for us. 

Something like this could work:
```
stream/tcp-list: convert unittests to FAIL/PASS API
```

**Comment by zazie-codes** [comment]
> > NOTE: This PR may contain new authors:
> > ```
> > Lizaopar <oparliza@gmail.com>
> > ```
> 
> I've noticed that you are using a different name format here from what you had on previous, merged, contributions. Could you please use the same author name style for all your contributions to Suricata? Otherwise, this messes up with some of our automated tools - and the commit history ;)



Let me check on it. I wonder why it changed since i didnt make any changes.
Im working on it.

**Comment by jufajardini** [comment]
Replaced by: https://github.com/OISF/suricata/pull/9823

**Pull request closed without merging**
