### PR TITLE
Mingw/v35

### PR DESCRIPTION
**Pull request by victorjulien**
Preview: builds and works on MinGW64.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR victorjulien-pcap: https://buildbot.openinfosecfoundation.org/builders/victorjulien-pcap/builds/50
- PR victorjulien: https://buildbot.openinfosecfoundation.org/builders/victorjulien/builds/51

### CODE REVIEW

**Comment by pevma** [comment]
I get an err on MSYS2 MinGW64  (Windows Server 2016)- 

```

  CC       util-affinity.o
  CC       util-var.o
  CC       util-var-name.o
  CC       win32-misc.o
  CC       win32-service.o
  CCLD     suricata.exe
../libhtp/htp/.libs/libhtp.a(htp_multipart.o): In function `htp_mpart_part_handle_data':
C:\msys64\home\Administrator\suricata\libhtp\htp/htp_multipart.c:786: undefined reference to `__stack_chk_fail'
../libhtp/htp/.libs/libhtp.a(htp_multipart.o):htp_multipart.c:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
../libhtp/htp/.libs/libhtp.a(htp_util.o): In function `htp_log':
C:\msys64\home\Administrator\suricata\libhtp\htp/htp_util.c:413: undefined reference to `__stack_chk_fail'
../libhtp/htp/.libs/libhtp.a(htp_util.o): In function `fprint_raw_data_ex':
C:\msys64\home\Administrator\suricata\libhtp\htp/htp_util.c:2145: undefined reference to `__stack_chk_fail'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [Makefile:1227: suricata.exe] Error 1
make[3]: Leaving directory '/home/Administrator/suricata/src'
make[2]: *** [Makefile:1142: all] Error 2
make[2]: Leaving directory '/home/Administrator/suricata/src'
make[1]: *** [Makefile:493: all-recursive] Error 1
make[1]: Leaving directory '/home/Administrator/suricata'
make: *** [Makefile:421: all] Error 2

```

this part goes ok (cmd line) -
```
./autogen.sh && \
./configure  --with-libpcre-includes=/opt/pcre/include/  --with-libpcre-libraries=/opt/pcre/lib/ \
--with-libpcap-includes=/npcap-sdk/Include --with-libpcap-libraries=/npcap-sdk/Lib/x64  \
--with-libyaml-includes=/opt/yaml/include/  --with-libyaml-libraries=/opt/yaml/lib/
```

I get err here -
```
 make clean && make
```

**Comment by victorjulien** [comment]
Looks like I did some libhtp changes to fix that. Will try to push those soon.

**Comment by victorjulien** [comment]
@pevma can you give https://github.com/OISF/libhtp/pull/162 a try?

**Comment by pevma** [comment]
works good with https://github.com/OISF/libhtp/pull/162  
64bit Suri - 
```
C:\msys64\home\Administrator\suricata\src>.libs\suricata.exe -c ..\suricata.yaml -i 10.0.2.15 -vvv -l ..\tmp-log
[780] 15/12/2017 -- 01:04:31 - (win32-service.c:53) <Info> (SCRunningAsService) -- Running as service: no
[780] 15/12/2017 -- 01:04:31 - (suricata.c:1191) <Info> (ParseCommandLinePcapLive) -- translated 10.0.2.15 to pcap device \Device\NPF_{D53813F6-9382-4292-93A0-DA131DA66D9F}
[780] 15/12/2017 -- 01:04:31 - (util-device.c:187) <Info> (LiveSafeDeviceName) -- Shortening device name to: \Devi..D9F}
Error opening file C:\\Program Files\\Suricata\\logsuricata.log
[780] 15/12/2017 -- 01:04:31 - (suricata.c:1116) <Notice> (LogVersion) -- This is Suricata version 4.1.0-dev (rev df8da5cc)
[780] 15/12/2017 -- 01:04:31 - (util-cpu.c:171) <Info> (UtilCpuPrintSummary) -- CPUs/cores online: 2
[780] 15/12/2017 -- 01:04:31 - (app-layer-htp.c:2247) <Config> (HTPConfigSetDefaultsPhase2) -- 'default' server has 'request-body-minimal-inspect-size' set to 31130 and 'request-body-inspect-window' set to 3892 after randomization.
[780] 15/12/2017 -- 01:04:31 - (app-layer-htp.c:2265) <Config> (HTPConfigSetDefaultsPhase2) -- 'default' server has 'response-body-minimal-inspect-size' set to 38913 and 'response-body-inspect-window' set to 15565 after randomization.
.....
.....
```

**Comment by victorjulien** [comment]
Merged in #3112

**Pull request closed without merging**
