### PR TITLE
Feature/http range/v26

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1576

Describe changes:
- Uses a generic container (a thread-safe hash table whose key is the url/filename) to store file parts with HTTP Range header
- handles reassembly of these parts, while enforcing a global memcap

suricata-verify-pr: 517
https://github.com/OISF/suricata-verify/pull/517

Continues #6333 with fixing the null dereference, ie removing obsolete check for `c->container->files->tail` as `c->container->lastsize` gets used 

For testing : https://github.com/jasonish/suricata-http-range-test

Left TODO : implement for HTTP2

### CODE REVIEW

**Comment by victorjulien** [comment]
```
[539874] 3/9/2021 -- 20:31:15 - (tm-threads.c:2004) <Notice> (TmThreadWaitOnThreadInit) -- Threads created -> RX: 1 W: 16 FM: 1 FR: 1   Engine started.
[539874] 3/9/2021 -- 20:31:15 - (suricata.c:2627) <Notice> (SuricataMainLoop) -- Signal Received.  Stopping engine.
suricata: app-layer-htp-range.c:570: void HttpRangeFreeBlock(HttpRangeContainerBlock *): Assertion `!((b->files != ((void*)0)))' failed.

Thread 7 "W#05" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdfd5a700 (LWP 539883)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff710b859 in __GI_abort () at abort.c:79
#2  0x00007ffff710b729 in __assert_fail_base (fmt=0x7ffff72a1588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x20440c0 <str> "!((b->files != ((void*)0)))", 
    file=0x2043500 <str> "app-layer-htp-range.c", line=570, function=<optimized out>) at assert.c:92
#3  0x00007ffff711cf36 in __GI___assert_fail (assertion=0x20440c0 <str> "!((b->files != ((void*)0)))", file=0x2043500 <str> "app-layer-htp-range.c", line=570, 
    function=0x2044100 <__PRETTY_FUNCTION__.HttpRangeFreeBlock> "void HttpRangeFreeBlock(HttpRangeContainerBlock *)") at assert.c:101
#4  0x0000000000ae271f in HttpRangeFreeBlock (b=0x6030003bd1f0) at app-layer-htp-range.c:570
#5  0x0000000000ab4deb in HTPStateFree (state=0x60b00019a530) at app-layer-htp.c:377
#6  0x0000000000af1b24 in AppLayerParserStateProtoCleanup (protomap=0 '\000', alproto=1, alstate=0x60b00019a530, pstate=0x60400005ac90) at app-layer-parser.c:1497
#7  0x0000000000af1ccd in AppLayerParserStateCleanup (f=0x6120003ca540, alstate=0x60b00019a530, pstate=0x60400005ac90) at app-layer-parser.c:1508
#8  0x0000000000d8b90c in FlowCleanupAppLayer (f=0x6120003ca540) at flow.c:147
#9  0x0000000000d97107 in FlowClearMemory (f=0x6120003ca540, proto_map=0 '\000') at flow.c:1082
#10 0x0000000000dcbe91 in CheckWorkQueue (tv=0x6120003ef5c0, fw=0x60d0000acfa0, detect_thread=0x0, counters=0x7fffdfd58e60, fq=0x7fffdfd58de0) at flow-worker.c:199
#11 0x0000000000dcb13e in FlowWorkerProcessInjectedFlows (tv=0x6120003ef5c0, fw=0x60d0000acfa0, p=0x61e003984c80, detect_thread=0x0) at flow-worker.c:458
#12 0x0000000000dc95c0 in FlowWorker (tv=0x6120003ef5c0, p=0x61e003984c80, data=0x60d0000acfa0) at flow-worker.c:581
#13 0x00000000009c2158 in TmThreadsSlotVarRun (tv=0x6120003ef5c0, p=0x61e003984c80, slot=0x6060000ddd80) at tm-threads.c:117
#14 0x00000000009cf043 in TmThreadsSlotVar (td=0x6120003ef5c0) at tm-threads.c:452
#15 0x00007ffff7d63609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007ffff7208293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 4
#4  0x0000000000ae271f in HttpRangeFreeBlock (b=0x6030003bd1f0) at app-layer-htp-range.c:570
570	        DEBUG_VALIDATE_BUG_ON(b->files != NULL);
(gdb) p *b
$1 = {toskip = 0, current = 0x0, container = 0x0, files = 0x60200004bb90}
(gdb)
```
I'll share the pcap privately.

**Comment by catenacyber** [comment]
Cf https://github.com/OISF/suricata/pull/6298/files#r694119852

> Normally if we'd get here we would have called the "close" logic before it, so that would be responsible for handling any data that is still useful somehow.

So, we were not in the normal case, right ?

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4053

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6354

**Pull request closed without merging**
