### PR TITLE
decode: Improved FTP active mode handling

### PR DESCRIPTION
**Pull request by jlucovsky**
Link to redmine tickets:

https://redmine.openinfosecfoundation.org/issues/2459
https://redmine.openinfosecfoundation.org/issues/2527

Describe changes
- Detect FTP active mode over IPv4 and IPv6
- Create expectation based on mode
- Suricata-verify tests: OISF/suricata-verify#28

Continuation of #3780

### CODE REVIEW

**Comment by victorjulien** [comment]
One of the scan-build warnings is gone, but one remains:
```
app-layer-ftp.c:485:29: warning: Use of memory after it is freed
                            FTPFree(state->port_line, state->port_line_size);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by jlucovsky** [comment]
Can you provide me with the report generated by scan-build? It'll be in `/tmp/scan-build-yyyy-mm-dd-*`?

**Comment by inliniac** [comment]
On 13-04-19 14:59, Jeff Lucovsky wrote:
> Can you provide me with the report generated by scan-build? It'll be in
> |/tmp/scan-build-yyyy-mm-dd-*|?
> 

I haven't captured that. My test runs in a gitlab-ci docker image. You
should be able to get it yourself using a docker instance of ubuntu
18.10 or 19.04.

**Comment by victorjulien** [comment]
We've determined that this is a scan-build fp that we can't easily work around, so we'll leave the code as-is.

**Comment by victorjulien** [comment]
Merged as part of #3810, thanks Jeff!

**Pull request closed without merging**
