### PR TITLE
rfb: ensure logging of incompletely parsed txs

### PR DESCRIPTION
**Pull request by satta**
- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#5912](https://redmine.openinfosecfoundation.org/issues/5912)

Describe changes:
- Mark skipped txs as complete so they get logged with the data we were able to gather so far. See https://github.com/OISF/suricata/pull/9071#issuecomment-1612022574

### CODE REVIEW

**Comment by jasonish** [comment]
Is an S-V test possible that shows failure in master, but success after this PR?

**Comment by satta** [comment]
> Is an S-V test possible that shows failure in master, but success after this PR?

I'll see if I can get a pcap of, say, an Apple RFB session, for which there is no authentication parsing, and see if I can get partial events logged.

**Comment by satta** [comment]
Found one, see https://github.com/OISF/suricata-verify/pull/1274. Will open a new PR using that.

**Comment by satta** [comment]
Next PR: #9114

**Pull request closed without merging**
