### PR TITLE
smb: fix wrong data offset when wct = 12 (backport6)

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6139

Describe changes:
- Backport of 000eb91078d5ca88ee93006340d7e68f97ade4bc

https://github.com/OISF/suricata-verify/pull/1260
```
SV_BRANCH=pr/1260
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 364 | 0.00 | 

Pipeline 14751

**Comment by jasonish** [comment]
Ticket 6008 in master also has commit abc76e27de7184d6f64040fb53d7d0a4d2b3df17. Is that not required in the backport?

**Comment by catenacyber** [comment]
This simple commit has big impact.

The other commit you mention is more complex and has less impact

**Comment by jasonish** [comment]
Maybe a comment in the ticket as to why, otherwise it looks like an incomplete backport.

**Comment by catenacyber** [comment]
> Maybe a comment in the ticket as to why, otherwise it looks like an incomplete backport.

This backport is indeed incomplete, but it is better than nothing.

In fact, the ticket should have been split in 2 different issues, each being fixed by a commit.

This is the impactful fix that seems to me important to merge...

This simple commit is complete enough to fix an important bug.

**Comment by jasonish** [comment]
The initial comment where this was held back: https://github.com/OISF/suricata/pull/9022#issuecomment-1590953660

**Comment by victorjulien** [comment]
> The initial comment where this was held back: [#9022 (comment)](https://github.com/OISF/suricata/pull/9022#issuecomment-1590953660)

This was because the patches in part were about fixing andx support, which is really only supported properly in 7.

**Comment by catenacyber** [comment]
> This was because the patches in part were about fixing andx support

I would not say so

This one commit in the PR fixes the case where the offset where to write the data in the file transferred over SMB is described as u16 instead of u32
Previously, we always took 0, if this offset was a u16, but this commit fixes by taking its value.
This fixes analysis of legit traffic.

The other commit fixes more completely the cases if you add padding in your SMB pdu (especially between the SMB "header" and the file data to write)
This is (attacker-)crafted traffic.
This is not about AndX offset being non 0. (But we may have still missed an evasion for some cases with these AndX offset being non 0 associated with padding)

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/9098

**Pull request closed without merging**
