### PR TITLE
http: Use libhtp-rs.

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2696) ticket:
https://redmine.openinfosecfoundation.org/issues/2696

Describe changes:
- Use libhtp-rs.

Rebase from #11885 + htp-rs handles better gap in compressed content

Draft to see CI/QA feedback with latest libhtp-rs changes, and not have too many conflicts

TODOs :
- look into more QA results
- look into the remaining oss-fuzz differential reports for libhtp-rs

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_single_suri_time.

ERROR: QA failed on SURI_TLPW2_single_alerts_cmp.

ERROR: QA failed on SURI_TLPW2_autofp_alerts_cmp.

ERROR: QA failed on SURI_TLPW1_files_sha256.

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_single_stats_chk | | |
| .uptime | 782 | 818 | 104.6% |
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.http.parser | 47 | 29 | 61.7% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 636 | 657 | 103.3% |
| .app_layer.error.http.parser | 700 | 584 | 83.43% | 

Pipeline 23196

**Comment by catenacyber** [comment]
Lots to do for SURI_TLPW1_files_sha256

I guess next step is : 
- translate individual pcaps in SV tests 
- make libhtp-rs behave as libhtp C (do not waste more time wondering which is having the best behavior for now) and count passing SV tests

For example, a body with Content-Length: 12 and 12 bytes followed by linefeed resulted in a 13-byte file for rust and 12-bytes for C... I do not know which is best, but let's keep behavior for now...

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_single_alerts_cmp.

ERROR: QA failed on SURI_TLPW2_autofp_alerts_cmp.

ERROR: QA failed on SURI_TLPW1_files_sha256.

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_single_stats_chk | | |
| .uptime | 782 | 815 | 104.22% |
| | SURI_TLPW2_autofp_stats_chk | | |
| .flow.end.tcp_state.established | 8 | 9 | 112.5% |
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.http.parser | 47 | 30 | 63.83% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.http.parser | 700 | 584 | 83.43% | 

Pipeline 23296

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/12198

**Pull request closed without merging**
