### PR TITLE
IPC Source

### PR DESCRIPTION
**Pull request by dbcfd**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Introduction of a source which can receive packets via one or multiple IPC channels (specifically [ipc-channel](https://github.com/servo/ipc-channel) with [packet-ipc](https://github.com/protectwise/packet-ipc) for wire format). This allows packets to be fed to suricata by any application that can consume utilize the rust library packet-ipc. Example library for usage is at [suricata-ipc](https://github.com/protectwise/suricata-ipc).

This PR will need some additional cleanup and addition of workers mode, however at this point in time, I would like feedback on the approach and implementation of the source, since it does require packet pool and packet free'ing changes.

### CODE REVIEW

**Comment by victorjulien** [comment]
Replaces #5011

**Comment by jasonish** [comment]
Can you explain in higher-than-code level terms why the changes were required to the packet pool? We already have an af packet zero copy mode which I don't think would be that much different. Thanks!

**Comment by dbcfd** [comment]
> Can you explain in higher-than-code level terms why the changes were required to the packet pool? We already have an af packet zero copy mode which I don't think would be that much different. Thanks!

I needed a function to invoke when suricata was done with the packet, so I could then tell the IPC code to release the packet. Did not see something that existed alright that provided a notification when suricata was done with the packet.

**Comment by victorjulien** [comment]
> > Can you explain in higher-than-code level terms why the changes were required to the packet pool? We already have an af packet zero copy mode which I don't think would be that much different. Thanks!
> 
> I needed a function to invoke when suricata was done with the packet, so I could then tell the IPC code to release the packet. Did not see something that existed already that provided a notification when suricata was done with the packet.

Have you looked at `Packet::ReleasePacket()`?

**Comment by dbcfd** [comment]
> > > Can you explain in higher-than-code level terms why the changes were required to the packet pool? We already have an af packet zero copy mode which I don't think would be that much different. Thanks!
> > 
> > 
> > I needed a function to invoke when suricata was done with the packet, so I could then tell the IPC code to release the packet. Did not see something that existed already that provided a notification when suricata was done with the packet.
> 
> Have you looked at `Packet::ReleasePacket()`?

Missed the ext function call with the data when I was looking at that. Will revert my changes around free'ing packets and resubmit the PR. Thanks @victorjulien

**Pull request closed without merging**
