### PR TITLE
fix krb5_msg_type: Unable to detect AS-REQ, TGS-REQ and KRB-ERROR v4

### PR DESCRIPTION
**Pull request by zer1t0**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4529

Previous PR: https://github.com/OISF/suricata/pull/6508
Related SV test: https://github.com/OISF/suricata-verify/pull/572

The problem is that the krb5_msg_type doesn't trigger properly for:
- AS-REQ (krb5_msg_type: 10): This rule matches the KRB-ERROR message that follows an AS-REQ, which is not the expected behaviour. 
- TGS-REQ (krb5_msg_type: 12): Same behaviour as AS-REQ.
-  KRB-ERROR (krb5_msg_type: 30) It's not triggered at all.

To solve the problem the following actions were taken in `KRB5State.parse`:
- Add transaction when parsing AS-REQ message
- Add transaction when parsing TGS-REQ message
- Change the message type of KRB-ERROR to MessageType::KRB_ERROR

suricata-verify-pr: 572

### CODE REVIEW

**Comment by catenacyber** [comment]
What were the changes from previous PR ?

**Comment by jufajardini** [comment]
Hi @zer1t0, thanks for your work so far in this issue! I saw that you didn't answer catenacyber's question. Are you still able/willing to work on this? From what I followed so far, it's near completion, right?

**Comment by victorjulien** [comment]
Closing due to inactivity. If you're interested in picking this back up, please open a new PR addressing the comments. Thanks!

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/8819

**Pull request closed without merging**
