### PR TITLE
Pr/5955/dcso/ike1/v1

### PR DESCRIPTION
**Pull request by victorjulien**
#5955 with a patch to continue working with old configs, see https://github.com/OISF/suricata/commit/3d3f813cf39c3f6540c531803d9d4158071601c4

suricata-verify-pr: 465

### CODE REVIEW

**Comment by victorjulien** [comment]
@satta @fhonza currently running this through QA

**Comment by victorjulien** [comment]
> @satta @fhonza currently running this through QA

Fully passed.

**Comment by satta** [comment]
> > @satta @fhonza currently running this through QA
> 
> Fully passed.

Yay, good news!

**Comment by victorjulien** [comment]
Replaced by #5959

**Pull request closed without merging**
