### PR TITLE
DRAFT: Multi-tenancy issue (Misc/v7)

### PR DESCRIPTION
**Pull request by victorjulien**
Var name redone in https://github.com/OISF/suricata/commit/cb7d7a43c318623f2d0186fb3e2e1760f7ded693

### CODE REVIEW

**Comment by victorjulien** [comment]
I've not yet done the work to do the "unregistration". This would require an update to the Free calls from all keywords using the var names to unregister the id's they use.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15485

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .memcap_pressure_max | 88 | 97 | 110.23% | 

Pipeline 15489

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15495

**Comment by jlucovsky** [comment]
The s-v tests fail in a few places

```
tests/eve-metadata/output/stdout:Warning: var-name: gid (type 7, id 6) still has ref_cnt 4294967294 [VarNameStoreDestroy:util-var-name.c:138]
tests/eve-metadata-04-flowvar/output/suricata.log:[109584 - Suricata-Main] 2023-08-03 13:24:15 Warning: var-name: key (type 7, id 1) still has ref_cnt 4294967295
tests/eve-metadata-04-flowvar/output/suricata.log:[109584 - Suricata-Main] 2023-08-03 13:24:15 Warning: var-name: value (type 7, id 2) still has ref_cnt 4294967295
tests/eve-metadata-04-flowvar/output/stdout:Warning: var-name: key (type 7, id 1) still has ref_cnt 4294967295 [VarNameStoreDestroy:util-var-name.c:138]
tests/eve-metadata-04-flowvar/output/stdout:Warning: var-name: value (type 7, id 2) still has ref_cnt 4294967295 [VarNameStoreDestroy:util-var-name.c:138]
```

**Comment by victorjulien** [comment]
replaced by #9340

**Pull request closed without merging**
