### PR TITLE
(7.0.x) Backport: Port grouping/v1

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- https://redmine.openinfosecfoundation.org/issues/6830
- https://redmine.openinfosecfoundation.org/issues/6520
- https://redmine.openinfosecfoundation.org/issues/6829

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1685

Note:
- I had tried to make the changes to `master` such that they'll be easy to backport and they were for the most part except that given that cleanups to `detect-*` are missing in `7.0.x` and `6.0.x` making it more effort than low to do the backports. I was just trying out what backporting would look like.
- This misses clean up commits on purpose.

### CODE REVIEW

**Review by inashivb — COMMENTED** [review]
Q1: Should we have backport tickets for all relevant port grouping issues for `7.0.x`?
Q2: Do we wanna do this for `6.0.x`?

**Comment by victorjulien** [comment]
Q1: yes
Q2: no

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 18983

**Comment by victorjulien** [comment]
I've set this to draft due to unclean history, as well as it needing the latest fixes from master. When we're ready for review, please open a new PR.

**Pull request closed without merging**
