### PR TITLE
App layer error close txs 4318 v6

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4318

Describe changes:
- app-layer: clean and "close" all txs if protocol reaches error state

Still need to test this, and check current app-layer parser returning error

Modifies #7243 with adding ticket number in message

### CODE REVIEW

**Comment by catenacyber** [comment]
One example where I am not sure how it should be dealt with :

if a HTP2 client does not send the magic banner, the app-layer parser returns an error.
Should it return an error ? or Should it try to parse further frames ?

It looks like we have two cases here :
- both client and server were recognized using the app-layer protocol
- or client and server do not talk the same protocol

PS : the banner can be split over multiple TCP packets, and the server side may have created multiple transactions before getting the error

**Comment by catenacyber** [comment]
Another case : SSH where a record has its length <= 1

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 7759

**Comment by catenacyber** [comment]
Not sure of this

**Pull request closed without merging**
