### PR TITLE
Af packet exit 6

### PR DESCRIPTION
**Pull request by regit**
Update of #3519 with rebase and build fix for netmap.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Rebase on latest master
- Build fix for netmap
- Remove useless variable in af-packet thread structure

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/424
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/206

### CODE REVIEW

**Comment by victorjulien** [comment]
Ground hog day
<pre>
util-bpf.c: In function 'SCBPFCompile':
util-bpf.c:52:36: error: passing argument 3 of 'pcap_compile' discards 'const' qualifier from pointer target type [-Werror]
     ret = pcap_compile(p, program, buf, optimize, mask);
                                    ^
In file included from suricata-common.h:193:0,
                 from util-bpf.c:25:
/usr/include/pcap.h:196:5: note: expected 'char *' but argument is of type 'const char *'
 int pcap_compile(pcap_t *, struct bpf_program *, char *, int,
     ^
cc1: all warnings being treated as errors
*** Error 1 in target 'util-bpf.o'
*** Error 1 in src (Makefile:1775 'util-bpf.o': @echo "  CC      " util-bpf.o;egcc -DHAVE_CONFIG_H -I. -I..    -I./../libhtp/  -I/usr/local/...)
*** Error 1 in . (Makefile:522 'all-recursive')
*** Error 2 in /home/qa/suricata-ci/build/suricata (Makefile:423 'all')
ERROR: Job failed: exit code 1
</pre>
OpenBSD 6.3

**Comment by regit** [comment]
Argh, forgot OpenBSD is using my grandma libpcap. Gonna address that today.Le 3 déc. 2018 11:35, Victor Julien <notifications@github.com> a écrit :Ground hog day
util-bpf.c: In function 'SCBPFCompile':
util-bpf.c:52:36: error: passing argument 3 of 'pcap_compile' discards 'const' qualifier from pointer target type [-Werror]
     ret = pcap_compile(p, program, buf, optimize, mask);
                                    ^
In file included from suricata-common.h:193:0,
                 from util-bpf.c:25:
/usr/include/pcap.h:196:5: note: expected 'char *' but argument is of type 'const char *'
 int pcap_compile(pcap_t *, struct bpf_program *, char *, int,
     ^
cc1: all warnings being treated as errors
*** Error 1 in target 'util-bpf.o'
*** Error 1 in src (Makefile:1775 'util-bpf.o': @echo "  CC      " util-bpf.o;egcc -DHAVE_CONFIG_H -I. -I..    -I./../libhtp/  -I/usr/local/...)
*** Error 1 in . (Makefile:522 'all-recursive')
*** Error 2 in /home/qa/suricata-ci/build/suricata (Makefile:423 'all')
ERROR: Job failed: exit code 1

OpenBSD 6.3

**Comment by victorjulien** [comment]
Btw, unless you specifically tested the netmap patch, please drop that one for now.

**Comment by regit** [comment]
I did run test it on a VMLe 3 déc. 2018 12:07, Victor Julien <notifications@github.com> a écrit :Btw, unless you specifically tested the netmap patch, please drop that one for now.

**Comment by regit** [comment]
We could simply do that:
```
diff --git a/src/util-bpf.c b/src/util-bpf.c
index 7a23d0b56..ced17d2ed 100644
--- a/src/util-bpf.c
+++ b/src/util-bpf.c
@@ -38,7 +38,12 @@ void SCBPFFree(struct bpf_program *program)
 }
 
 int SCBPFCompile(int snaplen_arg, int linktype_arg, struct bpf_program *program,
-                 const char *buf, int optimize, uint32_t mask,
+#if defined __OpenBSD__
+                 char *buf,
+#else
+                 const char *buf,
+#endif
+                 int optimize, uint32_t mask,
                  char *errbuf, size_t errbuf_len)
 {
     pcap_t *p;
```
but not sure it is a good solution as OpenBSD may one day switch to a newer version.

**Comment by regit** [comment]
OK, think I got it. We don't use pcap_compile options in OpenBSD so we can just have an empty code.

**Pull request closed without merging**
