### PR TITLE
test: do not output non ascii character

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- Fix CI by not having S-V hang indefinitely because of a non-ascii character in stderr

### CODE REVIEW

**Comment by catenacyber** [comment]
cc @jasonish as IIRC, you worked on this

**Comment by jasonish** [comment]
I guess this will prevent the error if the unprintable character is in the content?  What if its somewhere else in the rule.  For example:
```
[3795129] 15/9/2022 -- 09:03:04 - (detect-parse.c:1224) <Error> (SigParse) -- [ERRCODE: SC_ERR_RULE_INVALID_UTF8(336)] - rule is not valid UTF-8
[3795129] 15/9/2022 -- 09:03:04 - (detect-engine-loader.c:191) <Error> (DetectLoadSigFile) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ip any any -> any any (msg: "test"; content:"|a�|"; sid: 1;)" from file ./test.rules at line 1
```
point being, that the outer parser may print the whole rule as well, which would probably recreate this issue.  Not really sure how we should deal with this.  If its only to deal with S-V, then we should fix it at  SV and leave this alone.

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw1_files_sha256.

ERROR: QA failed on ips_afp_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .app_layer.error.http.parser | 64 | 47 | 73.44% |
| | tlpr1_stats_chk | | |
| .app_layer.error.http.parser | 1548 | 1103 | 71.25% |
| | ips_afp_stats_chk | | |
| .capture.kernel_drops | 0 | 283564 | - |
| .flow.end.tcp_state.syn_sent | 0 | 484 | - |
| .flow.end.tcp_state.syn_recv | 0 | 93 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 84 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 80 | - |
| .flow.end.tcp_state.time_wait | 0 | 70 | - |
| .flow.end.tcp_state.last_ack | 0 | 64 | - |
| .flow.end.tcp_state.close_wait | 0 | 185 | - |
| .tcp.reassembly_gap | 108000 | 126493 | 117.12% |
| .tcp.overlap | 0 | 19 | - |
| .app_layer.error.http.parser | 0 | 38 | - |
| .app_layer.error.ftp.gap | 0 | 46 | - |
| .app_layer.error.smtp.gap | 0 | 287 | - |
| .app_layer.error.tls.gap | 0 | 4699 | - |
| .app_layer.error.ssh.gap | 0 | 1 | - |
| .app_layer.error.dcerpc_tcp.parser | 0 | 169 | - |
| .ftp.memuse | 0 | 563 | - |
| | generic_stats_chk | | |
| .capture.kernel_drops | 0 | 100506 | - |
| .flow.end.tcp_state.syn_sent | 0 | 151 | - |
| .flow.end.tcp_state.syn_recv | 0 | 1 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 26 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 3 | - |
| .flow.end.tcp_state.time_wait | 0 | 9 | - |
| .flow.end.tcp_state.last_ack | 0 | 10 | - |
| .flow.end.tcp_state.close_wait | 0 | 36 | - |
| .tcp.reassembly_gap | 80952 | 90614 | 111.94% |
| .app_layer.error.http.parser | 0 | 10 | - |
| .app_layer.error.ftp.gap | 0 | 2 | - |
| .app_layer.error.smtp.gap | 0 | 13 | - |
| .app_layer.error.dcerpc_tcp.parser | 0 | 5 | - | 

Pipeline 9214

**Comment by catenacyber** [comment]
> I guess this will prevent the error if the unprintable character is in the content? What if its somewhere else in the rule. For example:
> 

As I see it, the purpose of this PR is not to be complete but to fix CI asap.
So, I fixed the only non-ascii output in unit tests...

Maybe we can create a ticket for other such problems...

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7871

**Pull request closed without merging**
