### PR TITLE
Add JA3S fingerprint support

### PR DESCRIPTION
**Pull request by thus**
This pull request implements JA3S fingerprints as implemented in the bro script in the JA3 github repo:
https://github.com/salesforce/ja3/blob/master/bro/ja3s.bro

Updates:
- Fixed changes requested in #3850 

Redmine:
https://redmine.openinfosecfoundation.org/issues/2684

- PR thus-pcap: https://buildbot.openinfosecfoundation.org/builders/thus-pcap/builds/187
- PR thus: https://buildbot.openinfosecfoundation.org/builders/thus/builds/187

### CODE REVIEW

**Comment by thus** [comment]
suricata-verify testcases:
https://github.com/OISF/suricata-verify/pull/59

**Comment by norg** [comment]
docs look good for me

**Comment by victorjulien** [comment]
Looks good. Could you rebase it to master though? I get conflicts. Thanks!

**Comment by thus** [comment]
Replaced by #3874

**Pull request closed without merging**
