### PR TITLE
rust: cargo clippy --fix

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- rust: cargo clippy --fix

Some changes in jsonbuilder.rs

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17318

**Review by victorjulien — CHANGES_REQUESTED** [review]
Can you include the clippy error in the commit message? Looking at the diff it isn't clear what changes

**Comment by catenacyber** [comment]
> Can you include the clippy error in the commit message? 

I looked for it and did not find it.

> Looking at the diff it isn't clear what changes

Indeed. Just reordering things apparently

**Comment by jasonish** [comment]
Looks like its force the tests to be at the end of a file.  Thats a bit much for a linter to fixup IMO.

But a plain old clippy doesn't complain at all, but the lint is `+#![warn(clippy::items_after_test_module)]`, which we could fix as it comes up, or add an ignore for it.

**Comment by catenacyber** [comment]
> but the lint is +#![warn(clippy::items_after_test_module)], which we could fix as it comes up, or add an ignore for it.

How did you find it ?

**Comment by jasonish** [comment]
> > but the lint is +#![warn(clippy::items_after_test_module)], which we could fix as it comes up, or add an ignore for it.
> 
> How did you find it ?

I just ran `cargo clippy --fix --all-features` locally.

**Comment by catenacyber** [comment]
🤔 I just have `Fixed src/jsonbuilder.rs (1 fix)`. 

I also see many warnings, the last one being
```
warning: items after a test module
  --> src/feature.rs:26:1
   |
26 | mod mock {
   | ^^^^^^^^
...
60 | pub use mock::*;
   |         ^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
   = note: `#[warn(clippy::items_after_test_module)]` implied by `#[warn(warnings)]`
```

**Comment by jasonish** [comment]
> 🤔 I just have `Fixed src/jsonbuilder.rs (1 fix)`.
> 
> I also see many warnings, the last one being
> 
> ```
> warning: items after a test module
>   --> src/feature.rs:26:1
>    |
> 26 | mod mock {
>    | ^^^^^^^^
> ...
> 60 | pub use mock::*;
>    |         ^^^^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
>    = note: `#[warn(clippy::items_after_test_module)]` implied by `#[warn(warnings)]`
> ```

Wonder why it didn't fix that one?

> 🤔 I just have `Fixed src/jsonbuilder.rs (1 fix)`.
> 
> I also see many warnings, the last one being
> 
> ```
> warning: items after a test module
>   --> src/feature.rs:26:1
>    |
> 26 | mod mock {
>    | ^^^^^^^^
> ...
> 60 | pub use mock::*;
>    |         ^^^^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
>    = note: `#[warn(clippy::items_after_test_module)]` implied by `#[warn(warnings)]`
> ```

Can you pull this in if doing a new version of the PR? https://github.com/OISF/suricata/commit/78ae058488abf5cb261fedd5e4733e4061705cd6

**Comment by victorjulien** [comment]
> Looks like its force the tests to be at the end of a file. Thats a bit much for a linter to fixup IMO.
> 
> But a plain old clippy doesn't complain at all, but the lint is `+#![warn(clippy::items_after_test_module)]`, which we could fix as it comes up, or add an ignore for it.

Can we disable this lint globally in `rust/src/lib.rs`? I agree that this is beyond what the linter should flag.

**Comment by catenacyber** [comment]
> Can we disable this lint globally in `rust/src/lib.rs`? I agree that this is beyond what the linter should flag.

Done in https://github.com/OISF/suricata/pull/10109

**Pull request closed without merging**
