### PR TITLE
dcerpc: return error on invalid header

### PR DESCRIPTION
**Pull request by inashivb**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/7230

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.dcerpc_tcp | 4185 | 40 | 0.96% |
| .app_layer.tx.dcerpc_tcp | 5949 | 4165 | 70.01% |
| .app_layer.error.dcerpc_tcp.parser | 6248 | 10393 | 166.34% | 

Pipeline 22285

**Comment by inashivb** [comment]
> WARNING:
> field 	baseline 	test 	%
> 	SURI_TLPR1_stats_chk 		
> .app_layer.flow.dcerpc_tcp 	4185 	40 	0.96%
> .app_layer.tx.dcerpc_tcp 	5949 	4165 	70.01%
> .app_layer.error.dcerpc_tcp.parser 	6248 	10393 	166.34%
> 
> Pipeline 22285

- Based on the smaller pcap of this given by Corey, my analysis is that these stat deviations are likely correct. This is because of the following.

|`master`|`this PR`|
|-------------|------------|
|Invalid header -> returns `Ok` from the parser|Invalid header -> returns `Error` from the parser|

and there's a lot of traffic which is not `dcerpc` and has invalid header.
- Most parsing errors report version mismatches like `Major version: 77 Minor version: 97` and return Ok.
For the reference, valid header should have: `Major version: 5 Minor version: 0` for `dcerpc/tcp`..

**Important to note**:
1. Probing does not seem to run for every input.
2. The pcap contains SMB/DCERPC traffic so not sure why this parser is even invoked. The parser however seems to work correctly. It receives in order:
- A valid `DCERPC` pkt
- Trailing data from `NBSS` (This is rejected by the parser as the header validation fails. This is correct.)

**Comment by victorjulien** [comment]
I'm not sure I understand the stats deviation. The PP is more strict, which leads to fewer dcerpc/tcp flows/txs, which is fine if that is correct. But why do we get more parser errors on fewer flows?

**Comment by inashivb** [comment]
> I'm not sure I understand the stats deviation. The PP is more strict, which leads to fewer dcerpc/tcp flows/txs, which is fine if that is correct. But why do we get more parser errors on fewer flows?

Because it's not dcerpc traffic that is being sent to the dcerpc parser which (now) results in header validation errors.
Please note that the probing does not run for every input so the header validation fails when the control reaches to the request/response parsers.

**Comment by victorjulien** [comment]
It doesn't make sense to me. If more traffic that is not dcerpc is sent to the parser, then it should be reflected in `.app_layer.flow.dcerpc_tcp` and `.app_layer.tx.dcerpc_tcp`, but these are lower. So less traffic is sent, but it generates more errors?

**Comment by inashivb** [comment]
> It doesn't make sense to me. If more traffic that is not dcerpc is sent to the parser, then it should be reflected in `.app_layer.flow.dcerpc_tcp` and `.app_layer.tx.dcerpc_tcp`, but these are lower. So less traffic is sent, but it generates more errors?

ok. thank you for explaining your concern. I'll follow the call path in case of Applayer::Err and share why this is happening. Perhaps that'll help me see better if and what I'm doing wrong or if my understanding is flawed.

**Comment by catenacyber** [comment]
Just putting here review of TLPR pcap dce_tcp_9149.pcap

This pcap looks definitely odd in just one packet :
All is good except packet 6 whose tcp payload seems junk, instead of a DCERPC bind ack as expected (and the next packets seem to show that client and server agreed to the bind)
TCP sequences, ack, checksum are all correct...

I think that Suricata should just skip this packet analysis...

**Comment by victorjulien** [comment]
> Just putting here review of TLPR pcap dce_tcp_9149.pcap
> 
> This pcap looks definitely odd in just one packet : All is good except packet 6 whose tcp payload seems junk, instead of a DCERPC bind ack as expected (and the next packets seem to show that client and server agreed to the bind) TCP sequences, ack, checksum are all correct...
> 
> I think that Suricata should just skip this packet analysis...

Skip how? You'd need to parse the data to know its invalid, right? And invalid data is something we care about, e.g. for setting an event.

**Comment by inashivb** [comment]
> It doesn't make sense to me. If more traffic that is not dcerpc is sent to the parser, then it should be reflected in `.app_layer.flow.dcerpc_tcp` and `.app_layer.tx.dcerpc_tcp`, but these are lower. So less traffic is sent, but it generates more errors?

We do not seem to increment the flow counter if the applayer parser returned an error: https://github.com/OISF/suricata/blob/master/src/app-layer.c#L660
Q: Is this incorrect? This seems to explain the less number of flows now that the header validation is stricter.. 

Note that if I do update the flow counter in the error condition, it starts to be close to the original stats.

**Comment by victorjulien** [comment]
> > It doesn't make sense to me. If more traffic that is not dcerpc is sent to the parser, then it should be reflected in `.app_layer.flow.dcerpc_tcp` and `.app_layer.tx.dcerpc_tcp`, but these are lower. So less traffic is sent, but it generates more errors?
> 
> We do not seem to increment the flow counter if the applayer parser returned an error: https://github.com/OISF/suricata/blob/master/src/app-layer.c#L660 Q: Is this incorrect? This seems to explain the less number of flows now that the header validation is stricter..
> 
> Note that if I do update the flow counter in the error condition, it starts to be close to the original stats.

Yes I feel this is incorrect. We should count the protocols we detected, regardless of whether we encounter parsing errors. If the detection was incorrect, we should improve the detection logic.

**Pull request closed without merging**
