### PR TITLE
Rfb rust keywords 3195 v2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/3195 justify everything

Describe changes:
- rfb: move keywords to pure rust
- rfb: move app-layer to pure rust as well, and convert unit test to SV one

Coming after the MQTT merged PR https://github.com/OISF/suricata/pull/11502, and before other protocols

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1986

https://github.com/OISF/suricata/pull/11518 with typo in commit message fix, and more SV tests

cc @satta

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21632

**Review by jufajardini — COMMENTED** [review]
As with the previous, the code looks good, so just think we should discuss and agree upon whether or not to have individual tickets per app-proto to track these changes.

**Comment by catenacyber** [comment]
> As with the previous, the code looks good, so just think we should discuss and agree upon whether or not to have individual tickets per app-proto to track these changes.

Thanks Juliana, I created https://redmine.openinfosecfoundation.org/issues/7178

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11560

**Pull request closed without merging**
