### PR TITLE
detect/pcre: Use pcre_jit_exec when possible

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #4655

This PR uses `pcre_jit_exec` when available with the `pcre` keyword. It also refactors like code across most of the detect modules into helper functions in `detect-parse.c`

- The refactoring of PCRE related code across dozens of detect modules
- Using `pcre_jit_exec` in the PCRE detect module for recurring patterns

Redmine issue:[749](https://redmine.openinfosecfoundation.org/issues/749)

This update
- Addresses CI error.

### CODE REVIEW

**Comment by victorjulien** [comment]
nit: commit messages are missing colon after 'detect/parse' and 'detect/pcre'.

**Comment by victorjulien** [comment]
Several of my builders fail with:
```
[21325] 12/3/2020 -- 12:19:57 - (util-checksum.c:88) <Info> (ChecksumAutoModeCheck) -- No packets with invalid checksum, assuming checksum offloading is NOT used
AddressSanitizer:DEADLYSIGNAL
=================================================================
==21324==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fb90afbf69d bp 0x7fb8f262e370 sp 0x7fb8f262e250 T17)
==21324==The signal is caused by a READ memory access.
==21324==Hint: address points to the zero page.
    #0 0x7fb90afbf69c  (<unknown module>)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
Thread T17 (W#16) created by T0 (Suricata-Main) here:
    #0 0x7fb92dc32805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x55e4204e7423 in TmThreadSpawn /builds/inliniac/suricata-ci/suricata/src/tm-threads.c:1765
    #2 0x55e420401230 in RunModeFilePcapAutoFp /builds/inliniac/suricata-ci/suricata/src/runmode-pcap-file.c:252
    #3 0x55e4204119fd in RunModeDispatch /builds/inliniac/suricata-ci/suricata/src/runmodes.c:377
    #4 0x55e4204d0b28 in SuricataMain /builds/inliniac/suricata-ci/suricata/src/suricata.c:3077
    #5 0x55e42032b102 in main /builds/inliniac/suricata-ci/suricata/src/main.c:22
    #6 0x7fb92caca1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
==21324==ABORTING
ERROR: Job failed: exit code 1
```
I can reproduce, but it has the same useless backtrace.

**Comment by victorjulien** [comment]
Recompiled w/o ASAN and then running in valgrind doesn't help much either:
```
==8540== Thread 12 W#10:
==8540== Conditional jump or move depends on uninitialised value(s)
==8540==    at 0x1AD801DA: ???
==8540==    by 0x1785F437: ???
==8540==    by 0x1785F437: ???
==8540==    by 0x1785F44C: ???
==8540==    by 0x43E6C08F: ???
==8540==    by 0x1: ???
==8540== 
==8540== Conditional jump or move depends on uninitialised value(s)
==8540==    at 0x1AD801DA: ???
==8540==    by 0x20C71F97: ???
==8540==    by 0x20C71F97: ???
==8540==    by 0x20C71FAE: ???
==8540==    by 0x43E6C08F: ???
==8540==    by 0x1: ???
==8540== 
==8540== Thread 3 W#01:
==8540== Conditional jump or move depends on uninitialised value(s)
==8540==    at 0x1AD801DA: ???
==8540==    by 0x14919937: ???
==8540==    by 0x14919937: ???
==8540==    by 0x1491994C: ???
==8540==    by 0x3F66308F: ???
```

**Comment by jlucovsky** [comment]
Continued in #4688

**Pull request closed without merging**
