### PR TITLE
unittest conversion to FAIL/PASS API - Outreachy/20221214/v1

### PR DESCRIPTION
**Pull request by jufajardini**
- https://github.com/OISF/suricata/pull/8283
- https://github.com/OISF/suricata/pull/8261

Redmine tickets:
- https://redmine.openinfosecfoundation.org/issues/4019
- https://redmine.openinfosecfoundation.org/issues/4029

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104017 | 81.11% | 

Pipeline 11207

**Comment by jufajardini** [comment]
Took the chance to update the copyright years for those files

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104029 | 81.12% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 35359 | 0.01 | 

Pipeline 11213

**Comment by jufajardini** [comment]
Main PRs have been already merged through https://github.com/OISF/suricata/pull/8288, so closing this one.

**Pull request closed without merging**
