### PR TITLE
Backports/60x/v4

### PR DESCRIPTION
**Pull request by victorjulien**
#10885 with one additional fixup to get my release pipeline unstuck.

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
LGTM

The last commit is not needed in master ?

**Comment by victorjulien** [comment]
> LGTM
> 
> The last commit is not needed in master ?

Not seeing the compile warning, so I guess not.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20133

**Comment by victorjulien** [comment]
Merged in #10895, thanks!

**Pull request closed without merging**
