### PR TITLE
userguide/install: add info on arch-based install

### PR DESCRIPTION
**Pull request by JSkier21**
userguide/install: add info on arch-based install

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Add ArchLinux based install information to documentation.

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hi there, thanks for this contribution :)

Could you please adjust the commit message so it will comply with our [commit guidelines](https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits)?
In short, something like `userguide/install: add info on arch-based install` works. The commit body is fine.

For our documentation, we're also trying to keep lines at a 79/80 characters limit, following Sphinx/Rst suggestions.

**Comment by jufajardini** [comment]
> Should be ready to go?

We have to adjust character limit per line, and the commit message, but this is something that I can do, this time, if need be :)

**Comment by jufajardini** [comment]
> > Should be ready to go?
> 
> We have to adjust character limit per line, and the commit message, but this is something that I can do, this time, if need be :)

Hey @JSkier21 do you want me to fix this one up?

**Comment by JSkier21** [comment]
> > > Should be ready to go?
> > 
> > 
> > We have to adjust character limit per line, and the commit message, but this is something that I can do, this time, if need be :)
> 
> Hey @JSkier21 do you want me to fix this one up?

Certainly please, if you don't mind. I haven't had time to delve into this much lately, but I'll try to take notes on what you do for next time 🙂

**Comment by jufajardini** [comment]
> > > > Should be ready to go?
> > > 
> > > 
> > > We have to adjust character limit per line, and the commit message, but this is something that I can do, this time, if need be :)
> > 
> > 
> > Hey @JSkier21 do you want me to fix this one up?
> 
> Certainly please, if you don't mind. I haven't had time to delve into this much lately, but I'll try to take notes on what you do for next time slightly_smiling_face

Ok, I'll submit a new PR with the preferred way, then you can compare and get a better idea of the guidelines ^^

**Comment by jufajardini** [comment]
Changes requested incorporated in: https://github.com/OISF/suricata/pull/8972

**Comment by JSkier21** [comment]
> > > > > Should be ready to go?
> > > > 
> > > > 
> > > > We have to adjust character limit per line, and the commit message, but this is something that I can do, this time, if need be :)
> > > 
> > > 
> > > Hey @JSkier21 do you want me to fix this one up?
> > 
> > 
> > Certainly please, if you don't mind. I haven't had time to delve into this much lately, but I'll try to take notes on what you do for next time slightly_smiling_face
> 
> Ok, I'll submit a new PR with the preferred way, then you can compare and get a better idea of the guidelines ^^

Much appreciated, thank you!

**Pull request closed without merging**
