### PR TITLE
[draft] Libcapture/v3

### PR DESCRIPTION
**Pull request by jasonish**
Draft for QA purposes.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22238

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22247

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22256

**Comment by jasonish** [comment]
Replaced by: https://github.com/OISF/suricata/pull/11711

**Pull request closed without merging**
