### PR TITLE
smb: fix flag parsing; set event when records in wrong direction - v4

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/7084

Changes from last PR:
- naming: reply -> response
- direction methods for smb2

Ticket: https://redmine.openinfosecfoundation.org/issues/4945

#suricata-verify-pr: 768

### CODE REVIEW

**Comment by victorjulien** [comment]
Any idea why CI fails?

**Comment by jasonish** [comment]
> Any idea why CI fails?

Yeah, that verify PR requires support for alerts on frames.  So its in reference to preparing an S-V test for this, but I guess still draft status.

**Comment by jasonish** [comment]
SV passes when not using that SV-PR.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 6454

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #7112, thanks!

**Pull request closed without merging**
