### PR TITLE
output: Remove registration of standalone output logging where EVE is also used

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #5290 
This PR removes the standalone output logging registrations where they are no longer relevant due to EVE multi instance handling.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [3178](https://redmine.openinfosecfoundation.org/issues/3178)

Describe changes:
- Remove unused output init/de-init functions

suricata-verify-pr: 316
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by catenacyber** [comment]
Lots of code removal ❤️

**Comment by jlucovsky** [comment]
@victorjulien Travis CI failed because it's not using the updated S-V test (pr 316)

**Comment by catenacyber** [comment]
Indeed, I think Travis, instead of other GitHub workflows, uses libhtp and suricata-verify default branches

**Comment by victorjulien** [comment]
Merged in #5356, thanks!

**Pull request closed without merging**
