### PR TITLE
Add NULL pointer guard on fclose when reopening.

### PR DESCRIPTION
**Pull request by eroullit**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Fix segfault on logrotate

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable): N/A

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you add a ticket to our redmine for this?

I'm sort of curious how fp can be NULL btw, does that mean we're missing error checks somewhere before?

**Comment by eroullit** [comment]
To trigger this, I use have made following changes in a vanilla `suricata.yaml`:
```
run-as:
  user: emmanuel.roullit
  group: dev
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      rotate-interval: minute
```
Then I followed this procedure:
```sh
$ mkdir logs
$ suricata -c suricata.yaml -l logs -i enp0s25 # in a seperate terminal
$ sudo chown -R root:root logs
$ kill -HUP $(pgrep Suricata)
```
The suricata output:
```
[...]
[30090] 28/3/2019 -- 11:35:36 - (tm-threads.c:2157) <Notice> (TmThreadWaitOnThreadInit) -- all 4 packet processing threads, 4 management threads initialized, engine started.
[30102] 28/3/2019 -- 11:36:25 - (util-logopenfile.c:283) <Error> (SCLogOpenFileFp) -- [ERRCODE: SC_ERR_FOPEN(44)] - Error opening file: "logs/eve.json": Permission denied
[30102] 28/3/2019 -- 11:36:25 - (util-logopenfile.c:283) <Error> (SCLogOpenFileFp) -- [ERRCODE: SC_ERR_FOPEN(44)] - Error opening file: "logs/stats.log": Permission denied
```
The files could not be opened, `log_fp` is `NULL` and the next reopen makes a `fclose(NULL)`
Meanwhile when attached to `gdb`:
```
Thread 7 "FR#01" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff0ee7700 (LWP 30100)]
_IO_new_fclose (fp=0x0) at iofclose.c:48
48      iofclose.c: No such file or directory.
(gdb) bt
#0  _IO_new_fclose (fp=0x0) at iofclose.c:48
#1  0x00000000005daaac in SCConfLogReopen (log_ctx=0x19a22c0) at util-logopenfile.c:503
#2  0x00000000005dabb3 in SCLogFileWrite (buffer=0x7fffd4000b90 "{\"timestamp\":\"2019-03-28T11:37:02.000552+0100\",\"flow_id\":1756433916848993,\"event_type\":\"flow\",\"src_ip\":\"fe80:0000:0000:0000:f229:29ff:fef1:58f1\",\"src_port\":546,\"dest_ip\":\"ff02:0000:0000:0000:0000:0000"..., buffer_len=<optimized out>, 
    log_ctx=0x19a22c0) at util-logopenfile.c:208
#3  0x00000000005daf83 in LogFileWrite (file_ctx=file_ctx@entry=0x19a22c0, buffer=0x7fffd4000b80) at util-logopenfile.c:584
#4  0x000000000056f388 in OutputJSONBuffer (js=js@entry=0x7fffd4010bf0, file_ctx=0x19a22c0, buffer=buffer@entry=0x7fffd4000b68) at output-json.c:819
#5  0x000000000055d726 in JsonFlowLogger (tv=<optimized out>, thread_data=0x7fffd4000b60, f=0x162fc00) at output-json-flow.c:382
#6  0x000000000054b8b0 in OutputFlowLog (tv=tv@entry=0x19a7d50, thread_data=<optimized out>, f=f@entry=0x162fc00) at output-flow.c:112
#7  0x0000000000528a7f in FlowRecycler (th_v=0x19a7d50, thread_data=0x7fffd4000b20) at flow-manager.c:917
#8  0x00000000005ae432 in TmThreadsManagement (td=0x19a7d50) at tm-threads.c:704
#9  0x00007ffff67676db in start_thread (arg=0x7ffff0ee7700) at pthread_create.c:463
#10 0x00007ffff59ad88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by eroullit** [comment]
Opened a ticket on redmine: https://redmine.openinfosecfoundation.org/issues/2909

**Comment by victorjulien** [comment]
Merged in #3772, thanks Emmanuel!

**Pull request closed without merging**
