### PR TITLE
protodetect: handle when multiple patterns match

### PR DESCRIPTION
**Pull request by catenacyber**
This PR is for discussion rather than straight merging.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2757

Describe changes:
- Keep searching when multiple patterns are found for protocol detection

Modifies #4152 with improved handling
Fixes #4606 with fixed compilation

First, we run probing parsers, restricted to the protocols found by pattern matching.
If that fails (and it should not), we run all probing parsers.

Probing parsers, ie `PPGetProto` return first successful protocol and not a list of successful protocols
Do we assume that  probing parsers do not overlap ?
In this case, we should check (with fuzzing?) that it is the case.
Otherwise, we should extend this PR

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you add a SV test for this as well?

**Comment by catenacyber** [comment]
> Can you add a SV test for this as well?

Ok, I will

Why did you mark this PR as draft ?

**Comment by inliniac** [comment]
On 24-07-2020 13:26, Catena cyber wrote:
>     Can you add a SV test for this as well?
> 
> Ok, I will
> 
> Why did you mark this PR as draft ?

Because its not meant for merge as is stated in the body.


-- 
---------------------------------------------
Victor Julien
http://www.inliniac.net/
PGP: http://www.inliniac.net/victorjulien.asc
---------------------------------------------

**Comment by catenacyber** [comment]
Indeed, and S-V test will help, thanks :-)

**Comment by catenacyber** [comment]
I tried a pcap with `GET /EHLO` and one with `SSH-\xffSMB` and I always got 1 pattern match instead of 2

My guess is that the MPM stops on the first pattern it finds.
So we cannot find more than one pattern.
Next PR is `DEBUG_VALIDATE_BUG_ON` to check this (with fuzzing)

**Comment by victorjulien** [comment]
> I tried a pcap with `GET /EHLO` and one with `SSH-\xffSMB` and I always got 1 pattern match instead of 2
> 
> My guess is that the MPM stops on the first pattern it finds.

The EHLO pattern will only be found in the first 4 bytes, so it makes sense it won't detect it here. But the SSH/SMB pattern is different, I would expect that to match. Can you share the pcaps?

**Comment by catenacyber** [comment]
> But the SSH/SMB pattern is different, I would expect that to match. 

I thought so as well

> Can you share the pcaps?

https://redmine.openinfosecfoundation.org/issues/2757#note-24

**Pull request closed without merging**
