### PR TITLE
Detect negated content absent buffer 2224 v24

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2224

Describe changes:
- detect: adds `absent` keyword to match on absent buffer

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1957

https://github.com/OISF/suricata/pull/11906 rebased to get green CI and history

Still the question of transforms : do you see a use case of buffer + transform + absent keyword ?
Or should we explicitly forbid it ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23116

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
Funky Suricon announcement coming 🎊  :-)

**Comment by victorjulien** [comment]
Get issues on openbsd
image

**Comment by catenacyber** [comment]
```
detect-absent-file-multi/input.pcap:           pcap capture file, microsecond ts, extensions (little-endian) - version 2.4 (No link-layer encapsulation, capture length 262144)
detect-absent-http-request-body/input.pcap:    pcap capture file, microsecond ts, extensions (little-endian) - version 2.4 (No link-layer encapsulation, capture length 262144)
detect-absent-negated-content/no_referer.pcap: pcap capture file, microsecond ts (little-endian) - version 2.4 (Ethernet, capture length 65535)
```

These extensions seem bad

**Comment by catenacyber** [comment]
Just updated SV pcaps with Wireshark resaving them, can you retry it ?

**Comment by victorjulien** [comment]
Can you submit a rebased PR here and in SV? Combination doesn't pass for me currently.

**Comment by catenacyber** [comment]
> Can you submit a rebased PR here and in SV? Combination doesn't pass for me currently.

Done in https://github.com/OISF/suricata/pull/12162

**Pull request closed without merging**
