### PR TITLE
http2: support deflate decompression

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4556

Describe changes:
- Support for deflate decompression over HTTP2

suricata-verify-pr: 515

https://github.com/OISF/suricata-verify/pull/515

### CODE REVIEW

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by suricata-qa** [comment]
Information:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |

**Comment by victorjulien** [comment]
I rebased this to master and ran the SV test, but it fails. Not sure if something recent in master caused this somehow. Can you have a look?

**Comment by catenacyber** [comment]
Investigating : transaction got freed before the call to `JsonBuildFileInfoRecord`

I think this is an effect of https://github.com/OISF/suricata/pull/5999
I think it is not related to this HTTP2 PR, it is just that the new S-V test shows it

**Comment by catenacyber** [comment]
Got it : https://github.com/OISF/suricata/pull/6329

**Pull request closed without merging**
