### PR TITLE
Fm row fix/v3

### PR DESCRIPTION
**Pull request by victorjulien**
Flow manager multi instance fixes.

Fix start issue with #12208

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
Tests well. LGTM 🚀

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 32421 | 36200 | 111.66% |
| .app_layer.flow.dcerpc_tcp | 40 | 43 | 107.5% |
| .app_layer.error.http.parser | 700 | 729 | 104.14% |
| .app_layer.error.ssh.parser | 124 | 128 | 103.23% |
| .ftp.memuse | 2906 | 3102 | 106.74% | 

Pipeline 23717

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 32421 | 36200 | 111.66% |
| .app_layer.flow.dcerpc_tcp | 40 | 43 | 107.5% |
| .app_layer.error.http.parser | 700 | 729 | 104.14% |
| .app_layer.error.ssh.parser | 124 | 128 | 103.23% |
| .ftp.memuse | 2906 | 3102 | 106.74% | 

Pipeline 23720

**Comment by victorjulien** [comment]
@ct0br0 for the alert top 500 redistribution, how do the numbers look for the ones that dropped out of the top 500? Do they have at least the same number as in master?

**Comment by victorjulien** [comment]
Merged in #12245, thanks!

**Pull request closed without merging**
