### PR TITLE
suricata: remove --disable-hashing option

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7352

Describe changes:
- suricata: remove --disable-hashing option

Was added by f723dc1309a793f6fbcf81d6507fe946b4caa04a because of nss (cc @jasonish )

### CODE REVIEW

**Comment by jasonish** [comment]
Do we want to remove this?  Before we removed `nss`, we knew of users would deliberately built Suricata without `nss` as a means to disable hashing.  When we moved hashing to Rust, where it was always available and no longer a compile time option, we added this command line option as a way to disable hashing, as the user could no longer do it as a compile time option.

**Comment by jasonish** [comment]
Relevant discussion: https://github.com/OISF/suricata/pull/5676#issuecomment-749973744

**Comment by victorjulien** [comment]
> Do we want to remove this? Before we removed `nss`, we knew of users would deliberately built Suricata without `nss` as a means to disable hashing. When we moved hashing to Rust, where it was always available and no longer a compile time option, we added this command line option as a way to disable hashing, as the user could no longer do it as a compile time option.

Yeah probably want to keep this.

**Comment by catenacyber** [comment]
Thanks for the link

Was not the problem that nss used a mutex for hashing ?

Anyways, moving to draft while discussing...

**Comment by jasonish** [comment]
> Thanks for the link
> 
> Was not the problem that nss used a mutex for hashing ?
> 
> Anyways, moving to draft while discussing...

I can't actually remember the use case.. Performance maybe?  I also want to say there was some who didn't want nss/nspr linked in for whatever reason, but if that was the case we probably would have used a rust compile time flag to compile out the hashing. Would just be simpler to get rid of it, as I'm pretty sure we're using the hash functions and not respecting this flag in some cases.

**Comment by catenacyber** [comment]
Are you saying a configure/compile-time option to disable hashing would be better than a runtime command line option ?

**Comment by jasonish** [comment]
> Are you saying a configure/compile-time option to disable hashing would be better than a runtime command line option ?

Depends on the use case. If the goal is to just disable hashing, then no. If the goal is not have that crypto code in the binary, then yes.  With NSS, disabling NSS accomplished both.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23209

**Comment by catenacyber** [comment]
Anyways, I do not want to be controversial for this... so closing this PR, and the discussion about if the ticket is needed can go in the ticket.

**Pull request closed without merging**
