### PR TITLE
detect: absent keyword to test absence of sticky buffer

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2224

Describe changes:
- detect: adds `absent` keyword to match on absent buffer

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1957

https://github.com/OISF/suricata/pull/11375 with newer tests, some engine analysis, and ability to express "if there is no user agent, or if it exists and is XYZ, then match"

### CODE REVIEW

**Comment by catenacyber** [comment]
Draft to check CI with fixup commit

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21385

**Comment by inashivb** [comment]
> Draft to check CI with fixup commit

I think there's a new different failure w the fuzz job. Your PR seems to be doing well.
Do you want to rebase and check the fuzz build issue?

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11459

**Pull request closed without merging**
