### PR TITLE
Multipart mime 3487 v13

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser

Follows #8385 by rebasing and fixing conflicts

Still to do : 
- get answers for https://github.com/OISF/suricata/pull/8326 questions
- wait for QA rebase with bigger `request-body-limit`

suricata-verify-pr: 1035

QA SURI_TLPW1_files_sha256 is still expected show a difference about HTTP files, because there are files bigger than default suricata.yaml `request-body-limit` and the files are not "chunked" the same way (this PR seems more complete than current master). Solution would be to have QA use a higher `request-body-limit` to have complete files (but it will need a QA rebase because hashes will be updated)

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_single_stats_chk | | |
| .tcp.ssn_from_cache | 264554 | 339671 | 128.39% |
| .tcp.ssn_from_pool | 628437 | 553320 | 88.05% |
| | SURI_TLPW2_autofp_stats_chk | | |
| .tcp.ssn_from_cache | 298547 | 381090 | 127.65% |
| .tcp.ssn_from_pool | 594444 | 511901 | 86.11% |
| | SURI_TLPW1_stats_chk | | |
| .tcp.ssn_from_cache | 63596 | 79000 | 124.22% |
| .tcp.ssn_from_pool | 139220 | 123816 | 88.94% |
| .tcp.rst | 128116 | 113554 | 88.63% |
| .app_layer.error.dns_udp.parser | 1276 | 0 | - |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 580947328 | 2761850848 | 475.4% |
| .tcp.ssn_from_cache | 3644947 | 6088050 | 167.03% |
| .tcp.ssn_from_pool | 8484810 | 6041676 | 71.21% |
| .tcp.synack | 7538139 | 10171103 | 134.93% |
| .tcp.rst | 5264608 | 6666144 | 126.62% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .app_layer.error.dns_udp.parser | 28003 | 0 | - |
| .http.memuse | 16440 | 2104 | 12.8% |
| | IPS_AFP_stats_chk | | |
| .tcp.segment_from_pool | 17089689 | 15753534 | 92.18% | 

Pipeline 11939

**Comment by catenacyber** [comment]
I think https://github.com/OISF/suricata/pull/8460 should be merged first, than have a QA rebase, then rebase this one

**Comment by catenacyber** [comment]
TODO: rebase after https://github.com/OISF/suricata/pull/8510 gets merged

**Comment by jasonish** [comment]
@catenacyber Possible to rebase, as QA has recently been rebased as well.

**Comment by catenacyber** [comment]
Indeed, I have been aiming it for a fe weeks...

**Comment by catenacyber** [comment]
Replaced by #8882

**Pull request closed without merging**
