### PR TITLE
TLS SubjectAltName sticky buffer/v7

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5234

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1743

Previous PR: https://github.com/OISF/suricata/pull/10758

Changes since v6:
- description added in schema
- cleanup commit separated

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19938

**Comment by catenacyber** [comment]
I still suggest that https://github.com/OISF/suricata/pull/10462 should come first

**Review by jufajardini — APPROVED** [review]
Looks good to me! :)

**Comment by inashivb** [comment]
> I still suggest that #10462 should come first

I'm good with that. I can then extend on your work to unify multi buffer code for this keyword as well. Could be less lines of code, it seems. 😉

**Pull request closed without merging**
