### PR TITLE
(RFC) rust: mark extern fn's unsafe; remove tranmute - v7

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/4666

The first commits remove all usages of transmute. Every usage of
it in our code can be replaced by a cast, or Box::into_raw and
Box::from_raw.

Next, mark all functions that dereference a raw pointer as unsafe,
this means most extern "C" functions that take a pointer from C.

Reference: https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref

And some discussion in PR #4666.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3634

**Comment by suricata-qa** [comment]
ERROR: QA failed on generic_collect.

Pipeline 3634

**Comment by suricata-qa** [comment]
ERROR: QA failed on generic_collect.

Pipeline 3634

**Comment by suricata-qa** [comment]
ERROR: QA failed on generic_collect.

Pipeline 3634

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3818

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/6299.

**Pull request closed without merging**
