### PR TITLE
Libhtp rs v19

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2696) ticket:
https://redmine.openinfosecfoundation.org/issues/2696

Describe changes:
- Use libhtp-rs.

Rebase from #12198 + with fixup commits improving QA

Draft to see CI/QA feedback with latest libhtp-rs changes, and not have too many conflicts

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 ERROR: panic in ASAN_TLPR1_suri QA test

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 23661

**Comment by ct0br0** [comment]
i thought we enabled that but it's in the compile step, should be on run i am guessing?

**Comment by catenacyber** [comment]
> i thought we enabled that but it's in the compile step, should be on run i am guessing?

Maybe even for both.

**Comment by catenacyber** [comment]
Next in https://github.com/OISF/suricata/pull/12240

**Pull request closed without merging**
