### PR TITLE
Transform rust 7229 v2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7229

Describe changes:
- transforms: move strip_whitespace and compress_whitespace to rust

Should we do other transforms ?

https://github.com/OISF/suricata/pull/11861 with warnings fixes, and transfer of compress_whitespace

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 649 | 627 | 96.61% | 

Pipeline 22963

**Comment by victorjulien** [comment]
please include results from rule profiling, similar to what I did for my SIMD work here https://github.com/OISF/suricata/pull/11617/commits/68ab0c2c8617d66c3650e7797dbecd9ff0f1b2d0

btw, I have some thoughts to SIMD optimize at least strip_whitespace, so will be interesting to see how rust performs here

**Comment by catenacyber** [comment]
> please include results from rule profiling, similar to what I did for my SIMD work here [68ab0c2](https://github.com/OISF/suricata/commit/68ab0c2c8617d66c3650e7797dbecd9ff0f1b2d0)

Cool, how do you produce these results ?
Compile with `--enable-profiling-rules` right ?
But then, which rules and traffic do you use then ? SV tests ?

**Comment by victorjulien** [comment]
> > please include results from rule profiling, similar to what I did for my SIMD work here [68ab0c2](https://github.com/OISF/suricata/commit/68ab0c2c8617d66c3650e7797dbecd9ff0f1b2d0)
> 
> Cool, how do you produce these results ? Compile with `--enable-profiling-rules` right ? But then, which rules and traffic do you use then ? SV tests ?

Use a large http body test, then a rule like `file.data; <transform>; ...` with a unlimited stream depth / http body inspection.

**Comment by catenacyber** [comment]
I get the same kind of results :

master
```
  --------------------------------------------------------------------------------------------------------------------------------
  Date: 10/3/2024 -- 15:51:02
  --------------------------------------------------------------------------------------------------------------------------------
  Stats for: total
  --------------------------------------------------------------------------------------------------------------------------------
  Prefilter                        Ticks           Called          Max Ticks       Avg             Bytes           Called          Max Bytes       Avg Bytes       Ticks/Byte     
  -------------------------------- --------------- --------------- --------------- --------------- --------------- --------------- --------------- --------------- --------------- 
  file_data#178 (strip_whitespace  970760640       119             15407846        8157652.00      28531348        116             266920          245959.00       34.00          

```

PR
```
  --------------------------------------------------------------------------------------------------------------------------------
  Date: 10/3/2024 -- 15:56:12
  --------------------------------------------------------------------------------------------------------------------------------
  Stats for: total
  --------------------------------------------------------------------------------------------------------------------------------
  Prefilter                        Ticks           Called          Max Ticks       Avg             Bytes           Called          Max Bytes       Avg Bytes       Ticks/Byte     
  -------------------------------- --------------- --------------- --------------- --------------- --------------- --------------- --------------- --------------- --------------- 
  file_data#178 (strip_whitespace  994663846       119             12126660        8358519.00      28540343        116             266997          246037.00       34.00  
```

Ticks/byte changes in different runs between 30 and 39 for the same build

What I did : compile with `--enable-profiling-rules` and `--enable-profiling` (only the first does not work)
Run `./src/suricata -r bigf.pcapng -S bigf.rules -c bigf.yaml -k none -l log`
with big.rules being `alert tcp any any -> any any (file.data; strip_whitespace; content:"hasxspace"; sid:1;)` and bigf.pcapng being a capture of http1 download of 28 Mbyte file SV datasets-1m-StringSets/datasets.csv and bigf.yaml having all kinds of options for profiling

**Comment by catenacyber** [comment]
On the other hand, running my MacOS instruments shows 182-298 milliseconds spent in `TransformStripWhiteSpace`  including 2ms for `InspectionBufferCopy` and 93-123 milliseconds spent in rust `strip_whitespace_transform` including 3ms for `InspectionBufferCopy`

**Comment by catenacyber** [comment]
Let's profile on a cloud device, without ASAN enabled

**Comment by catenacyber** [comment]
And we should do the modifications in place instead of allocating + InspectionBufferCopy

**Comment by catenacyber** [comment]
Next in https://github.com/OISF/suricata/pull/11926

**Pull request closed without merging**
