### PR TITLE
De only/70x/v1

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2166

https://redmine.openinfosecfoundation.org/issues/7432
https://redmine.openinfosecfoundation.org/issues/7439

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 650 | 698 | 107.38% | 

Pipeline 23708

**Review by jufajardini — APPROVED** [review]
looks good to me too, will probably add the rule in the ticket to my extended rule-types test, too, to have more de_only there.

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #12244, thanks!

**Pull request closed without merging**
