### PR TITLE
ebpf: Enable vlan use-for-tracking in ebpf keys

### PR DESCRIPTION
**Pull request by odinje**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4214) ticket:

Describe changes:
- Ensure that vlan tags is not used in ebpf keys when vlan use-for-tracking is disabled in suricata.yaml.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Looks good to me.

Is there the same problem in source-pfring.c ? and in util-ebpf.c ?

**Comment by odinje** [comment]
> Make sure these boxes are signed before submitting your Pull Request -- thank you.
> 
> * [x]  I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
> * [x]  I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
> * [ ]  I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
> 
> Link to [Bug #4214](https://redmine.openinfosecfoundation.org/issues/4214) ticket:
> 
> Describe changes:
> 
> * Ensure that vlan tags is not used in ebpf keys when vlan use-for-tracking is disabled in suricata.yaml.
> 
> #suricata-verify-pr:
> #suricata-verify-repo:
> #suricata-verify-branch:
> #suricata-update-pr:
> #suricata-update-repo:
> #suricata-update-branch:
> #libhtp-pr:
> #libhtp-repo:
> #libhtp-branch:

**Comment by odinje** [comment]
Good point @catenacyber. Need to take an extra check.

**Comment by catenacyber** [comment]
cc @regit since this is ebpf stuff

**Comment by catenacyber** [comment]
@odinje could you submit a new rebased version ? Thanks

**Comment by victorjulien** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
