### PR TITLE
source: Check for out-of-band control operations when packets aren't available

### PR DESCRIPTION
**Pull request by jlucovsky**
This PR fixes an issue seen when using Napatech hardware that results in the Suricata manager and unix-socket threads hanging. The same issue is in the dag packet source.

Describe changes:
- dag/napatech -- check for out-of-band control ops when packets aren't immediately available
- napatech: Fix timestamp conversion for usecs.

### CODE REVIEW

**Comment by victorjulien** [comment]
@pjyoung1 can you review the Napatech changes? Thanks!

**Comment by pjyoung1** [comment]
These changes are fine.  (In fact the timestamp change is something I was getting ready to fix.)

**Comment by victorjulien** [comment]
Merged in #4878, thanks!

**Comment by pjyoung1** [comment]
Something is not right here.  When I rebase and attempt build this it complains that there are "too many parameters" to the TmThreadsCaptureHandleTimeout() function.  Are there missing changes to tm-threads or was this added incorrectly.

**Comment by jlucovsky** [comment]
> Something is not right here. When I rebase and attempt build this it complains that there are "too many parameters" to the TmThreadsCaptureHandleTimeout() function. Are there missing changes to tm-threads or was this added incorrectly.

`master` and `master-5.0.x` have different interfaces. For `master`, omit the 2nd parameter

**Pull request closed without merging**
