### PR TITLE
doc updates - v2

### PR DESCRIPTION
**Pull request by jasonish**
Includes https://github.com/OISF/suricata/pull/5897.

Added parts from https://github.com/OISF/suricata/pull/5593 with minor mods from me.

And replace testmyids.org with a new URL that doesn't force https.

Would be nice to get into 6.0.x, but not required.  Cherry picks cleanly at the moment.

### CODE REVIEW

**Comment by catenacyber** [comment]
> And replace testmyids.org with a new URL that doesn't force https.

Good idea.
When teaching to write a "hello world" signature, people make the mistake of making a pcap with testmyids.org

**Comment by victorjulien** [comment]
Hi @wesinator, can you set a proper git author on your patches for us? This looks odd:
Screenshot from 2021-02-23 10-28-30

**Comment by wesinator** [comment]
> 
> 
> Hi @wesinator, can you set a proper git author on your patches for us? This looks odd:
> Screenshot from 2021-02-23 10-28-30

Not sure how to do this from the new pull branch - do you need me to go back and amend the commits on my original branch ?

**Comment by jasonish** [comment]
> Not sure how to do this from the new pull branch - do you need me to go back and amend the commits on my original branch ?

Can you tell me what "Full Name <user@domain.com>" we should use?  I can ammend this in my fixup branch, then you can `git config` locally for next time.. Thanks!

**Comment by wesinator** [comment]
> > Not sure how to do this from the new pull branch - do you need me to go back and amend the commits on my original branch ?
> 
> Can you tell me what "Full Name [user@domain.com](mailto:user@domain.com)" we should use? I can ammend this in my fixup branch, then you can `git config` locally for next time.. Thanks!

`Wes 5124946+wesinator@users.noreply.github.com` (this should render fine, I had alt unicode characters in the name )

Thanks,

**Pull request closed without merging**
