### PR TITLE
util/base64: remove coverity reported dead code

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6985

Previous PR: https://github.com/OISF/suricata/pull/10959

Changes since v2:
- squash commits
- rebase

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .memcap.pressure | 57 | 53 | 92.98% |
| .memcap.pressure_max | 62 | 70 | 112.9% | 

Pipeline 20409

**Review by catenacyber — APPROVED** [review]
Thanks for the work Shivani

CI : 🟢 
Code : good
Commits segmentation : good
Commit messages : good
Git ID set : looks fine for me
CLA : :-p
Doc update : not needed, comment is good
Redmine ticket : ok
Rustfmt : no rust
Tests : not needed besides coverity
Dependencies added: none added

**Comment by victorjulien** [comment]
@ct0br0 can this get a QA rerun? Esp the alert diff caught my eye.

**Comment by ct0br0** [comment]
@victorjulien will do. Going to update QA-dev this afternoon FYI.

**Comment by inashivb** [comment]
> ERROR: QA failed on SURI_TLPR1_alerts_cmp.

Seems unrelated to this PR. Also seen on https://github.com/OISF/suricata/pull/10997#issuecomment-2087935605 but I'm interested in knowing too if the this is a true positive.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20467

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11015, thanks!

**Pull request closed without merging**
