### PR TITLE
Decode runmode/v9

### PR DESCRIPTION
**Pull request by victorjulien**
WIP branch for merging decoders into capture methods.

https://redmine.openinfosecfoundation.org/issues/6968

Implements it for:
- pcap-file
- pcap
- af-packet
That should show if the approach makes sense and if CI/QA pass.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 642 | 665 | 103.58% | 

Pipeline 21015

**Comment by catenacyber** [comment]
Are you checking the red CI ?

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21520

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
  

Pipeline 21531

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21536

**Comment by victorjulien** [comment]
replaced by #12277

**Pull request closed without merging**
