### PR TITLE
Port grouping redo/v19

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- https://redmine.openinfosecfoundation.org/issues/6795
- https://redmine.openinfosecfoundation.org/issues/6792

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1662

Runtime on my laptop:
```
real	0m29.164s
user	0m28.578s
sys	0m0.518s
```

### CODE REVIEW

**Comment by victorjulien** [comment]
With this PR, do we still need the CopySigs etc logic in the `DetectPort` "cut" code at all?

**Review by inashivb — COMMENTED** [review]
@victorjulien now everything is heap alloc'd but the Windows and MacOS tests are still failing. Any more pointers about what may be going wrong?

**Comment by victorjulien** [comment]
I don't know. Have you inspected the output it generates and where the mismatch is?

**Comment by inashivb** [comment]
> I don't know. Have you inspected the output it generates and where the mismatch is?

yes. The rulegroup id is different in the output vs test. See

On Linux
```
$cat output/rule_group.json | jq '.tcp.toserver[]' | jq -c '[.port, .port2, .rulegroup.id, .rulegroup.rules]'
[1,1,0,[{"sig_id":1}]]
[2,2,1,[{"sig_id":2}]]
[3,3,2,[{"sig_id":3}]]
[4,4,3,[{"sig_id":4}]]
[5,5,4,[{"sig_id":5}]]
[6,6,5,[{"sig_id":6}]]
[7,7,6,[{"sig_id":7}]]
[8,8,7,[{"sig_id":8}]]
[9,9,8,[{"sig_id":9}]]
[10,10,9,[{"sig_id":10}]]
[11,11,10,[{"sig_id":11}]]
[12,12,11,[{"sig_id":12}]]
[1024,65535,12,[{"sig_id":13}]]
```
vs MacOS
```
[1024,65535,0,[{"sig_id":13}]]
[2,2,1,[{"sig_id":2}]]
[3,3,2,[{"sig_id":3}]]
[4,4,3,[{"sig_id":4}]]
[5,5,4,[{"sig_id":5}]]
[6,6,5,[{"sig_id":6}]]
[7,7,6,[{"sig_id":7}]]
[8,8,7,[{"sig_id":8}]]
[9,9,8,[{"sig_id":9}]]
[10,10,9,[{"sig_id":10}]]
[11,11,10,[{"sig_id":11}]]
[12,12,11,[{"sig_id":12}]]
[1,1,12,[{"sig_id":1}]]
```

**Comment by victorjulien** [comment]
Seeing it locally as well, in FreeBSD for example.

**Comment by inashivb** [comment]
> Seeing it locally as well, in FreeBSD for example.

ok.
Q1: Are rulegroup IDs important to stay the same across all platforms? Or, should it be about the groups created and the signatures that are a part of it?
Q2: Have we seen this before?

**Pull request closed without merging**
