### PR TITLE
Smtp to comma quote 7060 v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7060

Describe changes:
- Needed clean cherry-pick of https://redmine.openinfosecfoundation.org/issues/6906
- Needed clean cherry-pick for json schema addition of missing fields
- smtp: log split by commas with respecting quotes

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1885

What should be done with https://redmine.openinfosecfoundation.org/issues/6906 ? Downgrade it to resolved and mark it as needs backport ?

### CODE REVIEW

**Comment by victorjulien** [comment]
Assuming this will require a baseline update because of the SMTP data commit.

**Comment by victorjulien** [comment]
> > Assuming this will require a baseline update because of the SMTP data commit.
> 
> Likely yes. Is it good ?

Yup, just a bit more involved.

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPW1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .flow.end.tcp_state.syn_recv | 0 | 1 | - |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 649 | 669 | 103.08% | 

Pipeline 20950

**Comment by catenacyber** [comment]
@ct0br0 this is not a full rebase line, just some hash count changing for main7 branch

**Comment by ct0br0** [comment]
k, let me know when there's a next branch and i'll try to use that. the tlpw2 stuff is likely a fluke

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11267

**Pull request closed without merging**
