### PR TITLE
docs: improve code documentation-v4

### PR DESCRIPTION
**Pull request by zazie-codes**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:https://redmine.openinfosecfoundation.org/issues/6383

Describe changes:
This is an update #9611
- added the space in layer src/app-layer-htp-libhtp.h
- interchanged file description to come after author credentials according to conform to guidelines.
-Squashed all commits'.

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Seems like the commits made their way again into the PR. :/
Always check `git log` before sending a PR. This should only show one commit on top of Suricata's master. If that's the case, you're good to go.
Could you please squash them together again?

**Comment by zazie-codes** [comment]
> git log

It shows only 1, even with git log --oneline.

**Comment by zazie-codes** [comment]
> > git log
> 
> It shows only 1, even with git log --oneline.

I cant squash because it doesn't list my commits.

**Comment by inashivb** [comment]
> > It shows only 1, even with git log --oneline.
> 
> I cant squash because it doesn't list my commits.

My guess is your git history is messed up because you're working on your master branch. Please create a new branch for the feature locally (`git checkout -b my-feature-branch`) and push that to your remote to create a PR.
Your local master should be where Suricata's [master](https://github.com/OISF/suricata) is. No more/less commits.

**Comment by zazie-codes** [comment]
> > > It shows only 1, even with git log --oneline.
> > 
> > 
> > I cant squash because it doesn't list my commits.
> 
> My guess is your git history is messed up because you're working on your master branch. Please create a new branch for the feature locally (`git checkout -b my-feature-branch`) and push that to your remote to create a PR. Your local master should be where Suricata's [master](https://github.com/OISF/suricata) is. No more/less commits.

Should i close this PR?

**Comment by zazie-codes** [comment]
> > > > > It shows only 1, even with git log --oneline.
> > > > 
> > > > 
> > > > I cant squash because it doesn't list my commits.
> > > 
> > > 
> > > My guess is your git history is messed up because you're working on your master branch. Please create a new branch for the feature locally (`git checkout -b my-feature-branch`) and push that to your remote to create a PR. Your local master should be where Suricata's [master](https://github.com/OISF/suricata) is. No more/less commits.
> > 
> > 
> > Should i close this PR?
> 
> Yes, please. When you're creating creating a new PR, you'll see in the dashboard how many commits are being added, make sure there is just one over there. A new feature branch should make it easier to see ;)

Alright Shivani. I'll make sure to submit only 1 commit

**Comment by jufajardini** [comment]
Replaced by: https://github.com/OISF/suricata/pull/9650

**Pull request closed without merging**
