### PR TITLE
dns: parser and alert on invalid opcodes - v3

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: #8246

QA failed on the previous PRs due to too many UDP DNS parse errors. This was due to UDP streams on port 53 that were not being detected as DNS having a few packets well into the stream that *did* probe as DNS as they were close enough, yet were not DNS resulting in subsequents packet in the stream being sent to the DNS parser and, as expected erroring out.

To mitigate this, probe the header for validity on every incoming message into the DNS parser, even if probed as DNS. This is a check to ensure that the number of answers and responses fit in a DNS message.

If the header validity check fails the message will be ignored without a *parse* error.  A parse error will only be generated now if the header checks out, but parsing fails in the body.

This could result in missing some legitimate parse errors where there is traffic that is intended to be DNS, but the header doesn't check out well enough to be DNS.

This starts off with a rustfmt of the DNS module as I want my editor to start doing the formatting for me. So best reviewed by the commit rather than GitHub files changed.

suricata-verify-pr: 1024

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on report_failure.

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 11268

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103967 | 81.07% |
| .app_layer.error.dns_tcp.parser | 1 | 0 | - |
| .app_layer.error.dns_udp.parser | 1276 | 827 | 64.81% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 1688406848 | 298.76% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .app_layer.error.dns_udp.parser | 28003 | 13 | 0.05% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 14506 | 0.00 | 

Pipeline 11270

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 1276 | 827 | 64.81% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 28003 | 13 | 0.05% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 80862 | 0.01 | 

Pipeline 11273

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 1276 | 827 | 64.81% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 28003 | 13 | 0.05% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 74138 | 0.01 | 

Pipeline 11275

**Comment by jasonish** [comment]
Out of draft.  Ready for review.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103925 | 81.04% |
| .app_layer.error.dns_udp.parser | 1276 | 827 | 64.81% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 28003 | 13 | 0.05% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 162656 | 0.03 | 

Pipeline 11276

**Comment by jasonish** [comment]
> WARNING:
> 
> field	baseline	test	%
> SURI_TLPW1_stats_chk		
> .tcp.rst	128237	103925	81.04%
> .app_layer.error.dns_udp.parser	1276	827	64.81%
> SURI_TLPR1_stats_chk		
> .app_layer.error.dns_udp.parser	28003	13	0.05%
> TREX_GENERIC_stats_chk		
> .capture.kernel_drops	0	162656	0.03
> Pipeline 11276

Reduced `.app_layer.error.dns_udp.parser` is expected with this PR as we are silently ignoring UDP DNS packets that don't pass header validation.

I'm not sure why drops is increased. We should be doing less work by reducing the number of packets that go off for full parsing.

**Comment by jasonish** [comment]
Replaced by https://github.com/OISF/suricata/pull/8377.

**Pull request closed without merging**
