### PR TITLE
mqtt: fix transaction completion

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4879

### CODE REVIEW

**Comment by catenacyber** [comment]
The CI failure is unrelated : see https://github.com/OISF/suricata-verify/pull/509

**Comment by suricata-qa** [comment]
ERROR: QA failed on build_asan.
  

Pipeline 5188

**Comment by catenacyber** [comment]
S-V should pass with https://github.com/OISF/suricata-verify/pull/601

**Comment by inashivb** [comment]
Replaced w #6700

**Pull request closed without merging**
