### PR TITLE
Pcap read directories recursively v7

### PR DESCRIPTION
**Pull request by jamesdutrisac**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2363

Describe changes:

    Added ability to recursively read pcap directories
    src/suricata.c: addition of new command line parameter --pcap-file-recursive
    src/source-pcap-file.c: parsing of the command line argument
    src/source-pcap-file-directory-helper.h: two thread vars tracking directory depth and should recurse
    src/util-error.c / src/util-error.h: Added new warning code "SC_WARN_PATH_READ_ERROR"
    src/util-path.c / src/util-path.h added 4 functions
    a) SCIsRegularFile to provide OS independent file info.
    b) SCIsRegularDirectory to provide OS independent directory info.
    c) SCRealPath is an OS independent wrapper for realpath.
    d) PathJoin to manage path resolution logic.

This updates version 6 (#5211) with some code readability improvements as requested in the code review by @jlucovsky. 

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
Commit `pcap: read directories recursively (2363) updates to util-path` should be reworded. It's not about pcap, but about general path handling.

**Comment by victorjulien** [comment]
Merged in #5265, thanks!

As discuss offline I updated the commit message and git 'author' in the patches.

**Comment by victorjulien** [comment]
Btw it looks like Coverity flagged a few issues in error handling: https://redmine.openinfosecfoundation.org/issues/3858

**Comment by jamesdutrisac** [comment]
> Btw it looks like Coverity flagged a few issues in error handling: https://redmine.openinfosecfoundation.org/issues/3858

Thanks, I'll take a look.

**Pull request closed without merging**
