### PR TITLE
doc/rule-profiling: fix suricatasc typo

### PR DESCRIPTION
**Pull request by kprime21**
corrected typo in suricatasc

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#6371](https://redmine.openinfosecfoundation.org/issues/6371)

Describe changes:
- changed spelling of surictasc to suricatasc

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Hi @kprime21 !
Thank you for your first contribution to our project. :)
While the rst changes look good to me, we need to work on the commit message.
Could you please make something like `doc/rule-profiling: fix suricatasc typo`?

**Review by inashivb — CHANGES_REQUESTED** [review]
Hi @kprime21 !
1. Please make sure that commit signee is in the format: "FirstName LastName <name@example.com>"
2. We prefer new PR with any changes made over a force push to the same PR.
Please read through the contribution guidelines here: https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html

**Comment by jufajardini** [comment]
Hi @kprime21 did you close this on purpose? If you are not interested or can't work on this task any more, please let us know, so we can update the ticket accordingly :)

**Comment by kprime21** [comment]
> Hi @kprime21 did you close this on purpose? If you are not interested or can't work on this task any more, please let us know, so we can update the ticket accordingly :)

Hi @jufajardini , I was going to make a new PR with these changes

**Comment by jufajardini** [comment]
> > Hi @kprime21 did you close this on purpose? If you are not interested or can't work on this task any more, please let us know, so we can update the ticket accordingly :)
> 
> Hi @jufajardini , I was going to make a new PR with these changes

Ah, all good, then! Just to help we all know what's going on in such cases, if you don't close your PR with a comment pointing to the next one, could you please leave a note stating why you're closing the PR? Thanks in advance! :)

**Comment by jufajardini** [comment]
Followed by https://github.com/OISF/suricata/pull/9731

**Pull request closed without merging**
