### PR TITLE
Quic ietf 4967 v11

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4967
https://redmine.openinfosecfoundation.org/issues/5143
https://redmine.openinfosecfoundation.org/issues/5166

Describe changes:
- Parses standardized QUIC IETF v1
- bump up rust carte tls_parser already used by rep, so that it can be used by quic
- Rustfmt previous code

suricata-verify-pr: 783
https://github.com/OISF/suricata-verify/pull/783

Replaces https://github.com/OISF/suricata/pull/7149 with review :
- parse section 19.3.1.  ACK Ranges
- fix endianness for pkt_num
- add paenthesis for `1 + ((flags.raw & 0x30) >> 4)
- truncate payload as told by decrypt function
- Do not try to parse Q050 frames as decryption is unsupported by rustls

Still to do : commits history squash

Still to do more generally about quic : see https://redmine.openinfosecfoundation.org/issues/4966 (frame support)

### CODE REVIEW

**Comment by victorjulien** [comment]
Versions look good:
```
$ eve.json | jq -c 'select(.quic)|.quic.version'|sort|uniq -c|sort -nr
 298638 "1"
  58647 "ff00001d"
  26336 "faceb002"
   2754 "Q043"
    188 "Q046"
```

**Comment by catenacyber** [comment]
Thanks. Do you have anomalies ?

**Comment by victorjulien** [comment]
Yes:
```
 148528 {"app_proto":"quic","type":"unknown","code":0,"layer":"proto_parser"}
  26316 {"app_proto":"quic","type":"unknown","code":1,"layer":"proto_parser"}
```

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7174

**Pull request closed without merging**
