### PR TITLE
Convert byte_extract keyword parser to Rust

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #10716

Convert the byte_extract option parser from C to Rust.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6873](https://redmine.openinfosecfoundation.org/issues/6873)

Describe changes:
- Refactor code in rust/src/detect to support re-usability
- Implement the byte_extract parser in Rust, with unittests
- Modify the existing byte_extract module to use the Rust parser

Updates:
- Fixup rust clippy issues.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 19990

**Comment by ct0br0** [comment]
```
   Compiling suricata v8.0.0-dev (/home/suri/builds/oKPyeNbq/0/dev/qa-prod/suricata/rust)
error[E0308]: mismatched types
   --> src/detect/byte_extract.rs:223:40
    |
223 |                 if mult == 0 || mult > u16::MAX {
    |                                 ----   ^^^^^^^^ expected `u32`, found `u16`
    |                                 |
    |                                 expected because this is `u32`
    |
help: you can convert a `u16` to a `u32`
    |
223 |                 if mult == 0 || mult > u16::MAX.into() {
    |                                                +++++++
For more information about this error, try `rustc --explain E0308`.
error: could not compile `suricata` (lib) due to previous error
make[1]: *** [Makefile:548: all-local] Error 101
```

**Review by catenacyber — CHANGES_REQUESTED** [review]
CI should be green

**Comment by jlucovsky** [comment]
Continued in #10833

**Comment by jlucovsky** [comment]
> CI should be green

100% agree :-)

**Pull request closed without merging**
