### PR TITLE
exception policies batch backports - v1

### PR DESCRIPTION
**Pull request by jufajardini**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6035
https://redmine.openinfosecfoundation.org/issues/5935
https://redmine.openinfosecfoundation.org/issues/6149 (backport ticket not created)

Describe changes:

- Master switch backports
- midstream exception policy backports (except the portion that seemed to be causing a bug, cf https://github.com/OISF/suricata/pull/9059 - https://redmine.openinfosecfoundation.org/issues/6169)
- plus minor commits related to those

```
SV_BRANCH=pr/1268
```
https://github.com/OISF/suricata-verify/pull/1268

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 577437888 | 1039458048 | 180.01% | 

Pipeline 14781

**Comment by jufajardini** [comment]
> WARNING:
> 
> ERROR: QA failed on IPS_AFP_drop_chk.
> 

Note to self: check if that's for master-6.0.x, could be what's expected due to the changes...

**Comment by ct0br0** [comment]
> > WARNING:
> > ERROR: QA failed on IPS_AFP_drop_chk.
> 
> Note to self: check if that's for master-6.0.x, could be what's expected due to the changes...

Believe it is. The baseline of total drops matches master(7). `129600` (old) vs `194400` (new)

**Comment by jufajardini** [comment]
> > > WARNING:
> > > ERROR: QA failed on IPS_AFP_drop_chk.
> > 
> > 
> > Note to self: check if that's for master-6.0.x, could be what's expected due to the changes...
> 
> Believe it is. The baseline of total drops matches master(7). `129600` (old) vs `194400` (new)

🤔 ok, I'm confused. If we're comparing 7, and this PR is for 6, we shouldn't be a difference, right?

**Comment by victorjulien** [comment]
What is the status of this?

**Comment by jufajardini** [comment]
> What is the status of this?

I was waiting on the other fix to be merged, to backport those, too.

**Comment by jufajardini** [comment]
Replaced by: https://github.com/OISF/suricata/pull/9167

**Pull request closed without merging**
