### PR TITLE
doc/dcerpc: add proto keywords

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3029

### CODE REVIEW

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .detect.alert | 3109382 | 3962505 | 78.0% |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | generic_stats_chk |
| .tcp.reassembly_memuse | 2293760 | 1966080 | 86.0% |

**Comment by suricata-qa** [comment]
WARNING:\r\n| field | test | baseline | % |
|--|--|--|--|
| | generic_stats_chk |
| .tcp.reassembly_memuse | 2293760 | 1966080 | 86.0% |

**Comment by victorjulien** [comment]
Merged in #6248, thanks.

**Pull request closed without merging**
