### PR TITLE
Flow drops/v4

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=pr/1224

https://redmine.openinfosecfoundation.org/issues/5802

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 14178

**Review by jufajardini — COMMENTED** [review]
I like that we're handling the drop when updating the flow packet state, and that we're checking for the drop before updating app-layer for UDP protos. Seems like the drop handling is more contained. I saw that we are not calling 'FlowSetNoPacketInspectionFlag' and 'DecodeSetNoPacketInspectionFlag' after checking for the flow drops. Is that because we are handling the dropped flow earlier?

First of the commits seems to have a typo: "apply flow do" -> I imagine that should be "flow drop"?

**Comment by victorjulien** [comment]
> I like that we're handling the drop when updating the flow packet state, and that we're checking for the drop before updating app-layer for UDP protos. Seems like the drop handling is more contained. I saw that we are not calling 'FlowSetNoPacketInspectionFlag' and 'DecodeSetNoPacketInspectionFlag' after checking for the flow drops. Is that because we are handling the dropped flow earlier?

Yeah, the detect engine checks for `FLOW_ACTION_DROP`, so the other flags aren't needed for this case.

**Comment by victorjulien** [comment]
Merged in #8951

**Pull request closed without merging**
