### PR TITLE
src: remove unneeded header and refs

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 9467

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
Looks like https://github.com/OISF/suricata/pull/7872/commits/fd3b89d59b2bd507370ad879ca35e5841ca44743 ;-)

**Comment by inashivb** [comment]
> Looks like [fd3b89d](https://github.com/OISF/suricata/commit/fd3b89d59b2bd507370ad879ca35e5841ca44743) ;-)

oh. i'm sorry. do you have an open PR? I'll close this in that case

**Comment by catenacyber** [comment]
No, keep it open and approved please :-)

**Comment by victorjulien** [comment]
Merged in #8137, thanks!

**Pull request closed without merging**
