### PR TITLE
Integrate DPDK capture interface into Suricata

### PR DESCRIPTION
**Pull request by lukashino**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4507) ticket:

Describe changes:
- Add STAILQ implementation (required for DPDK).
- Integrate DPDK capture interface as an alternative to AF_PACKET or others. 
- Focus implementation on workers runmode.
- Support both IDS and IPS modes.
- Follow AF_PACKET capture interface architecture and apply DPDK best practices for development.
- Update documentation to reflect new changes.

Work has been based on DPDK 21.05 but I believe running it on earlier versions would be also possible.

### CODE REVIEW

**Comment by victorjulien** [comment]
Windows and Mac OS builders failing with
```
make[2]: Entering directory '/d/a/suricata/suricata/src'
1101
  CC       main.o
1102
  CC       alert-debuglog.o
1103
  CC       alert-fastlog.o
1104
In file included from decode.h:72,
1105
                 from detect-engine-alert.h:28,
1106
                 from suricata-common.h:507,
1107
                 from suricata.h:67,
1108
                 from main.c:18:
1109
source-dpdk.h:30:10: fatal error: linux/if_packet.h: No such file or directory
1110
   30 | #include <linux/if_packet.h>
1111
      |          ^~~~~~~~~~~~~~~~~~~
1112
compilation terminated.
1113
In file included from decode.h:72,
1114
                 from detect-engine-alert.h:28,
1115
                 from suricata-common.h:507,
1116
                 from alert-debuglog.c:24:
1117
source-dpdk.h:30:10: fatal error: linux/if_packet.h: No such file or directory
1118
   30 | #include <linux/if_packet.h>
1119
      |          ^~~~~~~~~~~~~~~~~~~
1120
compilation terminated.
1121
make[2]: *** [Makefile:3324: main.o] Error 1
1122
make[2]: *** Waiting for unfinished jobs....
1123
make[2]: *** [Makefile:3324: alert-debuglog.o] Error 1
1124
In file included from decode.h:72,
1125
                 from detect-engine-alert.h:28,
1126
                 from suricata-common.h:507,
1127
                 from alert-fastlog.c:27:
1128
source-dpdk.h:30:10: fatal error: linux/if_packet.h: No such file or directory
1129
   30 | #include <linux/if_packet.h>
1130
      |          ^~~~~~~~~~~~~~~~~~~
1131
compilation terminated.
1132
make[2]: *** [Makefile:3324: alert-fastlog.o] Error 1
1133
make[2]: Leaving directory '/d/a/suricata/suricata/src'
1134
make[1]: *** [Makefile:2564: all] Error 2
1135
make[1]: Leaving directory '/d/a/suricata/suricata/src'
1136
make: *** [Makefile:498: all-recursive] Error 1
```

**Comment by victorjulien** [comment]
cocci check sees a alloc w/o error check:
```
./struct-flags.py  ../../src > ../../qa/coccinelle/struct-flags.cocci
8249
TOP_BUILDDIR=/__w/suricata/suricata TOP_SRCDIR=/__w/suricata/suricata ../../qa/coccinelle/run_check.sh
8250
Using concurrency level 2
8251
Testing cocci file: /__w/suricata/suricata/qa/coccinelle/access-pkt-packet.cocci
8252
Testing cocci file: /__w/suricata/suricata/qa/coccinelle/action-pkt.cocci
8253
Testing cocci file: /__w/suricata/suricata/qa/coccinelle/banned-functions.cocci
8254
Testing cocci file: /__w/suricata/suricata/qa/coccinelle/direct-packet.cocci
8255
Testing cocci file: /__w/suricata/suricata/qa/coccinelle/malloc-error-check.cocci
8256
Structure malloced at /__w/suricata/suricata/src/runmode-dpdk.c:351 but error is not checked.
8257
make[2]: *** [check] Error 1
8258
Makefile:545: recipe for target 'check' failed
```

**Comment by victorjulien** [comment]
Can you add a check to our `.github/workflows/builds.yml` that installs dpdk and builds it?

**Comment by lukashino** [comment]
> cocci check sees a alloc w/o error check:
> 
> ```
> ./struct-flags.py  ../../src > ../../qa/coccinelle/struct-flags.cocci
> 8249
> TOP_BUILDDIR=/__w/suricata/suricata TOP_SRCDIR=/__w/suricata/suricata ../../qa/coccinelle/run_check.sh
> 8250
> Using concurrency level 2
> 8251
> Testing cocci file: /__w/suricata/suricata/qa/coccinelle/access-pkt-packet.cocci
> 8252
> Testing cocci file: /__w/suricata/suricata/qa/coccinelle/action-pkt.cocci
> 8253
> Testing cocci file: /__w/suricata/suricata/qa/coccinelle/banned-functions.cocci
> 8254
> Testing cocci file: /__w/suricata/suricata/qa/coccinelle/direct-packet.cocci
> 8255
> Testing cocci file: /__w/suricata/suricata/qa/coccinelle/malloc-error-check.cocci
> 8256
> Structure malloced at /__w/suricata/suricata/src/runmode-dpdk.c:351 but error is not checked.
> 8257
> make[2]: *** [check] Error 1
> 8258
> Makefile:545: recipe for target 'check' failed
> ```

I think it is a little bit weird because I believe there is an error check. This is what I had there 
`void ConfigInit(DPDKIfaceConfig **iconf)
{
    *iconf = SCCalloc(1, sizeof(**iconf));
    if (unlikely((*iconf) == NULL)) {
        SCLogError(SC_ERR_DPDK_CONF, "Could not allocate memory for DPDKIfaceConfig");
        SCReturn;
    }`

but I have changed it a little bit. So let's see if that passes the test.

I have additionally removed `#include <linux/if_packet.h>` as it was redundant. 

> Can you add a check to our .github/workflows/builds.yml that installs dpdk and builds it?
I think that it is possible.

**Comment by jlucovsky** [comment]
Thanks for your contribution. When making updates to your PR, please (1) create a new branch based on the previous one, and (2) create a new PR.

Force-pushing is destructive to the context of the previous PRs, especially wrt comments.

Thanks!

**Comment by lukashino** [comment]
> Thanks for your contribution. When making updates to your PR, please (1) create a new branch based on the previous one, and (2) create a new PR.
> 
> Force-pushing is destructive to the context of the previous PRs, especially wrt comments.
> 
> Thanks!

Sorry about that! Is it okay if I follow your advice for the next PRs or should I create a new branch even for this PR?

**Comment by lukashino** [comment]
I have added DPDK to the build workflow to some distributions, mainly to the ones that had it in their package managers. This can be later extended to some other distros. I have found [Github Action](https://github.com/yoursunny/setup-dpdk) to which I also submitted a PR to make it suitable to our needs.

**Comment by jlucovsky** [comment]
> > Thanks for your contribution. When making updates to your PR, please (1) create a new branch based on the previous one, and (2) create a new PR.
> > Force-pushing is destructive to the context of the previous PRs, especially wrt comments.
> > Thanks!
> 
> Sorry about that! Is it okay if I follow your advice for the next PRs or should I create a new branch even for this PR?

For additional changes only. Thanks!

**Comment by lukashino** [comment]
@jlucovsky If I am not mistaken, previously the CI workflows started automatically after pushing to the repository. Is there currently some kind of a problem with workflows or are they really just waiting for approval from your side? Thank you Jeff.

**Comment by lukashino** [comment]
I have created a new PR #6264  that follows the rules of clang formatting check on my changes. As a result, I think this PR can be closed and instead continue in #6264.

**Pull request closed without merging**
