### PR TITLE
Dcerpc single tx/v4

### PR DESCRIPTION
**Pull request by inashivb**
DCERPC parser in Rust.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/2779

S-V PR to go with this: https://github.com/OISF/suricata-verify/pull/226

### CODE REVIEW

**Comment by inashivb** [comment]
@victorjulien please check the commit messages here. Is this even close to what you were expecting?

**Comment by victorjulien** [comment]
> @victorjulien please check the commit messages here. Is this even close to what you were expecting?

Curious: do you have a git viewer somewhere that supports the rst syntax?

**Comment by inashivb** [comment]
> > @victorjulien please check the commit messages here. Is this even close to what you were expecting?
> 
> Curious: do you have a git viewer somewhere that supports the rst syntax?

Ah no. I think I have just developed this habit to differentiate headings and sub-headings. Should I remove that?

**Comment by victorjulien** [comment]
> > > @victorjulien please check the commit messages here. Is this even close to what you were expecting?
> > 
> > 
> > Curious: do you have a git viewer somewhere that supports the rst syntax?
> 
> Ah no. I think I have just developed this habit to differentiate headings and sub-headings. Should I remove that?

Yeah, if it serves no purpose I would like to see it cleaned up.

**Comment by inashivb** [comment]
Replaced with #4938

**Pull request closed without merging**
