### PR TITLE
documentation: fix typo in Stream engine documentation

### PR DESCRIPTION
**Pull request by lukashino**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- use a correct form of the past tense of the verb and fix the preposition

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
LGTM. Thank you! :)

**Comment by inashivb** [comment]
@lukashino sorry I missed the commit message. Could you please make your commit message have a `doc:` prefix?

**Comment by lukashino** [comment]
> @lukashino sorry I missed the commit message. Could you please make your commit message have a `doc:` prefix?

I am on it.

**Comment by lukashino** [comment]
#6699 covers it!

**Pull request closed without merging**
