### PR TITLE
 detect: add requires keyword - v4

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/9947
Changes from previous PR:
- address documentation comment
- other rules added to test

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1505

### CODE REVIEW

**Comment by jasonish** [comment]
One thought I had is that we can never add a keyword that doesn't follow the current structure of keywords.  Is that a concern?

We could, but it would have to come after `requires` and `sid`.  Even then, the parser would need to `break` once it has seen the `reuires` and the `sid` which it doesn't do now.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16887

**Comment by victorjulien** [comment]
> One thought I had is that we can never add a keyword that doesn't follow the current structure of keywords. Is that a concern?
> 
> We could, but it would have to come after `requires` and `sid`. Even then, the parser would need to `break` once it has seen the `reuires` and the `sid` which it doesn't do now.

Yeah. I don't really see us adopt a new format while trying to remain compatible here.

**Comment by victorjulien** [comment]
Wrt output, do we indicate to the user something like

```
5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10
```

**Comment by jasonish** [comment]
> Wrt output, do we indicate to the user something like
> 
> ```
> 5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10
> ```

No, mainly due to complexity. The reporting back to the initial rule loader would need a bit of an overhaul to track that level of detail, but then you'd also end up with:
```
5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10, 33 rules were skipped because running Suricata version 7.0.3 is lower than 7.0.11, 88 rules were skipped because feature "lua" was missing, 3 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.12 AND feature "geoip" was missing
```
So I do think something simpler would be idea.

**Comment by inashivb** [comment]
> > Wrt output, do we indicate to the user something like
> > ```
> > 5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10
> > ```
> 
> No, mainly due to complexity. The reporting back to the initial rule loader would need a bit of an overhaul to track that level of detail, but then you'd also end up with:
> 
> ```
> 5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10, 33 rules were skipped because running Suricata version 7.0.3 is lower than 7.0.11, 88 rules were skipped because feature "lua" was missing, 3 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.12 AND feature "geoip" was missing
> ```
> 
> So I do think something simpler would be idea.

Would this be better as a job for suricata-update? Like it already reports how many rules were skipped, loaded et el

**Comment by victorjulien** [comment]
> > > Wrt output, do we indicate to the user something like
> > > ```
> > > 5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10
> > > ```
> > 
> > 
> > No, mainly due to complexity. The reporting back to the initial rule loader would need a bit of an overhaul to track that level of detail, but then you'd also end up with:
> > ```
> > 5 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.10, 33 rules were skipped because running Suricata version 7.0.3 is lower than 7.0.11, 88 rules were skipped because feature "lua" was missing, 3 rules were skipped because the running Suricata version 7.0.3 is lower than 7.0.12 AND feature "geoip" was missing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I do think something simpler would be idea.
> 
> Would this be better as a job for suricata-update? Like it already reports how many rules were skipped, loaded et el

In addition, sure. But we need Suricata itself to output it as well.

**Comment by jasonish** [comment]
Playing with this:
2023-12-14T16:50:02,397970268-06:00
Thinking to log it at notice.. But maybe it should only be notice if the Suricata version is too old, otherwise just info.

Thoughts?

**Comment by victorjulien** [comment]
> Playing with this: 2023-12-14T16:50:02,397970268-06:00 Thinking to log it at notice.. But maybe it should only be notice if the Suricata version is too old, otherwise just info.
> 
> Thoughts?

Makes sense to me to split it between notice and info.

**Comment by victorjulien** [comment]
Will it be possible to express that a feature has been introduced in 7.0.11 and 8.0.3?
`requires: version >= 7.0.11, version >= 8.0.3;`
The first condition would also allow 8.0.2?

**Comment by jasonish** [comment]
> Will it be possible to express that a feature has been introduced in 7.0.11 and 8.0.3? `requires: version >= 7.0.11, version >= 8.0.3;` The first condition would also allow 8.0.2?

So you'd want to express:
```
(version >= 7.0.3 && version < 8) || version >= 8.0.3
```

I think we could reasonably shorten that down to
```
requires: version >= 7.0.3 < 8 || >= 8.0.3
```
In flow bits we use `|` as a logical `OR` so could do the same here, or even do...
```
requires: version >= 7.0.3 < 8 OR >= 8.0.3
```
makes not difference to the parser work.

**Comment by jasonish** [comment]
> > Will it be possible to express that a feature has been introduced in 7.0.11 and 8.0.3? `requires: version >= 7.0.11, version >= 8.0.3;` The first condition would also allow 8.0.2?
> 
> So you'd want to express:
> 
> ```
> (version >= 7.0.3 && version < 8) || version >= 8.0.3
> ```
> 
> I think we could reasonably shorten that down to
> 
> ```
> requires: version >= 7.0.3 < 8 || >= 8.0.3
> ```
> 
> In flow bits we use `|` as a logical `OR` so could do the same here, or even do...
> 
> ```
> requires: version >= 7.0.3 < 8 OR >= 8.0.3
> ```
> 
> makes not difference to the parser work.

Implementing this -- easy...

Handling the notice message not so..  Should we say the rule requires at least 8.0.3 or at least 7.0.3?

**Comment by jasonish** [comment]
Better reporting and more expressive syntax added: https://github.com/OISF/suricata/pull/10064

**Pull request closed without merging**
