### PR TITLE
smtp: exit data mode if data command was rejected

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6906

Describe changes:
- smtp: exit data mode if data command was rejected

Will need a QA rebase line as #10734 

```
SV_BRANCH=pr/1737
```
https://github.com/OISF/suricata-verify/pull/1737

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
  

Pipeline 19888

**Comment by jufajardini** [comment]
This one looks good to me. Is anything preventing its approval, or are we waiting as this will require a QA rebase line?

**Comment by catenacyber** [comment]
> This one looks good to me. Is anything preventing its approval, or are we waiting as this will require a QA rebase line?

I guess this is not the priority before the release, cc @victorjulien ?

**Comment by catenacyber** [comment]
Rebased in #10981

**Pull request closed without merging**
