### PR TITLE
next/315/20240222/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #10476
 - #10477

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1663

### CODE REVIEW

**Comment by jufajardini** [comment]
Missing https://github.com/OISF/suricata/pull/10477/commits/d4550ed1f5c250b6db82cbbfd23def8e35d7bd43?

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 101 | 113 | 111.88% | 

Pipeline 18690

**Review by jasonish — CHANGES_REQUESTED** [review]
Yes, appears to be missing a commit.

**Comment by victorjulien** [comment]
It is already in master as 872f007a14cdea70345d381620c40ac4c8e95bca is

**Review by jasonish — APPROVED** [review]

**Pull request merged**
