### PR TITLE
detect/xbits: parse keywords w strtok_r

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4820

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR: Invalid Signature config error in tlpr1_asan_cfg QA test

ERROR: QA failed on tlpr1_asan_cfg.
  

Pipeline 5944

**Comment by inashivb** [comment]
> ERROR: Invalid Signature config error in tlpr1_asan_cfg QA test
> 
> ERROR: QA failed on tlpr1_asan_cfg.
> 
> Pipeline 5944

- `noalert` needs to be handled
- multple `xbits` in a rule need to be handled
- removal of pcre2 specific dead code like regex etc

**Comment by victorjulien** [comment]
> > ERROR: Invalid Signature config error in tlpr1_asan_cfg QA test
> > ERROR: QA failed on tlpr1_asan_cfg.
> > Pipeline 5944
> 
> * `noalert` needs to be handled
> * multple `xbits` in a rule need to be handled
> * removal of pcre2 specific dead code like regex etc

I think its also a bit light on the unittest side. Maybe something like https://github.com/OISF/suricata/blob/master/src/detect-frame.c#L148 can be done here as well

**Comment by inashivb** [comment]
Replaced w #6885

**Pull request closed without merging**
