### PR TITLE
Flow drops/60x/v1

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=pr/1228

### CODE REVIEW

**Comment by victorjulien** [comment]
commit check fails due to unknown cherry pick(s) for not yet merged from #8951

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 579234048 | 907792768 | 156.72% | 

Pipeline 14219

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .uptime | 141 | 211 | 149.65% |
| .tcp.rst | 81627 | 89913 | 110.15% | 

Pipeline 14226

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.spare | 2155079 | 2019024 | 93.69% | 

Pipeline 14232

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 579234048 | 707307968 | 122.11% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 234 | 0.00 | 

Pipeline 14233

**Pull request merged**
