### PR TITLE
Multipart mime 3487 v21

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser

Follows #9437 with fix for rust panic (copying slices must have the exact same size) + removing some dead code cf #9419

@jasonish any ideas on how to get a better feedback that `pub rs_mime_find_header_token` was no longer used by the C side and should be removed as dead code ?

```
SV_BRANCH=pr/1371
```
SV tests from unit tests in https://github.com/OISF/suricata-verify/pull/1371

Draft : 
- I think #9435 should get merged first (and QA rebased over it)

### CODE REVIEW

**Comment by jasonish** [comment]
> @jasonish any ideas on how to get a better feedback that `pub rs_mime_find_header_token` was no longer used by the C side and should be removed as dead code ?

Not really.  The Rust code is just compiled into a library with externally addressable functions so I don't think we'll get a compiler to tell us.

**Comment by jasonish** [comment]
Do you have scripts already for finding unused C code?

```
nm target/release/libsuricata_rust.a |awk '$2 == "T" && $3 !~ /^_/ { print $3 }'
```
will get you all externally linkable C functions from the Rust code.  There are a few in there for other libraries like Brotli

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/9447

**Comment by catenacyber** [comment]
> > @jasonish any ideas on how to get a better feedback that `pub rs_mime_find_header_token` was no longer used by the C side and should be removed as dead code ?
> 
> Not really. The Rust code is just compiled into a library with externally addressable functions so I don't think we'll get a compiler to tell us.

Can a compiler/other tool tell us all the "externally addressable functions" from rust ? and check if they are used from C ?

**Comment by jasonish** [comment]
> Can a compiler/other tool tell us all the "externally addressable functions" from rust ? and check if they are used from C ?

I quick search tells me no.  The compiler links looks up functions it needs, it doesn't really see functions it doesn't need.  You can remove Rust from this question. As the `.a` library is the same as any other static C library, so all other tools like nm will work.

**Comment by catenacyber** [comment]
I was not thinking about nm but some rust-analyzer tool ;-) (if it exists)

**Comment by jasonish** [comment]
> I was not thinking about nm but some rust-analyzer tool ;-) (if it exists)

No, this is outside the scope of Rust and back in C land.

**Pull request closed without merging**
