### PR TITLE
http2: handle child_stream_id according to rfc

### PR DESCRIPTION
**Pull request by bulletforkiller**
Http2 handle child_stream_id according to RFC 7540

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- The PUSH_PROMISE frames sent by the server are sent on that explicit request's stream, so the promised stream identifier was the child stream id of the explicit request's stream. A previous version of that code set the promised stream identifier to the promised stream's child stream id.
- Added a function `process_child_stream_i` to set the promised stream identifier to child stream id of the explicit request's stream after handling PUSH_PROMISE frame, to clear child stream id of the explicit request's stream after handling CONTINUATION frame.

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks for this contribution.

Would you have a test for this ?
cf https://github.com/OISF/suricata-verify or simply a pcap ?

**Comment by bulletforkiller** [comment]
> Thanks for this contribution.
> 
> Would you have a test for this ? cf https://github.com/OISF/suricata-verify or simply a pcap ?

I don't have any http2 pcap in plaintext with PUSH_PROMISE frame, I simply run `nghttp -anv https://www.tunetheweb.com/performance/` and get the following result:

image

**Comment by catenacyber** [comment]
Thank you.

I am not sure how to interpret this nghttp output.
What is Suricata's output for such a flow ? And what should it be ?

**Comment by victorjulien** [comment]
Needs rebase to be able to run CI

**Comment by catenacyber** [comment]
@bulletforkiller are you working further on this ?

**Comment by victorjulien** [comment]
Needs a new version that passes CI, needs a test case in SV as well. Please submit a new PR, thanks!

**Pull request closed without merging**
