### PR TITLE
Dce fixes eloy/v1

### PR DESCRIPTION
**Pull request by inashivb**
#6711
#6510 
#6509 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
https://redmine.openinfosecfoundation.org/issues/4767
https://redmine.openinfosecfoundation.org/issues/4769

suricata-verify-pr: 613

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 5353

**Comment by inashivb** [comment]
I _think_ the current `master` behavior (i.e. without this patch) is replicated in `5.0.x` by [`DCERPCResetParsingState`](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1410).

@zer1t0 you mentioned [here](https://github.com/OISF/suricata/pull/6511)
> My guess, a misinterpretation how the protocol works, since I've check this function was added after moving the code to rust (maybe following the example of the smb handling, in which also deletes the bind state erroneously).

Could you please confirm if I interpreted the code correctly? I can see the tests (that you created for these changes https://github.com/OISF/suricata-verify/pull/613) failing on our `5.0.x` branch. That was pre-rust era.

**Comment by zer1t0** [comment]
> I _think_ the current `master` behavior (i.e. without this patch) is replicated in `5.0.x` by [`DCERPCResetParsingState`](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1410).
> 
> @zer1t0 you mentioned [here](https://github.com/OISF/suricata/pull/6511)
> 
> > My guess, a misinterpretation how the protocol works, since I've check this function was added after moving the code to rust (maybe following the example of the smb handling, in which also deletes the bind state erroneously).
> 
> Could you please confirm if I interpreted the code correctly? I can see the tests (that you created for these changes [OISF/suricata-verify#613](https://github.com/OISF/suricata-verify/pull/613)) failing on our `5.0.x` branch. That was pre-rust era.

I've reviewing and seems that [`DCERPCResetParsingState`](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1410) only resets the `ctxbytesprocessed` field of `dcerpcbindbindack`. What we care about in this case is the `accepted_uuid_list` field, that is used to check the iface in [`DetectDceIfaceMatch`](https://github.com/OISF/suricata/blob/master-5.0.x/src/detect-dce-iface.c#L302), and that is not reset by `DCERPCResetParsingState`. The `accepted_uuid_list` is only reset when the [state is freed](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1975) or a [new BIND message](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L947) [is received](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L888), which makes sense because is a context change.

However, I'm not sure why exactly the tests are failing. I prefer to dig in that question once this patch and the related tests are merged.

**Comment by inashivb** [comment]
> > I _think_ the current `master` behavior (i.e. without this patch) is replicated in `5.0.x` by [`DCERPCResetParsingState`](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1410).
> > @zer1t0 you mentioned [here](https://github.com/OISF/suricata/pull/6511)
> > > My guess, a misinterpretation how the protocol works, since I've check this function was added after moving the code to rust (maybe following the example of the smb handling, in which also deletes the bind state erroneously).
> > 
> > 
> > Could you please confirm if I interpreted the code correctly? I can see the tests (that you created for these changes [OISF/suricata-verify#613](https://github.com/OISF/suricata-verify/pull/613)) failing on our `5.0.x` branch. That was pre-rust era.
> 
> I've reviewing it and seems that [`DCERPCResetParsingState`](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1410) only resets the `ctxbytesprocessed` field of `dcerpcbindbindack`. What we care about in this case is the `accepted_uuid_list` field, that is used to check the iface in [`DetectDceIfaceMatch`](https://github.com/OISF/suricata/blob/master-5.0.x/src/detect-dce-iface.c#L302), and that is not reset by `DCERPCResetParsingState`. The `accepted_uuid_list` is only reset when the [state is freed](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L1975) or a [new BIND message](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L947) [is received](https://github.com/OISF/suricata/blob/master-5.0.x/src/app-layer-dcerpc.c#L888), which makes sense because is a context change.
> 
> However, I'm not sure why exactly the tests are failing in `5.0.x` branch. I prefer to dig in that question once this patch and the related tests were merged.

Thank you for the explanation. I mistakenly thought I saw a check against ctxbytesprocessed affecting it. Gonna get this merged in `master` soon. Thank you for your efforts with this! :)

**Comment by inashivb** [comment]
@zer1t0 could you please assign https://redmine.openinfosecfoundation.org/issues/4926 and https://redmine.openinfosecfoundation.org/issues/4928 to yourself if you plan to look into this later? Thank you very much!

**Comment by zer1t0** [comment]
> @zer1t0 could you please assign https://redmine.openinfosecfoundation.org/issues/4926 and https://redmine.openinfosecfoundation.org/issues/4928 to yourself if you plan to look into this later? Thank you very much!

Done

**Comment by victorjulien** [comment]
Merged in #6860, thanks @zer1t0 and @inashivb !

**Pull request closed without merging**
