### PR TITLE
Exception policy stats counters - 70x backports - v1

### PR DESCRIPTION
**Pull request by jufajardini**
Describe changes:
- Clean cherry-picks from https://github.com/OISF/suricata/pull/10785
- an extra commit with clang-formatting changes to the json schema
- clean cherry-picks for https://github.com/OISF/suricata/pull/10800

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6509

Parent ticket: https://redmine.openinfosecfoundation.org/issues/5816

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1754

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20019

**Comment by catenacyber** [comment]
Why do we need to backport #10800 ?

**Comment by jufajardini** [comment]
> Why do we need to backport #10800 ?

Don't need to, but the changes wanted to sneak in with mine, so thought I'd just bring them. Should I drop that commit?

**Comment by catenacyber** [comment]
> Don't need to, but the changes wanted to sneak in with mine, so thought I'd just bring them. Should I drop that commit?

Thanks for the explanation, I would keep it for cleanness of cherry-picks as this is not changing Suri behavior

**Review by catenacyber — APPROVED** [review]
LGTM as consistent with changes merged in master

CI : 🟢 
Code : consistent with changes merged in master
Commits segmentation : consistent with changes merged in master
Commit messages : consistent with changes merged in master
Git ID set : looks fine for me
CLA : you already contributed :-p
Doc update : consistent with changes merged in master
Redmine ticket : ok
Rustfmt : no rust
Tests : 🟢 
Dependencies added: none

**Comment by jufajardini** [comment]
We're taking time to rethink a bit if what the output looks like right now is what we want, or if we'd like to re-work those. As such, I'll close this for now, as it's very likely that there will be updates that'd impact the backports, too.

**Pull request closed without merging**
