### PR TITLE
Protocol detection 2757 v12

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2757

Describe changes:
- Use both directions for protocol detection over UDP (as is done with TCP)
- Changes `AppLayerProtoDetectPPGetProto` so that first packet does not bit mask away a protocol for both directions when config option midstream is activated 

The main goal was the first one (use both directions for UDP)
And then I came across this unwanted behavior from `AppLayerProtoDetectPPGetProto` :
When the first packet is no valid DNS but on port 53 (for instance a junk request), second packet (error response from server) does not get checked for DNS as first packet bit masked away DNS for both directions (ie `probing_parser_toclient_alproto_masks` and `probing_parser_toserver_alproto_masks`)

There are other open PRs regarding
https://redmine.openinfosecfoundation.org/issues/2757
such as "Support when multiple protocols have patterns matching (such as USER for FTP and IRC)"

Modifies #7119 with rebase and commit rewording as requested

suricata-verify-pr: 813
https://github.com/OISF/suricata-verify/pull/813

### CODE REVIEW

**Comment by victorjulien** [comment]
Many CI failures

**Comment by catenacyber** [comment]
> Many CI failures

Need to update some new S-V tests indeed

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw1_files_sha256.
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk | | |
| .flow.memuse | 530444608 | 498197568 | 106.47% |
| .app_layer.error.dns_udp.parser | 28003 | 4273 | 655.35% | 

Pipeline 7238

**Comment by victorjulien** [comment]
Merged in #7423, thanks!

**Pull request closed without merging**
