### PR TITLE
Warnint 64to32 6186 v18

### PR DESCRIPTION
**Pull request by catenacyber**
[Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6186

Describe changes:
- fix `-Wshorten-64-to-32` warnings for some files
- Add CI build with this warning

```
LIBHTP_BRANCH=pr/399
```
https://github.com/OISF/libhtp/pull/399

#9811 with core review taken into account

There must be some stuff to review more carefully

QA needs to be checked for defrag (and then have a git bisect...)

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .decoder.event.ipv4.frag_overlap | 805 | 511 | 63.48% | 

Pipeline 16645

**Review by victorjulien — CHANGES_REQUESTED** [review]
Needs review of the defrag QA result.

**Comment by catenacyber** [comment]
> Needs review of the defrag QA result.

@ct0br0 can you have a `git bisect` for this QA deviation ?

**Comment by catenacyber** [comment]
> Maybe it's a good idea to split the PR so we can already get parts merged.

Should I make a PR with just the first commit out of the 17 ones ?

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 16672

**Comment by catenacyber** [comment]
Closing as needing rebase, and split in multiple future PRs like #9878

**Pull request closed without merging**
