### PR TITLE
Add to docs 2081 v2

### PR DESCRIPTION
**Pull request by x62smith**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues/2081) ticket:

Original PR:
https://github.com/OISF/suricata/pull/3695#discussion_r261888898

Describe changes:
Corrected spelling and made punctuation in the tables uniform.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by x62smith** [comment]
@shivan1b I completely agree but is the first time I've actually submitted a PR and it was just a mess.  Trying to figure out the flow of how it works and of course it just got botched.

**Comment by shivan1b** [comment]
@x62smith no problem. Feel free to ask in case you're stuck somewhere.

**Comment by x62smith** [comment]
@shivan1b Is there a good way to remove the commits, without breaking something? :-)

**Comment by shivan1b** [comment]
I see that you've already managed to do that. Please close this and one other PR then.

**Comment by victorjulien** [comment]
Replaced by #3703

**Pull request closed without merging**
