### PR TITLE
Stage pull requests

### PR DESCRIPTION
**Pull request by jasonish**
Staging:
- https://github.com/OISF/suricata/pull/9019
- https://github.com/OISF/suricata/pull/9047
- https://github.com/OISF/suricata/pull/9048
- https://github.com/OISF/suricata/pull/9055

### CODE REVIEW

**Comment by catenacyber** [comment]
#9010 seems to be missing. Is it intended ?

**Comment by jasonish** [comment]
> #9010 seems to be missing. Is it intended ?

Looks like its already in master-6.0.x.

**Comment by catenacyber** [comment]
Is it normal that MacOS CI on master6 times out ?

**Comment by jasonish** [comment]
> Is it normal that MacOS CI on master6 times out ?

Not normal, but not that uncommon.  Its nothing to do with the branch, sometimes the MacOS runners take hours if not a day to get assigned. It does happen enough that I wonder if we should remove the MacOS job, or put it in its own workflow so we can get a faster feedback time on the other workflows.

**Comment by catenacyber** [comment]
Closing as #9019 requested some changes

**Pull request closed without merging**
