### PR TITLE
Ci warnint v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- Makes CI error on integer warnings !
- Fixes one newly introduced integer warning (by eb155639c6293e5fd412a8268a2c1a6ca03ebe45)

libhtp-pr: 369

Draft : I think there are a bit more warnings to fix

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104001 | 81.1% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 1509781 | - |
| .flow.end.state.new | 6272 | 15648 | 249.49% |
| .flow.end.tcp_state.syn_sent | 0 | 3164 | - |
| .flow.end.tcp_state.syn_recv | 0 | 25 | - |
| .flow.end.tcp_state.established | 53996 | 60055 | 111.22% |
| .flow.end.tcp_state.fin_wait1 | 0 | 421 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 172 | - |
| .flow.end.tcp_state.time_wait | 0 | 217 | - |
| .flow.end.tcp_state.last_ack | 0 | 136 | - |
| .flow.end.tcp_state.close_wait | 0 | 557 | - |
| .flow.end.tcp_liberal | 80952 | 140508 | 173.57% |
| .tcp.segment_from_pool | 15728353 | 16534046 | 105.12% |
| .tcp.reassembly_gap | 80952 | 279541 | 345.32% |
| .tcp.overlap | 0 | 27 | - |
| .app_layer.error.http.parser | 0 | 168 | - |
| .app_layer.error.ftp.gap | 0 | 32 | - |
| .app_layer.error.smtp.gap | 0 | 318 | - |
| .app_layer.error.tls.gap | 53852 | 106524 | 197.81% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 83 | - |
| .ftp.memuse | 0 | 387 | - | 

Pipeline 10352

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103972 | 81.08% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 2002919 | - |
| .flow.end.state.new | 6272 | 18809 | 299.89% |
| .flow.end.tcp_state.syn_sent | 0 | 4087 | - |
| .flow.end.tcp_state.syn_recv | 0 | 59 | - |
| .flow.end.tcp_state.established | 53996 | 61317 | 113.56% |
| .flow.end.tcp_state.fin_wait1 | 0 | 602 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 201 | - |
| .flow.end.tcp_state.time_wait | 0 | 300 | - |
| .flow.end.tcp_state.last_ack | 0 | 195 | - |
| .flow.end.tcp_state.close_wait | 0 | 834 | - |
| .flow.end.tcp_liberal | 80952 | 153182 | 189.23% |
| .tcp.reassembly_gap | 80952 | 317169 | 391.8% |
| .tcp.overlap | 0 | 27 | - |
| .app_layer.error.http.parser | 0 | 262 | - |
| .app_layer.error.ftp.gap | 0 | 35 | - |
| .app_layer.error.smtp.gap | 0 | 386 | - |
| .app_layer.error.tls.gap | 53852 | 117278 | 217.78% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 184 | - |
| .ftp.memuse | 0 | 256 | - | 

Pipeline 10355

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 4986525 | - |
| .flow.end.state.new | 6272 | 37779 | 602.34% |
| .flow.end.tcp_state.syn_sent | 0 | 11021 | - |
| .flow.end.tcp_state.syn_recv | 0 | 114 | - |
| .flow.end.tcp_state.established | 53996 | 72771 | 134.77% |
| .flow.end.tcp_state.fin_wait1 | 0 | 1617 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 522 | - |
| .flow.end.tcp_state.time_wait | 0 | 801 | - |
| .flow.end.tcp_state.last_ack | 0 | 504 | - |
| .flow.end.tcp_state.close_wait | 0 | 2189 | - |
| .flow.end.tcp_liberal | 80952 | 254133 | 313.93% |
| .tcp.reassembly_gap | 80952 | 741856 | 916.41% |
| .tcp.overlap | 0 | 77 | - |
| .app_layer.error.http.parser | 0 | 561 | - |
| .app_layer.error.ftp.gap | 0 | 84 | - |
| .app_layer.error.smtp.gap | 0 | 923 | - |
| .app_layer.error.tls.gap | 53852 | 205762 | 382.09% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 324 | - |
| .ftp.memuse | 0 | 288 | - | 

Pipeline 10357

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103975 | 81.08% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 1179847 | - |
| .flow.end.state.new | 6272 | 13673 | 218.0% |
| .flow.end.tcp_state.syn_sent | 0 | 2516 | - |
| .flow.end.tcp_state.syn_recv | 0 | 24 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 356 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 114 | - |
| .flow.end.tcp_state.time_wait | 0 | 183 | - |
| .flow.end.tcp_state.last_ack | 0 | 84 | - |
| .flow.end.tcp_state.close_wait | 0 | 460 | - |
| .flow.end.tcp_liberal | 80952 | 123247 | 152.25% |
| .tcp.reassembly_gap | 80952 | 230297 | 284.49% |
| .tcp.overlap | 0 | 19 | - |
| .app_layer.error.http.parser | 0 | 141 | - |
| .app_layer.error.ftp.gap | 0 | 21 | - |
| .app_layer.error.smtp.gap | 0 | 224 | - |
| .app_layer.error.tls.gap | 53852 | 91181 | 169.32% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 57 | - | 

Pipeline 10379

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8144

**Pull request closed without merging**
