### PR TITLE
dns: add missing dns keywords to schema.json v2

### PR DESCRIPTION
**Pull request by hadiqaalamdar**
Feature #5642

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5642) ticket: https://redmine.openinfosecfoundation.org/issues/5642

Previous PR: https://github.com/OISF/suricata/pull/10193

Describe changes:
- Added tc boolean field to dns object in schema.json file
- Added sshfp field in dns.answers and dns.grouped in schema.json
- SV tests are passing:
```
===> dns/dns-sshfp: OK

PASSED:  1
FAILED:  0
SKIPPED: 0
```
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1588

### CODE REVIEW

**Comment by jufajardini** [comment]
> NOTE: This PR may contain new authors.

Interesting, why would this be triggered, considering Hadiqa has contributions merged to master, and her author info seems unchanged? 🤔

**Comment by jasonish** [comment]
> > NOTE: This PR may contain new authors.
> 
> Interesting, why would this be triggered, considering Hadiqa has contributions merged to master, and her author info seems unchanged? 🤔

This is dependabot getting flagged. So please ignore. We'll have to suppress dependabot since it uses some job id in its email. Still curious as to why it got flagged as it wasn't part of this PR, maybe a rebase would clear it out as well.

**Comment by catenacyber** [comment]
You can rebase on latest master and the authors check should be green.

https://github.com/OISF/suricata/pull/10408 about it

**Comment by catenacyber** [comment]
And I rebased my SV PR to get CI greener on next run

**Review by jufajardini — CHANGES_REQUESTED** [review]
The additions look good, thanks for removing the added duplicated fields from last PR.

We are trying to add descriptions to the fields in the JSON schema, so this can also later be used for documentation. Could you please add that to the fields you have added? (one example PR where this is done: https://github.com/OISF/suricata/pull/10348/files)

I have added the `needs rebase` label based on the existing comments here.

**Comment by hadiqaalamdar** [comment]
New PR: https://github.com/OISF/suricata/pull/10429

**Pull request closed without merging**
