### PR TITLE
Include less v8

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- Remove unused includes in c files
- adds some options in CI : hyperscan, luajit

Now that #7644 is merged, we can remove includes from C files independently from one another.

Follows #7658 by being ready for review

Obtained with 
`./configure --enable-unittests --enable-debug --enable-geoip --enable-profiling --enable-lua`

Then `ls src/*.c | while read i; do echo $i; python3 scripts/mininc.py $i; done`

There is still some more removals :
- util-memrchr.h if the system has `memrchr`
- luajit stuff
- dpdk stuff
- ebpf stuff
- windows stuff
- libhiredis stuff
- maybe some FPs

Are there more config options to test ?

### CODE REVIEW

**Comment by jasonish** [comment]
nfqueue fails to build.  Even though we have CI builds with the nfqueue depedencies, it does not get enabled by default.  I added a commit to enable nfqueue for the Fedora 36 build over here: https://github.com/jasonish/suricata/runs/7637121133?check_suite_focus=true

**Comment by catenacyber** [comment]
Thanks Jason, pushing a new version to test it

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8466

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7686

**Pull request closed without merging**
