### PR TITLE
bittorrent-dht: add bittorrent-dht app-layer parser - v12

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/7838
Ticket: https://redmine.openinfosecfoundation.org/issues/3086

Changes from last PR:
- Fix some more non-string types
- Fix unit tests for non-string types

Reference BitTorrent DHT specification:
https://www.bittorrent.org/beps/bep_0005.html

suricata-verify-pr: 930

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128100 | 104085 | 81.25% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 243338 | - |
| .flow.end.state.new | 6272 | 7792 | 124.23% |
| .flow.end.tcp_state.syn_sent | 0 | 529 | - |
| .flow.end.tcp_state.syn_recv | 0 | 3 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 93 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 36 | - |
| .flow.end.tcp_state.time_wait | 0 | 52 | - |
| .flow.end.tcp_state.last_ack | 0 | 41 | - |
| .flow.end.tcp_state.close_wait | 0 | 133 | - |
| .flow.end.tcp_liberal | 80952 | 96506 | 119.21% |
| .tcp.reassembly_gap | 80952 | 127794 | 157.86% |
| .tcp.overlap | 0 | 4 | - |
| .app_layer.error.http.parser | 0 | 45 | - |
| .app_layer.error.ftp.gap | 0 | 11 | - |
| .app_layer.error.smtp.gap | 0 | 84 | - |
| .app_layer.error.tls.gap | 53852 | 67565 | 125.46% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 27 | - | 

Pipeline 10282

**Comment by victorjulien** [comment]
Codecov suggests no coverage for setting events, can we add tests for that?

**Comment by victorjulien** [comment]
Merged in #8113, thanks!

**Comment by jasonish** [comment]
> Codecov suggests no coverage for setting events, can we add tests for that?

That would have to be a S-V test right?  SInce a Rust unit test never actually calls back into the C code.

**Comment by victorjulien** [comment]
Was looking at this
image

**Pull request closed without merging**
