### PR TITLE
Domain extract

### PR DESCRIPTION
**Pull request by regit**
Number of IOCs sources are publishing domains list. Matching on them using dataset looks like the way to use these data.
But dataset is only doing to strict string matching so matching on sub domains and hostnames is not possible via dataset. A way to extract the domain from hosts name is thus necessary.

This PR adds 2 new transforms `domain` and `tld` using a crate named PSL (https://github.com/addr-rs/psl) that is available under MIT license.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5639

Describe changes:
- Add domain transform
- Add tld transform

### CODE REVIEW

**Comment by regit** [comment]
This is a draft, I need to add documentation and suricata verify tests. But I would like to see if the license and crate are ok.

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10422

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_cfg.
  

Pipeline 10427

**Comment by victorjulien** [comment]
@jasonish can you review Erics question on the new crate?

**Comment by jasonish** [comment]
> @jasonish can you review Erics question on the new crate?

The data is licensed under the MPL which I believe is fine. 

The lists are updated daily. I wonder if it's something we could incorporate as a data source with Suricata update. However that would be the slow path.

**Comment by victorjulien** [comment]
> > @jasonish can you review Erics question on the new crate?
> 
> The data is licensed under the MPL which I believe is fine.
> 
> The lists are updated daily. I wonder if it's something we could incorporate as a data source with Suricata update. However that would be the slow path.

What do you mean with slow path here?

**Comment by jasonish** [comment]
> > > @jasonish can you review Erics question on the new crate?
> > 
> > 
> > The data is licensed under the MPL which I believe is fine.
> > The lists are updated daily. I wonder if it's something we could incorporate as a data source with Suricata update. However that would be the slow path.
> 
> What do you mean with slow path here?

There is the PSL crate that embeds the database (license OK) and claims to be fast.  Then there is https://crates.io/crates/publicsuffix, which is more or less the same but uses an external database file so you can update it independent of making a patch release, but it claims to be slower.

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_cfg.
  

Pipeline 10427

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_cfg.
  

Pipeline 10427

**Comment by victorjulien** [comment]
As it's clear that this PR won't go in, I'm closing this. It seems like the discussion on what lib/crate to use can move to the ticket.

**Comment by woundride** [comment]
It's a real shame, I agree with @regit  this feature would be very useful, especially for integrating lists of malicious domains.

**Comment by catenacyber** [comment]
A new PR is welcome for this feature :-)

**Comment by victorjulien** [comment]
> It's a real shame, I agree with @regit this feature would be very useful, especially for integrating lists of malicious domains.

We didn't reject the idea, just the implementation. So open to contributions on this.

**Pull request closed without merging**
