### PR TITLE
Backports 6.0.4 b2/v4

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4383

suricata-verify-pr: 538

### CODE REVIEW

**Comment by victorjulien** [comment]
This still needs more lua related backports I think, I see quite a few failures still. @jufajardini can you point out the fixes required for the new tests?

**Comment by jufajardini** [comment]
> This still needs more lua related backports I think, I see quite a few failures still. @jufajardini can you point out the fixes required for the new tests?

Wondering if just the commit that modifies the callbacks for SCFIleInfo should be included in this backport, or all that are related to the usage of `lua_pushinteger`?

**Comment by suricata-qa** [comment]
WARNING:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.mgr.rows_maxlen | 364 | 539 | 67.53% |
| .flow.mgr.flows_timeout_inuse | 0 | 1247 | 0.0% |

Pipeline 4294

**Comment by inashivb** [comment]
Replaced w #6411

**Pull request closed without merging**
