### PR TITLE
Backport: 6.0.x: flow manager: using too much CPU during idle

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #7765

Backport to 6.0.x -- flow manager

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4421](https://redmine.openinfosecfoundation.org/issues/4421)

Updates:
- Address review comments

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
@ct0br0 can you add the QA issue that we found for the almost identical PR #7765 here?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | generic_collect | | |
 

Pipeline 8822
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

**Comment by victorjulien** [comment]
This fails QA by not cleanly shutting down the flow manager somehow. @ct0br0 should be able to provide more details.

**Comment by jlucovsky** [comment]
> This fails QA by not cleanly shutting down the flow manager somehow. @ct0br0 should be able to provide more details.

@ct0br0 Can you provide details?

**Comment by ct0br0** [comment]
Hey Jeff, sorry for the delay. This leaves a dangeling flow manager thread when running and Suricata is unable to close. Should be a timing issue if I had to guess from fidling with flow manager the other week.


```
{"timestamp":"2022-08-25T13:10:51.976662+0000","log_level":"Notice","event_type":"engine","engine":{"message":"Signal Received.  Stopping engine."}}
{"timestamp":"2022-08-25T13:11:53.000689+0000","log_level":"Error","event_type":"engine","engine":{"error_code":188,"error":"SC_ERR_SHUTDOWN","message":"unable to get all flow manager threads to shutdown in time"}}
```

**Comment by jlucovsky** [comment]
@ct0br0 Thanks for the update.

**Comment by victorjulien** [comment]
Sounds like FM not waking up while trying to shut it down. I think the main thread gives it 60s, during which it continuously pokes it to wake up.

**Comment by jlucovsky** [comment]
Continued in #7800

**Pull request closed without merging**
