### PR TITLE
protocol parser: rdp

### PR DESCRIPTION
**Pull request by lmzke**
Initial implementation of #2314:
1. Add protocol parser for RDP
2. Add transactions for RDP negotiation
3. Add eve logging of transactions

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- https://redmine.openinfosecfoundation.org/issues/2314

New contributor, all feedback welcome.

Sample output (based on [wireshark RDP-002.pcap](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=view&target=RDP-002.pcap.gz)):

```json
{
  "timestamp": "2007-10-24T18:58:09.119601-0400",
  "flow_id": 2031235224416398,
  "pcap_cnt": 5,
  "event_type": "rdp",
  "src_ip": "10.226.24.52",
  "src_port": 3389,
  "dest_ip": "10.226.41.226",
  "dest_port": 10446,
  "proto": "TCP",
  "rdp": {
    "tx_id": 0,
    "event_type": "initial_request",
    "cookie": "A70067"
  }
}
{
  "timestamp": "2007-10-24T18:58:09.119844-0400",
  "flow_id": 2031235224416398,
  "pcap_cnt": 6,
  "event_type": "rdp",
  "src_ip": "10.226.41.226",
  "src_port": 10446,
  "dest_ip": "10.226.24.52",
  "dest_port": 3389,
  "proto": "TCP",
  "rdp": {
    "tx_id": 1,
    "event_type": "initial_response"
  }
}
{
  "timestamp": "2007-10-24T18:58:09.120861-0400",
  "flow_id": 2031235224416398,
  "pcap_cnt": 7,
  "event_type": "rdp",
  "src_ip": "10.226.24.52",
  "src_port": 3389,
  "dest_ip": "10.226.41.226",
  "dest_port": 10446,
  "proto": "TCP",
  "rdp": {
    "tx_id": 2,
    "event_type": "connect_request",
    "client": {
      "version": "v5",
      "desktop_width": 1152,
      "desktop_height": 864,
      "color_depth": 15,
      "keyboard_layout": "en-US",
      "build": "Windows XP",
      "client_name": "ISD2-KM84178",
      "keyboard_type": "enhanced",
      "function_keys": 12,
      "product_id": 1,
      "capabilities": [
        "support_errinfo_pdf"
      ],
      "id": "55274-OEM-0011903-00107"
    },
    "channels": [
      "rdpdr",
      "cliprdr",
      "rdpsnd"
    ]
  }
}
{
  "timestamp": "2007-10-24T18:58:09.121164-0400",
  "flow_id": 2031235224416398,
  "pcap_cnt": 8,
  "event_type": "rdp",
  "src_ip": "10.226.41.226",
  "src_port": 10446,
  "dest_ip": "10.226.24.52",
  "dest_port": 3389,
  "proto": "TCP",
  "rdp": {
    "tx_id": 3,
    "event_type": "connect_response"
  }
}
```

### CODE REVIEW

**Comment by lmzke** [comment]
I activated Travis CI on my fork, and will work to get all checks passing.

**Comment by lmzke** [comment]
This PR has a dependency on tls-parser v0.8.1 (for nom 4), which does not compile on rustc 1.31.0 or rustc 1.31.1.

See also &lt;https://codeberg.org/matthiasbeyer/repolocli/commit/a816c326eb245dc265a7e5aad1043423bb807978&gt;.

I get clean builds (for tls-parser v0.8.1, all other dependencies, and the source) on rustc 1.32.0 and stable (1.36.0).

What would it take to bump rustc in `.travis.yml`?

**Comment by jasonish** [comment]
> What would it take to bump rustc in `.travis.yml`?

There is a RUST_VERSION in the build matrix you can bump.  Note that as of now we still need to build with Rust 1.24.1.  We hope to up the minimum version soon, but haven't yet.

**Comment by lmzke** [comment]
Continued in #4095.

**Pull request closed without merging**
