### PR TITLE
doc: add bypass keyword documentation

### PR DESCRIPTION
**Pull request by jmtaylor90**
Signed-off-by: jason taylor <jtfas90@gmail.com>

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ x ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ x ] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ x ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2600

Describe changes:
- add bypass keyword documentation
-
-

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
Think it would be good to add some things:
* explain that the bypass can be handled in 3 places 1) suricata itself, 2) kernel, 3) driver/nic (add link to the af-packet ebpf document)
* add reference to "ignoring traffic"
* add section to "ignoring traffic" about rule based bypass

Are you interesting adding these suggestions?

**Comment by jmtaylor90** [comment]
Yeah absolutely. I figured there would be more to add but wanted to get this out there to see if it was heading in the right direction.

**Comment by victorjulien** [comment]
I wonder if there should be a master page about the concept 'bypass', then this page about how to trigger it from the rules. Plus references from/to the concept to the afpacket implementation, the 'ignoring traffic', etc

**Comment by jmtaylor90** [comment]
Would you want the master page to be something added to the performance/ignoring-traffic.rst page or an entirely new bypassing-traffic.rst page?

**Comment by victorjulien** [comment]
I guess it's fine if the concept is explained in ignoring-traffic, the same is done for other similar concepts. Good point.

**Comment by jmtaylor90** [comment]
replaced by #3525

**Pull request closed without merging**
