### PR TITLE
Rfb frames v12

### PR DESCRIPTION
**Pull request by hsadia538**
- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5717

Previous PR: https://github.com/OISF/suricata/pull/8416

Describe changes:

- Rebase branch

suricata-verify-pr: 1117

### CODE REVIEW

**Comment by victorjulien** [comment]
Looking at the pcap from our SV tests I think there are many more things we can do.

E.g. for this packet
image

I would think we can do something like:
`tpkt.hdr`, `tpkt.data`
something for the iso 8073 layer
something for the t.125 layer
Then the RDP portion has a header, a signature and a data portion.

**Comment by hsadia538** [comment]
> Looking at the pcap from our SV tests I think there are many more things we can do.
> 
> E.g. for this packet image
> 
> I would think we can do something like: `tpkt.hdr`, `tpkt.data` something for the iso 8073 layer something for the t.125 layer Then the RDP portion has a header, a signature and a data portion.

I think the screenshot you have shared represents RDP protocol. The packet data of RFB does not contain any fields that can be categorized. Sharing a snippet below:
Screenshot 2023-02-10 at 6 01 52 PM

**Comment by victorjulien** [comment]
Whoops you are right. Will have a look at RFB.

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Unfortunately this no longer compiles after rebasing it to master. This is because the tests added in 6b55e53ff56ad5a263ee240472acd4db2f702dec fail to compile. I didn't see a quick fix.

**Comment by hsadia538** [comment]
> 6b55e53

So basically the tests need a new PR for both to compile?

**Comment by jufajardini** [comment]
> > [6b55e53](https://github.com/OISF/suricata/commit/6b55e53ff56ad5a263ee240472acd4db2f702dec)
> 
> So basically the tests need a new PR for both to compile?

I think you'll need to rebase, then adjust the unit tests to compile with the new additions, and then submit a new PR for frames and adjusted tests.

**Comment by hsadia538** [comment]
Followed by #8693

**Pull request closed without merging**
