### PR TITLE
detect/bytemath: Support out of order options 

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #7789

The intent of this PR is to support arbitrary order options for `byte_math`. During the investigation phase, it was suggested that the parser be converted to Rust for simplification. Thus, the PCRE based parser for `byte_math` was removed and replaced with a Rust based parser. @jasonish's prototype rules parser work helped guide this PR.

The C unittests were retained and many were added to the Rust based parser.

Issue: 5077

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [5077](https://redmine.openinfosecfoundation.org/issues/5077)

Describe changes:
- Converts the PCRE based parser to Rust.
- Adds unit tests to the new Rust modules
- Removes the PCRE parser from detect-bytemath.c
- Adjusts the C source modules to refer to the Rust definitions

Updates
- Commit fixups (doc related).

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .tcp.rst | 126016 | 103033 | 122.31% | 

Pipeline 8909
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. BE MINDFUL OF ANY RESULTS.

**Review by catenacyber — APPROVED** [review]
Ok for me, some comments in the details :

- CI : green
- Code : Looks good to me
- Commits segmentation : ok for me :-)
- Commit message : Look good to me, thanks for the changes
- Git ID set : ok
- CLA : ok ;-)
- Doc update : good for me, Juliana was also ok I think
- Redmine ticket : ok
- Rustfmt : `rustfmt rust/src/detect/*.rs` looks good :-)
- Tests : Ok for me. I would like to see a SV test about the fix of use of multiplication in bytemath ;-)
- Dependencies added: none

**Comment by jufajardini** [comment]
> Ok for me, some comments in the details :
> 
> * CI : green
> * Code : Looks good to me
> * Commits segmentation : ok for me :-)
> * Commit message : Look good to me, thanks for the changes
> * Git ID set : ok
> * CLA : ok ;-)
> * Doc update : good for me, Juliana was also ok I think
> * Redmine ticket : ok
> * Rustfmt : `rustfmt rust/src/detect/*.rs` looks good :-)
> * Tests : Ok for me. I would like to see a SV test about the fix of use of multiplication in bytemath ;-)
> * Dependencies added: none

Good with me as well! :)

**Comment by victorjulien** [comment]
Fails `lua-byte-extract` SV test for me:

```
[3260876] 20/9/2022 -- 10:20:55 - (suricata.c:1149) <Notice> (LogVersion) -- This is Suricata version 7.0.0-dev (9a08164059 2022-09-20) running in USER mode
[3260876] 20/9/2022 -- 10:20:55 - (detect-bytemath.c:204) <Error> (DetectByteMathParse) -- [ERRCODE: SC_ERR_PCRE_PARSE(7)] - invalid bytemath values
[3260876] 20/9/2022 -- 10:20:55 - (detect-engine-loader.c:191) <Error> (DetectLoadSigFile) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ip any any -> any any (msg:"GPL ATTACK_RESPONSE id check returned root"; content:"uid=0|28|root|29|"; classtype:bad-unknown; byte_math: bytes 4, offset 0, oper +, rvalue 0, result var2; lua:lua-byte-math.lua; sid:2; rev:7;)" from file /home/victor/sync/qa/sv/all/00default/lua-byte-extract/test.rules at line 2
[3260876] 20/9/2022 -- 10:20:55 - (suricata.c:2351) <Error> (LoadSignatures) -- [ERRCODE: SC_ERR_NO_RULES_LOADED(43)] - Loading signatures failed.
```

**Comment by jlucovsky** [comment]
> Fails `lua-byte-extract` SV test for me:
> 
> ```
> [3260876] 20/9/2022 -- 10:20:55 - (suricata.c:1149) <Notice> (LogVersion) -- This is Suricata version 7.0.0-dev (9a08164059 2022-09-20) running in USER mode
> [3260876] 20/9/2022 -- 10:20:55 - (detect-bytemath.c:204) <Error> (DetectByteMathParse) -- [ERRCODE: SC_ERR_PCRE_PARSE(7)] - invalid bytemath values
> [3260876] 20/9/2022 -- 10:20:55 - (detect-engine-loader.c:191) <Error> (DetectLoadSigFile) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ip any any -> any any (msg:"GPL ATTACK_RESPONSE id check returned root"; content:"uid=0|28|root|29|"; classtype:bad-unknown; byte_math: bytes 4, offset 0, oper +, rvalue 0, result var2; lua:lua-byte-math.lua; sid:2; rev:7;)" from file /home/victor/sync/qa/sv/all/00default/lua-byte-extract/test.rules at line 2
> [3260876] 20/9/2022 -- 10:20:55 - (suricata.c:2351) <Error> (LoadSignatures) -- [ERRCODE: SC_ERR_NO_RULES_LOADED(43)] - Loading signatures failed.
> ```

I checked the Snort source code and byte math only accepts values from 1 to the max uint32 value. To maintain compatibility with Suri (which accepts 0-uint32-max), I'll update the snort diff docs.

**Comment by jlucovsky** [comment]
Continued in #7894

**Pull request closed without merging**
