### PR TITLE
Batch backports to 5.0.x

### PR DESCRIPTION
**Pull request by jlucovsky**
Batch backports to 5.0.x 

Describe changes:
- Github CI -- Almalinux 8.4 instead of CentOS 8: [5091](https://redmine.openinfosecfoundation.org/issues/5091)
- FTP Segfault: [4889](https://redmine.openinfosecfoundation.org/issues/4889)
- Reference config validation: [4678](https://redmine.openinfosecfoundation.org/issues/4678)
- Application log re-use when not root: [5103](https://redmine.openinfosecfoundation.org/issues/5103)
- SWF Coverity warning: [5109](https://redmine.openinfosecfoundation.org/issues/5109)

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 6343

**Comment by pevma** [comment]
QA retrying the rust build run and will update.

**Comment by pevma** [comment]
Latest QA run
```
3 major deviations in alert counts
"2034813:5"
 base 6342 vs test 4247
"2836094:3"
 base 2221 vs test 1223
"2836155:3"
 base 2214 vs test 1220
```

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on tlpr1_alerts_cmp.
  

Pipeline 6362

**Comment by jlucovsky** [comment]
Closing to add more backports ...

**Pull request closed without merging**
