### PR TITLE
Smtp server detection 1125 v2.5

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/1125
https://redmine.openinfosecfoundation.org/issues/6821
https://redmine.openinfosecfoundation.org/issues/5491

Describe changes:
- smtp server detection (ie to_client)
- ftp server detection (ie to_client)
- smtp recognize more reply codes

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1894

 https://github.com/OISF/suricata/pull/11314 with dummy debug prints for @ct0br0

### CODE REVIEW

**Comment by ct0br0** [comment]
Just realized the changes are in this PR but the baseline had more ftp-tx in stats. How could I printf out for ftp-tx without the changes?

**Comment by catenacyber** [comment]
> Just realized the changes are in this PR but the baseline had more ftp-tx in stats. How could I printf out for ftp-tx without the changes?

I hope the less ftp txs come from more smtp flows that are printed...

**Comment by ct0br0** [comment]
Ok I can pull the SMTP then

**Comment by ct0br0** [comment]
So we have 141 more ftp.tx in the pcap from lolstmpX flows compared to master but the last PR had 5658 ftp.tx difference between master8 and the PR. Sounds like we need a master printf too to get all packets that ftp.tx have then?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.smtp.parser | 409 | 42 | 10.27% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.smtp | 335817 | 347615 | 103.51% |
| .app_layer.flow.failed_tcp | 178240 | 167256 | 93.84% |
| .app_layer.tx.ftp | 101030 | 95386 | 94.41% |
| .app_layer.error.smtp.parser | 527 | 144 | 27.32% |
| .ftp.memuse | 10637 | 2906 | 27.32% | 

Pipeline 21142

**Comment by catenacyber** [comment]
Thanks Corey, https://github.com/OISF/suricata/pull/11333 should be better for FTP

**Pull request closed without merging**
