### PR TITLE
Ips/v36/debug

### PR DESCRIPTION
**Pull request by catenacyber**
Just #7463 with some debug reproducer features

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 7719

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 7720

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on tlpw1_files_sha256.

ERROR: QA failed on tlpr1_alerts_cmp.
  

Pipeline 7722

**Comment by catenacyber** [comment]
Solved by getting the failing test from a previous public corpus

**Pull request closed without merging**
