### PR TITLE
readthedocs - docutils.conf to disable smart quotes, minor updates

### PR DESCRIPTION
**Pull request by wesinator**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- disable smart quotes rendering on readthedocs

fixes examples like https://suricata.readthedocs.io/en/latest/rules/dns-keywords.html#dns-query

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Looks good to me.
It looks like CI failure is due to CI itself

**Comment by catenacyber** [comment]
Could you rebase a new branch on top of master with your changes and open a new PR ?

**Comment by wesinator** [comment]
> Could you rebase a new branch on top of master with your changes and open a new PR ?

did my merge work for you ? I can always open a new PR

**Comment by catenacyber** [comment]
> did my merge work for you ?

Yes but clang-format CI seems unhappy.
Could you fix this ?

**Pull request closed without merging**
