### PR TITLE
Defrag cleanup/v4

### PR DESCRIPTION
**Pull request by victorjulien**
bring defrag hash handling closer to flow hash handling:
- free trackers on lookup
- new stats
 
Also modified `max-frags` behavior: if we hit max-frags the tracker is now freed.  

replaces #11122

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20781

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 642 | 667 | 103.89% | 

Pipeline 20785

**Comment by inashivb** [comment]
Do you plan on working more on this? w.r.t. Draft status

**Comment by victorjulien** [comment]
replaced by #11209

**Pull request closed without merging**
