### PR TITLE
pgsql: allow out of order parameters in startup message - v2

### PR DESCRIPTION
**Pull request by jufajardini**
This is a continuation of the work done by @catenacyber in https://github.com/OISF/suricata/pull/7778

Previous PR: #8072

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5579

Describe changes:
- support out of order parameters in the pgsql startup message
move the database message into the optional parameters, as it's indeed an optional parameter
- update the json schema accordingly
- There is still work to be done related to the initial bug report by Philippe (pgsql should not error out when reaching a parsing error, if it's still capable of finding the next PDU on the stream [5524](https://redmine.openinfosecfoundation.org/issues/5524))

suricata-verify-pr: 978

### CODE REVIEW

**Comment by victorjulien** [comment]
CI fail is likely https://redmine.openinfosecfoundation.org/issues/5595

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128100 | 104087 | 81.25% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 312469 | - |
| .flow.end.state.new | 6272 | 8187 | 130.53% |
| .flow.end.tcp_state.syn_sent | 0 | 579 | - |
| .flow.end.tcp_state.syn_recv | 0 | 8 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 101 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 41 | - |
| .flow.end.tcp_state.time_wait | 0 | 55 | - |
| .flow.end.tcp_state.last_ack | 0 | 27 | - |
| .flow.end.tcp_state.close_wait | 0 | 127 | - |
| .flow.end.tcp_liberal | 80952 | 97530 | 120.48% |
| .tcp.segment_from_pool | 15600086 | 16551811 | 106.1% |
| .tcp.reassembly_gap | 80952 | 126943 | 156.81% |
| .tcp.overlap | 0 | 8 | - |
| .app_layer.error.http.parser | 0 | 42 | - |
| .app_layer.error.ftp.gap | 0 | 7 | - |
| .app_layer.error.smtp.gap | 0 | 95 | - |
| .app_layer.error.tls.gap | 53852 | 68636 | 127.45% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 27 | - | 

Pipeline 10171

**Comment by catenacyber** [comment]
Thanks for this work Juliana ;-)

**Comment by jufajardini** [comment]
> Thanks for this work Juliana ;-)

Thanks for spotting this up, and for your work :D

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #8118, thanks!

**Pull request closed without merging**
