### PR TITLE
Include less v9

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- Remove unused includes in c files
- adds some options in CI : hyperscan, luajit

Now that #7644 is merged, we can remove includes from C files independently from one another.

Follows #7677 by including nfqueue

Obtained with 
`./configure --enable-unittests --enable-debug --enable-geoip --enable-profiling --enable-lua`

Then `ls src/*.c | while read i; do echo $i; python3 scripts/mininc.py $i; done`

There is still some more removals :
- util-memrchr.h if the system has `memrchr`
- luajit stuff
- dpdk stuff
- ebpf stuff
- windows stuff
- libhiredis stuff
- maybe some FPs

Are there more config options to test ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8471

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8473

**Comment by catenacyber** [comment]
CI green : ready for review

**Comment by jasonish** [comment]
> Are there more config options to test ?

Some that might be harder to test?  Napatech, PF_RING, and DAG support?

We seem good for NF_QUEUE now tho.

**Comment by catenacyber** [comment]
> > Are there more config options to test ?
> 
> Some that might be harder to test? Napatech, PF_RING, and DAG support?
> 
> We seem good for NF_QUEUE now tho.

Who can try these ?
Should we ignore some files in this PR to be safer ?

**Comment by jasonish** [comment]
> > > Are there more config options to test ?
> > 
> > 
> > Some that might be harder to test? Napatech, PF_RING, and DAG support?
> > We seem good for NF_QUEUE now tho.
> 
> Who can try these ? Should we ignore some files in this PR to be safer ?

I can test PF_RING at some point.  Jeff can test Napatech, say after we do a release candidate.  And I can poke someone at Endace re DAG.

**Comment by victorjulien** [comment]
pfring
```
runmode-pfring.c: In function 'OldParsePfringConfig':
runmode-pfring.c:114:17: error: implicit declaration of function 'StringParseInt32' [-Werror=implicit-function-declaration]
  114 |             if (StringParseInt32(&pfconf->threads, 10, 0, threadsstr) < 0) {
      |                 ^~~~~~~~~~~~~~~~
runmode-pfring.c: In function 'ParsePfringConfig':
runmode-pfring.c:244:36: error: implicit declaration of function 'UtilCpuGetNumProcessorsOnline' [-Werror=implicit-function-declaration]
  244 |             pfconf->threads = (int)UtilCpuGetNumProcessorsOnline();
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c:248:35: error: implicit declaration of function 'GetIfaceRSSQueuesNum' [-Werror=implicit-function-declaration]
  248 |                 pfconf->threads = GetIfaceRSSQueuesNum(iface);
      |                                   ^~~~~~~~~~~~~~~~~~~~
runmode-pfring.c:255:17: error: implicit declaration of function 'StringParseUint16' [-Werror=implicit-function-declaration]
  255 |             if (StringParseUint16(&threads, 10, 0, (const char *)threadsstr) < 0) {
      |                 ^~~~~~~~~~~~~~~~~
runmode-pfring.c:393:9: error: implicit declaration of function 'LiveGetOffload' [-Werror=implicit-function-declaration]
  393 |     if (LiveGetOffload() == 0) {
      |         ^~~~~~~~~~~~~~
runmode-pfring.c:394:13: error: implicit declaration of function 'GetIfaceOffloading' [-Werror=implicit-function-declaration]
  394 |         if (GetIfaceOffloading(iface, 0, 1) == 1) {
      |             ^~~~~~~~~~~~~~~~~~
runmode-pfring.c:399:9: error: implicit declaration of function 'DisableIfaceOffloading' [-Werror=implicit-function-declaration]
  399 |         DisableIfaceOffloading(LiveGetDevice(iface), 0, 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c:399:32: error: implicit declaration of function 'LiveGetDevice' [-Werror=implicit-function-declaration]
  399 |         DisableIfaceOffloading(LiveGetDevice(iface), 0, 1);
      |                                ^~~~~~~~~~~~~
runmode-pfring.c: At top level:
runmode-pfring.c:421:51: error: unknown type name 'ConfigIfaceParserFunc'
  421 | static int GetDevAndParser(const char **live_dev, ConfigIfaceParserFunc *parser)
      |                                                   ^~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c: In function 'RunModeIdsPfringAutoFp':
runmode-pfring.c:455:5: error: unknown type name 'ConfigIfaceParserFunc'
  455 |     ConfigIfaceParserFunc tparser;
      |     ^~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c:459:5: error: implicit declaration of function 'TimeModeSetLive' [-Werror=implicit-function-declaration]
  459 |     TimeModeSetLive();
      |     ^~~~~~~~~~~~~~~
runmode-pfring.c:461:11: error: implicit declaration of function 'GetDevAndParser' [-Werror=implicit-function-declaration]
  461 |     ret = GetDevAndParser(&live_dev, &tparser);
      |           ^~~~~~~~~~~~~~~
runmode-pfring.c:467:11: error: implicit declaration of function 'RunModeSetLiveCaptureAutoFp' [-Werror=implicit-function-declaration]
  467 |     ret = RunModeSetLiveCaptureAutoFp(tparser,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c: In function 'RunModeIdsPfringSingle':
runmode-pfring.c:490:5: error: unknown type name 'ConfigIfaceParserFunc'
  490 |     ConfigIfaceParserFunc tparser;
      |     ^~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c:502:11: error: implicit declaration of function 'RunModeSetLiveCaptureSingle' [-Werror=implicit-function-declaration]
  502 |     ret = RunModeSetLiveCaptureSingle(tparser,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c: In function 'RunModeIdsPfringWorkers':
runmode-pfring.c:525:5: error: unknown type name 'ConfigIfaceParserFunc'
  525 |     ConfigIfaceParserFunc tparser;
      |     ^~~~~~~~~~~~~~~~~~~~~
runmode-pfring.c:537:11: error: implicit declaration of function 'RunModeSetLiveCaptureWorkers' [-Werror=implicit-function-declaration]
  537 |     ret = RunModeSetLiveCaptureWorkers(tparser,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
At top level:
runmode-pfring.c:410:12: warning: 'PfringConfLevel' defined but not used [-Wunused-function]
  410 | static int PfringConfLevel(void)
      |            ^~~~~~~~~~~~~~~
runmode-pfring.c:183:14: warning: 'ParsePfringConfig' defined but not used [-Wunused-function]
  183 | static void *ParsePfringConfig(const char *iface)
      |              ^~~~~~~~~~~~~~~~~
runmode-pfring.c:82:14: warning: 'OldParsePfringConfig' defined but not used [-Wunused-function]
   82 | static void *OldParsePfringConfig(const char *iface)
      |              ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

**Comment by catenacyber** [comment]
Thanks Victor.
Before fixing these, I would like to think the overview.

What is the best course of action ?
Is the general approach good ?
Can we add these options like pfring in CI ?

**Comment by victorjulien** [comment]
> Thanks Victor. Before fixing these, I would like to think the overview.
> 
> What is the best course of action ? Is the general approach good ? Can we add these options like pfring in CI ?

Good question. PFRING is getting increasingly irrelevant to us I think, esp with DPDK. But I'm also no longer aware of any user of it.

That said, this change is not a good reason to remove it or anything. That will require a bit more discussion and planning.

**Comment by jasonish** [comment]
> Can we add these options like pfring in CI ?

It would be possible to add PF_RING, but not Napatech or DAG as those are closed libraries.

**Comment by victorjulien** [comment]
FreeBSD + ipfw
```
  CC       runmode-ipfw.o
../../../src/runmode-ipfw.c:57:5: error: implicit declaration of function 'TimeModeSetLive' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    TimeModeSetLive();
    ^
../../../src/runmode-ipfw.c:59:5: error: implicit declaration of function 'LiveDeviceHasNoStats' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    LiveDeviceHasNoStats();
    ^
../../../src/runmode-ipfw.c:61:11: error: implicit declaration of function 'RunModeSetIPSAutoFp' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ret = RunModeSetIPSAutoFp(IPFWGetThread,
          ^
../../../src/runmode-ipfw.c:61:11: note: did you mean 'RunModeIpsIPFWAutoFp'?
../../../src/runmode-ipfw.c:49:5: note: 'RunModeIpsIPFWAutoFp' declared here
int RunModeIpsIPFWAutoFp(void)
    ^
../../../src/runmode-ipfw.c:77:5: error: implicit declaration of function 'TimeModeSetLive' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    TimeModeSetLive();
    ^
../../../src/runmode-ipfw.c:79:5: error: implicit declaration of function 'LiveDeviceHasNoStats' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    LiveDeviceHasNoStats();
    ^
../../../src/runmode-ipfw.c:81:11: error: implicit declaration of function 'RunModeSetIPSWorker' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ret = RunModeSetIPSWorker(IPFWGetThread,
          ^
../../../src/runmode-ipfw.c:81:11: note: did you mean 'RunModeIpsIPFWWorker'?
../../../src/runmode-ipfw.c:69:5: note: 'RunModeIpsIPFWWorker' declared here
int RunModeIpsIPFWWorker(void)
    ^
6 errors generated.
```

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8487

**Comment by victorjulien** [comment]
I have fixes for ipfw and netmap, will also see if I can patch up pfring and test nflog.

**Comment by catenacyber** [comment]
> I have fixes for ipfw and netmap, will also see if I can patch up pfring and test nflog.

Leaving you to it for the next couple of weeks ;-)

**Comment by pastly** [comment]
Hello.

My group develops network traffic sensors that use Suricata's support for PF_RING. These aren't just small lab VMs; these 10 Gbps sensors will be deployed at around 100 sites. It is very important to us that Suricata maintains its PF_RING support.

I know this doesn't contribute to the direct topic of this ticket. While searching for tickets related to a Suricata+PF_RING issue I'm having, I saw this one and thought I'd mention there's at least one big user of this feature.

**Comment by victorjulien** [comment]
> > Good question. PFRING is getting increasingly irrelevant to us I think, esp with DPDK. I'm also no longer aware of any user of it.
> > That said, this change is not a good reason to remove it or anything. That will require a bit more discussion and planning.
> 
> Hello.
> 
> My group develops network traffic sensors that use Suricata's support for PF_RING. These aren't just small lab VMs; these 10 Gbps sensors will be deployed at around 100 sites. It is very important to us that Suricata maintains its PF_RING support.
> 
> I know this doesn't contribute to the direct topic of this ticket. While searching for tickets related to a Suricata+PF_RING issue I'm having, I saw this one and thought I'd mention there's at least one big user of this feature.

Thanks @pastly, this helps give perspective. Lots of users are not telling us what they do, so it can seem some parts of suri remain unused.

**Comment by crossoverTang** [comment]
Hello. Is there any documentation to help build and run suricata+dpdk. Thanks.

**Comment by jufajardini** [comment]
> Hello. Is there any documentation to help build and run suricata+dpdk. Thanks.

Hi!

There's this, from our userguide:
https://suricata.readthedocs.io/en/latest/configuration/suricata-yaml.html?highlight=dpdk#data-plane-development-kit-dpdk

And there's also a presentation from last year's SuriCon, which also discusses a bit DPDK's implementation on Suricata:
https://youtu.be/XU950_dEN0Q

Hope these help, but if you have more questions, do share them in our forum: https://forum.suricata.io/ you'll have views from more folks there ^^

**Comment by catenacyber** [comment]
Maybe I need to revisit this and have some smarter script about the ifdefs...

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7872

**Pull request closed without merging**
