### PR TITLE
SDP protocol: implement parser and logger v3

### PR DESCRIPTION
**Pull request by glongo**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6627

Describe changes:
- SDP version is not logged
- `js.open_object('sdp')` is moved in SDP logger
- `is_ipaddr` renamed with `is_ipaddr_char`
- Remove `unwrap()`
- Use `verify` in `parse_num` function

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1741

### CODE REVIEW

**Review by jufajardini — COMMENTED** [review]
Was about to ask if we should update the `EVE` outputs documentation section to include this change, and noticed we don't have such a section for `SIP`. So:
- Should we add such documentation for `SIP` (as a separate work and ticket)
- Should we add an output section for `SDP`?

**Comment by catenacyber** [comment]
CI should get green for MacOS on rebase on latest master

**Comment by glongo** [comment]
> Was about to ask if we should update the `EVE` outputs documentation section to include this change, and noticed we don't have such a section for `SIP`. So:
> 
>     * Should we add such documentation for `SIP` (as a separate work and ticket)

Yes, IMO. I can take care of that.

>     * Should we add an output section for `SDP`?
And yes.

**Comment by glongo** [comment]
Replaced with https://github.com/OISF/suricata/pull/10835

**Pull request closed without merging**
