### PR TITLE
iprep improvements v1

### PR DESCRIPTION
**Pull request by glongo**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2759
https://redmine.openinfosecfoundation.org/issues/659

Describe changes:

This patchset would bring some improvements
for IP-Reputation module adding new features and fixes
minor issues.

One major change is the ability to add IP addresses via unix-socket, this is done by keeping a list of IPs added and when the rules are reloaded iprep loads the IPs from the list.

It's possible to have at most 100 IPs in pending,
then the user is forced to run 'reload-rules' to be able to add them again until the maximum number of entries via unix-socket is reached, which is 500 IPs.

This approach permits to not use a lock when a lookup occurs, but it is used when an IP is added to provide thread safety.

Also, number of categories and reputation score are doubled, as requested. I'm not sure if the ticket required something else to do.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR glongo: https://buildbot.openinfosecfoundation.org/builders/glongo/builds/203
- PR glongo-pcap: https://buildbot.openinfosecfoundation.org/builders/glongo-pcap/builds/67

### CODE REVIEW

**Comment by victorjulien** [comment]
Haven't looked at the code yet, but wanted to understand the summary first: the unix socket command to add iprep won't go into effect until a rule reload? If so I think the design needs some extra thought.

**Comment by glongo** [comment]
Yes exactly, rule reload is needed to have iprep going into effect.

**Comment by victorjulien** [comment]
I'd like to see a different approach, as I don't like the delay or the arbitrary 100 rep limit. Could you do a new PR with this functionality removed and just the other commits?

**Comment by glongo** [comment]
Replaced by #3723

**Pull request closed without merging**
