### PR TITLE
2497.dev

### PR DESCRIPTION
**Pull request by jlucovsky**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2497 ticket:

Describe changes:
This PR adds a subsystem and module identifier to SCLog messages when the log format includes %S. Subsystem and module identifiers are intrinsic properties of threads and source code modules (respectively).

New threads are assigned a subsystem identifier when the thread is created; the identifier is a Thread-Local-Storage variable declared in util-debug.c; values are assigned to it as threads are created using SCSetSubsystem (a macro defined in util-debug.h).

Module identifiers are assigned using SCSetModule (macro defined in util-debug.h).

Subsystem and module identifiers are added to log messages when the format contains %S. The generated log message will substitute a tag built from

The subsystem identifier
(Optional) The module identifier will be included if set (not all source modules will set one)
The constructed tag is of the form [subsystem-id[:module-identifier]] (the first and last brackets are literal; the brackets surrounding the module-identifier indicate the module-identifier is optional).

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
It seems to lack some consistency still, e.g.
```
SC_LOG_FORMAT="%S: " ./src/suricata -c suricata.yaml -l tmp/ -r ~/sync/pcap/sandnet.pcap --disable-detection -vv
Suricata-main: detection engine disabled
Error opening file /var/log/suricata/suricata.log
Suricata-main: This is Suricata version 5.0.0-dev (rev c95512abd)
Suricata-main: CPUs/cores online: 12
Suricata-main: fast output device (regular) initialized: fast.log
Suricata-main: eve-log output device (regular) initialized: eve.json
Suricata-main: stats output device (regular) initialized: stats.log
RX#01:receive-pcap-file: Checking file or directory /home/victor/sync/pcap/sandnet.pcap
RX#01: /home/victor/sync/pcap/sandnet.pcap: Plain file, not a directory
RX#01:receive-pcap-file: Argument /home/victor/sync/pcap/sandnet.pcap was a file
Suricata-main: all 13 packet processing threads, 4 management threads initialized, engine started.
RX#01:receive-pcap-file: Starting file run for /home/victor/sync/pcap/sandnet.pcap
RX#01: No packets with invalid checksum, assuming checksum offloading is NOT used
RX#01:pcap-file-dispatch: pcap file /home/victor/sync/pcap/sandnet.pcap end of file reached (pcap err code 0)
Suricata-main: Signal Received.  Stopping engine.
FM#01:flow-manager: 0 new flows, 0 established flows were timed out, 0 flows in closed state
Suricata-main: time elapsed 2.656s
FR#01:flow-manager: 147629 flows processed
RX#01:receive-pcap-file: Pcap-file module read 1 files, 1354508 packets, 413760573 bytes
tmqh-flow: AutoFP - Total flow handler queues - 12
counters: Alerts: 0
ippair: ippair memory usage: 414144 bytes, maximum: 16777216
: segment_pool_memuse 0
: segment_pool_memcnt 0
host: host memory usage: 398144 bytes, maximum: 33554432
: htp memory 0 (0)
```

Sometimes we have nothing, sometimes we have just a thread name, sometimes just a subsystem name and other times both.

**Comment by victorjulien** [comment]
Side thought: wonder if we should rename Suricata-Main to something like Ctl here, so make it nice and short so it's more like the other thread names.

**Comment by jasonish** [comment]
Some tools like `top` show the thread name instead of process name, so it might be confusing to some to not see a `suricata` process.  `htop` doesn't do this though, nor does `ps` output.

Maybe its a CentOS specific thing with `top`?  Haven't really looked into it though.

**Comment by jlucovsky** [comment]
Closing for rebuild.

**Pull request closed without merging**
