### PR TITLE
Discard truncate fn/v4

### PR DESCRIPTION
**Pull request by inashivb**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/7044

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1964

Previous PR: https://github.com/OISF/suricata/pull/11435

Changes since v3:
- unstage incorrect removal of smb fns

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPW1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 137 | 144 | 105.11% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 642 | 665 | 103.58% | 

Pipeline 21388

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21407

**Comment by catenacyber** [comment]
Nice :-)

**Comment by victorjulien** [comment]
Merged in #11488, thanks!

**Pull request closed without merging**
