### PR TITLE
Pcap log/v4

### PR DESCRIPTION
**Pull request by victorjulien**
Replaces #11103. Addressing a newly found issue: https://redmine.openinfosecfoundation.org/issues/7037

https://redmine.openinfosecfoundation.org/issues/7034
https://redmine.openinfosecfoundation.org/issues/7037

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1844

### CODE REVIEW

**Comment by jasonish** [comment]
`pl->h` is still passed onto `pcap_dump`, is its full nice not written out to disk?

**Comment by victorjulien** [comment]
> `pl->h` is still passed onto `pcap_dump`, is its fully not written out to disk?

No, it's not. I think it's converted internally in libpcap.

**Review by jasonish — APPROVED** [review]
Looks good. Tested, file sizes are much more accurate. Tested with lz4 as well.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20711

**Comment by victorjulien** [comment]
Merged in #11120, thanks!

**Pull request closed without merging**
