### PR TITLE
next/562/20240831/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #11576
 - #11627
 - #11628
 - #11655
 - #11685
 - #11686

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22305

**Comment by catenacyber** [comment]
> ERROR: QA failed on SURI_TLPR1_alerts_cmp.

Is this expected ?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .flow.end.tcp_state.established | 8 | 9 | 112.5% | 

Pipeline 22307

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .flow.end.tcp_state.established | 8 | 9 | 112.5% | 

Pipeline 22309

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22310

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22312

**Review by catenacyber — APPROVED** [review]
Looks consistent with the approved PRs, and QA previous glitchy results are likely not dur to this PR...

**Pull request merged**
