### PR TITLE
Backport 5.0.x Bundle

### PR DESCRIPTION
**Pull request by jlucovsky**
Backport bundle to 5.0.x with the following issues:

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- [3669](https://redmine.openinfosecfoundation.org/issues/3669)
- [3667](https://redmine.openinfosecfoundation.org/issues/3667)

### CODE REVIEW

**Comment by victorjulien** [comment]
@pjyoung1 can you review and build test this? It will go into 5.0.3 for which the window is closing within a few hours.

**Comment by pjyoung1** [comment]
I'm not sure if you saw my earlier comment on [PR 4870](https://github.com/OISF/suricata/pull/4870) since the PR was closed.

This is not building correctly.  There are too many parameters to the TmThreadsCaptureHandleTimeout() function as added to source_napatech.c.  Are there missing changes to tm-threads or was this function added incorrectly to this file?

**Comment by victorjulien** [comment]
Yes, I saw that. But this is a different branch (5.0.x) so things may be different here. Did you build *this* PR?

**Comment by pjyoung1** [comment]
This is failing in a different place.  It appears an ending  brace is missing somewhere.  I downloaded  from this branch from https://github.com/jlucovsky/suricata/tree/backport-5.0.x/1.  I'm building it as follows:

$ ./autogen.sh
$ ./configure --enable-napatech
$ make

When I do I get the following errors:

source-napatech.c: In function ‘NapatechPacketLoopZC’:
source-napatech.c:596:1: error: expected declaration or statement at end of input
 }
 ^
source-napatech.c:596:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^

**Comment by pjyoung1** [comment]
Looks like either a cut/paste or a merge error at line 372:

        /* Napatech returns packets 1 at a time */
        status = NT_NetRxGet(ntv->rx_stream, &packet_buffer, 1000);
->     if (unlikely(status == NT_STATUS_TIMEOUT || status == NT_STATUS_TRYAGAIN)) {
        if (unlikely(
                status == NT_STATUS_TIMEOUT || status == NT_STATUS_TRYAGAIN)) {
            if (status == NT_STATUS_TIMEOUT) {
                TmThreadsCaptureHandleTimeout(tv, ntv->slot, NULL);
            }
            continue;

**Comment by jlucovsky** [comment]
Once the conflict is resolved, you shouldn't have any syntactical issues.

**Comment by jlucovsky** [comment]
Continued in #4892

**Pull request closed without merging**
