### PR TITLE
rust: fix lint warnings about if same then else -v9

### PR DESCRIPTION
**Pull request by Rai0Catodic0**
Ticket: [4609](https://redmine.openinfosecfoundation.org/issues/4609)

[ :white_check_mark: ]  I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
    [  :white_check_mark: ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
 - [ ]  I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Previous PR: #8035 

Describe changes:
- Fixed commit message

### CODE REVIEW

**Comment by jasonish** [comment]
Still one issue with the commit message, the author line is showing up like:
```
Author:     Gabriel Lima Luz <gabriel.luz.limahotmail.com>
```
you can fix this like so:
```
git config -g user.email gabriel.luz.lima@hotmail.com
git commit --amend --author "Gabriel Lima Luz <gabriel.luz.lima@hotmail.com>"
```
then you can force push that to your branch.

**Comment by jufajardini** [comment]
> ```
> ```
> Author:     Gabriel Lima Luz <gabriel.luz.limahotmail.com>
>  ```
> > you can fix this like so:
> > ```
> git config -g user.email gabriel.luz.lima@hotmail.com
> git commit --amend --author "Gabriel Lima Luz <gabriel.luz.lima@hotmail.com>"
> ```
> > then you can force push that to your branch.
> ```
> 
> Sorry about that. I believe it is correct now.

It is, thanks :)

**Review by inashivb — APPROVED** [review]
Nice job, @Rai0Catodic0 ! LGTM. Thank you. :)
Depends on https://github.com/OISF/suricata/pull/8007

**Comment by jasonish** [comment]
Merged via https://github.com/OISF/suricata/pull/8051. Thanks!

**Pull request closed without merging**
