### PR TITLE
http2: remove http2.header keyword

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5780

Describe changes:
- http2: remove http2.header as it is confusing with `http.header`
- Keep the functionality with keywords `http2.request_header` and `http2.response_header` which match an individual header

@victorjulien do you also want to add the individual header matching on HTTP1 ? and have the keyword be `http.request_header`

### CODE REVIEW

**Comment by catenacyber** [comment]
Previous PR was https://github.com/OISF/suricata/pull/8371

**Comment by catenacyber** [comment]
Looks like I need to modify S-V tests...

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .flow.end.tcp_state.last_ack | 1004 | 257 | 25.6% |
| .tcp.rst | 145769 | 113397 | 77.79% |
| | SURI_TLPR1_stats_chk | | |
| .flow.end.tcp_state.fin_wait2 | 156072 | 127814 | 81.89% | 

Pipeline 12794

**Comment by victorjulien** [comment]
The ticket suggests doing just `http.request_header`/`http.request_headers`, not specific http1 and http2 variants.

**Comment by catenacyber** [comment]
Going on in https://github.com/OISF/suricata/pull/8621

**Pull request closed without merging**
