### PR TITLE
next/437/20240513/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #11046
 - #11049

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 20566

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 20571

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20582

**Review by jasonish — APPROVED** [review]
Still need to iterate on https://github.com/OISF/suricata/pull/11041, but this is good for now.

**Pull request merged**
