### PR TITLE
propose: codeql security-extended suite

### PR DESCRIPTION
**Pull request by 0xEniola**
Add the CodeQL security-extended suite to the CodeQL workflow configuration.

The `security-extended` query suite consists of all the queries in the default query suite, with addition of queries with slightly lower precision and severity, although, relative to the `default` query suite, the security-extended suite may return a greater number of false positive code scanning results.

It will allow us to catch likely flaws in the codebase that we may have missed during development, and flaws that are not checked for with the `default` suite, hence, allowing for greater hardening of Suricata, and eradicating potential threats.

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Commit should say: `codeql: add security-extended query`.

**Comment by 0xEniola** [comment]
> Commit should say: `codeql: add security-extended query`.

OK!

Thank you.

**Comment by 0xEniola** [comment]
> Commit should say: `codeql: add security-extended query`.

should I just leave it at `query`? And not add `suite`?
Because it's not a query, it's a suite of queries.

**Comment by inashivb** [comment]
> > Commit should say: `codeql: add security-extended query`.
> 
> should I just leave it at `query`? And not add `suite`? Because it's not a query, it's a suite of queries.

Please add it then. :)

**Pull request closed without merging**
