### PR TITLE
detect: free all tenant detect engines

### PR DESCRIPTION
**Pull request by jlucovsky**
Free all tenants registered in the master.

(cherry picked from commit a4d80bc7c4910170aba950db0a497124712b330a)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6549](https://redmine.openinfosecfoundation.org/issues/6549)

Describe changes:
- Free all tenant detect engines (and indirect references)

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1562
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17293

**Comment by catenacyber** [comment]
[redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6549](https://redmine.openinfosecfoundation.org/issues/6549) is closed ?

**Comment by jlucovsky** [comment]
> 6549

I've reopened 6549 with a note about the new problem.

**Comment by victorjulien** [comment]
Interestingly, this fails my arm64 alpine (so musl c-lib?)
image
It does not fail all my arm64 builds, e.g. ubuntu is fine.

**Comment by victorjulien** [comment]
My windows builder also failed, but that may just be an issue with the SV test requirements
image

**Review by victorjulien — CHANGES_REQUESTED** [review]
Fails my QA

**Comment by jlucovsky** [comment]
> My windows builder also failed, but that may just be an issue with the SV test requirements image

Do you have the output directories for some of these tests available?

**Comment by victorjulien** [comment]
> > My windows builder also failed, but that may just be an issue with the SV test requirements image
> 
> Do you have the output directories for some of these tests available?

I don't.

**Comment by jlucovsky** [comment]
Continued in #10217

**Pull request closed without merging**
