### PR TITLE
Printable/v14

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1616

https://redmine.openinfosecfoundation.org/issues/6553

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 182 | 192 | 105.49% | 

Pipeline 17775

**Review by jlucovsky — APPROVED** [review]

**Comment by jasonish** [comment]
Bug 6553 is flagged as a backport, but in this PR we are adding extra data. Any thoughts on how this might affect log processing tools?

**Comment by victorjulien** [comment]
> Bug 6553 is flagged as a backport, but in this PR we are adding extra data. Any thoughts on how this might affect log processing tools?

Not sure. I think the old output also printed more in some cases than expected due to broken overlap printing. It's certainly a change, so maybe we need a more conservative approach for backports.

**Comment by victorjulien** [comment]
> > Bug 6553 is flagged as a backport, but in this PR we are adding extra data. Any thoughts on how this might affect log processing tools?
> 
> Not sure. I think the old output also printed more in some cases than expected due to broken overlap printing. It's certainly a change, so maybe we need a more conservative approach for backports.

But anyway, this is for master. We can discuss the backport when the backport is done.

**Comment by victorjulien** [comment]
replaced by #10592

**Pull request closed without merging**
