### PR TITLE
Revert "detect: do not store state without flags"

### PR DESCRIPTION
**Pull request by victorjulien**
This reverts commit 2fb50598f23b112f14ec15330e11c40b74caa35f.

Logic is incorrect, a shown by failing tests.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1623

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]

**Review by jasonish — APPROVED** [review]

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17945

**Comment by catenacyber** [comment]
Also to investigate:
- why the spurious retransmission in SV bug-2576-02 is seen as an error by the dispatch function
- why is the `filemd5` keyword a "packet" keyword ?

**Comment by victorjulien** [comment]
> Also to investigate:
> 
>     * why the spurious retransmission in SV bug-2576-02 is seen as an error by the dispatch function
> 
>     * why is the `filemd5` keyword a "packet" keyword ?

I don't this it is?

**Comment by victorjulien** [comment]
I'm not going to take this in, as we feel the commit is correct but instead exposes another issue that we'll address in master and then backport.

**Comment by victorjulien** [comment]
> > > * why is the `filemd5` keyword a "packet" keyword ?
> > 
> > 
> > I don't this it is?
> 
> Maybe not the right naming, but I mean that a signature with only `filemd5` keyword as the one in bug-2576-02 is taken in by `DetectRunPrefilterPkt` + `DetectPrefilterBuildNonPrefilterList` (and thus uses scratch alproto) instead of by `DetectRunTx` and its subfunctions (unless it is stored)

I have some work that changes this logic, but in short: any sig that doesn't have a prefilter/fast_pattern is handled this way.

**Pull request closed without merging**
