### PR TITLE
Rust: generic files definition

### PR DESCRIPTION
**Pull request by jufajardini**
Issue: Optimization 3825
- filecontainer: add Files structure, to replace/unify SMBFiles
 and NFSFiles
- smb/files: delete SMBFiles implementation
- smb/smb: replace SMBFiles with Files
- nfs/nfs: delete NFSFiles implementation, replace its former
 declarations with Files' ones

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3825

Link to previous PR:
https://github.com/OISF/suricata/pull/5511

Describe changes:
- filecontainer: add Files structure, to replace/unify SMBFiles  and NFSFiles
- smb/files: delete SMBFiles implementation 
- smb/smb: replace SMBFiles with Files
- nfs/nfs: delete NFSFiles implementation, replace its former declarations with Files' ones
- squash commits to keep things clean

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by jufajardini** [comment]
Hi, have checked the details for the failed checks on appveyor, but I'm not quite sure what's wrong on my side. Can you please help me understand what do I have to do here, or if there's something else in my code that may be causing this, and I wasn't able to realise?

Thanks in advance! :)

**Comment by inashivb** [comment]
About appveyor: Doesn't seem like an issue on your end. :)

**Comment by jasonish** [comment]
Appveyor seems to be having issues today.

**Review by catenacyber — CHANGES_REQUESTED** [review]
There is also HTTP2 in addition to SMB and NFS which should be replaced

**Comment by jufajardini** [comment]
> There is also HTTP2 in addition to SMB and NFS which should be replaced

Yeah, I saw that in the original discussion, but since it was not listed in this issue, and since I'm still new to the project, I need some approvals before tackling that. 

Can it be done right now, in this very branch/issue?

**Comment by catenacyber** [comment]
Yes it can be done in this issue.
But you can create a new branch optimization-3825-v3

**Comment by jufajardini** [comment]
ok, thanks! will try to do another PR tomorrow evening, then.

**Comment by jufajardini** [comment]
Replaced by: https://github.com/OISF/suricata/pull/5531

to implement changes requested by @catenacyber .

**Pull request closed without merging**
