### PR TITLE
Snmp usm 5416 v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5416

Describe changes:
- Adds `snmp.usm` keyword

suricata-verify-pr: 865

Spin-off PR of #7566 

There is no documentation added... Should there be ?

Should we put these new files in a detect subdirectory ?

What about the direction of this keyword ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8032

**Comment by victorjulien** [comment]
Did you intend to include the script commit?

**Comment by catenacyber** [comment]
> Did you intend to include the script commit?

Yes, should I not include it ?

Why is there the needs-verify label when there is a Suricata-verify test ?

**Comment by victorjulien** [comment]
> There is no documentation added... Should there be ?

Yes. I think asking this question is answering it.

**Comment by victorjulien** [comment]
Wrt direction, I don't know enough about the protocol to answer it.

**Comment by catenacyber** [comment]
> Wrt direction, I don't know enough about the protocol to answer it.

It appears in both directions in the S-V pcap, so looks consistent...


Replaced by https://github.com/OISF/suricata/pull/7601

**Pull request closed without merging**
