### PR TITLE
detect/http-host: clean up tests

### PR DESCRIPTION
**Pull request by victorjulien**
Some quick unittest cleanups.

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Comment by catenacyber** [comment]
Why not convert to suricata-verify ?

> +1,712 −6,195

Nice, I need that for my LoC-neutrality

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 137 | 143 | 104.38% | 

Pipeline 20717

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11120, thanks!

**Comment by catenacyber** [comment]
Please let me clean src//tests/detect-http-server-body.c ;-)

cf `find src/ -name "*.c" | xargs wc -l | sort -n`

**Comment by victorjulien** [comment]
Btw I pushed this file because it had the largest number of missed lines in this view https://app.codecov.io/gh/OISF/suricata/tree/master/src%2Ftests (sort by missed column)

**Pull request closed without merging**
