### PR TITLE
defrag: fix wrong datalink being logged

### PR DESCRIPTION
**Pull request by victorjulien**
Bug: #6887.

https://redmine.openinfosecfoundation.org/issues/6887

### CODE REVIEW

**Comment by victorjulien** [comment]
> How do you test this ? How gets `datalink` field used ?

It's logged in eve and tells you the data type of the packet logging. So if there is an ethernet header, the datalink should reflect that, instead of claiming RAW (so first byte is start of the IP header)

**Comment by catenacyber** [comment]
So, is there a SV test for this fix ?

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 645 | 691 | 107.13% | 

Pipeline 20016

**Comment by victorjulien** [comment]
> So, is there a SV test for this fix ?

https://github.com/OISF/suricata/pull/10817

Replaced by #10817.

**Pull request closed without merging**
