### PR TITLE
Dataset set postmatch 5576 v8

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/5576

Describe changes:
- detect/dataset: delay set operation after signature full match

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2000

https://github.com/OISF/suricata/pull/11714 with diff split into different commits, with more explanations and more comments in the code

So, now Victor, you will ask me for more tests 
- rule with multibuffer + content + dataset vs traffic having multiple buffers but only one matching
- rule with dataset + pcap with transaction spanning over multiple packets (like https://github.com/OISF/suricata-verify/pull/1999 but with dataset instead of flowvar)

Right ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22386

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22428

**Comment by catenacyber** [comment]
@ct0br0 could I have some more data about this QA report ?

**Comment by catenacyber** [comment]
Draft: QA results to investigate, (I think it will end in a needed QA rebaseline)

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11834

**Pull request closed without merging**
