### PR TITLE
ftp: completely parses pasv and epsv responses

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4447

Describe changes:
- Completely parses ftp epsv response

suricata-verify-pr: 491

### CODE REVIEW

**Comment by catenacyber** [comment]
Windows CI failure seems unrelated

**Review by jasonish — COMMENTED** [review]
Looks good. Could we also add a test in the unit tests for this parser?

**Comment by catenacyber** [comment]
> Could we also add a test in the unit tests for this parser?

In addition to the Suricata Verify test ? or in replacement ?

**Comment by catenacyber** [comment]
https://github.com/OISF/suricata-verify/pull/491

**Comment by jasonish** [comment]
> In addition to the Suricata Verify test ? or in replacement ?

Both is fine.  But this is pretty trivially unit-tested so I think it should exist as a unit test.

**Comment by catenacyber** [comment]
> > In addition to the Suricata Verify test ? or in replacement ?
> 
> Both is fine. But this is pretty trivially unit-tested so I think it should exist as a unit test.

Replaced by https://github.com/OISF/suricata/pull/6096

**Pull request closed without merging**
