### PR TITLE
Backport/7.0.x: dpdk: interrupt mode, hugepage analysis, removing old docs' references

### PR DESCRIPTION
**Pull request by lukashino**
https://redmine.openinfosecfoundation.org/issues/6697
https://redmine.openinfosecfoundation.org/issues/6696
https://redmine.openinfosecfoundation.org/issues/6699

Describe changes:
- docs update - remove references to the old versions
- interrupt mode for DPDK
- better hugepage analysis

### CODE REVIEW

**Comment by lukashino** [comment]
Note: the Redmine tickets were not officially planned for 7.0.3 but I think it is okay to add it in.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17679

**Comment by catenacyber** [comment]
I think it deserves different PRs for the different issues.

There is one about doc, and the other ones change code for instance...

**Comment by victorjulien** [comment]
Agree, please split into separate PRs. Not going to consider the powersaving mode for 7.0.3.

**Review by victorjulien — CHANGES_REQUESTED** [review]
See inline

**Comment by lukashino** [comment]
Okay, thanks all, continues in:
https://github.com/OISF/suricata/pull/10225
https://github.com/OISF/suricata/pull/10226
https://github.com/OISF/suricata/pull/10227

**Pull request closed without merging**
