### PR TITLE
Unused parameters v2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
None, generic cleanup

Describe changes:
- remove some unused parameters in functions
- remove some useless `return;` line at the end of a function

Continuation of #11080

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 20664

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20673

**Comment by catenacyber** [comment]
Not sure I should keep this on...

**Comment by victorjulien** [comment]
> Not sure I should keep this on...

Would like to see this get merged. Can you rebase and do a new PR?

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11155

**Pull request closed without merging**
