### PR TITLE
Rust updates/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Updates to some of @chifflier's crates. Bumps MSRV to 1.67.0.

### CODE REVIEW

**Comment by victorjulien** [comment]
Debian stable has Rust 1.63.

**Comment by victorjulien** [comment]
Ubuntu 18.04 is stuck at 1.65.

Haven't checked CentOS Stream yet. Otherwise, I've updated https://redmine.openinfosecfoundation.org/issues/6573

Seems if we want to bump MSRV we have to leave Debian 12 and Ubuntu 18 behind, but given that we still have over a year before the 8 release date that seems acceptable.

**Comment by jasonish** [comment]
> Seems if we want to bump MSRV we have to leave Debian 12 and Ubuntu 18 behind, but given that we still have over a year before the 8 release date that seems acceptable.

Debian 12 is our dist-builder, we can either use Rustup there and choose something else as the dist-builder.  Pretty sure I have a patch here that does that as I have a branch that needed at least 1.64.0 somewhere.

**Comment by chifflier** [comment]
Hi all,

All my crates have 1.63 as MSRV. Did you encounter any problem with 1.63 ?

**Comment by victorjulien** [comment]
> Hi all,
> 
> All my crates have 1.63 as MSRV. Did you encounter any problem with 1.63 ?

I saw this https://github.com/rusticata/asn1-rs/commit/a20e5f7319c896737ad0f2557037817b91ad854f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR16, but I haven't actually tried if 1.63 works.

**Comment by chifflier** [comment]
Ah, got it.
It is possible to build with 1.63, but `asn1-rs` has a dependency that requires to pin the `time` version in the CI script:
https://github.com/rusticata/asn1-rs/blob/asn1-rs-0.6.1/.github/workflows/rust.yml#L24-L26

**Comment by victorjulien** [comment]
Looks like MSRV 1.63 indeed still works.

**Comment by victorjulien** [comment]
replaced by #10541

**Pull request closed without merging**
