### PR TITLE
Small Doc update (suricata.yaml.in)

### PR DESCRIPTION
**Pull request by King-Konsto**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [not necessary] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
There is no ticket for my changes.
Describe changes:
suricata.yaml.in
- add var for DC_SERVERS (Domain Controller) 
- add note for dns.log (not availbale when rust is enabled) 
- add note for dns v1 not available with rust 
- add smb default detection ports 137 and 138 (udp)

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by norg** [comment]
Overall good addition, but not sure if we want to include **DC_SERVERS** by default. We should at least document it somewhere, seems to be rather new within some rulesets. Would also like @victorjulien oppinion on that.

**Comment by victorjulien** [comment]
I've cherry-picked all but the smb ports one. Do you have some pcaps with traffic over those ports?

Note that I've rewritten the commit messages in include a prefix and to make sure subject line is short.

**Comment by victorjulien** [comment]
Merged the commits I mentioned in #3457, thanks!

**Comment by King-Konsto** [comment]
Thanks. I will try to capture pcaps on sensors where I can share them with you.

Cheers,

Konstantin

**Comment by victorjulien** [comment]
Thanks. Closing this PR. We can handle the SMB discussion in IRC or with a new dedicated PR after analyzing the pcap(s).

**Pull request closed without merging**
