### PR TITLE
dev environment feature

### PR DESCRIPTION
**Pull request by Hillsie**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- PR  with devcontainer configured with prerequisites that auto install
- Makes it easier to get up an running and contributing
- Decouples the local environment and enables quickly swap between environment
- Read more https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers&ssr=false

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by Hillsie** [comment]
This was a late night pr  and  I couldn't find the  "undo"  of “ready for review” – my bad 🙏️. It's back to `draft` now.  I'll also re-label as some more appropriate - dev environment feature.

**The backstory:**
Managing separate or semi-sandboxed development environments has a bit of a challenge for me until I found the `ms-vscode-remote.remote-containers` plugin. This has improved the process of rebuilding, debugging, and setting up development environments for different projects.  While setting up this project, thought that if others faced similar challenges that this might offer an easier solution.

**A Quick guide to getting up and running:**
- Prerequisites : `VSCode, Docker Desktop, ms-vscode-remote.remote-containers plugin, git`.
- Launch Docker Desktop
- Navigate to the `Remote Explorer` and select `Add new dev container`. Choose the option to 'Clone Repository in Container Volume,'  which puts the the repository and branch to clone into a container.
- Answer some prompts with personal preferences
   
This triggers a development container build and installs project prerequisites into the container.

_Note: There is one prompt in the vscode terminal during the final build setup. I'm unsure if there's an unattended `cargo install --force cbindgen` option._

If you run into snags, let me know, happy to assist where I am able.

**Comment by jufajardini** [comment]
Hello there, thanks a lot for the time you've dedicated to this contribution and for willing to share tooling to help other developers :)

Unfortunately, I think this isn't the type of work we want to merge in our official repo.

If you still want to share it, maybe you could share your repo in the `Developers` category in our forum: https://forum.suricata.io/ :)

In the future, if you want to get feedback on feature suggestions before spending a lot of development time, you can also create a Feature ticket on our Redmine (https://redmine.openinfosecfoundation.org/projects/suricata/issues) or just post about it on the forum.

**Comment by jasonish** [comment]
Just wanted to record this here:

- Using a devcontainer configuration from an external directory: https://code.visualstudio.com/docs/devcontainers/create-dev-container#_alternative-repository-configuration-folders
- Some prior work here: https://github.com/jasonish/suricata-devcontainer

**Comment by Hillsie** [comment]
@jufajardini  Of course, no worries. Please feel free to close the pr.
@jasonish Thanks for the reference. I'll take a look and see how I can use it.

**Comment by jufajardini** [comment]
> @jufajardini Of course, no worries. Please feel free to close the pr. @jasonish Thanks for the reference. I'll take a look and see how I can use it.

Thanks once again, and sorry for not accepting this, this time. It is something that we discuss a lot internally, but haven't come up to a conclusion yet...

Closing this PR for now, as, although we understand tooling like this can be very useful, we're not sure at this point that this is the right approach for us to maintain.

**Pull request closed without merging**
