### PR TITLE
5.0.x - backport nfs fixes - v1

### PR DESCRIPTION
**Pull request by jasonish**
Master ticket: https://redmine.openinfosecfoundation.org/issues/5145
5.0.x backport ticket: https://redmine.openinfosecfoundation.org/issues/5150

Reference PR: https://github.com/OISF/suricata/pull/7049

@victorjulien Are the validations enough to fix this issue with respect to 5.0.x, are are there partial fixes required as well?

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk | | |
| .flow.memuse | 569938176 | 725499720 | 78.56% | 

Pipeline 6571

**Comment by victorjulien** [comment]
Will need some variant of https://github.com/OISF/suricata/commit/d85b77cad064bd88c921b2f3d520fe526ad8ff82 and https://github.com/OISF/suricata/commit/4418fc1b02f47533439fe00789d9c850a24271b2 as well. Keep in mind that in `master` the nom parser now takes care of the padding bytes, where the parser in this PR still includes those in the `file_data` as a result of the call to `rest`.

**Comment by victorjulien** [comment]
These changes look correct and test OK in my private NFS tests as well. I can already take them in, or wait for a more complete PR.

**Comment by jasonish** [comment]
> These changes look correct and test OK in my private NFS tests as well. I can already take them in, or wait for a more complete PR.

I'd wait for a more complete PR.  Will look at these are 2 real soon now.

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/7151.

**Pull request closed without merging**
