### PR TITLE
Revert "ci: do not use ppa for cocci"

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- try to fix Cocci segfault

### CODE REVIEW

**Comment by victorjulien** [comment]
Didn't work :(

**Comment by catenacyber** [comment]
I still intend to work on this draft ;-)

**Comment by catenacyber** [comment]
#9200 may fix this

**Comment by catenacyber** [comment]
Continues in #9200

**Pull request closed without merging**
