### PR TITLE
Tcp protodetect bail 4171 v8

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4171

Describe changes:
- tracks the actual stored data, at minimal overhead, in the stream buffer.

Replaces #6189 by increasing `STREAMTCP_DEFAULT_MEMCAP` to match the default `stream.memcap` in suricata.yaml.in (from 32 to 64 Mb)

suricata-verify-pr: 488
cf OISF/suricata-verify#488

### CODE REVIEW

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.spare | 6630013 | 5890991 | 89.0% |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by suricata-qa** [comment]
WARNING:\r\n| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.spare | 6630013 | 5890991 | 89.0% |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by victorjulien** [comment]
Merged in #6248, thanks.

**Pull request closed without merging**
