### PR TITLE
smtp: check if there is a transaction to close

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4948

Describe changes:
- smtp: check if there is a transaction to close (for starttls)

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 6397

**Comment by catenacyber** [comment]
> Do we have an s-v test as mentioned on the issue for this? The change looks fine on the first sight.

There is none for the moment.
I confess I rely on oss-fuzz for regressions testing on the issues it finds
I could craft one S-V test if needed out of the oss-fuzz reproducer

**Comment by victorjulien** [comment]
> > Do we have an s-v test as mentioned on the issue for this? The change looks fine on the first sight.
> 
> There is none for the moment. I confess I rely on oss-fuzz for regressions testing on the issues it finds I could craft one S-V test if needed out of the oss-fuzz reproducer

Can you craft such a test?

**Comment by catenacyber** [comment]
> Can you craft such a test?

Done in https://github.com/OISF/suricata-verify/pull/784

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #7172, thanks!

**Pull request closed without merging**
