### PR TITLE
pfring: ips mode

### PR DESCRIPTION
**Pull request by glongo**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1726

Describe changes:
This patchset permits to set-up pfring in IPS mode.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR glongo: https://buildbot.openinfosecfoundation.org/builders/glongo/builds/216
- PR glongo-pcap: https://buildbot.openinfosecfoundation.org/builders/glongo-pcap/builds/80

### CODE REVIEW

**Comment by victorjulien** [comment]
When we tested an earlier version of this some years ago, we saw very poor performance. What numbers are you seeing now?

**Comment by glongo** [comment]
I've made some tests with iperf, and this below is the result:

```
iperf -c 192.168.1.1
------------------------------------------------------------
Client connecting to 192.168.1.1, TCP port 5001
TCP window size:  129 KByte (default)
------------------------------------------------------------
[  4] local 192.168.1.2 port 50617 connected with 192.168.1.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-20.0 sec  2.18 GBytes   938 Mbits/sec
```

**Comment by victorjulien** [comment]
What does your test look like? What is your setup?

How does this work wrt vlan headers? In AF_PACKET we had to manually put it back into the packets that were sent out.

**Comment by glongo** [comment]
I set-up suricata as gateway, and sent traffic from one side to the other with iperf and tcpreplay.

Regarding vlan headers, pf_ring kernel module itself take care of putting them before forwarding the packets when standard driver are used.

With other drivers instead, such as ZC, vlan stripping must be disabled because in this case the kernel is bypassed.

**Comment by Onotoko** [comment]
Hello,

I got the error: `<Warning> - [ERRCODE: SC_ERR_SOCKET(200)] - Sending packet failed [xx->xx]: No buffer space available` 

When I are trying use IPS mode

Could you help me figure it out this error?

Thank you!

**Comment by glongo** [comment]
@Onotoko could you try to print the value returned by `pfring_send`?

**Comment by Onotoko** [comment]
@glongo,

The value returned by `pfring_send` is `-1`,
And I see if I sent `517110 packets`  (with line rate is `5.5 Gb/s`), suricata logged `1745` line of warning as above.

Could I setup anything for peer interface?

Thank you in advance!

**Comment by cardigliano** [comment]
@Onotoko, is it sending any packet or returning -1 for *all* packets? What is the adapter model? What is the interface name in the configuration file?

**Comment by Onotoko** [comment]
@cardigliano 

```
is it sending any packet or returning -1 for all packets? 
```

It isn't. When I send traffic with line rate 5.5 Gb/s, it returned -1 about ~ 0.1 %

```
What is the adapter model? 
```

I used 3 servers, 
- Server A for traffic generator 
- Server B for suricata (IPS mode, 2 interface NIC (10 Gb))
- Server B will receive traffic from suricata

```
What is the interface name in the configuration file?
```
[suricata.txt](https://github.com/OISF/suricata/files/3822356/suricata.txt)


Thank you!

**Comment by cardigliano** [comment]
Just to make sure, does this mean it works sending 99.9% of the traffic and failing for 0.1%?

**Comment by glongo** [comment]
Could you attach stats.log file?

**Comment by Onotoko** [comment]
@cardigliano,

```
Just to make sure, does this mean it works sending 99.9% of the traffic and failing for 0.1%?
```
Yes

@glongo 

```
Could you attach stats.log file?
```

Sure.
[stats.txt](https://github.com/OISF/suricata/files/3829211/stats.txt)

**Comment by cardigliano** [comment]
It seems it's just a matter of TX speed, the interface cannot keep up with the transmission rate. I suggest you to run some test with pfsend -i <interface> (you can use -l to simulate the averaga packet size, or replay a pcap with -f) to check what is the max speed your interface is able to handle.

**Comment by Onotoko** [comment]
@cardigliano,

Here is the result

```
TX rate: [current 562'526.31 pps/6.86 Gbps][average 562'526.31 pps/6.86 Gbps][total 562'528.00 pkts]
TX rate: [current 623'745.30 pps/7.60 Gbps][average 593'136.46 pps/7.23 Gbps][total 1'186'302.00 pkts]
TX rate: [current 625'595.23 pps/7.63 Gbps][average 603'956.03 pps/7.36 Gbps][total 1'811'911.00 pkts]
TX rate: [current 626'115.10 pps/7.63 Gbps][average 609'495.78 pps/7.43 Gbps][total 2'438'038.00 pkts]
TX rate: [current 626'356.72 pps/7.64 Gbps][average 612'867.96 pps/7.47 Gbps][total 3'064'406.00 pkts]
TX rate: [current 624'802.25 pps/7.62 Gbps][average 614'857.02 pps/7.50 Gbps][total 3'689'227.00 pkts]
TX rate: [current 625'425.49 pps/7.63 Gbps][average 616'366.80 pps/7.51 Gbps][total 4'314'665.00 pkts]
TX rate: [current 625'408.11 pps/7.62 Gbps][average 617'496.96 pps/7.53 Gbps][total 4'940'085.00 pkts]
TX rate: [current 625'562.11 pps/7.63 Gbps][average 618'393.08 pps/7.54 Gbps][total 5'565'659.00 pkts]
TX rate: [current 624'838.13 pps/7.62 Gbps][average 619'037.60 pps/7.55 Gbps][total 6'190'519.00 pkts]
TX rate: [current 624'854.12 pps/7.62 Gbps][average 619'566.37 pps/7.55 Gbps][total 6'815'385.00 pkts]
```

It seems the TX speed cannot get full 10Gbps

**Comment by cardigliano** [comment]
@Onotoko it seems you are using standard drivers, not ZC, right?

**Comment by Onotoko** [comment]
@glongo,
Yes I just have used standard driver, because I cannot config zc on suricata.yaml file for pfring section which can help suricata can understand

**Comment by glongo** [comment]
@Onotoko btw, I've just pushed a new version of this branch, you can find it here: 
https://github.com/glongo/suricata/tree/dev-pfring-ips-v3

I don't think you will have better performance, but at least it's on top of master.

**Comment by Onotoko** [comment]
@glongo,

Thank you for your support

**Comment by victorjulien** [comment]
We are working on plugin support and see the future of our PF_RING support as an (externally developed and maintained) plugin. See #5150 for the current iteration. Until that time I don't want to add new functionality like this to it.

**Comment by glongo** [comment]
@victorjulien, are you interested in this patchset?

**Pull request closed without merging**
