### PR TITLE
ftp: incorrect direction of expectation for STOR cmd in active mode

### PR DESCRIPTION
**Pull request by vanlink**
Bug #3542

For ftp active mode and STOR command, the expectation is created in wrong direction.
And file extraction fails.

### CODE REVIEW

**Comment by jlucovsky** [comment]
LGTM.

**Comment by victorjulien** [comment]
Not sure if I asked this before, but can you update your git id to your name? E.g. for me the id is `Victor Julien <victor@inliniac.net>`

**Comment by vanlink** [comment]
> Not sure if I asked this before, but can you update your git id to your name? E.g. for me the id is `Victor Julien <victor@inliniac.net>`

Is this right now？

**Comment by catenacyber** [comment]
Hi @vanlink 
Thanks for this PR
Do you have a pcap to test this ? Or event better a suricata-verify test ? cf https://github.com/OISF/suricata-verify

**Comment by victorjulien** [comment]
> > Not sure if I asked this before, but can you update your git id to your name? E.g. for me the id is `Victor Julien <victor@inliniac.net>`
> 
> Is this right now？

I don't see a difference yet. Did you push your updated commits?

**Comment by vanlink** [comment]
> Hi @vanlink
> Thanks for this PR
> Do you have a pcap to test this ? Or event better a suricata-verify test ? cf https://github.com/OISF/suricata-verify

Yes, please download below:
https://github.com/vanlink/pcaps/blob/master/ftp/ftp-port-stor.pcapng

**Comment by catenacyber** [comment]
Thank you.
@jlucovsky are you the FTP expert ? Or should I take this one ?

**Comment by jlucovsky** [comment]
> Thank you.
> @jlucovsky are you the FTP expert ? Or should I take this one ?

I had given a LGTM earlier.

**Comment by victorjulien** [comment]
I see two commits where there should be just one. Can you squash them and also make sure the formatting matches these guidelines? https://github.com/OISF/suricata/blob/master/doc/devguide/code-submission-process.rst#commits

**Comment by victorjulien** [comment]
@vanlink this is what I meant:
Screenshot from 2020-07-14 12-41-13

Is that OK with you?

**Comment by victorjulien** [comment]
Merged in #5216, thanks!

**Pull request closed without merging**
