### PR TITLE
Http range file v15

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1576

Describe changes:
- Uses a generic container (a thread-safe hash table whose key is the url/filename) to store file parts with HTTP Range header
- handles reassembly of these parts, while enforcing a global memcap

suricata-verify-pr: 443

Modifies #6226 with  fixing introduced null dereference

TODO: commit squashing 
Renaming to more specific ?
More testing of concurrency ? Is there a generic framework for this ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .detect.alert | 3109382 | 3962505 | 78.0% |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .detect.alert | 3109382 | 3962505 | 78.0% |

**Comment by suricata-qa** [comment]
ERROR: SEGMENTATION FAULT in tlpr1_autofp_suri QA test

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6266

**Pull request closed without merging**
