### PR TITLE
Smtp rfc2231 4386 v7 backport6

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4386

Describe changes:
- Backport of #6670 (only first 2 commits, last commit is more code style)

Clean cherry-picks except `#include "rust.h"` was needed in addition

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8445

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8445

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 10602

**Comment by victorjulien** [comment]
Merged in #8180, thanks!

**Pull request closed without merging**
