### PR TITLE
events: reset logged event

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
I should create one once this bug is acknowledged

Describe changes:
- events: reset logged event

I guess this needs a S-V test also

### CODE REVIEW

**Comment by victorjulien** [comment]
Not sure I understand the bug. Can you do a SV test to show it?

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on tlpw1_files_sha256.

ERROR: QA failed on tlpr1_alerts_cmp.
  

Pipeline 7617

**Comment by catenacyber** [comment]
> Not sure I understand the bug. Can you do a SV test to show it?

I got this with my pcap for Suricon ;-)

I try to reproduce with another from scratch pcap
It seems it depends on the packet recycling stuff
When reading a pcap, which packets get `PACKET_RECYCLE` from another ?

**Comment by catenacyber** [comment]
To try to phrase the bug :
When a packet that had an event logged gets recycled, if it gets a new event, this new event does not get logged, because only  events->cnt was reset and not events->event_last_logged and `event_last_logged` gets used in output-json-anomaly.c by `AnomalyAppLayerDecoderEventJson`

**Comment by victorjulien** [comment]
That sounds like a bug indeed. Essentially in the packet flow we take a packet from the pool, use it, then return it. Before returning we clean it (PACKET_RECYCLE). Sounds like its not fully cleaned.

Perhaps we need a set of debug validation checks to see if a packet we get from the pool is clean in the ways we expect.

**Comment by suricata-qa** [comment]
ERROR:
 ERROR: Invalid Signature config error in tlpw1_cfg QA test

ERROR: QA failed on tlpw1_cfg.
  

Pipeline 7668

**Comment by catenacyber** [comment]
> Perhaps we need a set of debug validation checks to see if a packet we get from the pool is clean in the ways we expect.

Well, if we know what we expect, we can reset it properly in the first place, no ?

**Pull request closed without merging**
