### PR TITLE
Log rfb skipped tx v2

### PR DESCRIPTION
**Pull request by satta**
Previous PR: #9106 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#5912](https://redmine.openinfosecfoundation.org/issues/5912)

Describe changes to previous PR:
- Reference S-V test PR as requested.
- Make sure that we also set parsed values in the event even if we skip parsing at some point.

https://github.com/OISF/suricata-verify/pull/1279

```
SV_BRANCH=pr/1279
```

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
CI : green
Code : ok, I wonder if a wrapper around these 5 lines would be nicer
Commits segmentation : ok
Commit messages : ok, but I would have added the ticket number as you promised ;-p
Git ID set : looks fine for me
CLA : ok
Doc update : not needed
Redmine ticket : ok
Rustfmt : ok
Tests : ok, test with an unknown security type is always welcome
Dependencies added: none
Divisions : none

**Review by victorjulien — APPROVED** [review]

**Comment by satta** [comment]
> Commit messages : ok, but I would have added the ticket number as you promised ;-p 

Well, I omitted it because an earlier commit fixed the Redmine issue, this one just addressed another point. Or do you mean the GitHub issue number?

**Comment by catenacyber** [comment]
> > Commit messages : ok, but I would have added the ticket number as you promised ;-p
> 
> Well, I omitted it because an earlier commit fixed the Redmine issue, this one just addressed another point. Or do you mean the GitHub issue number?

As this PR completes the previous commit, I would have noted the redmine issue, so that both commits get back ported if needed

**Comment by victorjulien** [comment]
Merged in #9143, thanks!

**Pull request closed without merging**
