### PR TITLE
Datajson v2.0

### PR DESCRIPTION
**Pull request by regit**
Update of #12102 

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7372

Describe changes:
- Address comments of #12102
- Rebase the code

SV_REPO=https://github.com/OISF/suricata-verify/pull/2123

### CODE REVIEW

**Comment by jasonish** [comment]
I still have to play with this a little more, and datasets in general, but a few quick observations, not all related to this PR, but make things confusing.

If my IP dataset input file is simply:
```
10.16.1.11
```
then `datajson` crashes.

-----

- A dataset input line like `10.16.1.10,asdf` is parsed as `datarep` even if `dataset` is used. Errors out because `asdf` is not a valid reputation value, but it seems like we already have some overloading going on.
- A dataset input like like `10.16.1.10,["asdf"]` parses the JSON even if `dataset` is used and not `datajson`
- Scalars like `1`, and `"one"` are valid JSON but not accepted.

-----

Should `datarepjson` be a thing for completeness?

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 138 | 145 | 105.07% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 624 | 687 | 110.1% |
| .http.byterange.memuse | 99602115 | 104192025 | 104.61% | 

Pipeline 23600

**Comment by regit** [comment]
> I still have to play with this a little more, and datasets in general, but a few quick observations, not all related to this PR, but make things confusing.
> 
> If my IP dataset input file is simply:
> 
> ```
> 10.16.1.11
> ```
> 
> then `datajson` crashes.
> 
> * A dataset input line like `10.16.1.10,asdf` is parsed as `datarep` even if `dataset` is used. Errors out because `asdf` is not a valid reputation value, but it seems like we already have some overloading going on.
> * A dataset input like like `10.16.1.10,["asdf"]` parses the JSON even if `dataset` is used and not `datajson`
> * Scalars like `1`, and `"one"` are valid JSON but not accepted.

OK, I need to fix the parsing for here. :/

> 
> Should `datarepjson` be a thing for completeness?

I more in favor of building the set from the CTI tool at the correct cut before exporting it to Suricata. I think it corresponds to most of the usage I've seen. But potentially we could open the issue and try to see if someone is interested by it.

**Comment by regit** [comment]
Closing in favor of #12289.

**Pull request closed without merging**
