### PR TITLE
pfring: convert to plugin - v2

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/11462

Changes from last PR:
- keep the pfring command line arguments and setup the plugin

If build with pfring support, the following "just works":

```
suricata --pfring=enp10s0
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW1_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 642 | 677 | 105.45% | 

Pipeline 21469

**Comment by victorjulien** [comment]
This needs ticket reference https://redmine.openinfosecfoundation.org/issues/7162

Also, would expect the upgrade docs to cover this.

**Comment by victorjulien** [comment]
Passed my QA. Ran this PR with SV master. Local pipeline 4984, run 525.

**Comment by jasonish** [comment]
https://github.com/OISF/suricata/pull/11483

**Pull request closed without merging**
