### PR TITLE
updating unittests in src/app-layer-htp.c to new FAIL/PASS API/v1

### PR DESCRIPTION
**Pull request by Nancyenos**
Ticket: #6935

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [ ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [ ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [ ] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [ ] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
-
-updated HTPParserTest01a in  src/app-layer-htp.c to new FAIL/PASS API
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Congrats on your first contribution, @Nancyenos ! :)
The changes are looking ok from a brief overview, however, we need to rework a few things:
- Rebase your branch on the latest master
- Cover all the tests in this file
- Commit message should be reworded to something like: `applayer/htp: convert to new FAIL/PASS API`

Nice first try! ⭐

**Comment by Nancyenos** [comment]
Thank you @inashivb .Working on it!

**Comment by victorjulien** [comment]
Please open a new branch and PR for implementing the requested changes.

**Comment by inashivb** [comment]
Replaced w https://github.com/OISF/suricata/pull/11950

**Pull request closed without merging**
