### PR TITLE
dns: add dns.rrtype keyword v3

### PR DESCRIPTION
**Pull request by hadiqaalamdar**
Feature #6666

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6666) ticket: https://redmine.openinfosecfoundation.org/issues/6666

Previous PR: https://github.com/OISF/suricata/pull/10289

Describe changes:
- made suggested changes from last PR
- SV for negated value is failing:
`===> dns-rrtype: Sub test #3: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'alert.signature_id': 3}} 
`
- successfully ran the following tests:
- from rust dir: make check
- from rust dir: cargo test
- from rust dir: cargo clippy --all-features
- from rust dir: rustfmt src/dns/*
- from suricata dir: ./scripts/clang-format.sh check-branch
- from suricata dir: ./scripts/clang-format.sh branch
- from suricata dir running ./src/suricata -u showed that one unit test had failed. 
- from suricata dir running ./src/suricata -u -U dns showed 7 tests passed.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1628

### CODE REVIEW

**Comment by hadiqaalamdar** [comment]
Apologies for the messy commit history but I'd appreciate feedback on the current PR so I can make the new edits and fix the commit history in the next PR.

**Comment by jufajardini** [comment]
> Apologies for the messy commit history but I'd appreciate feedback on the current PR so I can make the new edits and fix the commit history in the next PR.

Ok! From a first glance, though, I coudln't  see differences from the commits. Is there a reason why you don't want to squash them all together?

**Review by jufajardini — CHANGES_REQUESTED** [review]
Apart from the commit history, this looks good to me, thanks! :) 👏🏽 

I think that the SV test failure is related to the test itself, Shivani's comment on it looks like a good starting point to figure out how to fix it. 
Once the sv tests are passing, we'll need a new Suri PR with  neat commit history, to run again passing SV tests, so we have green CI checks before merge :)

**Comment by hadiqaalamdar** [comment]
New PR: https://github.com/OISF/suricata/pull/10314

**Pull request closed without merging**
