### PR TITLE
detect: log app-layer metadata in alert with single tx

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7199

May also solve https://redmine.openinfosecfoundation.org/issues/7406 and https://redmine.openinfosecfoundation.org/issues/7350

Describe changes:
- detect: log app-layer metadata in alert with single tx

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2141

Is this the right way to solve most of the cases as I remember discussing with someone ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 23563

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 23564

**Comment by catenacyber** [comment]
Why is QA failing ? I do not see a stack trace...

**Comment by catenacyber** [comment]
Next in https://github.com/OISF/suricata/pull/12158

**Pull request closed without merging**
