### PR TITLE
Output alert applayer v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None, preliminary work for https://redmine.openinfosecfoundation.org/issues/5053 and app-layer plugins
Continuation of https://github.com/OISF/suricata/pull/8772

Describe changes:
- Fix setup-app-layer script so that it adds app-layer metadata to alerts
- Adds ftp metadata to alerts
- Adds tftp metadata to alerts

```
SV_BRANCH=pr/1196
```

### CODE REVIEW

**Comment by catenacyber** [comment]
Questions about this draft :
- Should we unify logging functions so that they use state ? and configuration flags ?
Looks like some protocols could get rid of state in their logging function : snmp, rfb, krb5
- What about cases where we want to log multiple objects ? (such as `smtp` and `email`)

TODOs : cf output.c

There are more protocols which currently miss this (beyond template, ftp and tftp being fixed here) : pgsql, dcerpc, dhcp, krb5

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 13735

**Comment by catenacyber** [comment]
> There are more protocols which currently miss this (beyond template, ftp and tftp being fixed here) : pgsql, dcerpc, dhcp, krb5

I guess tickets should be created for these (including ftp and tftp)

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 13737

**Comment by catenacyber** [comment]
@jasonish what do you think about the Check Rust failure ?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113274 | 144861 | 127.89% | 

Pipeline 13738

**Comment by catenacyber** [comment]
Also, one next step is to have `JsonGenericLogger` to replace all `JsonBitTorrentDHTLogger` (and other), and get rid of `output-json-bittorrent-dht.c`

Only difficulty there is to know if we have TCP or UDP or both for OutputGenericLogInitSub

**Comment by jasonish** [comment]
> @jasonish what do you think about the Check Rust failure ?

Looks like GitHub changed the format the code is checked out, in such a way we can no longer use git tools like `git diff`.

**Comment by catenacyber** [comment]
> Looks like GitHub changed the format the code is checked out, in such a way we can no longer use git tools like `git diff`.

Ok, but I also do not get anything locally running `cargo clippy --all-features --fix --allow-no-vcs`

And this PR is only removing some lines of rust code...

**Comment by jasonish** [comment]
Fix: https://github.com/OISF/suricata/pull/8866

**Comment by jasonish** [comment]
> * What about cases where we want to log multiple objects ? (such as `smtp` and `email`)

By this do you mean that there is not a 1:1 relation between protocol and name and objects logged?

**Comment by catenacyber** [comment]
> By this do you mean that there is not a 1:1 relation between protocol and name and objects logged?

Yes there is.

I mean to ask : should these cases be handled in the generic fashion proposed in this PR ? Or just have some separate logic..

**Comment by jasonish** [comment]
> I mean to ask : should these cases be handled in the generic fashion proposed in this PR ? Or just have some separate logic..

I think some separate logic may make the initial versions of this PR easier to reason about?  We're shooting for post 7.0 stuff here right?

**Comment by catenacyber** [comment]
> We're shooting for post 7.0 stuff here right?

Not necessarily : this is code simplification, a fix for the script to setup an app layer, and it is leading to adding missing features (adding ftp metadata to alerts)
Do not you think it can be merged already ? (after some cleanups in this PR)

**Comment by catenacyber** [comment]
Need to rebase after https://github.com/OISF/suricata/pull/8867 to get CI green

**Comment by catenacyber** [comment]
Replaced by #8872

**Comment by jasonish** [comment]
> Do not you think it can be merged already ? (after some cleanups in this PR)

Perhaps, I wasn't looking at it in that frame of mind as the issue is targetted for 8.0.

**Pull request closed without merging**
