### PR TITLE
doc: updated gulp/npm notes

### PR DESCRIPTION
**Pull request by jmtaylor90**
Signed-off-by: jason taylor <jtfas90@gmail.com>

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ x ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ x ] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ x ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Update documentation around the development server used to test rst file updates
-
-

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
@jasonish any thoughts on this PR and my comment?

**Comment by jasonish** [comment]
It looks like I forgot to remove this bit of the README when I removed the gulp stuff. I really only found it useful during the phase of migrating the wiki docs. If others still find this useful, then we should probably include the actual config rather than just an example in the README.

**Comment by jmtaylor90** [comment]
@victorjulien mentioned he uses make pdf when QA'ing changes when we were discussing it in IRC the other day. I was just sort of fumbling my way through a workflow for looking at how to update userguide docs and was going through the README and figured I would submit what I used.

If there's more efficient ways (e.g. make pdf) I can update the README with that information and resubmit.

**Comment by jmtaylor90** [comment]
Closing in favor of #3524

**Pull request closed without merging**
