### PR TITLE
Next/20230129/v2

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
- #8484 
- #8483

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_single_stats_chk | | |
| .tcp.ssn_from_cache | 264554 | 339191 | 128.21% |
| .tcp.ssn_from_pool | 628437 | 553800 | 88.12% |
| | SURI_TLPW2_autofp_stats_chk | | |
| .tcp.ssn_from_cache | 298547 | 375117 | 125.65% |
| .tcp.ssn_from_pool | 594444 | 517874 | 87.12% |
| | SURI_TLPW1_stats_chk | | |
| .tcp.ssn_from_cache | 63596 | 78944 | 124.13% |
| .tcp.ssn_from_pool | 139220 | 123872 | 88.98% |
| .tcp.rst | 128116 | 113558 | 88.64% |
| .app_layer.error.dns_udp.parser | 1276 | 0 | - |
| .ftp.memuse | 862 | 348 | 40.37% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 580947328 | 536208176 | 92.3% |
| .tcp.ssn_from_cache | 3644947 | 6063556 | 166.36% |
| .tcp.ssn_from_pool | 8484810 | 6066173 | 71.49% |
| .tcp.synack | 7538139 | 10185455 | 135.12% |
| .tcp.rst | 5264608 | 6697264 | 127.21% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .app_layer.error.dns_udp.parser | 28003 | 0 | - |
| .http.memuse | 16440 | 2104 | 12.8% |
| .ftp.memuse | 13827 | 11093 | 80.23% |
| | IPS_AFP_stats_chk | | |
| .tcp.segment_from_pool | 17089689 | 15755171 | 92.19% | 

Pipeline 12110

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
@jasonish all my arm/arm64 builders on alpine fail with
```
make[2]: Leaving directory '/builds/inliniac/suricata-ci/suricata/rust'
CARGO_HOME="/root/.cargo"  \
	CARGO_TARGET_DIR="/builds/inliniac/suricata-ci/suricata/rust/target" \
	/usr/bin/cargo test --all --release --features "  "
   Compiling hex v0.4.3
   Compiling test-case v1.1.0
   Compiling suricata-derive v7.0.0-rc1-dev (/builds/inliniac/suricata-ci/suricata/rust/derive)
   Compiling suricata v7.0.0-rc1-dev (/builds/inliniac/suricata-ci/suricata/rust)
error[E0308]: mismatched types
   --> src/ffi/hashing.rs:227:51
    |
227 |             let string = std::ffi::CStr::from_ptr(hex.as_ptr() as *mut i8).to_str().unwrap();
    |                          ------------------------ ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |                          |
    |                          arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*mut i8`
note: associated function defined here
error[E0308]: mismatched types
   --> src/ffi/hashing.rs:247:51
    |
247 |             let string = std::ffi::CStr::from_ptr(hex.as_ptr() as *mut i8).to_str().unwrap();
    |                          ------------------------ ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |                          |
    |                          arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*mut i8`
note: associated function defined here
error[E0308]: mismatched types
  --> src/ffi/strings.rs:56:17
   |
54 |             assert!(copy_to_c_char(
   |                     -------------- arguments to this function are incorrect
55 |                 INPUT.to_string(),
56 |                 buf.as_ptr() as *mut i8,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*mut u8`
              found raw pointer `*mut i8`
note: function defined here
  --> src/ffi/strings.rs:33:15
   |
33 | pub unsafe fn copy_to_c_char(src: String, buf: *mut c_char, size: usize) -> bool {
   |               ^^^^^^^^^^^^^^ -----------  ----------------  -----------
error[E0308]: mismatched types
  --> src/ffi/strings.rs:59:51
   |
59 |             let output = std::ffi::CStr::from_ptr(buf.as_ptr()).to_str().unwrap();
   |                          ------------------------ ^^^^^^^^^^^^ expected `u8`, found `i8`
   |                          |
   |                          arguments to this function are incorrect
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`
note: associated function defined here
error[E0308]: mismatched types
  --> src/ffi/strings.rs:73:17
   |
71 |             assert!(!copy_to_c_char(
   |                      -------------- arguments to this function are incorrect
72 |                 INPUT.to_string(),
73 |                 buf.as_ptr() as *mut i8,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*mut u8`
              found raw pointer `*mut i8`
note: function defined here
  --> src/ffi/strings.rs:33:15
   |
33 | pub unsafe fn copy_to_c_char(src: String, buf: *mut c_char, size: usize) -> bool {
   |               ^^^^^^^^^^^^^^ -----------  ----------------  -----------
For more information about this error, try `rustc --explain E0308`.
error: could not compile `suricata` due to 5 previous errors
make[1]: *** [Makefile:573: check] Error 101
make[1]: Leaving directory '/builds/inliniac/suricata-ci/suricata/rust'
make: *** [Makefile:489: check-recursive] Error 1
```

**Comment by victorjulien** [comment]
Wonder if it related to arm defaulting to unsigned for char.

**Comment by jasonish** [comment]
> Wonder if it related to arm defaulting to unsigned for char.

Yup.  The casts to i8 is in error for calls to `copy_to_c_char`, casting to `c_char` should take care that.  I've made the change here, can push.  But can't test on arm.

**Comment by jasonish** [comment]
https://github.com/OISF/suricata/pull/8488

**Pull request closed without merging**
