### PR TITLE
WIP: Use libhtp-rs v6

### PR DESCRIPTION
**Pull request by cccs-rtmorti**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2696) ticket: 2696

Describe changes:
- Use libhtp-rs.
- Rebased from #8335

Updated with changes requested from v5. Did not tackle the commit separation yet - will wait until all the other changes are in.

libhtp-repo: https://github.com/cccs-rtmorti/libhtp-rs
libhtp-branch: main

### CODE REVIEW

**Comment by catenacyber** [comment]
@cccs-rtmorti would you rebase and submit a new version of this PR ?

**Comment by victorjulien** [comment]
FYI I ran this against our private QA and it has several failures in pcaps that we can't easily share. So we're trying to figure out how to proceed.

**Comment by cccs-rtmorti** [comment]
> @cccs-rtmorti would you rebase and submit a new version of this PR ?

Done in #9031

**Comment by cccs-rtmorti** [comment]
> FYI I ran this against our private QA and it has several failures in pcaps that we can't easily share. So we're trying to figure out how to proceed.

I would be happy to help debug any failures. I don't necessarily need the pcaps, just need to know what the nature of the failures are - header parsing not handling certain cases, etc.

**Comment by cccs-rtmorti** [comment]
Updated in #9031

**Pull request closed without merging**
