### PR TITLE
detect/transform: Case changing transform backport to main-7.0.x 

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #10025 

Add the transforms for changing the case of a buffer. 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6612](https://redmine.openinfosecfoundation.org/issues/6612)

Describe changes:
- Add to_lowercase and to_uppercase transforms

Updates:
- Rebase

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1460
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
This won't be picked up until it points to an open SV PR.

**Review by victorjulien — CHANGES_REQUESTED** [review]
Needs rebase and a link to a open SV PR.

**Comment by jlucovsky** [comment]
> This won't be picked up until it points to an open SV PR.

There's already an existing set of s-v tests that are predicated on `src/detect-transform-casechange.c` existing.

**Comment by jlucovsky** [comment]
> Needs rebase and a link to a open SV PR.

Will rebase and there's already existing s-v test coverage.

**Comment by jlucovsky** [comment]
Continued in #10067

**Pull request closed without merging**
