### PR TITLE
NSM: add TTL flags for netflow event record

### PR DESCRIPTION
**Pull request by macpas**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- add TTL fields for netflow event record
- provide minimum and maximum time-to-live

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you update the PR title to be more meaningful?

**Comment by macpas** [comment]
any news ? Do I need to add something for this PR to go to next step ?
Thanks.

**Comment by victorjulien** [comment]
No, looks good now, thanks! Will do some more QA/testing next week.

**Comment by victorjulien** [comment]
Merged in #3009, thanks all!

**Pull request closed without merging**
