### PR TITLE
Add a definition for the number of actions

### PR DESCRIPTION
**Pull request by stricaud**
Creates a definition to specify the number of actions. This is needed for my Xmas changes.

Until now, the number of actions (4) was hard-coded in multiple places of the code. This change fixes it.

It is now recommended to use the NUMBER_OF_ACTIONS definition anytime one need to use the number of actions.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
Hi @stricaud , thanks for this cleanup. Looking forward to learning about your fancy xmas plans :)

Code looks OK to me, but the commit message needs some love. Please see https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria#Commits

**Comment by stricaud** [comment]
On the item number 6. in the Commit section?

**Comment by norg** [comment]
Yes, you can look into other commit messages related to those files to get a better idea :)

**Comment by stricaud** [comment]
Thanks for the feedback, I was not sure of the subsystem (maybe a link to list all of them to avoid confusion for new commiters?), and looking at the activity on the patched file, it was 8 years ago, when the commit messages did not have this rule ;-) So I took "action", hoping this is the good one. Anyway, here we go, it has been updated.

**Comment by regit** [comment]
@stricaud we try to avoid merge in the git history and it seems we have some in the commits stack of this MR

**Comment by stricaud** [comment]
Opened #3603 to make sure it is all clean, closing this one.

**Pull request closed without merging**
