### PR TITLE
smb: fix wrong endian conversion when parse NTLM Negotiate Flags - V3

### PR DESCRIPTION
**Pull request by b1tg**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket: [5783](https://redmine.openinfosecfoundation.org/issues/5783)

Previous PR: https://github.com/OISF/suricata/pull/8373

Changes from last PR:
- fix commit message
- add comment in test code
- submit a PR with a suricata-verify test to indicate this issue https://github.com/OISF/suricata-verify/pull/1079

Signed-off-by: Lancer Cheng b1tg@protonmail.ch

suricata-verify-pr: 1079

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Thanks for incorporating the changes requested!

Current status:

**CI:** I think that the rustfmt failures that we're seeing might be related to the latest batch of merges to master. I'm betting that rebasing would fix that
**Rustfmt:** was looking good, recent merges to master seem to be triggering errors now for this PR
**Doc update:** would be good to add the version field to https://suricata.readthedocs.io/en/latest/output/eve/eve-json-format.html#ntlmssp-fields
**Commit messages:** ✅  (if we want to make it perfect, replace `ticket: 5783` for `Bug #5783`)

**Code:** seems to fix the issue, but needs a second reviewer 
**Commits segmentation:** ✅ 
**Git ID set:** ✅ 
**CLA:** ✅ 
**Redmine ticket:** ✅ 
**Tests:** Suricata-verify tests look fine 
**Dependencies added:** none, I think

**Comment by catenacyber** [comment]
Looks like the suricata-verify PR was updated to https://github.com/OISF/suricata-verify/pull/1091

**Comment by jufajardini** [comment]
> Thanks for incorporating the changes requested!
> 
> Current status:
> 
> **CI:** I think that the rustfmt failures that we're seeing might be related to the latest batch of merges to master. I'm betting that rebasing would fix that **Rustfmt:** was looking good, recent merges to master seem to be triggering errors now for this PR **Doc update:** would be good to add the version field to https://suricata.readthedocs.io/en/latest/output/eve/eve-json-format.html#ntlmssp-fields **Commit messages:** white_check_mark (if we want to make it perfect, replace `ticket: 5783` for `Bug #5783`)
> 
> **Code:** seems to fix the issue, but needs a second reviewer **Commits segmentation:** white_check_mark **Git ID set:** white_check_mark **CLA:** white_check_mark **Redmine ticket:** white_check_mark **Tests:** Suricata-verify tests look fine **Dependencies added:** none, I think

Hello @b1tg, thanks for incorporating our feedback to the SV PR with the tests that accompany this contribution. Could you please address the documentation and commit changes mentioned in the checklist? Once those are ready, I'll ask for some other team member to double-check the code changes, since to me those are good to go.

**Comment by victorjulien** [comment]
replaced by #8511

**Pull request closed without merging**
