### PR TITLE
New StringParse* functions

### PR DESCRIPTION
**Pull request by inashivb**
Add a new set of StringParse* functions and use them for strict parsing in all parser, configuration and setup functions.
Related to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3053

### CODE REVIEW

**Comment by victorjulien** [comment]
In commit `util: Add StringParse* functions`, can you explain what the behaviour of the new function is that why it is important?

**Comment by jlucovsky** [comment]
The new function sig is `StringParseUint32(&configval, 10, strlen(conf_val),  conf_val)`

Would it make sense to avoid the extra parameter (`strlen(x)`) and have `StringParseX` compute that?

**Comment by victorjulien** [comment]
I think a 

> The new function sig is `StringParseUint32(&configval, 10, strlen(conf_val), conf_val)`
> 
> Would it make sense to avoid the extra parameter (`strlen(x)`) and have `StringParseX` compute that?

I supposed that depends on whether the current functionality of being able to parse only part of a string is considered useful. Is it being used anywhere in the current code?

**Comment by inashivb** [comment]
> I think a
> 
> > The new function sig is `StringParseUint32(&configval, 10, strlen(conf_val), conf_val)`
> > Would it make sense to avoid the extra parameter (`strlen(x)`) and have `StringParseX` compute that?
> 
> I supposed that depends on whether the current functionality of being able to parse only part of a string is considered useful. Is it being used anywhere in the current code?

There are parts of code like `if (StringParseUint32(&data->multiplier, 10, strlen(args[i]) - 11,..` so it does not always seem to take strlen of the string being passed to it. Leaving the function signature as-is.

**Comment by inashivb** [comment]
Replaced with # #4739

**Pull request closed without merging**
