### PR TITLE
Next/20220901/v6

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
- #7804 
- #7798 (part)
- #7796 
- #7756 
- #7707
- #7555

suricata-verify-pr: 923

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .tcp.rst | 103033 | 126175 | 122.46% |
| .app_layer.error.tls.parser | 1025 | 157 | 15.32% |
| | tlpr1_stats_chk | | |
| .app_layer.error.tls.parser | 22937 | 1499 | 6.54% |
| | ips_afp_stats_chk | | |
| .capture.kernel_drops | 1 | 803900 | 80390000.0% |
| .flow.end.state.new | 10800 | 14142 | 130.94% |
| .flow.end.tcp_state.syn_sent | 1 | 1369 | 136900.0% |
| .flow.end.tcp_state.syn_recv | 1 | 312 | 31200.0% |
| .flow.end.tcp_state.fin_wait1 | 1 | 246 | 24600.0% |
| .flow.end.tcp_state.fin_wait2 | 1 | 225 | 22500.0% |
| .flow.end.tcp_state.time_wait | 1 | 168 | 16800.0% |
| .flow.end.tcp_state.last_ack | 1 | 219 | 21900.0% |
| .flow.end.tcp_state.close_wait | 1 | 483 | 48300.0% |
| .flow.end.tcp_liberal | 108000 | 124517 | 115.29% |
| .tcp.reassembly_gap | 108000 | 164748 | 152.54% |
| .tcp.overlap | 1 | 41 | 4100.0% |
| .app_layer.error.http.parser | 1 | 163 | 16300.0% |
| .app_layer.error.ftp.gap | 1 | 105 | 10500.0% |
| .app_layer.error.smtp.gap | 1 | 634 | 63400.0% |
| .app_layer.error.tls.gap | 1 | 10934 | 1093400.0% |
| .app_layer.error.dcerpc_tcp.parser | 1 | 451 | 45100.0% |
| .ftp.memuse | 1 | 1160 | 116000.0% | 

Pipeline 8940

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | generic_stats_chk | | |
| .uptime | 731 | 173 | 23.67% |
| .capture.kernel_packets | 589954799 | 81477133 | 13.81% |
| .decoder.pkts | 589954799 | 81435290 | 13.8% |
| .decoder.bytes | 509200866792 | 70123659014 | 13.77% |
| .decoder.ipv4 | 589954799 | 81435290 | 13.8% |
| .decoder.ethernet | 589954799 | 81435290 | 13.8% |
| .decoder.tcp | 408239555 | 58386541 | 14.3% |
| .decoder.udp | 181715244 | 23048749 | 12.68% |
| .flow.total | 3302615 | 480577 | 14.55% |
| .flow.tcp | 2827913 | 411470 | 14.55% |
| .flow.udp | 474702 | 69107 | 14.56% |
| .flow.end.state.new | 6272 | 1362 | 21.72% |
| .flow.end.state.established | 522426 | 83584 | 16.0% |
| .flow.end.state.closed | 2773917 | 395631 | 14.26% |
| .flow.end.tcp_state.established | 53996 | 15333 | 28.4% |
| .flow.end.tcp_state.closed | 2773917 | 395585 | 14.26% |
| .flow.end.tcp_liberal | 80952 | 15692 | 19.38% |
| .flow.spare | 2202303 | 1967025 | 89.32% |
| .flow.memuse | 760476288 | 584361728 | 76.84% |
| .tcp.sessions | 2827913 | 411342 | 14.55% |
| .tcp.syn | 4690535 | 681756 | 14.53% |
| .tcp.synack | 2827913 | 411183 | 14.54% |
| .tcp.rst | 1931034 | 274591 | 14.22% |
| .tcp.reassembly_gap | 80952 | 24232 | 29.93% |
| .detect.alert | 108732 | 14898 | 13.7% |
| .detect.alerts_suppressed | 1398578 | 201608 | 14.42% |
| .app_layer.flow.http | 544167 | 78374 | 14.4% |
| .app_layer.flow.ftp | 18444 | 2693 | 14.6% |
| .app_layer.flow.smtp | 18460 | 2682 | 14.53% |
| .app_layer.flow.tls | 1862622 | 270191 | 14.51% |
| .app_layer.flow.smb | 176775 | 26577 | 15.03% |
| .app_layer.flow.dcerpc_tcp | 16108 | 2313 | 14.36% |
| .app_layer.flow.failed_tcp | 137472 | 19945 | 14.51% |
| .app_layer.flow.dns_udp | 324446 | 47263 | 14.57% |
| .app_layer.flow.failed_udp | 150256 | 21844 | 14.54% |
| .app_layer.tx.http | 544167 | 78462 | 14.42% |
| .app_layer.tx.ftp | 73776 | 10768 | 14.6% |
| .app_layer.tx.smtp | 36920 | 5325 | 14.42% |
| .app_layer.tx.smb | 1452962 | 220133 | 15.15% |
| .app_layer.tx.dcerpc_tcp | 273836 | 39128 | 14.29% |
| .app_layer.tx.dns_udp | 648892 | 94509 | 14.56% |
| .app_layer.error.ftp.parser | 18444 | 2689 | 14.58% |
| .app_layer.error.tls.gap | 53852 | 10859 | 20.16% | 

Pipeline 8971

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | generic_stats_chk | | |
| .uptime | 731 | 173 | 23.67% |
| .capture.kernel_packets | 589954799 | 81477133 | 13.81% |
| .decoder.pkts | 589954799 | 81435290 | 13.8% |
| .decoder.bytes | 509200866792 | 70123659014 | 13.77% |
| .decoder.ipv4 | 589954799 | 81435290 | 13.8% |
| .decoder.ethernet | 589954799 | 81435290 | 13.8% |
| .decoder.tcp | 408239555 | 58386541 | 14.3% |
| .decoder.udp | 181715244 | 23048749 | 12.68% |
| .flow.total | 3302615 | 480577 | 14.55% |
| .flow.tcp | 2827913 | 411470 | 14.55% |
| .flow.udp | 474702 | 69107 | 14.56% |
| .flow.end.state.new | 6272 | 1362 | 21.72% |
| .flow.end.state.established | 522426 | 83584 | 16.0% |
| .flow.end.state.closed | 2773917 | 395631 | 14.26% |
| .flow.end.tcp_state.established | 53996 | 15333 | 28.4% |
| .flow.end.tcp_state.closed | 2773917 | 395585 | 14.26% |
| .flow.end.tcp_liberal | 80952 | 15692 | 19.38% |
| .flow.spare | 2202303 | 1967025 | 89.32% |
| .flow.memuse | 760476288 | 584361728 | 76.84% |
| .tcp.sessions | 2827913 | 411342 | 14.55% |
| .tcp.syn | 4690535 | 681756 | 14.53% |
| .tcp.synack | 2827913 | 411183 | 14.54% |
| .tcp.rst | 1931034 | 274591 | 14.22% |
| .tcp.reassembly_gap | 80952 | 24232 | 29.93% |
| .detect.alert | 108732 | 14898 | 13.7% |
| .detect.alerts_suppressed | 1398578 | 201608 | 14.42% |
| .app_layer.flow.http | 544167 | 78374 | 14.4% |
| .app_layer.flow.ftp | 18444 | 2693 | 14.6% |
| .app_layer.flow.smtp | 18460 | 2682 | 14.53% |
| .app_layer.flow.tls | 1862622 | 270191 | 14.51% |
| .app_layer.flow.smb | 176775 | 26577 | 15.03% |
| .app_layer.flow.dcerpc_tcp | 16108 | 2313 | 14.36% |
| .app_layer.flow.failed_tcp | 137472 | 19945 | 14.51% |
| .app_layer.flow.dns_udp | 324446 | 47263 | 14.57% |
| .app_layer.flow.failed_udp | 150256 | 21844 | 14.54% |
| .app_layer.tx.http | 544167 | 78462 | 14.42% |
| .app_layer.tx.ftp | 73776 | 10768 | 14.6% |
| .app_layer.tx.smtp | 36920 | 5325 | 14.42% |
| .app_layer.tx.smb | 1452962 | 220133 | 15.15% |
| .app_layer.tx.dcerpc_tcp | 273836 | 39128 | 14.29% |
| .app_layer.tx.dns_udp | 648892 | 94509 | 14.56% |
| .app_layer.error.ftp.parser | 18444 | 2689 | 14.58% |
| .app_layer.error.tls.gap | 53852 | 10859 | 20.16% | 

Pipeline 8971

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | generic_stats_chk | | |
| .uptime | 731 | 173 | 23.67% |
| .capture.kernel_packets | 589954799 | 81477133 | 13.81% |
| .capture.kernel_drops | 0 | 41666 | - |
| .decoder.pkts | 589954799 | 81435290 | 13.8% |
| .decoder.bytes | 509200866792 | 70123659014 | 13.77% |
| .decoder.ipv4 | 589954799 | 81435290 | 13.8% |
| .decoder.ethernet | 589954799 | 81435290 | 13.8% |
| .decoder.tcp | 408239555 | 58386541 | 14.3% |
| .decoder.udp | 181715244 | 23048749 | 12.68% |
| .flow.total | 3302615 | 480577 | 14.55% |
| .flow.tcp | 2827913 | 411470 | 14.55% |
| .flow.udp | 474702 | 69107 | 14.56% |
| .flow.end.state.new | 6272 | 1362 | 21.72% |
| .flow.end.state.established | 522426 | 83584 | 16.0% |
| .flow.end.state.closed | 2773917 | 395631 | 14.26% |
| .flow.end.tcp_state.syn_sent | 0 | 242 | - |
| .flow.end.tcp_state.syn_recv | 0 | 45 | - |
| .flow.end.tcp_state.established | 53996 | 15333 | 28.4% |
| .flow.end.tcp_state.fin_wait1 | 0 | 30 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 9 | - |
| .flow.end.tcp_state.time_wait | 0 | 28 | - |
| .flow.end.tcp_state.last_ack | 0 | 18 | - |
| .flow.end.tcp_state.close_wait | 0 | 52 | - |
| .flow.end.tcp_state.closed | 2773917 | 395585 | 14.26% |
| .flow.end.tcp_liberal | 80952 | 15692 | 19.38% |
| .flow.spare | 2202303 | 1967025 | 89.32% |
| .flow.memuse | 760476288 | 584361728 | 76.84% |
| .tcp.sessions | 2827913 | 411342 | 14.55% |
| .tcp.syn | 4690535 | 681756 | 14.53% |
| .tcp.synack | 2827913 | 411183 | 14.54% |
| .tcp.rst | 1931034 | 274591 | 14.22% |
| .tcp.reassembly_gap | 80952 | 24232 | 29.93% |
| .tcp.overlap | 0 | 1 | - |
| .detect.alert | 108732 | 14898 | 13.7% |
| .detect.alerts_suppressed | 1398578 | 201608 | 14.42% |
| .app_layer.flow.http | 544167 | 78374 | 14.4% |
| .app_layer.flow.ftp | 18444 | 2693 | 14.6% |
| .app_layer.flow.smtp | 18460 | 2682 | 14.53% |
| .app_layer.flow.tls | 1862622 | 270191 | 14.51% |
| .app_layer.flow.smb | 176775 | 26577 | 15.03% |
| .app_layer.flow.dcerpc_tcp | 16108 | 2313 | 14.36% |
| .app_layer.flow.failed_tcp | 137472 | 19945 | 14.51% |
| .app_layer.flow.dns_udp | 324446 | 47263 | 14.57% |
| .app_layer.flow.failed_udp | 150256 | 21844 | 14.54% |
| .app_layer.tx.http | 544167 | 78462 | 14.42% |
| .app_layer.tx.ftp | 73776 | 10768 | 14.6% |
| .app_layer.tx.smtp | 36920 | 5325 | 14.42% |
| .app_layer.tx.smb | 1452962 | 220133 | 15.15% |
| .app_layer.tx.dcerpc_tcp | 273836 | 39128 | 14.29% |
| .app_layer.tx.dns_udp | 648892 | 94509 | 14.56% |
| .app_layer.error.http.parser | 0 | 19 | - |
| .app_layer.error.ftp.parser | 18444 | 2689 | 14.58% |
| .app_layer.error.smtp.gap | 0 | 11 | - |
| .app_layer.error.tls.gap | 53852 | 10859 | 20.16% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 14 | - | 

Pipeline 8971

**Comment by victorjulien** [comment]
replaced by #7836

**Pull request closed without merging**
