### PR TITLE
Python lgtmfix v4

### PR DESCRIPTION
**Pull request by catenacyber**
Found by lgtm.com

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- Various python style improvements

Follows #4397 with needed rebase

### CODE REVIEW

**Comment by catenacyber** [comment]
Did I close this one by mistake ? It does not look merged...

**Comment by victorjulien** [comment]
> Did I close this one by mistake ? It does not look merged...

Think so. Not merged and no explanation given when it was closed.

**Comment by catenacyber** [comment]
Reopening

**Comment by victorjulien** [comment]
Merged through #4679, thanks Philippe!

**Pull request closed without merging**
