### PR TITLE
Smtp server detection 1125 v2.2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/1125
https://redmine.openinfosecfoundation.org/issues/6821
https://redmine.openinfosecfoundation.org/issues/5491

Describe changes:
- smtp server detection (ie to_client)
- ftp server detection (ie to_client)
- smtp recognize more reply codes

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1850

 https://github.com/OISF/suricata/pull/11128 with additional commit for smtp reply codes to get less smtp parser errors

### CODE REVIEW

**Comment by catenacyber** [comment]
There remain some unexpected SMTP reply codes :
- 400
- 472
- 4.7.0 (instead of 454)

and also some SMTP servers will reply unexpected command + the junk (TLS handshake from client) including multiple lines of it, so we get junk lines from the server

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.flow.smtp | 7556 | 7827 | 103.59% |
| .app_layer.error.smtp.parser | 409 | 42 | 10.27% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.smtp | 335817 | 347722 | 103.55% |
| .app_layer.flow.failed_tcp | 178240 | 161818 | 90.79% |
| .app_layer.tx.ftp | 101030 | 95212 | 94.24% |
| .app_layer.error.smtp.parser | 527 | 177 | 33.59% |
| .ftp.memuse | 10637 | 2921 | 27.46% | 

Pipeline 20871

**Comment by victorjulien** [comment]
Nice... Now I'm curious about the remaining 42 errors :)

**Comment by catenacyber** [comment]
> Nice... Now I'm curious about the remaining 42 errors :)

See https://github.com/OISF/suricata/pull/11193#issuecomment-2140768526

**Comment by victorjulien** [comment]
Since the 42 are from TLPW1, can we turn the unique error classes from it into SV tests?

**Comment by catenacyber** [comment]
> Since the 42 are from TLPW1, can we turn the unique error classes from it into SV tests?

Done in https://github.com/OISF/suricata-verify/pull/1894

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11261

**Pull request closed without merging**
