### PR TITLE
suricata: fix list-keywords option

### PR DESCRIPTION
**Pull request by regit**
The list keywords option was crashing due to improper init.

Ticket: 7397

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7397

Describe changes:
- fix list keywords

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 23399

**Comment by victorjulien** [comment]
"Attention: Patch coverage is 0%"... a CI check would be a good idea I think :)

**Comment by regit** [comment]
> "Attention: Patch coverage is 0%"... a CI check would be a good idea I think :)

I was thinking about adding a few command run (keywords and app layer list) in the CI. But I was wondering in which part of the CI it should be done. I've tried something.

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.dcerpc_tcp | 40 | 42 | 105.0% | 

Pipeline 23436

**Review by victorjulien — APPROVED** [review]

**Comment by inashivb** [comment]
> > "Attention: Patch coverage is 0%"... a CI check would be a good idea I think :)
> 
> I was thinking about adding a few command run (keywords and app layer list) in the CI. But I was wondering in which part of the CI it should be done. I've tried something and pushed an additional commit.

Thanks. Do you know why did the coverage not increase?

**Comment by victorjulien** [comment]
Merged in #12140, thanks!

**Pull request closed without merging**
