### PR TITLE
profiling: allow absolute paths

### PR DESCRIPTION
**Pull request by victorjulien**
Ticket #6490.

Replaces #11465

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21477

**Comment by jufajardini** [comment]
Should we have an SV or CI step to check for this?

**Comment by victorjulien** [comment]
> Should we have an SV or CI step to check for this?

I don't think we really need it here.

**Review by jufajardini — APPROVED** [review]
Worked with my local tests (both using /dev/null or trying to use a different absolute path)

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11488, thanks!

**Pull request closed without merging**
