### PR TITLE
Draft: Ish/Staging/v1

### PR DESCRIPTION
**Pull request by jasonish**
Staging:
- https://github.com/OISF/suricata/pull/9418
- Update bitflags crate
- https://github.com/OISF/suricata/pull/9419
- https://github.com/OISF/suricata/pull/9399
- https://github.com/OISF/suricata/pull/9426

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1363

### CODE REVIEW

**Comment by catenacyber** [comment]
What do you think about https://github.com/OISF/suricata/pull/9418/commits/45036b0ff0ca023c83841332bf8a361f22af94e1 ?

bit flags latest doc mentions to avoid zero bit flags cf https://docs.rs/bitflags/latest/bitflags/#zero-bit-flags

**Comment by jasonish** [comment]
> What do you think about [45036b0](https://github.com/OISF/suricata/commit/45036b0ff0ca023c83841332bf8a361f22af94e1) ?
> 
> bit flags latest doc mentions to avoid zero bit flags cf https://docs.rs/bitflags/latest/bitflags/#zero-bit-flags

We should update and bring that fix in. Sorry, that commit arrived after plucking the clippy fixes from the PR.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15781

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15784

**Comment by victorjulien** [comment]
Obsolete (and very messy), so closing.

**Pull request closed without merging**
