### PR TITLE
detect/transforms: test in place modifications of buffers

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7409

Describe changes:
- detect/transforms: fix and test in place modifications of buffers (aka do not use memcpy)

#12193 with clippy fixes

### CODE REVIEW

**Comment by victorjulien** [comment]
what is the "test" reference in the commit message? If this PR is a test, then it should just be a draft.

**Comment by catenacyber** [comment]
> what is the "test" reference in the commit message?

cargo unit tests

> If this PR is a test, then it should just be a draft.

It is not a draft

**Comment by victorjulien** [comment]
> > what is the "test" reference in the commit message?
> 
> cargo unit tests
> 
> > If this PR is a test, then it should just be a draft.
> 
> It is not a draft

The language confuses me, making me think the commit is a test, an experiment.

Would the following reflect your intent?

```
detect/transforms: in place modifications of buffers

As is the case when chaining multiple transforms.

Add tests.
```

**Comment by catenacyber** [comment]
Putting
```
detect/transforms: in place modifications of buffers
    
    As is the case when chaining multiple transforms.
    Avoids using memcpy in these cases.
    
    Add tests for these cases.
    
    Ticket: 7409
```

**Comment by catenacyber** [comment]
Next in https://github.com/OISF/suricata/pull/12200

My intent was to highlight the testing part, but not to confuse...

**Pull request closed without merging**
