### PR TITLE
readme: fix minor punctuation errors

### PR DESCRIPTION
**Pull request by joonkyu**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Added/removed punctuation to make sure it's consistency throughout the README file.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Looks good for me, thanks :)

**Comment by joonkyu** [comment]
Can I delete this fork or should I wait until merge?

**Comment by jufajardini** [comment]
> Can I delete this fork or should I wait until merge?

We must wait for it to be merged, which could happen, I believe, in the next couple of weeks or so. Thanks for asking! :)

**Comment by joonkyu** [comment]
Any updates on this pull request?

**Comment by jufajardini** [comment]
> Any updates on this pull request?

Sorry for letting it linger for so long, I'll try to bundle it with some other documentation PR this week.

**Comment by victorjulien** [comment]
I'm not going to take this as I think it's not really adding anything.

**Pull request closed without merging**
