### PR TITLE
Clippy fixes v3

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None 

Describe changes:
- rust: fix clippy warnings in tests

#10124 with code review + match_single_binding fixed + CI now listing unit tests

Side question @jasonish `cargo clippy` shows some optimizations because of `SCLogDebug` like
```
error: manual implementation of `Iterator::find`
   --> src/dns/dns.rs:362:9
    |
362 | /         for tx in &mut self.transactions {
363 | |             if tx.id == tx_id + 1 {
364 | |                 SCLogDebug!("Found DNS TX with ID {}", tx_id);
365 | |                 return Some(tx);
...   |
368 | |         SCLogDebug!("Failed to find DNS TX with ID {}", tx_id);
369 | |         return None;
    | |____________________^ help: replace with an iterator: `self.transactions.iter_mut().find(|tx| tx.id == tx_id + 1)`
    |
```

Should we optimize this and remove the debug logs ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17382

**Comment by jasonish** [comment]
> Should we optimize this and remove the debug logs ?

Yeah, I think we should use the iterator/find method here.

**Comment by catenacyber** [comment]
> > Should we optimize this and remove the debug logs ?
> 
> Yeah, I think we should use the iterator/find method here.

Maybe in a next PR, so that this one is only about rust unit tests, ok for you ?

**Review by jasonish — APPROVED** [review]
Some nice tidying.

**Comment by victorjulien** [comment]
Can we have the Cargo.lock.in update in a dedicated commit?

**Comment by jasonish** [comment]
> Can we have the Cargo.lock.in update in a dedicated commit?

That could break the commit-check CI job as Cargo.lock and Cargo.toml should not get out of sync.

**Comment by victorjulien** [comment]
> > Can we have the Cargo.lock.in update in a dedicated commit?
> 
> That could break the commit-check CI job as Cargo.lock and Cargo.toml should not get out of sync.

Sure, what I meant is that it's not clear from looking at the git log which commit updated Cargo.lock. I think https://github.com/OISF/suricata/pull/10129/commits/168b495917c8a3509cd702a1548bf2eadf43b9c4 just needs a different message, as it main thing is updating a dependency, so it should state that clearly in the subject.

**Comment by catenacyber** [comment]
> Sure, what I meant is that it's not clear from looking at the git log which commit updated Cargo.lock. I think [168b495](https://github.com/OISF/suricata/commit/168b495917c8a3509cd702a1548bf2eadf43b9c4) just needs a different message, as it main thing is updating a dependency, so it should state that clearly in the subject.

Reworded in https://github.com/OISF/suricata/pull/10152

**Pull request closed without merging**
