### PR TITLE
Next/60x/20220926/v4

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
- #7887 
- #7908
- #7913 
- mqtt backport
- flowbits parsing made more relax https://redmine.openinfosecfoundation.org/issues/5547

### CODE REVIEW

**Comment by catenacyber** [comment]
MSRV fails because of VecDeque.range_mut cf Debian 9

**Comment by victorjulien** [comment]
Needs a fix for the MSRV issue

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 81672 | 89920 | 110.1% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 88282 | - |
| .tcp.reassembly_gap | 80952 | 98551 | 121.74% |
| .tcp.overlap | 0 | 2 | - | 

Pipeline 9481

**Comment by victorjulien** [comment]
replaced by #7936

**Pull request closed without merging**
