### PR TITLE
exception/policy: add stats counters - v2

### PR DESCRIPTION
**Pull request by jufajardini**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5816

Previous PR: #8658 

Includes commit from https://github.com/OISF/suricata/pull/8733, to keep work complete.

Describe changes:
- register stats counters for all exception policies

TODO:
- better align stats.log - as the new counters size character is longer than what we currently have in the stats
- update the `json.schema` to include delta counters.

Considerations:
- Should we not output the registers that are zero, for the counters that are `0`?
Overall, Victor would like to have @jasonish input on the stats event verbosity. `app_layer` is especially long, since we have all values per enabled protocol.

The approach suggested [here](https://redmine.openinfosecfoundation.org/issues/5816#note-5) would be less verbose, but more complex to implement, given how the code is organized.

Output examples:
`app_layer`:
```json
 "app_layer": {
    "error": {
      "http": {
          "exception_policy": {
            "ignore": 0,
            "reject": 0,
            "bypass": 0,
            "pass_flow": 0,
            "drop_packet": 0,
            "drop_flow": 0
          }
       }
    }
}
```
`flow`:
```json
 "flow": {
    "memcap": 0,
     "memcap_exception_policy": {
        "ignore": 0,
        "reject": 0,
        "bypass": 0,
        "pass_flow": 0,
        "pass_packet": 0,
        "drop_flow": 0,
        "drop_packet": 1
  },
    "total": 1,
    "active": 0,
    "tcp": 0,
    "udp": 0,
    "icmpv4": 1,
    "icmpv6": 0,
    "tcp_reuse": 0,
    "get_used": 0,
    "get_used_eval": 0,
    "get_used_eval_reject": 0,
    "get_used_eval_busy": 0,
    "get_used_failed": 0,
    "wrk": {
      "spare_sync_avg": 100,
      "spare_sync": 1,
      "spare_sync_incomplete": 0,
      "spare_sync_empty": 0,
      "flows_evicted_needs_work": 0,
      "flows_evicted_pkt_inject": 0,
      "flows_evicted": 0,
      "flows_injected": 0,
      "flows_injected_max": 0
    },
```

suricata-verify-pr: 1178
https://github.com/OISF/suricata-verify/pull/1178

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 112875 | 145101 | 128.55% | 

Pipeline 13238

**Comment by jufajardini** [comment]
Haven't checked the fuzz issue yet.

**Comment by jasonish** [comment]
> Should we not output the registers that are zero, for the counters that are 0?

It would be nice to have such an option to apply to all outputted stats.  I've done this in some event visualization code code, and hide all zero values makes it much more pleasant to look at.  But may introduce reporting challenges for some databases.  Elastic can handle this fine, as well as some more advanced SQL though.

**Comment by jufajardini** [comment]
> > Should we not output the registers that are zero, for the counters that are 0?
> 
> It would be nice to have such an option to apply to all outputted stats. I've done this in some event visualization code code, and hide all zero values makes it much more pleasant to look at. But may introduce reporting challenges for some databases. Elastic can handle this fine, as well as some more advanced SQL though.

I'll add a reference to this comment in a ticket we created to keep this in mind - https://redmine.openinfosecfoundation.org/issues/6001

**Comment by jufajardini** [comment]
> I don't know if the verbosity can be helped as we add more visibility into whats going on, but it is getting quite verbase. Between master and this PR, a single `stats` record has grown from 608 lines (~13k) to 891 lines (~20k) which is considerable.
> 
> A few things to consider:
> 
> * Should per-protocol be done? Maybe off by default, you should still see the numbers in aggregate under `flow` right?

I hadn't considered adding the summary of the app-layer errors to the flow portion of the stats. In that case, should it look somewhat like:
```json
{
  "flow": {
    "app_layer":{
      "exception_policy": {
        "ignore": 0,
        "reject": 0,
        "bypass": 0,
        "pass_flow": 0,
        "drop_packet": 0,
        "drop_flow": 0
        }
     }
   }
}
```

> * Is data with respect to exception policies logged to a flow record? If it is, that could be one way to drill into which protocols are exhibiting this problem.  And just have the `flow` log this in detail under the stats is a signal to look deeper.

Not as of now. If the flow is dropped due to some exception policy (then the drop reason could show up in the first associated drop event - but I'm not sure if we get the exact same value in the flow event where we register if a show was dropped.

> * Make the per-protocol a configuration option for stats? I wouldn't make a flag per protocol, just something along the liens of `enable-app-layer-exception-stats` or something like that.

Agreeing with this part, maybe having that coupled with showing a summary in the flow portion, as you've pointed out, too, would work well...

> * Having an option to suppress 0 values could help as well I suppose.
> 
> Anyways, these are my initial thoughts.

Thanks for the feedback 🙇🏽

**Comment by jasonish** [comment]
> > I don't know if the verbosity can be helped as we add more visibility into whats going on, but it is getting quite verbase. Between master and this PR, a single `stats` record has grown from 608 lines (~13k) to 891 lines (~20k) which is considerable.
> > A few things to consider:
> > 
> > * Should per-protocol be done? Maybe off by default, you should still see the numbers in aggregate under `flow` right?
> 
> I hadn't considered adding the summary of the app-layer errors to the flow portion of the stats. In that case, should it look somewhat like:
> 
> ```json
> {
>   "flow": {
>     "app_layer":{
>       "exception_policy": {
>         "ignore": 0,
>         "reject": 0,
>         "bypass": 0,
>         "pass_flow": 0,
>         "drop_packet": 0,
>         "drop_flow": 0
>         }
>      }
>    }
> }
> ```

Would this be required?  I was more asking if `flow.memcap.memcap_exception_policy` includes counts for what would appear in the app-layer counters?  Cause if it appears in an app-layer counter, it must have a flow I think.

The idea being to not add more.

**Comment by jufajardini** [comment]
> 

Oh, I misunderstood it. Each of those fields reports on different exception policies. 
`app_layer.error.exception_policy` counts when the app-layer proto reached an error state, these are different from the ones counted in `flow.memcap.memcap_exception_policy`.

**Comment by jasonish** [comment]
> > 
> 
> Oh, I misunderstood it. Each of those fields reports on different exception policies. `app_layer.error.exception_policy` counts when the app-layer proto reached an error state, these are different from the ones counted in `flow.memcap.memcap_exception_policy`.

I feel like I need a big flow chart on a big whiteboard :)

Without touching every app-layer module, can an app-layer exception counter be implemented?  So we know there are exceptions happening in the app-layer but we don't know which one, unless more verbose logging is enabled?

**Comment by jufajardini** [comment]
> > > 
> > 
> > 
> > Oh, I misunderstood it. Each of those fields reports on different exception policies. `app_layer.error.exception_policy` counts when the app-layer proto reached an error state, these are different from the ones counted in `flow.memcap.memcap_exception_policy`.
> 
> I feel like I need a big flow chart on a big whiteboard :)

Haha, we do need better documentation on the exception policies. We're adding a matrix just for the midstream case, but we might need more in general, too. D:

> 
> Without touching every app-layer module, can an app-layer exception counter be implemented? So we know there are exceptions happening in the app-layer but we don't know which one, unless more verbose logging is enabled?

Considering how these `app-layer` errors in general are counted, I'd say so. I'll look into that :)

**Comment by jufajardini** [comment]
- We're missing `pass_packet` for `app_layer`
- Reminder: remove values that cannot be applied to specific policies from their logs (like `pass_flow` in `flow_memcap`)
- by default, have only the app-layer summary version enabled
- if configured for more verbose mode, enable per app-proto
- don't output 0 values
- consider if we can actually not output when exception policy is ignore
- change `ignore` to `ignored`
- standardize the outputs, if we make them more compact

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 112875 | 145101 | 128.55% | 

Pipeline 13238

**Comment by catenacyber** [comment]
Hey @jufajardini :-) are you planning to get back on this ?

**Comment by jufajardini** [comment]
> Hey @jufajardini :-) are you planning to get back on this ?

Yep, it's just that it's been moved to 8, right now...

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 112875 | 145101 | 128.55% | 

Pipeline 13238

**Comment by jufajardini** [comment]
Coming back to this work after I finish my current task, but will close this one as it's stale.

**Pull request closed without merging**
