### PR TITLE
rule: Don't drop flow if rule matches on packet properties.

### PR DESCRIPTION
**Pull request by jlucovsky**
This commit modifies the logic used to determine the disposition of a flow/packet.

If the rule contains packet match properties, the flow shouldn't be dropped.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [5578](https://redmine.openinfosecfoundation.org/issues/5578)

Describe changes:
- When deciding how to handle the `drop` action, check if the rule applies to packet properties.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1414

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | IPS_AFP_stats_chk | | |
| .tcp.reassembly_gap | 54000 | 108000 | 200.0% |
| .flow_bypassed.local_pkts | 0 | 25920 | - |
| .flow_bypassed.local_bytes | 0 | 2833920 | - |
| .detect.alerts_suppressed | 1058400 | 1112400 | 105.1% | 

Pipeline 15863

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | IPS_AFP_stats_chk | | |
| .tcp.reassembly_gap | 54000 | 108000 | 200.0% |
| .flow_bypassed.local_pkts | 0 | 25920 | - |
| .flow_bypassed.local_bytes | 0 | 2833920 | - |
| .detect.alerts_suppressed | 1058400 | 1112400 | 105.1% | 

Pipeline 15874

**Comment by jufajardini** [comment]
I wish I could signal to watch this PR, to better understand this. 
And this makes me wonder if we should try and document those flags....

**Review by inashivb — COMMENTED** [review]
This patch makes sense to me.
I have added the s-v tests done by Victor to the PR body and re-triggered the CI.

**Comment by inashivb** [comment]
The s-v test seems to pass. The test `http2-deflate` on Ubuntu 22.04 is failing. The test seems flaky to me but would be nice if you checked.

**Comment by jlucovsky** [comment]
Continued in #9664

**Pull request closed without merging**
