### PR TITLE
xdp: compile on pre 5.11 kernels - v1

### PR DESCRIPTION
**Pull request by jasonish**
Changes:
- github-ci: add Debian 11 builder with XDP
- source-xdp: only allow busy poll if headers support it

Ticket: https://redmine.openinfosecfoundation.org/issues/5855

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 12371

**Comment by victorjulien** [comment]
#8524's xdp fix doesn't play well with this. Can you integrate both?

**Comment by jasonish** [comment]
> #8524's xdp fix doesn't play well with this. Can you integrate both?

I think for now we drop the fix in 8524.  That'll need a configure.ac test

**Comment by victorjulien** [comment]
Merged in #8605, thanks!

**Pull request closed without merging**
