### PR TITLE
base64: use Rust base64 encoder - v3

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/6342

Changes from last PR:
- Fix C buffer length accounting.

### CODE REVIEW

**Comment by jasonish** [comment]
This does not use the Rust base64 craft for decoding yet, as our decoder has a non-strict mode where it will return what its decoded so far once it hits an error. The Rust crate just fails without returning whats been decode so far.  But I think with some work it could be made to work that way.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4058

**Comment by suricata-qa** [comment]
Information:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .detect.alert | 3108324 | 3964415 | 78.41% |

Pipeline 4058

**Comment by suricata-qa** [comment]
Information:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .detect.alert | 3108324 | 3964415 | 78.41% |

Pipeline 4058

**Comment by victorjulien** [comment]
Requesting another rebase so QA can compare it to a proper baseline.

**Comment by jasonish** [comment]
Rebased: https://github.com/OISF/suricata/pull/6423

**Pull request closed without merging**
