### PR TITLE
Multipart mime 3487 v28

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser

Follows #9769 with rust nits fixed

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
  

Pipeline 16644

**Comment by ct0br0** [comment]
Looks like this only adds a file for TLPW1, so it should be good.

**Review by victorjulien — CHANGES_REQUESTED** [review]
CI failure needs investigation

**Comment by catenacyber** [comment]
> CI failure needs investigation

Nice find : just default values used for `MIME_SMTP_CONFIG_DECODE_BASE64` when nothing is in suricata.yaml

Updating in next PR

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/9873

**Pull request closed without merging**
