### PR TITLE
Napatech: fixed SCTIME_ADD_USECS from util-time.h

### PR DESCRIPTION
**Pull request by ilya-bakhtin**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
it's https://github.com/OISF/suricata/pull/9523 rebased to the current master branch

The SCTIME_ADD_USECS code is updated and timestamp-related code in source-napatech.c is fixed.
Current 7.0.2 and master versions generate timestamps with seconds == 0.
The SV test is impossible since the code is only reachable when the Napatech card is available.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by sfd** [comment]
If you are fixing SCTIME_ADD_USECS() why not fix SCTIME_ADD_SECS() as well? That macro is returning 0 for usecs instead of ts.usec, which is inconsistent?
SCTIME_ADD_SECS(ts, s) should add s to ts.secs and return ts.usec unmodified.

**Comment by ilya-bakhtin** [comment]
My intention was to fix Napatech-related bugs only.
SCTIME_ADD_SECS I
is used in separate places and it seems somebody already made a workaround that assumes the current incorrect behavior. I'm not sure if some tests cover the corresponding code and I do not want to introduce possible troubles. My opinion is that It's definitely not in the scope of Napatech fix and it must be tracked separately.

**Comment by jlucovsky** [comment]
> If you are fixing SCTIME_ADD_USECS() why not fix SCTIME_ADD_SECS() as well? That macro is returning 0 for usecs instead of ts.usec, which is inconsistent? SCTIME_ADD_SECS(ts, s) should add s to ts.secs and return ts.usec unmodified.

Could you file a separate redmine issue for this? I think we should keep the scope intact for this MR.

**Comment by sfd** [comment]
> Could you file a separate redmine issue for this? I think we should keep the scope intact for this MR.

Agreed.
https://redmine.openinfosecfoundation.org/issues/6584

**Review by jlucovsky — APPROVED** [review]

**Review by jlucovsky — COMMENTED** [review]
Hi @ilya-bakhtin 

The code changes look good. We'd like the commit messages to be adjusted to be consistent with https://docs.suricata.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits

E.g., the commit message for the change to `util-time.h` could be

time: Ensure useconds doesn't overflow

Issue: 6372

This commit prevents the useconds field from overflowing past its maximum value.

Similarly, the message for the second commit (source-napatech.c) can be improved.

**Comment by ilya-bakhtin** [comment]
Hi @jlucovsky, should i create a new pull request with updated commit messages?

**Comment by jlucovsky** [comment]
> Hi @jlucovsky, should i create a new pull request with updated commit messages?

Yes -- thank you.

**Pull request closed without merging**
