### PR TITLE
streaming: fix intersect detection

### PR DESCRIPTION
**Pull request by victorjulien**
Update logic to always use data right edge.

Bug: #6041.

### CODE REVIEW

**Comment by victorjulien** [comment]
https://redmine.openinfosecfoundation.org/issues/5834 actually, will check if 6041 is also fixed by this

**Comment by victorjulien** [comment]
> https://redmine.openinfosecfoundation.org/issues/5834 actually, will check if 6041 is also fixed by this

6041 is a separate issue

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 13851

**Comment by victorjulien** [comment]
replaced by #8903

**Pull request closed without merging**
