### PR TITLE
draft: dns: parser and alert on invalid opcodes - v2

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/8228

Draft: Trying to resolve .app_layer.error.dns_udp.parser as seen at
https://github.com/OISF/suricata/pull/8228#issuecomment-1332728829.

suricata-verify-pr: 1024

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 28003 | 74715 | 266.81% | 

Pipeline 11065

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 11092

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.spare | 2212941 | 2099617 | 94.88% |
| .flow.memuse | 565135168 | 613615168 | 108.58% |
| .app_layer.error.dns_udp.parser | 28003 | 74715 | 266.81% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 183302 | 0.03 | 

Pipeline 11108

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103997 | 81.1% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.dns_udp.parser | 28003 | 74715 | 266.81% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 8353 | 0.00 | 

Pipeline 11266

**Comment by jasonish** [comment]
Replaced by https://github.com/OISF/suricata/pull/8311.

**Pull request closed without merging**
