### PR TITLE
DNS cleanup: Move more C pieces to Rust - v3

### PR DESCRIPTION
**Pull request by jasonish**
Moves more of the remaining C parser bits to Rust. Most of the C
was just wrappers around Rust functions anyways.

Also a small DHCP cleanup where it also just wrapped Rust.

Previous PR: https://github.com/OISF/suricata/pull/4513

Changes from last PR:
- Remove unused DNS settings from suricata.yaml.
- Use "silent errors" for unknown app-layer decoder events.

Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/3234

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/440
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/796

### CODE REVIEW

**Comment by victorjulien** [comment]
With `-T` unknown events still cause failure. Is that intended?
```
./src/suricata -c suricata.yaml -l tmp/ -S ../suricata-4.1.x/rules/dns-events.rules -T
[21284] 24/2/2020 -- 11:13:37 - (suricata.c:1892) <Info> (ParseCommandLine) -- Running suricata under test mode
[21284] 24/2/2020 -- 11:13:37 - (suricata.c:1069) <Notice> (LogVersion) -- This is Suricata version 6.0.0-dev (194897987 2020-02-24) running in SYSTEM mode
[21284] 24/2/2020 -- 11:13:37 - (detect-app-layer-event.c:209) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "dns" doesn't have event "unsollicited_response" registered
[21284] 24/2/2020 -- 11:13:37 - (detect-app-layer-event.c:209) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "dns" doesn't have event "flooded" registered
[21284] 24/2/2020 -- 11:13:37 - (detect-app-layer-event.c:209) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "dns" doesn't have event "state_memcap_reached" registered
[21284] 24/2/2020 -- 11:13:37 - (suricata.c:2469) <Error> (LoadSignatures) -- [ERRCODE: SC_ERR_NO_RULES_LOADED(43)] - Loading signatures failed.
```

**Comment by jasonish** [comment]
> With `-T` unknown events still cause failure. Is that intended?
> 
> ```
> ./src/suricata -c suricata.yaml -l tmp/ -S ../suricata-4.1.x/rules/dns-events.rules -T
> [21284] 24/2/2020 -- 11:13:37 - (suricata.c:1892) <Info> (ParseCommandLine) -- Running suricata under test mode
> [21284] 24/2/2020 -- 11:13:37 - (suricata.c:1069) <Notice> (LogVersion) -- This is Suricata version 6.0.0-dev (194897987 2020-02-24) running in SYSTEM mode
> [21284] 24/2/2020 -- 11:13:37 - (detect-app-layer-event.c:209) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "dns" doesn't have event "unsollicited_response" registered
> [21284] 24/2/2020 -- 11:13:37 - (detect-app-layer-event.c:209) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "dns" doesn't have event "flooded" registered
> [21284] 24/2/2020 -- 11:13:37 - (detect-app-layer-event.c:209) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "dns" doesn't have event "state_memcap_reached" registered
> [21284] 24/2/2020 -- 11:13:37 - (suricata.c:2469) <Error> (LoadSignatures) -- [ERRCODE: SC_ERR_NO_RULES_LOADED(43)] - Loading signatures failed.
> ```

Perhaps a new error code, -3, silient case but don't error out?  I forget the -T implies init-errors-fatal.

**Comment by victorjulien** [comment]
Like discussed in our call:
`-T` should pass even with warning.
With `--strict-parsing` it should fail with `-T`.
Operate similar to our `ja3` logic.

So this needs a bit more testing. Can we add SV tests for this and also the JA3 case?

**Comment by jasonish** [comment]
> Like discussed in our call:
> `-T` should pass even with warning.
> With `--strict-parsing` it should fail with `-T`.
> Operate similar to our `ja3` logic.
> 
> So this needs a bit more testing. Can we add SV tests for this and also the JA3 case?

JA3 handling isn't as graceful as we thought.  If ja3 is disabled, or NSS support is not compiled in, loading JA3 rules with -T will result in a failed exit code. So in that respect, JA3, and unknown application layer event keywords currently behave the same.

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/4608.

**Pull request closed without merging**
