### PR TITLE
runmodes: dpdk: Move IPS check outside of the core suricata file and add checksum offload to DPDK v8

### PR DESCRIPTION
**Pull request by lukashino**
This is a follow-up of PR #8332 

Changes
- duplicate definition of netmap function removed
- Livedev functions changed in `ConfigGetCaptureValue` function
- Livedev functions working with preregistered devices removed
- update Github CI hashes

Redmine tickets:
https://redmine.openinfosecfoundation.org/issues/5580
https://redmine.openinfosecfoundation.org/issues/5553
https://redmine.openinfosecfoundation.org/issues/5706

### CODE REVIEW

**Comment by lukashino** [comment]
Force pushed to update action hashes in the Github CI DPDK action.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104030 | 81.12% |
| .app_layer.error.tls.parser | 931 | 1145 | 122.99% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.http | 3118951 | 3340798 | 107.11% |
| .app_layer.flow.tls | 510462 | 623355 | 122.12% |
| .app_layer.flow.ssh | 8937 | 11032 | 123.44% |
| .app_layer.flow.telnet | 1624 | 2334 | 143.72% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| | IPS_AFP_stats_chk | | |
| .tcp.segment_from_pool | 17114563 | 15754545 | 92.05% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 18489 | 0.00 | 

Pipeline 11678

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103934 | 81.05% |
| .app_layer.error.tls.parser | 931 | 1145 | 122.99% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 599980608 | 106.17% |
| .app_layer.flow.http | 3118951 | 3340799 | 107.11% |
| .app_layer.flow.tls | 510462 | 623355 | 122.12% |
| .app_layer.flow.ssh | 8937 | 11032 | 123.44% |
| .app_layer.flow.telnet | 1624 | 2334 | 143.72% |
| | IPS_AFP_stats_chk | | |
| .tcp.segment_from_pool | 17114563 | 15754815 | 92.06% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 195346 | 0.03 | 

Pipeline 11682

**Comment by victorjulien** [comment]
Merged in #8430, thanks!

**Pull request closed without merging**
