### PR TITLE
runmodes: fix `--list-runmodes` output-V1

### PR DESCRIPTION
**Pull request by Rai0Catodic0**
Modified the RunMode Struct to include fields for more informations about each runmode

Optimization: #6572

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ :heavy_check_mark: ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [ :heavy_check_mark:  ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [  ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues
      (if applicable)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
- Added new fields to the RunMode struct to follow the suggested description as listed in the ticket [#6572 ](https://redmine.openinfosecfoundation.org/issues/6572). 
-
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by victorjulien** [comment]
This looks incomplete? Just adding struct members will not achieve much.

**Comment by Rai0Catodic0** [comment]
Hi, I'm sorry , I feel I wasn't clear in the goal of my draft PR. I wanted to discuss my proposal for the addition of fields to struct, after that I will be modifying the registerRunmode to populate those fields and the ListRunModes to print then as well.
Sorry about the confusion

**Comment by victorjulien** [comment]
Ok, so can you explain what you're after in more detail?

**Comment by Rai0Catodic0** [comment]
Closing in favor of a newer PR(#11412)

**Pull request closed without merging**
