### PR TITLE
Threshold flow/v1

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1677

https://redmine.openinfosecfoundation.org/issues/6822

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 18906

**Comment by victorjulien** [comment]
To provide some context: my idea is to update the stream events to use this to reduce stream event alerts per flow. Per flow tracking means relatively low overhead.

**Comment by jasonish** [comment]
On first look, things look OK.  But I find there is some detail lacking in the ticket and/or commit message as to why.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 18920

**Comment by victorjulien** [comment]
replaced by #10550

**Pull request closed without merging**
