### PR TITLE
next/159/20231107/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #9745
 - #9746

SV_BRANCH=pr/1456

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16410

**Comment by victorjulien** [comment]
SV PR breaks 6.0.x, need to resolve that before this can be merged.

**Comment by catenacyber** [comment]
> SV PR breaks 6.0.x, need to resolve that before this can be merged.

And we need to merge this to create the backport to have SV PR passing 6.0.x right ?

**Comment by victorjulien** [comment]
> > SV PR breaks 6.0.x, need to resolve that before this can be merged.
> 
> And we need to merge this to create the backport to have SV PR passing 6.0.x right ?

Yeah, if you can commit to doing that quickly after the merge I'm fine with that.

**Comment by catenacyber** [comment]
> Yeah, if you can commit to doing that quickly after the merge I'm fine with that.

I can do that today to tomorrow morning :-)

**Review by catenacyber — APPROVED** [review]
Good for me

**Pull request merged**
