### PR TITLE
Rust unused v3

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None, generic cleaning

Describe changes:
- rust: remove unused dead code

Found with
`git grep 'pub ' rust/src/ | cut -d: -f1 | uniq | xargs sed -i -e 's/pub /pub(crate) /'` then see rust warnings when compiling

There is more to it :
- https://redmine.openinfosecfoundation.org/issues/4517 `APP_LAYER_PARSER_NO_INSPECTION_PAYLOAD` and like should only be defined on the rust side
- There are parsed fields which get never used. (like `pad` in DCERPCState) Coming in a next PR
- dcerpc defines lots of unused constants like PFC_RESERVED_1. These should get removed as well
- `AuthenticationKerb5` and like are never constructed for pgsql. Should they be @jufajardini ?

Follows #8771 with code review from @jasonish taken into account

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 13462

**Comment by jufajardini** [comment]
I'll refresh my memory and notes to give an answer on the Kerb5/PGSQL question. o>

**Comment by jufajardini** [comment]
@catenacyber according to Postgresql v13 docs, Kerb5 is no longer supported since  9.4 - I checked previous docs versions to find this info. (https://www.postgresql.org/docs/13/protocol-flow.html#id-1.10.5.7.3). I guess my question with regard to this is: should we be able to parse unsupported versions of messages? If yes, then the Kerb5 should stay - and then I must extend `pgsql_parse_authentication_message`. If not, then yep, to remove it.

**Comment by catenacyber** [comment]
> according to Postgresql v13 docs, Kerb5 is no longer supported since 9.4 - I checked previous docs versions to find this info. (https://www.postgresql.org/docs/13/protocol-flow.html#id-1.10.5.7.3). I guess my question with regard to this is: should we be able to parse unsupported versions of messages? If yes, then the Kerb5 should stay - and then I must extend `pgsql_parse_authentication_message`. If not, then yep, to remove it.

@jufajardini I would say that this Kerb5 should be removed until implemented for real, and I am not sure this is important enough to do so...

**Comment by jufajardini** [comment]
> > according to Postgresql v13 docs, Kerb5 is no longer supported since 9.4 - I checked previous docs versions to find this info. (https://www.postgresql.org/docs/13/protocol-flow.html#id-1.10.5.7.3). I guess my question with regard to this is: should we be able to parse unsupported versions of messages? If yes, then the Kerb5 should stay - and then I must extend `pgsql_parse_authentication_message`. If not, then yep, to remove it.
> 
> @jufajardini I would say that this Kerb5 should be removed until implemented for real, and I am not sure this is important enough to do so...

Ok, I'll prepare a PR to remove them for now.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8880

**Pull request closed without merging**
