### PR TITLE
Include less v13

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/945

Describe changes:
- Remove unused includes in c files
- adds some options in CI : hyperscan, luajit

Follows #7942 with removing includes only if all ifdefs are defined...

This is no longer a draft !

There are still some configure options that I can run afterwards
And there is also the case of moving includes in ifdef if they are only needed in one case...

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 126063 | 103120 | 81.8% | 

Pipeline 9602

**Comment by victorjulien** [comment]
Would like to fast track this, can you rebase (or redo if it is tool based)?

**Comment by catenacyber** [comment]
> Would like to fast track this, can you rebase (or redo if it is tool based)?

Yes, I can redo it next week.

Would you like a first PR with the commits up to `scripts: include minimizer` ?

**Comment by catenacyber** [comment]
This has been getting more complex since commit 39cf5b151a73ea24f926946abebf253a76e09eb8 which made the header file util-unittest-helper.h :
- break cppclean in a bigger way than was done before (cf one-line fix in this PR) : this is doable
- make a header file conditionally include other header files : decode-icmpv4.c really needs to include flow.h by itself for the case where we compile without unit tests, even if the script is not smart enough to guess so

**Comment by catenacyber** [comment]
Try in https://github.com/OISF/suricata/pull/8138

**Pull request closed without merging**
