### PR TITLE
Rfb frames v11

### PR DESCRIPTION
**Pull request by hsadia538**
- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5717

Previous PR: https://github.com/OISF/suricata/pull/8364

Describe changes:

- Register `pdu` frames in every match case.

suricata-verify-pr: 1059

### CODE REVIEW

**Comment by jufajardini** [comment]
My apologies, I triggered another run of the CI checks, and not they're failing, possibly due to the fact that this hasn't been rebased.

**Review by jufajardini — APPROVED** [review]
In the light of the discussion in the previous PR, I think that these changes are good.

Let's wait for some other mentor to give the final word, now :)

**Comment by jufajardini** [comment]
Seeing that we have these CI failures, just to be 100% sure things are good, could you please rebase both Suricata and SV branches and submit new PRs? Then I'll ping the other mentors for extra reviews :)

**Comment by hsadia538** [comment]
followed by #8526

**Pull request closed without merging**
