### PR TITLE
eve: add json schema for eve

### PR DESCRIPTION
**Pull request by jasonish**
Ticket: https://redmine.openinfosecfoundation.org/issues/1369

Add JSON schema for EVE.

Just adds a few missing fields from #7407.

suricata-verify-pr: 830

### CODE REVIEW

**Comment by victorjulien** [comment]
Many CI failures it seems.

**Comment by jasonish** [comment]
CI issues fixed.  Fedora 34 seems to be failing due to reasons outside of our control tho.

**Comment by jasonish** [comment]
CI issues should be fixed now, plus some silent failures.

**Comment by catenacyber** [comment]
Nice :-)

**Comment by victorjulien** [comment]
Merged as part of #7455, thanks!

**Pull request closed without merging**
