### PR TITLE
Dns z bit 4515 v2

### PR DESCRIPTION
**Pull request by odinje**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [Feature #4515](https://redmine.openinfosecfoundation.org/issues/4515) ticket:

Describe changes:
- Adding logging of Z-bit in DNS logs
- Updating eve-json-format documentation for DNS to include this bit

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by jasonish** [comment]
Do you happen to have a public pcap with the z-flag set that we can put into `suricata-verify`?

**Comment by odinje** [comment]
Currently I do not have a public PCAP, but I could craft one if that is suitable.

**Comment by catenacyber** [comment]
> Currently I do not have a public PCAP, but I could craft one if that is suitable.

Yes :-) a crafted pcap is better than no pcap

**Comment by jasonish** [comment]
Fixes and request handling added in https://github.com/OISF/suricata/pull/6731.

**Pull request closed without merging**
