### PR TITLE
Cocci check v2

### PR DESCRIPTION
**Pull request by regit**
Update of #4387 fixing make distcheck and handling false positive. It also adds a new feature to check value of flags in setter and getter.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/2852

Describe changes:
- Port struct-flags.py to python 3
- Fix make dist check
- Add setter and getter flags check

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/512
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/288

### CODE REVIEW

**Comment by victorjulien** [comment]
I can confirm the struct-flags.cocci now passes, thanks.

What I don't understand is that in my own tests the `strndup` use (in `util-mem.h`) doesn't trigger in our QA (prscript, travis, github-actions), while it does fail in my own.

**Comment by regit** [comment]
@victorjulien it would worth to compare coccinelle version on the different systems.

**Comment by victorjulien** [comment]
Merged in #4420, thanks Eric!

**Comment by victorjulien** [comment]
> @victorjulien it would worth to compare coccinelle version on the different systems.

Tried 1.0.4 and 1.0.8.

**Pull request closed without merging**
