### PR TITLE
next/qarebaseline/20240504/v1

### PR DESCRIPTION
**Pull request by catenacyber**
Branch: pr-staging/3
- https://github.com/OISF/suricata/pull/10980
- https://github.com/OISF/suricata/pull/10981
- https://github.com/OISF/suricata/pull/10982

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.

ERROR: QA failed on SURI_TLPR1_alerts_cmp.

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.flow.ftp | 52 | 43 | 82.69% |
| .app_layer.tx.ftp | 819 | 188 | 22.95% |
| .app_layer.error.ftp.gap | 2 | 0 | - |
| .app_layer.error.ftp.parser | 2 | 0 | - |
| .ftp.memuse | 348 | 3 | 0.86% |
| | SURI_TLPR1_stats_chk | | |
| .ftp.memuse | 11385 | 10637 | 93.43% |
| | IPS_AFP_stats_chk | | |
| .ips.blocked | 1395360 | 747360 | 53.56% |
| .ips.drop_reason.flow_drop | 1296000 | 680400 | 52.5% |
| .ips.drop_reason.applayer_error | 32400 | 0 | - |
| .flow.end.state.established | 583199 | 550799 | 94.44% |
| .flow.end.state.closed | 1016272 | 1048672 | 103.19% |
| .flow.end.tcp_state.established | 201960 | 169560 | 83.96% |
| .flow.end.tcp_state.closed | 1016272 | 1048672 | 103.19% |
| .app_layer.error.exception_policy.drop_flow | 32400 | 0 | - |
| .app_layer.error.ftp.parser | 32400 | 0 | - |
| .app_layer.flow.ftp | 33480 | 1080 | 3.23% |
| .app_layer.tx.ftp | 131760 | 2160 | 1.64% |
| | TREX_GENERIC_stats_chk | | |
| .app_layer.flow.ftp | 14871 | 0 | - |
| .app_layer.tx.ftp | 59484 | 0 | - |
| .app_layer.error.ftp.parser | 14871 | 0 | - | 

Pipeline 20503

**Comment by victorjulien** [comment]
@ct0br0 can you prep a rebaseline based on this PR?

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11095, thanks!

**Comment by catenacyber** [comment]
Forgot to do a staging SV PR matching this cf https://github.com/OISF/suricata-verify/labels/tests%20pass

**Pull request closed without merging**
