### PR TITLE
WIP -- Netmap 6.0.x port with candidate fix for fuzzing issue

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #6741 -- check to see if https://github.com/OISF/suricata/pull/6716/commits/96e3424e0f5ca5abe5d5a6afd38e52677220540c helps with fuzzing related errors.

Describe changes:
-
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.memuse | 513144448 | 544894528 | 94.17% |
| | generic_stats_chk |
| .capture.kernel_drops | 0 | 92961 | 0.0% |
| .tcp.reassembly_gap | 80952 | 97967 | 82.63% | 

Pipeline 5605

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | generic_stats_chk |
| .capture.kernel_drops | 0 | 92961 | 0.0% |
| .tcp.reassembly_gap | 80952 | 97967 | 82.63% | 

Pipeline 5615

**Comment by catenacyber** [comment]
The CIFuzz issue seems to be the nfs file_data signature ;-)

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 5902

**Pull request closed without merging**
