### PR TITLE
src: use WARN_UNUSED for ByteExtract* functions

### PR DESCRIPTION
**Pull request by hsadia538**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues/3658) ticket:

Previous PR: https://github.com/OISF/suricata/pull/8022

Describe new changes:

- Add missing WARN_UNUSED macro for ByteExtractStringInt32
- Fix spelling line 467 
- Update Copyright year

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Hi @hsadia538 !
Good job with this. 😃 The patch seems OK to me on the first sight but we need to make the following changes:
1. The part of code being changed here is `src` so please prefix your commit messages with that instead of `c`.
2. There should be just one commit to merge here.

**Review by jufajardini — CHANGES_REQUESTED** [review]
It also seems that some of the changes have triggered our clang checks (see https://github.com/OISF/suricata/actions/runs/3269124932/jobs/5379018207#step:14:31).

You may use clang-format.sh branch to make the necessary changes. If there are too many, please add them to their own commit :)

**Comment by hsadia538** [comment]
> Hi @hsadia538 ! Good job with this. 😃 The patch seems OK to me on the first sight but we need to make the following changes:
> 
> 1. The part of code being changed here is `src` so please prefix your commit messages with that instead of `c`.
> 2. There should be just one commit to merge here.

Thanks @inashivb . I have squashed the commits here and updated the commit message as well.

**Comment by hsadia538** [comment]
> It also seems that some of the changes have triggered our clang checks (see https://github.com/OISF/suricata/actions/runs/3269124932/jobs/5379018207#step:14:31).
> 
> You may use clang-format.sh branch to make the necessary changes. If there are too many, please add them to their own commit :)

When I try to do so I get errors in clang-format.sh . See below for reference.
Screenshot 2022-10-18 at 11 00 36 PM

Alternatively I've tried git clang-format but it says nothing to modify.

**Comment by hsadia538** [comment]
> It also seems that some of the changes have triggered our clang checks (see https://github.com/OISF/suricata/actions/runs/3269124932/jobs/5379018207#step:14:31).
> 
> You may use clang-format.sh branch to make the necessary changes. If there are too many, please add them to their own commit :)

I have force pushed after squashing commits. How can I run the tests again to see if the issue is resolved?

**Comment by hsadia538** [comment]
> I just approved the workflow run, so we'll see how it goes!
Alright, thanks!

> How were you able to fix it? (I was still answering your comment :P )

I am not sure if the change works but to make it I made a dummy change(e.g adding spaces) in the code and ran git clang-format. After comparing the files, I was able to spot formatting changes so I think it worked but not sure yet.

**Comment by jufajardini** [comment]
Still failing...

what clang version do you have installed?

**Comment by hsadia538** [comment]
> Still failing...
> 
> what clang version do you have installed?

Homebrew clang-format version 15.0.2

**Comment by jufajardini** [comment]
> > Still failing...
> > what clang version do you have installed?
> 
> Homebrew clang-format version 15.0.2

I've shared the suggested changes by clang with you, but if you keep having issues with clang, maybe we could ask if @catenacyber  knows how to approach this since he also uses a mac...

**Comment by hsadia538** [comment]
> > > Still failing...
> > > what clang version do you have installed?
> > 
> > 
> > Homebrew clang-format version 15.0.2
> 
> I've shared the suggested changes by clang with you, but if you keep having issues with clang, maybe we could ask if @catenacyber knows how to approach this since he also uses a mac...

Do you have any idea regarding the clang-format.sh errors that I am facing

**Comment by hsadia538** [comment]
> > > Still failing...
> > > what clang version do you have installed?
> > 
> > 
> > Homebrew clang-format version 15.0.2
> 
> I've shared the suggested changes by clang with you, but if you keep having issues with clang, maybe we could ask if @catenacyber knows how to approach this since he also uses a mac...

Where have you shared?

**Comment by jufajardini** [comment]
> Where have you shared?

On Discord

**Comment by hsadia538** [comment]
> > Where have you shared?
> 
> On Discord

Pushed changes. PTAL

**Comment by hsadia538** [comment]
Followed by #8034

**Pull request closed without merging**
