### PR TITLE
detect/transform: Case changing transform backport to main-7.0.x

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #10035

Add the transforms for changing the case of a buffer. 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6612](https://redmine.openinfosecfoundation.org/issues/6612)

Describe changes:
- Add to_lowercase and to_uppercase transforms

Updates:
- Rebase

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17127

**Comment by jlucovsky** [comment]
> pr/1460

Will fix -- stale reference to (closed) s-v pr.

**Comment by jlucovsky** [comment]
Closing to address CI issues

**Comment by jlucovsky** [comment]
Continued in #10068

**Pull request closed without merging**
