### PR TITLE
eve/flow: add vlan and in_iface fields - v1

### PR DESCRIPTION
**Pull request by praseodym**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable) => not applicable

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2057

Describe changes:
- eve/flow: add vlan field 
- eve/flow: add in_iface field

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
not applicable

### CODE REVIEW

**Comment by victorjulien** [comment]
Related to #3494. @bolzzy could you check this, think these address different parts of the same issue.

**Comment by bolzzy** [comment]
sorry about the late reply, will look into it this tomorrow @victorjulien

**Comment by bolzzy** [comment]
@victorjulien @praseodym 
This PR fixes the missing vlan in flow and netflow output, but does not fix the missing interface in other outputs (alert, http etc) that happens because of logging a pseudopacket without iface/vlan that pr #3494 fixes.

I suggest pulling #3494 and modifying this PR so we fix all outputs :)

**Comment by praseodym** [comment]
#3494 could be improved with the vlan index that is introduced by this PR (see comment there for the specifics), so maybe it would be better if I rebase this branch onto #3494 and create a single new PR to do that in one go?

**Comment by bolzzy** [comment]
I can fix the vlan index in a new version of my branch tomorrow that you can rebase on if you'd like, but I agree on fixing this in a single PR :)

**Comment by bolzzy** [comment]
@praseodym done: https://github.com/bolzzy/suricata/tree/vlan-iface-psuedopacket-fixv3

**Comment by praseodym** [comment]
@bolzzy cheers, updated branch is in #3636

**Pull request closed without merging**
