### PR TITLE
Ci bench tool/v18

### PR DESCRIPTION
**Pull request by victorjulien**
Initial work of doing a bench tool for spm and content inspection. It's pretty rough still, but would like to merge it anyway, so we can start using it to evaluate changes.

Currently it tests spm algo's and prints csv to stdout for that.

It runs 2 sets of content inspect tests, outputs csv files for those.

I've been using this for analysis for work I'll be posting soon. Pretty much just load the csv in libreoffice and graph things.

An example of such a graph:
image

### CODE REVIEW

**Review by jasonish — CHANGES_REQUESTED** [review]
Looks OK to merge, but it should probably have a README, even if minimal for now.

**Comment by victorjulien** [comment]
> Looks OK to merge, but it should probably have a README, even if minimal for now.

Added one. Please have a look.

**Comment by jasonish** [comment]
> > Looks OK to merge, but it should probably have a README, even if minimal for now.
> 
> Added one. Please have a look.

Looks good.

**Comment by victorjulien** [comment]
replaced by #11617

**Pull request closed without merging**
