### PR TITLE
Detect negated content absent buffer 2224 v25

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2224

Describe changes:
- detect: adds `absent` keyword to match on absent buffer

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1957

https://github.com/OISF/suricata/pull/11964 rebased as requested

Still the question of transforms : do you see a use case of buffer + transform + absent keyword ?
Or should we explicitly forbid it ?
cc @jlucovsky about transforms error

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23590

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
I propose we merge this first then look at the open questions. Esp the xform issue could use some more discussion including trying to come up with examples of why it should or should not work.

**Comment by victorjulien** [comment]
Merged in #12174, thanks!

**Comment by catenacyber** [comment]
cc @Koen1999 this for merged ( cf your comment https://github.com/OISF/suricata/pull/10334#issuecomment-1980746832 )

**Pull request closed without merging**
