### PR TITLE
Codeql v4

### PR DESCRIPTION
**Pull request by catenacyber**
Link to redmine ticket:
None

Describe changes:

Updated lgtm.yml and codeql.yml so :
-Suricata will works on LGTM
-Codeql workflow for C will successfully run

Fixes 18 warnings found by CodeQL

Replaces #7299 by trying to fix compilation on windows where `fchmod` does not exist

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw1_files_sha256.
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk | | |
| .flow.memuse | 502077568 | 539921728 | 92.99% | 

Pipeline 7172

**Comment by victorjulien** [comment]
I think the commit messages need some refining. `snprintd` in one. `codeql:` prefix in a commit that updates file handling but not "codeql" (it addresses a finding by it). `detect: checks....` doesn't check anything, it fixes a type.

**Comment by victorjulien** [comment]
Also need a ticket or perhaps even several.

**Comment by catenacyber** [comment]
> Also need a ticket or perhaps even several.

Would you want a QA ticket for codeql and bug fixes (or optimization) tickets for the source changes ?

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7331

**Pull request closed without merging**
