### PR TITLE
util/landlock: check return values for ConfGet

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5539

Describe changes:
- util/landlock: check return values for ConfGet to get Coverity happy

Rebased https://github.com/OISF/suricata/pull/8443 with remaining commits

### CODE REVIEW

**Comment by victorjulien** [comment]
@regit can you review this?

**Review by regit — APPROVED** [review]
Looks good to me!

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_single_stats_chk | | |
| .tcp.ssn_from_cache | 264554 | 339543 | 128.35% |
| .tcp.ssn_from_pool | 628437 | 553448 | 88.07% |
| | SURI_TLPW2_autofp_stats_chk | | |
| .tcp.ssn_from_cache | 298547 | 372994 | 124.94% |
| .tcp.ssn_from_pool | 594444 | 519997 | 87.48% |
| | SURI_TLPW1_stats_chk | | |
| .tcp.ssn_from_cache | 63596 | 78985 | 124.2% |
| .tcp.ssn_from_pool | 139220 | 123831 | 88.95% |
| .tcp.rst | 128116 | 113459 | 88.56% |
| .app_layer.error.dns_udp.parser | 1276 | 0 | - |
| .ftp.memuse | 862 | 348 | 40.37% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 580947328 | 537533008 | 92.53% |
| .tcp.ssn_from_cache | 3644947 | 6065866 | 166.42% |
| .tcp.ssn_from_pool | 8484810 | 6063859 | 71.47% |
| .tcp.synack | 7538139 | 10045701 | 133.27% |
| .tcp.rst | 5264608 | 6724343 | 127.73% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .app_layer.error.dns_udp.parser | 28003 | 0 | - |
| .http.memuse | 16440 | 2104 | 12.8% |
| .ftp.memuse | 13827 | 11093 | 80.23% |
| | IPS_AFP_stats_chk | | |
| .tcp.segment_from_pool | 17089689 | 15752756 | 92.18% |
| | TREX_GENERIC_stats_chk | | |
| .tcp.segment_from_pool | 15728353 | 14739709 | 93.71% | 

Pipeline 12015

**Comment by victorjulien** [comment]
Merged in #8468, thanks!

**Pull request merged**
