### PR TITLE
fix double implementation of Default on FileContainer

### PR DESCRIPTION
**Pull request by linuxhunter**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by inashivb — COMMENTED** [review]
Hi @linuxhunter !
Thank you for your first contribution to our project. :)
The changes look good to me but I think we need to work a bit on the commit message. Could you please add a  prefix indicating the relevant part of code that was changed?
e.g. `rust/filecontainer: fix ..`

**Comment by linuxhunter** [comment]
Hi @inashivb !
What should I do next about this PR?

**Comment by linuxhunter** [comment]
Hi @inashivb !
What should I do next about this PR?

**Comment by inashivb** [comment]
> Hi @inashivb ! What should I do next about this PR?

Hi! Thanks for addressing the requested changes. I'm afraid the git history seems to have become a bit too long. Could you please make sure you have just one commit with your changes and no merge commits and any extras? That'll be all from me. Thanks for doing this :)

**Pull request closed without merging**
