### PR TITLE
ndpi plugin support/v5 - fuzz fix test

### PR DESCRIPTION
**Pull request by jasonish**
Rebase of https://github.com/OISF/suricata/pull/12093 with fix for fuzz code compile error.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23301

**Comment by victorjulien** [comment]
Why is this a draft?

**Comment by jasonish** [comment]
> Why is this a draft?

Test PR to see if GitHub CI passes. Don't have local setup for cifuzz.

**Comment by victorjulien** [comment]
> > Why is this a draft?
> 
> Test PR to see if GitHub CI passes. Don't have local setup for cifuzz.

It passed.

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #12117, thanks!

**Pull request closed without merging**
