### PR TITLE
Stats udp prefix 6304 v4

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6304

Describe changes:
- fix missing _udp or _tcp suffix in stats for protocols on both

#9946 without variable name shadowing

```
SV_BRANCH=pr/1546
```
https://github.com/OISF/suricata-verify/pull/1546

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
S-V PR has been updated to https://github.com/OISF/suricata-verify/pull/1546

Should I rebase this Suricata PR to match it ?

**Comment by victorjulien** [comment]
> S-V PR has been updated to [OISF/suricata-verify#1546](https://github.com/OISF/suricata-verify/pull/1546)
> 
> Should I rebase this Suricata PR to match it ?

I've restarted the actions after updating the reference here, we'll see if it passes. Both suricata and SV have been updated since, so rebase may be required.

**Review by victorjulien — CHANGES_REQUESTED** [review]
needs a rebase

**Comment by catenacyber** [comment]
> needs a rebase

Done in https://github.com/OISF/suricata/pull/10050

**Pull request closed without merging**
