### PR TITLE
detect/bytemath: Support out of order options

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #7783

The intent of this PR is to support arbitrary order options for `byte_math`. During the investigation phase, it was suggested that the parser be converted to Rust for simplification. Thus, the PCRE based parser for `byte_math` was removed and replaced with a Rust based parser. @jasonish's prototype rules parser work helped guide this PR.

The C unittests were retained and many were added to the Rust based parser.

Issue: 5077

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [5077](https://redmine.openinfosecfoundation.org/issues/5077)

Describe changes:
- Converts the PCRE based parser to Rust.
- Adds unit tests to the new Rust modules
- Removes the PCRE parser from detect-bytemath.c
- Adjusts the C source modules to refer to the Rust definitions

Updates
- Update cast of endian value.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw2_single_stats_chk | | |
| .flow.spare | 1949445 | 1835514 | 106.21% |
| | tlpw2_autofp_stats_chk | | |
| .flow.spare | 1962071 | 1812994 | 108.22% |
| .flow.memuse | 518377728 | 550537728 | 94.16% |
| | tlpw1_stats_chk | | |
| .tcp.rst | 125980 | 105279 | 119.66% |
| | tlpr1_stats_chk | | |
| .flow.memuse | 567452928 | 845888448 | 67.08% |
| .http.memuse | 16440 | 49320 | 33.33% |
| | ips_afp_stats_chk | | |
| .flow.end.state.new | 111030 | 10800 | 1028.06% |
| .flow.end.state.closed | 1978251 | 2097352 | 94.32% |
| .flow.end.tcp_state.closed | 1971209 | 2097352 | 93.99% |
| .flow.end.tcp_liberal | 358961 | 108000 | 332.37% |
| .flow.memuse | 871787968 | 1081197888 | 80.63% |
| .tcp.reassembly_gap | 1182303 | 108000 | 1094.73% |
| .app_layer.flow.http | 412110 | 434160 | 94.92% |
| .app_layer.flow.tls | 922150 | 974152 | 94.66% |
| .app_layer.flow.failed_tcp | 205548 | 218160 | 94.22% |
| .app_layer.tx.ftp | 243172 | 263520 | 92.28% |
| .app_layer.tx.smtp | 130401 | 149040 | 87.49% |
| .app_layer.tx.dcerpc_tcp | 954477 | 1101600 | 86.64% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 1390 | 5654519 | 0.02% |
| .flow.end.state.new | 6284 | 14867 | 42.27% |
| .flow.end.tcp_state.syn_sent | 7 | 183 | 3.83% |
| .flow.end.tcp_state.syn_recv | 0 | 52 | 0.0% |
| .flow.end.tcp_state.established | 54003 | 61527 | 87.77% |
| .flow.end.tcp_liberal | 81343 | 90436 | 89.95% |
| .flow.memuse | 761280448 | 709384128 | 107.32% |
| .tcp.segment_memcap_drop | 0 | 11729 | 0.0% |
| .tcp.reassembly_gap | 81349 | 114099 | 71.3% |
| .tcp.insert_data_normal_fail | 0 | 11358 | 0.0% |
| .app_layer.error.http.parser | 0 | 55 | 0.0% |
| .app_layer.error.smtp.gap | 2 | 61 | 3.28% |
| .app_layer.error.tls.gap | 54209 | 60833 | 89.11% | 

Pipeline 8853
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

**Review by catenacyber — APPROVED** [review]
Ok for me, some comments in the details :

- CI : green
- Code : Will do right now
- Commits segmentation : ok for me, I would have one commit for all the renaming in detect directory 
- Commit message : 
One commit title misses a prefix "add to doc/userguide/rules/payload-keywords.rst"
I would have squashed it ;-)

"doc/byte_math: Add byte_math differences"
Maybe precise "with snort"
- Git ID set : ok
- CLA : ok ;-)
- Doc update : good for me, Juliana was also ok I think
- Redmine ticket : ok
- Rustfmt : `rustfmt rust/src/detect/*.rs` looks good :-)
- Tests : Ok for me. I would like to see a SV test about the fix of use of multiplication in bytemath ;-)
- Dependencies added: none

**Comment by jufajardini** [comment]
> Ok for me, some comments in the details :
> 
> * CI : green
> * Code : Will do right now
> * Commits segmentation : ok for me, I would have one commit for all the renaming in detect directory
> * Commit message :
>   One commit title misses a prefix "add to doc/userguide/rules/payload-keywords.rst"
>   I would have squashed it ;-)
> 
> "doc/byte_math: Add byte_math differences" Maybe precise "with snort"
> 
> * Git ID set : ok
> * CLA : ok ;-)
> * Doc update : good for me, Juliana was also ok I think
> * Redmine ticket : ok
> * Rustfmt : `rustfmt rust/src/detect/*.rs` looks good :-)
> * Tests : Ok for me. I would like to see a SV test about the fix of use of multiplication in bytemath ;-)
> * Dependencies added: none

Indeed, docs good with me! :)

**Comment by jlucovsky** [comment]
Continued in #7802

**Pull request closed without merging**
