### PR TITLE
eve: revert ethernet addresses when needed

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6405

Describe changes:
- eve: revert ethernet addresses when needed

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1872

https://github.com/OISF/suricata/pull/11197 with compiler warning fix

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20896

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11214, thanks!

**Comment by vzmsk** [comment]
@victorjulien hello!
I need help. How to apply this fix.

**Comment by catenacyber** [comment]
This patch is available since Suricata 7.0.6

**Pull request closed without merging**
