### PR TITLE
Ci bench tool/v17

### PR DESCRIPTION
**Pull request by victorjulien**
An example of the graph based on the csv
image

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21996

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21998

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21999

**Comment by victorjulien** [comment]
replaced by #11614

**Pull request closed without merging**
