### PR TITLE
Http2 master6 v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4067

Describe changes:
- Cherry-pick all latest HTTP2 commits from master to master-6.0.x, except the range one

### CODE REVIEW

**Comment by victorjulien** [comment]
```
===> tcp-protodetect-bailout: FAILED: got exit code -6, expected 0
```

**Comment by victorjulien** [comment]
Are there SV tests that need to be adjusted to actually execute the backported code?

**Comment by suricata-qa** [comment]
WARNING:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.mgr.flows_timeout_inuse | 0 | 1248 | 0.0% |
| .flow.spare | 6215339 | 6942743 | 89.52% |
| .flow.memuse | 1156123648 | 1295845568 | 89.22% |

Pipeline 4457

**Comment by catenacyber** [comment]
I also get the fail S-V test with master-6.0.x

Should we change the S-V test to have min-version 7 ?

One commit fixing it is f77b027ada0436855109f422bfa4d491dba846c7 and also 7a114e506a27fcb2a3b5ed28b1c10fe100cf78c6 which are quite complex changes

And this is just a debug assertion...

**Comment by victorjulien** [comment]
> I also get the fail S-V test with master-6.0.x
> 
> Should we change the S-V test to have min-version 7 ?
> 
> One commit fixing it is [f77b027](https://github.com/OISF/suricata/commit/f77b027ada0436855109f422bfa4d491dba846c7) and also [7a114e5](https://github.com/OISF/suricata/commit/7a114e506a27fcb2a3b5ed28b1c10fe100cf78c6) which are quite complex changes
> 
> And this is just a debug assertion...

Pretty sure those commits are backported to 6...

**Comment by victorjulien** [comment]
Maybe these were merged after this PR though.

**Comment by catenacyber** [comment]
> Maybe these were merged after this PR though.

Indeed, they were merged in between...

Replaced by https://github.com/OISF/suricata/pull/6453

**Pull request closed without merging**
