### PR TITLE
Fix compiler warnings with Rust nightly

### PR DESCRIPTION
**Pull request by satta**
- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Fix warnings with Rust nightly (`rustc 1.55.0-nightly (406d4a9cc 2021-06-21)`). These are simple changes relating to:
  - variables only used in debug output macros, which may be removed before compiling, making these variables unused, and
  - unused borrows in what should just be function calls.

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Looks good to me

Some part is duplicate with #6208

**Review by jasonish — APPROVED** [review]

**Comment by satta** [comment]
Should be done via #6222

**Comment by satta** [comment]
Or do we want to keep this open since #6222 was only merged into the 6.x line?

**Comment by catenacyber** [comment]
I guess so

**Comment by victorjulien** [comment]
Merged in #6242, thanks!

**Pull request closed without merging**
