### PR TITLE
detect: header_lowercase transform

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6290

Describe changes:
- detect: header_lowercase transform for HTTP/1 HTTP/2 normalization

```
SV_BRANCH=pr/1458
```

#9758 with typo in doc fixed

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 199 | 183 | 91.96% | 

Pipeline 16425

**Comment by victorjulien** [comment]
What happens with content that has upper case chars?

**Review by victorjulien — CHANGES_REQUESTED** [review]
Needs a rebase, thanks

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/9837

**Pull request closed without merging**
