### PR TITLE
detect-itype.c: Convert unittests to new FAIL/PASS API

### PR DESCRIPTION
**Pull request by hsadia538**
- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4049) ticket:

Describe changes:

- Update detect-itype unit tests to FAIL/PASS APIs

### CODE REVIEW

**Comment by hsadia538** [comment]
`DetectITypeMatchTest01` Seemed more complicated than a simple null/not null scenario. Seems like it should be converted to Suricata verify test. Should I do so?

**Comment by inashivb** [comment]
> `DetectITypeMatchTest01` Seemed more complicated than a simple null/not null scenario. Seems like it should be converted to Suricata verify test. Should I do so?

Great job spotting. 😉 
Yes, please. If there isn't a ticket for that, perhaps you could create one and assign to yourself.

**Review by inashivb — CHANGES_REQUESTED** [review]
Looking fine overall. We seem to have broken a unittest with this conversion. Could you please look into that? Thank you! :)

**Comment by hsadia538** [comment]
> > `DetectITypeMatchTest01` Seemed more complicated than a simple null/not null scenario. Seems like it should be converted to Suricata verify test. Should I do so?
> 
> Great job spotting. 😉 Yes, please. If there isn't a ticket for that, perhaps you could create one and assign to yourself.

Here is the link. Please update incase I missed any field https://redmine.openinfosecfoundation.org/issues/5590

**Comment by hsadia538** [comment]
Followed by #8060

**Comment by jufajardini** [comment]
> > > `DetectITypeMatchTest01` Seemed more complicated than a simple null/not null scenario. Seems like it should be converted to Suricata verify test. Should I do so?
> > 
> > 
> > Great job spotting. wink Yes, please. If there isn't a ticket for that, perhaps you could create one and assign to yourself.
> 
> Here is the link. Please update incase I missed any field https://redmine.openinfosecfoundation.org/issues/5590

This is good, thanks!
(A small note - for Suricata-verify tickets, we usually choose target version `QA` :) )

**Pull request closed without merging**
