### PR TITLE
profiling: allow absolute paths

### PR DESCRIPTION
**Pull request by victorjulien**
Ticket #6490.

https://redmine.openinfosecfoundation.org/issues/6490

@ct0br0 can you give this a test?

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21449

**Comment by victorjulien** [comment]
@ct0br0 can you add your review comments here instead of the ticket?

Anyway, updated the PR. Can you try again?

**Comment by ct0br0** [comment]
When reading off an interface the rule profiling file does go to `filename: /tmp/woohoo.txt`. But when reading a PCAP  is not put in the absolute path, just your CWD. Think this is different behavior though. lgtm

**Comment by victorjulien** [comment]
replaced by #11477

**Pull request closed without merging**
