### PR TITLE
Http2 noalloc header compare 5454 backport6 v3

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
Backport of https://redmine.openinfosecfoundation.org/issues/5454

Describe changes:
- http2: remove `to_vec` in comparisons (no need to alloc)

Modifies #7805 modifying cherry-pick for commit b86beb9b68807e371f7af1ad6a1f789fdd5f7209 to get MSRV to work

#7808 with right target branch

### CODE REVIEW

**Comment by catenacyber** [comment]
CIFuzz is only PCRE1 bug now :-)

**Comment by victorjulien** [comment]
Some of the commits had bad cherry-pick lines, so can you rebase this? I took the other commits in #7828

**Comment by catenacyber** [comment]
> Some of the commits had bad cherry-pick lines, so can you rebase this? I took the other commits in #7828

What are bad cherry-pick lines ?
How can I test it ?

Replaced by https://github.com/OISF/suricata/pull/7834

**Comment by victorjulien** [comment]
> > Some of the commits had bad cherry-pick lines, so can you rebase this? I took the other commits in #7828
> 
> What are bad cherry-pick lines ? How can I test it ?

Cherry-pick line in commit that references a commit not in master. I've added https://github.com/OISF/suricata/commit/275975c699b2d0cc0e48066cf2b01ad3db1226f6 to catch these.

**Pull request closed without merging**
