### PR TITLE
source-pcap:set PktAcqBreakLoop as pcap_breakloop v2

### PR DESCRIPTION
**Pull request by jingleyang**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:https://redmine.openinfosecfoundation.org/issues/2751

Describe changes:
-  to set PktAcqBreakLoop as pcap_breakloop to quit explicitly, instead of waiting for timeout.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by jingleyang** [comment]
Thank you for your code review.
And Happy Christmas!

**Comment by victorjulien** [comment]
Hi, I've sent you an email on this PR. Could you have a look? Thanks!

**Comment by jingleyang** [comment]
> Hi, I've sent you an email on this PR. Could you have a look? Thanks!

hi Victor,
It's OK. Feel free to make the update.
Thanks.

**Comment by victorjulien** [comment]
Merged as part of #3625, thanks!

**Pull request closed without merging**
