### PR TITLE
reorg: modular file reorganization of C source code - v2

### PR DESCRIPTION
**Pull request by jasonish**
Bring forward old work of re-organizing the C code into a modular layout as a
point of discussion.

This PR just moves the DNP3 related code into an "app-layer/dnp3" module that
contains the parser, the logging and detection code for DNP3.

The previous PR also renamed the files inside the module. For example
"detect-dnp3.c" would become "app-layer/dnp3/detect.c". I have not done that
rename here, but it would mirror our Rust side more.

Moving C files triggers our clang-format CI check to fail, so these have been
reformatted as well.

S-V will also need careful checks for any tests that depend on filenames
existing.

Previous PR: https://github.com/OISF/suricata/pull/4758

### CODE REVIEW

**Comment by victorjulien** [comment]
> The previous PR also renamed the files inside the module. For example
> "detect-dnp3.c" would become "app-layer/dnp3/detect.c". I have not done that
> rename here, but it would mirror our Rust side more.

I would be in favor of this, probably in a single step.

**Comment by jasonish** [comment]
Moved `ike` and `modbus`, renaming the files. This was scripted.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16854

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/9957.

**Pull request closed without merging**
