### PR TITLE
 app-layer events: consistently use uint8_t/u8 as the event id - v3

### PR DESCRIPTION
**Pull request by jasonish**
Replaces https://github.com/OISF/suricata/pull/12010.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23170

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
> misc: remove unneeded headers
Remove unneeded headers from worked on in previous commits, just
simple ones flagged by clangd.

Interesting. Can we add this clangd check in CI ?

**Comment by catenacyber** [comment]
Why did we have no warnings about mixing integer types ? 
https://redmine.openinfosecfoundation.org/issues/6632 ?

**Comment by jasonish** [comment]
> Interesting. Can we add this clangd check in CI ?

No idea how, this is an editor feature as far as I'm aware.

**Comment by victorjulien** [comment]
Merged in #12026, thanks!

**Pull request closed without merging**
