### PR TITLE
Stats/v5

### PR DESCRIPTION
**Pull request by victorjulien**
Various optimizations and cleanups.

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 14104

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 14107

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 14108

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 526058088 | 624566000 | 118.73% | 

Pipeline 14110

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 526058088 | 596973176 | 113.48% | 

Pipeline 14113

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 14115

**Comment by victorjulien** [comment]
Merged in #8945

**Pull request closed without merging**
