### PR TITLE
Detect pseudo v5 pkt inspect engines inline v6

### PR DESCRIPTION
**Pull request by catenacyber**
Ticket:
https://redmine.openinfosecfoundation.org/issues/6291
https://redmine.openinfosecfoundation.org/issues/6728

Based on https://github.com/OISF/suricata/pull/11274 + https://github.com/OISF/suricata/pull/10202

@coledishington would you give it a try ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21086

**Comment by catenacyber** [comment]
This PR requires rules to add the `prefilter` keyword after the decode-event one

With this, I go from 14 seconds to 7 seconds with  rules/decoder-events.rules on a random pcap with 487089 packets (where most packets do not have events)

So, need to
- optimize further with prefiltering not checking for the specific event, but just checking there is an event (so the pre filter is the same for all decode event rules)
- make a rule automatically use its pre filter when there is one ? Or update the rules to add it
- add this to `app-layer-event`

**Comment by coledishington** [comment]
@catenacyber Thanks for linking me in this patch. I have been trying to test it but I am having some trouble with compiling later versions of Suricata (due to libsuricata_rust.a having a mix of Machine code instead of just my target arch).

I will try again later this week.

**Comment by catenacyber** [comment]
Do you need to set `CARGO_BUILD_TARGET` env variable ? to ` mips64-unknown-linux` or alike

**Comment by catenacyber** [comment]
@coledishington I rebased and improved on this PR in https://github.com/OISF/suricata/pull/11328

**Comment by coledishington** [comment]
> Do you need to set `CARGO_BUILD_TARGET` env variable ? to ` mips64-unknown-linux` or alike

I have the CARGO_BUILD_TARGET set (to mips64-unknown-linux-gnuabi64). Specifically, I am having problems with the .o files from the cargo package suricata-lua-sys, which doesn't appear to be picking up my cross compilation flags. Thanks

**Comment by catenacyber** [comment]
@jasonish would you know how to solve this lua + rust problem ?

**Comment by jasonish** [comment]
> @jasonish would you know how to solve this lua + rust problem ?

No, but its more a cross compiling problem and I've never cross compiled Suricata. But it crops up from time to time. Some how to, or even a CI job would be handy if someone was willing to put one together.

**Pull request closed without merging**
