### PR TITLE
nsh: Parsing of Network Services Header and payload

### PR DESCRIPTION
**Pull request by carlgsmith**
Support for EtherType 0x894F and basic header

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3292

Describe changes:
- Add basic support for parsing NSH headers and locating encapsulated headers
- Tested on live network with NSH traffic
- https://github.com/the-tcpdump-group/tcpdump/raw/master/tests/nsh.pcap

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

suricata-verify-pr: 307
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by jlucovsky** [comment]
@carlgsmith I made an edit so your suricata-verify PR would be used -- `s/#suricata-verify-pr: 302/suricata-verify-pr: 302`

**Comment by carlgsmith** [comment]
> @carlgsmith I made an edit so your suricata-verify PR would be used -- `s/#suricata-verify-pr: 302/suricata-verify-pr: 302`

oops - thanks

**Review by catenacyber — APPROVED** [review]
Looks good to me

**Comment by victorjulien** [comment]
Merged in #5693, thanks!

**Pull request closed without merging**
