### PR TITLE
Draft changes for issue 4145

### PR DESCRIPTION
**Pull request by jlucovsky**
This commit is *draft* and demonstrates an approach to commonlizing registrations for file data.

This compiles but has a runtime fault (both s-v and unittests) and the single commit will be replaced by a proper commit series if it moves forward.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 48976 | 0.01 | 

Pipeline 11130

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 11136

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104010 | 81.11% | 

Pipeline 11142

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_stats_chk.
  

Pipeline 11142

**Comment by victorjulien** [comment]
replaced by #8785

**Pull request closed without merging**
