### PR TITLE
Detect negated content absent buffer 2224 v15

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2224

Describe changes:
- detect: negated content matches on absent buffer
- detect: adds `absent` keyword to match on absent buffer

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1535

#11186 with SV fix (including file hash keywords for match_on_null = false)

Are we sure this is the behavior we want for files ?
With this PR, negated content matches if there is no files...
But there may be SMB transactions which are not file transactions, so they will match on such...

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 20865

**Comment by ct0br0** [comment]
I assume this is expected. PR finds more for a SID than current does.

**Comment by catenacyber** [comment]
> I assume this is expected. PR finds more for a (single) SID than current does.

It is possible, but I would like to get more details about it privately

**Comment by catenacyber** [comment]
Thanks @ct0br0 

PR seems to behave as expected and create more alerts indeed, for instance one for 74.63.195.237_80-192.168.87.10_1043.pcap where there is indeed no `http.request_body`

**Comment by victorjulien** [comment]
This issue of this logic only working for some buffer types, but not for others doesn't sit well with me.

We have a couple of buffer types:
1. low level buffers, like p->payload (raw content), stream, packet headers (e.g. udp.hdr), etc. For none of these we want to change the meaning of negation.

A rule like `alert tcp ... content:!"ABC";` should not match on a packet w/o payload.

2. general app buffers, like `http.uri`. Here things are mixed. `tls.sni` is an optional field. But I would not expect `alert tls ... tls.sni; content:!"suricata";` to match on traffic that has no SNI.

The desired use case I think it's around things like user agents in HTTP, where a `http.user_agent; content:!"ABC";` should match also if the user agent is omitted from the traffic.

3. file buffers. A rule like `alert smb ... file.data; content:!"MZ";` should not match on a non-file TX.

My conclusion is that just overloading the existing negation support to get this new meaning isn't going to work. We need to add some other syntax to make this a clear and explicit rule writer decision.

E.g. something like `http.user_agent; content:!"ABC"; or_absent;` This should then be supported for all content inspection types above too.

Not set on the syntax above, it serves more as a start of a discussion.

**Comment by victorjulien** [comment]
`http.user_agent; absent_or; pcre:"!/abc/g";`

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata/pull/11295

**Pull request closed without merging**
