### PR TITLE
detect/analyzer: add more details for the tcp ack keyword - v3

### PR DESCRIPTION
**Pull request by 0xEniola**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6354

Previous PR: https://github.com/OISF/suricata/pull/9608

Describe changes:
- Modified the code to properly handle the DETECT_ACK case; corrected the variable used to represent the Acknowledgement number.

Output:

```
{
  "raw": "alert tcp any any -> any any (msg:\"Testing ack\"; ack:782; sid:1;)",
  "id": 1,
  "gid": 1,
  "rev": 0,
  "msg": "Testing ack",
  "app_proto": "unknown",
  "requirements": [],
  "type": "pkt",
  "flags": [
    "src_any",
    "dst_any",
    "sp_any",
    "dp_any",
    "need_packet",
    "toserver",
    "toclient"
  ],
  "pkt_engines" : [
    {
      "name": "packet",
      "is_mpm": false
    }
  ],
  "frame_engines": [],
  "lists": {
    "packet": {
      "matches": [
        {
          "name": "tcp.ack",
          "ack": {
            "number": 782
          }
        }
      ]
    }
   }
}
```

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1430

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Thanks, @0xEniola ! Looking good, mostly. :)
Could you please address CI failures and submit a new PR?

**Comment by inashivb** [comment]
Please note that you're first supposed to create the s-v PR and then Suricata PR with a reference to s-v PR, if you edit it later on, it won't be picked up by the CI as it is picked in the beginning and cached for the distro runs.

**Review by jufajardini — CHANGES_REQUESTED** [review]
I think you forgot to add the header file in this version of the PR :P

As a good practice, remember to build your code and run the sv tests locally before submitting PRs, this should help you catch things like this one.

**Comment by 0xEniola** [comment]
> Please note that you're first supposed to create the s-v PR and then Suricata PR with a reference to s-v PR, if you edit it later on, it won't be picked up by the CI as it is picked in the beginning and cached for the distro runs.

I'm just seeing this, and I already created a new PR 😔🤦🏿‍♂️.

**Comment by 0xEniola** [comment]
> I think you forgot to add the header file in this version of the PR :P
> 
> As a good practice, remember to build your code and run the sv tests locally before submitting PRs, this should help you catch things like this one.

I'll make sure to keep that in mind from now on.

Thank you very much for the feedback 😊.

**Comment by jufajardini** [comment]
Followed by: https://github.com/OISF/suricata/pull/9658

**Pull request closed without merging**
