### PR TITLE
parse: dns probe_tcp handles incomplete data

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None yet

Describe changes:
- Fixes DNS TCP parser against packet split evasion after gap

Problem happens after gap because of recovery code using `probe_tcp` which does not handle incomplete data
https://github.com/OISF/suricata/blob/master/rust/src/dns/dns.rs#L515

Problem found while running suricata-verify test `dns-tcp-ts-gap` against Suricata compiled with this patch
```
diff --git a/src/app-layer.c b/src/app-layer.c
index b614f2712..0149d6b4f 100644
--- a/src/app-layer.c
+++ b/src/app-layer.c
@@ -658,8 +658,15 @@ int AppLayerHandleTCPData(ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx,
          * a start msg should have gotten us one */
         if (f->alproto != ALPROTO_UNKNOWN) {
             PACKET_PROFILING_APP_START(app_tctx, f->alproto);
+#ifndef LOLSPLIT
+            for (size_t i = 0; i < data_len; i++) {
+                r = AppLayerParserParse(tv, app_tctx->alp_tctx, f, f->alproto,
+                                        flags, data+i, 1);
+            }
+#else
             r = AppLayerParserParse(tv, app_tctx->alp_tctx, f, f->alproto,
                                     flags, data, data_len);
+#endif
             PACKET_PROFILING_APP_END(app_tctx, f->alproto);
             if (r >= 0) {
                 (*stream)->app_progress_rel += data_len;
```

This PR fixes it but I am not sure it is right.
So, this is open to discussion

Similar to #4645

### CODE REVIEW

**Comment by catenacyber** [comment]
Maybe we should wait for #4677 to get a better fix

**Comment by victorjulien** [comment]
> Maybe we should wait for #4677 to get a better fix

I don't know if #4677 is really related. I think the issue here is that the DNS parser doesn't try hard enough to find the next DNS record in the stream.

**Comment by catenacyber** [comment]
> I don't know if #4677 is really related. I think the issue here is that the DNS parser doesn't try hard enough to find the next DNS record in the stream.

Indeed, that is the issue.
But to find the next DNS record in the stream, the parser must have enough data.
And with #4677, it can specify how much data is needed

**Comment by jasonish** [comment]
> > I don't know if #4677 is really related. I think the issue here is that the DNS parser doesn't try hard enough to find the next DNS record in the stream.
> 
> Indeed, that is the issue.
> But to find the next DNS record in the stream, the parser must have enough data.
> And with #4677, it can specify how much data is needed

So the current approach to finding the next record is rather weak, it hopes that it is called again with the start of record, rather than scanning for potential start of records as that could get very expensive.

**Comment by victorjulien** [comment]
Merged in #4788, with a git commit message rewrite. Thanks Philippe.

**Pull request closed without merging**
