### PR TITLE
detect: remove flash decompression feature

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6184

Describe changes:
- remove flash decompression feature

#9876 with warning if config value is still there and true

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 16704

**Comment by victorjulien** [comment]
```
6 major deviations in alert counts
2827799:2
 missing in test alerts
2811659:2
 missing in test alerts
2015704:7
 missing in test alerts
2827800:2
 missing in base alerts
2816808:4
 missing in base alerts
2811657:2
 missing in base alerts
```
Wonder if we need to reconsider if this sigs still depend on it. cc @jmtaylor90

**Comment by jmtaylor90** [comment]
> ```
> 6 major deviations in alert counts
> 2827799:2
>  missing in test alerts
> 2811659:2
>  missing in test alerts
> 2015704:7
>  missing in test alerts
> 2827800:2
>  missing in base alerts
> 2816808:4
>  missing in base alerts
> 2811657:2
>  missing in base alerts
> ```
> 
> Wonder if we need to reconsider if these sigs still depend on it. cc @jmtaylor90

We reviewed the signatures and they will be retired/disabled in todays release. Thanks for the tag!

**Comment by catenacyber** [comment]
> We reviewed the signatures and they will be retired/disabled in todays release. Thanks for the tag!

@ct0br0 will you do a QA rebaseline with the new signature base (without these deprecated ones) ?

**Comment by victorjulien** [comment]
@jmtaylor90 any general opinions on removing the flash decompression support from the rule writing perspective?

**Comment by ozuriexv** [comment]
@victorjulien my only counter argument for removing this is that Flash is technically still supported in some areas of the world and I wouldn't put it past some orgs to have developed a workaround to continue using Flash for whatever reason they decided to come up with.  Basically I'm saying it'd be nice to keep 'just in case'.  Is there any justification on your side that warrants the removal of a feature that may still see use at some point?

**Comment by catenacyber** [comment]
> Is there any justification on your side that warrants the removal of a feature that may still see use at some point?

Security and maintainability concerns on my side

**Comment by jmtaylor90** [comment]
> @jmtaylor90 any general opinions on removing the flash decompression support from the rule writing perspective?

From our perspective, after talking with the team, we would generally prefer keeping the feature for a time. As noted above we do have rules in the set available for use though currently disabled that require flash decompression. And as @ozuriexv mentioned some areas where suri could be deployed would/could still see flash traffic.

**Comment by victorjulien** [comment]
Thanks for the feedback @jmtaylor90 and @ozuriexv , I've update the ticket(s) to reflect that we'll wait at least another cycle, but we'll reevaluate when shaping the 9 roadmap.

https://redmine.openinfosecfoundation.org/issues/6179

So closing this PR.

**Pull request closed without merging**
