### PR TITLE
rust: cbindgen and 2018 edition - v20

### PR DESCRIPTION
**Pull request by jasonish**
Builds on cbindgen PR #4448, but also migrate Rust code
to 2018 edition.

Previous PR: https://github.com/OISF/suricata/pull/4468

Changes from last PR:
- If cbindgen is available, pretend as if the headers
  are not bundled. This satisfies distcheck as when
  cbindgen is available, the headers get regenerated
  which distcheck does not like.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3308

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- Fails: requires cbindgen

### CODE REVIEW

**Comment by victorjulien** [comment]
Breaks my windows builders:
<pre>
6379 make[5]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp/htp'
6380 make[4]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp/htp'
6381 Making all in test
6382 make[4]: Entering directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp/test'
6383 make[4]: Nothing to be done for 'all'.
6384 make[4]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp/test'
6385 Making all in docs
6386 make[4]: Entering directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp/docs'
6387 make[4]: Nothing to be done for 'all'.
6388 make[4]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp/docs'
6389 make[4]: Entering directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp'
6390 make[4]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp'
6391 make[3]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp'
6392 make[2]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/libhtp'
6393 Making all in rust
6394 make[2]: Entering directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/rust'
6395 CARGO_HOME="/home/SYSTEM/.cargo"  /mingw32/bin/cargo \
6396 	generate-lockfile
6397 error: failed to load source for a dependency on `bitflags`
6398 Caused by:
6399   Unable to update registry `https://github.com/rust-lang/crates.io-index`
6400 Caused by:
6401   failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`
6402 Caused by:
6403   failed to read root of directory source: C:\c\Gitlab-Runner\builds\hNRUpEPe\0\inliniac\suricata-ci\suricata\rust\vendor
6404 Caused by:
6405   Het systeem kan het opgegeven pad niet vinden. (os error 3)
6406 make[2]: *** [Makefile:557: /c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/rust/Cargo.lock] Error 101
6407 make[2]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata/rust'
6408 make[1]: *** [Makefile:500: all-recursive] Error 1
6409 make[1]: Leaving directory '/c/Gitlab-Runner/builds/hNRUpEPe/0/inliniac/suricata-ci/suricata'
6410 make: *** [Makefile:426: all] Error 2
6413 ERROR: Job failed: exit status 2
</pre>

Note `C:\c\Gitlab-Runner\builds\hNRUpEPe\0\inliniac\suricata-ci\suricata\rust\vendor`.

**Comment by jasonish** [comment]
Is this build from a distribution archive? Is it failing during a simple ./configure && make, or is this part of a distcheck..

**Comment by jasonish** [comment]
I also think this is more from some distcheck and out of tree build fixes (that are also an issue in master), rather than cbindgen.  I think its best if I break cbindgen out from those fixes.

**Comment by victorjulien** [comment]
> Is this build from a distribution archive? Is it failing during a simple ./configure && make, or is this part of a distcheck..

Yeah it is failing during `./configure && make`.

**Comment by victorjulien** [comment]
> I also think this is more from some distcheck and out of tree build fixes (that are also an issue in master), rather than cbindgen. I think its best if I break cbindgen out from those fixes.

That would be helpful, yeah.

**Comment by jasonish** [comment]
Continue at https://github.com/OISF/suricata/pull/4482.

**Pull request closed without merging**
