### PR TITLE
Smtp server detection 1125 v14

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1125 preliminary work

Describe changes:
- protocoldetect: use stricter max depth
- pop3: add detection

Modifies #8512 by only taking some commits

Draft : waiting for QA

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113181 | 145067 | 128.17% |
| .app_layer.tx.ftp | 646 | 187 | 28.95% |
| .app_layer.error.ftp.gap | 2 | 0 | - |
| .app_layer.error.ftp.parser | 2 | 0 | - |
| .ftp.memuse | 348 | 3 | 0.86% |
| | IPS_AFP_stats_chk | | |
| .app_layer.flow.ftp | 33480 | 1080 | 3.23% |
| .app_layer.tx.ftp | 131760 | 2160 | 1.64% |
| .app_layer.error.ftp.parser | 32400 | 0 | - |
| | TREX_GENERIC_stats_chk | | |
| .app_layer.flow.ftp | 18444 | 0 | - |
| .app_layer.tx.ftp | 73776 | 0 | - |
| .app_layer.error.ftp.parser | 18444 | 0 | - | 

Pipeline 13059

**Comment by catenacyber** [comment]
@ct0br0 how can we confirm that the QA ftp changes are related to in fact pop3 ?

**Comment by ct0br0** [comment]
After taking a look at TLPW1 it looks like POP3 counters aren't incremented at all?

```
tcpdump -nr tlpw1_smtp_pop3.pcap "(port 110 or port 995)" | wc -l
reading from file tlpw1_smtp_pop3.pcap, link-type EN10MB (Ethernet), snapshot length 262144
201521
```

I'll send you a link with ftp+data/email pcaps.

**Comment by catenacyber** [comment]
Thanks Corey, continuing in https://github.com/OISF/suricata/pull/8804

**Pull request closed without merging**
