### PR TITLE
modbus: move parser from c to rust

### PR DESCRIPTION
**Pull request by cccs-sadugas**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- [3957](https://redmine.openinfosecfoundation.org/issues/3957)

Describe changes:
- Moves the C parsing logic into a rust module and removes unused C files.
- Moves the modbus detection keyword to a rust module.
- Adds and documents eve json logging, which did not seem to exist previously.
- Uses [sawp-modbus](https://crates.io/crates/sawp-modbus), our new modbus parser for integration in suricata and other projects.

Example of eve log for modbus alert:
```json
{
    "timestamp": "2004-08-26T12:12:19.148970+0000",
    "flow_id": 337987411284003,
    "pcap_cnt": 53,
    "event_type": "alert",
    "src_ip": "10.0.0.9",
    "src_port": 3082,
    "dest_ip": "10.0.0.3",
    "dest_port": 502,
    "proto": "TCP",
    "tx_id": 0,
    "alert": {
        "action": "allowed",
        "gid": 1,
        "signature_id": 1,
        "rev": 1,
        "signature": "Modbus function number test",
        "category": "",
        "severity": 3
    },
    "modbus": {
        "id": 1,
        "request": {
            "transaction_id": 1,
            "protocol_id": 0,
            "unit_id": 10,
            "function_raw": 1,
            "function_code": "RdCoils",
            "access_type": "READ | COILS",
            "category": "PUBLIC_ASSIGNED",
            "error_flags": "NONE",
            "read": {
                "address": 0,
                "quantity": 1
            }
        },
        "response": {
            "transaction_id": 1,
            "protocol_id": 0,
            "unit_id": 10,
            "function_raw": 1,
            "function_code": "RdCoils",
            "access_type": "READ | COILS",
            "category": "PUBLIC_ASSIGNED",
            "error_flags": "NONE",
            "read": {
                "data": "\u0000"
            }
        }
    },
    "app_proto": "modbus",
    "flow": {
        "pkts_toserver": 4,
        "pkts_toclient": 2,
        "bytes_toserver": 248,
        "bytes_toclient": 126,
        "start": "2004-08-26T12:12:06.102435+0000"
    }
}
```

suricata-verify-pr: 411

### CODE REVIEW

**Comment by victorjulien** [comment]
For the CI to pick up the SV PR just specify the number
```
suricata-verify-pr: NNN
```

**Comment by victorjulien** [comment]
Formatting can be fixed with `git rebase master -x 'git clang-format HEAD~'`.

The CIFuzz check found a real issue it seems, a incorrect use of the app-layer incomplete result. @catenacyber are you able to point to docs on how to reproduce this CIFuzz result?

**Comment by victorjulien** [comment]
Reviewing the new dependencies is going to take some time. Can you indicate the MSRV? The master branch is at 1.41.1 currently (Debian version).

**Comment by victorjulien** [comment]
This may be a good source for a few more tests https://github.com/bro/bro/tree/master/testing/btest/Traces/modbus

**Comment by cccs-sadugas** [comment]
Thanks for the quick review. We will look into these issues and post an updated PR.

**Comment by catenacyber** [comment]
> The CIFuzz check found a real issue it seems, a incorrect use of the app-layer incomplete result. @catenacyber are you able to point to docs on how to reproduce this CIFuzz result?

You should download the artifact create by CIFuzz cf https://google.github.io/oss-fuzz/getting-started/continuous-integration/#understanding-results
Then run it against the fuzz target built as described in src/tests/fuzz/README (in Suricata)

**Pull request closed without merging**
