### PR TITLE
detect: adds flow.age keyword

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5536

Describe changes:
- detect: adds flow.age keyword

I should create a meta ticket to list all the fields logged as integers which should have their detection keyword

Replaces #7848 with review taken into account (doc rephrase)

suricata-verify-pr: 933
https://github.com/OISF/suricata-verify/pull/933
libhtp-pr: 366

### CODE REVIEW

**Comment by victorjulien** [comment]
Still needs an SV test

**Comment by catenacyber** [comment]
> Still needs an SV test

Done as https://github.com/OISF/suricata-verify/pull/933

**Review by jufajardini — APPROVED** [review]
Doc's good to me :)

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .tcp.rst | 103033 | 126176 | 122.46% |
| .app_layer.error.http.parser | 64 | 47 | 73.44% |
| | tlpr1_stats_chk | | |
| .app_layer.error.http.parser | 1548 | 1103 | 71.25% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 0 | 208827 | - |
| .flow.end.state.new | 6272 | 7515 | 119.82% |
| .flow.end.tcp_state.syn_sent | 0 | 353 | - |
| .flow.end.tcp_state.syn_recv | 0 | 6 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 62 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 19 | - |
| .flow.end.tcp_state.time_wait | 0 | 35 | - |
| .flow.end.tcp_state.last_ack | 0 | 17 | - |
| .flow.end.tcp_state.close_wait | 0 | 82 | - |
| .tcp.reassembly_gap | 80952 | 104742 | 129.39% |
| .tcp.overlap | 0 | 2 | - |
| .app_layer.error.http.parser | 0 | 29 | - |
| .app_layer.error.ftp.gap | 0 | 3 | - |
| .app_layer.error.smtp.gap | 0 | 39 | - |
| .app_layer.error.tls.gap | 53852 | 60376 | 112.11% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 12 | - | 

Pipeline 9202

**Comment by catenacyber** [comment]
Waits for CI fix cf https://github.com/OISF/suricata/pull/7871

**Comment by victorjulien** [comment]
Merged in #7884, thanks!

**Pull request closed without merging**
