### PR TITLE
detect-detection: Convert unittests to new FAIL/PASS API

### PR DESCRIPTION
**Pull request by hsadia538**
- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5741) ticket:

Previous PR: https://github.com/OISF/suricata/pull/8278

Describe changes:

- Remove accidental comments
- Remove `retval` from the test function documentation block.

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Looks good to me, thanks! :D

**Comment by jufajardini** [comment]
Nit for other PRs: don't forget to add the redmine link to the ticket ;)

**Comment by hsadia538** [comment]
> Nit for other PRs: don't forget to add the redmine link to the ticket ;)

You mean in the description?

**Comment by jufajardini** [comment]
> > Nit for other PRs: don't forget to add the redmine link to the ticket ;)
> 
> You mean in the description?

Yes ^^

**Comment by hsadia538** [comment]
> > > Nit for other PRs: don't forget to add the redmine link to the ticket ;)
> > 
> > 
> > You mean in the description?
> 
> Yes ^^

Its there as an embedded link. That doesn't work?

**Comment by jufajardini** [comment]
> > > > Nit for other PRs: don't forget to add the redmine link to the ticket ;)
> > > 
> > > 
> > > You mean in the description?
> > 
> > 
> > Yes ^^
> 
> Its there as an embedded link. That doesn't work?

When I check, it shows the generic link, from my end, that's why I mentioned it...
To answer the other question, pasting the link directly reduces friction - which is generally good :)

**Comment by hsadia538** [comment]
> When I check, it shows the generic link, from my end, that's why I mentioned it... To answer the other question, pasting the link directly reduces friction - which is generally good :)

I have updated it

**Comment by victorjulien** [comment]
Merged in #8288, thanks!

**Pull request closed without merging**
