### PR TITLE
detect-icmp-id: convert unittests to FAIL/PASS APIs

### PR DESCRIPTION
**Pull request by AkakiAlice**
Task: #4042

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4042

Describe changes:
- Update detect-icmp-id to use FAIL/PASS API

### CODE REVIEW

**Comment by AkakiAlice** [comment]
I see the tests ``DetectIcmpIdMatchTest01`` and ``DetectIcmpIdMatchTest02`` present in this file as good candidates to be converted to a Suricata-Verify tests. May I create a task?

**Review by jufajardini — APPROVED** [review]
Looks good to me!

If you do work on the task of removing the unittests that shall be converted to SV tests, could you please also update the copyright year for this file? :) Thanks!

**Comment by AkakiAlice** [comment]
> If you do work on the task of removing the unittests that shall be converted to SV tests, could you please also update the copyright year for this file? :) Thanks!
Sure!

**Review by jasonish — APPROVED** [review]
Looks good.

**Comment by victorjulien** [comment]
Merged in #8113, thanks!

**Pull request closed without merging**
