### PR TITLE
Next/60x/backports/v6

### PR DESCRIPTION
**Pull request by catenacyber**
Backports for 6:
#6325 
#6310
#6332
various other backports

Plus #6250

#6347 using `-x` in cherry-picks

suricata-verify-pr: 530

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.mgr.rows_maxlen | 539 | 364 | 148.08% |
| .flow.mgr.flows_timeout_inuse | 0 | 1247 | 0.0% |

Pipeline 4057

**Comment by victorjulien** [comment]
Locally I see this fail on https://github.com/OISF/suricata-verify/blob/master/tests/http2-upgrade/test.yaml#L33, but here it seems to have passed. Not understanding why.

**Comment by catenacyber** [comment]
Working locally for me
With or without HTTP2 decompression ?

> Locally I see this fail on https://github.com/OISF/suricata-verify/blob/master/tests/http2-upgrade/test.yaml#L33, but here it seems to have passed. Not understanding why.

It is failing because in version 6, we get 
```
        "name": "Host",
        "value": "nghttp2.org"
```
when in version 7, we get normalized 
```
        "name": ":authority",
        "value": "nghttp2.org"
```

cf commit 75f75e1eb09c208a42e58b2babbc55027cd79e28

**Comment by victorjulien** [comment]
Yes I understand that about 6, but why is CI in this PR (which is for 6) not failing?

**Comment by catenacyber** [comment]
> Yes I understand that about 6, but why is CI in this PR (which is for 6) not failing?

Because it is using https://github.com/OISF/suricata-verify/pull/530
especially https://github.com/OISF/suricata-verify/pull/530/files#diff-1afe6bc97f0dd3bc1432d34c7db15d6252cbff6dbb7b3eb175f24f00765e7b0dR34

**Comment by catenacyber** [comment]
Should we add #6250 ?

**Comment by jasonish** [comment]
> when in version 7, we get normalized
> 
> ```
>         "name": ":authority",
>         "value": "nghttp2.org"
> ```

Just realizing that we should have a section in the upgrade documentation about all the changes made in the http events.

**Pull request merged**
