### PR TITLE
Http range file v13

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1576

Describe changes:
- Uses a generic container (a thread-safe hash table whose key is the url/filename) to store file parts with HTTP Range header
- handles reassembly of these parts, while enforcing a global memcap

suricata-verify-pr: 443

Modifies #5996 with handling gaps which are now handled by HTTP1 (ie `data == NULL && len > 0`)
They are handled by the `FileAppendData` util function

TODO: commit squashing 
Renaming to more specific ?
Test concurrency ? Is there a generic framework for this ?

### CODE REVIEW

**Comment by catenacyber** [comment]
Rerunning CI with rebased https://github.com/OISF/suricata-verify/pull/443

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6226

**Comment by suricata-qa** [comment]
ERROR: SEGMENTATION FAULT

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| |  |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| |  |

**Comment by suricata-qa** [comment]
ERROR: SEGMENTATION FAULT in tlpr1_autofp_suri QA test

**Comment by suricata-qa** [comment]
ERROR: SEGMENTATION FAULT in tlpr1_autofp_suri QA test

**Pull request closed without merging**
