### PR TITLE
Quic ietf 4967 v16

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4967
https://redmine.openinfosecfoundation.org/issues/5143
https://redmine.openinfosecfoundation.org/issues/5166

Describe changes:
- Parses standardized QUIC IETF v1
- Parses gquic version Q039, 0xfaceb002, etc...
- JA3 logging and detection on quic
- Adds quic events and rules 
- bump up rust carte tls_parser already used by rep, so that it can be used by quic
- Rustfmt previous code

suricata-verify-pr: 783
https://github.com/OISF/suricata-verify/pull/783

Replaces https://github.com/OISF/suricata/pull/7390 with setting `get_eventinfo` functions to some derived function from QuicEvent

### CODE REVIEW

**Comment by victorjulien** [comment]
Debian 11
```
   Compiling phf_codegen v0.10.0
error[E0658]: unions with non-`Copy` fields are unstable
  --> /builds/inliniac/suricata-ci/suricata/rust/vendor/polyval/src/backend/autodetect.rs:26:1
   |
26 | / union Inner {
27 | |     intrinsics: ManuallyDrop<intrinsics::Polyval>,
28 | |     soft: ManuallyDrop<soft::Polyval>,
29 | | }
   | |_^
   |
   = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information
   Compiling digest v0.10.3
   Compiling rusticata-macros v4.1.0
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: could not compile `polyval`.
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by victorjulien** [comment]
Debian buster on armhf
```
   Compiling suricata v7.0.0-dev (/builds/inliniac/suricata-ci/suricata/rust)
error[E0277]: the trait bound `u64: nom::ToUsize` is not satisfied
   --> src/quic/frames.rs:407:36
    |
407 |     let (rest, stream_data) = take(data_length)(rest)?;
    |                               ---- ^^^^^^^^^^^ the trait `nom::ToUsize` is not implemented for `u64`
    |                               |
    |                               required by a bound introduced by this call
    |
    = help: the following implementations were found:
              <u16 as nom::ToUsize>
              <u32 as nom::ToUsize>
              <u8 as nom::ToUsize>
              <usize as nom::ToUsize>
note: required by a bound in `nom::bytes::complete::take`
   --> /builds/inliniac/suricata-ci/suricata/rust/vendor/nom-5.1.2/src/bytes/complete.rs:381:6
    |
381 |   C: ToUsize,
    |      ^^^^^^^ required by this bound in `nom::bytes::complete::take`
For more information about this error, try `rustc --explain E0277`.
error: could not compile `suricata` due to previous error
make[1]: *** [Makefile:540: all-local] Error 101
```

**Comment by victorjulien** [comment]
Seeing that last one on Ubuntu 18.04 and Mingw32 as well.

**Comment by victorjulien** [comment]
> @jasonish can we upgrade `RUST_VERSION_MIN`from 1.48 to 1.49 ?

Debian Stable uses 1.48, so it's not a trivial thing.

**Comment by catenacyber** [comment]
Ok, so trying the downgrade of crates to supports MSRV 1.48 (1.41 even)

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8088

**Comment by catenacyber** [comment]
https://github.com/OISF/suricata/pull/7606

**Pull request closed without merging**
