### PR TITLE
Detect ac endswith/v1

### PR DESCRIPTION
**Pull request by victorjulien**
https://redmine.openinfosecfoundation.org/issues/6852

### CODE REVIEW

**Review by jasonish — COMMENTED** [review]
Are any documentation changes required?

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19273

**Comment by victorjulien** [comment]
> Are any documentation changes required?

Not sure, it's mostly an internal optimization.

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #10652, thanks!

**Pull request closed without merging**
