### PR TITLE
Ppp/v5

### PR DESCRIPTION
**Pull request by victorjulien**
Replaces https://github.com/OISF/suricata/pull/10831:

- rebase to master
- some ppp fixes
- few additional cleanups
- recognize a few more PPP record types

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1765

Tickets:
https://redmine.openinfosecfoundation.org/issues/6942

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .decoder.event.ppp.wrong_type | 2862 | 0 | - |
| .decoder.event.ppp.unsup_proto | 931 | 3772 | 405.16% | 

Pipeline 20066

**Comment by victorjulien** [comment]
> WARNING:
> field 	baseline 	test 	%
> 	SURI_TLPR1_stats_chk 		
> .decoder.event.ppp.wrong_type 	2862 	0 	-
> .decoder.event.ppp.unsup_proto 	931 	3772 	405.16%
> 
> Pipeline 20066

I've confirmed that this result is correct. cc @ct0br0

**Comment by ct0br0** [comment]
let me know when it merges and we can update qa baseline for it

**Review by lukashino — APPROVED** [review]

**Comment by catenacyber** [comment]
What is the relationship between https://redmine.openinfosecfoundation.org/issues/6887 and this PR ?

**Comment by victorjulien** [comment]
> What is the relationship between https://redmine.openinfosecfoundation.org/issues/6887 and this PR ?

Nothing, removed the links. It was part of the same work, but the other tickets have already been addressed in a diff pr.

**Comment by victorjulien** [comment]
Merged in #10852, thanks!

**Pull request closed without merging**
