### PR TITLE
detect-engine-iponly: remove insertion sort - v2

### PR DESCRIPTION
**Pull request by cccs-sadugas**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- https://redmine.openinfosecfoundation.org/issues/6376

# Describe changes

Since last PR, I ran `clang-format` to fix formatting.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks for this work @cccs-sadugas 

What do you expect out of this draft ?
Why is CI so red ?

**Comment by victorjulien** [comment]
Perhaps it makes sense to do the sorting after all entries have been inserted in the list. So do the insert as in this PR, build an array, qsort the array, rebuild the list.

**Comment by cccs-sadugas** [comment]
> Perhaps it makes sense to do the sorting after all entries have been inserted in the list. So do the insert as in this PR, build an array, qsort the array, rebuild the list.

Thanks for the feedback. I'll look into this and confirm that the test cases pass.

**Comment by cccs-sadugas** [comment]
> Thanks for this work @cccs-sadugas
> 
> What do you expect out of this draft ? Why is CI so red ?

Hi @catenacyber, I was looking for some initial feedback on how to approach this. I think @victorjulien's comment provides a way forward.

**Pull request closed without merging**
