### PR TITLE
Quic ietf 4967 v15

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4967
https://redmine.openinfosecfoundation.org/issues/5143
https://redmine.openinfosecfoundation.org/issues/5166

Describe changes:
- Parses standardized QUIC IETF v1
- Parses gquic version Q039, 0xfaceb002, etc...
- JA3 logging and detection on quic
- Adds quic events and rules 
- bump up rust carte tls_parser already used by rep, so that it can be used by quic
- Rustfmt previous code

suricata-verify-pr: 783
https://github.com/OISF/suricata-verify/pull/783

Replaces https://github.com/OISF/suricata/pull/7388 with not using latest aes crate so as not to depend on edition 2021

### CODE REVIEW

**Comment by catenacyber** [comment]
@pevma @ct0br0 is it possible to get the flows with the 35 remaining `.app_layer.error.quic.parser` in tlpw1_stats_chk ?

**Comment by victorjulien** [comment]
```
 148541 {"app_proto":"quic","type":"unknown","code":0,"layer":"proto_parser"}
  21601 {"app_proto":"quic","type":"unknown","code":1,"layer":"proto_parser"}
```

**Comment by catenacyber** [comment]
> [2740817] 7/6/2022 -- 12:09:03 - (detect-app-layer-event.c:228) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "quic" doesn't have event "failed_decrypt" registered
> [2740817] 7/6/2022 -- 12:09:03 - (detect-app-layer-event.c:228) <Warning> (DetectAppLayerEventParseAppP2) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - app-layer-event keyword's protocol "quic" doesn't have event "error_on_data" registered
> [2740817] 7/6/2022 -- 12:09:03 - (detect-engine-loader.c:353) <Warning> (SigLoadSignatures) -- [ERRCODE: SC_ERR_NO_RULES_LOADED(43)] - 1 rule files specified, but no rules were loaded!

Thanks, @ct0br0 do you know how to make CI test this ?

Looks like I missed 
```
diff --git a/rust/src/quic/quic.rs b/rust/src/quic/quic.rs
index 8332b444a..5563dce50 100644
--- a/rust/src/quic/quic.rs
+++ b/rust/src/quic/quic.rs
@@ -466,8 +466,8 @@ pub unsafe extern "C" fn rs_quic_register_parser() {
         tx_comp_st_ts: 1,
         tx_comp_st_tc: 1,
         tx_get_progress: rs_quic_tx_get_alstate_progress,
-        get_eventinfo: None,
-        get_eventinfo_byid: None,
+        get_eventinfo: Some(QuicEvent::get_event_info),
+        get_eventinfo_byid: Some(QuicEvent::get_event_info_by_id),
         localstorage_new: None,
         localstorage_free: None,
         get_files: None,
```

Pushing next version

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7504

**Pull request closed without merging**
