### PR TITLE
Converted unittests to new PASS/FAIL API #4022

### PR DESCRIPTION
**Pull request by sam10155**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
[Task #4022](https://redmine.openinfosecfoundation.org/issues/4022)

Describe changes:
- Converted unit tests in 'detect-engine-address-ipv4.c' to new PASS/FAIL API

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hello! Thanks and kudos for your first contribution to our project!

It's nice that you have added the redmine ticket :) Can you also comment on the ticket itself that you are working on this task, so we can assign it to you? (this prevents that other person starts to work on it ;) )

These were big tests, so thank you for your time and dedication, as well! 

I have set the CI checks to run, which is mandatory before approval.
Before merge, the commit message needs adjusting to conform to the contribution guidelines that you read.

Can you edit the message to include the module you have edited, and then what was done?

You can follow this commit message as example. The task corresponds to the redmine ticket: https://github.com/OISF/suricata/commit/025fd385cd1a219745bd8bb186df0768c9dd7405

**Comment by sam10155** [comment]
I forced a new commit message

**Comment by jufajardini** [comment]
> I forced a new commit message

Saw it, thanks!

Can you follow the format:
```
detect/ipv4: convert unittests to FAIL/PASS API

Task #4022
```
That way it also respects the character limit for the commit message ^^
(for more info about our commit guidelines, you can check: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria#Commits)

**Comment by sam10155** [comment]
Okay, I think I have done the message the proper way now

**Comment by jufajardini** [comment]
> Okay, I think I have done the message the proper way now

Looking good now, thanks a lot! I've approved the CI checks again, let's give them time to run to see if the code changes are as expected from the checks perspective, now ;)

**Comment by victorjulien** [comment]
Unfortunately I'm currently finishing work that replaces almost all the code in `detect-engine-address*.[ch]` and also removes all these tests. It won't make sense to merge this followed by a quick removal.

**Comment by sam10155** [comment]
Closing PR since changes made are irrelevant.

**Comment by victorjulien** [comment]
Thanks for understanding, I know it sucks to do work that turns out to be unnecessary. I think it could help to check in our dev channel on discord before doing another bigger changeset. Wouldn't want this to happen again :)

**Pull request closed without merging**
