### PR TITLE
Geoip2 backport/v1

### PR DESCRIPTION
**Pull request by shivan1b**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3067

### CODE REVIEW

**Comment by shivan1b** [comment]
Hi @bmeeks8!
Could you please help testing this branch?

**Comment by bmeeks8** [comment]
> Hi @bmeeks8!
> Could you please help testing this branch?

Yes, I can take a look at the changes.  I am running this patched code in the Suricata 4.1.4 binary used on the pfSense firewall distribution.  We have been running the GeoIP2 patch there since January of this year.  I will respond with the results in a couple of days.

I can't help with the Appveyor buid failure.  I think Victor had a solution for that.

**Comment by shivan1b** [comment]
> > Hi @bmeeks8!
> > Could you please help testing this branch?
> 
> Yes, I can take a look at the changes. I am running this patched code in the Suricata 4.1.4 binary used on the pfSense firewall distribution. We have been running the GeoIP2 patch there since January of this year. I will respond with the results in a couple of days.
> 
> I can't help with the Appveyor buid failure. I think Victor had a solution for that.

Thank you very much!

**Comment by victorjulien** [comment]
The 4.1.x branch still uses a cygwin based test on appveyor. A quick search suggests there is no geoip2 package for cygwin, so lets simply disable geoip in the build. Simply remove the '--enable-geoip' from line https://github.com/OISF/suricata/blob/master-4.1.x/appveyor.yml#L50 and the obsolete package installation from https://github.com/OISF/suricata/blob/master-4.1.x/appveyor.yml#L34

This can be done a separate commit in the same PR as the rest of the changes.

**Comment by victorjulien** [comment]
For reference: https://cygwin.com/cgi-bin2/package-grep.cgi?grep=geoip&arch=x86_64

**Comment by shivan1b** [comment]
Thanks @victorjulien . Replaced with #4000

**Pull request closed without merging**
