### PR TITLE
rust: fix clippy issues

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #12189

Based on https://github.com/OISF/suricata/pull/12171

Backport clippy fixes to main-7.0.x

Updates:
- Removed changes to x509/mod.rs (not needed for main-7.0.x)

### CODE REVIEW

**Comment by jasonish** [comment]
The changes to `Cargo.lock.in` seem larger than I would have expected, how did you regenerate it?  For reference, in master what I did was:
- update num-derive in Cargo.toml.in
- run `make`
- run `cp Cargo.lock Cargo.lock.in`
- doing the same on main-7.0.x results in a smaller diff to `Cargo.lock.in`.

Maybe `make update-lock` should do similar logic to prevent pulling in more stuff then needed to match a `Cargo.toml` change.

**Comment by jlucovsky** [comment]
> The changes to `Cargo.lock.in` seem larger than I would have expected, how did you regenerate it? For reference, in master what I did was:
> 
> * update num-derive in Cargo.toml.in
> * run `make`
> * run `cp Cargo.lock Cargo.lock.in`
> * doing the same on main-7.0.x results in a smaller diff to `Cargo.lock.in`.
> 
> Maybe `make update-lock` should do similar logic to prevent pulling in more stuff then needed to match a `Cargo.toml` change.

I cherry-picked the commit and resolved the issues.

I'm happy to try your suggestion if that will be cleaner. Please advise.

**Comment by victorjulien** [comment]
My preference:
1. cargo update, make, copy Cargo.lock to Cargo.lock.in, commit
2. update num-derive in Cargo.toml.in
   run make
   run cp Cargo.lock Cargo.lock.in
3. add the remaining commits

This splits the num-derive update from a regular update, and excludes any possible artifacts from master

**Comment by jlucovsky** [comment]
Continued in #12220

**Pull request closed without merging**
