### PR TITLE
detect: transforms check for 0-sized buffer backport6

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5521

Describe changes:
- backport of https://redmine.openinfosecfoundation.org/issues/5521

libhtp-pr: 366

### CODE REVIEW

**Comment by catenacyber** [comment]
CIFuzz is same old libpcre1 bug.
I wonder how we could disable it in master6...

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | generic_stats_chk | | |
| .capture.kernel_drops | 0 | 154815 | - |
| .tcp.reassembly_gap | 80952 | 107624 | 132.95% |
| .tcp.overlap | 0 | 12 | - |
| .ftp.memuse | 0 | 39 | - | 

Pipeline 9186

**Comment by catenacyber** [comment]
Waits for CI fix cf https://github.com/OISF/suricata/pull/7871

**Comment by victorjulien** [comment]
Merged in #7878, thanks!

**Pull request closed without merging**
