### PR TITLE
WIP: Libhtp rs v3

### PR DESCRIPTION
**Pull request by cccs-rtmorti**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2696) ticket: 2696

Describe changes:
- Use libhtp-rs.
- Rebased from #7438 
- I broke this up in the 3 commits that can be logically separated: Reworking the API to use libhtp constants and functions; removing the suricata URI normalization in favour of the libhtp-rs implementation; and building libhtp-rs as a crate instead of a shared library. The main commit has a message describing all of the changes. 

libhtp-repo: https://github.com/cccs-rtmorti/libhtp-rs
libhtp-branch: master

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks Todd, could you get CI to be greener ? Do you need help with it ?

**Comment by cccs-rtmorti** [comment]
> Thanks Todd, could you get CI to be greener ? Do you need help with it ?

Yup, I can give it a shot. What is the easiest way to test the pipeline without opening a new PR every time? 

I can fix the formatting check pretty easily, and can probably figure out the build failures, but I think the commit check will fail because it's hard to pull some of the bits apart into separate chunks. I don't know how much of an issue that will be.

**Comment by catenacyber** [comment]
I guess you can push commits on this PR and mark this PR as a draft to get CI green

commit-check is important for `got bisect` : every commit needs to build

**Comment by cccs-rtmorti** [comment]
> I guess you can push commits on this PR and mark this PR as a draft to get CI green

Will do! :)
 
> commit-check is important for `got bisect` : every commit needs to build

Okay, in that case it might be hard to pull things apart. I will see what I can do.

**Comment by cccs-rtmorti** [comment]
I have a working branch open at #8270 for CI checks. Trying to keep things as separate buildable commits while getting the rest of the CI passing is tricky, so one thing at a time. :)

**Pull request closed without merging**
