### PR TITLE
Bug/tls frag incomplete/v52

### PR DESCRIPTION
**Pull request by victorjulien**
#7794 on top #7793

Tickets:
https://redmine.openinfosecfoundation.org/issues/5191
https://redmine.openinfosecfoundation.org/issues/1096
https://redmine.openinfosecfoundation.org/issues/5183
https://redmine.openinfosecfoundation.org/issues/5481

suricata-verify-pr: 911

### CODE REVIEW

**Comment by opoplawski** [comment]
Can I ask why you keep closing and opening new PRs rather than just updating the exiting one?

**Comment by victorjulien** [comment]
> Can I ask why you keep closing and opening new PRs rather than just updating the exiting one?

It's our policy: https://github.com/OISF/suricata/blob/master/doc/userguide/devguide/codebase/contributing/code-submission-process.rst#pull-requests
We feel that the review CI and QA processes don't work well when PRs are updated.

**Comment by opoplawski** [comment]
Interesting.  FWIW - it does make it hard for me to follow the progress.  Thanks.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .app_layer.error.tls.parser | 157 | 1025 | 15.32% |
| | tlpr1_stats_chk | | |
| .flow.spare | 2085166 | 2200819 | 94.75% |
| .flow.memuse | 924538368 | 562615488 | 164.33% |
| .app_layer.error.tls.parser | 1499 | 22937 | 6.54% | 

Pipeline 8929
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. BE MINDFUL OF ANY RESULTS.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_opt | | |
 

Pipeline 8991

**Comment by victorjulien** [comment]
replaced by #7896

**Pull request closed without merging**
