### PR TITLE
Dev 3346 mysql proto v2

### PR DESCRIPTION
**Pull request by Kotodian**
Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/3446

Describe changes:
- fix mysql parser bug.
- fix mysql logger bug.
- add mysql detection keywords
1. mysql.command
2. mysql.rows
- add SV tests.

SV_REPO=https://github.com/OISF/suricata-verify
SV_BRANCH=tests-3446-mysql-v2

### CODE REVIEW

**Comment by victorjulien** [comment]
@Kotodian I've emailed you on the email address you used to sign the CLA, can you please have a look?

**Comment by Kotodian** [comment]
> @Kotodian I've emailed you on the email address you used to sign the CLA, can you please have a look?

Ok, sorry.

**Comment by victorjulien** [comment]
> > @Kotodian I've emailed you on the email address you used to sign the CLA, can you please have a look?
> 
> Ok, i feel so sorry about it, but i couldn't find any email from you in all of my emails, can i ask what is CLA?

The contribution agreement. I've sent it that email, which looks like the same email as you git author has.

**Comment by Kotodian** [comment]
> > > @Kotodian I've emailed you on the email address you used to sign the CLA, can you please have a look?
> > 
> > 
> > Ok, i feel so sorry about it, but i couldn't find any email from you in all of my emails, can i ask what is CLA?
> 
> The contribution agreement. I've sent it to that email, which looks like the same email as you git author has.
Can you send email to `blackfaceuncle@gmail.com`? Because I from China, maybe i can't recv email from foreigner.

**Pull request closed without merging**
