### PR TITLE
log/diag: Support diagnostic stacktraces on unexpected signals

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #6309  
This PR supports configuring Suricata to emit a one-line diagnostic message containing a stacktrace when a signal that terminates Suricata execution (e.g., SIGABRT or SIGSEGV) occurs.

Requires:
- Removed configuration option; this feature will always be enabled when libunwind is present during configuration
- `libunwind` must be available for when building Suricata
- Enablement in Suricata's configuration file (`logging.stacktrace-on-signal`)

Example output:
```
[1429359] 24/8/2021 -- 10:15:02 - (suricata.c:1108) <Notice> (LogVersion) -- This is Suricata version 7.0.0-dev running in SYSTEM mode
[1429359] 24/8/2021 -- 10:15:02 - (tm-threads.c:2004) <Notice> (TmThreadWaitOnThreadInit) -- Threads created -> W: 16 FM: 1 FR: 1   Engine started.
[1429373] 24/8/2021 -- 10:15:04 - (suricata.c:332) <Error> (SignalHandlerUnexpected) -- [ERRCODE: SC_ERR_SIGNAL(339)] - stacktrace:sig 6:raise+0x000000cb;AFPReadFromRing+0x00000174;ReceiveAFPLoop+0x00000c06;TmThreadsSlotPktAcqLoop+0x00000ca9;start_thread+0x000000d9;clone+0x00000043
Aborted
```
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4526](https://redmine.openinfosecfoundation.org/issues/4526)

Describe changes:
- Default configuration setting changed to `on`.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4049

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4049

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4049

**Comment by victorjulien** [comment]
Naive question: during the unwind, can we actually insert logic? Thinking about things like "if we have a Signature pointer, print Signature::id", and along those lines some details about a packet and flow and such.

**Comment by jlucovsky** [comment]
> Naive question: during the unwind, can we actually insert logic? Thinking about things like "if we have a Signature pointer, print Signature::id", and along those lines some details about a packet and flow and such.

The danger would be in presuming that any part of the system is in a workable state following a `SIGSEGV` or `SIGABRT`.

There is value in having a "crash report" with more information but whether additional information could be added when this occurs is questionable.

**Comment by victorjulien** [comment]
> > Naive question: during the unwind, can we actually insert logic? Thinking about things like "if we have a Signature pointer, print Signature::id", and along those lines some details about a packet and flow and such.
> 
> The danger would be in presuming that any part of the system is in a workable state following a `SIGSEGV` or `SIGABRT`.
> 
> There is value in having a "crash report" with more information but whether additional information could be added when this occurs is questionable.

What is the danger? We're already aborting, so trying to extract a bit of info shouldn't lead to many risks?

**Comment by jlucovsky** [comment]
> > > Naive question: during the unwind, can we actually insert logic? Thinking about things like "if we have a Signature pointer, print Signature::id", and along those lines some details about a packet and flow and such.
> > 
> > 
> > The danger would be in presuming that any part of the system is in a workable state following a `SIGSEGV` or `SIGABRT`.
> > There is value in having a "crash report" with more information but whether additional information could be added when this occurs is questionable.
> 
> What is the danger? We're already aborting, so trying to extract a bit of info shouldn't lead to many risks?

Right .... but which signature? which packet? which thread?

The point is ... we don't know what triggered the deadly signal so what interfaces can be trusted? which information to attempt to gather?

I think the idea of a crash report with rich information is good. I suggest we create a feature for "Enhanced error reporting" or similar and address that separately.

**Comment by victorjulien** [comment]
> > > > Naive question: during the unwind, can we actually insert logic? Thinking about things like "if we have a Signature pointer, print Signature::id", and along those lines some details about a packet and flow and such.
> > > 
> > > 
> > > The danger would be in presuming that any part of the system is in a workable state following a `SIGSEGV` or `SIGABRT`.
> > > There is value in having a "crash report" with more information but whether additional information could be added when this occurs is questionable.
> > 
> > 
> > What is the danger? We're already aborting, so trying to extract a bit of info shouldn't lead to many risks?
> 
> Right .... but which signature? which packet? which thread?
> 
> The point is ... we don't know what triggered the deadly signal so what interfaces can be trusted? which information to attempt to gather?
> 
> I think the idea of a crash report with rich information is good. I suggest we create a feature for "Enhanced error reporting" or similar and address that separately.

Feature ticket sounds good, can you create one?

**Comment by jlucovsky** [comment]
> Feature ticket sounds good, can you create one?

https://redmine.openinfosecfoundation.org/issues/4723

**Comment by jlucovsky** [comment]
Continued in #6650

**Pull request closed without merging**
