### PR TITLE
WIP: Af packet exit

### PR DESCRIPTION
**Pull request by regit**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- https://redmine.openinfosecfoundation.org/issues/2637
- https://redmine.openinfosecfoundation.org/issues/2633

Describe changes:
- Cleaner exit handling in af-packet
- Display error message when BPF compilation fails

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/418
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/200

### CODE REVIEW

**Comment by oksbsb** [comment]
@regit would you like to add AF_XDP support from Linux 4.18+?

**Comment by regit** [comment]
@oksbsb my objective is to start coding AF_XDP support in the coming days.

**Comment by victorjulien** [comment]
The appveyor build failure is a real issue btw.

**Comment by regit** [comment]
Thanks @inliniac, I'm gonna rebase and resubmit.

**Pull request closed without merging**
