### PR TITLE
Sctime fixes v1

### PR DESCRIPTION
**Pull request by sfd**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6584
https://redmine.openinfosecfoundation.org/issues/6585

Describe changes:
-  Fix SCTIME_FROM_TIMESPEC garbage microseconds part
   -  When converting nanosecond to microseconds divide by 1000 instead of multiplying by 1000.
- Fix SCTIME_ADD_SECS zeroing subsecond part
  - When adding s seconds to SCtime_t ts, don't zero out the ts.usecs field.

### CODE REVIEW

**Comment by sfd** [comment]
Sorry the history is a bit messy, I can start a clean -v2 branch if you prefer?

**Review by victorjulien — CHANGES_REQUESTED** [review]
I think a single commit would be sufficient here. Can you force push things until CI is green and review phase is over? Then we can do a v2 for merging. Thanks!

**Comment by sfd** [comment]
Please note this PR does not duplicate the fix to SCTIME_ADD_USECS from https://github.com/OISF/suricata/pull/9833 Redmine https://redmine.openinfosecfoundation.org/issues/6372 so this PR should be considered additional.

**Review by jlucovsky — APPROVED** [review]
The code changes look good. Thanks!

**Comment by victorjulien** [comment]
@sfd can you do that in your v2 PR?

**Comment by sfd** [comment]
Added sctime-fixes-v2 PR
https://github.com/OISF/suricata/pull/9959

**Comment by inashivb** [comment]
Replaced w https://github.com/OISF/suricata/pull/9959

**Pull request closed without merging**
