### PR TITLE
rust/mqtt: create PDU frames prior to input parsing

### PR DESCRIPTION
**Pull request by glongo**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6956

Describe changes:
- Move PDU creation prior to input parsing

### CODE REVIEW

**Comment by victorjulien** [comment]
Do you happen to have a SV test for this?

**Comment by glongo** [comment]
> Do you happen to have a SV test for this?

No, I don’t. However, there are already tests related to MQTT frames.

**Comment by catenacyber** [comment]
I agree one SV test is needed to show the improvement over existing code.
IIRC, I had tried that and did not find a way to "see" the frame before its length was set (but Victor claimed it could).

**Review by catenacyber — CHANGES_REQUESTED** [review]
Needs a rebase and a test to show the changed behavior

**Comment by catenacyber** [comment]
Closing as stale.
Giuseppe, let me know if you manage to trigger a different behavior...

**Pull request closed without merging**
