### PR TITLE
Dataset set postmatch 5576 v9

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/5576

Describe changes:
- detect/dataset: delay set operation after signature full match

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2000

https://github.com/OISF/suricata/pull/11719 with rebase after unset operation has been added

So, now Victor, you will ask me for more tests 
- rule with multibuffer + content + dataset vs traffic having multiple buffers but only one matching
- rule with dataset + pcap with transaction spanning over multiple packets (like https://github.com/OISF/suricata-verify/pull/1999 but with dataset instead of flowvar)

Right ?

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 22812

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22853

**Comment by victorjulien** [comment]
I would like to avoid rerunning transforms and detection. One alternative way could be to explore having a immediate dataset operation that stores the data in a temporary location (det_ctx for example) and then uses that from post-match.

**Comment by catenacyber** [comment]
> I would like to avoid rerunning transforms and detection.

Ok...
Note that transforms should be cached in the regular case ;-)

> One alternative way could be to explore having an immediate dataset operation that stores the data in a temporary location (det_ctx for example) and then uses that from post-match.

This is problematic as https://redmine.openinfosecfoundation.org/issues/7197 shows it for flowvar
If the rule match spans over multiple packets (because of different tx progress), we do not have a good location to store it
What do you suggest ?

**Comment by catenacyber** [comment]
Next in https://github.com/OISF/suricata/pull/11962

**Pull request closed without merging**
