### PR TITLE
version: start development towards 7.0.8

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by catenacyber** [comment]
> [util/thash: fix formatting](https://github.com/OISF/suricata/pull/11849/commits/09d3ff998033d37cd83f9f2097e51ecb22ed181a)

There was a conflict

And my pre-push git hook `./scripts/clang-format.sh check-branch` did not catch it because clang-format.sh works only for master and not for main-7.0.x cf `FirstCommitOfBranch`

**Comment by catenacyber** [comment]
So https://redmine.openinfosecfoundation.org/issues/7292

**Comment by inashivb** [comment]
> > [util/thash: fix formatting](https://github.com/OISF/suricata/pull/11849/commits/09d3ff998033d37cd83f9f2097e51ecb22ed181a)
> 
> There was a conflict
> 
> And my pre-push git hook `./scripts/clang-format.sh check-branch` did not catch it because clang-format.sh works only for master and not for main-7.0.x cf `FirstCommitOfBranch`

hmmm. idk how but it does fail for me locally on `main-7.0.x` and in the CI job w the same command https://github.com/OISF/suricata/actions/runs/11123949421/job/30908477206

**Comment by catenacyber** [comment]
> > > [util/thash: fix formatting](https://github.com/OISF/suricata/pull/11849/commits/09d3ff998033d37cd83f9f2097e51ecb22ed181a)
> > 
> > 
> > There was a conflict
> > And my pre-push git hook `./scripts/clang-format.sh check-branch` did not catch it because clang-format.sh works only for master and not for main-7.0.x cf `FirstCommitOfBranch`
> 
> hmmm. idk how but it does fail for me locally on `main-7.0.x` and in the CI job w the same command https://github.com/OISF/suricata/actions/runs/11123949421/job/30908477206

Indeed, so I wonder how it bypassed my git hook...

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22934

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11851, thanks!

**Pull request merged**
