### PR TITLE
next/508/20240628/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #11388

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1947

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 137 | 142 | 103.65% | 

Pipeline 21323

**Comment by ct0br0** [comment]
I suspect the 10sec is a fluke. But we can rerun, probably after things catch up.

**Review by inashivb — APPROVED** [review]
LGTM 🚀 
Merge blocked by: QA lab results

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21334

**Pull request merged**
