### PR TITLE
Include less v15

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/945

Describe changes:
- Remove unused includes in c files
- adds some options in CI : hyperscan, luajit

Follows #8138 with 
- removal of latest commits removing includes of C files for now
- fixing completely cppclean (like including "action-globals.h" from every C file instead of using super header)

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 10384

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10406

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10437

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10437

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8167

**Pull request closed without merging**
