### PR TITLE
output/alert: don't call basic logging twice

### PR DESCRIPTION
**Pull request by regit**
Issue: 4106

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4106

Describe changes:
- Fix duplicate logging of TLS basic fields

### CODE REVIEW

**Review by jlucovsky — APPROVED** [review]

**Comment by catenacyber** [comment]
@jasonish should some json linter run on Suricata-verify to check this kind of duplicate entries ?

**Comment by jasonish** [comment]
> @jasonish should some json linter run on Suricata-verify to check this kind of duplicate entries ?

This one would be duplicate keys? We might be able to change the JSON loader to error out on this. The loader should already fail on invalid json, but duplicate keys are not invalid.

**Comment by catenacyber** [comment]
> This one would be duplicate keys? 

Exactly.

> We might be able to change the JSON loader to error out on this.

Cool

> The loader should already fail on invalid json, but duplicate keys are not invalid.

Indeed, it is not strictly invalid, but it is not something we want in Suricata's output ;-)

**Comment by victorjulien** [comment]
Merged in #6802, thanks!

**Pull request closed without merging**
