### PR TITLE
 reorg: modular file reorganization of C source code - v6

### PR DESCRIPTION
**Pull request by jasonish**
Continuation of #9957 

Changes from previous PR:
- Remove clang-format from single line arrays
- More protocols
- "EVE" output files not related to an app-layer in `output/eve`
- Other output files into `output`
- `util-*` into `util/`

TODO:
- Other log should go into output as well

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 16863

**Comment by jasonish** [comment]
A file got lost, `util-config.[ch]` to `util/config.[ch]`, but anyways, its more about the overall structure.

**Comment by inashivb** [comment]
Tips on how does one go about reviewing a PR of this order and length?

**Comment by jasonish** [comment]
> Tips on how does one go about reviewing a PR of this order and length?

At this point, probably sampling a few of the commits in the PR to make sure they're reorganzing their item of interest in s a sane way.

**Comment by jasonish** [comment]
The last commit, the util reorg is causing build failures.

**Comment by jasonish** [comment]
The building is fixed at https://github.com/OISF/suricata/pull/9973.

**Pull request closed without merging**
