### PR TITLE
doc: added noted about big endian for icmp_seq v1

### PR DESCRIPTION
**Pull request by jmtaylor90**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
- [] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues
      (if applicable)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
- added note about endianess to icmp_seq keyword
-
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by jasonish** [comment]
Can you elaborate more on what this means for the end-user? Or maybe its even a bug.

When we store the icmp_seq, we keep it in network/wire order.  When we parse this keyword, we parse it then convert to network byte order before match. Am I missing something?

**Comment by jmtaylor90** [comment]
> NOTE: This PR may contain new authors.

oops, will fix this

**Comment by jmtaylor90** [comment]
> Can you elaborate more on what this means for the end-user? Or maybe its even a bug.
> 
> When we store the icmp_seq, we keep it in network/wire order. When we parse this keyword, we parse it then convert to network byte order before match. Am I missing something?

When reviewing an ET signature (2032935), the pcap provided by the source article, https://github.com/SpiderLabs/IOCs-IDPS/tree/master/Pingback there are static icmp sequence values. When writing to match on icmp_seq the big endian value 53764 matches whereas the little endian value (1234) does not match in my testing.

**Review by jufajardini — COMMENTED** [review]
nit:  typos in the commit message :P

If this is a bug, then we'll also want to create a ticket and add a reference to it in the docs.

**Comment by jasonish** [comment]
> > Can you elaborate more on what this means for the end-user? Or maybe its even a bug.
> > When we store the icmp_seq, we keep it in network/wire order. When we parse this keyword, we parse it then convert to network byte order before match. Am I missing something?
> 
> When reviewing an ET signature (2032935), the pcap provided by the source article, https://github.com/SpiderLabs/IOCs-IDPS/tree/master/Pingback there are static icmp sequence values. When writing to match on icmp_seq the big endian value 53764 matches whereas the little endian value (1234) does not match in my testing.

Interesting. I never paid close enough attention to Wireshark here that it displays the icmp seq number in BE and LE. Seems there are some ICMP implementations out there that don't use network byte order for these fields, but most do, which is what Suricata assumes, as does tcpdump, etc.

Perhaps some extra context: This value assumes the ICMP sequence number on the wire is sent in network byte order (big endian), if looking at Wireshark, use the BE value.

Or something along those lines.

Seems like this Pingback is one of those implementation that doesn't use network byte order on the wire.

**Comment by jmtaylor90** [comment]
> > > Can you elaborate more on what this means for the end-user? Or maybe its even a bug.
> > > When we store the icmp_seq, we keep it in network/wire order. When we parse this keyword, we parse it then convert to network byte order before match. Am I missing something?
> > 
> > 
> > When reviewing an ET signature (2032935), the pcap provided by the source article, https://github.com/SpiderLabs/IOCs-IDPS/tree/master/Pingback there are static icmp sequence values. When writing to match on icmp_seq the big endian value 53764 matches whereas the little endian value (1234) does not match in my testing.
> 
> Interesting. I never paid close enough attention to Wireshark here that it displays the icmp seq number in BE and LE. Seems there are some ICMP implementations out there that don't use network byte order for these fields, but most do, which is what Suricata assumes, as does tcpdump, etc.
> 
> Perhaps some extra context: This value assumes the ICMP sequence number on the wire is sent in network byte order (big endian), if looking at Wireshark, use the BE value.
> 
> Or something along those lines.
> 
> Seems like this Pingback is one of those implementation that doesn't use network byte order on the wire.

Sounds good, thank you both. Will get this fixed up and resubmitted. Is there a need for a ticket?

**Comment by jufajardini** [comment]
> > > > Can you elaborate more on what this means for the end-user? Or maybe its even a bug.
> > > > When we store the icmp_seq, we keep it in network/wire order. When we parse this keyword, we parse it then convert to network byte order before match. Am I missing something?
> > > 
> > > 
> > > When reviewing an ET signature (2032935), the pcap provided by the source article, https://github.com/SpiderLabs/IOCs-IDPS/tree/master/Pingback there are static icmp sequence values. When writing to match on icmp_seq the big endian value 53764 matches whereas the little endian value (1234) does not match in my testing.
> > 
> > 
> > Interesting. I never paid close enough attention to Wireshark here that it displays the icmp seq number in BE and LE. Seems there are some ICMP implementations out there that don't use network byte order for these fields, but most do, which is what Suricata assumes, as does tcpdump, etc.
> > Perhaps some extra context: This value assumes the ICMP sequence number on the wire is sent in network byte order (big endian), if looking at Wireshark, use the BE value.
> > Or something along those lines.
> > Seems like this Pingback is one of those implementation that doesn't use network byte order on the wire.
> 
> Sounds good, thank you both. Will get this fixed up and resubmitted. Is there a need for a ticket?

No need, from what I understood. Thanks for asking :)

**Review by catenacyber — CHANGES_REQUESTED** [review]
waiting for your next version :-)

**Comment by jmtaylor90** [comment]
continued in #11712

**Pull request closed without merging**
