### PR TITLE
quic: Add GQUIC App Layer - v1

### PR DESCRIPTION
**Pull request by sharksforarms**
- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3440

Describe changes:
- Parses gquic version Q043-Q046 and logs a CYU hash
- Added a mix of unit and suricata-verify pcap tests
- Fails gracefully with unknown QUIC versions
- Other versions can be added later w/ pcaps + testing
- Logs a cyu hash and string to eve.json
  - Example ```{"timestamp":"2020-09-02T15:58:21.139196+0000","flow_id":1610311033233340,"pcap_cnt":1,"event_type":"quic","src_ip":"10.0.2.15","src_port":51989,"dest_ip":"172.217.164.142","dest_port":443,"proto":"UDP","quic":{"cyu":{"hash":"910a5e3a4d51593bd59a44611544f209","string":"46,PAD-SNI-VER-CCS-UAID-TCID-PDMD-SMHL-ICSL-NONP-MIDS-SCLS-CSCT-COPT-IRTT-CFCW-SFCW"}}}```

References:
   - https://docs.google.com/document/d/1WJvyZflAO2pq77yOLbp9NsGjC1CHetAXV8I0fQe-B_U/edit
   - https://docs.google.com/document/d/1g5nIXAIkN_Y-7XJW5K45IblHd_L2f5LTaDUDwvZ5L6g/edit
   - https://www.slideshare.net/shigeki_ohtsu/quic-overview
   - https://tools.ietf.org/html/draft-ietf-quic-transport-17#section-19.8
   - https://github.com/salesforce/GQUIC_Protocol_Analyzer/blob/master/src/gquic-protocol.pac
   - cyu: https://engineering.salesforce.com/gquic-protocol-analysis-and-fingerprinting-in-zeek-a4178855d75f

suricata-verify:
https://github.com/OISF/suricata-verify/pull/364

Questions:
- Should it be enabled by default in suricata.yml
- Should port 80 be added as per https://github.com/salesforce/GQUIC_Protocol_Analyzer/blob/e62494ad437539e4b88d1b917e7cc16e4acaca91/scripts/Salesforce/GQUIC/main.zeek#L33

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks for this contribution.
Did you check the CI failures ?

Do you plan to add the documentation for this ?
Do you plan to add signature keywords for this protocol ?

Could you modify output-json-alert.c as well ?
cf `git grep MQTT | cut -d: -f1 | uniq | grep -v mqtt` to see the modified files for a new protocol

> Should it be enabled by default in suricata.yml

Not for the first version I guess

> Should port 80 be added ?

I guess so
This is used especially by probing parser

**Comment by victorjulien** [comment]
> > Should it be enabled by default in suricata.yml
> 
> Not for the first version I guess

This will depend on how early in the dev cycle we merge it, and how well the SV coverage is.

**Comment by sharksforarms** [comment]
> Did you check the CI failures ?

Working through the failures! Most seem to be related to a rust dependency I introduced.

> Do you plan to add the documentation for this ?

Yes, will add this as a TODO

> Do you plan to add signature keywords for this protocol ?

I wasn't thinking of adding this for this PR, may be better in a future PR
as required.

**Comment by sharksforarms** [comment]
> I wasn't thinking of adding this for this PR, may be better in a future PR
> as required.

Now that I looked into it a bit more, this is almost required to create any sort of alert based on the cyu correct? My assumption was that alerts could be created off the output json, is this possible?

**Comment by catenacyber** [comment]
> Now that I looked into it a bit more, this is almost required to create any sort of alert based on the cyu correct? My assumption was that alerts could be created off the output json, is this possible?

The alerts are not created out of the json.
It is rather that both alerts and logs originate from the same data/structures...

**Comment by sharksforarms** [comment]
> > Now that I looked into it a bit more, this is almost required to create any sort of alert based on the cyu correct? My assumption was that alerts could be created off the output json, is this possible?
> 
> The alerts are not created out of the json.
> It is rather that both alerts and logs originate from the same data/structures...

Would `detect-mqtt-publish-topic.c` be a good example to expose a `quic.cyu` for matching?

**Comment by catenacyber** [comment]
> Would detect-mqtt-publish-topic.c be a good example to expose a quic.cyu for matching?

I guess so.
It depends on the nature of `quic.cyu`
Is this a buffer ? Do you have only one `quic.cyu` per transaction ?

**Comment by sharksforarms** [comment]
> > Would detect-mqtt-publish-topic.c be a good example to expose a quic.cyu for matching?
> 
> I guess so.
> It depends on the nature of `quic.cyu`
> Is this a buffer ? Do you have only one `quic.cyu` per transaction ?

Yes and yes. Pushed a commit, will also update the suricata-verify tests to include alerts.
Will expose `quic.cyu.hash` and `quic.cyu.string`.

Will look into adding a `quic.version` as-well, that way we can log/alert on this.

**Comment by catenacyber** [comment]
>> Is this a buffer ? Do you have only one quic.cyu per transaction ?
> Yes and yes. Pushed a commit, will also update the suricata-verify tests to include alerts.
> Will expose quic.cyu.hash and quic.cyu.string.

You can look at `ssh.hassh` which looks similar to me with hash and string as well

**Pull request closed without merging**
