### PR TITLE
eve/schema: check that each array has at least one element

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5167

Describe changes:
- eve/schema : forbid empty arrays

Replaces https://github.com/OISF/suricata-verify/pull/897 (yes replacing S-V PR with suricata one)

### CODE REVIEW

**Comment by catenacyber** [comment]
ping @jasonish ?

**Comment by victorjulien** [comment]
This looks like it fails on `dns-lua-rules`, which has this record:
```json
{
  "query": [],
  "answer": {
    "version": 2,
    "type": "answer",
    "id": 36146,
    "flags": "81a0",
    "qr": true,
    "rd": true,
    "ra": true,
    "rrname": "www.suricata-ids.org",
    "rrtype": "A",
    "rcode": "NOERROR"
  }
}
```

**Comment by catenacyber** [comment]
Nice catch, fix in https://github.com/OISF/suricata/pull/8231

**Comment by catenacyber** [comment]
Why did not CI catch this ? is S-V run with lua support ?

**Comment by jasonish** [comment]
> Why did not CI catch this ? is S-V run with lua support ?

On a quick look, Debian 9 with Luajit does an S-V test in GitHub CI.  But we should enable this more explicitly in some newer builds.

**Pull request closed without merging**
