### PR TITLE
mqtt: enable limiting of logged message length

### PR DESCRIPTION
**Pull request by satta**
- [X] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6984

Describe changes:
- Add an `msg-log-limit` option to enable optional truncation of the message payloads in MQTT.

```
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1828
```

### CODE REVIEW

**Comment by satta** [comment]
Hmm, it looks like the included file `doc/userguide/partials/eve-log.yaml` hasn't been updated in some time. I guess that's where you meant the additional options to be listed? Should I bring it up to date with the current state of supported event types?

Also, I don't think that the logging options should go into `doc/userguide/configuration/suricata-yaml.rst`? The app-layer parser configuration is there, but the changes here only affect logging. I think it would probably be best to add a MQTT section to `doc/userguide/output/eve/eve-json-output.rst`. What do you think?

**Comment by satta** [comment]
New PR: #11054 11054

**Comment by catenacyber** [comment]
> Also, I don't think that the logging options should go into `doc/userguide/configuration/suricata-yaml.rst`? The app-layer parser configuration is there, but the changes here only affect logging. I think it would probably be best to add a MQTT section to `doc/userguide/output/eve/eve-json-output.rst`. What do you think?

I think `doc/userguide/configuration/suricata-yaml.rst` is meant to document everything in suricata.yaml
@jufajardini what do you think ?

**Comment by jufajardini** [comment]
> > Also, I don't think that the logging options should go into `doc/userguide/configuration/suricata-yaml.rst`? The app-layer parser configuration is there, but the changes here only affect logging. I think it would probably be best to add a MQTT section to `doc/userguide/output/eve/eve-json-output.rst`. What do you think?
> 
> I think `doc/userguide/configuration/suricata-yaml.rst` is meant to document everything in suricata.yaml @jufajardini what do you think ?

I see that Sascha has addressed this, but just to answer - it seems to be what we're following, indeed.

**Pull request closed without merging**
