### PR TITLE
detect: add requires keyword - v1

### PR DESCRIPTION
**Pull request by jasonish**
Add a new rule keyword "requires" that allows a rule to require specific Suricata versions and/or Suricata features to be enabled.

Example:

  requires: feature geoip, version >= 7.0.0, version < 8;

Feature: https://redmine.openinfosecfoundation.org/issues/5972

### CODE REVIEW

**Comment by jasonish** [comment]
Currently submitting this PR for feedback on how we should report a rule being skipped due to missing requirements.

Currently, I'm not warning, or erroring out at all. Without `-v` there is no indication that any rules were skipped.

With `-v` you get some `Info` logging. For example, with the rules:
```
alert dns any any -> any any (msg:"TEST"; requires: feature output::lua, version >= 8.0.4; sid:2; rev:1;)
alert dns any any -> any any (msg:"TEST"; requires: feature output::lua; sid:3; rev:1;)
alert dns any any -> any any (msg:"TEST"; sid:4; rev:1;)
```
you will see:
```
Info: detect-requires: Suricata did not meet the rule requirements: Suricata version less than required: feature output::lua, version >= 8.0.4 [DetectRequiresSetup:detect-requires.c:33]
Info: detect: Skipping signature due to missing requirements: alert dns any any -> any any (msg:"TEST"; requires: feature output::lua, version >= 8.0.4; sid:2; rev:1;) from file ./test.rules at line 1 [DetectLoadSigFile:detect-engine-loader.c:200]
Info: detect-requires: Suricata did not meet the rule requirements: Suricata missing a required feature: feature output::lua [DetectRequiresSetup:detect-requires.c:33]
Info: detect: Skipping signature due to missing requirements: alert dns any any -> any any (msg:"TEST"; requires: feature output::lua; sid:3; rev:1;) from file ./test.rules at line 2 [DetectLoadSigFile:detect-engine-loader.c:200]
```
and the summary:
```
Info: detect: 1 rule files processed. 1 rules successfully loaded, 0 rules failed, 2 rules skipped [SigLoadSignatures:detect-engine-loader.c:371]
```
where skipped has been added.

I'm a little hesitant to make too much noise when Suricata doesn't meet the requirements. Any thoughts?

We could make `--strict-rule-keywords` with `all` or `requires` turn missing requirements into a warn and fail `-T`, but that's more perhaps of a QA level type thing, than what end users will use in combination with Suricata-Update and `-T`.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16773

**Comment by victorjulien** [comment]
I agree it should not be noisy. Perhaps only
```
Info: detect-requires: Suricata did not meet the rule requirements for sid 5: Suricata version less than required: feature output::lua, version >= 8.0.4 [DetectRequiresSetup:detect-requires.c:33]
```
(added the `for sid 5`)

I think in general we need special handling of requires, where we scan the rule for this key and parse that before anything else. Otherwise we get:
```
alert vxlan any any -> any any (requires: version >= 10; sid:1;)
alert udp any any -> any any (vxlan_vni:10; requires: version >= 10; sid:2;)
alert http any any => any any (requires: version >= 10; sid:3;)
alert tcp any any -> any any (frame:smtp.not_supported; requires: version >= 10; sid:4;)
```
resulting in errors as we error out before we consider the requires checks
```
Error: detect-parse: protocol "vxlan" cannot be used in a signature.  Either detection for this protocol is not yet supported OR detection has been disabled for protocol through the yaml option app-layer.protocols.vxlan.detection-enabled [SigParseProto:detect-parse.c:1114]
Error: detect: error parsing signature "alert vxlan any any -> any any (requires: version >= 10; sid:1;)" from file unsupported.rules at line 1 [DetectLoadSigFile:detect-engine-loader.c:180]
Error: detect-parse: unknown rule keyword 'vxlan_vni'. [SigParseOptions:detect-parse.c:907]
Error: detect: error parsing signature "alert udp any any -> any any (vxlan_vni:10; requires: version >= 10; sid:2;)" from file unsupported.rules at line 2 [DetectLoadSigFile:detect-engine-loader.c:180]
Error: detect-parse: "=>" is not a valid direction modifier, "->" and "<>" are supported. [SigParseBasics:detect-parse.c:1385]
Error: detect: error parsing signature "alert http any any => any any (requires: version >= 10; sid:3;)" from file unsupported.rules at line 3 [DetectLoadSigFile:detect-engine-loader.c:180]
Error: detect-frame: unknown frame 'not_supported' for protocol 'smtp' [DetectFrameSetup:detect-frame.c:121]
Error: detect: error parsing signature "alert tcp any any -> any any (frame:smtp.not_supported; requires: version >= 10; sid:4;)" from file unsupported.rules at line 4 [DetectLoadSigFile:detect-engine-loader.c:180]
Warning: detect: 1 rule files specified, but no rules were loaded! [SigLoadSignatures:detect-engine-loader.c:356]
Error: suricata: Loading signatures failed. [LoadSignatures:suricata.c:2405]
```

**Comment by jasonish** [comment]
> I think in general we need special handling of requires, where we scan the rule for this key and parse that before anything else. Otherwise we get:

Yeah, was already thinking about this for rule options, as its not that hard.  Pre-scanning before the protocol is a little more invasive, but I guess a necessary requirement.

**Comment by victorjulien** [comment]
Scanning for the sid would be great while at it, so we can use it in error reporting. It's generally last in the rule, so parsed lasted, but it's one of the first things we want to know in case of error :)

**Comment by jasonish** [comment]
> I agree it should not be noisy. Perhaps only
> 
> ```
> Info: detect-requires: Suricata did not meet the rule requirements for sid 5: Suricata version less than required: feature output::lua, version >= 8.0.4 [DetectRequiresSetup:detect-requires.c:33]
> ```

I didn't address this in the new PR yet as at this level I don't think we can log the line number, but in `detect-engine-loader` we can:
```
Info: detect: Skipping signature due to missing requirements: alert udp any any -> any any (vxlan_vni:10; requires: version >= 10; sid:2;) from file ./victor.rules at line 2 [DetectLoadSigFile:detect-engine-loader.c:200]
```

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/9919.

**Pull request closed without merging**
