### PR TITLE
next/662/20241207/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #12218
 - #12232

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 32421 | 36200 | 111.66% |
| .app_layer.flow.dcerpc_tcp | 40 | 43 | 107.5% |
| .app_layer.error.http.parser | 700 | 729 | 104.14% |
| .app_layer.error.ssh.parser | 124 | 128 | 103.23% |
| .ftp.memuse | 2906 | 3102 | 106.74% | 

Pipeline 23722

**Comment by inashivb** [comment]
> Information:
> 
> ERROR: QA failed on SURI_TLPR1_alerts_cmp.
> field 	baseline 	test 	%
> 	SURI_TLPR1_stats_chk 		
> .app_layer.flow.ftp 	32421 	36200 	111.66%
> .app_layer.flow.dcerpc_tcp 	40 	43 	107.5%
> .app_layer.error.http.parser 	700 	729 	104.14%
> .app_layer.error.ssh.parser 	124 	128 	103.23%
> .ftp.memuse 	2906 	3102 	106.74%
> 
> Pipeline 23722

Q1: Is the difference in stats on hitting emergency mode?
Q2: Is the FM able to see more flows after scanning the hash rows correctly in a designated time?

**Comment by victorjulien** [comment]
> Q1: Is the difference in stats on hitting emergency mode?

No, it's not hitting the emergency mode in the baseline or the PR runs.

> Q2: Is the FM able to see more flows after scanning the hash rows correctly in a designated time?

It's able to see things more timely for sure, but it's a good question why should lead to more detection. Things *should* still be covered by the packet path and shutdown timeout handling.

**Comment by jufajardini** [comment]
> It's consistent with approved original PRs.
> 
> Did you get an answer about the alerts' redistribution? I see that we are missing some, and hitting others.

Question was answered.

**Comment by jufajardini** [comment]
> > Q2: Is the FM able to see more flows after scanning the hash rows correctly in a designated time?
> 
> It's able to see things more timely for sure, but it's a good question why should lead to more detection. Things _should_ still be covered by the packet path and shutdown timeout handling.

Would it be possible that the way things are now would lead to such a waiting time that some flows would time out before they could be fully inspected, leading to less alerts before?

**Review by jufajardini — APPROVED** [review]
Consistent with approved PRs. Differences in QA checks seem to be for the better/ reflect the changes added.

**Pull request merged**
