### PR TITLE
6.0.x: issue 5868: file_data fix for http1 response files - v4

### PR DESCRIPTION
**Pull request by jasonish**
Possible fix for: https://redmine.openinfosecfoundation.org/issues/5868

Previous PR: https://github.com/OISF/suricata/pull/9063

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1225

### CODE REVIEW

**Review by victorjulien — CHANGES_REQUESTED** [review]
This is not the correct approach.

Can't just set this flag and expect things to work.

**Comment by victorjulien** [comment]
Also still missing a full analysis of the problem.

**Comment by jasonish** [comment]
My analysis hasn't really changed. Given a rule like:
```
alert http any any -> any any (msg:"PDF LOGO"; flow:established,to_client; file_data; content:"PDF"; filestore; classtype:policy-violation; sid:9000000; rev:1;)
```
the file is stored, but 0 size, due to the pruning logic at https://github.com/OISF/suricata/blob/master-6.0.x/src/util-file.c#L382. Applying the pruning logic when `FILE_USE_DETECT` is set (https://github.com/OISF/suricata/blob/master-6.0.x/src/util-file.c#L358), does fix this as shown by the S-V test.

No new information here. I've asked for help/pointers to take this further given it fixes that failing test case.

**Comment by victorjulien** [comment]
Analysis needs to go into the commit and needs to go deeper than describing that something doesn't work. See https://github.com/OISF/suricata/pull/9063#issuecomment-1607371005 for a start.

On the flag, it will have side effects that need to be described (e.g. different mechanics used for tracking progress). The fact that all of these things are missing suggest to me that this is more of a hack than a properly researched solution.

**Pull request closed without merging**
