### PR TITLE
Quic/v11

### PR DESCRIPTION
**Pull request by victorjulien**
#6794 with
- formatting fixups
- sni logging and new `quic.sni` keyword
- reduced tx creation/logging: only "long header" frames currently lead to a tx

suricata-verify-pr: 653

cc: @sharksforarms

### CODE REVIEW

**Comment by jasonish** [comment]
Only comments around logging are the CYU.  Does it need to be a list? Would be nice to show this in an S-V test.
And should the CYU be optional much like the ja3 is for TLS?

**Comment by victorjulien** [comment]
> Only comments around logging are the CYU. Does it need to be a list? Would be nice to show this in an S-V test. And should the CYU be optional much like the ja3 is for TLS?

It's stored as a list as well, and inspected as such, but I'm not sure really. The pcaps we've seen don't have multiple. @sharksforarms ?

**Comment by sharksforarms** [comment]
> > Only comments around logging are the CYU. Does it need to be a list? Would be nice to show this in an S-V test. And should the CYU be optional much like the ja3 is for TLS?
> 
> It's stored as a list as well, and inspected as such, but I'm not sure really. The pcaps we've seen don't have multiple. @sharksforarms ?

Previous discussion/change here:
https://github.com/OISF/suricata/pull/5574#discussion_r527012309

I don't have any pcaps to backup this theory.

**Comment by victorjulien** [comment]
replaced by #6813

**Pull request closed without merging**
