### PR TITLE
util-misc: Convert unittests to new FAIL/PASS API - v4

### PR DESCRIPTION
**Pull request by hadiqaalamdar**
- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6345) ticket:
Previous PR: https://github.com/OISF/suricata/pull/9661

Describe changes:
- Update `UtilMiscParseSizeStringTest01` in util-misc unit tests

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Looks good to me, thanks!

CI : ✅ 
Code :  ✅ 
Commits segmentation :  just one, ✅
Commit author:  ✅ 
Commit messages :  just one, ✅ 
Ticket number on message : ✅ 
Git ID set : ✅  
CLA :  🤔 
Doc update :  doesn´t apply
Redmine ticket :  ✅ 
Rustfmt : doesn't apply
Tests : ✅ 
Dependencies added: none

**Review by jufajardini — CHANGES_REQUESTED** [review]
Please, see previous comment :)

**Comment by hadiqaalamdar** [comment]
@jufajardini I've edited the commit message. Please let me know if anything else is required. Thanks!

**Review by jufajardini — APPROVED** [review]
All looking good to me now, thanks! :)

**Comment by jasonish** [comment]
> CLA : 🤔

Doesn't look like we have a signed CLA.

**Comment by jufajardini** [comment]
@hadiqaalamdar could you please ensure that you have signed https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html or, in case you have, make sure that the info used there is the same you are using as your author info here on git? Without that, we can't merge your contributions. Thanks a lot! :)

**Comment by hadiqaalamdar** [comment]
Just signed the agreement. Sorry, I must have overlooked it in the guide.

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #9701, thanks!

**Pull request closed without merging**
