### PR TITLE
next/442/20240516/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #11021
 - #11083
 - #11093

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1835

### CODE REVIEW

**Review by jasonish — APPROVED** [review]

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.

ERROR: QA failed on SURI_TLPR1_alerts_cmp.

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.flow.ftp | 52 | 43 | 82.69% |
| .app_layer.tx.ftp | 819 | 188 | 22.95% |
| .app_layer.error.ftp.gap | 2 | 0 | - |
| .app_layer.error.ftp.parser | 2 | 0 | - |
| .ftp.memuse | 348 | 3 | 0.86% |
| | SURI_TLPR1_stats_chk | | |
| .ftp.memuse | 11385 | 10637 | 93.43% |
| | IPS_AFP_stats_chk | | |
| .ips.blocked | 1395360 | 747360 | 53.56% |
| .ips.drop_reason.flow_drop | 1296000 | 680400 | 52.5% |
| .ips.drop_reason.applayer_error | 32400 | 0 | - |
| .flow.end.state.established | 583199 | 550799 | 94.44% |
| .flow.end.state.closed | 1016272 | 1048672 | 103.19% |
| .flow.end.tcp_state.established | 201960 | 169560 | 83.96% |
| .flow.end.tcp_state.closed | 1016272 | 1048672 | 103.19% |
| .app_layer.error.exception_policy.drop_flow | 32400 | 0 | - |
| .app_layer.error.ftp.parser | 32400 | 0 | - |
| .app_layer.flow.ftp | 33480 | 1080 | 3.23% |
| .app_layer.tx.ftp | 131760 | 2160 | 1.64% |
| | TREX_GENERIC_stats_chk | | |
| .app_layer.flow.ftp | 14871 | 0 | - |
| .app_layer.tx.ftp | 59484 | 0 | - |
| .app_layer.error.ftp.parser | 14871 | 0 | - | 

Pipeline 20659

**Comment by victorjulien** [comment]
@ct0br0 can this get a run against the updated baseline requested here https://github.com/OISF/suricata/pull/11021#issuecomment-2097481264 ? Thanks!

**Comment by suricata-qa** [comment]
CANCELED:
 
 | field | baseline | test | % |
|--|--|--|--| Pipline CANCELED. Reruns require manual intervention. 

Pipeline 20669

**Comment by ct0br0** [comment]
Have a QA run going to verify it's good. Should be fine considering we already tested against the child PR a week or so ago.

**Pull request merged**
