### PR TITLE
configure: Improved cross compilation support

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #5338 

This PR changes the run-time check for PCRE's "JIT exec" from a run-time to a compile time check for better support in cross compilation environments. Additionally, the run-time check to determine the size of a Lua integer is now guarded so it won't run on cross-compilation environments.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [3872](https://redmine.openinfosecfoundation.org/issues/3872)

Describe changes:
- Uses `AC_LINK_ELSEIF`

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by Grommish** [comment]
I pulled this to test, and I am still receiving errors:

```
configure:28329: checking for ./rust/dist
configure:28335: error: cannot check for file existence when cross compiling

```
```
uname -m = x86_64
uname -r = 5.4.0-42-generic
uname -s = Linux
```
cross compiling for ```mips64-unknown-linux-muslabi64``` under OpenWrt

See attached config.log
[config.log](https://github.com/OISF/suricata/files/5147593/config.log)

**Comment by jlucovsky** [comment]
> I pulled this to test, and I am still receiving errors:
> 
> ```
> configure:28329: checking for ./rust/dist
> configure:28335: error: cannot check for file existence when cross compiling
> ```
> 
> ```
> uname -m = x86_64
> uname -r = 5.4.0-42-generic
> uname -s = Linux
> ```
> 
> cross compiling for `mips64-unknown-linux-muslabi64` under OpenWrt
> 
> See attached config.log
> [config.log](https://github.com/OISF/suricata/files/5147593/config.log)

@jasonish Suggestions for handling this Rust-specific `configure` check?

**Comment by jasonish** [comment]
> @jasonish Suggestions for handling this Rust-specific `configure` check?

Yeah, this should be an `if test ...` instead of the macro as this check shouldn't prevent cross compilation.  I can make the fix here.

**Comment by jasonish** [comment]
> > @jasonish Suggestions for handling this Rust-specific `configure` check?
> 
> Yeah, this should be an `if test ...` instead of the macro as this check shouldn't prevent cross compilation. I can make the fix here.

See https://github.com/OISF/suricata/pull/5348

**Comment by jlucovsky** [comment]
Continued in #5350

**Pull request closed without merging**
