### PR TITLE
doc: update install instructions v9

### PR DESCRIPTION
**Pull request by lukashino**
Cherry-pick of: 5a3ecbde62c83c216caab52f53c1f7692091e045

Follow-up of https://github.com/OISF/suricata/pull/9899

Changes:
- rebase on the current master-6.0.x
- cleared unneeded dependencies
- PR comments

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5988) ticket - https://redmine.openinfosecfoundation.org/issues/5988

### CODE REVIEW

**Comment by victorjulien** [comment]
Same comment about the cherry-pick line. Please use the `-x` format.

**Comment by lukashino** [comment]
sorry about that. Should it even be kept there as the commit has changed so much already?

**Comment by victorjulien** [comment]
> sorry about that. Should it even be kept there as the commit has changed so much already?

If it feels more like a new work then we can drop the reference I think, esp if it is based your own commit.

**Comment by lukashino** [comment]
Continues in https://github.com/OISF/suricata/pull/9981

**Pull request closed without merging**
