### PR TITLE
Unify functions for multi-buffer in preparation for detection negated content + absent buffer 2224 v12.12

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6575

Describe changes:
- detect: unify multi-buffer code

#11070 rebased after merge of #11003 😢 
And also a few more unused struct defintions removals

This is required for #10334

### CODE REVIEW

**Comment by victorjulien** [comment]
Is this about negation and "absent" logic like the PR title suggests? Or is this "only" a registration cleanup/consolidation?

**Comment by catenacyber** [comment]
This is "registration cleanup/consolidation" for multi-buffer as needed for  negation and "absent" logic (#10334)

**Comment by victorjulien** [comment]
> This is "registration cleanup/consolidation" for multi-buffer as needed for negation and "absent" logic (#10334)

So if it is a preparation PR, shouldn't the title reflect that?

**Comment by victorjulien** [comment]
The title matters to a reviewer. Got confused and started looking if I had missed things in the code.

**Comment by catenacyber** [comment]
PR renamed

**Review by victorjulien — APPROVED** [review]
Nice cleanup and LoC reduction.

**Comment by inashivb** [comment]
> #11070 rebased after merge of #11003 😢 

Sorry about that 😓

**Comment by victorjulien** [comment]
Merged in #11139, thanks!

**Pull request closed without merging**
