### PR TITLE
detect: fix memory leak when parsing signature

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5529

Describe changes:
- detect: fix memory leak when parsing signature with frames

`break` wrongly introduced by https://github.com/OISF/suricata/commit/40c315aa35d277653dd6bb46cdaab6af71499df2

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10416

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10420

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10429

**Comment by victorjulien** [comment]
Can you add an explanation of the issue into the git commit message?

**Comment by catenacyber** [comment]
> Can you add an explanation of the issue into the git commit message?

I would like to, but I do not really understand what this code is doing.
I just noticed similar patterns did not have `break` and tested that this was solving it.

Why was this `break` added ?
And I somehow bet transforms make that "Frames?" May have multiple "Detect engines ?" (I do not get it about directions)

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 1485328128 | 262.83% | 

Pipeline 10495

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103956 | 81.07% | 

Pipeline 10614

**Comment by victorjulien** [comment]
Merged in #8187, thanks!

**Pull request closed without merging**
