### PR TITLE
http: code simplification

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5921

Describe changes:
- http: code simplification to avoid one direct usage of `htp_list_get`

```
LIBHTP_BRANCH=pr/416
```
https://github.com/OISF/libhtp/pull/416

### CODE REVIEW

**Comment by victorjulien** [comment]
Is the libhtp PR a requirement or just a way to get it tested in Suricata CI (in the future, please state this in a PR)

**Comment by catenacyber** [comment]
> Is the libhtp PR a requirement or just a way to get it tested in Suricata CI (in the future, please state this in a PR)

The libhtp PR is not a requirement.

It is a bit mote than a way to get it tested in CI, as it is related (code optimizations after release for the same redmine issue)

**Comment by victorjulien** [comment]
Typo in commit `tw_id` instead of `tx_id`?

**Comment by catenacyber** [comment]
> Typo in commit `tw_id` instead of `tx_id`?

Right, see #10368

**Pull request closed without merging**
