### PR TITLE
Next/20200305/v2

### PR DESCRIPTION
**Pull request by victorjulien**
Cleanups for recent threading/pcap patches.
#4629 
Cherry-picked all but the mtu patches from #4632 

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
Passed

### CODE REVIEW

**Comment by catenacyber** [comment]
I am still modifying some of these commits with detect-icmpv6hdr-v5 (CI running)

**Comment by victorjulien** [comment]
> I am still modifying some of these commits with detect-icmpv6hdr-v5 (CI running)

Which ones?

**Comment by catenacyber** [comment]
only detect-tcpmss.c for sed s/TRUE/true/`

**Comment by catenacyber** [comment]
I can rebase on top of new master no problem :-)

**Comment by victorjulien** [comment]
> only detect-tcpmss.c for sed s/TRUE/true/`

Ok dropping that patch and merging the rest.

**Comment by victorjulien** [comment]
Merged w/o d17848d

**Pull request closed without merging**
