### PR TITLE
Pcre2 3194 v18

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3194
https://redmine.openinfosecfoundation.org/issues/4446

Describe changes:
- migrate all pcre1 code to pcre2
- fuzz: builds fuzz_sigpcap_aware only when asked (ie ./configure --enable-fuzztargets)
- qa : remove some obsolete files
- pcrexform : checks that we have exactly one substring capture in a signature
- transforms : use generic `Free` functions everywhere

suricata-verify-pr: 502

https://github.com/OISF/suricata-verify/pull/502

Replaces https://github.com/OISF/suricata/pull/6330 with code comments taken into account

Should I make a PR with the first 4 preliminary commits ? (like transform: use generic Free function)
The completeness of the commit about `PCRE2_ERROR_UNSET` needs to be carefully reviewed : should it become the generic case ?

I bet CI commit-check will fail

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you check why the commit-check CI test fails?

**Comment by catenacyber** [comment]
> Can you check why the commit-check CI test fails?

Discussion continued from https://github.com/OISF/suricata/pull/6330#discussion_r711132331

commit check indeed fails.
It cannot build the first commits without PCRE1, and it uses only the latest `.github` files version

I can split the last commit removing PCRE1 in two :

- the last part only for CI .github files, in a next PR
- the first part about configure.ac and everything else

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4341

**Comment by victorjulien** [comment]
> > Can you check why the commit-check CI test fails?
> 
> Discussion continued from [#6330 (comment)](https://github.com/OISF/suricata/pull/6330#discussion_r711132331)
> 
> commit check indeed fails.
> It cannot build the first commits without PCRE1, and it uses only the latest `.github` files version
> 
> I can split the last commit removing PCRE1 in two :
> 
> * the last part only for CI .github files, in a next PR
> * the first part about configure.ac and everything else

Ok so I think we should just add pcre2 as a dependency in the github workflows for now, and remove pcre1 from it when the PR is merged.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6413

**Pull request closed without merging**
