### PR TITLE
Tcp chunk size updates/v2

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | IPS_AFP_stats_chk | | |
| .flow.end.state.established | 550799 | 583199 | 105.88% |
| .flow.end.tcp_state.established | 169560 | 201960 | 119.11% | 

Pipeline 13539

**Comment by inashivb** [comment]
> Information:
> 
> ERROR: QA failed on IPS_AFP_drop_chk.
> field 	baseline 	test 	%
> 	IPS_AFP_stats_chk 		
> .flow.end.state.established 	550799 	583199 	105.88%
> .flow.end.tcp_state.established 	169560 	201960 	119.11%
> 
> Pipeline 13539

Probably worth figuring out what does this change 🤔

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on IPS_AFP_drop_chk.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113274 | 144972 | 127.98% |
| | IPS_AFP_stats_chk | | |
| .flow.end.state.established | 550799 | 583199 | 105.88% |
| .flow.end.tcp_state.established | 169560 | 201960 | 119.11% | 

Pipeline 13559

**Comment by ct0br0** [comment]
Ignore the IPS checks on this. It looks like the 'engine fixes' PR was merged.

**Comment by inashivb** [comment]
After discussion, the extra 33% chunk data in case of large payloads is to ensure we have some pattern and initial data for the next segments. Closing this PR as it does not make sense to remove that condition then.

**Pull request closed without merging**
