### PR TITLE
dns: parse SRV records - v2

### PR DESCRIPTION
**Pull request by satta**
Previous PR: https://github.com/OISF/suricata/pull/5525

Describe changes (to previous PR):
- Remove `NS` and `NULL` handling.
- Restructure commits.
- Use `NS` parsing function using `rest()`.

### CODE REVIEW

**Comment by jasonish** [comment]
Looks good. Do you have a PCAP we can use for an S-V test. None of the pcaps in S-V at this time seem to output any SRV records.

Thanks.

**Comment by satta** [comment]
> Looks good. Do you have a PCAP we can use for an S-V test. None of the pcaps in S-V at this time seem to output any SRV records.

Done, see https://github.com/OISF/suricata-verify/pull/356

**Comment by jasonish** [comment]
Thanks. All looks good. Just unsure about the "raw" in the SRV records, its not something we've typically logged. Do you find this useful to have in your event feed?

**Comment by satta** [comment]
> Just unsure about the "raw" in the SRV records, its not something we've typically logged. Do you find this useful to have in your event feed?

The idea is to have an uninterpreted byte log to possibly reconstruct the traffic for both directions of a tunnel from the EVE. That would require serializing the parsed structure back to bytes without the `raw` field, that's why I added it. If we can find a more idiomatic solution for this, I'd be happy to implement it ;)

**Comment by jasonish** [comment]
> The idea is to have an uninterpreted byte log to possibly reconstruct the traffic for both directions of a tunnel from the EVE. That would require serializing the parsed structure back to bytes without the `raw` field, that's why I added it. If we can find a more idiomatic solution for this, I'd be happy to implement it ;)

How much of this data would exist in a true tunnel? I'd worry about performance when a tunnel is opened due to the amount of data that may need to be written to the log file.  Would base64 be better rather than our somewhat hacky method of encoding non-printable characters?

**Comment by satta** [comment]
> > The idea is to have an uninterpreted byte log to possibly reconstruct the traffic for both directions of a tunnel from the EVE. That would require serializing the parsed structure back to bytes without the `raw` field, that's why I added it. If we can find a more idiomatic solution for this, I'd be happy to implement it ;)
> 
> How much of this data would exist in a true tunnel? I'd worry about performance when a tunnel is opened due to the amount of data that may need to be written to the log file. 

No idea but I would guess it's pretty limited. Maybe it also would be best to make this field optional, to reduce content duplication if raw DNS rdata dumping is not required?

> Would base64 be better rather than our somewhat hacky method of encoding non-printable characters?

Maybe. It would probably best to stick with the format also used for the `payload` fields.

**Comment by jasonish** [comment]
> > > The idea is to have an uninterpreted byte log to possibly reconstruct the traffic for both directions of a tunnel from the EVE. That would require serializing the parsed structure back to bytes without the `raw` field, that's why I added it. If we can find a more idiomatic solution for this, I'd be happy to implement it ;)
> > 
> > 
> > How much of this data would exist in a true tunnel? I'd worry about performance when a tunnel is opened due to the amount of data that may need to be written to the log file.
> 
> No idea but I would guess it's pretty limited. Maybe it also would be best to make this field optional, to reduce content duplication if raw DNS rdata dumping is not required?
> 
> > Would base64 be better rather than our somewhat hacky method of encoding non-printable characters?
> 
> Maybe. It would probably best to stick with the format also used for the `payload` fields.

Ok. How about we kill this raw field as part of this PR.. I can do that if you don't mind, I have some changes already applied on top of this around clippy cleanups and a rustfmt of the DNS module I'm hoping to get in soon.

Then make it optional. I would be nice to see a pcap of a real tunnel and just how much data would get logged in that case.

**Comment by satta** [comment]
[...]
> Ok. How about we kill this raw field as part of this PR.. I can do that if you don't mind, I have some changes already applied on top of this around clippy cleanups and a rustfmt of the DNS module I'm hoping to get in soon.

OK, let's do that then.

> Then make it optional. I would be nice to see a pcap of a real tunnel and just how much data would get logged in that case.

The OP of the original Redmine ticket (https://redmine.openinfosecfoundation.org/issues/3663) posted one. Obviously, in the end the total amount of logged data depends on the full amount of data transferred over the tunnel, but the amount of data logged within a _single_ DNS answer is sure limited.

**Comment by victorjulien** [comment]
Merged through #5641, thanks!

**Pull request closed without merging**
