### PR TITLE
[RFC} doc: dataset doc updates

### PR DESCRIPTION
**Pull request by jmtaylor90**
Signed-off-by: jason taylor <jtfas90@gmail.com>

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- update global yaml formatting
- update rule example
-

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by jmtaylor90** [comment]
If the rule example update is agreeable, I can update the http user-agent example as well.

I was also wondering if we want an example snippet of the global yaml config in the suricata.yaml? If so should that be a part of this PR or an additional PR?

**Comment by victorjulien** [comment]
Yeah. Should probably be after https://redmine.openinfosecfoundation.org/issues/3143 gets done though.

**Comment by jmtaylor90** [comment]
> Yeah. Should probably be after https://redmine.openinfosecfoundation.org/issues/3143 gets done though.

Okay sounds good, is that ticket going to handle these changes or do you want a separate redmine? (I can assign to myself if you want)

**Comment by jmtaylor90** [comment]
continued in https://github.com/OISF/suricata/pull/4315

**Pull request closed without merging**
