### PR TITLE
docs - add docutils.conf to disable smart quotes

### PR DESCRIPTION
**Pull request by wesinator**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Disable use of stupid Unicode smart quotes in readthedocs

fixes examples such as https://suricata.readthedocs.io/en/latest/rules/dns-keywords.html#dns-query 

image
-----

Regards,

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by norg** [comment]
AFAIR we already thought about that. The Build fail is not due to this IMHO.

**Comment by wesinator** [comment]
> AFAIR we already thought about that. The Build fail is not due to this IMHO.

I submitted a PR for this earlier but it wasn't clean and didn't seem to get merged. 
this one is good. 

thanks and regards,

**Comment by jlucovsky** [comment]
LGTM

**Review by jlucovsky — APPROVED** [review]

**Comment by wesinator** [comment]
@jlucovsky can you merge this ? 

thx

**Comment by victorjulien** [comment]
Sorry just getting back to this now, could you set a proper git author? I can also do it for you on merge if you let me know what it should be. We use "Firstname Lastname <email>"

**Comment by victorjulien** [comment]
Merged after rebase in #8829, thanks Wes!

**Pull request closed without merging**
