### PR TITLE
Enip rust 3958 v10

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3958

Describe changes:
- convert enip parser to rust
- integer keywords now support hexadecimal notation

Alon the way, also
- transactions are now bidirectional
- there is a enip logger
- gap support is improved with probing for resync
- frames
- events
- enip_command keyword accepts now string enumeration as values.
- more keywords

#10072 with rust style imroved as suggested per Jason

```
SV_BRANCH=pr/1521
```
https://github.com/OISF/suricata-verify/pull/1521

Does the first commit deserve its own redmine ticket ?
And the one in https://github.com/OISF/suricata/pull/9945/commits/4a493528fa694e50a5f0bbd1f92167e2ba9241e7 also ?

### CODE REVIEW

**Comment by victorjulien** [comment]
Yeah, please add tickets for those detect improvements. Will also need doc and SV updates. Might be good to break it out into its own PR.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17169

**Comment by catenacyber** [comment]
> Yeah, please add tickets for those detect improvements. Will also need doc and SV updates. Might be good to break it out into its own PR.

Tracking ticket https://redmine.openinfosecfoundation.org/issues/6644

**Review by jufajardini — COMMENTED** [review]
Doc changes look good to me! Do I understand correctly that many of the new enip keywords descriptions can later on be updated, once https://github.com/OISF/suricata/pull/10122 gets merged?

**Comment by catenacyber** [comment]
> Do I understand correctly that many of the new enip keywords descriptions can later on be updated, once #10122 gets merged?

Correct indeed

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/10178

**Pull request closed without merging**
