### PR TITLE
Integer overflow 4516 v5

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4516

Describe changes:
- Avoids some warnings about integers

Obviously not complete yet... But still mergeable ?

Replaces #6583 with
- more warning fixes
- including more true fixes
- including fix ENIP connection with more than 65k transactions 

libhtp-pr: 338

I also discovered a style issue : removing explicit useless casts such as
```
uint64_t t = 0;
uint64_t x = 1;
x = (uint64_t) t;
```
Is there some automated tool to do this ? 
(and remove the `#if 0` as well ?)

### CODE REVIEW

**Review by jufajardini — COMMENTED** [review]
Just a nit. Saw typos in:
- https://github.com/OISF/suricata/pull/6628/commits/894e5d660da2831b82a4177095c6fb40dc0697e8 - `Aso`
- https://github.com/OISF/suricata/pull/6628/commits/df2f35f139d20ede5e77248e7fdee77143278948 - `then`

**Comment by catenacyber** [comment]
Thanks Juliana, reworded and force-pushed

**Comment by victorjulien** [comment]
Can you address the commit messages to be more consistent?

`source: remove unused code for pcap files` -> `source/pcap: ...`
`warnint: fix app-layer-dnp3.c` -> `dnp3: fix int warnings`
prefixes seem almost random now
etc

**Comment by victorjulien** [comment]
I seem to miss the `turn into draft PR` button, or maybe I'm blind. But can you turn this into a draft?

**Comment by suricata-qa** [comment]
Information:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.memuse | 537994688 | 509179328 | 105.66% |
| | generic_stats_chk |
| .flow.spare | 1983667 | 1866612 | 106.27% | 

Pipeline 5033

**Comment by catenacyber** [comment]
> Can you address the commit messages to be more consistent?
> 
> `source: remove unused code for pcap files` -> `source/pcap: ...` `warnint: fix app-layer-dnp3.c` -> `dnp3: fix int warnings` prefixes seem almost random now etc

New version in https://github.com/OISF/suricata/pull/6636
I find the old one using `warnint` (and one changed file per commit) more consistent 
So, I guess I misunderstand what you are expecting...

**Pull request closed without merging**
