### PR TITLE
util/thash: decrease memuse if array was allocated

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7135

Describe changes:
- util/thash: decrease memuse only if array was allocated

### CODE REVIEW

**Comment by catenacyber** [comment]
cc @inashivb commit f1b44ca8c7ed35a7c6add1c427327fef2b843046 https://github.com/OISF/suricata/pull/11402

**Review by inashivb — APPROVED** [review]
LGTM 🚀 

Please note that this was a pre-existing issue just discovered due to assertion check added in https://github.com/OISF/suricata/commit/f1b44ca8c7ed35a7c6add1c427327fef2b843046
Thank you! :)

**Comment by catenacyber** [comment]
> LGTM 🚀
> 
> Please note that this was a pre-existing issue just discovered due to assertion check added in [f1b44ca](https://github.com/OISF/suricata/commit/f1b44ca8c7ed35a7c6add1c427327fef2b843046) Thank you! :)

Indeed 👍

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21371

**Comment by victorjulien** [comment]
Merged in #11431, thanks!

**Pull request closed without merging**
