### PR TITLE
Detect log alert tx one 7199 v8.2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7449
https://redmine.openinfosecfoundation.org/issues/7199

Describe changes:
- document more guess-applayer-tx
- improves guess-applayer-tx for unidirectional protocol such as DNS

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2180

#12266 with suricata.yaml.in changes as proposed in #12260

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23921

**Comment by jufajardini** [comment]
> @jufajardini @jasonish remind me, why do we want to test with SV task-7018-dns-ips-stream-rule that `oisf.net` gets logged when you want to alert on `suricata` ? This looks wrong to me.
> 
> Rule is https://github.com/OISF/suricata-verify/blob/master/tests/dns/task-7018-dns-ips-stream-rule/test.rules
> 
> The third and fourth alert https://github.com/OISF/suricata-verify/blob/master/tests/dns/task-7018-dns-ips-stream-rule/test.yaml#L138 (lines 121 - 141)
> 
> I understand why the code does that but I do not understand why we want to enforce this behavior with the test...

I see your point. I think I created a test that was descriptive of what we had, and that was the result. 

I wonder if at some point we could have a more precise processing, and then we wouldn't even have that mismatch. In which case removing this check makes sense.

**Comment by jasonish** [comment]
> @jufajardini @jasonish remind me, why do we want to test with SV task-7018-dns-ips-stream-rule that `oisf.net` gets logged when you want to alert on `suricata` ? This looks wrong to me.
> 
> Rule is https://github.com/OISF/suricata-verify/blob/master/tests/dns/task-7018-dns-ips-stream-rule/test.rules
> 
> The third and fourth alert https://github.com/OISF/suricata-verify/blob/master/tests/dns/task-7018-dns-ips-stream-rule/test.yaml#L138 (lines 121 - 141)
> 
> I understand why the code does that but I do not understand why we want to enforce this behavior with the test...

If I recall correctly, this was confusing behavior. Your alerting on `suricata`, but get an alert with `oisf.net` in the metadata.  We're not necessarily enforcing it with a test, we're just capturing current behavior so we know when it changes, as that is important and should be explained/documented by updating a test at least.

**Comment by catenacyber** [comment]
Thanks, next version in https://github.com/OISF/suricata/pull/12306

I put a comment in the SV check that this was not the desired behavior and added a reference to the ticket 7004 about it...

**Pull request closed without merging**
