### PR TITLE
Applayer plugin 5053 v3.5

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
Preliminary work for https://redmine.openinfosecfoundation.org/issues/5053

Describe changes:
- get ready to use dynamic number of app-layer protos (also work with static constant) in some places
- preventive fix of macro with parenthesis cc @jufajardini 

#11572 next round

#11795 with comments taken into account

Still more work to do after : 
Only `AppProtoStrings` is to be handled, but it is the big one.

And then take remaining commits out of https://github.com/OISF/suricata/pull/11321
And supply an example of an app-layer plugin

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23058

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/11987

**Comment by victorjulien** [comment]
> Could we remove ALPROTO_TEST as the tests do not make sense to me ?

What about them doesn't make sense?

**Comment by catenacyber** [comment]
> > Could we remove ALPROTO_TEST as the tests do not make sense to me ?
> 
> What about them doesn't make sense?

Registering a alproto with a parser function that always fails, and just testing that `AppLayerParserParse` returned -1. Would you not get the same result without registering a parser function, or using `ALPROTO_FAILED` as argument to `AppLayerParserParse` ?

The comment says "Test the deallocation of app layer parser memory on occurrence of error in the parsing process." but I do not see such a thing, is there ?

No big deal, but I do not see the point of these tests...

**Comment by victorjulien** [comment]
> > > Could we remove ALPROTO_TEST as the tests do not make sense to me ?
> > 
> > 
> > What about them doesn't make sense?
> 
> Registering a alproto with a parser function that always fails, and just testing that `AppLayerParserParse` returned -1. Would you not get the same result without registering a parser function, or using `ALPROTO_FAILED` as argument to `AppLayerParserParse` ?
> 
> The comment says "Test the deallocation of app layer parser memory on occurrence of error in the parsing process." but I do not see such a thing, is there ?
> 
> No big deal, but I do not see the point of these tests...

I'm fine with removing them.

**Comment by catenacyber** [comment]
> I'm fine with removing them.

Done in https://github.com/OISF/suricata/pull/12051

**Pull request closed without merging**
