### PR TITLE
configure: use classification.config gen by suricata-update

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4136

### CODE REVIEW

**Comment by inashivb** [comment]
@jasonish don't know if this is blatantly wrong but thought of following https://github.com/inashivb/suricata/commit/9d7a497cc168cf3917c1fd7b68daf0fb27e22722 

Q: Should `classification.config` be allowed to load from places other than rule dir if we're enforcing rule dir?

**Comment by jasonish** [comment]
My `suricata.yaml` in my dev tree now has this:
```
classification-file: /opt/suricata/7.0.0-dev/var/lib/suricata/rulesclassification.config
```
(missing slash)

**Review by jasonish — CHANGES_REQUESTED** [review]
Path issue.

**Comment by inashivb** [comment]
> My `suricata.yaml` in my dev tree now has this:
> 
> ```
> classification-file: /opt/suricata/7.0.0-dev/var/lib/suricata/rulesclassification.config
> ```
> 
> (missing slash)

Clearly didn't test it. Sorry about this. :disappointed:

**Comment by norg** [comment]
I overall agree with @jasonish as long as we ensure it's documented in a way that it's easy to spot.

The only thing that I don't like about the result is the fact, that we have the config part with all 3 (classification, reference and threshold) stuck together and a user might be asking why is just one in a different location.

One might argue that threshold is commented by default.

From my experience it is not as much in use as it would be a big problem to change that part. But config files related to rules should stick together in a way?

**Comment by jasonish** [comment]
> I overall agree with @jasonish as long as we ensure it's documented in a way that it's easy to spot.
> 
> The only thing that I don't like about the result is the fact, that we have the config part with all 3 (classification, reference and threshold) stuck together and a user might be asking why is just one in a different location.
> 
> One might argue that threshold is commented by default.
> 
> From my experience it is not as much in use as it would be a big problem to change that part. But config files related to rules should stick together in a way?

The way I see it, reference.config and classification.config are usually handled by us (Suricata) or rule writers. So don't really need to be in a user configuration directory.  But threshold.config is designed to be a file that is edited by the end-user, and not distributed by rule vendors or us (other than an empty stub).  

But yeah, documentation is pretty key here.

**Comment by victorjulien** [comment]
Agree with Jasons suggestions.

**Pull request closed without merging**
