### PR TITLE
Smb hashmap/v2

### PR DESCRIPTION
**Pull request by victorjulien**
https://redmine.openinfosecfoundation.org/issues/5672

### CODE REVIEW

**Comment by victorjulien** [comment]
I don't feel https://github.com/OISF/suricata/pull/11716/commits/2c8a42cafe3136fda4570005b13a212c7e064ad7 actually is an improvement, so probably better to just suppress clippy on this.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22391

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 22394

**Comment by victorjulien** [comment]
replaced by #11721

**Pull request closed without merging**
