### PR TITLE
Port grouping redo/v17.1

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1662

Takes #10493:
- rebase to master
- replace insert sort by qsort
- minor int handling fixup

Brings the `-T` test time down from 3:30 to 1:05 in my system compared to #10493.

### CODE REVIEW

**Comment by victorjulien** [comment]
perf report
image

**Comment by victorjulien** [comment]
CopySigs, which is a wrongly named, is another place to see if we can shave some time off. It is really just merging two bitarrays. We can probably do that much faster.

**Comment by victorjulien** [comment]
> CopySigs, which is a wrongly named, is another place to see if we can shave some time off. It is really just merging two bitarrays. We can probably do that much faster.

SIMD might be able to help here. Looking at some of the memcmp SIMD code for inspiration. Would require us to change allocation sizes and ideally use aligned allocations. Perhaps worth a ticket.

**Comment by victorjulien** [comment]
I suspect the failures in mac, windows, are related to my stack allocation of "array". Should switch that to a heap allocation.

**Comment by victorjulien** [comment]
Some numbers

```
laptop AMD Ryzen 7 PRO 4750U

v17
Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real	3m27,080s
user	3m25,832s
sys	0m1,231s
 

v17.1

Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real	1m5,092s
user	1m4,737s
sys	0m0,331s
```

Desktop
```
Intel Xeon w-2245

master
Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real    11m35,876s
user    11m35,656s
sys     0m0,199s

v15
Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real    2m7,348s
user    2m7,116s
sys     0m0,230s

v16
Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real    2m6,239s
user    2m5,904s
sys     0m0,332s

v17
Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real    1m29,380s
user    1m29,076s
sys     0m0,303s

v17.1
Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]

real    1m3,174s
user    1m2,898s
sys     0m0,276s
```

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 101 | 121 | 119.8% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 651 | 706 | 108.45% | 

Pipeline 18714

**Comment by inashivb** [comment]
> Some numbers
> 
> ```
> laptop AMD Ryzen 7 PRO 4750U
> 
> v17
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real	3m27,080s
> user	3m25,832s
> sys	0m1,231s
>  
> 
> v17.1
> 
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real	1m5,092s
> user	1m4,737s
> sys	0m0,331s
> ```
> 
> Desktop
> 
> ```
> Intel Xeon w-2245
> 
> master
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real    11m35,876s
> user    11m35,656s
> sys     0m0,199s
> 
> v15
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real    2m7,348s
> user    2m7,116s
> sys     0m0,230s
> 
> v16
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real    2m6,239s
> user    2m5,904s
> sys     0m0,332s
> 
> v17
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real    1m29,380s
> user    1m29,076s
> sys     0m0,303s
> 
> v17.1
> Notice: suricata: Configuration provided was successfully loaded. Exiting. [SuricataMain:suricata.c:2970]
> 
> real    1m3,174s
> user    1m2,898s
> sys     0m0,276s
> ```

Thanks. This explains the discrepancies b/w your and my results. Didn't know processor would make that big of a difference.

**Comment by victorjulien** [comment]
replaced by #10500

**Pull request closed without merging**
