### PR TITLE
doc/copyright: Update copyright dates for dev/user guide

### PR DESCRIPTION
**Pull request by jlucovsky**
This PR updates the document tools to use the current year as the range end (user guide) or single date (dev guide).

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [5046](https://redmine.openinfosecfoundation.org/issues/5046)

Describe changes:
- Dynamically determine year

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
@jufajardini will the dev guide still have its own config when we move into a userguide chapter?

**Comment by jufajardini** [comment]
> @jufajardini will the dev guide still have its own config when we move into a userguide chapter?

According to our latest conversations, no, those shall be removed.

**Review by jufajardini — COMMENTED** [review]
The change itself looks good to me, we just won't be using config file for the devguide anymore, so that part can go... If you want, I can do my changes on top of yours, and edit the commit which adds the change for the devguide, to omit this part.

**Comment by jlucovsky** [comment]
> The change itself looks good to me, we just won't be using config file for the devguide anymore, so that part can go... If you want, I can do my changes on top of yours, and edit the commit which adds the change for the devguide, to omit this part.

I can remove the devguide commit -- but, if you're working on this for 7.0, as long as the copyright year issue is addressed, I can also close this PR. The change I made is tiny ... please feel free to use it or similar in your work.

**Comment by jufajardini** [comment]
> > The change itself looks good to me, we just won't be using config file for the devguide anymore, so that part can go... If you want, I can do my changes on top of yours, and edit the commit which adds the change for the devguide, to omit this part.
> 
> I can remove the devguide commit -- but, if you're working on this for 7.0, as long as the copyright year issue is addressed, I can also close this PR. The change I made is tiny ... please feel free to use it or similar in your work.

Yes, that should be in for 7. Alright, I think I'll use yours, since it works, no point in wasting effort :)

**Comment by jlucovsky** [comment]
Added in e0c8dba7ac6eaa757daf80245688f9f2b2496eff

**Pull request closed without merging**
