### PR TITLE
 eve/tls: reimplement basic and extended logging in terms of custom - v3

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/11991

Fix uninitialized memory issue, plus flags cleanup.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23142

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #12004, thanks!

**Comment by catenacyber** [comment]
I have a new error compiling

```
output-json-tls.c:102:5: error: initializer element is not constant
     BASIC_FIELDS |
     ^~~~~~~~~~~~
```

Is that expected ?

**Comment by jasonish** [comment]
> I have a new error compiling
> 
> ```
> output-json-tls.c:102:5: error: initializer element is not constant
>      BASIC_FIELDS |
>      ^~~~~~~~~~~~
> ```
> 
> Is that expected ?

Do you have some extra warnings enabled that we don't in CI?

**Comment by jasonish** [comment]
@catenacyber Can you try https://github.com/OISF/suricata/pull/12022?  I haven't seen this error, but after a bit of research I understand it can happen.

**Comment by catenacyber** [comment]
Compiles :-)

**Pull request closed without merging**
