### PR TITLE
af-xdp: add af-xdp capture source v4

### PR DESCRIPTION
**Pull request by rmcconnell-r7**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3306

Replaces: #8197

Describe changes:
- Updated documentation to enhance Linux tunable's description
- Documentation updated to correct indentation error for ``threads``
- Added function header to describe ``AFXDPReleasePacket()``
- Refactored ``SysFsWriteValue()`` to eliminate ``TOCTTOU`` race condition
- Improved warning message displayed in ``ConfigureBusyPolling()``
- Corrected ``runmode-af-xdp.h`` starting line

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
Restarted the failing CI jobs and now they are green. Issue was some network failure in the jobs, unrelated to the PR.

**Comment by victorjulien** [comment]
Merged in #8237, thanks a lot @rmcconnell-r7 and @gtedesco-r7!

**Comment by lukashino** [comment]
@victorjulien @rmcconnell-r7 
I might be out of loop but considering my work on #8330, does AF_XDP support IPS mode? 
If so, does it call `EngineModeSetIPS`? (if not it might need a fix)

**Comment by vincentmli** [comment]
> @victorjulien @rmcconnell-r7 I might be out of loop but considering my work on #8330, does AF_XDP support IPS mode? If so, does it call `EngineModeSetIPS`? (if not it might need a fix)

@lukashino based on the commit message

"
This feature currently only supports receiving packets via AF_XDP,
no TX support has been developed.
"
I guess IPS mode is not supported if IPS requires TX?

**Comment by lukashino** [comment]
@vincentmli ah cool thanks!

**Pull request closed without merging**
