### PR TITLE
next/575/70x/20240913/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #11751
 - #11759
 - #11775

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2042

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 141 | 146 | 103.55% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 644 | 683 | 106.06% | 

Pipeline 22623

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 644 | 696 | 108.07% | 

Pipeline 22624

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22626

**Comment by jufajardini** [comment]
Shouldn't the SV branch include the tests for Jeff's backports, too?

**Comment by victorjulien** [comment]
Too much QA variation

**Pull request closed without merging**
