### PR TITLE
Convert byte_extract keyword parser to Rust

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #11344 

Convert the byte_extract option parser from C to Rust.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6873](https://redmine.openinfosecfoundation.org/issues/6873)

Describe changes:
- Refactor code in rust/src/detect to support re-usability
- Implement the byte_extract parser in Rust, with unittests
- Modify the existing byte_extract module to use the Rust parser

Updates:
- Rebase

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by victorjulien** [comment]
What was done about the alert deviation?

**Comment by ct0br0** [comment]
Talked with Jeff. Made an issue to track it. Still chasing the other issues going on right now with release qa-rebase and potential hardware issue.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21325

**Comment by jlucovsky** [comment]
> What was done about the alert deviation?

A QA re-run happened and there were no alert deviations.

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11447, thanks!

**Pull request closed without merging**
