### PR TITLE
Backports 6.0.5 20210113/v4

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:

- https://redmine.openinfosecfoundation.org/issues/4896
- https://redmine.openinfosecfoundation.org/issues/4837
- https://redmine.openinfosecfoundation.org/issues/4822

- https://redmine.openinfosecfoundation.org/issues/4818
https://github.com/OISF/suricata/commit/0e70958e67398f599b77ba991dc631e025cae5f4 backported,
https://github.com/OISF/suricata/commit/c1bffa9545b8aa9d0fc64ac6511edd34919135d7 was already in the branch.

- https://redmine.openinfosecfoundation.org/issues/4744
- https://redmine.openinfosecfoundation.org/issues/4467
- https://redmine.openinfosecfoundation.org/issues/4933
- https://redmine.openinfosecfoundation.org/issues/4978
- https://redmine.openinfosecfoundation.org/issues/4971
- https://redmine.openinfosecfoundation.org/issues/4960
- https://redmine.openinfosecfoundation.org/issues/4958
- https://redmine.openinfosecfoundation.org/issues/4954
- https://redmine.openinfosecfoundation.org/issues/4791

suricata-verify-pr: 661

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR: QA failed on tlpw1_files_sha256.

ERROR: QA failed on tlpw1_files_md5.
  

Pipeline 5826

**Comment by inashivb** [comment]
@catenacyber is the fuzz failure for me to fix?

**Comment by catenacyber** [comment]
Oh, It looks like this is the leak from PCRE1 itself 
```
#include <pcre.h>
#include <stdio.h>

int main() {
        int ec;
    const char *eb;
    int eo;
    char *s = "\xFpiwSobYokYidpg0Y>iw(?J)ddnp3tcp.mssp|http.krA(?(<piwSobYFko>)(?<ppi>/?(?<pi>/?(?<pi>/
?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<piFko>
/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/Y(?<pi>/?(?<pi>/??<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?
<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?tls_cert_valid(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<xi>/
?(?<pi>/?(?<pi><piwSobYFko>/?(?<pi>/?(?)<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi
>/?(?<pi>(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>(?<pi>/?(?<pi><piwSobYFko>/?(?<pi>/?(?<pi>(?
<pi>/?(?<pi>/?(?<pi>/?(?<pi>1?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pl3_protoi>/?(?<pi>/?(?<pi>/?(?<pi>/?(?<pi
><pi>/?(?<pi>/?(?<pi><pi>/?(?<pi>/?(?<pi>)))))))))))))))))))))))))))))))(?<pi>ob\"okF>)(?<pikF>)S.obYokYnp4
p|tk/\"4";
    pcre *p = pcre_compile2(s, 4096, &ec, &eb, &eo, NULL);
    printf("lol %p\n", p);
    return 0;
}
```

So, I do not think we can fix it...

**Comment by victorjulien** [comment]
Is there an upstream ticket for this?

**Pull request merged**
