### PR TITLE
next/568/70x/20240909/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #11703
 - #11730

### CODE REVIEW

**Comment by catenacyber** [comment]
CIFuzz failure is due to serde update in master

**Comment by inashivb** [comment]
> CIFuzz failure is due to serde update in master

So confused at this. The update was not in `main-7.0.x` though. So, why is this affected by `master`?

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22488

**Review by jufajardini — APPROVED** [review]

**Pull request merged**
