### PR TITLE
detect: xor transform

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3285

Describe changes:
- Adds xor as transform

suricata-verify-pr: 574
https://github.com/OISF/suricata-verify/pull/574

Replaces #6550 with one improved error message

### CODE REVIEW

**Comment by catenacyber** [comment]
Did this segfault cocci ?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.wrk.flows_evicted | 5308068 | 4693221 | 113.1% |
| .flow.mgr.rows_maxlen | 115 | 539 | 21.34% |
| | generic_stats_chk |
| .decoder.pkts | 75477019 | 592348659 | 12.74% |
| .decoder.bytes | 63982463257 | 511152628311 | 12.52% |
| .decoder.ipv4 | 75477019 | 592348659 | 12.74% |
| .decoder.ethernet | 75477019 | 592348659 | 12.74% |
| .decoder.tcp | 53338133 | 410062810 | 13.01% |
| .decoder.udp | 22138886 | 182285849 | 12.15% |
| .flow.udp | 188705 | 478913 | 39.4% |
| .flow.wrk.spare_sync | 24009 | 21123 | 113.66% |
| .flow.wrk.flows_evicted_needs_work | 96118 | 2115832 | 4.54% |
| .flow.wrk.flows_evicted_pkt_inject | 191500 | 4053274 | 4.72% |
| .flow.wrk.flows_evicted | 527787 | 77373 | 682.13% |
| .flow.wrk.flows_injected | 95537 | 2090456 | 4.57% |
| .flow.mgr.flows_timeout | 1424093 | 1293608 | 110.09% |
| .flow.mgr.flows_evicted | 1424093 | 1760730 | 80.88% |
| .flow.mgr.flows_evicted_needs_work | 1651 | 1309518 | 0.13% |
| .flow.memuse | 748009728 | 907273728 | 82.45% |
| .tcp.sessions | 582097 | 2839834 | 20.5% |
| .tcp.syn | 627839 | 4710349 | 13.33% |
| .tcp.synack | 376403 | 2839807 | 13.25% |
| .tcp.rst | 259494 | 1939251 | 13.38% |
| .tcp.reassembly_gap | 591993 | 81184 | 729.2% |
| .tcp.memuse | 88800000 | 1776000000 | 5.0% |
| .tcp.reassembly_memuse | 98304 | 1966080 | 5.0% |
| .detect.alert | 395 | 109440 | 0.36% |
| .app_layer.flow.http | 668 | 546279 | 0.12% |
| .app_layer.flow.ftp | 24 | 18535 | 0.13% |
| .app_layer.flow.smtp | 23 | 18540 | 0.12% |
| .app_layer.flow.tls | 3773 | 1870416 | 0.2% |
| .app_layer.flow.smb | 181 | 177170 | 0.1% |
| .app_layer.flow.dcerpc_tcp | 18 | 16310 | 0.11% |
| .app_layer.flow.failed_tcp | 10377 | 138168 | 7.51% |
| .app_layer.flow.dns_udp | 42987 | 324973 | 13.23% |
| .app_layer.tx.http | 5354 | 546325 | 0.98% |
| .app_layer.tx.ftp | 80 | 74136 | 0.11% |
| .app_layer.tx.smtp | 31 | 37040 | 0.08% |
| .app_layer.tx.smb | 1633 | 1455501 | 0.11% |
| .app_layer.tx.dcerpc_tcp | 57 | 277179 | 0.02% |
| .app_layer.tx.dns_udp | 50887 | 649940 | 7.83% | 

Pipeline 4752

**Comment by catenacyber** [comment]
cc @ct0br0 what happened with QA ?

**Comment by victorjulien** [comment]
merged in #6810, thanks!

**Pull request closed without merging**
