### PR TITLE
detect: absent keyword to test absence of sticky buffer 2224 v23

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2224

Describe changes:
- detect: adds `absent` keyword to match on absent buffer

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1957

https://github.com/OISF/suricata/pull/11509 with code review taken into account

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23045

**Comment by catenacyber** [comment]
Force-pushed with just the commit reworded.

Still the question of transforms : do you see a use case of buffer + transform + absent keyword ?
Or should we explicitly forbid it ?

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23073

**Comment by catenacyber** [comment]
Clean in https://github.com/OISF/suricata/pull/11964

**Pull request closed without merging**
