### PR TITLE
New option for logging hash of truncated files

### PR DESCRIPTION
**Pull request by aoshiken**
The prior iteration of this PR was #2824

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

[Redmine ticket](https://redmine.openinfosecfoundation.org/issues/2147)

Changes since PR #2824 :
- Removed code from output-json
- Refactored some minimal code shared between CLOSED and TRUNCATED file states
 
 
 
Changes since PR #2823 :
- Fixed coding style according to documentation
- Squashed some commits for comments
- Reverting part of commit that moved code

_EDIT: Fix Redmine ticket URL_

### CODE REVIEW

**Comment by victorjulien** [comment]
I'm trying to see if the legal side is ok, but I can't seem to figure out if the contrib agreement has been signed. Could you email me on victor@inliniac.net? Thanks!

**Comment by victorjulien** [comment]
In filestore2 this is already addressed, right @jasonish ?

**Comment by jasonish** [comment]
No, not for all hash type. SHA256 is done for truncated files as the filename depends on it. But MD5 and SHA1 have been left alone, as they won't be finalized if the files has gaps or is truncated.

**Comment by victorjulien** [comment]
I don't recall why this was closed (by me). Could you rebase and resubmit?

**Comment by aoshiken** [comment]
I assume you want a new PR as a next iteration of this one, am I right?

**Comment by victorjulien** [comment]
Yes, please! Thanks!

**Pull request closed without merging**
