### PR TITLE
App layer error close txs 4318 v5

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4318

Describe changes:
- app-layer: clean and "close" all txs if protocol reaches error state

I am more and more convinced that there is no good way to test this as app-layer parsers should not return error...

Modifies #7076 by using a flag on the directional stream instead of the bidirectional session, so as to still have detection run for both directions

### CODE REVIEW

**Comment by catenacyber** [comment]
Converting to draft as I am not sure this is right... (because we are missing the good test I guess)

Maybe `AppLayerParserTransactionsCleanup` should take into account the direction, so that if the tcp session is disrupted, `xx_disrupt_flags = FlowGetDisruptionFlags(f, xx);` gets the disrupted flags in the current direction, but not in the opposite direction, so that we run detection for both directions, but only once...

**Comment by victorjulien** [comment]
For testing, using this (draft) work will be useful I think https://github.com/OISF/suricata/pull/7234/commits/ff3219240a0d0eb6ddcd53b0c147836516834158

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 6928

**Comment by suricata-qa** [comment]
Warning: no commits in this PR have specified the following ticket(s):
- 4318 - https://redmine.openinfosecfoundation.org/issues/4318

Please update the commit(s) and submit a new PR.

**Pull request closed without merging**
