### PR TITLE
Backports port grouping/v5

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- https://redmine.openinfosecfoundation.org/issues/6830
- https://redmine.openinfosecfoundation.org/issues/6520
- https://redmine.openinfosecfoundation.org/issues/6829
- https://redmine.openinfosecfoundation.org/issues/6844
- https://redmine.openinfosecfoundation.org/issues/6845
- https://redmine.openinfosecfoundation.org/issues/6895
- https://redmine.openinfosecfoundation.org/issues/6897

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1733

Previous PR: https://github.com/OISF/suricata/pull/10730

Changes since v3:
- Cherry picked d02429e46818917462195c8184e733bdf2a2fe0c

### CODE REVIEW

**Comment by inashivb** [comment]
ok I had to do [67872ed](https://github.com/OISF/suricata/pull/10737/commits/67872ed68162a646099266f853512799d1caaf78) separately. No matter the configs, and now using the same clang-fmt versions, it is for some reason accepted in master but not here.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19881

**Comment by catenacyber** [comment]
CI clang format is green 🎊 

Besides the clang format commits, were all the other ones merged in a single PR on master ? Which one ?

**Comment by inashivb** [comment]
> CI clang format is green 🎊
> 
> Besides the clang format commits, were all the other ones merged in a single PR on master ? Which one ?

No, there were multiple, actually. I have tried to list them all below.
- https://github.com/OISF/suricata/pull/10569
- https://github.com/OISF/suricata/pull/10600
- https://github.com/OISF/suricata/pull/10608
- https://github.com/OISF/suricata/pull/10697
- https://github.com/OISF/suricata/pull/10720
- https://github.com/OISF/suricata/pull/10569

**Comment by catenacyber** [comment]
#10569 is a staging PR including DPDK changes. What is the list of base (non-staging) PRs like https://github.com/OISF/suricata/pull/10567 ?

**Comment by catenacyber** [comment]
Are these 2 commits missing from #10567 ?

https://github.com/OISF/suricata/pull/10567/commits/6b97fc1a5739be9480339a6008943851cb11b418
https://github.com/OISF/suricata/pull/10567/commits/b3f12cc65e33c63e9c2eab24a27219480029014e

**Comment by inashivb** [comment]
> Are these 2 commits missing from #10567 ?
> 
> [6b97fc1](https://github.com/OISF/suricata/commit/6b97fc1a5739be9480339a6008943851cb11b418) [b3f12cc](https://github.com/OISF/suricata/commit/b3f12cc65e33c63e9c2eab24a27219480029014e)

Yes because we don't want to backport clean ups and any unimportant commits.

**Comment by catenacyber** [comment]
Why is https://github.com/OISF/suricata/commit/6b97fc1a5739be9480339a6008943851cb11b418 unimportant ?

It looks good for perf to remove code "only being used at the time of parsing the ports from rules initially"

**Comment by inashivb** [comment]
> Why is [6b97fc1](https://github.com/OISF/suricata/commit/6b97fc1a5739be9480339a6008943851cb11b418) unimportant ?
> 
> It looks good for perf to remove code "only being used at the time of parsing the ports from rules initially"

ok. I disregarded it as a cleanup commit. Will add it. Thank you!

**Pull request closed without merging**
