### PR TITLE
af-packet: speed up thread sync during startup

### PR DESCRIPTION
**Pull request by victorjulien**
Threads are initialized sequentially to allow for a predictable mapping of threads and queues. Not all parts of the start up need to be done sequentially. The setting up of the rings can be very expensive, taking of a couple of hundred milliseconds. The ring setup doesn't need to be done sequentially though.

This patch releases the thread early, after bind but before the ring setups.

Ticket: #7272.

Replace #11806

https://redmine.openinfosecfoundation.org/issues/7272

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22793

**Review by catenacyber — APPROVED** [review]
Thanks for the work.

CI : ok
Commits segmentation : ok
Commit messages : ok
Git ID set : ok
CLA : you already contributed
Doc update : not needed
Redmine ticket :  thanks for the ticket
Rustfmt : no rust
Tests : I do not think we have a good way to test such optimizations, do we ?
Dependencies added: none
Code : good

**Comment by catenacyber** [comment]
@victorjulien are you not merging this ?

**Comment by victorjulien** [comment]
I think I saw one case where this didn't start up, but I did not record it. So want to do some more testing.

**Comment by victorjulien** [comment]
I've been running this in a loop for a long time, and under load. Haven't seen issues.

**Comment by victorjulien** [comment]
Merged in #12222, thanks!

**Pull request closed without merging**
