### PR TITLE
Napatech bypass v1.09

### PR DESCRIPTION
**Pull request by pjyoung1**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket:
[https://redmine.openinfosecfoundation.org/issues/2818](https://redmine.openinfosecfoundation.org/issues/2818)

Describe changes:
```
Added hardware based bypass support on Napatech SmartNICs
Added support for inline processing using Napatech SmartNICs
```
This PR Addresses issues identified in the review of [PR 4472 ](https://github.com/OISF/suricata/pull/4472)
This reflects changes since PR  [Napatech bypass v1.07]https://github.com/OISF/suricata/pull/4472)

### CODE REVIEW

**Comment by pjyoung1** [comment]
This PR failed the Debian 9 test build with the error:  "sip-response-line: Sub test #1: FAIL : expected 3 matches; got 1 for filter {'count': 3, 'match': {'event_type': 'alert'}}"  This appears to be unrelated to any of the changes that I made.  Can you explain what is causing this?  Is this something that I did?  If not, will I have to submit another PR for this?

**Comment by jlucovsky** [comment]
> This PR failed the Debian 9 test build with the error: "sip-response-line: Sub test #1: FAIL : expected 3 matches; got 1 for filter {'count': 3, 'match': {'event_type': 'alert'}}" This appears to be unrelated to any of the changes that I made. Can you explain what is causing this? Is this something that I did? If not, will I have to submit another PR for this?

We've seen this in the past and it's unlikely your change is causing it. I've restarted the PR checks.

**Comment by pjyoung1** [comment]
I see it passed the second time through.  Thanks.

**Comment by jlucovsky** [comment]
> I see it passed the second time through. Thanks.

You're welcome

**Pull request closed without merging**
