### PR TITLE
build: cbindgen (v10)

### PR DESCRIPTION
**Pull request by dbcfd**
Version 10 (from https://github.com/OISF/suricata/pull/4279)

Rust headers are now generated using cbindgen. If cbindgen is present, they can
be generated during dist, otherwise they will be available for builds.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Rust headers are now created by cbindgen
- Cbindgen is run as a step under dist when cbindgen is available and a high enough version

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
https://redmine.openinfosecfoundation.org/issues/3308

**Comment by jasonish** [comment]
We can get rid of a few warnings w.r.t. lua with:
```
+[defines]
+"feature = lua" = "HAVE_LUA"
```
in cbindgen.toml.

**Comment by jasonish** [comment]
I see 2 possible issues here, that we can live with:
- All that annoying WARN output.  I think cbindgen should be smarter there. If we explicitly exclude something, don't warn us about it. One idea here is to grep this output for actual errors, or just leave it as is (as I see other projects doing that have a lot of warn output as well).
- Doing anything in Rust, which will trigger a rebuild of the header file causes all C files to be rebuilt, and ccache doesn't provide much help here.

**Comment by victorjulien** [comment]
> * Doing anything in Rust, which will trigger a rebuild of the header file causes all C files to be rebuilt, and ccache doesn't provide much help here.

This may be a side effect of my suggestion to include the bindings in ``suricata-common.h``. Maybe that wasn't such a good idea after all. OTOH, the more rust we'll write, the more we'll include it.

**Comment by jasonish** [comment]
> > * Doing anything in Rust, which will trigger a rebuild of the header file causes all C files to be rebuilt, and ccache doesn't provide much help here.
> 
> This may be a side effect of my suggestion to include the bindings in `suricata-common.h`. Maybe that wasn't such a good idea after all. OTOH, the more rust we'll write, the more we'll include it.

I'm pretty sure thats it. I'm not opposed to having to include the rust binding in each file that needs. Sure, eventually that might be about every file, but currently its not.

**Comment by dbcfd** [comment]
Closing for https://github.com/OISF/suricata/pull/4367

**Pull request closed without merging**
