### PR TITLE
Pcap conditional v2.2.11

### PR DESCRIPTION
**Pull request by scottfgjordan**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/120

Describe changes:
- Rebase
- Addressed documentation nitpicks in [previous PR](https://github.com/OISF/suricata/pull/6571)
- Rebased suricata-verify pr, comparison for log.pcap may need reworking.

suricata-verify-pr: 542

### CODE REVIEW

**Comment by scottfgjordan** [comment]
I will take a look at what's going in the MacOS Suricata-Verify test as well as the cocci failure.

**Comment by victorjulien** [comment]
> I will take a look at what's going on in the MacOS Suricata-Verify test as well as the cocci failure.

The cocci crash is a known issue, so you can ignore it.

Not sure what the Mac issue is. @jasonish @inashivb have you seen this before?

**Comment by inashivb** [comment]
> > I will take a look at what's going on in the MacOS Suricata-Verify test as well as the cocci failure.
> 
> The cocci crash is a known issue, so you can ignore it.
> 
> Not sure what the Mac issue is. @jasonish @inashivb have you seen this before?

No. But, it's coming from https://github.com/OISF/suricata-verify/tree/master/tests/output-pcap-log, for some reason pcap-log file is not getting generated.

**Comment by jasonish** [comment]
> > > I will take a look at what's going on in the MacOS Suricata-Verify test as well as the cocci failure.
> > 
> > 
> > The cocci crash is a known issue, so you can ignore it.
> > Not sure what the Mac issue is. @jasonish @inashivb have you seen this before?
> 
> No. But, it's coming from https://github.com/OISF/suricata-verify/tree/master/tests/output-pcap-log, for some reason pcap-log file is not getting generated. Edit: I'm just seeing the last point of Describe changes", maybe it is something they still have to fix.

Whats more curious I think is why its only failing on MacOS.  The failing test had been moved from a `check.sh` style to `test.yaml`, the S-V PR re-adds a `check.sh` without updating the `test.yaml` where it should have just been an update to the `test.yaml`.  But the SV PR mentioned in the PR message is not being used.  So 2 things, this is not being tested against the SV PR that it should be (instead master), and the tests in that PR need some cleanup as well.

**Comment by jasonish** [comment]
> Whats more curious I think is why its only failing on MacOS.

Ah, this is why: https://redmine.openinfosecfoundation.org/issues/4899

**Comment by jasonish** [comment]
I'm running into an issue where my config adapted from master doesn't result in a pcap log anymore. I'm simply settings `enabled: yes` for `pcap-log`. On master this results in a pcap being logged. With this PR, not pcap files are created. This appears to be the issue behind some S-V issues as well here.

**Comment by inashivb** [comment]
> > Whats more curious I think is why its only failing on MacOS.
> 
> Ah, this is why: https://redmine.openinfosecfoundation.org/issues/4899

Update: This issue has been fixed in https://github.com/OISF/suricata-verify/pull/622

**Comment by scottfgjordan** [comment]
@jasonish 
> I'm running into an issue where my config adapted from master doesn't result in a pcap log anymore. I'm simply settings `enabled: yes` for `pcap-log`. On master this results in a pcap being logged. With this PR, not pcap files are created. This appears to be the issue behind some S-V issues as well here.

Looks like I introduced a bug in the last PR in the PcapLogCondition function and didn't realize since the suricata-verify cases came up clean except for MacOS. Got that fixed. Will be cleaning up some of the other issues you mentioned about the Suricata-Verify cases and will get a new PR out.

**Comment by scottfgjordan** [comment]
Replaced by: https://github.com/OISF/suricata/pull/6766

**Pull request closed without merging**
