### PR TITLE
rfb: add RFB parser - v8

### PR DESCRIPTION
**Pull request by satta**
Previous PR: #4633 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#3501](https://redmine.openinfosecfoundation.org/issues/3501)

Describe changes (from previous PR):
- Add keyword `rfb.secresult`, allowing one to alert on failed connection attempts.
- Use flow direction for logging (mostly for consistency)
- Include unknown security result number in JSON output.

Updated suricata-verify tests as well.

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you rebase this? I've updated the app layer API to return a different type, so this will require some work. The good part is that you can remove the TCP buffering code and support the new incomplete logic introduced in #4691

**Comment by satta** [comment]
Sure, I'll look into it ASAP.

**Comment by victorjulien** [comment]
> Sure, I'll look into it ASAP.

See the in progress documentation work for more explanation: #4692

**Comment by victorjulien** [comment]
Btw, could you expand the commit message too?

**Comment by satta** [comment]
> Btw, could you expand the commit message too?

What do you mean by "expand"?  Add some background besides the summary line?

**Comment by victorjulien** [comment]
> > Btw, could you expand the commit message too?
> 
> What do you mean by "expand"? Add some background besides the summary line?

Yeah exactly.

**Comment by satta** [comment]
Okay, will do!

**Pull request closed without merging**
