### PR TITLE
detect/transform: add domain transform

### PR DESCRIPTION
**Pull request by jlucovsky**
This PR adds a transform for:
1. domain - Returns the domain and passes it on.

Continuation of #4104 

This update:
1. Addresses review feedback

Companion PR to suricata-verify` repo; https://github.com/OISF/suricata-verify/pull/111

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:  [3074](https://redmine.openinfosecfoundation.org/issues/3074)

### CODE REVIEW

**Comment by victorjulien** [comment]
Any thoughts on the name of this transform? Its not 'domain' specific at all I think, it just puts a dot in front of whatever data it is used with. cc @jasonish

**Comment by jlucovsky** [comment]
> Any thoughts on the name of this transform? Its not 'domain' specific at all I think, it just puts a dot in front of whatever data it is used with. cc @jasonish

True but it facilitates domain and tld identification.

**Comment by jasonish** [comment]
> > Any thoughts on the name of this transform? Its not 'domain' specific at all I think, it just puts a dot in front of whatever data it is used with. cc @jasonish
> 
> True but it facilitates domain and tld identification.

As its not a domain I'm not sure if domain is the best name.  But it is treating it like a domain, so I don't really have a better name except for:

- `as_domain`. So in an OO language as hostname object might have some methods.  You'd expect `domain()` to return the actual domain, but maybe `.as_domain()` would return the hostname as a domain name.  With the caveat that both return a dot prefixed name.

- `dotprefix`: to be quote literal, give me the buffer with a . in front.

**Comment by jlucovsky** [comment]
> > > Any thoughts on the name of this transform? Its not 'domain' specific at all I think, it just puts a dot in front of whatever data it is used with. cc @jasonish
> > 
> > 
> > True but it facilitates domain and tld identification.
> 
> As its not a domain I'm not sure if domain is the best name. But it is treating it like a domain, so I don't really have a better name except for:
> 
> * `as_domain`. So in an OO language as hostname object might have some methods.  You'd expect `domain()` to return the actual domain, but maybe `.as_domain()` would return the hostname as a domain name.  With the caveat that both return a dot prefixed name.
> * `dotprefix`: to be quote literal, give me the buffer with a . in front.

The most indicative is `dotprefix` but I like `as_domain` since that provides the purpose.

@victorjulien ?

**Comment by victorjulien** [comment]
``dotprefix`` works the best for me as nothing in the code is actually specific to a domain. Only its intended use is around domains.

**Comment by jlucovsky** [comment]
Closed in #4190

**Pull request closed without merging**
