### PR TITLE
template: remove C app-layer template

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5636

Describe changes:
- remove C app-layer template

Only keep rust one

@jufajardini what do you think about setup-app-layer.py ? 'as your Suricon talk used it)

suricata-verify-pr: 1031

### CODE REVIEW

**Comment by catenacyber** [comment]
CI red because I did not use https://github.com/OISF/suricata-verify/pull/1031

**Comment by jasonish** [comment]
See https://github.com/OISF/suricata/pull/8182. Does this take a different approach?

**Comment by jasonish** [comment]
Ah! I never claimed it in Redmine!

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104019 | 81.11% | 

Pipeline 11063

**Comment by catenacyber** [comment]
Closed in favor of #8182 which seems more complete

@jasonish I had not seen the PR, and there are duplicate redmine tickets...

From a S-V discussion, I remembered this was not yet merged...

**Pull request closed without merging**
