### PR TITLE
Multipart mime 3487 v39

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser
- json schema : add email.received array

Follows #11130 with rebase

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1851

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20820

**Comment by victorjulien** [comment]
Email input:
```
To: "XXXXX-YYYY, ZZZZZ" <xyz@mydomain.zzz>
```
Is logged as:
```json
    "to": [
      "\"XXXXX-YYYY",
      " ZZZZZ\" <xyz@mydomain.zzz>"
    ],
```
We match on it in SV
```yaml
    email.to[0]: '"XXXXX-YYYY'
    email.to[1]: ZZZZZ" <xyz@mydomain.zzz>
```
Note the leading space in the ZZZZZ part of the "to" field.

So couple of things:
1. this is different from our master, which strips the leading space from `to[1]`
2. both master and this branch seem wrong to split the name

Can't provide a pcap sadly, as it's TLP dark red, but I can test fixes.

We can fix this up post merge too.

**Comment by victorjulien** [comment]
Also seeing a pcap where this branch no longer tracks an attachment, where master does. Trying to see how to share or analyze.

**Comment by victorjulien** [comment]
> Also seeing a pcap where this branch no longer tracks an attachment, where master does. Trying to see how to share or analyze.

It appears to be a MIME email embedded in another. Sharing something offline.

**Comment by catenacyber** [comment]
> So couple of things:
> 
> 1. this is different from our master, which strips the leading space from `to[1]`
> 2. both master and this branch seem wrong to split the name

Fixing both the leading space, and also improving on the quotes
 
> Can't provide a pcap sadly, as it's TLP dark red, but I can test fixes.

Crafted a test in https://github.com/OISF/suricata-verify/pull/1869

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata/pull/11188

**Pull request closed without merging**
