### PR TITLE
Unify reg smb/v3

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3315

### CODE REVIEW

**Comment by victorjulien** [comment]
I would like to see the same `setfileflags` direction change here.

Also can you combine this PR with the nfs one to create a single PR?

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 0 | 255 | 0.0% |

**Comment by inashivb** [comment]
Replaced w #6263

**Pull request closed without merging**
