### PR TITLE
App layer error close txs 4318 v3

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4318

Describe changes:
- app-layer: clean and "close" all txs if protocol reaches error state

The best way I see to test this is SMB
But I am not sure how to get multiple live transactions over SMB

Then to get an error, simply have a NBSS message with length 4, and just `\xFFSMB` so the SMB parser will fail decode the SMB1 header (not sure it should put the whole parser in an error state by the way, as we could go on with the next NBSS message)

Modifies #6800 by adding a commit to rename STREAM_DEPTH to STREAM_DISRUPTED

### CODE REVIEW

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6887

**Comment by pevma** [comment]
ERROR: QA failed on tlpw1_files_sha256.

Pipeline 5986

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw1_files_sha256.
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.memuse | 531796608 | 505591168 | 105.18% | 

Pipeline 6083

**Comment by catenacyber** [comment]
@pevma how should I debug this interesting QA ?

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7076

**Pull request closed without merging**
