### PR TITLE
eve/log: FTP logging

### PR DESCRIPTION
**Pull request by jlucovsky**
This changeset is for issue [2315](https://redmine.openinfosecfoundation.org/issues/2315)  and implements eve logging for FTP, including documentation updates.

Updated to correct memory buffer overrun from #3841.

FTP logging adds 2 event types:
- ftp
- ftp_data

Each ftp event can contain:
- command
- command_data
- reply (in array format to handle multi-line replies)
- completion_code
- dynamic_port
- mode
- reply_received

ftp_data events contain:

- filename
- command associated with the data transfer.

Continuation of #3841 

## Sample `event_type ftp` output
```
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 2229468357925974,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 16,
  "ftp": {
    "command": "EPRT",
    "command_data": "|2|2a01:e34:ee97:b130:8c3e:45ea:5ac6:e301|41813|",
    "reply": [
      "EPRT command successful. Consider using EPSV"
    ],
    "completion_code": "200",
    "dynamic_port": 41813,
    "mode": "active",
    "reply_received": "yes"
  }
}
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 2229468357925974,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 17,
  "ftp": {
    "command": "RETR",
    "command_data": "index.html",
    "reply": [
      "Opening BINARY mode data connection for index.html (6712 bytes)",
      "Transfer complete"
    ],
    "completion_code": "150",
    "reply_received": "yes"
  }
}
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 2229468357925974,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 18,
  "ftp": {
    "command": "QUIT",
    "reply": [
      "Goodbye"
    ],
    "completion_code": "221",
    "reply_received": "yes"
  }
}
```

## Sample `event_type ftp_data` output
```
{
  "timestamp": "2019-03-10T15:20:01.500157-0700",
  "flow_id": 1615446949360413,
  "parent_id": 274790086810710,
  "pcap_cnt": 68,
  "event_type": "ftp_data",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 53697,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 51093,
  "proto": "TCP",
  "tx_id": 0,
  "ftp_data": {
    "filename": "uio-app.js",
    "command": "RETR"
  }
}
{
  "timestamp": "2019-03-10T15:20:18.000469-0700",
  "flow_id": 1343493916181127,
  "parent_id": 274790086810710,
  "pcap_cnt": 116,
  "event_type": "ftp_data",
  "src_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "src_port": 20,
  "dest_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "dest_port": 41813,
  "proto": "TCP",
  "tx_id": 0,
  "ftp_data": {
    "filename": "index.html",
    "command": "RETR"
  }
}
```

### CODE REVIEW

**Comment by victorjulien** [comment]
This fails to build the userguide w/o warnings. I'm fixing travis to catch this. See https://travis-ci.org/victorjulien/suricata/jobs/535665553 (at the end).

Could you reword the commits to all have a proper prefix in the subject?

**Comment by lmzke** [comment]
I am looking forward to having this addition in the application.  FYI, I will be contacting @jlucovsky about a bug in the reply parsing in `jlucovsky:2315.6`.

**Comment by lmzke** [comment]
For consideration: https://github.com/jlucovsky/suricata/pull/1

**Comment by jlucovsky** [comment]
> I am looking forward to having this addition in the application. FYI, I will be contacting @jlucovsky about a bug in the reply parsing in `jlucovsky:2315.6`.

Thanks! Included in #3887

**Comment by jlucovsky** [comment]
Continued in #3887

**Pull request closed without merging**
