### PR TITLE
Ebpf 4.0 v23

### PR DESCRIPTION
**Pull request by regit**
Update of #3177 

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Fix documentation following @norg review
- Rename `cpu-set` option to `xdp-cpu-redirect`

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/371
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/154

### CODE REVIEW

**Comment by netoptimizer** [comment]
Subscribing to github thread...
Thanks for renaming the option name.

I've tested Ebpf 4.0 v22 #3177 ... I guess I should test this branch too ;-)

I have some improvement to xdp_filter.c and the selection of the cpu_dest. Basically do proper hashing before the modulo, as modulo with an even number (of CPUs) over the IP src+dst gives very uneven distribution across the CPU array. But I can integrate that later...

**Comment by regit** [comment]
@netoptimizer there is just the renaming of the option and some doc fix. But tests are always welcome.

**Comment by netoptimizer** [comment]
@regit testing ... found a bug ;-)
Already have a fix/patch for it... I don't know howto attach patches to github.

**Comment by regit** [comment]
@netoptimizer you can fork push and do a merge request on top of this branch ?

**Pull request closed without merging**
