### PR TITLE
detect: bump detect engine version for tenant reload

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5866

Describe changes:
- detect: bump detect engine version for tenant reload

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .flow.end.tcp_state.last_ack | 1004 | 257 | 25.6% |
| | SURI_TLPR1_stats_chk | | |
| .flow.end.tcp_state.fin_wait2 | 156072 | 127814 | 81.89% | 

Pipeline 12791

**Comment by catenacyber** [comment]
Fix was approved in redmine ticket : so ready for review

**Comment by victorjulien** [comment]
Merged in #8635, thanks!

**Comment by hongliangl** [comment]
Thanks for merging this!

**Pull request closed without merging**
