### PR TITLE
detect/alert: ensure reject action is applied to packet/flow (6.0.x backports) - v1

### PR DESCRIPTION
**Pull request by jufajardini**
Backports of reject action regression fixes to six.
- https://redmine.openinfosecfoundation.org/issues/5471

Describe changes:
- remove unused macros for packet->action handling
- Make `PacketDrop` update `packet->action`, instead of setting it, to prevent overwriting when that's not desirable, also include which action generated the Drop

The Cocci checks were failing in my repo, but not locally, so decided to give it a try to see how will the PR perform...

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8922
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. BE MINDFUL OF ANY RESULTS.

**Comment by victorjulien** [comment]
```
Failed with input length 26 versus 229, found enip instead of smb
Assertion failure: enip-smb
```
@catenacyber missing backport or new issue?

**Comment by catenacyber** [comment]
>  missing backport or new issue?

I guess we can backport d1ebf320f713af6ca102d71d9201a629334d162b ;-)

**Comment by jufajardini** [comment]
> > missing backport or new issue?
> 
> I guess we can backport [d1ebf32](https://github.com/OISF/suricata/commit/d1ebf320f713af6ca102d71d9201a629334d162b) ;-)

Should I do this or will it be done with the other fuzz backports?

**Comment by victorjulien** [comment]
> > > missing backport or new issue?
> > 
> > 
> > I guess we can backport [d1ebf32](https://github.com/OISF/suricata/commit/d1ebf320f713af6ca102d71d9201a629334d162b) ;-)
> 
> Should I do this or will it be done with the other fuzz backports?

Can be done separately.

**Comment by victorjulien** [comment]
Merged instead of #7814 in #7806, thanks!

**Pull request closed without merging**
