### PR TITLE
Update and restructure rules documentation

### PR DESCRIPTION
**Pull request by ralphje**
The documentation on Suricata Rules could use some improvement, mainly because the ToC levels varied across sections. I tried to improve the documentation as follows:

* Removed screenshots of rules in first few sections (ongoing effort)
* Rewritten the introduction and parts of meta keywords
* Lowercased all section titles that are keywords
* Moved explanation of modifiers and normalization to the introduction page
* Moved fast_pattern and prefilter to their own page as they do similar things
* Moved pcre from its dedicated page to the payload keywords page, and removed the reference to it from the HTTP keywords page
* Moved flowint from its dedicated page to the flow keywords page.
* Moved IP reputation keywords to the rules section.
* Restructured documentation to have more consistent ToC levels

This is a resubmission of PR #2936, which in turn was a resubmission of PR #2927. This version of the PR should build properly under Sphinx v1.3.6. I also fixed the comments of @norg in this PR.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

### CODE REVIEW

**Comment by victorjulien** [comment]
A commit like "doc: Resolve review points from @norg" shouldn't exist. The fixes should be put into the other commits. See https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria#Commits

**Comment by victorjulien** [comment]
make pdf is now fixed

**Comment by victorjulien** [comment]
I don't understand the part about 'inlining'. @norg @jasonish can you see if that makes sense to you?

**Comment by victorjulien** [comment]
Please make sure the next iteration of this PR is rebased to the current master, thanks.

**Comment by jasonish** [comment]
> I don't understand the part about 'inlining'. @norg @jasonish can you see if that makes sense to you?

Looks like this is a fixup commit. Perhaps they should have been inlined earlier on in this PR instead of included, then this commit could be avoided?

**Comment by victorjulien** [comment]
@jasonish my question was mostly about this commit https://github.com/OISF/suricata/pull/3041/commits/95773ff7541f09592aef9e2aee4b4f6c82c07f6e

**Comment by jasonish** [comment]
> On Dec 4, 2017, at 08:44, Victor Julien <notifications@github.com> wrote:
> 
> @jasonish my question was mostly about this commit 95773ff
> 

Yup. A previous commit included these files, then this one inlines the includes. They are not included in git master so this is a bit of a fix up commit. 

I’m fine with the inlining though as they were only included once anways. Includes are best used in Sphinx when you want to include it multiple times. IMO this should probably be squashed into the commit that added them as includes in the first place.

**Comment by ralphje** [comment]
I have done as you asked. I have kept the fix for the list of accepted protocols as a separate commit, as that seemed more appropriate.

**Comment by victorjulien** [comment]
Can you change "As mentioned by @norg in PR #2936, based on the list in suricata.yaml" into something like "Base list on settings in suricata.yaml". The github handle and PR have no meaning in just the git history, which is meant to stay useful w/o github.

**Comment by victorjulien** [comment]
Please also see https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Github_work_flow#Create-a-new-branch-for-incorporating-feedback : create a new branch and PR for incorporating feedback. Thanks!

**Comment by ralphje** [comment]
Let met just say that I am volunteering here to get some fixes in the documentation. It is not like I rewrote the entirety of Suricata and I feel that complaining about a specific commit message that is in fact contextually relevant is simply demotivating for contributors.

I know you have your guidelines and respect that you attempt to keep stuff straight, and I'm not here to discuss that, but I feel it is better to stop laying salt on all the snails (I'm not sure that is a valid English proverb, but you get the gist of it). Due to your strict regulations, I'm very demotivated to help fix other things for Suricata.

I have created a new PR as you asked, but in the future, please be more respectful and open to contributions from the community. That saves everyone a lot of time, that is better invested in bug fixes and other relevant commits.

**Comment by victorjulien** [comment]
All of our feedback is based on docs we've already written before and that are clearly listed in the repo, in our dev docs, etc. So asking contributors (politely!) to stick by our guidelines is not disrespectful.

Lets turn things around. Do you think it's reasonable that we lower our standards for a contributor?

**Comment by ralphje** [comment]
I feel that your standards on Git commits are too high, higher than can be expected from the occasional contributor, and I'm now very reluctant to help you improve Suricata further. It is not fun to go back to the same PR multiple times for something like changing commit messages. That is disrespectful to the contribution itself and the time I spent to write it.

Reading through documentation on how to write commit messages for this project is not something an occasional contributor should be needing to do. I applaud your efforts in writing those guidelines and respect your efforts to abide by them, but you may be turning down very good improvements and may be scaring away potential contributors.

This is my personal opinion and it's not my intention to start a discussion, I'm just saying that I feel that you could be more open to people spending their free time to improve Suricata, and lower your standards a little bit. Please take this as constructive criticism, I'm simply sharing my own experience in an effort to help your project.

**Pull request closed without merging**
