### PR TITLE
Http2 noalloc header compare 5454 backport6

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
Backport of https://redmine.openinfosecfoundation.org/issues/5454

Describe changes:
- http2: remove `to_vec` in comparisons (no need to alloc)

### CODE REVIEW

**Comment by catenacyber** [comment]
CIFuzz failure is another missing backport about HTTP2...

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .tcp.rst | 89922 | 81679 | 110.09% | 

Pipeline 8713
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

**Comment by victorjulien** [comment]
Can you do a PR with that backport included?

**Comment by catenacyber** [comment]
Done in https://github.com/OISF/suricata/pull/7805

**Pull request closed without merging**
