### PR TITLE
Backports/20220630/v3

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- https://redmine.openinfosecfoundation.org/issues/5420
- https://redmine.openinfosecfoundation.org/issues/5398
- 5314

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on report_failure.

ERROR: QA failed on build_asan.
  

Pipeline 8066

**Comment by ct0br0** [comment]
> 

Going to re-run this.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8085

**Comment by victorjulien** [comment]
Merged in #7605, thanks.

**Pull request closed without merging**
