### PR TITLE
jsonbuilder: methods for adding safe strings

### PR DESCRIPTION
**Pull request by jasonish**
Add methods set_string_safe and append_string_safe for adding
strings that are guaranteed to already be JSON safe, such as
base64 data. This leads to a much faster operationg as
encoding (escaping) the string is skipped.

This is the modification discussed in the comment re. benchmarking over here:
https://github.com/OISF/suricata/pull/6227#issuecomment-874999553

### CODE REVIEW

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

**Comment by suricata-qa** [comment]
Information:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |

**Comment by victorjulien** [comment]
todo: add at least a single consumer

**Comment by jasonish** [comment]
Closing until there is a use case.

**Comment by jasonish** [comment]
This should have been a draft.  Providers a rather large performance boost for the `JsonBuilder` JSON support when being called from C. 

https://github.com/OISF/suricata/pull/6227#issuecomment-874999553

**Pull request closed without merging**
