### PR TITLE
JA4 for TLS and QUIC -- v7

### PR DESCRIPTION
**Pull request by satta**
Previous PR: #9634

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6379

Changes to previous PR:
- Rebase against current `master`.
- Adjust function calls to match recent renames:
  - `DetectAppLayerInspectEngineRegister2` -> `DetectAppLayerInspectEngineRegister`
  - `DetectAppLayerMpmRegister2` -> `DetectAppLayerMpmRegister`

```
SV_BRANCH=pr/1564
```

### CODE REVIEW

**Comment by satta** [comment]
Can someone please restart the failed CI checks, I had to update the `SV_BRANCH` reference to make sure the tests match the updated other code from the master rebase. Thanks!

**Comment by satta** [comment]
I don't think the correct S-V branch was actually pulled in... 🤔

**Comment by jasonish** [comment]
> I don't think the correct S-V branch was actually pulled in... 🤔

Looks like it was...

https://github.com/OISF/suricata/actions/runs/7308018681/job/19975956736?pr=10095#step:9:39

**Comment by victorjulien** [comment]
> > I don't think the correct S-V branch was actually pulled in... 🤔
> 
> Looks like it was...
> 
> https://github.com/OISF/suricata/actions/runs/7308018681/job/19975956736?pr=10095#step:9:39

I did another restart, then it worked.

**Comment by satta** [comment]
Thanks!

**Comment by victorjulien** [comment]
I think this is where we're landing:
- we'd like to take this in
- we'll make it a compile and runtime optional thing per algo
- we will add each to the new "features" section of the "requires" keyword so that rules can be written for it w/o errors
- we'd like to make ja3/ja3s and friends compile time optional as well
- ja4 for tls we'd probably compile in by default
- ja4 for quic needs to be investigated if it falls under the same license logic as tls client
cc @jasonish 

We can take on this plumbing work, but happy to accept it if you're willing and able to do it @satta :)

Thanks a lot for your work _and_ patience!

**Comment by satta** [comment]
> I think this is where we're landing:

Thanks Victor for chiming in as well!

> * we'd like to take this in

🥳 

> * we'll make it a compile and runtime optional thing per algo
> * we'd like to make ja3/ja3s and friends compile time optional as well

OK. For runtime, this is already implemented via config option for both JA3 and JA4. For compile time, this will need additional work. What do you think about #10135 (raw fingerprint support) -- my feeling is that this should also be configurable at runtime, do you agree?

> * we will add each to the new "features" section of the "requires" keyword so that rules can be written for it w/o errors

Makes sense.

> * ja4 for tls we'd probably compile in by default
> * ja4 for quic needs to be investigated if it falls under the same license logic as tls client
>   cc @jasonish

AFAICS the license makes no difference between TLS and QUIC.

> We can take on this plumbing work, but happy to accept it if you're willing and able to do it @satta :)

I can do it, give me a bit of time to do it since it's not my focus atm but I will do it on the side. (Will let you know if there are questions about the finally arriving `requires` keyword but I guess there are already examples merged into master?)

One thing I would be asking for is to take a look at #10135 and provide some feedback whether we should include the raw fingerprints in the main JA4 feature. That would simplify going forward with future single PRs.

> Thanks a lot for your work _and_ patience!

Anytime -- this might make some other people I know happy as well :)

**Comment by john-althouse** [comment]
> - ja4 for quic needs to be investigated if it falls under the same license logic as tls client
cc @jasonish

> AFAICS the license makes no difference between TLS and QUIC.

That is correct. QUIC uses TLS, it's just encapsulated over UDP instead of TCP. 

image

**Review by catenacyber — CHANGES_REQUESTED** [review]
Setting GH status to changes requested cf https://github.com/OISF/suricata/pull/10095#issuecomment-1900271833

**Pull request closed without merging**
