### PR TITLE
templates: cleanups and C app-layer removals - v1

### PR DESCRIPTION
**Pull request by jasonish**
Ticket: https://redmine.openinfosecfoundation.org/issues/4939

Summary of changes:
- Test generated parser in CI.
- Remove C stub for Rust parsers.
- Remove C templates and support for generating C parsers
- Rename as needed the "rust-template" to simply "template".
- Minor Rust template cleanups.
- Set copyright year to current year on all newly created files.
- Rustfmt generated files
- Ensure new Rust files are clippy and rustfmt clean

suricata-verify-pr: 1008

### CODE REVIEW

**Comment by victorjulien** [comment]
Should we have a CI check that checks if the template files are a 100% rustfmt, clippy etc clean?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104008 | 81.11% | 

Pipeline 10700

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 10704

**Comment by jasonish** [comment]
> Should we have a CI check that checks if the template files are a 100% rustfmt, clippy etc clean?

We could, but they always will be.  We can't guarantee the output of the scripts is 100% clean, so this would be an added step to run those tools after creation.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103965 | 81.07% | 

Pipeline 10718

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103929 | 81.04% | 

Pipeline 10719

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 595854528 | 105.44% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 17167 | - |
| .flow.end.tcp_state.syn_sent | 0 | 22 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 8 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 3 | - |
| .flow.end.tcp_state.time_wait | 0 | 3 | - |
| .flow.end.tcp_state.last_ack | 0 | 2 | - |
| .flow.end.tcp_state.close_wait | 0 | 10 | - |
| .tcp.segment_from_pool | 15728353 | 16597549 | 105.53% |
| .app_layer.error.http.parser | 0 | 2 | - |
| .app_layer.error.smtp.gap | 0 | 7 | - | 

Pipeline 10720

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103932 | 81.05% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 594496448 | 105.2% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - | 

Pipeline 10731

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104040 | 81.13% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 645203968 | 114.17% | 

Pipeline 10733

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 10734

**Comment by catenacyber** [comment]
@jasonish latest oss-fuzz bug report is about C template as well :

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54056

My fix is 
```
diff --git a/src/app-layer-template.c b/src/app-layer-template.c
index 5803cacac..3407237a4 100644
--- a/src/app-layer-template.c
+++ b/src/app-layer-template.c
@@ -99,6 +99,10 @@ static void TemplateTxFree(void *txv)
         SCFree(tx->request_buffer);
     }
 
+    if (tx->tx_data.de_state != NULL) {
+        DetectEngineStateFree(tx->tx_data.de_state);
+    }
+
     if (tx->response_buffer != NULL) {
         SCFree(tx->response_buffer);
```

What do you think of it ?

**Comment by catenacyber** [comment]
Template seems the only C parser to be missing it 🤦 good to remove it

**Comment by jasonish** [comment]
> What do you think of it ?

Looks good.  So this has always been an issue in the C template? Tells you how little we use it.

I think there'll be another round of template cleanups after this is merged, at least I have some other changes I want to make soon.

**Comment by catenacyber** [comment]
> > What do you think of it ?
> 
> Looks good. So this has always been an issue in the C template? Tells you how little we use it.
> 

Always since `tx_data.de_state` so I would bet less than 3 years ;-)

**Pull request closed without merging**
