### PR TITLE
CEIL converts quantity value into count value

### PR DESCRIPTION
**Pull request by SaberGYL**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
Hi, can you explain the change in the commit message?

**Comment by catenacyber** [comment]
Could you also fix the formatting ? For instance by running `git rebase master -x "git clang-format HEAD^"`

**Comment by victorjulien** [comment]
A test case would be great too...

**Comment by victorjulien** [comment]
We have no test coverage for the line that is being changed.
Screenshot from 2021-01-23 10-16-17
So a test case would be most welcome, thanks!

**Comment by catenacyber** [comment]
Thoughts on this @cccs-sadugas ?

**Comment by cccs-sadugas** [comment]
> 
> 
> Thoughts on this @cccs-sadugas ?

It's true that there is a bug in both the C and rust version of the modbus parser.

Looking at the [Modbus specification, Section 6.11](https://modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf), it clearly states:
```rust
count = quantity / 8
```
 
Looking at our [rust parser](https://github.com/CybercentreCanada/sawp/blob/sawp-modbus-0.4.0/sawp-modbus/src/lib.rs#L674) it is the opposite of the spec:
```rust
quantity != u16::from(count / 8) + u16::from((count % 8) != 0)
```

Same with the expansion of the C parser:
```c
/* Macro to convert quantity value (in bit) into count value (in word): count = Ceil(quantity/8) */
#define CEIL(quantity) (((quantity) + 7)>>3)
quantity != CEIL(count)
```

Thanks for finding this. We will update the rust parser with a fix. It was probably caused by a lack of test cases for the Write Multiple Coils function which we can also add.

**Comment by catenacyber** [comment]
Closing this in favor of #6090, thanks @SaberGYL

**Pull request closed without merging**
