### PR TITLE
4.1.x - ftp - tx detect flags - v1

### PR DESCRIPTION
**Pull request by jasonish**
[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/776
- https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/420

### CODE REVIEW

**Comment by victorjulien** [comment]
Heh, the fatal check fails on smb (non-rust) I think.

**Comment by victorjulien** [comment]
> Heh, the fatal check fails on smb (non-rust) I think.

Have a fixed for this.

**Comment by victorjulien** [comment]
I'm doubting a bit about the fatal error on wrong registration patch. It might bite those who have out of tree parsers, but OTOH they should be aware of the issue and can always remove the error. Thoughts?

**Comment by jasonish** [comment]
In 4.1.x, I'd leave it out, I just added it for a sanity check.  Or change it to a warning/error.

**Comment by victorjulien** [comment]
Replaced by #4413

**Pull request closed without merging**
