### PR TITLE
Improving DPDK capture interface and docs v5

### PR DESCRIPTION
**Pull request by lukashino**
Follow up of https://github.com/OISF/suricata/pull/8738

Links to the Redmine tickets:

https://redmine.openinfosecfoundation.org/issues/5857
https://redmine.openinfosecfoundation.org/issues/5858
https://redmine.openinfosecfoundation.org/issues/5859
https://redmine.openinfosecfoundation.org/issues/5937
https://redmine.openinfosecfoundation.org/issues/5936
https://redmine.openinfosecfoundation.org/issues/5925
https://redmine.openinfosecfoundation.org/issues/5923
https://redmine.openinfosecfoundation.org/issues/6006
https://redmine.openinfosecfoundation.org/issues/5963

Changes:
- warn a user when segmented mbufs are detected

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 13300

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 112875 | 145159 | 128.6% | 

Pipeline 13303

**Review by jufajardini — CHANGES_REQUESTED** [review]
Are you still working on this? In case you are, could you split the doc changes commit into one that only applies formatting changes and another that has content changes? This would make it easier to review actual doc changes :)

**Comment by victorjulien** [comment]
replaced by #8811

**Pull request closed without merging**
