### PR TITLE
PostgreSQL: add initial support (WIP)

### PR DESCRIPTION
**Pull request by jufajardini**
Reboot PostgreSQL code; patch common existing files.
rust/src/applayerpgsql/parser.rs:
- add nom parsers for decoding SSL Requests and Responses;
- use data model that allows adding more message types.
- Add nom parser for normal startup messages.
- add more unittests
src/Makefile.am  fix formatting issue
rust/src/applayerpgsql/pgsql.rs:
- fix unused documentation comments warning
output-json-pgsql.c:
- update CreateEveHeader call.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4241

Previous PR: https://github.com/OISF/suricata/pull/6012

Describe changes:
- rust/src/applayerpgsql/parser.rs add more unit tests, data structures and nom parsers
- rust/src/applayerpgsql/pgsql.rs: fix unused documentation comments
- src/output-json-pgsql.c: update CreateEveHeader call

This version parses a few authentication requests but doesn't cover all types of authentication/encryption methods, as I fear it may be necessary to move some of the parsing logic/control to pgsql.rs. That's because some messages have the same initial identifier and in order to know how to interpret part of their contents we must know the context (previous messages exchanged).
About CreateEveHeader, I saw some possibilities of arguments and wasn't sure what should I use. Went with NULL, for now...
I think I'll add tests and nom parsers for Error Response messages now.

pcaps:
- SSL accepted, startup message, error message: https://drive.google.com/file/d/1Gqc73esu61qo_LbXDEXS33S_euO9eR8f/view?usp=sharing
- SSL rejected, MD5 authentication ok: https://drive.google.com/file/d/1yIivAakRth_suM8TmXI4sh7OJrtvxw_u/view?usp=sharing

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by jufajardini** [comment]
About the failed checks... the formatting one is due to trying to follow utils-profiling.c formatting pattern. Do I adapt it to what clang wants?

**Comment by victorjulien** [comment]
The formatting check should pass, ya. There is still lots of non-compliant code in the tree.

**Comment by victorjulien** [comment]
Can you turn the linked pcaps into SV tests and reference that in your next PR? That will likely also help with the codecov result.

**Comment by jufajardini** [comment]
Followed by: https://github.com/OISF/suricata/pull/6062

**Pull request closed without merging**
