### PR TITLE
decode: do not use 4-byte footer of FabricPath

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6394

Describe changes:
- decode: take into account Cisco FabricPath footer

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 199 | 187 | 93.97% | 

Pipeline 16471

**Comment by victorjulien** [comment]
Would like to see SV tests with this. Perhaps we can craft some with scapy.

**Comment by satta** [comment]
Also please note that even with this patch we still don't have the same behaviour as before. Instead of drops we now get huge `decoder.invalid` values which were not there before fdf9cdf40068f00147bb07dd3f41a7556b8de823.

**Review by victorjulien — CHANGES_REQUESTED** [review]
Needs more work, including test cases.

**Comment by catenacyber** [comment]
@satta do you have anomaly events ?  cf `ENGINE_SET_INVALID_EVENT`

**Comment by satta** [comment]
> @satta do you have anomaly events ? cf `ENGINE_SET_INVALID_EVENT`

Lots. I'm going to add details in the Redmine ticket.

**Comment by catenacyber** [comment]
Looks bad to have footer...

**Pull request closed without merging**
