### PR TITLE
logging: detect engine logging updates v2

### PR DESCRIPTION
**Pull request by jmtaylor90**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- updated SCLogError messages to be more consistent
- removed trailing space after log entry
- removed trailing newlines (updated after v1 review)
- enclosed fast_pattern in single quotes for readability (updated after v1 review)
- removed SCLogDebug entry mistakenly updated (updated after v1 review) 

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by victorjulien** [comment]
I can't get this to work with https://github.com/OISF/suricata-verify/pull/68

Keep getting
```
===> test-bad-byte-extract-rule-1: OK
===> test-bad-byte-extract-rule-2: OK
===> test-bad-content-dsize-rule-1: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': "signature can't match as content length 30 is bigger than dsize 10"}}
===> test-bad-content-quotes-rule-1: OK
===> test-bad-depth-depth-rule-1: OK
===> test-bad-depth-distance-rule-1: OK
===> test-bad-depth-distance-rule-2: OK
===> test-bad-depth-rule-1: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': 'depth needs preceding content, uricontent option, http_client_body, http_server_body, http_header option, http_raw_header option, http_method option, http_cookie, http_raw_uri, http_stat_msg, http_stat_code, http_user_agent, http_host, http_raw_host or file_data/dce_stub_data sticky buffer options'}}
===> test-bad-depth-within-rule-1: OK
===> test-bad-depth-within-rule-2: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': 'depth needs preceding content, uricontent option, http_client_body, http_server_body, http_header option, http_raw_header option, http_method option, http_cookie, http_raw_uri, http_stat_msg, http_stat_code, http_user_agent, http_host, http_raw_host or file_data/dce_stub_data sticky buffer options'}}
===> test-bad-dsize-offset-rule-1: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': "signature can't match as content length 2 with offset 100 (=102) is bigger than dsize 50"}}
===> test-bad-dsize-range-offset-rule-1: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': "signature can't match as content length 4 with offset 8 (=12) is bigger than dsize 10"}}
===> test-bad-dsize-range-rule-1: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': "signature can't match as content length 30 is bigger than dsize 10"}}
===> test-bad-hex-rule-1: OK
===> test-bad-hex-rule-2: OK
===> test-bad-hex-rule-3: OK
===> test-bad-negate-fast-pattern-rule-1: OK
===> test-bad-offset-distance-rule-1: OK
===> test-bad-offset-offset-rule-1: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'engine', 'engine.message': "can't use multiple offsets for the same content. "}}
```

Example eve.json for test-bad-dsize-offset-rule-1
```json
{"timestamp":"2019-05-28T09:25:59.310590+0000","log_level":"Notice","event_type":"engine","engine":{"message":"This is Suricata version 5.0.0-dev (rev 8a339e73d) running in USER mode"}}
{"timestamp":"2019-05-28T09:25:59.310931+0000","log_level":"Info","event_type":"engine","engine":{"message":"CPUs\/cores online: 12"}}
{"timestamp":"2019-05-28T09:25:59.317090+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":307,"error":"SC_ERR_SMB_CONFIG","message":"no SMB TCP config found, enabling SMB detection on port 445."}}
{"timestamp":"2019-05-28T09:25:59.318970+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":240,"error":"SC_ERR_DNS_CONFIG","message":"no DNS UDP config found, enabling DNS detection on port 53."}}
{"timestamp":"2019-05-28T09:25:59.319058+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":240,"error":"SC_ERR_DNS_CONFIG","message":"no DNS TCP config found, enabling DNS detection on port 53."}}
{"timestamp":"2019-05-28T09:25:59.328193+0000","log_level":"Info","event_type":"engine","engine":{"message":"No 'host-mode': suricata is in IDS mode, using default setting 'sniffer-only'"}}
{"timestamp":"2019-05-28T09:25:59.339533+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":261,"error":"SC_WARN_NO_STATS_LOGGERS","message":"stats are enabled but no loggers are active"}}
{"timestamp":"2019-05-28T09:25:59.340187+0000","log_level":"Info","event_type":"engine","engine":{"message":"Added \"42\" classification types from the classification file"}}
{"timestamp":"2019-05-28T09:25:59.340297+0000","log_level":"Info","event_type":"engine","engine":{"message":"Added \"19\" reference types from the reference.config file"}}
{"timestamp":"2019-05-28T09:25:59.340603+0000","log_level":"Error","event_type":"engine","engine":{"error_code":39,"error":"SC_ERR_INVALID_SIGNATURE","message":"signature can't match as content length 2 with offset 100 (=102) is bigger than dsize 50."}}
{"timestamp":"2019-05-28T09:25:59.340702+0000","log_level":"Error","event_type":"engine","engine":{"error_code":39,"error":"SC_ERR_INVALID_SIGNATURE","message":"error parsing signature \"alert udp any any -> any any (msg:\"TEST SUCCESFULL - dsize\/offset INVALID combination \"; dsize:50; content:\"AA\"; offset:100; sid:6666661; rev:1;)\" from file \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/test.rules at line 1"}}
{"timestamp":"2019-05-28T09:25:59.340763+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":43,"error":"SC_ERR_NO_RULES_LOADED","message":"1 rule files specified, but no rule was loaded at all!"}}
{"timestamp":"2019-05-28T09:25:59.340829+0000","log_level":"Info","event_type":"engine","engine":{"message":"Threshold config parsed: 0 rule(s) found"}}
{"timestamp":"2019-05-28T09:25:59.341108+0000","log_level":"Info","event_type":"engine","engine":{"message":"0 signatures processed. 0 are IP-only rules, 0 are inspecting packet payload, 0 inspect application layer, 0 are decoder event only"}}
{"timestamp":"2019-05-28T09:25:59.347376+0000","log_level":"Info","event_type":"engine","engine":{"message":"Argument \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/ was a directory"}}
{"timestamp":"2019-05-28T09:25:59.439702+0000","log_level":"Notice","event_type":"engine","engine":{"message":"all 13 packet processing threads, 2 management threads initialized, engine started."}}
{"timestamp":"2019-05-28T09:25:59.439884+0000","log_level":"Info","event_type":"engine","engine":{"message":"Starting directory run for \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/"}}
{"timestamp":"2019-05-28T09:25:59.439975+0000","log_level":"Info","event_type":"engine","engine":{"message":"Processing pcaps directory \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/, files must be newer than 0 and older than 18446744073709550616"}}
{"timestamp":"2019-05-28T09:25:59.440122+0000","log_level":"Info","event_type":"engine","engine":{"message":"Found \"\/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/eve.json\" at 1558082863662"}}
{"timestamp":"2019-05-28T09:25:59.440200+0000","log_level":"Info","event_type":"engine","engine":{"message":"Found \"\/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/.test.yaml.swp\" at 1559035559005"}}
{"timestamp":"2019-05-28T09:25:59.440241+0000","log_level":"Info","event_type":"engine","engine":{"message":"Found \"\/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/test.rules\" at 1558338244367"}}
{"timestamp":"2019-05-28T09:25:59.440274+0000","log_level":"Info","event_type":"engine","engine":{"message":"Found \"\/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/test.yaml\" at 1558338244367"}}
{"timestamp":"2019-05-28T09:25:59.440337+0000","log_level":"Info","event_type":"engine","engine":{"message":"Found \"\/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/suricata.yaml\" at 1558338244507"}}
{"timestamp":"2019-05-28T09:25:59.440471+0000","log_level":"Error","event_type":"engine","engine":{"error_code":44,"error":"SC_ERR_FOPEN","message":"unknown file format"}}
{"timestamp":"2019-05-28T09:25:59.440547+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":20,"error":"SC_ERR_PCAP_DISPATCH","message":"Failed to init pcap file \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/eve.json, skipping"}}
{"timestamp":"2019-05-28T09:25:59.440640+0000","log_level":"Error","event_type":"engine","engine":{"error_code":44,"error":"SC_ERR_FOPEN","message":"unknown file format"}}
{"timestamp":"2019-05-28T09:25:59.440674+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":20,"error":"SC_ERR_PCAP_DISPATCH","message":"Failed to init pcap file \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/test.rules, skipping"}}
{"timestamp":"2019-05-28T09:25:59.440746+0000","log_level":"Error","event_type":"engine","engine":{"error_code":44,"error":"SC_ERR_FOPEN","message":"unknown file format"}}
{"timestamp":"2019-05-28T09:25:59.440782+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":20,"error":"SC_ERR_PCAP_DISPATCH","message":"Failed to init pcap file \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/test.yaml, skipping"}}
{"timestamp":"2019-05-28T09:25:59.440840+0000","log_level":"Error","event_type":"engine","engine":{"error_code":44,"error":"SC_ERR_FOPEN","message":"unknown file format"}}
{"timestamp":"2019-05-28T09:25:59.440882+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":20,"error":"SC_ERR_PCAP_DISPATCH","message":"Failed to init pcap file \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/suricata.yaml, skipping"}}
{"timestamp":"2019-05-28T09:25:59.440945+0000","log_level":"Error","event_type":"engine","engine":{"error_code":44,"error":"SC_ERR_FOPEN","message":"unknown file format"}}
{"timestamp":"2019-05-28T09:25:59.440999+0000","log_level":"Warning","event_type":"engine","engine":{"error_code":20,"error":"SC_ERR_PCAP_DISPATCH","message":"Failed to init pcap file \/home\/victor\/sync\/devel\/suricata-verify\/tests\/test-bad-dsize-offset-rule-1\/\/.test.yaml.swp, skipping"}}
{"timestamp":"2019-05-28T09:25:59.441038+0000","log_level":"Info","event_type":"engine","engine":{"message":"Directory run mode complete"}}
{"timestamp":"2019-05-28T09:25:59.449876+0000","log_level":"Notice","event_type":"engine","engine":{"message":"Signal Received.  Stopping engine."}}
{"timestamp":"2019-05-28T09:25:59.476126+0000","log_level":"Info","event_type":"engine","engine":{"message":"time elapsed 0.134s"}}
{"timestamp":"2019-05-28T09:25:59.482276+0000","log_level":"Notice","event_type":"engine","engine":{"message":"Pcap-file module read 0 files, 0 packets, 0 bytes"}}
{"timestamp":"2019-05-28T09:25:59.487900+0000","log_level":"Info","event_type":"engine","engine":{"message":"Alerts: 0"}}
{"timestamp":"2019-05-28T09:25:59.512928+0000","log_level":"Info","event_type":"engine","engine":{"message":"cleaning up signature grouping structure... complete"}}
```

**Comment by victorjulien** [comment]
Ah I see I also needed https://github.com/OISF/suricata-verify/pull/64

**Comment by jmtaylor90** [comment]
> Ah I see I also needed [OISF/suricata-verify#64](https://github.com/OISF/suricata-verify/pull/64)

Ah yeah, sorry I should have been more clear about that. I didn't want to base/rebase it on 64 in case there was something broken there. I am open for suggestions on how I could do this better, it can get a little odd with dependencies between branches on suricata/suricata-verify.

**Comment by victorjulien** [comment]
Merged in #3896, thanks Jason!

**Pull request closed without merging**
