### PR TITLE
decode/ethertype: Event on unknown ethertype

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #11546 

Issue: 7129

Create a decode/engine event if unknown ethertypes are observed.

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7129

Describe changes:
- Add an event created when unknown ethertypes are observed
- Update schema with event counter
- Add rule for event.

Updates
- Formatting fixup.

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1954
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21726

**Comment by catenacyber** [comment]
A rebase should get CI green...

How could we get the unknown ether type logged ?

**Comment by jlucovsky** [comment]
Continued in #11632

**Comment by jasonish** [comment]
> How could we get the unknown ether type logged ?

We have an `ether` object in eve, we should add a type it. Its not logged by default though.  Also if you enable packet logging, this should log the alerting packet, that would have the ethertype as well.

**Pull request closed without merging**
