### PR TITLE
Resolving ticket 4052- Converting unittests to new FAIL/PASS API for …

### PR DESCRIPTION
**Pull request by JananiRamjee**
…detect-mark.c

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ .] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ .] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ .] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Resolved the ticket 4052- converting unittests to use FAIL/PASS API 
- Done for outreachy contributing phase 
- 

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by inashivb** [comment]
Hi Janani!
Thanks for your first contribution to the project! :)
The code changes look good but we'd require some modifications on commit message and formatting.
Commit message should be:
- Within 80 char limit
- ideally in imperative mood (e.g. Fix something [correct], Fixed something [incorrect], Fixing something [incorrect])
- Start with the areas of concern it is referring to e,g, for this PR: "detect/mark: Fix ...." [This can be tricky so don't worry if you don't get it right]
- Have a body in the commit message explaining the change (what was it like earlier, what's it like now and why did you make the changes)

We recently introduced clang formatting checks and its important for them to pass (first check that fails here). You can check out how to set up clang formatting with git here (https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format). 

Make sure that the QA is not failing because of the changes you made. You should always check though if there is a failure to see if it was an issue on GitHub's front.

Please make sure to read the contribution guidelines mentioned on Outreachy dashboard while submitting these changes.

Please incorporate these changes and we shall be happy to accept the PR.
Good job!

**Comment by JananiRamjee** [comment]
Hello,
Thanks for the feedback. Have made the required changes.
Regards
Janani

**Comment by inashivb** [comment]
The commit message does not seem to be limited to 80 chars on a line. Formatting check still seems to be failing. Commit history is not clean. Please make sure to have one commit only for one type of change.
No new commits should be added for making the changes requested unless its a different feature/addition/removal.

Please also make sure to create a new PR with the changes requested. We always require new PRs for any changes.

**Comment by inashivb** [comment]
@JananiRamjee this would be helpful for this as well as future PRs: https://github.com/OISF/suricata/blob/master/doc/devguide/codebase/code-style.rst

**Comment by JananiRamjee** [comment]
Hello,
Just a clarification. I am supposed to give a new pull request with one
commit only, right? Before committing, I need to run git-clang-format and
commit the changes with the commit message containing only 80 characters
per line.
Thank you
Regards
Janani

**Comment by inashivb** [comment]
@JananiRamjee that's correct!

**Comment by JananiRamjee** [comment]
Hello,
I have followed the previous steps and have given a new pull request. The
checks show that except Travis CI, every check is passed. Requesting your
feedback.
Thank you
Regards
janani

**Comment by inashivb** [comment]
Thanks, Janani!
Please close your previous PRs after creating a new one and link the new one there.

Replaced with #5481

**Pull request closed without merging**
