### PR TITLE
Convert byte_extract keyword parser to Rust

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #10712

Convert the byte_extract option parser from C to Rust.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6873](https://redmine.openinfosecfoundation.org/issues/6873)

Describe changes:
- Refactor code in rust/src/detect to support re-usability
- Implement the byte_extract parser in Rust, with unittests
- Modify the existing byte_extract module to use the Rust parser

Updates:
- Fixup rust check issues.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19787

**Comment by catenacyber** [comment]
> Updates:
> 
> * Fixup rust check issues.

Looks like there are more to fix :-p

**Review by catenacyber — CHANGES_REQUESTED** [review]
Need a green CI, the clippy warning seems legit

**Comment by jlucovsky** [comment]
> Need a green CI, the clippy warning seems legit

Will fix.

**Comment by jlucovsky** [comment]
Continued in #10797

**Pull request closed without merging**
