### PR TITLE
rust: collapse single match

### PR DESCRIPTION
**Pull request by TheKharleeci**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4605

This commit addresses rust "unnecessary_nested_match" clippy warnings.

Describe changes:
- Logger: Fix unnecessary_nested_match clippy warnings
- Remove #![allow(clippy::collapsible_match)] clippy lint from rust/src/lib.rs

ticket: #4605

Bug: #4605

Previous PR: #6515

### CODE REVIEW

**Comment by victorjulien** [comment]
Git message body needs a reference to the ticket:
`Bug: #XXXX.`

Also after the subject line use natural language, not `rust: ...` anymore.

**Comment by TheKharleeci** [comment]
> Git message body needs a reference to the ticket: `Bug: #XXXX.`
> 
> Also after the subject line use natural language, not `rust: ...` anymore.

Hi. I am sure I know where these changes should be made.

**Comment by victorjulien** [comment]
> > Git message body needs a reference to the ticket: `Bug: #XXXX.`
> > Also after the subject line use natural language, not `rust: ...` anymore.
> 
> Hi. I am sure I know where these changes should be made.

In the git commit message. It has a subject line, a blank line, then a message body.

**Comment by TheKharleeci** [comment]
> Git message body needs a reference to the ticket: `Bug: #XXXX.`
> 
> Also after the subject line use natural language, not `rust: ...` anymore.

Hi. Please do you mean my commit message should not start with 'rust:' anymore

**Comment by TheKharleeci** [comment]
Followed by: #6548

**Comment by jufajardini** [comment]
> > Git message body needs a reference to the ticket: `Bug: #XXXX.`
> > Also after the subject line use natural language, not `rust: ...` anymore.
> 
> Hi. Please do you mean my commit message should not start with 'rust:' anymore

Hi @TheKharleeci, I'll answer it here just in case this question arises for others, as well. :) What it's meant by that is that, besides the commit main message (in this case here `rust: collapse single match`), in the body of the commit message, it is a preferred practice for us to mention the redmine ticket number that is addressed in this commit. So an example of a full commit message could be as follows (see the commit at https://github.com/OISF/suricata/commit/536291054c96940):
```
flow/bypass: clear memory on bypass
    
Previously the flow would hold on to the app-layer and segment data
until the end of the flow, even though it would never be accessed again.
    
This patch clears app-layer and stream data, but not stream ssn as its
used in flow logging.
    
Bug: #4778.
```

**Pull request closed without merging**
