### PR TITLE
Vxlan backport/v5

### PR DESCRIPTION
**Pull request by shivan1b**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3068

### CODE REVIEW

**Comment by victorjulien** [comment]
The 2nd unittest will need the same logic. It passes now as well, but as a side effect.

**Comment by shivan1b** [comment]
Side effect is that the control never reaches to `DecodeVXLAN` func where the packet enqueing is handled because of `false` value returned by `DecodeVXLANEnabledForPort`.
In an ideal scenario, the `false` value should have been returned by `DecodeVXLANEnabledForPort`   because of the global setting but because port `1` does not have VXLAN enabled.

Is this correct, @victorjulien ?

**Comment by shivan1b** [comment]
Replaced with #4018

**Comment by victorjulien** [comment]
Yes exactly :)

**Pull request closed without merging**
