### PR TITLE
flow: complete stats for app_layer protocol counters

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5769

Describe changes:
- flow: complete stats for app_layer protocol counters

Last part of https://github.com/OISF/suricata/pull/8327 to have QA step by step

suricata-verify-pr: 1060

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.tls.parser | 931 | 1145 | 122.99% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.http | 3118951 | 3340798 | 107.11% |
| .app_layer.flow.tls | 510462 | 623355 | 122.12% |
| .app_layer.flow.ssh | 8937 | 11032 | 123.44% |
| .app_layer.flow.telnet | 1624 | 2334 | 143.72% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 199282 | 0.03 | 

Pipeline 11309

**Comment by victorjulien** [comment]
Do we have some SV tests that validate these new results?

**Comment by catenacyber** [comment]
> Do we have some SV tests that validate these new results?

@jasonish how could we have S-V check jq 'select(.event_type=="flow" and .app_proto=="ftp") | .app_proto'  log/eve.json | wc -l equals jq 'select(.event_type=="stats") | .stats."app_layer".flow.ftp' log/eve.json ?

**Comment by catenacyber** [comment]
> Do we have some SV tests that validate these new results?

Created https://github.com/OISF/suricata-verify/pull/1060

This is about the `STREAM_EOF` case.
The gap case comes from code inspection.

**Comment by victorjulien** [comment]
Merged in #8360, thanks!

**Pull request closed without merging**
