### PR TITLE
Multipart mime 3487 v15

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser

Follows #8882 by adding long line anomaly to get S-V happy

Still to do : 
- get answers for https://github.com/OISF/suricata/pull/8326 questions

```
SV_BRANCH=pr/1035
```
https://github.com/OISF/suricata-verify/pull/1035

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
  

Pipeline 13804

**Comment by catenacyber** [comment]
@ct0br0 waiting for a pcap with the 6 files with different hashes (1 http, and rest smtp)

**Comment by catenacyber** [comment]
Status :
- wait for merge of https://github.com/OISF/suricata/pull/8899
- then rebaseline of QA
- then rebase this PR and do a new iteration

Meanwhile, I can investigate the SMTP changes + do a C fix for body_md5 cf https://github.com/OISF/suricata-verify/pull/1035#issuecomment-1563083933

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/9036

**Pull request closed without merging**
