### PR TITLE
github-ci: run cocci in fedora 38

### PR DESCRIPTION
**Pull request by victorjulien**

### CODE REVIEW

**Comment by catenacyber** [comment]
Lucky guess ? Or do you know something I do not ?

**Comment by victorjulien** [comment]
> Lucky guess ? Or do you know something I do not ?

Don't know if it will be successful, but the guess is that fedora has newer stuff. Based on version number it will likely not work.

**Comment by victorjulien** [comment]
Looks like it's my lucky day.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 285 | 269 | 94.39% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 592373632 | 512215648 | 86.47% | 

Pipeline 15106

**Review by catenacyber — APPROVED** [review]
Nice

**Pull request merged**
