### PR TITLE
detect: make events prefilterable

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/6728

Describe changes:
- add prefilter for decode-event and such

Follows on https://github.com/OISF/suricata/pull/11559 rebased to get green CI, and hopefully not buggy codecov report

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1992

### CODE REVIEW

**Comment by catenacyber** [comment]
> Attention: Patch coverage is 15.15152% with 28 lines in your changes missing coverage. Please review.

My debug print is not agreeing with codecov :

I see `PrefilterSetupDecodeEvent` is called when running `python3 ../suricata-verify/run.py decode-too-small` with https://github.com/OISF/suricata-verify/pull/1992

**Comment by catenacyber** [comment]
Oh, codecov shows "?" for suricata-verify coverage...

**Comment by catenacyber** [comment]
We can still retrieve the data codecov sees as buggy and see
```
   81|       |static void PrefilterPacketEventSet(PrefilterPacketHeaderValue *v, void *smctx)
   82|     12|{
   83|     12|    const DetectEngineEventData *a = smctx;
   84|     12|    v->u8[0] = PREFILTER_U8HASH_MODE_EQ;
   85|     12|    v->u8[1] = a->event; // arg1
   86|     12|    v->u8[2] = 0;        // arg2
   87|     12|}
   88|       |
   89|       |static bool PrefilterPacketEventCompare(PrefilterPacketHeaderValue v, void *smctx)
   90|      0|{
   91|      0|    const DetectEngineEventData *a = smctx;
   92|      0|    DetectUintData_u8 du8;
   93|      0|    du8.mode = DETECT_UINT_EQ;
   94|      0|    du8.arg1 = a->event;
   95|      0|    du8.arg2 = 0;
   96|      0|    return PrefilterPacketU8Compare(v, &du8);
   97|      0|}
   98|       |
   99|       |static void PrefilterPacketEventMatch(DetectEngineThreadCtx *det_ctx, Packet *p, const void *pectx)
  100|      4|{
  101|      4|    const PrefilterPacketU8HashCtx *h = pectx;
  102|      8|    for (uint8_t u = 0; u < p->events.cnt; u++) {
  103|      4|        const SigsArray *sa = h->array[p->events.events[u]];
  104|      4|        if (sa) {
  105|      4|            PrefilterAddSids(&det_ctx->pmq, sa->sigs, sa->cnt);
  106|      4|        }
  107|      4|    }
  108|      4|}
  109|       |
  110|       |static int PrefilterSetupStreamEvent(DetectEngineCtx *de_ctx, SigGroupHead *sgh)
  111|      2|{
  112|      2|    return PrefilterSetupPacketHeaderU8Hash(de_ctx, sgh, DETECT_STREAM_EVENT,
  113|      2|            SIG_MASK_REQUIRE_ENGINE_EVENT, PrefilterPacketEventSet, PrefilterPacketEventCompare,
  114|      2|            PrefilterPacketEventMatch);
  115|      2|}
  116|       |
  117|       |static int PrefilterSetupDecodeEvent(DetectEngineCtx *de_ctx, SigGroupHead *sgh)
  118|      5|{
  119|      5|    return PrefilterSetupPacketHeaderU8Hash(de_ctx, sgh, DETECT_DECODE_EVENT,
  120|      5|            SIG_MASK_REQUIRE_ENGINE_EVENT, PrefilterPacketEventSet, PrefilterPacketEventCompare,
  121|      5|            PrefilterPacketEventMatch);
  122|      5|}
```

So, there is more coverage than said here...

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21758

**Comment by catenacyber** [comment]
TODO: SV test should test prefilter auto mode

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11604

**Pull request closed without merging**
