### PR TITLE
Dev/rustify x509 v4

### PR DESCRIPTION
**Pull request by chifflier**
Previous PR: #4663

Describe changes (to previous PR):

- reorder commit history, merge related commits
- add mapping from the Rust decoder return values to suricata decoder events
  - note: event IDs are duplicated for now, when `enum` will be exported in `cbindgen` the duplication can be removed

### CODE REVIEW

**Comment by victorjulien** [comment]
Commit order is wrong. First commit depends on a later commit. Please make sure each commit builds.

**Comment by victorjulien** [comment]
General policy is that each commit should build, to make sure `git bisect` is useful.

**Comment by chifflier** [comment]
Doh, my bad.
@victorjulien after reorder and checks, should I resubmit a PR, or force-push?

**Comment by chifflier** [comment]
> Doh, my bad.
> @victorjulien after reorder and checks, should I resubmit a PR, or force-push?

nm the question, I created another branch

**Comment by chifflier** [comment]
Continued in #4721

**Pull request closed without merging**
