### PR TITLE
detect/mark:Fix unittest into FAIL/PASS API

### PR DESCRIPTION
**Pull request by JananiRamjee**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ .] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ .] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ .] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4052

Describe changes:
- Removed initial test methods in detect-mark.c
- Used FAIL or PASS macros described in util-unittest.h
- FAIL/PASS macros determine conditionals for return value(0 or 1 respectively)

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by inashivb** [comment]
Hi, Janani!
The travis failure seems legit. Would you like to try and see what happened here? https://travis-ci.com/github/OISF/suricata/jobs/398159243#L1987

**Comment by JananiRamjee** [comment]
> Hi, Janani!
> The travis failure seems legit. Would you like to try and see what happened here? https://travis-ci.com/github/OISF/suricata/jobs/398159243#L1987

Sure! Will check the error out and report back

**Comment by JananiRamjee** [comment]
> Hi, Janani!
> The travis failure seems legit. Would you like to try and see what happened here? https://travis-ci.com/github/OISF/suricata/jobs/398159243#L1987

hello @inashivb,
I think I have fixed the error. Can i commit it again in this branch? Or should I close this PR and give a new one?

**Comment by inashivb** [comment]
> > Hi, Janani!
> > The travis failure seems legit. Would you like to try and see what happened here? https://travis-ci.com/github/OISF/suricata/jobs/398159243#L1987
> 
> hello @inashivb,
> I think I have fixed the error. Can i commit it again in this branch? Or should I close this PR and give a new one?

You should close this one and create a new PR.

**Comment by inashivb** [comment]
Replaced with #5483

**Pull request closed without merging**
