### PR TITLE
fuzz: adds MSAN to CIFuzz

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4125

Describe changes:
- Adds memory sanitizer to CIFuzz

cf https://github.com/google/oss-fuzz/issues/4614
cc @jonathanmetzman

Let's see if CI works

### CODE REVIEW

**Comment by catenacyber** [comment]
So, not working

**Comment by victorjulien** [comment]
How is it expected to work? It somehow builds in a place that has special compiled versions of our dependencies like pcre?

**Comment by catenacyber** [comment]
> It somehow builds in a place that has special compiled versions of our dependencies like pcre?

Yes, it should have prebuilt MSAN-compiled versions of some libraries like pcre
That is how oss-fuzz does it. CIFuzz is getting fixed to do the same apparently

**Comment by jonathanmetzman** [comment]
> > It somehow builds in a place that has special compiled versions of our dependencies like pcre?
> 
> Yes, it should have prebuilt MSAN-compiled versions of some libraries like pcre
> That is how oss-fuzz does it. CIFuzz is getting fixed to do the same apparently

+1 Maybe we can close this PR. I can reopen a similar one and use it to debug a branch I'm working on when I next get a chance to fix this (probably after the holidays).

**Pull request closed without merging**
