### PR TITLE
fuzz: specify protocol with fuzz target name

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4125

Describe changes:
- Make fuzz target about app-layer force a protocol based on its name

So that oss-fuzz can have one fuzz target for each protocol, just by copying and using another name
Tested with my oss-fuzz branch suricataproto

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you add more explanation to the git commit, including ticket ref?

Would it make sense to have our buildsys output these binaries based on the app protocols we have in the code?

**Comment by catenacyber** [comment]
> Would it make sense to have our buildsys output these binaries based on the app protocols we have in the code?

I do not think so.
It is the same binary.
The hack is oss-fuzz is to use the binary name, as we use the env variable, to find out which app-layer we will be fuzzing.

**Comment by catenacyber** [comment]
Force-pushed with reworded commit

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6029

**Pull request closed without merging**
