### PR TITLE
next/649/20241128/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #12043
 - #12172

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .http.byterange.memuse | 99602115 | 104101775 | 104.52% | 

Pipeline 23598

**Review by jasonish — APPROVED** [review]
Looks OK.

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 624 | 648 | 103.85% | 

Pipeline 23601

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23603

**Pull request merged**
