### PR TITLE
RFC: github-actions: example test workflows - v1

### PR DESCRIPTION
**Pull request by jasonish**
This is an example of using GitHub actions to perform
the following builds:

- MacOS
- Fedora 31 (in container)
- Ubuntu 18.04 with Coccinelle
- Ubuntu 16.04, using dist tarball artifact from the
  Fedora 31 build.

### CODE REVIEW

**Comment by jasonish** [comment]
A PR here doesn't seem to trigger the action. It did against my own repo tho:
https://github.com/jasonish/suricata/pull/16

**Comment by victorjulien** [comment]
I like it. Are there disadvantages vs using travis? Like maybe stricter resource limits?

**Comment by jasonish** [comment]
> I like it. Are there disadvantages vs using travis? Like maybe stricter resource limits?

As far as I can tell, it will only do 20 concurrent jobs (5 on Mac). Each workflow has a maximum runtime of 6 hours. But otherwise no limits, extra jobs will just be queued.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits

Other disadvantages include:
- Not able to restart just one job in the workflow.
- The UI is not quite as nice.
- No ARM builder (this is a fairly new Travis CI feature we don't use)

The pros are that it has Windows, Linux and Mac all in one place. First class Docker support so we can easily test on any distribution. Defining a build is simpler.

**Comment by victorjulien** [comment]
Maybe we can expand the integration a bit further and run it parallel to travis for a few weeks. It definitely sounds interesting.

**Comment by jasonish** [comment]
> Maybe we can expand the integration a bit further and run it parallel to travis for a few weeks. It definitely sounds interesting.

Any tests you'd like to see added right away? I'd like to try Windows, but that would be more time consuming.

I'm probably going to add this to Suricata-Update as well. It will really benefit from tests across multiple distros.

**Comment by victorjulien** [comment]
Can we get as many from 'tier 1' in as reasonable? https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Support_Status

Windows may be a bit much work, although the appveyor config would be a good start. Since that is working well for us, I'm fine with skipping windows for this test.

**Comment by jasonish** [comment]
Closing. Continued at https://github.com/OISF/suricata/pull/4392.

**Pull request closed without merging**
