### PR TITLE
Remove duplicate function declarations-v4

### PR DESCRIPTION
**Pull request by Nancyenos**
Ticket: #7297

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7297

Describe changes:
-Remove duplicate function declarations from header files
-Add  a prefix misc:  to the subject
-previous pr: #11993

### CODE REVIEW

**Review by inashivb — COMMENTED** [review]
Hi @Nancyenos !
The subject line change is to be done in the commit not the PR title. ;)

**Comment by Nancyenos** [comment]
@inashivb is it okay now?

**Comment by jufajardini** [comment]
> @inashivb is it okay now?

The commit message is good now, thanks (although we prefer not having PRs with force-pushes ;) )
The failing check, although not due to your PR, is probably something that we'll need to sort out, as the failure means those checks did not run on your changes.

**Comment by Nancyenos** [comment]
worked continued in #12015

**Pull request closed without merging**
