### PR TITLE
docs: improve code documentation- v5

### PR DESCRIPTION
**Pull request by zazie-codes**
Task #6383

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:https://redmine.openinfosecfoundation.org/issues/6383

Describe changes:
This is an update of #9649
-squashed all commits.
-added the space in layer src/app-layer-htp-libhtp.h
-interchanged file description to come after author credentials to conform to guidelines.

### CODE REVIEW

**Comment by zazie-codes** [comment]
I've noticed a clang format error. Im correcting it right now.

**Comment by jufajardini** [comment]
> I've noticed a clang format error. Im correcting it right now.

Nice :)

I'm a bit confused with the CI checks, as they seem to be linking the checks to PR #9611. Could you please, just in case, rebase your branch to Suricata newest master, when applying the formatting fixes? Not sure what is making GH link the workflows like that...

**Comment by zazie-codes** [comment]
> > I've noticed a clang format error. Im correcting it right now.
> 
> Nice :)
> 
> I'm a bit confused with the CI checks, as they seem to be linking the checks to PR #9611. Could you please, just in case, rebase your branch to Suricata newest master, when applying the formatting fixes? Not sure what is making GH link the workflows like that...

In not certain but could it be because i used a new branch that the master will commit from?

**Comment by jufajardini** [comment]
> > > I've noticed a clang format error. Im correcting it right now.
> > 
> > 
> > Nice :)
> > I'm a bit confused with the CI checks, as they seem to be linking the checks to PR #9611. Could you please, just in case, rebase your branch to Suricata newest master, when applying the formatting fixes? Not sure what is making GH link the workflows like that...
> 
> In not certain but could it be because i used a new branch that the master will commit from?

Not sure, but Shivani re-ran the CI checks, and now it has passed. Maybe github had a hiccup...

**Review by jufajardini — APPROVED** [review]
Looks good to me, thanks :)

**Review by jasonish — APPROVED** [review]

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #9701, thanks!

**Pull request closed without merging**
