### PR TITLE
Backports port grouping/v3

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- https://redmine.openinfosecfoundation.org/issues/6830
- https://redmine.openinfosecfoundation.org/issues/6520
- https://redmine.openinfosecfoundation.org/issues/6829
- https://redmine.openinfosecfoundation.org/issues/6844
- https://redmine.openinfosecfoundation.org/issues/6845
- https://redmine.openinfosecfoundation.org/issues/6895

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1729

Previous PR: https://github.com/OISF/suricata/pull/10612

Changes since v2:
- rebased on top of latest main-7.0.x
- backports for one more ticket

### CODE REVIEW

**Comment by inashivb** [comment]
Should we continue to use clang-format-9 in 7.0.x and update the commits accordingly? Or, backport https://github.com/OISF/suricata/commit/93071501b5a233b0499dc4c5f00ba9be34eb2c52?

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19780

**Comment by victorjulien** [comment]
> Should we continue to use clang-format-9 in 7.0.x and update the commits accordingly? Or, backport [9307150](https://github.com/OISF/suricata/commit/93071501b5a233b0499dc4c5f00ba9be34eb2c52)?

I think backporting that makes sense. What do you think @jasonish?

**Comment by jasonish** [comment]
> I think backporting that makes sense. What do you think @jasonish?

Makes sense to me.  Should ease the backport process a little.

**Pull request closed without merging**
