### PR TITLE
Multipart mime 3487 v43

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser
- json schema : add email.received + email.cc array and reorder

Follows #11215 with off by one fix for snprintf about url extraction config schemes

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1869

### CODE REVIEW

**Comment by victorjulien** [comment]
add https://github.com/OISF/suricata/pull/11223/commits/ec743f01ef92eb7722ad062d0d0029c596386732 for green CI

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20933

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
CI was red because SV PR was not up to date with SV master.
Leaving as is as this PR is approved

**Comment by victorjulien** [comment]
Merged in #11227, thanks!

**Pull request closed without merging**
