### PR TITLE
Ipv6 frag 4664 v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4664

Describe changes:
- Generic check for IPv6 fragments overlap

suricata-verify-pr: 535

https://github.com/OISF/suricata-verify/pull/535

### CODE REVIEW

**Comment by catenacyber** [comment]
Cf more precisely ipv6-malformed-fragments-8 where we have 
```
mf true frag_offset 0 data_offset 62, data_len 408, frag_end 408, ip_hdr_offset 14, frag_hdr_offset 54
mf false frag_offset 808 data_offset 62, data_len 400, frag_end 1208, ip_hdr_offset 14, frag_hdr_offset 54
mf true frag_offset 408 data_offset 62, data_len 528, frag_end 936, ip_hdr_offset 14, frag_hdr_offset 54
```
and no overlap is given when last fragment [408:936] overlaps with previous one [808:1208]

**Comment by catenacyber** [comment]
Suricata-verify passes locally and seems to fail on CI... I do not see why

**Comment by catenacyber** [comment]
> Suricata-verify passes locally and seems to fail on CI... I do not see why

Oh, some file were not added in the GitHub S-V PR...

**Review by jasonish — CHANGES_REQUESTED** [review]
The commit message is a bit vague.  Suggests its just a simpler check for overlaps, however behaviour is changed.  Can you add that to the commit message please?  The ticket is a little vague in that area as well.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6400

**Pull request closed without merging**
