### PR TITLE
Feature/http range/v15

### PR DESCRIPTION
**Pull request by victorjulien**
Continuation of #6282. Removes the per tracker mutex in favor of the THashData lock. Various other cleanups and fixes.
Fixes CI issues in #6292

suricata-verify-pr: 517

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3781

**Comment by victorjulien** [comment]
Replaced by #6295

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3781

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3781

**Comment by suricata-qa** [comment]
ERROR: ASAN TRIP in tlpr1_asan_suri QA test

Pipeline 3781

**Pull request closed without merging**
