### PR TITLE
Feature: extract message body for smtp protocol 

### PR DESCRIPTION
**Pull request by superway117**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5737) ticket:

Describe changes:
- extract body message from smtp protocol
- enable or disable extract smtp body message in suricata.yaml.in
- enable or disable save smtp body message to eve-log in suricata.yaml.in

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hello, 

There are a few things going on here.
First, I wonder if the work done in #8299 impacts or affects what you are trying to do here in any way (as in - do these changes overlap, is there duplicated effort somewhere?).

Once that's answered, if both efforts are necessary, we must address:
- the commit messages are very out of our guidelines. Please keep the commit title within the 50 characters limit, and use the `module: commit addition` style, as explained in https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits
- any details may go in the commit body, which should also contain the redmine ticket number, like so: `Task #XXXX`
- please make sure to configure your author/username and email for your git commits. Right now it's showing the default "Your Name <you@example.com>", instead of your info. (this link may help with that: https://www.git-tower.com/learn/git/faq/change-author-name-email)
- Also, there are still CI failures, please check and fix them for your next PR. ;)

If any of those comments are unclear, please let us know, so we can clarify.

**Comment by superway117** [comment]
> Hello,
> 
> There are a few things going on here. First, I wonder if the work done in #8299 impacts or affects what you are trying to do here in any way (as in - do these changes overlap, is there duplicated effort somewhere?).
> 
> Once that's answered, if both efforts are necessary, we must address:
> 
> * the commit messages are very out of our guidelines. Please keep the commit title within the 50 characters limit, and use the `module: commit addition` style, as explained in https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits
> * any details may go in the commit body, which should also contain the redmine ticket number, like so: `Task #XXXX`
> * please make sure to configure your author/username and email for your git commits. Right now it's showing the default "Your Name [you@example.com](mailto:you@example.com)", instead of your info. (this link may help with that: https://www.git-tower.com/learn/git/faq/change-author-name-email)
> * Also, there are still CI failures, please check and fix them for your next PR. ;)
> 
> If any of those comments are unclear, please let us know, so we can clarify.

Hello
from  https://github.com/OISF/suricata/pull/8299 , looks the detect and parse for smtp is moving to rust, right? if yes, then there are double effort.  i could close my issue.

another question, we are also writing code for mysql and pop3 using c language, looks  all app detect and parse are moving to rust, right?  if yes, looks we should stop using c language to write app layer.


the commit messages are very out of our guidelines. Please keep the commit title within the 50 characters limit, and use the module: commit addition style, as explained in https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits
any details may go in the commit body, which should also contain the redmine ticket number, like so: Task #XXXX
please make sure to configure your author/username and email for your git commits. Right now it's showing the default "Your Name [you@example.com](mailto:you@example.com)", instead of your info. (this link may help with that: https://www.git-tower.com/learn/git/faq/change-author-name-email)
Also, there are still CI failures, please check and fix them for your next PR. ;)

**Comment by superway117** [comment]
hello
first, from [#8299](https://github.com/OISF/suricata/pull/8299), looks the smtp is moving to rust language, right? if yes, current we use c language to enhancement the feature, then there are double effort. so i will close this issue.
in fact , we are writing code for mysql and pop3 detect and parse using c language, looks all the app layer will move to rust in the future, right? 

for the problem of PR
1. commit title and commit body is out of guidelines
 -->  sorry for that,   i will check the guidelines, and fix them for the next PR
2. no author/username/email for git
 -->  i use a new machine to commit code,  i will fill them later
3. CI failures: Clang format
 --> i am really confused, i use `./clang-format.sh commit ` to format my codes, why stilll raise failures? 
4. CI failures: build failed on Window and MacOS
 --> from the CI log, i can't find any clue to location what happened. normally i use Ubunut to test my code.

**Comment by superway117** [comment]
sorry , i close it for misoperation

**Comment by jufajardini** [comment]
> 
> hello first, from [#8299](https://github.com/OISF/suricata/pull/8299), looks the smtp is moving to rust language, right? if yes, current we use c language to enhancement the feature, then there are double effort. so i will close this issue. in fact , we are writing code for mysql and pop3 detect and parse using c language, looks all the app layer will move to rust in the future, right?
> 
You understood it correctly: we are trying to move our application layer parsers to rust, and we do ask that new application layer protocols are developed in Rust. :)

> for the problem of PR
> 
> 1. commit title and commit body is out of guidelines
>    -->  sorry for that,   i will check the guidelines, and fix them for the next PR
Thanks! This makes reviewing and following up on review requests much easier, it also helps when you're incorporating reviews, if you follow the tip for creating new branches for new PRs ^^

> 2. no author/username/email for git
>    -->  i use a new machine to commit code,  i will fill them later
Ok, just please remember to have this fixed with your next PR 

> 3. CI failures: Clang format
>    --> i am really confused, i use `./clang-format.sh commit ` to format my codes, why stilll raise failures?
I didn't check al the failures, but maybe there were format changes needed in more than one commit? Have you tried using `./scripts/clang-format.sh branch` ?

> 4. CI failures: build failed on Window and MacOS
>    --> from the CI log, i can't find any clue to location what happened. normally i use Ubunut to test my code.
If there are no other failures, just those, then maybe we can try to re-run the CI checks and see if that helps. For now, there are other things that need fixing, so it's harder to figure out what may be wrong with those checks...

**Review by inashivb — COMMENTED** [review]
Hello @superway117 !
Thank you for your first contribution to our project. :)
Why do you want to log the mime body? Do we have any special information in there that might help with analysis and/or detection.

**Comment by victorjulien** [comment]
Closing due to inactivity. If you're interested in picking this back up, please open a new PR addressing the comments. Thanks!

**Pull request closed without merging**
