### PR TITLE
Pkt ptrs/v44

### PR DESCRIPTION
**Pull request by victorjulien**
#10926, rebased.

Adds an improvement of handling retransmissions of offset 0 frags.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20344

**Comment by jasonish** [comment]
Commit 592664bbc3cd4b050e887969442e8ba1c3bd5252 is essentially undone in the commit just after it?

**Comment by jasonish** [comment]
Only a review comment so far.. Its not as complex as the diff size might make you think at first, but would like:
- A ticket with the purpose and goals stated - its a rather large bit of work without that covered
- I find some commits lacking in detail, ie: `decode/icmpv6: store embedded ip6h ptr as offset`? Why change from pointer to offset.

**Comment by victorjulien** [comment]
Added some tickets and more explanations in #10961

**Pull request closed without merging**
