### PR TITLE
github-ci: fix rust check by fixing git directory permissions - v1

### PR DESCRIPTION
**Pull request by jasonish**
Due to the update to AlmaLinux 9.2, a new version of git with stricter
permissions was introduced.  Mark the directory as safe as we have
done in other builds with newer versions of it.

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113274 | 145196 | 128.18% | 

Pipeline 13742

**Comment by victorjulien** [comment]
Should we just remove the offending comment now?

**Comment by victorjulien** [comment]
Merged this, but hacked around more CI in: issueshttps://github.com/OISF/suricata/pull/8867/commits/d4c60924f1c6f692192bef8584d0ea53d1f342d2

Probably needs a proper fix.

**Comment by jasonish** [comment]
> Merged this in #8867, but hacked around more CI in: issues [d4c6092](https://github.com/OISF/suricata/commit/d4c60924f1c6f692192bef8584d0ea53d1f342d2)
> 
> Probably needs a proper fix.

Whats the hack that needs the proper fix?

**Comment by jasonish** [comment]
Weird, the fix in this PR worked locally, missed that it failed here as well.

**Pull request closed without merging**
