### PR TITLE
Multipart mime 3487 v36

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser

Follows #10547 with needed rebase after e38ec7d0a7b71650f3b2cfb543a21b671daacaca (ignoring it as rust does it differently)

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
  

Pipeline 19877

**Comment by catenacyber** [comment]
https://github.com/OISF/suricata/pull/10739 fixes the root cause for not having one file missing in master with QA SURI_TLPW1_files_sha256

**Comment by catenacyber** [comment]
Will rebase after merge of https://github.com/OISF/suricata/pull/10739

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/11115

**Pull request closed without merging**
