### PR TITLE
Doc/experiments/v3

### PR DESCRIPTION
**Pull request by victorjulien**
#5665 with a few additions, adding some indication if something is problem indicator

### CODE REVIEW

**Comment by catenacyber** [comment]
cc @jufajardini for the dev guide ?

**Comment by jufajardini** [comment]
> cc @jufajardini for the dev guide ?

The real code snippets is a great tip, thanks <3 anything else in particular that you had in mind?

**Comment by catenacyber** [comment]
> The real code snippets is a great tip, thanks <3 anything else in particular that you had in mind?

Nothing beyond that.
I do not know what Victor expects out of this PR...

**Comment by suricata-qa** [comment]
ERROR: QA failed on build_asan.
  

Pipeline 6128

**Comment by pevma** [comment]
Needs rebase.

**Pull request closed without merging**
