### PR TITLE
ftp: add events for request/response command being too long - v1

### PR DESCRIPTION
**Pull request by jasonish**
This adds events for when a FTP request or response command is too long
requiring truncation.

I wanted to use the Rust "generics" for the boiler plate of defining app-layer
events, however the way we export enums from Rust to C wasn't very compatible
with the auto-naming of app-layer events into a scheme that fits our current
convention.

To fix this, I modified the cbindgen configuration to do enum naming from
idiomatic Rust names to C style names, which are more to our naming convention
for C enums. As this renamed all export enum fields the commit is quite large.

Once that was done, the FTP events could be added with Rust.

Finally I went looking for SID range documentation in-tree and didn't find any,
and I feel it should be there.

suricata-verify-pr: 1072

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.error.tls.parser | 931 | 1145 | 122.99% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.http | 3118951 | 3340800 | 107.11% |
| .app_layer.flow.tls | 510462 | 623355 | 122.12% |
| .app_layer.flow.ssh | 8937 | 11032 | 123.44% |
| .app_layer.flow.telnet | 1624 | 2334 | 143.72% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 492621 | 0.08 | 

Pipeline 11818

**Comment by victorjulien** [comment]
While it makes the code look nicer and more idiomatic, I think this has a important drawback: which is that something like `git grep SSH_CONNECTION_STATE_BANNER_DONE` will now not give a quick view into where things happen for that state, but instead we'll need to grep twice (once for ` SSH_CONNECTION_STATE_BANNER_DONE` and once for `BannerDone`) and there will be no single place where the two are obviously mapped.

**Comment by jasonish** [comment]
> While it makes the code look nicer and more idiomatic, I think this has a important drawback: which is that something like `git grep SSH_CONNECTION_STATE_BANNER_DONE` will now not give a quick view into where things happen for that state, but instead we'll need to grep twice (once for ` SSH_CONNECTION_STATE_BANNER_DONE` and once for `BannerDone`) and there will be no single place where the two are obviously mapped.

Hmm.. Good point.  I'll probably have to back peddle on this and use a C implementation of `get_event_info` and `get_event_info_by_id` as the alert name generation doesn't work well with enum's with a stutter in them.... Or what might have been simpler is just a Rust method for each event type exported to C to not have to worry about exporting the enum at all.  Thats what I think I'll go with.

**Comment by jasonish** [comment]
Replaced by https://github.com/OISF/suricata/pull/8425.

**Pull request closed without merging**
