### PR TITLE
github-ci: Master CI improvements re: Travis CI for 5.0.x

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #5608 

Batch CI backports to 5.0.x

Describe changes:
- Multiple commits from master for CI additions.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
I think this should be synced to #5633 once that is merged.

**Comment by jlucovsky** [comment]
> I think this should be synced to #5633 once that is merged.

I'll update my branch when that pr is merged.

**Comment by victorjulien** [comment]
Also add https://github.com/OISF/suricata/pull/5649/commits/49ca070446cdca49afc42d71aaedaa9a1b458897

**Comment by jlucovsky** [comment]
Continued in #5652

**Pull request closed without merging**
