### PR TITLE
Next/60x/20220228/v2

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
- #7031 w/o the nfs commit
- #7024

CIFuzz is expected to fail due to NFS.

### CODE REVIEW

**Comment by victorjulien** [comment]
Interesting, looks like CIFuzz (undefined) found a new corner case for when an IP-only sig uses `0.0.0.5/0.0.0.5`.

**Comment by victorjulien** [comment]
> Interesting, looks like CIFuzz (undefined) found a new corner case for when an IP-only sig uses `0.0.0.5/0.0.0.5`.

https://redmine.openinfosecfoundation.org/issues/5168

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 6440

**Comment by inashivb** [comment]
This was added to #7089 . Thanks!

**Pull request closed without merging**
