### PR TITLE
dpdk: fix received/error counters v2

### PR DESCRIPTION
**Pull request by lukashino**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

This PR does not have a Redmine ticket, rather addresses an issue found by @amaan-fmad in https://github.com/OISF/suricata/pull/6652/files#r765566286. Follow up on the PR #6714 where I understood that resetting NIC's counters might not be the best approach.

Describe changes:
- refactor the way counters are set
- from dropped packets removed erroneous packets in TX direction
- from RX erroneous packets removed incoming pkts counter (the root of the original issue)
- setting number of incoming packets per thread to thread counters (shown in stats.log)
- setting number of incoming packets per port on worker 0 to livedev

### CODE REVIEW

**Comment by lukashino** [comment]
For the purposes of tracking, I've created a [Redmine ticket 4935](https://redmine.openinfosecfoundation.org/issues/4935)

**Comment by tbarbette** [comment]
Hey! Before opening another issue, will this fix the following problem ?
With 2 interfaces, I see : 
`Stats for '0000:51:00.1':  pkts: 11872, drop: 11872 (100.00%), invalid chksum: 0 `
I actually got it to more than 100% once.

Also, the stats seem wrong : 
stats.log:
`capture.packets                               | Total                     | 20775                                                                                                                                                              capture.rx_errors                             | Total                     | 20775                                                                                                                                                              decoder.pkts                                  | Total                     | 20775`
Thanks!

**Comment by lukashino** [comment]
Yes indeed, I was setting the stats wrong. I was putting both received and error counters to Suricata's drop counter. 
When you had it over 100% it could have been possible that you encountered errors while receiving. 

This PR should solve the issue!

**Comment by victorjulien** [comment]
Merged in #6802, thanks!

**Comment by lukashino** [comment]
@victorjulien please close the issue in https://redmine.openinfosecfoundation.org/issues/4935
I can't seem to do it myself. 
Thanks

**Comment by victorjulien** [comment]
> @victorjulien please close the issue in https://redmine.openinfosecfoundation.org/issues/4935 I can't seem to do it myself. Thanks

Done!

**Pull request closed without merging**
