### PR TITLE
Backports/706/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Backports for:
https://redmine.openinfosecfoundation.org/issues/6950
https://redmine.openinfosecfoundation.org/issues/7038
https://redmine.openinfosecfoundation.org/issues/7035
https://redmine.openinfosecfoundation.org/issues/7023
https://redmine.openinfosecfoundation.org/issues/7021
https://redmine.openinfosecfoundation.org/issues/7043

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1849

### CODE REVIEW

**Comment by ct0br0** [comment]
qa tokens ran out. ignore the 'pipeline canceled' incoming

**Comment by catenacyber** [comment]
Should there be more commits from https://github.com/OISF/suricata/pull/11106 ?

Which PR are you back porting ?

**Comment by victorjulien** [comment]
> Should there be more commits from #11106 ?
> 
> Which PR are you back porting ?

No, I left the general cleanup commits out. I'm backporting from `master` for the tickets mentioned above.

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11135, thanks!

**Pull request closed without merging**
