### PR TITLE
eve: remove duplicate fields from json - v1

### PR DESCRIPTION
**Pull request by jasonish**
Fixes for the following duplicate JSON field tickets:
- https://redmine.openinfosecfoundation.org/issues/5813
- https://redmine.openinfosecfoundation.org/issues/5814
- https://redmine.openinfosecfoundation.org/issues/5811

The RFB one (5813) was trival.  5814 and 5811 (SMB) need review.

Also includes a commit to github-ci to better highlight what suricata-verify pr
among other variables are being used.

Commits:
- smb: remove duplicate tree_id logging
- eve: remove dcerpc.interface from schema
- smb: fix duplicate interface logging
- rfb: remove duplicate logging of depth
- github-ci: annotate job with s-v info

Previous PR: https://github.com/OISF/suricata/pull/8455

Changes from last PR:
- Fix missing jsonbuilder close.

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_single_stats_chk | | |
| .tcp.ssn_from_cache | 264554 | 339437 | 128.31% |
| .tcp.ssn_from_pool | 628437 | 553554 | 88.08% |
| | SURI_TLPW2_autofp_stats_chk | | |
| .tcp.ssn_from_cache | 298547 | 380587 | 127.48% |
| .tcp.ssn_from_pool | 594444 | 512404 | 86.2% |
| | SURI_TLPW1_stats_chk | | |
| .tcp.ssn_from_cache | 63596 | 79013 | 124.24% |
| .tcp.ssn_from_pool | 139220 | 123803 | 88.93% |
| .tcp.rst | 128116 | 113546 | 88.63% |
| .app_layer.error.dns_udp.parser | 1276 | 0 | - |
| .ftp.memuse | 862 | 348 | 40.37% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 580947328 | 533846400 | 91.89% |
| .tcp.ssn_from_cache | 3644947 | 6041464 | 165.75% |
| .tcp.ssn_from_pool | 8484810 | 6088267 | 71.75% |
| .tcp.synack | 7538139 | 10142824 | 134.55% |
| .tcp.rst | 5264608 | 6763128 | 128.46% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .app_layer.error.dns_udp.parser | 28003 | 0 | - |
| .http.memuse | 16440 | 2104 | 12.8% |
| .ftp.memuse | 13827 | 11093 | 80.23% |
| | IPS_AFP_stats_chk | | |
| .tcp.segment_from_pool | 17089689 | 15759624 | 92.22% |
| | TREX_GENERIC_stats_chk | | |
| .tcp.segment_from_pool | 15728353 | 14926407 | 94.9% | 

Pipeline 12025

**Comment by victorjulien** [comment]
What causes the rust check to fail?

**Comment by jasonish** [comment]
> What causes the rust check to fail?

The new lints, but the fixes for those have been merged into master.  This predates that PR.

**Comment by jasonish** [comment]
Rebase here: https://github.com/OISF/suricata/pull/8483

**Pull request closed without merging**
