### PR TITLE
Applayer plugin 5053 v3.2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
Preliminary work for https://redmine.openinfosecfoundation.org/issues/5053

Describe changes:
- get ready to use dynamic number of app-layer protos (also work with static constant) in some places
- preventive fix of macro with parenthesis cc @jufajardini 

#11572 next round

Still more work to do after : 
Only `AppProtoStrings` is to be handled, but it is the big one.

And then take remaining commits out of https://github.com/OISF/suricata/pull/11321
And supply an example of an app-layer plugin

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 22315

**Comment by catenacyber** [comment]
Draft to see CI with array dimensions well ordered..

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22316

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22320

**Comment by catenacyber** [comment]
Clean in https://github.com/OISF/suricata/pull/11701

**Pull request closed without merging**
