### PR TITLE
Add commandline option to simulate alert queue expand failure - v4

### PR DESCRIPTION
**Pull request by jufajardini**
Previous PR: #7649 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5319

Describe changes:
- rebased
- possibly fixed author name and email

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8383

**Comment by jufajardini** [comment]
Force pushed sneaky command author info changes

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8410

**Comment by victorjulien** [comment]
Merged in #7670, thanks!

**Pull request closed without merging**
