### PR TITLE
Suricata library v1

### PR DESCRIPTION
**Pull request by amirabell**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Add libsuricata support (includes all the commit since developing this feature)
-
-

suricata-verify-pr: 1166
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
(whoa, big one! :) )

Could you please have a look at the CI Failures?
This doc could help with the Clang one: https://suricata.readthedocs.io/en/latest/devguide/codebase/code-style.html#coding-style
Please note that we prefer that clang formatting changes go in their own PR, if they change already existing code :)

**Comment by amirabell** [comment]
> (whoa, big one! :) )
> 
> Could you please have a look at the CI Failures? This doc could help with the Clang one: https://suricata.readthedocs.io/en/latest/devguide/codebase/code-style.html#coding-style Please note that we prefer that clang formatting changes go in their own PR, if they change already existing code :)

Hey,
I am looking at the CI failures already but it might take a bit since they are quite a lot :)
Regarding the clang formatting: if it goes in a separate PR how will the `formatting-check` pass and allow to merge?
Thanks!

**Comment by amirabell** [comment]
> (whoa, big one! :) )
> 
> Could you please have a look at the CI Failures? This doc could help with the Clang one: https://suricata.readthedocs.io/en/latest/devguide/codebase/code-style.html#coding-style Please note that we prefer that clang formatting changes go in their own PR, if they change already existing code :)

Hey, I am taking a look at the CI failures.
It might take a bit of time since they are quite a lot :)

**Comment by victorjulien** [comment]
Btw I'm not asking for a PR per commit, but per logical change.

**Comment by amirabell** [comment]
> Btw I'm not asking for a PR per commit, but per logical change.

Hey @victorjulien.

Ok I will close this one and start submitting on PR at a time grouping the commit as you said. 
One question before starting: how do you can't to handle the suricata-verify PR? Should we merge it after the last suricata PR has been approved?

**Pull request closed without merging**
