### PR TITLE
stream/tcp: fix typos

### PR DESCRIPTION
**Pull request by ffashion**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Thank you for your first contribution to our project! 😃
The change looks good to me, however, it is important for us that you sign the contribution agreement ;)

**Review by jufajardini — APPROVED** [review]

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hello! Sorry for that, but Clang is complaining about code formatting. We don't merge code with this type of CI failure, so can you do a new PR, fixing this?
Let us know if you need any guidance in running Clang to fix formatting ;)

**Comment by ffashion** [comment]
> Hello! Sorry for that, but Clang is complaining about code formatting. We don't merge code with this type of CI failure, so can you do a new PR, fixing this? Let us know if you need any guidance in running Clang to fix formatting ;)

i dont know to use what tools to fix it, can you tell me what should i do? , thanks.

**Comment by jufajardini** [comment]
> i dont know to use what tools to fix it, can you tell me what should i do? , thanks.

No problems! From within a new local Suricata branch, you can run:
```bash
./scripts/clang-format.sh check-branch
./scripts/clang-format.sh branch
```
The first command will check if current formatting is correct
The second one will automatically apply correct formatting to your branch and add apply changes as a new commit

Then you make sure that the new changes are committed, and can submit a new PR ;)

**Comment by ffashion** [comment]
thank for your teaching. so you will close this pr, and i open a new ?

**Comment by jufajardini** [comment]
> thank for your teaching. so you will close this pr, and i open a new ?

Almost like that ;) 
It is better that when you open the new PR, you close this one with a comment mentioning that you are replacing this with the new one, or that you are continuing the work in the new one (and add a link).

And then you add a version number to the new one, as well, to help us (and you) to keep track of progress. So this first PR should have a title like:
`stream/tcp: fix typos - v1`
And then the next would be:
`stream/tcp: fix typos - v2`

**Comment by ffashion** [comment]
i close this pr, and reopen in https://github.com/OISF/suricata/pull/7398.

**Pull request closed without merging**
