### PR TITLE
Pgsql improve

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None yet, TODO

Describe changes:
- improves pgsql parsing

Draft needed to parse pcap shared privately

@jufajardini can you take on this ?
Create ticket, review and improve the commits

+ PGSQL parser should not error on parsing error, so as to keep on parsing the next PDUs

Let me know what you need

### CODE REVIEW

**Comment by catenacyber** [comment]
+ I would love to have `pgsql.query` as a detection keyword

**Comment by jufajardini** [comment]
> @jufajardini can you take on this ? Create ticket, review and improve the commits
> 

Sure, thanks for the kickstart and report! :)

**Comment by jufajardini** [comment]
Ticket: https://redmine.openinfosecfoundation.org/issues/5524

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw2_single_stats_chk | | |
| .flow.spare | 1950053 | 1835514 | 106.24% |
| | tlpw2_autofp_stats_chk | | |
| .flow.spare | 1909299 | 1812994 | 105.31% |
| .flow.memuse | 518377728 | 550537728 | 94.16% |
| | tlpw1_stats_chk | | |
| .tcp.rst | 125940 | 105279 | 119.62% |
| | tlpr1_stats_chk | | |
| .flow.memuse | 569261888 | 845888448 | 67.3% |
| .http.memuse | 16440 | 49320 | 33.33% |
| | ips_afp_stats_chk | | |
| .flow.end.state.new | 116447 | 10800 | 1078.21% |
| .flow.end.state.closed | 1973425 | 2097352 | 94.09% |
| .flow.end.tcp_state.closed | 1966178 | 2097352 | 93.75% |
| .flow.end.tcp_liberal | 351512 | 108000 | 325.47% |
| .flow.memuse | 872724608 | 1081197888 | 80.72% |
| .tcp.reassembly_gap | 1229802 | 108000 | 1138.71% |
| .app_layer.flow.http | 411601 | 434160 | 94.8% |
| .app_layer.flow.tls | 920493 | 974152 | 94.49% |
| .app_layer.flow.failed_tcp | 205696 | 218160 | 94.29% |
| .app_layer.tx.ftp | 243227 | 263520 | 92.3% |
| .app_layer.tx.smtp | 130073 | 149040 | 87.27% |
| .app_layer.tx.dcerpc_tcp | 954809 | 1101600 | 86.67% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 37669 | 5654519 | 0.67% |
| .flow.end.state.new | 6510 | 14867 | 43.79% |
| .flow.end.tcp_state.syn_sent | 69 | 183 | 37.7% |
| .flow.end.tcp_state.syn_recv | 2 | 52 | 3.85% |
| .flow.end.tcp_state.established | 54181 | 61527 | 88.06% |
| .flow.memuse | 760805568 | 709384128 | 107.25% |
| .tcp.segment_memcap_drop | 0 | 11729 | 0.0% |
| .tcp.reassembly_gap | 84758 | 114099 | 74.28% |
| .tcp.insert_data_normal_fail | 0 | 11358 | 0.0% |
| .app_layer.error.http.parser | 0 | 55 | 0.0% |
| .app_layer.error.smtp.gap | 4 | 61 | 6.56% | 

Pipeline 8817
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

**Comment by catenacyber** [comment]
Closing in favor of future work on https://redmine.openinfosecfoundation.org/issues/5524 by @jufajardini

**Comment by jufajardini** [comment]
> * I would love to have `pgsql.query` as a detection keyword

Finally created a ticket for this: https://redmine.openinfosecfoundation.org/issues/6259

**Pull request closed without merging**
