### PR TITLE
Batch backports to 5.0.x 

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #7116 

Batch backports to 5.0.x

Describe changes:
- [4644](https://redmine.openinfosecfoundation.org/issues/4644)
- [4889](https://redmine.openinfosecfoundation.org/issues/4889)
- [5091](https://redmine.openinfosecfoundation.org/issues/5091)
- [5096](https://redmine.openinfosecfoundation.org/issues/5096)
- [5101](https://redmine.openinfosecfoundation.org/issues/5101)
- [5103](https://redmine.openinfosecfoundation.org/issues/5103)
- [5105](https://redmine.openinfosecfoundation.org/issues/5105)
- [5107](https://redmine.openinfosecfoundation.org/issues/5107)
- [5109](https://redmine.openinfosecfoundation.org/issues/5109)
- [5115](https://redmine.openinfosecfoundation.org/issues/5115)
- [5117](https://redmine.openinfosecfoundation.org/issues/5117)
- [5164](https://redmine.openinfosecfoundation.org/issues/5164)

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on generic_collect.
  

Pipeline 6500

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on tlpw2_single_alerts_cmp.

ERROR: QA failed on tlpw2_autofp_alerts_cmp.

ERROR: QA failed on tlpr1_alerts_cmp.
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk | | |
| .flow.memuse | 593422648 | 725499720 | 81.8% | 

Pipeline 6504

**Review by victorjulien — CHANGES_REQUESTED** [review]
Git history isn't right, needs backports that have proper cherry-pick references.

**Comment by jlucovsky** [comment]
Continued in #7134

**Pull request closed without merging**
