### PR TITLE
Detect generic uint 4112 v5

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4112

Describe changes:
- Makes use of generic `DetectUint` structure for `dsize` and `dcerpc`, `ttl`, `tcpmss`, `filesize` (and template2)

Replaces #7167 with style fixes from code review

Still TODO:
- more keywords in C use specific versions, but they are more complex than just an integer
- look for uses of `set_uint` in loggers to see if we can easily a new keywords
- wait for ET to change rules 2030055 and 2030056
 
```
> git grep _LT src/*.h | grep DETEC
src/detect-ipproto.h:#define DETECT_IPPROTO_OP_LT     '<' /**< "less than" operator */
src/detect-iprep.h:#define DETECT_IPREP_OP_LT        0
src/detect-stream_size.h:#define DETECTSSIZE_LT 0
src/detect-tls-cert-validity.h:#define DETECT_TLS_VALIDITY_LT (1<<1) /* less than */
src/detect-urilen.h:#define DETECT_URILEN_LT   0   /**< "less than" operator */
 ```

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 ERROR: Invalid Signature config error in tlpr1_asan_cfg QA test

ERROR: QA failed on tlpr1_asan_cfg.
  

Pipeline 6636

**Comment by victorjulien** [comment]
CI and QA failure, so set it to draft.

**Comment by catenacyber** [comment]
> CI and QA failure, so set it to draft.

Looks like ET changed rules 2030055 and 2030056, cf https://www.proofpoint.com/us/daily-ruleset-update-summary-20220324
So resetting it to ready for review

**Comment by suricata-qa** [comment]
ERROR:
 ERROR: Invalid Signature config error in tlpr1_asan_cfg QA test

ERROR: QA failed on tlpr1_asan_cfg.
  

Pipeline 6937

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7302

**Pull request closed without merging**
