### PR TITLE
applayer: remove truncation logic

### PR DESCRIPTION
**Pull request by inashivb**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/7044

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1946

Previous PR: https://github.com/OISF/suricata/pull/11151

Changes since v1:
- changed the entire approach

TODO: Remove truncate glue code and parser specific calls

### CODE REVIEW

**Comment by inashivb** [comment]
Hey @catenacyber !
Is this in accordance with your proposal? s-v passed locally but I'm waiting for the QA.
I'm unsure about the changes as there are too many moving parts incl file handling related to these flags and logic. I don't know if this will cause any unknown side effects.
Lmk if you see any obvious mistakes. Thanks a lot!

**Comment by victorjulien** [comment]
Passed my QA. Ran this PR with SV PR https://github.com/OISF/suricata-verify/pull/1946. Local pipeline 4967, run 512.

**Comment by victorjulien** [comment]
possibly related daffcc6e53f7e50ff9cd7b4dbff58e2d4be98ebd

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21330

**Pull request closed without merging**
