### PR TITLE
detect: errors on 65k filestore signatures (backport7)

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6537

Describe changes:
- Clean cherry-pick of #10297

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 120 | 112 | 93.33% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 697 | 650 | 93.26% |
| .http.memuse | 336824 | 416808 | 123.75% | 

Pipeline 18210

**Review by inashivb — APPROVED** [review]
LGTM

**Review by victorjulien — APPROVED** [review]

**Review by victorjulien — CHANGES_REQUESTED** [review]
please ignore, need to have this not get picked up by my staging tool just yet

**Review by victorjulien — APPROVED** [review]
of course I forgot I could just skip a PR, oh well

**Comment by victorjulien** [comment]
Merged in #10357, thanks!

**Pull request closed without merging**
