### PR TITLE
rust/sip: register parser for tcp v11

### PR DESCRIPTION
**Pull request by glongo**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3351

Describe changes:
- Remove `OPTIONS` from pattern matching

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1510
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by catenacyber** [comment]
Let's wait for QA feedback

**Comment by glongo** [comment]
Any updates on this?

**Comment by catenacyber** [comment]
@ct0br0 did QA miss this PR ?

@glongo at one point, this will still need a rebase to solve the conflict about doc/userguide/upgrade.rst

**Comment by ct0br0** [comment]
If a rebase is needed, the run is skipped. Guessing this is a continuation of another PR, so there may have been overlap in the qa-tag and when this was made too. LMK when it's rebased and I'll take a look at the pipeline.

**Comment by glongo** [comment]
New PR: https://github.com/OISF/suricata/pull/10037

**Pull request closed without merging**
