### PR TITLE
smb: fix SMB_COM_WRITE_ANDX record parser - v4

### PR DESCRIPTION
**Pull request by b1tg**
Bug: #6008

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

ticket:
https://redmine.openinfosecfoundation.org/issues/6008

Previous PR: https://github.com/OISF/suricata/pull/8889

Changes from last PR:
- split into two commit and add tests
- update SV

SV_BRANCH=pr/1211

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you look into why some of the SV tests fail?

Also, could you give the git commits unique subjects?

**Comment by b1tg** [comment]
> Can you look into why some of the SV tests fail?

Why [Fedora 37](https://github.com/OISF/suricata/actions/runs/5044768356/jobs/9048246377?pr=8905#logs) show error about filestore-filecontainer-smb1-padding which is not in SV master?

**Comment by victorjulien** [comment]
> > Can you look into why some of the SV tests fail?
> 
> Why [Fedora 37](https://github.com/OISF/suricata/actions/runs/5044768356/jobs/9048246377?pr=8905#logs) show error about filestore-filecontainer-smb1-padding which is not in SV master?

It uses the tests from SV PR 1211, since that is what the PR body specifies.

**Comment by b1tg** [comment]
I just push a new commit in SV, could you re-run the failed tests？
https://github.com/OISF/suricata-verify/pull/1211/commits/f8537ba677e04cdd83c771776f4fc3aaace678cf

**Comment by victorjulien** [comment]
> I just push a new commit in SV, could you re-run the failed tests？ [OISF/suricata-verify@f8537ba](https://github.com/OISF/suricata-verify/commit/f8537ba677e04cdd83c771776f4fc3aaace678cf)

I've restarted all "build" runs.

**Comment by b1tg** [comment]
All tests passed now.

**Review by catenacyber — CHANGES_REQUESTED** [review]
Thanks for these fixes

CI : 🟢 
Code : 🟢 
Commits segmentation : 🟢 
Commit messages : could you give the git commits unique subjects?
I also think you can just write `Bug: #6008` simpler than `Bug: OISF#6008`
Git ID set : 🟢 
CLA : 🟢 already some merged commits
Doc update : 🟢 none needed
Redmine ticket : 🟢 I updated 
Rustfmt : rust is not formatted before this PR
Tests : Are the unit tests duplicating the S-V ones ? I think we prefer S-V
Dependencies added: 🟢 none

**Comment by catenacyber** [comment]
So, almost all green, just the commit messages to reword a bit, and a questions about the testing...

**Comment by b1tg** [comment]
use  https://github.com/OISF/suricata/pull/8938

**Pull request closed without merging**
