### PR TITLE
next/304/70x/20240215/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #10416
 - #10430
 - #10437

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1651

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
All commits seem to be there, seems good.

**Review by jasonish — APPROVED** [review]

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 109 | 115 | 105.5% |
| | SURI_TLPW1_stats_chk | | |
| .uptime | 136 | 141 | 103.68% | 

Pipeline 18544

**Comment by victorjulien** [comment]
QA result of both this and #10437 is a bit high. @ct0br0 can you trigger a rerun?

**Comment by ct0br0** [comment]
Yep. Something else is going then this should go again

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 18551

**Pull request merged**
