### PR TITLE
build: cbindgen (v13)

### PR DESCRIPTION
**Pull request by dbcfd**
Version 13 (from https://github.com/OISF/suricata/pull/4385)

Rust headers are now generated using cbindgen. If cbindgen is present, they can
be generated during dist, otherwise they will be available for builds.

Closes https://redmine.openinfosecfoundation.org/issues/3308

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Rust headers are now created by cbindgen
- Cbindgen is run as a step under dist when cbindgen is available and a high enough version

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by jasonish** [comment]
Some fixups for github actions here:
https://github.com/OISF/suricata/pull/4448

**Comment by victorjulien** [comment]
@dbcfd could you explain some things a bit more in the commit message. Thinking mostly about some of the settings in the `cbindgen.yaml`: include, exclude and export.rename.

**Comment by jasonish** [comment]
> @dbcfd could you explain some things a bit more in the commit message. Thinking mostly about some of the settings in the `cbindgen.yaml`: include, exclude and export.rename.

I think it might make more sense to add this detail to the cbindgen.yaml itself, so its right there when this file needs to be updated without having to look at the commit.

**Comment by victorjulien** [comment]
> > @dbcfd could you explain some things a bit more in the commit message. Thinking mostly about some of the settings in the `cbindgen.yaml`: include, exclude and export.rename.
> 
> I think it might make more sense to add this detail to the cbindgen.yaml itself, so its right there when this file needs to be updated without having to look at the commit.

In both then. I use git commit messages a lot when trying to understand things.

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/4496.

**Pull request closed without merging**
