### PR TITLE
Dev/nom5 v1

### PR DESCRIPTION
**Pull request by chifflier**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
not applicable

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3128

Describe changes:
- This PR upgrades all parsers to use nom 5. This is mostly a basic conversion (also to minimize code changes), so there are still macros, but at least it is now possible to use nom 5 features. Conversions from macros to functions can be done more selectively in further PRs [*]
- Some subparsers (DER, Kerberos, SNMP) have also been upgraded to latest versions, and may provide new features
- Unit tests all pass [**], and performance tests here are showing similar performances. However, more tests would be nice

[*] Note that this also showed that the macro to functions conversion is not so easy. For example, it tends to confuse type inference in the Rust compiler, and sometimes require manual type annotations.
[**] Feedback: the rust unit tests present in the code (`cargo test`) have been especially useful to diagnose regressions. We need more of them!

### CODE REVIEW

**Comment by victorjulien** [comment]
I get a QA error in NFS/RPC handling. For 5.0.x I created this test:
```rust
#[cfg(test)]
mod tests {
    use crate::nfs::rpc_records::*;
    use nom::Err::Incomplete;
    use nom::Needed::Size;

    #[test]
    fn test_parse_input_too_short() {
        let buf: &[u8] = &[
            0x80, 0x0, 0x0, 0x9c, 0x8e, 0x28, 0x2, 0x7e
        ];
        let r = parse_rpc_request_partial(buf);
        match r {
            Err(Incomplete(e)) => { assert_eq!(e, Size(4)); },
             _ => { panic!("failed {:?}",r); }
       }
    }
}
```
As you can see, the data is too short for the parser so it returns Err::Incomplete as expected.

However for the git master (6.0.x), the parser returns Eof. This is a passing test:
```rust
#[cfg(test)]
mod tests {
    use crate::nfs::rpc_records::*;
    use nom::Err::Error;
    use nom::error::ErrorKind::Eof;

    #[test]
    fn test_parse_input_too_short() {
        let buf: &[u8] = &[
            0x80, 0x0, 0x0, 0x9c, 0x8e, 0x28, 0x2, 0x7e
        ];

        let r = parse_rpc_request_partial(buf);
        match r {
            Err(Error((rem, ek))) => {
                    assert_eq!(rem.len(),0);
                    assert_eq!(ek, Eof);
                },
            _ => { panic!("failed {:?}",r); }
        }
    }
}
```

So it doesn NOT return `Incomplete` as I would have expected. Any idea why?

**Comment by chifflier** [comment]
@victorjulien Good catch! The fix is to use the streaming API and not the complete one:
```diff
-use nom::number::complete::be_u32;
+use nom::number::streaming::be_u32;
```

This thing is, I'm not sure this can be generalized to all calls (for ex, subparsers called in `many`, `fold` and `while`-like combinators should be complete or the whole parsing will fail.

I'm committing the above fix, but also have to check if the streaming/complete error happens in other places.

**Comment by chifflier** [comment]
I pushed ad4a017 to use the streaming version where possible, to get the expected behavior. Tests are OK here (as well as `suricata-verify`)

**Comment by chifflier** [comment]
The changes implemented in ad4a017 fixes all known locations of possible incomplete calls.
@victorjulien , what do you think of this fix? Can you run more tests?

**Comment by victorjulien** [comment]
> The changes implemented in [ad4a017](https://github.com/OISF/suricata/commit/ad4a017abf8aed23bf49f4e6d11a1cc0c8acfa13) fixes all known locations of possible incomplete calls.
> @victorjulien , what do you think of this fix? Can you run more tests?

I had to undo this for `smb1_records.rs`, then all my tests pass. It does make me wonder if we need to do this on a per case basis. I supposed one way to check would be to see if parsers have special handling for getting `err::Incomplete`?

**Comment by chifflier** [comment]
> I had to undo this for `smb1_records.rs`, then all my tests pass. It does make me wonder if we need to do this on a per case basis. I supposed one way to check would be to see if parsers have special handling for getting `err::Incomplete`?

Hmm, I am curious why `smb1_records.rs` broke (I found no calls to `many`).

For the record, this last patch is, imho, the correct way to handle incomplete reads in a streaming parser. That said, nom 5 now allows *each parser* to choose its behavior (error on incomplete, or raise incomplete). If the upper layer does not differentiate `Ok` from other results (which is usually the case, for ex in `rust/src/dhcp/parser.rs`) , it all goes to error handling.
I think the streaming version should be preferred because it gives a chance of waiting for more data (for ex when handling fragmentation) and does not change parsers that do not handle incomplete reads.

The only case where the streaming versions should not be used are inside `many` combinators: unless you specify exactly the number of items to read, the next read after the last one will always return incomplete for this combinator.

So I believe the standard method of choosing combinators should be something like:
- always prefer the streaming version
- unless inside a `many` or `fold` combinator, in that case either add `complete` of use the complete combinators (the former being maybe a better choice, since it is transitive - think of parsers calling subparsers).

So my suggestion would be to use the streaming version everywhere unless explicitly required/justified.

**Comment by victorjulien** [comment]
> > I had to undo this for `smb1_records.rs`, then all my tests pass. It does make me wonder if we need to do this on a per case basis. I supposed one way to check would be to see if parsers have special handling for getting `err::Incomplete`?
> 
> Hmm, I am curious why `smb1_records.rs` broke (I found no calls to `many`).

Yeah, I don't know. I didn't investigate deeply. A test that tests many many records reported to be off, and with this change it passed again.

> For the record, this last patch is, imho, the correct way to handle incomplete reads in a streaming parser. That said, nom 5 now allows _each parser_ to choose its behavior (error on incomplete, or raise incomplete). If the upper layer does not differentiate `Ok` from other results (which is usually the case, for ex in `rust/src/dhcp/parser.rs`) , it all goes to error handling.
> I think the streaming version should be preferred because it gives a chance of waiting for more data (for ex when handling fragmentation) and does not change parsers that do not handle incomplete reads.
> 
> The only case where the streaming versions should not be used are inside `many` combinators: unless you specify exactly the number of items to read, the next read after the last one will always return incomplete for this combinator.
> 
> So I believe the standard method of choosing combinators should be something like:
> 
> * always prefer the streaming version
> * unless inside a `many` or `fold` combinator, in that case either add `complete` of use the complete combinators (the former being maybe a better choice, since it is transitive - think of parsers calling subparsers).
> 
> So my suggestion would be to use the streaming version everywhere unless explicitly required/justified.

I'm not really happy with this. I wonder if it would be better to just explicitly call the parsers in their full form directly, so its clear how they behave. It's quite inconvenient that some very important distinction in the behavior of the system requires you to know it is included in the top of the file.

**Comment by victorjulien** [comment]
Perhaps we can do something like this:
```diff
diff --git a/rust/src/smb/smb1_records.rs b/rust/src/smb/smb1_records.rs
index 148631fbf..a26685711 100644
--- a/rust/src/smb/smb1_records.rs
+++ b/rust/src/smb/smb1_records.rs
@@ -19,6 +19,7 @@ use crate::smb::error::SmbError;
 use crate::log::*;
 use nom::IResult;
 use nom::combinator::rest;
+use nom::number::complete::le_u8 as le_u8c;
 use nom::number::complete::{le_u8, le_u16, le_u32, le_u64};
 use crate::smb::smb::*;
 use crate::smb::smb_records::*;
@@ -51,7 +52,7 @@ pub struct Smb1WriteRequestRecord<'a> {
 
 named!(pub parse_smb1_write_request_record<Smb1WriteRequestRecord>,
     do_parse!(
-            _wct: le_u8
+            _wct: le_u8c
         >>  fid: take!(2)
         >>  _count: le_u16
         >>  offset: le_u32
```

**Comment by chifflier** [comment]
> Perhaps we can do something like this:
> 
> ```diff
> diff --git a/rust/src/smb/smb1_records.rs b/rust/src/smb/smb1_records.rs
> +use nom::number::complete::le_u8 as le_u8c;
>  use nom::number::complete::{le_u8, le_u16, le_u32, le_u64};
> ```

Sure, this is one of the nice things in nom 5: each parser combinator can choose if calling complete subparsers or not.

**Comment by chifflier** [comment]
[...]
> I'm not really happy with this. I wonder if it would be better to just explicitly call the parsers in their full form directly, so its clear how they behave. It's quite inconvenient that some very important distinction in the behavior of the system requires you to know it is included in the top of the file.

Well, this is one possibility. What I would find important is to have a common convention (for ex: default to complete parsers, justify/document exceptions) for code consistency and easier reviews.

I'm fine with both kind of parsers, so I'll leave the choice to the team. In both cases, tests will be very important to ensure no regression happened.

Note: according to https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_5.md all macros default to _streaming_ version. This means that in some cases we may need to transition to functions to really get the _complete_ version.

**Comment by victorjulien** [comment]
I may have somehow messed up my testing, because the tests now also pass w/o that smb1 change.

**Comment by victorjulien** [comment]
Merged through #4624 (#4626), thanks a lot Pierre!

**Pull request closed without merging**
