### PR TITLE
New app layer event for invalid http request line

### PR DESCRIPTION
**Pull request by catenacyber**
Link to redmine ticket:
https://redmine.openinfosecfoundation.org/issues/2655

Describe changes:
- New app layer event for invalid http request line (using flags rather than log string comparison)
- New app layer event for unexpected request body

Modifies https://github.com/OISF/suricata/pull/3910 : rebased

See https://github.com/OISF/suricata-verify/pull/24 and https://github.com/OISF/libhtp/pull/211

### CODE REVIEW

**Comment by victorjulien** [comment]
When I test this with https://github.com/OISF/libhtp/pull/211 I get:
```
Test HTPParserTest17                                              : expected method M_GET and got (null): , expected protocol HTTP/1.1 and got (null) 
FAILED
ERROR: unittest failed.
```

**Comment by catenacyber** [comment]
Thanks Victor
libhtp PR has been updated to https://github.com/OISF/libhtp/pull/231

CI failure seems to be a network problem while running curl (not related to this PR)
https://travis-ci.org/OISF/suricata/jobs/540692476#L136

**Comment by victorjulien** [comment]
Can you rebase this and resubmit?

**Comment by catenacyber** [comment]
Looks like this got cherry-picked already : https://github.com/OISF/suricata/commit/b5f3e03209922f1029b76a1a3570a3aca91659f5

**Pull request closed without merging**
