### PR TITLE
Pcap conditional v2.2.5

### PR DESCRIPTION
**Pull request by regit**
Rebase of #6048 

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- fix formatting

suricata-verify-pr: 471

### CODE REVIEW

**Comment by regit** [comment]
So clang-format-11 and clang-format-9 are not producing the same result...

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | generic_stats_chk |
| .tcp.reassembly_memuse | 2293760 | 1966080 | 86.0% |

**Comment by cifer76** [comment]
I traced from the initial first [PR](https://github.com/OISF/suricata/pull/5128) proposed by @scottfgjordan last year till this latest one, what an excellent job you have been working!

Just curious, is this PR the final solution for https://redmine.openinfosecfoundation.org/issues/120? I'm also interested in this topic :P

**Comment by suricata-qa** [comment]
ERROR: ASAN TEST FAIL in tlpr1_asan_suri QA test

Pipeline 3469

**Comment by victorjulien** [comment]
Replaced by #6389

**Pull request closed without merging**
