### PR TITLE
dcerpc: maximum number of live transactions also for UDP

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6156

Describe changes:
- Cherry pick of d40dca5e55286c57e9a83018975022c4f08bf6d1

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 577437888 | 1013773888 | 175.56% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 12499 | 0.00 | 

Pipeline 14731

**Comment by catenacyber** [comment]
@jasonish what should we do about MSRV not having `range_mut` for VecDeque ?

**Comment by jasonish** [comment]
> @jasonish what should we do about MSRV not having `range_mut` for VecDeque ?

Looks like we'll use 1.63 at least as the MSRV for 7. What version is required for `range_mut`?

**Comment by catenacyber** [comment]
> Looks like we'll use 1.63 at least as the MSRV for 7. What version is required for `range_mut`?

This is for master6...

**Comment by jasonish** [comment]
> > Looks like we'll use 1.63 at least as the MSRV for 7. What version is required for `range_mut`?
> 
> 
> 
> This is for master6...

Ah. Will have to look for an alternate fix then.

**Pull request closed without merging**
