### PR TITLE
next/129/20230905/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #9397
 - #9434
 - #9439

SV_BRANCH=pr/1375

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15837

**Comment by catenacyber** [comment]
Could next next branch have https://github.com/OISF/suricata/pull/9298/commits/31c61f9eeb71f9b0ba2cb3139c31f93f80d3c37a ?

**Comment by victorjulien** [comment]
> Could next next branch have [31c61f9](https://github.com/OISF/suricata/commit/31c61f9eeb71f9b0ba2cb3139c31f93f80d3c37a) ?

What PR is that?

**Comment by catenacyber** [comment]
> > Could next next branch have [31c61f9](https://github.com/OISF/suricata/commit/31c61f9eeb71f9b0ba2cb3139c31f93f80d3c37a) ?
> 
> What PR is that?

The PR is https://github.com/OISF/suricata/pull/9298 but this single commit is unrelated and just a CI cleanup ;-)

**Pull request merged**
