### PR TITLE
detect/sip: add sticky buffers to match headers

### PR DESCRIPTION
**Pull request by glongo**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6374

Describe changes:
This patchset introduces several sticky buffers to match the following SIP headers:

- From
- To
- Via
- User-Agent
- Content-Type
- Content-Length

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1764

### CODE REVIEW

**Comment by jlucovsky** [comment]
I'm looking at RFC3261 and some of the keywords being added like:
- `Content-Type`
- `Content-Length`
also have "compact forms (`l` and `c` respectively).

I don't know how prevalent the compact form usage is; should your additions handle both forms of the headers iff the header has a compact form?

**Comment by glongo** [comment]
> I'm looking at RFC3261 and some of the keywords being added like:
> 
>     * `Content-Type`
> 
>     * `Content-Length`
>       also have "compact forms (`l` and `c` respectively).
> 
> 
> I don't know how prevalent the compact form usage is; should your additions handle both forms of the headers iff the header has a compact form?

Definitely, those compact form  must be handled.

**Comment by catenacyber** [comment]
Why not a generic `sip.request_header` keyword ? whose buffer would be name+value like `http.request_header` (and same for response)

**Comment by glongo** [comment]
> Why not a generic `sip.request_header` keyword ? whose buffer would be name+value like `http.request_header` (and same for response)

I'm not sure I like that to be honest. 
@victorjulien, thoughts?

**Comment by catenacyber** [comment]
> > Why not a generic `sip.request_header` keyword ? whose buffer would be name+value like `http.request_header` (and same for response)
> 
> I'm not sure I like that to be honest. @victorjulien, thoughts?

Why do not you like it ?
It would allow more signatures expressivity (not restricted to the headers added here), with less lines of code...

**Comment by victorjulien** [comment]
> > > Why not a generic `sip.request_header` keyword ? whose buffer would be name+value like `http.request_header` (and same for response)
> > 
> > 
> > I'm not sure I like that to be honest. @victorjulien, thoughts?
> 
> Why do not you like it ? It would allow more signatures expressivity (not restricted to the headers added here), with less lines of code...

It's an important keyword for http. In general, the other http keywords like http.header_names, http.start, etc should probably all be recreated here. Rule writers love them :)

**Comment by glongo** [comment]
> It's an important keyword for http. In general, the other http keywords like http.header_names, http.start, etc should probably all be recreated here. Rule writers love them :)

So, could I add a keyword as @catenacyber suggested in another PR, and leave this one as is once the compact form issue is resolved?

**Comment by victorjulien** [comment]
> > It's an important keyword for http. In general, the other http keywords like http.header_names, http.start, etc should probably all be recreated here. Rule writers love them :)
> 
> So, could I add a keyword as @catenacyber suggested in another PR, and leave this one as is once the compact form issue is resolved?

I'm ok with doing them in follow up PRs. Btw I suggest a more comprehensive list :)

**Comment by glongo** [comment]
> > > It's an important keyword for http. In general, the other http keywords like http.header_names, http.start, etc should probably all be recreated here. Rule writers love them :)
> > 
> > 
> > So, could I add a keyword as @catenacyber suggested in another PR, and leave this one as is once the compact form issue is resolved?
> 
> I'm ok with doing them in follow up PRs. Btw I suggest a more comprehensive list :)

Sure, it's just a starting point :)

**Comment by glongo** [comment]
Replaced with https://github.com/OISF/suricata/pull/10907

**Pull request closed without merging**
