### PR TITLE
Pr/9365+s v debug log/v1

### PR DESCRIPTION
**Pull request by inashivb**
- #9365

\+ 248fac00777ddbe748e7a096b50723412aa49bc9

SV_BRANCH=pr/1349

### CODE REVIEW

**Comment by jasonish** [comment]
I think there was a time when `--debug-failed` failed itself in CI, appears to be working now, at least on MacOS.  I believe it was some sort of P ython 2/3 difference with respect to unicode.

**Comment by inashivb** [comment]
> I think there was a time when `--debug-failed` failed itself in CI, appears to be working now, at least on MacOS. I believe it was some sort of P ython 2/3 difference with respect to unicode.

yeah. I fixed that a few days ago when I really needed it: https://github.com/OISF/suricata-verify/pull/1332/commits/f3d53da77bcfa82793f46989d389fdedb8780ac5

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15553

**Comment by jufajardini** [comment]
Being able to have more insight into the SV failure/error is awesome :D

Noticed that a part of the string seems to be cut here, https://github.com/OISF/suricata/actions/runs/5809471949/job/15753777071#step:12:7975 trying to figure out if that's happening when the message is logged out, or what 🤔

**Comment by jufajardini** [comment]
> Being able to have more insight into the SV failure/error is awesome :D
> 
> Noticed that a part of the string seems to be cut here, https://github.com/OISF/suricata/actions/runs/5809471949/job/15753777071#step:12:7975 trying to figure out if that's happening when the message is logged out, or what thinking

Is it expected, or even controllable by us, that the debug output will vary between OSs? https://github.com/OISF/suricata/actions/runs/5809471949/job/15753773978#step:16:91

**Comment by jasonish** [comment]
> > Being able to have more insight into the SV failure/error is awesome :D
> > Noticed that a part of the string seems to be cut here, https://github.com/OISF/suricata/actions/runs/5809471949/job/15753777071#step:12:7975 trying to figure out if that's happening when the message is logged out, or what thinking
> 
> Is it expected, or even controllable by us, that the debug output will vary between OSs? https://github.com/OISF/suricata/actions/runs/5809471949/job/15753773978#step:16:91

Differences are expected, within reason. File paths will be different.  Even different versions of Python could have minor effects on the output.

**Comment by victorjulien** [comment]
#9368

**Pull request closed without merging**
