### PR TITLE
Multipart mime 3487 v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser

This is a draft to run CI, share work and get feedback  :-)

### CODE REVIEW

**Comment by jasonish** [comment]
Maybe just use `mime.rs` in `src/` until the mime module needs multiple files?

**Comment by catenacyber** [comment]
> Maybe just use `mime.rs` in `src/` until the mime module needs multiple files?

The file is already there, so I did not move it ;-)

**Comment by jasonish** [comment]
> > Maybe just use `mime.rs` in `src/` until the mime module needs multiple files?
> 
> The file is already there, so I did not move it ;-)

So it is.. Oops.

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on tlpw1_files_sha256.
  

Pipeline 8485

**Comment by catenacyber** [comment]
I have no idea why CIFuzz is failing, especially this way...
Still more work to do before having more than a draft anyways

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7812

**Pull request closed without merging**
