### PR TITLE
exceptions: fix 'auto' for master switch in IDS  - v1

### PR DESCRIPTION
**Pull request by jufajardini**
If the master exception policy was set to 'auto' in IDS mode, instead of just setting the master switch to the default in this case, which is 'ignore', the engine would switch a warning saying that auto wasn't a valid config and then set the policy to ignore.

This makes 'auto' work for the master switch in IDS, removes function for setting IPS option and handles the valid IDS options directly from the function that parses the master policy, as this was the only place where the function was still called.

Bug #6149

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6149

Describe changes:
- fix handling of 'auto' setting for the exception policy master switch, in IDS mode
- change Log level and message for when master switch is parsed and configured
- remove function that was only being used for parsing the master switch

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the pull request number.

```
SV_BRANCH=pr/1251
```
https://github.com/OISF/suricata-verify/pull/1251

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.tx.ftp | 646 | 819 | 126.78% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 519171056 | 846740640 | 163.09% | 

Pipeline 14672

**Comment by jufajardini** [comment]
Figuring out what are the SV failures about.

**Comment by victorjulien** [comment]
> Figuring out what are the SV failures about.

I think SV PR needs rebase.

**Comment by victorjulien** [comment]
> > > Figuring out what are the SV failures about.
> > 
> > 
> > I think SV PR needs rebase.
> 
> T_T it does

Did you do that? Rebase, force push the SV branch, then we can restart CI

**Comment by victorjulien** [comment]
Merged as part of #9035, thanks.

**Comment by jufajardini** [comment]
> > > > Figuring out what are the SV failures about.
> > > 
> > > 
> > > I think SV PR needs rebase.
> > 
> > 
> > T_T it does
> 
> Did you do that? Rebase, force push the SV branch, then we can restart CI

Did now >__<'

**Pull request closed without merging**
