### PR TITLE
[draft] plugins: ndpi stub plugin - v1

### PR DESCRIPTION
**Pull request by jasonish**
Example/stub plugin for nDPI. Utilizes new features from PR https://github.com/OISF/suricata/pull/11969.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23118

**Comment by jasonish** [comment]
Updated with example of rule keyword registrations.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23134

**Comment by jasonish** [comment]
Actual plugin now. https://github.com/OISF/suricata/pull/12092

**Pull request closed without merging**
