### PR TITLE
Privdrop without libcap ng

### PR DESCRIPTION
**Pull request by eroullit**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2931

Describe changes:
- Allow suricata to drop privileges on platform without libcap-ng support
- Prevent suricata to start in `RUNMODE_AFP_DEV` with dropped privileges without libcap-ng support
- Enable `--user` and `--group` CLI parameters to be used without libcap-ng support

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable): N/A

### CODE REVIEW

**Comment by eroullit** [comment]
Once the tests have passed, this branch will be rebased.

**Comment by victorjulien** [comment]
I think configure.ac checks for setresuid, setresgid should be added, so it can be checked in the code w/o assumptions per OS or other factors.

**Comment by eroullit** [comment]
I am going to close this pull request and prepare a v2 for review.

**Comment by eroullit** [comment]
Superseeded by v2: https://github.com/OISF/suricata/pull/3800

**Pull request closed without merging**
