### PR TITLE
mqtt: fix consumed bytes computation for truncated msg

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5268

Describe changes:
- mqtt : fixes consumed bytes computation in truncated case

cc @satta following https://github.com/OISF/suricata/pull/7231 by adding a ticket and handling request the same way

### CODE REVIEW

**Comment by catenacyber** [comment]
CI failure seems unrelated to this PR...

**Comment by satta** [comment]
Yes, looks good. Thanks for taking care of it.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 6929

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #7253, thanks

**Pull request closed without merging**
