### PR TITLE
next/310/20240220/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #10273
 - #10443
 - #10444
 - #10454

### CODE REVIEW

**Review by jasonish — APPROVED** [review]

**Review by lukashino — COMMENTED** [review]
Should the PR contain `examples/plugins/c-json-filetype/Makefile.in` and not the `.am`?

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 101 | 111 | 109.9% | 

Pipeline 18643

**Comment by victorjulien** [comment]
> Should the PR contain `examples/plugins/c-json-filetype/Makefile.in` and not the `.am`?

Are you looking for more clarification of the explanation in https://github.com/OISF/suricata/pull/10443/commits/d3573a04225b4d35b3a2a59d9c5f2ec8c6673e32 ?

**Comment by jasonish** [comment]
> Should the PR contain `examples/plugins/c-json-filetype/Makefile.in` and not the `.am`?

In short, we want autoconf to give us the substitions that `./configure` provides, but we don't want automake here.

It might be that we have to hand code some stuff for different operating systems, etc. But that does serve a purpose of how to use the library in various places in a more or less build system agnostic way.

**Review by lukashino — APPROVED** [review]
yes, thank you both

**Pull request merged**
