### PR TITLE
Fix midstream exception policy bug 5825 - v5

### PR DESCRIPTION
**Pull request by jufajardini**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5825

Previous PR: https://github.com/OISF/suricata/pull/8969

Describe changes:
- Rebase
- Check for `NULL` before incrementing stats in the right place

SV_BRANCH=pr/1230
SV PR: https://github.com/OISF/suricata-verify/pull/1230

### CODE REVIEW

**Comment by jufajardini** [comment]
Still trying to figure out the fuzz failures. The error says that... `no suricata.yaml file was found`. Can't yet understand why the previous PR passed and this is failing...🤔

**Comment by jufajardini** [comment]
> Still trying to figure out the fuzz failures. The error says that... `no suricata.yaml file was found`. Can't yet understand why the previous PR passed and this is failing...thinking

This - https://github.com/OISF/suricata/actions/runs/5214960621/jobs/9415833809#step:4:11120
still not sure...

**Comment by victorjulien** [comment]
Output is weird, for example with default config and `--simulate-ips`:
```
Info: suricata: Setting IPS mode [ParseCommandLine:suricata.c:1526]
Notice: suricata: This is Suricata version 7.0.0-rc2-dev (524e26384e 2023-06-09) running in USER mode [LogVersion:suricata.c:1158]
Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
Warning: exception-policy: flow actions not supported for flow.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
Notice: threads: Threads created -> RX: 1 W: 16 FM: 1 FR: 1   Engine started. [TmThreadWaitOnThreadRunning:tm-threads.c:1886]
```

**Comment by victorjulien** [comment]
CIFuzz is failing due to the extra output:
```
./src/suricata --list-app-layer
Error: conf-yaml-loader: failed to open file: /etc/suricata//suricata.yaml: No such file or directory [ConfYamlLoadFile:conf-yaml-loader.c:489]
Warning: exception-policy: app-layer.error-policy: ignore (defined via 'built-in default' for IDS-mode) [ExceptionPolicyGetDefault:util-exception-policy.c:228]
=========Supported App Layer Protocols=========
http
ftp
```

**Comment by victorjulien** [comment]
Actually the output is
```
Info: suricata: Setting IPS mode [ParseCommandLine:suricata.c:1526]
Notice: suricata: This is Suricata version 7.0.0-rc2-dev (524e26384e 2023-06-09) running in USER mode [LogVersion:suricata.c:1158]
Warning: exception-policy: exception-policy set to: drop-flow [ExceptionPolicyMasterParse:util-exception-policy.c:207]
Warning: exception-policy: app-layer.error-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
Warning: exception-policy: defrag.memcap-policy: drop-packet (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
Warning: exception-policy: flow actions not supported for flow.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
Warning: exception-policy: flow.memcap-policy: drop-packet (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
Warning: exception-policy: stream.memcap-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
Warning: exception-policy: stream.reassembly.memcap-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
Warning: exception-policy: midstream-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
Notice: threads: Threads created -> RX: 1 W: 16 FM: 1 FR: 1   Engine started. [TmThreadWaitOnThreadRunning:tm-threads.c:1886]
```
These warnings are excessive.

**Comment by jufajardini** [comment]
> Actually the output is
> 
> ```
> Info: suricata: Setting IPS mode [ParseCommandLine:suricata.c:1526]
> Notice: suricata: This is Suricata version 7.0.0-rc2-dev (524e26384e 2023-06-09) running in USER mode [LogVersion:suricata.c:1158]
> Warning: exception-policy: exception-policy set to: drop-flow [ExceptionPolicyMasterParse:util-exception-policy.c:207]
> Warning: exception-policy: app-layer.error-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
> Warning: exception-policy: defrag.memcap-policy: drop-packet (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: flow actions not supported for flow.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
> Warning: exception-policy: flow.memcap-policy: drop-packet (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: stream.memcap-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: stream.reassembly.memcap-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: midstream-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Notice: threads: Threads created -> RX: 1 W: 16 FM: 1 FR: 1   Engine started. [TmThreadWaitOnThreadRunning:tm-threads.c:1886]
> ```
> 
> These warnings are excessive.



> CIFuzz is failing due to the extra output:
> 
> ```
> ./src/suricata --list-app-layer
> Error: conf-yaml-loader: failed to open file: /etc/suricata//suricata.yaml: No such file or directory [ConfYamlLoadFile:conf-yaml-loader.c:489]
> Warning: exception-policy: app-layer.error-policy: ignore (defined via 'built-in default' for IDS-mode) [ExceptionPolicyGetDefault:util-exception-policy.c:228]
> =========Supported App Layer Protocols=========
> http
> ftp
> ```

Oh, I had no idea this would cause a CIFuzz failure '-'

**Comment by jufajardini** [comment]
> Actually the output is
> 
> ```
> Info: suricata: Setting IPS mode [ParseCommandLine:suricata.c:1526]
> Notice: suricata: This is Suricata version 7.0.0-rc2-dev (524e26384e 2023-06-09) running in USER mode [LogVersion:suricata.c:1158]
> Warning: exception-policy: exception-policy set to: drop-flow [ExceptionPolicyMasterParse:util-exception-policy.c:207]
> Warning: exception-policy: app-layer.error-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
> Warning: exception-policy: defrag.memcap-policy: drop-packet (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: flow actions not supported for flow.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
> Warning: exception-policy: flow.memcap-policy: drop-packet (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: stream.memcap-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: stream.reassembly.memcap-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Warning: exception-policy: midstream-policy: drop-flow (defined via 'exception-policy' master switch) [ExceptionPolicyGetDefault:util-exception-policy.c:222]
> Notice: threads: Threads created -> RX: 1 W: 16 FM: 1 FR: 1   Engine started. [TmThreadWaitOnThreadRunning:tm-threads.c:1886]
> ```
> 
> These warnings are excessive.

I think we were not seeing these before due to the other log macro possibly not working as expected, as these are cases where Suri would issue log messages...

**Comment by jufajardini** [comment]
> 

Verdict: remove all highlighted output - change to `SCLogNotice`.

**Comment by jufajardini** [comment]
> Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]

```bash
Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
```
Changing those warnings to `Notice`. But I think this one above is especially bad. Because this is the result of defining the `defrag.memcap-policy` with our default, which shouldn't lead to a warning.

**Comment by jufajardini** [comment]
> > > Warning: exception-policy: flow actions not supported for defrag.memcap-policy, defaulting to "drop-packet" [PickPacketAction:util-exception-policy.c:132]
> > 
> > 
> > Changing those warnings to `Notice`. But I think this one above is especially bad. Because this is the result of defining the `defrag.memcap-policy` with our default, which shouldn't lead to a warning.
> 
> Notice is likely still too verbose.

ok! Saw this a bit too late, but will change it to `Info`, then.

**Comment by jufajardini** [comment]
Output changed in https://github.com/OISF/suricata/pull/9011

**Pull request closed without merging**
