### PR TITLE
Include less v17

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/945

Describe changes:
- Remove unused includes in c files
- adds some options in CI : hyperscan, luajit

Follows #8167 with removing comment that would go stale

Still TODO after that : run script mininc.py

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103845 | 80.98% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 604828608 | 107.02% | 

Pipeline 10659

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Taking this with additional fixes in #8185. The CI check is too fragile for me for now, so leaving that out. Fixing the build in profiling triggers the check. Perhaps for now we'll just occasionally  run the script instead of making it part of CI.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8186

**Comment by victorjulien** [comment]
Merged in #8187, thanks!

**Pull request closed without merging**
