### PR TITLE
doc: update sphinx api to use add_css_file

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- update sphinx api to use `add_css_file` instead of `add_stylesheet`

cf https://github.com/sphinx-doc/sphinx/issues/7747

### CODE REVIEW

**Comment by catenacyber** [comment]
Looks like CI is using old sphinxes...
How do we do python code compatible with both old and newest version ?

**Comment by jasonish** [comment]
> How do we do python code compatible with both old and newest version ?

I think we need to settle on whatever Python we have available to us in the distrubtion we choose to build the release tarballs.  As this will require running Sphinx to generate the man pages we need to ship in the release tarballs.

**Comment by catenacyber** [comment]
Is there a way _not_ to build the docs ?

Replaced by https://github.com/OISF/suricata/pull/6127

**Comment by jasonish** [comment]
> Is there a way _not_ to build the docs ?

Not if you have Sphinx installed.  So I guess `--without-docs` might be a good idea (or should that be a `--disable-docs`).

**Pull request closed without merging**
