### PR TITLE
Updated queue.h to fix build errors using clang10 on FreeBSD13.0-CURRENT

### PR DESCRIPTION
**Pull request by jbarfield**
Updated "queue.h" headers to fix build errors using clang10 on FreeBSD13-CURRENT.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [NA] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: NA

Describe changes:

Updated Suricata included "queue.h" headers to resolve build errors on FreeBSD12.1-STABLE & 13-CURRENT & HardenedBSD-12.1-STABLE. 

The original included "queue.h" from 6.0.0-beta1 had numerous errors regarding types, identifiers, and pointers making it impossible to build from source on the aforementioned OS platform. We initially updated "app-layer-expectation.c functions directly" but it was discovered by OISF that there were new build errors since implemented in a function named ctime. After further research into the issue it was determined that "queue.h" was the culprit of build issues across the app-layers and hence the need for an updated "queue.h" attached to this pull request. 

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

I am having problems getting the pr script to run on FreeBSD12 and can't find much documentation about it. I've run it with both python 2.7 and python 3.7 with mixed results but it never runs. It either complains about docker or complains that a remote push has not happened with the branch. Very strange behaviors have been observed. I am assuming that this is meant for linux/docker. 

I hope that I have properly submitted this pull request this time. 

Have a great day!

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
Thanks John, can you provide details about what errors you get and using what commandline? I am able to build suricata on 12.1 with clang 10 w/o any warning or error.

**Comment by jbarfield** [comment]
It may actually be okay on 12.1 ill have to attempt the build to see if that release is affected. For some reason I thought that I recalled 6.0.0-beta1 wouldnt build on either. Will double check and post errors. I know for a fact that it would not build on freebsd13. Do you want those errors as well?

**Comment by victorjulien** [comment]
Yeah can you share the details of the build and the errors?

**Comment by jbarfield** [comment]
From FreeBSD13 suricata-6.0.0-beta1

_--prefix=/opt/local --enable-old-barnyard2=no --enable-debug=yes --enable-ipfw=yes --enable-unix-socket=yes --enable-prelude=no --enable-pfring=no --enable-af-packet=no --enable-netmap --enable-dag=no  --disable-nspr --disable-nss --enable-libmagic --enable-napatech=no --enable-hiredis=no --enable-rust-strict=no --enable-python --with-libhs-includes=/opt/local/include/hs --with-libhs-libraries=/opt/local/lib  --enable-suricata-update --enable-luajit --enable-geoip --disable-silent-rules --enable-gccmarch-native=no_


>Making all in src
--- all ---
make  all-am
--- main.o ---
--- alert-debuglog.o ---
--- alert-fastlog.o ---
--- alert-prelude.o ---
--- alert-syslog.o ---
--- app-layer.o ---
--- app-layer-dcerpc.o ---
--- app-layer-dcerpc-udp.o ---
--- app-layer-detect-proto.o ---
--- app-layer-dnp3.o ---
--- app-layer-dnp3-objects.o ---
--- main.o ---
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c && mv -f $depbase.Tpo $depbase.Po
--- alert-debuglog.o ---
depbase=`echo alert-debuglog.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT alert-debuglog.o -MD -MP -MF $depbase.Tpo -c -o alert-debuglog.o alert-debuglog.c && mv -f $depbase.Tpo $depbase.Po
--- alert-fastlog.o ---
depbase=`echo alert-fastlog.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT alert-fastlog.o -MD -MP -MF $depbase.Tpo -c -o alert-fastlog.o alert-fastlog.c && mv -f $depbase.Tpo $depbase.Po
--- alert-prelude.o ---
depbase=`echo alert-prelude.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT alert-prelude.o -MD -MP -MF $depbase.Tpo -c -o alert-prelude.o alert-prelude.c && mv -f $depbase.Tpo $depbase.Po
--- alert-syslog.o ---
depbase=`echo alert-syslog.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT alert-syslog.o -MD -MP -MF $depbase.Tpo -c -o alert-syslog.o alert-syslog.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer.o ---
depbase=`echo app-layer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer.o -MD -MP -MF $depbase.Tpo -c -o app-layer.o app-layer.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-dcerpc.o ---
depbase=`echo app-layer-dcerpc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-dcerpc.o -MD -MP -MF $depbase.Tpo -c -o app-layer-dcerpc.o app-layer-dcerpc.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-dcerpc-udp.o ---
depbase=`echo app-layer-dcerpc-udp.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-dcerpc-udp.o -MD -MP -MF $depbase.Tpo -c -o app-layer-dcerpc-udp.o app-layer-dcerpc-udp.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-detect-proto.o ---
depbase=`echo app-layer-detect-proto.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-detect-proto.o -MD -MP -MF $depbase.Tpo -c -o app-layer-detect-proto.o app-layer-detect-proto.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-dnp3.o ---
depbase=`echo app-layer-dnp3.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-dnp3.o -MD -MP -MF $depbase.Tpo -c -o app-layer-dnp3.o app-layer-dnp3.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-dnp3-objects.o ---
depbase=`echo app-layer-dnp3-objects.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-dnp3-objects.o -MD -MP -MF $depbase.Tpo -c -o app-layer-dnp3-objects.o app-layer-dnp3-objects.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-enip.o ---
depbase=`echo app-layer-enip.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-enip.o -MD -MP -MF $depbase.Tpo -c -o app-layer-enip.o app-layer-enip.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-enip-common.o ---
depbase=`echo app-layer-enip-common.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-enip-common.o -MD -MP -MF $depbase.Tpo -c -o app-layer-enip-common.o app-layer-enip-common.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-events.o ---
depbase=`echo app-layer-events.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-events.o -MD -MP -MF $depbase.Tpo -c -o app-layer-events.o app-layer-events.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-expectation.o ---
depbase=`echo app-layer-expectation.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-expectation.o -MD -MP -MF $depbase.Tpo -c -o app-layer-expectation.o app-layer-expectation.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-ftp.o ---
depbase=`echo app-layer-ftp.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-ftp.o -MD -MP -MF $depbase.Tpo -c -o app-layer-ftp.o app-layer-ftp.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-htp-body.o ---
depbase=`echo app-layer-htp-body.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I.    -I./../libhtp/  -I/usr/local/include -I/usr/local/include/libnet11 -I/opt/local/include/hs -I/usr/local/include/luajit-2.0   -Wextra -Werror-implicit-function-declaration -Wno-error=unused-command-line-argument     -DLOCAL_STATE_DIR=\"/opt/local/var\" -Wall  -Wno-unused-parameter -Wmissing-prototypes  -Wmissing-declarations -Wstrict-prototypes -Wwrite-strings  -Wbad-function-cast -Wformat-security -Wno-format-nonliteral  -Wmissing-format-attribute -funsigned-char -ggdb -O0 -g -O2 -DOS_FREEBSD -std=c11 -I./../rust/gen -I./../rust/dist -MT app-layer-htp-body.o -MD -MP -MF $depbase.Tpo -c -o app-layer-htp-body.o app-layer-htp-body.c && mv -f $depbase.Tpo $depbase.Po
--- app-layer-expectation.o ---
app-layer-expectation.c:83:5: error: type name requires a specifier or qualifier
    CIRCLEQ_ENTRY(Expectation_) entries;
    ^
app-layer-expectation.c:83:19: error: a parameter list without types is only allowed in a function definition
    CIRCLEQ_ENTRY(Expectation_) entries;
                  ^
app-layer-expectation.c:83:32: error: expected ';' at end of declaration list
    CIRCLEQ_ENTRY(Expectation_) entries;
                               ^
                               ;
app-layer-expectation.c:93:5: error: type name requires a specifier or qualifier
    CIRCLEQ_HEAD(EList, Expectation_) list;
    ^
app-layer-expectation.c:93:18: error: a parameter list without types is only allowed in a function definition
    CIRCLEQ_HEAD(EList, Expectation_) list;
                 ^
app-layer-expectation.c:93:38: error: expected ';' at end of declaration list
    CIRCLEQ_HEAD(EList, Expectation_) list;
                                     ^
                                     ;
app-layer-expectation.c:132:9: error: implicit declaration of function 'CIRCLEQ_FOREACH_SAFE' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        CIRCLEQ_FOREACH_SAFE(exp, &exp_list->list, entries, pexp) {
        ^
app-layer-expectation.c:132:46: error: no member named 'list' in 'struct ExpectationList_'
        CIRCLEQ_FOREACH_SAFE(exp, &exp_list->list, entries, pexp) {
                                   ~~~~~~~~  ^
app-layer-expectation.c:132:52: error: use of undeclared identifier 'entries'
        CIRCLEQ_FOREACH_SAFE(exp, &exp_list->list, entries, pexp) {
                                                   ^
app-layer-expectation.c:188:5: error: implicit declaration of function 'CIRCLEQ_REMOVE' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    CIRCLEQ_REMOVE(&exp_list->list, exp, entries);
    ^
app-layer-expectation.c:188:31: error: no member named 'list' in 'struct ExpectationList_'
    CIRCLEQ_REMOVE(&exp_list->list, exp, entries);
                    ~~~~~~~~  ^
app-layer-expectation.c:188:42: error: use of undeclared identifier 'entries'
    CIRCLEQ_REMOVE(&exp_list->list, exp, entries);
                                         ^
app-layer-expectation.c:245:9: error: implicit declaration of function 'CIRCLEQ_INSERT_HEAD' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        CIRCLEQ_INSERT_HEAD(&exp_list->list, exp, entries);
        ^
app-layer-expectation.c:245:40: error: no member named 'list' in 'struct ExpectationList_'
        CIRCLEQ_INSERT_HEAD(&exp_list->list, exp, entries);
                             ~~~~~~~~  ^
app-layer-expectation.c:245:51: error: use of undeclared identifier 'entries'
        CIRCLEQ_INSERT_HEAD(&exp_list->list, exp, entries);
                                                  ^
app-layer-expectation.c:249:37: error: implicit declaration of function 'CIRCLEQ_LAST' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            Expectation *last_exp = CIRCLEQ_LAST(&exp_list->list);
                                    ^
app-layer-expectation.c:249:61: error: no member named 'list' in 'struct ExpectationList_'
            Expectation *last_exp = CIRCLEQ_LAST(&exp_list->list);
                                                  ~~~~~~~~  ^
app-layer-expectation.c:250:13: error: implicit declaration of function 'CIRCLEQ_REMOVE' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            CIRCLEQ_REMOVE(&exp_list->list, last_exp, entries);
            ^
app-layer-expectation.c:250:39: error: no member named 'list' in 'struct ExpectationList_'
            CIRCLEQ_REMOVE(&exp_list->list, last_exp, entries);
                            ~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** [app-layer-expectation.o] Error code 1

make[2]: stopped in /opt/src/depends/barfield/suricata/src
1 error

make[2]: stopped in /opt/src/depends/barfield/suricata/src

**Comment by jbarfield** [comment]
All of the aforementioned errors are produced with the default build process:


<pre>
 git clone -b suricata-6.0.0-beta1 https://github.com/OISF/suricata.git
 cd suricata
 git clone https://github.com/OISF/libhtp.git
 mv suricata-update ../
 git clone https://github.com/OISF/suricata-update.git
 mv ../suricata-update/* suricata-update/
 ./autogen.sh
 ./configure $(cat ../options.build)
 make -j11 install-full
</pre>


`--prefix=/opt/local --enable-old-barnyard2=no --enable-debug=yes --enable-ipfw=yes --enable-unix-socket=yes --enable-prelude=no --enable-pfring=no --enable-af-packet=no --enable-netmap --enable-dag=no  --disable-nspr --disable-nss --enable-libmagic --enable-napatech=no --enable-hiredis=no --enable-rust-strict=no --enable-python --with-libhs-includes=/opt/local/include/hs --with-libhs-libraries=/opt/local/lib  --enable-suricata-update --enable-luajit --enable-geoip --disable-silent-rules --enable-gccmarch-native=no
`

We had to add the following to the configure phase to get the new queue.h and suricata to build properly:

`CFLAGS=-std=c99`

**Comment by jbarfield** [comment]
I retract all statements for FreeBSD12.1 & HARDENED-BSD 12.1. Copy and Paste of the process above onto a clean 12.1 install builds first time out of the box.

**Comment by catenacyber** [comment]
Closing as the las message indicates it works

**Comment by victorjulien** [comment]
Just FYI I just successfully built the git master on FreeBSD 13.0-RELEASE.

**Pull request closed without merging**
