### PR TITLE
dns: log addresses in flow direction, not packet - v1

### PR DESCRIPTION
**Pull request by jasonish**
Ticket 3340.
https://redmine.openinfosecfoundation.org/issues/3340

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/766
https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/410

### CODE REVIEW

**Comment by jasonish** [comment]
Related suricata-verify PR: https://github.com/OISF/suricata-verify/pull/152

**Comment by jasonish** [comment]
ping @glongo

**Comment by jlucovsky** [comment]
LGTM.

BTW, the URL for the `Ticket` isn't pointing to the redmine issue -- it's pointing to the PR.

**Comment by jasonish** [comment]
> BTW, the URL for the `Ticket` isn't pointing to the redmine issue -- it's pointing to the PR.

Heh, thats GitHub inserting its own link.

**Comment by glongo** [comment]
Looks good to me too, thanks @jasonish.

**Pull request merged**
