### PR TITLE
rust: fix lint warning about enum's name

### PR DESCRIPTION
**Pull request by hsadia538**
- [X] I have read the contributing guidelines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)fixes lint warnings in the rust code

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4597) ticket:

Previous PR: https://github.com/OISF/suricata/pull/7988

Describe changes:
- Squash the commits

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
This looks good. Thank you. :)
One last small change is required from me.
Please remove
```
Squash the commits for:

Delete .DS_Store
rust: fix lint warning about enum's name
fixes lint warnings in the rust code  Ticket: https://github.com/OISF/suricata/pull/4597
Delete suricatactl-filestore.1
Delete suricatactl.1
Delete suricatasc.1
Update .gitignore
```
from the commit message and only have the relevant info in there.
Also, please mention the name of the lint that is fixed i.e. `fix lint warning for the lint enum_variant_names...` in the message.

**Comment by jufajardini** [comment]
> This looks good. Thank you. :) One last small change is required from me. Please remove
> 
> ```
> Squash the commits for:
> 
> Delete .DS_Store
> rust: fix lint warning about enum's name
> fixes lint warnings in the rust code  Ticket: https://github.com/OISF/suricata/pull/4597
> Delete suricatactl-filestore.1
> Delete suricatactl.1
> Delete suricatasc.1
> Update .gitignore
> ```
> 
> from the commit message and only have the relevant info in there. Also, please mention the name of the lint that is fixed i.e. `fix lint warning for the lint enum_variant_names...` in the message.
> 
> Edit: After creating a PR, please set the status of the redmine ticket to "In Review". That helps to not lose track of the status of the issue. wink

Tip related to the removal of some parts of the commit message: if you won't care about the commit messages for the commits being squashed, you may also use fixup, instead, to save time. :)

**Comment by catenacyber** [comment]
How can I see those lint warnings ? (Is this clippy ? Jason has a big PR about fixing some clippy warnings)
Should it be part of a CI check ?

**Comment by jufajardini** [comment]
> How can I see those lint warnings ? (Is this clippy ? Jason has a big PR about fixing some clippy warnings) Should it be part of a CI check ?

From Jason's explanation:
run cargo clippy inside the Rust directory.  You should get no warning.  Then in lib.rs, comment out or remove the line with the lint(s) you want to check. For this PR - #![allow(clippy::enum_variant_names)]

Then, run cargo clippy again.  That will generate the warnings for the code that needs to be fixed so we can stop suppressing that lint.

> Should it be part of a CI check ?

I think we are slowly changing the CI to check on these. (not sure)

**Comment by catenacyber** [comment]
Ok, so see also https://github.com/OISF/suricata/pull/7975

**Comment by inashivb** [comment]
> How can I see those lint warnings ? (Is this clippy ? Jason has a big PR about fixing some clippy warnings) Should it be part of a CI check ?

It is a part of the CI checks already. See https://github.com/OISF/suricata/blob/master/.github/workflows/rust.yml

**Comment by inashivb** [comment]
> Ok, so see also #7975

Yes. Thank you. Jason recently updated the clippy tickets but we'll still keep an eye out.

**Comment by hsadia538** [comment]
Followed by #7991

**Pull request closed without merging**
