### PR TITLE
src: rework includes wip

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- Remove unused includes in alert-debug log.c

Now that #7644 is merged, we can remove includes from C files independently from one another.

This is a draft that compiles on a single configuration, to see if it passes CI
Then I guess wee can try to automate the process

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8388

**Comment by victorjulien** [comment]
This is going to be good...

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8391

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ips_afp_drop_chk.
  

Pipeline 8409

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8429

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8431

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8432

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8433

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8434

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8438

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8439

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8440

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8441

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8443

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 8446

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 8452

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 8453

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7677

**Pull request closed without merging**
