### PR TITLE
Upgrade base64 crate/v4

### PR DESCRIPTION
**Pull request by inashivb**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/7219

Previous PR: https://github.com/OISF/suricata/pull/11695

Changes since v3:
- used NO_PAD mode for http2/doh
- cleanups in import names
- Rebased on top of latest master

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22372

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 32421 | 33804 | 104.27% | 

Pipeline 22410

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22424

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11732, thanks!

**Pull request closed without merging**
