### PR TITLE
Expectation ftp v24

### PR DESCRIPTION
**Pull request by regit**
Update of #3018 

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/550

Describe changes:
- fix problem when client send commands that are not accepted by server

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/356
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/140

### CODE REVIEW

**Comment by victorjulien** [comment]
I've been fuzzing this, and I'm starting to see issues:
<pre>
ASAN:DEADLYSIGNAL
=================================================================
==11232==ERROR: AddressSanitizer: FPE on unknown address 0x00000095b8f4 (pc 0x00000095b8f4 bp 0x7ffdf3ce8ce0 sp 0x7ffdf3ce8be0 T0)
    #0 0x95b8f3 in IPPairGetKey /home/victor/qa/local/afl/suricata/src/ippair.c:377:20
    #1 0x9594cd in IPPairGetIPPairFromHash /home/victor/qa/local/afl/suricata/src/ippair.c:507:20
    #2 0x617206 in AppLayerExpectationCreate /home/victor/qa/local/afl/suricata/src/app-layer-expectation.c:196:11
    #3 0x61b508 in FTPParseRequest /home/victor/qa/local/afl/suricata/src/app-layer-ftp.c:452:32
    #4 0x64e554 in AppLayerParserParse /home/victor/qa/local/afl/suricata/src/app-layer-parser.c:1041:13
    #5 0x653a28 in AppLayerParserFromFile /home/victor/qa/local/afl/suricata/src/app-layer-parser.c:1704:19
    #6 0xb2af0f in ParseCommandLineAFL /home/victor/qa/local/afl/suricata/src/suricata.c:1264:14
    #7 0xb2af0f in ParseCommandLine /home/victor/qa/local/afl/suricata/src/suricata.c:1677
    #8 0xb135a0 in main /home/victor/qa/local/afl/suricata/src/suricata.c:2846:9
    #9 0x7f84a42ae82f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #10 0x41cad8 in _start (/home/victor/qa/local/afl/suricata/src/suricata+0x41cad8)
</pre>

**Comment by victorjulien** [comment]
This is the input that creates that asan crash:
<pre>
00000000  56 0a 0f 0a ff 2f 3c f3  0a 52 65 54 52 ea ca 7f  |V..../<..ReTR...|
00000010  ff 0a 52 40 54 79 79 79  ec 52 7b 89 ed 52 fa 79  |..R@Tyyy.R{..R.y|
00000020  79 ec 00 02 ff 62 52 ea  ca 0a 68 0a 52 54 54 01  |y....bR...h.RTT.|
00000030  79 79 ec 52 15 89 ed ea  ca 0a 10 0a 0a fa 04 fa  |yy.R............|
00000040  00 8b 09 fa f3 54 79 79  79 80 5b 53 53 f8 00 73  |.....Tyyy.[SS..s|
00000050  52 52 ea ca 00 ff 62 52  ea ca 0a 68 0a ff ff fb  |RR....bR...h....|
00000060  80 00 54 79 79 79 ec 79  79 79 79 79 79 79 86 56  |..Tyyy.yyyyyyy.V|
00000070  79 79 79 79 79 79 79 79  79 94 79 79 79 79 79 79  |yyyyyyyyy.yyyyyy|
00000080  79 79 79 79 79 79 79 0f  ff ff e9                 |yyyyyyy....|
0000008b
</pre>

**Comment by regit** [comment]
This output looks weird:
```
    #3 0x61b508 in FTPParseRequest /home/victor/qa/local/afl/suricata/src/app-layer-ftp.c:452:32
```
It looks like code of the v23 branch and not of v24. The expectation creation is not at line 452 in v24.

**Comment by victorjulien** [comment]
Whoops, you are right. Restarting fuzzer :)

**Comment by victorjulien** [comment]
No more crashes, so that is good.

Would you agree that at the last stats.log when processing a pcap, the ftp.memuse counter should be 0? I see no pools so I would expect all ftp memory to be freed.

However, when running a very large pcap, I see as the last record:
<pre>
app_layer.flow.ftp                         | Total                     | 85972
app_layer.flow.ftp-data                    | Total                     | 2797
app_layer.tx.ftp-data                      | Total                     | 2618
ftp.memuse                                 | Total                     | 143883
</pre>

Another question: how can app_layer.flow.ftp-data and app_layer.tx.ftp-data be different?

**Comment by regit** [comment]
Closing this one, found a problem in ftp expectation creation and did optimize the expectation check.

Gonna look at the ftp-data counter too.

**Comment by regit** [comment]
On ftp-data tx, I remember first version was using a tx cnt function returning 1 and you did complain about this. I change to something else and that was just stupid I think. @inliniac if good with you I will switch to single tx.

**Comment by victorjulien** [comment]
On 08-12-17 20:54, Eric Leblond wrote:
> On ftp-data tx, I remember first version was using a tx cnt function
> returning 1 and you did complain about this. I change to something else
> and that was just stupid I think. @inliniac
> <https://github.com/inliniac> if good with you I will switch to single tx.

I don't remember this discussion, but I think we can be sure that a
single ftp-data connection is a single tx, right? More than one seems
impossible, and less too. Then the connection just wouldn't be there.

**Comment by regit** [comment]
Agree. Gonna test that code with single tx and fixes and resubmiting during the weekend.

**Comment by victorjulien** [comment]
Wonder if the expectation 'atomic' check should be per ipproto. In the testing we saw increased cost with udp, even though we don't have any support yet for protocols with udp expectations. I do like that the expectation code is generic, so wouldn't want to give up on that.

**Comment by regit** [comment]
Updated code a performance problem: we had multiple tests per flow, the updated code only check once per direction so we should have a reduced load. If impact is still there maybe switching to per protocol would be a good idea.

**Pull request closed without merging**
