### PR TITLE
JA4 for TLS and QUIC -- v6

### PR DESCRIPTION
**Pull request by satta**
Previous PR: #9598

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6379

Changes to previous PR:
- Rebase.
- Mention in documentation that JA4 hash is not derived from real data and does not match the other hashes.
- Unify checks for whether to update the JA4 state to always check whether a) we have a JA4 object and b) we are in a client hello.
- Update Redmine ticket link in commit message to correct format.

```
SV_BRANCH=pr/1426
```

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Thanks for the work Sascha :-)

- CI : green
- Code : ok for me
- Commits segmentation : Ok
- Commit messages : Ok, thanks
- Git ID set : looks fine for me
- CLA : you already contributed :-)
- Doc update : Ok
- Redmine ticket : ok
- Rustfmt : ok
- Tests : Suricata-verify tests still looks fine
- Dependencies added: none

**Comment by jasonish** [comment]
Just a note that there are questions with respect to the license and patent here. It should be made more clear if JA4 falls under patent restrictions soon: https://github.com/FoxIO-LLC/ja4/issues/15 (or if its just JA4+).

**Comment by john-althouse** [comment]
> Just a note that there are questions with respect to the license and patent here. It should be made more clear if JA4 falls under patent restrictions soon: [FoxIO-LLC/ja4#15](https://github.com/FoxIO-LLC/ja4/issues/15) (or if its just JA4+).

I've updated the thread and readme, there are no patent restrictions for JA4. Thanks for working on this!

**Comment by satta** [comment]
New PR: #10095

**Pull request closed without merging**
