### PR TITLE
Batch backports to 5.0.4

### PR DESCRIPTION
**Pull request by jlucovsky**
Batch backport to 5.0.4

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- [3947](https://redmine.openinfosecfoundation.org/issues/3947) protocol decoder: geneve
- [3946](https://redmine.openinfosecfoundation.org/issues/3946) Incorrect ASN.1 long form length parsing
- [3944](https://redmine.openinfosecfoundation.org/issues/3944) heap-buffer-overflow READ 8 - DZetecdtGetLastSMByL
- [3937](https://redmine.openinfosecfoundation.org/issues/3937) Integer overflow in DetectContentPropagateLimits
- [3935](https://redmine.openinfosecfoundation.org/issues/3935) Integer overflow in SCSigOrderByPriorityCompare

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by victorjulien** [comment]
QA fails.

VXLAN and Teredo commits should be left out I think.

Geneve should be disabled by default. Geneve YAML patch is missing.

**Comment by victorjulien** [comment]
Also, needs a SV PR to enable the Geneve test for 5, making sure it enables it in the config.

**Comment by jlucovsky** [comment]
> QA fails.
> 
Will investigate.

> VXLAN and Teredo commits should be left out I think.
> 

Ok, I'll remove those commits.

> Geneve should be disabled by default. Geneve YAML patch is missing.

Thanks; I found the commit that patches the config.

**Comment by jlucovsky** [comment]
> > QA fails.

An outstanding PR (#5410) addresses the s-v failure.

**Comment by jlucovsky** [comment]
Continued in #5440

**Pull request closed without merging**
