### PR TITLE
rust: fix warnings on rustc 1.67.0-nightly

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None 

Describe changes:
- rust: fix warnings on rustc 1.67.0-nightly

### CODE REVIEW

**Comment by catenacyber** [comment]
The check rust failure seems unrelated...
What is it Jason ?

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .tcp.ssn_from_cache | 3647103 | 4928666 | 135.14% |
| .tcp.ssn_from_pool | 8482654 | 7201091 | 84.89% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 6632657 | - |
| .flow.end.state.new | 6272 | 46712 | 744.77% |
| .flow.end.tcp_state.syn_sent | 0 | 12779 | - |
| .flow.end.tcp_state.syn_recv | 0 | 140 | - |
| .flow.end.tcp_state.established | 53996 | 76542 | 141.75% |
| .flow.end.tcp_state.fin_wait1 | 0 | 1770 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 603 | - |
| .flow.end.tcp_state.time_wait | 0 | 874 | - |
| .flow.end.tcp_state.last_ack | 0 | 470 | - |
| .flow.end.tcp_state.close_wait | 0 | 2361 | - |
| .flow.end.tcp_liberal | 80952 | 285517 | 352.7% |
| .tcp.segment_from_cache | 264716640 | 249979018 | 94.43% |
| .tcp.reassembly_gap | 80952 | 841365 | 1039.34% |
| .tcp.overlap | 0 | 115 | - |
| .app_layer.error.http.parser | 0 | 643 | - |
| .app_layer.error.ftp.gap | 0 | 97 | - |
| .app_layer.error.smtp.gap | 0 | 1047 | - |
| .app_layer.error.tls.gap | 53852 | 233279 | 433.19% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 406 | - |
| .ftp.memuse | 0 | 356 | - | 

Pipeline 10405

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10407

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10410

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10412

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10433

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #8157, thanks!

**Pull request closed without merging**
