### PR TITLE
Backports/708/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Need the stream addition to make SV pass (task-7018-* tests)

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2178

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
It looks consistent with the original work.

**Review by catenacyber — CHANGES_REQUESTED** [review]
This is not consistent with original work because of added commit
detect: readd app-layer to alerts on stream matches

**Comment by catenacyber** [comment]
And more important, SV testing does not include bug-7199

**Comment by jasonish** [comment]
I think that second commit needs more of a description in it as its not consistent with whats being backported.

**Comment by victorjulien** [comment]
w/o it we break tests, this indicates a regression. The commit fixes the regression.

**Comment by jasonish** [comment]
It appears this change of behaviour is not address in the upgrade guide, should it be something for the upgrade guide in master?

**Comment by jufajardini** [comment]
> It appears this change of behaviour is not address in the upgrade guide, should it be something for the upgrade guide in master?

Is that about the live transactions? If yes, https://github.com/OISF/suricata/pull/12266 adds that, but Victor want the docs for post-merge of the staging branch

**Comment by catenacyber** [comment]
> Victor want the docs for post-merge of the staging branch

I think he meant post merge of https://github.com/OISF/suricata/pull/12259

**Comment by victorjulien** [comment]
replaced by #12267

**Pull request closed without merging**
