### PR TITLE
Setup app layer fix v1

### PR DESCRIPTION
**Pull request by jufajardini**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- there isn't one. Would it be better if I created one, in this case?

[Previous PR #5983 ](https://github.com/OISF/suricata/pull/5983)

Describe changes:
- use the `lstrip()` solution.
- add lines for the header files, not only `.c` ones
- add fix for the `detect` option, too.
- as is, the script will add the lines right above the `template` ones, I wanted to make it happen in alphabetical order, but don't know how, yet.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by jlucovsky** [comment]
This looks good to me.

Can I suggest that the spelling errors in the `src/*template*` files be fixed with this PR?

**Comment by jufajardini** [comment]
> This looks good to me.
> 
> Can I suggest that the spelling errors in the `src/*template*` files be fixed with this PR?

Perfect with me! I'll have a look and see what I find, and fix those. Do you happen to have some on the top of your mind, so I have an idea of what you have in mind?

**Comment by jlucovsky** [comment]
> > This looks good to me.
> > Can I suggest that the spelling errors in the `src/*template*` files be fixed with this PR?
> 
> Perfect with me! I'll have a look and see what I find, and fix those. Do you happen to have some on the top of your mind, so I have an idea of what you have in mind?

Here's a quick list -- my editor highlights misspellings with red-underscores -- from files within src/*template*.[ch] and src/test/*template*.[ch]. I didn't look at the template files within the `rust` subdirectory.
- pruposes
- recieved
- registeringd
- detecter
- allocted
- atemplate2d 
- modififier
- occurence
- arround

**Comment by jufajardini** [comment]
Thanks a lot for the list, I believe I can move on from there, and check the rust files as well. :)

**Comment by jufajardini** [comment]
Closed with PR (5988)[https://github.com/OISF/suricata/pull/5988]

**Pull request closed without merging**
