### PR TITLE
docs: improve code documentation- v2

### PR DESCRIPTION
**Pull request by zazie-codes**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
This is an update of https://github.com/OISF/suricata/pull/9604
- made suggested spacing and name errors.
-added file and author tag in the files to elaborate each file description maintaining consistency with the Suricata's documentation style.
-Ensure there are no syntax errors and grammatical errors in the document maintaining existing format.

ISSUE
Ticket.6383

Notes
The file description added is in line with your existing documentation standards and will enhance the documentations accessibility.
The additions are clear and concise.

I'll appreciate your feedback and guidance on how to improve the changes.

### CODE REVIEW

**Comment by victorjulien** [comment]
Please have a look at existing commits in our git tree, and bring yours in line with that.

**Comment by jufajardini** [comment]
Also @zazie-codes, to help us reviewers' job, please keep the PRs with the same title, and add a version number to them. This helps us know that the new PR is a continuation. (Check the example below ;) )
image

**Comment by zazie-codes** [comment]
> Also @zazie-codes, to help us reviewers' job, please keep the PRs with the same title, and add a version number to them. This helps us know that the new PR is a continuation. (Check the example below ;) ) image

Is it okay if i proceed with this current one since the other one was not direct about my commit.

**Comment by jufajardini** [comment]
It's still the same contribution thread. You can change the PR title. I think that thinking about a PR title that sums up the work you've done will help you with adjusting the commit messages to be in style with our commit guidelines, too ;)

> 
> Is it okay if i proceed with this current one since the other one was not direct about my commit.

**Comment by zazie-codes** [comment]
> It's still the same contribution thread. You can change the PR title. I think that thinking about a PR title that sums up the work you've done will help you with adjusting the commit messages to be in style with our commit guidelines, too ;)
> 
> > Is it okay if i proceed with this current one since the other one was not direct about my commit.

Hows it looking? Is it better?

**Comment by jufajardini** [comment]
When you incorporate feedback from this PR, please also address this CI failure: https://github.com/OISF/suricata/actions/runs/6496454785/job/17643536696?pr=9606#step:14:23

The check indicates how to solve it ^^

**Comment by zazie-codes** [comment]
> When you incorporate feedback from this PR, please also address this CI failure: https://github.com/OISF/suricata/actions/runs/6496454785/job/17643536696?pr=9606#step:14:23
> 
> The check indicates how to solve it ^^

I'll do just that.

**Comment by zazie-codes** [comment]
> When you incorporate feedback from this PR, please also address this CI failure: https://github.com/OISF/suricata/actions/runs/6496454785/job/17643536696?pr=9606#step:14:23
> 
> The check indicates how to solve it ^^

just to clarify, is this is the only issue in my submission?

**Comment by victorjulien** [comment]
Replaced by #9611

**Pull request closed without merging**
