### PR TITLE
smb: check file lengths against nbss records length

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5770

Describe changes:
- smb : fix evasions by abusing length field

I still need to create a pcap with this attack...

suricata-verify-pr: 1049

Replacing #8331 with code review taken into account

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 11399

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104110 | 81.19% |
| .app_layer.error.tls.parser | 931 | 1145 | 122.99% |
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 565135168 | 666105088 | 117.87% |
| .app_layer.flow.http | 3118951 | 3340798 | 107.11% |
| .app_layer.flow.tls | 510462 | 623355 | 122.12% |
| .app_layer.flow.ssh | 8937 | 11032 | 123.44% |
| .app_layer.flow.telnet | 1624 | 2334 | 143.72% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 544 | 0.00 | 

Pipeline 11492

**Comment by catenacyber** [comment]
Action: make a new version where Victor understands the check

**Comment by catenacyber** [comment]
So, Victor would like to check that for instance the (write record length) + (the offset of the write record data compared to the start of the NBSS record) is lesser than the NBSS record length

That means passing two informations to `smb1_write_request_record` and such, instead of one :
- the NBSS record length (easy, fair enough)
- the offset of the write record data compared to the start of the NBSS record : we need to pass the start of the NBSS record
  - I find it dangerous to do pointer arithmetics even in rust (ie subtracting pointers to get an offset)
  - Using constant values for this offset is prone to error cf https://redmine.openinfosecfoundation.org/issues/5805

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8399

**Pull request closed without merging**
