### PR TITLE
[Draft] netmap: Netmap API 14 support

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #6296 

This commit provides support for Netmap API version 14+.

We thank @bmeeks8 for his contributions -- much of the content in this
pull request are the result of his efforts.

This commit is in *DRAFT* mode and should not be used in production
systems.

Updates
- Multiple threads will be created to process packets iff the network interface supports multiple queues
- And, multiple threads have been configured, e.g., using `threads: auto` in the `netmap` section.
- Netmap V14 API used if available *and* libnetmap.h exists; it's required for multi-thread support.

This has been tested with runmodes `autofp` and `workers`.

Multiple thread support is working for
- IPS with Host method, e.g., interface-name and interface-name^
- IDS mode

In IPS mode and when using physical interfaces, `threads: 1` required as packets are not yet fully distributed to multiple
queues.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_alerts_cmp |


Pipeline 3888

**Comment by victorjulien** [comment]
So it seems FreeBSD 11 is almost EOL, leaving us with 12+. My fully updated 12.2 VM has Netmap API 14. Should we just make API 14 the only supported version?

**Comment by bmeeks8** [comment]
There may be another more problematic issue that needs addressing. After some research, it appears the libnetmap wrapper library is present only in the FreeBSD 12.2-STABLE branch and up (including 13.0-RELEASE). That wrapper is not part of FreeBSD 12.2-RELEASE and lower. The inclusion of the Netmap v14 API is somewhat divorced from the libnetmap wrapper library.

So that means the _nmport_prepare()_, _nmport_open_desc()_,  _nmport_inject()_ and _nmport_close()_ functions used from that wrapper library are not available in the 12.x RELEASE versions of FreeBSD. You can still do multiple host rings, but you must call the lower-level netmap functions in order to do so. And the parsing of the device descriptor string (the "netmap:xxx" or "vale:xxx" device name with the optional arguments) would have to be done within Suricata code. Then the proper values and bit flags set in the _nm_req_ structure prior to calling the _ioctl()_ function to open the netmap device.

If Suricata restricts itself to using simple "netmap:" or "vale:" device types, creating the parser code would not be too difficult. There is a template to follow in the source code for the libnetmap library.

**Comment by jlucovsky** [comment]
We discussed how to handle the "wrapper" library used by Suricata. There are 2 paths forward

For `master` (7.0), Netmap V14 with the wrapper library is required
For `6.0.x`, an additional configuration flag (name tbd) will be required to select Netmap V14 (the wrapper library will be required). Without the additional configuration flag, functionality from V14 will not be used.

**Comment by bmeeks8** [comment]
> We discussed how to handle the "wrapper" library used by Suricata. There are 2 paths forward
> 
> For `master` (7.0), Netmap V14 with the wrapper library is required
> For `6.0.x`, an additional configuration flag (name tbd) will be required to select Netmap V14 (the wrapper library will be required). Without the additional configuration flag, functionality from V14 will not be used.

I think that is a good approach. Over time the wrapper library should become standard in the various OS releases supporting netmap.

**Pull request closed without merging**
