### PR TITLE
Feature/http range/master6/v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
none

Describe changes:
- HTTP range support for version 6, with configure-time option to enable `./configure --enable-http-range-reassembly`

All commits cherry-picked, including later fixes, plus one final commit to make the whole thing optional at compile time

Tested with `python3 ../suricata-verify/run.py --force range`

cc @victorjulien

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on tlpw2_single_alerts_cmp.

ERROR: QA failed on tlpw2_autofp_alerts_cmp.

ERROR: QA failed on tlpr1_alerts_cmp.
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.mgr.rows_maxlen | 373 | 539 | 69.2% | 

Pipeline 4562

**Comment by pevma** [comment]
The correct pipeline number for the lust results is 4597.

**Comment by suricata-qa** [comment]
ERROR: QA failed on build_dbg.
  

Pipeline 5073

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on build_dbg.
  

Pipeline 5073

**Comment by catenacyber** [comment]
@victorjulien should I rebase or close this ?

**Comment by victorjulien** [comment]
Rebase in new PR would be my preference.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7517

**Pull request closed without merging**
