### PR TITLE
Adds WinDivert support to Windows builds

### PR DESCRIPTION
**Pull request by smithjacobj**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/2455

Describe changes:

Enables IPS functionality on Windows using the open-source
(LGPLv3/GPLv2) WinDivert driver and API. Special thanks to @basil00
for dual-licensing WinDivert for this project.

From https://www.reqrypt.org/windivert-doc.html : "WinDivert is a
user-mode capture/sniffing/modification/blocking/re-injection package
for Windows Vista, Windows Server 2008, Windows 7, and Windows 8.
WinDivert can be used to implement user-mode packet filters, packet
sniffers, firewalls, NAT, VPNs, tunneling applications, etc., without
the need to write kernel-mode code."

- adds `--windivert [filter string]` and `--windivert-forward [filter
    string]` command-line options to enable WinDivert IPS mode.
    `--windivert[-forward] true` will open a filter for all traffic. See
    https://www.reqrypt.org/windivert-doc.html#filter_language for more
    information.

Limitation: currently limited to `autofp` runmode.

Additionally:
- `tmm_modules` now zeroed during `RegisterAllModules`
- fixed Windows Vista+ `inet_ntop` call in `PrintInet`
- fixed `GetRandom` bug (nonexistent keys) on fresh Windows installs
- Added WMI queries for MTU

---

This is a replacement for #3355

### CODE REVIEW

**Comment by victorjulien** [comment]
I have windivert compiled in, but not yet getting it to work.

I have '--windivert tcp' on my commandline, but I'm getting

WinDivertOpen failed, error: 2 (on source-windivert.c:483)

This is on win10 64bit, in a vm with mingw. I also downloaded the mingw binary from windivert. Any ideas?

**Comment by victorjulien** [comment]
screenshot from 2018-05-24 09-44-02

See screenshot. It seems the filter has some effect. 'tcp' doesn't list devices, but 'true' does. The ultimate error is the same though. Open to suggestions.

**Comment by basil00** [comment]
If `WinDivertOpen` fails with `ERROR_FILE_NOT_FOUND` (code=2) it means that either the `WinDivert64.sys` or `WinDivert32.sys` driver files were not found.  To fix you should put the driver files in the same directory as `suricata.exe`.

**Comment by victorjulien** [comment]
Ah yes, that did it, thanks @basil00 ! I see packets & logs now. Very cool.

**Comment by victorjulien** [comment]
Would it be possible for this error to be more explicit so it's more actionable by the user?

**Comment by victorjulien** [comment]
btw, it seems these warnings about filters are a bit verbose for successful(?) operations
screenshot from 2018-05-24 12-38-12

**Comment by smithjacobj** [comment]
I can make the common errors more explicit. Possibly make those warnings lower priority so it's not so noisy.

**Comment by smithjacobj** [comment]
Which messages, specifically, should be made less verbose? What output level is preferable? I think the top ones should stay visible, it lets the user know what adapters are being monitored. That said, the bottom ones are just noise, as generally it's an issue with software-only devices. That said, maybe even removing the `win32-syscall.c:659` Info-level message seems fine to me, leaving the more verbose error.

image

**Comment by victorjulien** [comment]
Maybe make the top ones SCLogConfig? It seems those bottom warnings give 2 warnings per single failure? So maybe those can be merged.

**Comment by smithjacobj** [comment]
Sounds good. I did un-duplicate the bottom error spew, but I'll set the top ones to `SCLogConfig`.

**Pull request closed without merging**
