### PR TITLE
Add a definition for the number of actions

### PR DESCRIPTION
**Pull request by stricaud**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
Creates a definition to specify the number of actions. This is needed for my Xmas changes.

Until now, the number of actions (4) was hard-coded in multiple places of the code. This change fixes it.

It is now recommended to use the NUMBER_OF_ACTIONS definition anytime one need to use the number of actions.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by stricaud** [comment]
Hi,

I was kind of letting this go, but this is the easiest patch of something more complicated, and I felt I did everything right, even by reading the submission quality, I want to learn how I can push this. 

First of all, this is a *dumb* and very obvious patch, nothing crazy here. When I write, "add a definition for the number of actions" when the only change it to make sure we have the definition of the number of actions, using #define, I have no idea what am I missing in the git commit message here.

Because of the policy, I am explaining the value was hard-coded, and I create a definition instead.

I would love to understand what am I missing here, because I don't get it, and I feel discouraged to push the hardest patches.

Thanks.

**Comment by victorjulien** [comment]
Hi @stricaud, the PR itself does not become part of git. So it should not contain info that is not in the git commit message itself. The PR has more explanation than the git message itself.

2nd, the commit message should follow the formatting guide, so a short subject line. It's too long currently.

**Comment by stricaud** [comment]
ok will change that and re-open, thanks for the explanation!

**Comment by victorjulien** [comment]
Please make sure to follow: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Github_work_flow#Incorporating-feedback

In short: new branch and new PR for changes. Thanks!

**Pull request closed without merging**
