### PR TITLE
Tx track modif 7087 v17

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7087

Describe changes:
- app-layer: track modified/processed txs

#11976 with better git message and format fix

### CODE REVIEW

**Comment by catenacyber** [comment]
@ct0br0 
what does mean the QA report ?
```
2013076:11
 missing in test alerts
2013435:6
 missing in base alerts
```

With this PR, we have less 2013076 but more 2013435 than in master ?

**Comment by ct0br0** [comment]
The top 500 alerts switched around. I can try to get pcaps for them but usually that is just massive data and threading moving things around. Or in this case, the pr mentions tracking so it could be something with that.

**Comment by catenacyber** [comment]
Testing another QA run to confirm

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23210

**Comment by victorjulien** [comment]
Passed my QA. Ran this PR with SV master. Local pipeline 5161, run 655.

**Comment by catenacyber** [comment]
So, approved ?

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #12259, thanks!

**Pull request closed without merging**
