### PR TITLE
src: remove unused headers-exported functions

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None : generic cleaning
https://redmine.openinfosecfoundation.org/issues/4083

Describe changes:
- remove functions defined in a header and never used (debug, api-completeness, and others)
- remove double definition of IPPairLock

Python helper script to do this in previous PR

Rebase of #9420

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | ASAN_TLPR1_suri | | |
 

Pipeline 15989

**Review by jasonish — APPROVED** [review]
LGTM

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 195 | 184 | 94.36% | 

Pipeline 16045

**Review by victorjulien — CHANGES_REQUESTED** [review]
need rebase, thanks

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata/pull/9835

**Pull request closed without merging**
