### PR TITLE
Detect cleanups/v2

### PR DESCRIPTION
**Pull request by victorjulien**
Next set of detection related cleanups, part of a bigger rewrite branch (in progress).

Most interesting are:
https://github.com/OISF/suricata/commit/301901f44d4c4cd988dd41490875e3a48e0ca9ce -- instead of constantly checking and update `DetectEngineThreadCtx` recursion counting is done on the stack

https://github.com/OISF/suricata/commit/493be0aba9b741d0a3a79632e0cb2ff56aee91c6 -- InspectionBuffer specific entry point to this API, to as a convenience.

Mostly cleanups otherwise.

Review per commit may make more sense than the whole diff in one step.

Also includes #9932

### CODE REVIEW

**Comment by victorjulien** [comment]
Force push to drop a patch that shouldn't have been part of this yet.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 181 | 197 | 108.84% | 

Pipeline 16836

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16838

**Comment by victorjulien** [comment]
replaced by #9949

**Pull request closed without merging**
