### PR TITLE
http: fix condition check [backport7]

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7310

Describe changes:
- backport of https://github.com/OISF/suricata/pull/11901 clean cherry-pick

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 23084

**Review by victorjulien — APPROVED** [review]

**Comment by inashivb** [comment]
You can take [ff26d90](https://github.com/OISF/suricata/pull/11898/commits/ff26d904dd437233d1c6a40865065759f670fd3a) and the rpm fixes for green CI

**Comment by victorjulien** [comment]
> You can take [ff26d90](https://github.com/OISF/suricata/pull/11898/commits/ff26d904dd437233d1c6a40865065759f670fd3a) and the rpm fixes for green CI

We'll need more than that to get CI green, the rpm cbindgen stuff as well.

**Comment by catenacyber** [comment]
I just did backport s for my PRs/commits
Should I do others ?

**Comment by inashivb** [comment]
> I just did backport s for my PRs/commits Should I do others ?

I usually do the CI fixes backports myself just to get the green CI..

**Comment by inashivb** [comment]
> I see you cherry-picked one right commit in #11898
> 
> Why did you not do its own PR for [ff26d90](https://github.com/OISF/suricata/commit/ff26d904dd437233d1c6a40865065759f670fd3a) ?
> 

because my PR would still be red..
I tried creating new branch w this MacOs fix and then tried cherry-picking the rpm fixes and they were messy so I left it. 🐤

**Comment by victorjulien** [comment]
Merged in #11982, thanks!

**Pull request closed without merging**
