### PR TITLE
detect/http-server-body: clean up tests

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/4083

Describe changes:
- Some quick unittest cleanups.

Inspired by https://github.com/OISF/suricata/pull/11113

### CODE REVIEW

**Review by victorjulien — DISMISSED** [review]
Nice!

**Comment by victorjulien** [comment]
Except build issues :)

**Comment by catenacyber** [comment]
> Except build issues :)

Turning to draft while fixing.
So now we know that we do not need the request to match on the server body ;-)

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20753

**Comment by catenacyber** [comment]
Clean in https://github.com/OISF/suricata/pull/11137

**Pull request closed without merging**
