### PR TITLE
Multipart mime 3487 v37

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3487

Describe changes:
- convert HTTP to use new rust mime parser
- convert SMTP to use new rust mime parser

Follows #10734 with needed rebase 

There should be no more QA diff after merge of https://github.com/OISF/suricata/pull/10981 and rebaseline

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1847

### CODE REVIEW

**Comment by catenacyber** [comment]
I need to do a SV PR to modify the behavior and no longer error on bug-1449

**Comment by victorjulien** [comment]
Not sure if we lack tests of if this is due to CI failures, but it would be nice to make sure we have tests covering the smtp output logic here https://app.codecov.io/gh/OISF/suricata/pull/11115/blob/rust/src/mime/smtp_log.rs

**Comment by ct0br0** [comment]
qa tokens ran out. ignore the 'pipeline canceled' incoming

**Comment by catenacyber** [comment]
> Not sure if we lack tests of if this is due to CI failures, but it would be nice to make sure we have tests covering the smtp output logic here https://app.codecov.io/gh/OISF/suricata/pull/11115/blob/rust/src/mime/smtp_log.rs

Would you have a pcap with `Bcc:` ?

Otherwise, next rebased PR will use next extended SV tests ;-)

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata/pull/11130

**Comment by catenacyber** [comment]
I did `git grep Bcc: .. | grep pcap` in suricata-verify/tests and there were no results, if you have somewhere else to grep ;-)

**Pull request closed without merging**
