### PR TITLE
userguide: explain rule types and categorization - v8

### PR DESCRIPTION
**Pull request by jufajardini**
Previous PR: #12114 

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7031

Please check the built version: https://suri-rtd-test.readthedocs.io/en/doc-sigtypes-et-properties-v8/rules/rule-types.html

Describe changes:
- Move to its own section under `Suricata Rules`
- Add engine analysis report examples for each rule type 
  - Showcase having these examples collapsed, as some can be quite lengthy
- Another try at https://github.com/OISF/suricata/pull/12114#discussion_r1839699302, I think this is more correct, but a strict read of this table, especially for `stream` and `packet-stream` rule types is very welcome
- Newer version of the flowchart for `SignatureSetType()`. Add the drawio file to version control - makes maintaining easier.
- Add explanation about different outcomes of using Flowvars and other similar keywords
- Add a brief explanation about the existence of rules that require real packets (more work to be done here with https://redmine.openinfosecfoundation.org/issues/7424), trying to tackle https://github.com/OISF/suricata/pull/12095#issuecomment-2483178292 -- what do you think, @catenacyber ?
- add a table/ list with human readable rule types

Many of the examples and conclusions documented here were derived from tests and checks as seen on https://github.com/OISF/suricata-verify/pull/2153

### CODE REVIEW

**Comment by jufajardini** [comment]
Moved to draft as I see too many CI failures.
Still apt for a review, though, please.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 23611

**Review by inashivb — COMMENTED** [review]
The docs look neat and well organized. If you clean the PR, this looks pretty good to me.
Will let others review the content too.

**Comment by jufajardini** [comment]
Clang and commit errors were due to a mistakenly added libhtp build workflow? I'll never know how, but fixed.

Still trying to figure out how to fix the Almalinux 9 failure. Must find the right package for `sphinx-toolbox` there...

**Comment by jasonish** [comment]
Doesn't look like sphinx-toolbox is universally available in system packages?  And we'd at least need it on the Dist Builder which is currently Ubuntu 22.04.

**Comment by jasonish** [comment]
> Not sure I'll be able to, as I couldn't find the package for that distro. I went back to #9165 to see if @jasonish had found a solution for displaying very long json/ schema stuff, but failed to find something.

I can't remember what the issue was, but this work did get merged.

**Comment by jufajardini** [comment]
> > Not sure I'll be able to, as I couldn't find the package for that distro. I went back to #9165 to see if @jasonish had found a solution for displaying very long json/ schema stuff, but failed to find something.
> 
> I can't remember what the issue was, but this work did get merged.

But I think with your work you didn't use anything to collapse large sections, right?

**Comment by jufajardini** [comment]
collapsible sections removed with https://github.com/OISF/suricata/pull/12209

**Comment by jasonish** [comment]
> But I think with your work you didn't use anything to collapse large sections, right?

No, it didn't.

**Pull request closed without merging**
