### PR TITLE
doc: escape dot in pcre

### PR DESCRIPTION
**Pull request by myr463**
- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Escape a dot in a regular expression to match `.com` TLD

@catenacyber

### CODE REVIEW

**Comment by victorjulien** [comment]
Hi @myr463, you've checked "￼ I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/ ", but I'm not able to find a record of this. Could you retry?

**Comment by victorjulien** [comment]
> Hi @myr463, you've checked "￼ I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/ ", but I'm not able to find a record of this. Could you retry?

Nevermind, I found it. Sorry for the noise.

**Review by catenacyber — APPROVED** [review]
Looks relevant to me

**Comment by jlucovsky** [comment]
LGTM

**Review by norg — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #6306, thanks!

**Pull request closed without merging**
