### PR TITLE
detect-lua: Convert unittests to FAIL/PASS API-v3

### PR DESCRIPTION
**Pull request by Rai0Catodic0**
Ticket: [4051](https://redmine.openinfosecfoundation.org/issues/4051)

- [ :white_check_mark: ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ :white_check_mark: ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- Convert tests to use the FAIL/PASS macro

### CODE REVIEW

**Comment by jufajardini** [comment]
Hi, thanks for this contribution! :)

Not sure if you saw my comment on the previous PR: https://github.com/OISF/suricata/pull/8400#issuecomment-1412827015

Since the other work isn't finished, I'm not sure how we'll handle your PR. But wanted to bring attention to the situation....

**Review by jufajardini — APPROVED** [review]
Changes look good to me, thanks! :)

**Comment by jufajardini** [comment]
> Hi. I'm really sorry about that, I must have missed your last comment. Thanks for the warning.

Hi there, we've analyzed this and considered that it is worth merging, when ready since the other work is still in progress. So, thank you for your contribution! :)

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #8605, thanks!

**Pull request closed without merging**
