### PR TITLE
rust: fix build with MSRV

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6876

Describe changes:
- rust: fix build with MSRV

### CODE REVIEW

**Comment by victorjulien** [comment]
Is there any practical effect from this change?

**Comment by catenacyber** [comment]
Rust panics on allocation failure

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19636

**Comment by catenacyber** [comment]
The original commit created `set_string_from_bytes_limited` by copy/pasting `set_string_from_bytes`

In master `set_string_from_bytes` uses `try_string_from_bytes`, In master-6.0.x, it uses `string_from_bytes`

So, this PR looks like the good way to backport the original commit

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #10679, thanks!

**Pull request closed without merging**
