### PR TITLE
threshold: fix regex to accept by_both and by_rule backport6

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5327

Describe changes:
- Backport of https://github.com/OISF/suricata/pull/7380

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10413

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | TREX_GENERIC_collect | | |
 

Pipeline 10425

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10432

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 10498

**Comment by catenacyber** [comment]
Pushing with cherry-pick of fix for fuzz target

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 10616

**Comment by victorjulien** [comment]
Merged in #8177, thanks!

**Pull request closed without merging**
