### PR TITLE
next/416/20240419/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #10868
 - #10869
 - #10879
 - #10882
 - #10891
 - #10896
 - #10912

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1791

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
  

Pipeline 20200

**Review by catenacyber — APPROVED** [review]
Looks consistent with the individual PRs

**Comment by catenacyber** [comment]
#10869 was rebased in a new version

**Comment by victorjulien** [comment]
> #10869 was rebased in a new version

Yeah, was a clean rebase. This PR has the same code.

**Pull request merged**
