### PR TITLE
sip/stat_code: fix buffer name

### PR DESCRIPTION
**Pull request by starrysec**
Bug #7295

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [ ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [ ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [ ] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [ ] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
-
-
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2072
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks, but did you see https://github.com/OISF/suricata/pull/11846#issuecomment-2390709368 ?

> @starrysec can you please rework this in a next PR:
> 
> 1. make sure to review the entries from the PR template
> 2. review & sign the CLA
> 3. use a real name commit author setting.
>    Thanks!

That means you should also make use of https://github.com/OISF/suricata-verify/pull/2072 (see PR template)

**Review by jufajardini — CHANGES_REQUESTED** [review]
Linked the SV PR here, re-run the CI checks.

Marking this as changes requested as per Philippe's comment ;)

**Comment by jufajardini** [comment]
@starrysec we'd like to have your patch merged for our next release.

But for us to be able to merge it, we need the commit author to be the same as we see in the CLA, could you fix that, rebase the code, and submit a new PR?

**Comment by jlucovsky** [comment]
Closed due to lack of response from PR author.

**Pull request closed without merging**
