### PR TITLE
devguide: add page on installing suricata from git

### PR DESCRIPTION
**Pull request by mrbazzan**
Continuation from #8128 

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#5585](https://redmine.openinfosecfoundation.org/issues/5585)

Describe changes:
- Incorporated review from #8128 

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Comparing this with the prior reviews from other PRs, I think this is ready to go, now.

**Comment by jasonish** [comment]
The only thing I might consider adding is a line "These instructions were tested on Ubuntu 22.04" or whatever.

**Comment by jufajardini** [comment]
Checks failing for lack of rebase, possibly?

**Comment by jufajardini** [comment]
> The only thing I might consider adding is a line "These instructions were tested on Ubuntu 22.04" or whatever.

I could amend that, if that's ok.

**Comment by jasonish** [comment]
> > The only thing I might consider adding is a line "These instructions were tested on Ubuntu 22.04" or whatever.
> 
> I could amend that, if that's ok.

Fine for it to be its own standalone commit by you as well.

**Comment by jufajardini** [comment]
Merged via https://github.com/OISF/suricata/pull/8258#event-7997175122
Thanks! :)

**Pull request closed without merging**
