### PR TITLE
app-layer: remove unidirectional flag

### PR DESCRIPTION
**Pull request by jasonish**
Based on https://github.com/OISF/suricata/pull/8601, we should be able to
remove the unidirectional flag on a parser, instead transactions are now the
scope of bidirectional or unidirectional.

Draft for QA purposes.

suricata-verify-pr: 1140

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 12755

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 12756

**Comment by victorjulien** [comment]
What is the status of this? Seems QA is unhappy.

**Comment by jasonish** [comment]
> What is the status of this? Seems QA is unhappy.

Updated. QA results should be identical to https://github.com/OISF/suricata/pull/8601.

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 145160 | 113016 | 77.86% | 

Pipeline 12936

**Comment by jasonish** [comment]
Out of draft as the PR its based on is now in master.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 112875 | 145039 | 128.5% | 

Pipeline 13241

**Pull request closed without merging**
