### PR TITLE
dns: add dns.rrtype keyword v4

### PR DESCRIPTION
**Pull request by hadiqaalamdar**
Feature #6666

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6666) ticket: https://redmine.openinfosecfoundation.org/issues/6666

Previous PR: https://github.com/OISF/suricata/pull/10306

Describe changes:
- cleaned up the commit history
- SV tests are passing
- successfully ran the following tests:
- from rust dir: make check
- from rust dir: cargo test
- from rust dir: cargo clippy --all-features
- from rust dir: rustfmt src/dns/*
- from suricata dir: ./scripts/clang-format.sh check-branch
- from suricata dir: ./scripts/clang-format.sh branch
- from suricata dir running ./src/suricata -u showed that one unit test had failed. 
- from suricata dir running ./src/suricata -u -U dns showed 7 tests passed.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1629

### CODE REVIEW

**Comment by inashivb** [comment]
Why is this draft?

**Comment by hadiqaalamdar** [comment]
> Why is this draft?

I can mark it as ready for review. Just wanted to make sure that it passed all the checks.

**Review by jufajardini — CHANGES_REQUESTED** [review]
Looking very good, congrats!

The recent merge to master means this needs a rebase now, though.

**Comment by hadiqaalamdar** [comment]
Created new PR for SV test: https://github.com/OISF/suricata-verify/pull/1635. Will rebase and create a new PR once the CI issues mentioned with the failing clippy and cocci tests have been fixed.

**Comment by hadiqaalamdar** [comment]
New PR: https://github.com/OISF/suricata/pull/10435

**Pull request closed without merging**
