### PR TITLE
7.0.x backport: Fix stats missing for non workers

### PR DESCRIPTION
**Pull request by jlucovsky**
7.0.x backport of #10583

Follow up for: https://redmine.openinfosecfoundation.org/issues/6907 
Describe changes:

Commit b8b8aa69b49ac0dd222446c28d00a50f9fd7d716 used tm_name of the first StatsRecord of a thread block as key for the "threads" object. However, depending on the type of thread, tm_name can be NULL and would result in no entry being included for that thread at all. This caused non-worker metrics to vanish from the "threads" object in the dump-counters output.

This patch fixes this by remembering the first occurrence of a valid tm_name within the per-thread block and adds another unittest to cover this scenario.

Update:
- Associated with newly created issue 6907 (was 6746 -- already closed)

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

SV BRANCH=pr/1686

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19816

**Comment by jasonish** [comment]
Should this have a new ticket?  6746 is closed and marked as fixed in the 7.0.4 changelog.

**Review by catenacyber — CHANGES_REQUESTED** [review]
Could you rebase it on latest main-7.0.x to get greener CI ?

**Comment by jlucovsky** [comment]
> Should this have a new ticket? 6746 is closed and marked as fixed in the 7.0.4 changelog.

Will associated with 6907 (newly created).

**Comment by jlucovsky** [comment]
Continued in #10742

**Pull request closed without merging**
