### PR TITLE
doc: generate eve reference - v4

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: https://github.com/OISF/suricata/pull/9165
Ticket: https://redmine.openinfosecfoundation.org/issues/6288

Use the EVE schema to produce:
- app-layer specific EVE reference: shown here are quick and pgsql
- generate a complete EVE reference
- generate "dot" separated eve reference

Documentation examples:
- PGSQL: https://jasonish-suricata.readthedocs.io/en/evedoc-v4/output/eve/eve-json-format.html#field-reference
- Quic: https://jasonish-suricata.readthedocs.io/en/evedoc-v4/output/eve/eve-json-format.html#output-reference
- Complete reference: https://jasonish-suricata.readthedocs.io/en/evedoc-v4/appendix/eve-index.html

This Gist show the output of  `./doc/userguide/evedoc.py --flat ./etc/schema.json` which may be useful for correlating logged fields with keywords: https://gist.github.com/jasonish/de5fd130982c0d046c968619a9d2e4e2

### CODE REVIEW

**Review by jufajardini — COMMENTED** [review]
The amount of info is insane, but it's so cool to see this information accessible in a more user-friendly way.

**Comment by jufajardini** [comment]
`make distcheck` the vile enemy of those introducing structural changes to our docs, strikes again 😅

**Comment by jasonish** [comment]
> `make distcheck` the vile enemy of those introducing structural changes to our docs, strikes again 😅

Fixed (but via force-push).

**Comment by victorjulien** [comment]
Generally we don't like checking in generated files. Is it really needed here? If so, what is the workflow to update it?

**Comment by inashivb** [comment]
> Generally we don't like checking in generated files. Is it really needed here?

Generated files are the ones that are going to be rendered here.. so, I'd say, yes. We could choose a diff name if it's confusing.

`make generate` to update the docs from newest schema, I think.

**Comment by jasonish** [comment]
> Generally we don't like checking in generated files. Is it really needed here? If so, what is the workflow to update it?

We haven't been able to successfully make ReadTheDocs and `make dist` happy when on-fly generation. This is why we check-in the generated images from the .msc files, and also why this PR went dormant for so long, gave up trying to make it work.

In the `docs/userguide`, `make generate` will rebuild them. We could do a CI job to fail if they are out of date.

**Pull request closed without merging**
