### PR TITLE
Cherry-pick: profiling: activate when Suricata starts in pcap reader mode

### PR DESCRIPTION
**Pull request by jlucovsky**
Cherry-pick of issue 6550

Link to ticket: https://redmine.openinfosecfoundation.org/issues/6557

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21155

**Review by victorjulien — APPROVED** [review]

**Comment by jlucovsky** [comment]
Continued in #11343

**Comment by jlucovsky** [comment]
Re-opened; pending PR will address rust/clippy warnings.

**Comment by victorjulien** [comment]
Merged in #11348, thanks!

**Pull request closed without merging**
