### PR TITLE
modbus: move parser from c to rust - v7

### PR DESCRIPTION
**Pull request by cccs-sadugas**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- [3957](https://redmine.openinfosecfoundation.org/issues/3957)

Describe changes:
- Changed logging from `LOG_DIR_PACKET` to `LOG_DIR_FLOW`.
- Prefixed functions with `rs_modbus_`.
- Added detection for responses as well.
- Removed unused function `rs_modbus_state_progress_completion_status`.
- Added  `app-layer-modbus.c` C test once again, and fixed some test cases in a separate commit.
  - Fixed the modbus parser to make the `app-layer-modbus.c` tests pass by handling invalid lengths more robustly.
  - `ModbusParserTest05` - `modbus.invalid_protocol_id` no longer supported. If this is required we can be more permissive of what's in the protocol id field instead of failing to parse an invalid protocol id.
  - `ModbusParserTest07`, `ModbusParserTest09`, `ModbusParserTest16`, `ModbusParserTest18` - Return code changed to `AppLayerResult::incomplete()` because the parser will not buffer or discard any data. The resulting transactions are the same.

Todo:
- Line wrap regexes at 100 chars.

Link to parser:
- [sawp-modbus-0.1.1](https://github.com/CybercentreCanada/sawp/blob/sawp-modbus-0.1.1/sawp-modbus/src/lib.rs)

Link to previous PR:
- #5810 

suricata-verify-pr: 411

### CODE REVIEW

**Comment by catenacyber** [comment]
> ModbusParserTest05 - modbus.invalid_protocol_id no longer supported. If this is required we can be more permissive of what's in the protocol id field instead of failing to parse an invalid protocol id.

I did not see the code yet, but I want to point out the way to go
An invalid message should not prevent the parsing of further validation messages...
We can set an app-layer event in these cases.

**Comment by cccs-sadugas** [comment]
I was able to reproduce the build failure and will fix accordingly.

**Comment by cccs-sadugas** [comment]
@catenacyber looking at the output of AddressSanitizer for `ModbusParserTest11` it seems that the test case itself is invalid. Wouldn't passing an `input_len` that goes beyond the `input` buffer result in undefined behaviour (if the buffer is read)?

This modbus PDU is invalid in two ways and the `input_len` is fine:
1. `length - offset == count` : `65530 - 7 == 255` is `false`
2. `quantity <= 125`: `32761 <= 125` is `false`
3. `self.length - offset <= input_len - amount read so far`: `65530 - 7 <= 65536 - 13`: this is okay

The simple fix is to calloc the entire buffer.

**Test Case**
https://github.com/cccs-sadugas/suricata/blob/507f811f9d8be83638e7c2e4793fc65f69929e01/src/app-layer-modbus.c#L1009

```
static uint8_t exceededLengthWriteMultipleRegistersReq[] = {
/* Transaction ID */          0x00, 0x0A,
/* Protocol ID */             0x00, 0x00,
/* Length */                  0xff, 0xfa, // 65530
/* Unit ID */                 0x00,
/* Function code */           0x10,
/* Starting Address */        0x00, 0x01,
/* Quantity of Registers */   0x7f, 0xf9, // 32761
/* Byte count */              0xff // 255
};
```

**AddressSanitizer Output** 
```
ASAN_OPTIONS="detect_leaks=0" ./src/suricata -u -l . -U ModbusParserTest11
Test ModbusParserTest11 - Modbus exceeded Length request          : =================================================================
==23053==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000026d66ed at pc 0x0000008abab7 bp 0x7ffe04c4cf10 sp 0x7ffe04c4c6d0
READ of size 65523 at 0x0000026d66ed thread T0 (Suricata-Main)
    #0 0x8abab6 in memcpy (//suricata/src/suricata+0x8abab6)
    #1 0x1c2cceb in core::intrinsics::copy_nonoverlapping::h2e934988544d5c48 /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/intrinsics.rs:1486:4
    #2 0x1c22ab8 in core::slice::_$LT$impl$u20$$u5b$T$u5d$$GT$::copy_from_slice::h46aee8742a05080f /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/slice/mod.rs:2230:12
    #3 0x1c1fe04 in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$$RF$T$C$core..slice..Iter$LT$T$GT$$GT$$GT$::spec_extend::hf1afe9148eecb4f7 /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/vec.rs:2104:12
    #4 0x1c1ff3e in alloc::vec::Vec$LT$T$GT$::extend_from_slice::h09b8139db5d8ba53 /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/vec.rs:1525:8
    #5 0x1c25718 in alloc::slice::hack::to_vec::h0bd1c5b4c12c60cd /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/slice.rs:159:8
    #6 0x1c256a4 in alloc::slice::_$LT$impl$u20$$u5b$T$u5d$$GT$::to_vec::hb3545fe2c2c6e338 /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/slice.rs:394:8
    #7 0x16b33e1 in sawp_modbus::Message::parse_write_request::h405749bc2349a7cc //.cargo/registry/src/github.com-1ecc6299db9ec823/sawp-modbus-0.1.1/src/lib.rs:717:26
    #8 0x16b4f10 in sawp_modbus::Message::parse_request::h69433efd18561c0a //.cargo/registry/src/github.com-1ecc6299db9ec823/sawp-modbus-0.1.1/src/lib.rs:850:27
    #9 0x16b7851 in _$LT$sawp_modbus..Modbus$u20$as$u20$sawp..parser..Parse$GT$::parse::h391193c585f27554 //.cargo/registry/src/github.com-1ecc6299db9ec823/sawp-modbus-0.1.1/src/lib.rs:1231:35
    #10 0x13bc020 in suricata::modbus::modbus::ModbusState::parse::h74e2ca53bd7c8ccc //suricata/rust/src/modbus/modbus.rs:223:18
    #11 0x13bd451 in rs_modbus_parse_request //suricata/rust/src/modbus/modbus.rs:356:4
    #12 0xa01aac in AppLayerParserParse //suricata/src/app-layer-parser.c:1276:30
    #13 0x9f4abf in ModbusParserTest11 //suricata/src/app-layer-modbus.c:1006:13
   #14 0x10e42b7 in UtRunTests //suricata/src/util-unittest.c:214:23
    #15 0xf20222 in RunUnittests //suricata/src/runmode-unittests.c:274:27
    #16 0x100b4e6 in StartInternalRunMode //suricata/src/suricata.c:2110:13
    #17 0x100697b in SuricataMain //suricata/src/suricata.c:2719:13
    #18 0x93cb98 in main //suricata/src/main.c:22:12
    #19 0x7f5e8003a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #20 0x894d5d in _start (//suricata/src/suricata+0x894d5d)

0x0000026d66ed is located 51 bytes to the left of global variable 'invalidLengthPDUWriteMultipleRegistersReq' defined in 'app-layer-modbus.c:259:16' (0x26d6720) of size 8
0x0000026d66ed is located 0 bytes to the right of global variable 'exceededLengthWriteMultipleRegistersReq' defined in 'app-layer-modbus.c:249:16' (0x26d66e0) of size 13
```

**Comment by catenacyber** [comment]
> Wouldn't passing an input_len that goes beyond the input buffer result in undefined behaviour (if the buffer is read)?

Yes, that seems a wrong use of `AppLayerParserParse`

**Pull request closed without merging**
