### PR TITLE
Detect alert pass 7.0.x/v1

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1945

https://redmine.openinfosecfoundation.org/issues/6674

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21331

**Comment by victorjulien** [comment]
@inashivb can you review this? It's a backport of #11272

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Comment by victorjulien** [comment]
Merged in #11405, thanks!

**Pull request closed without merging**
