### PR TITLE
Threshold flow/v3

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1679

replaces  #10550:
- remove a unused enum addition
- add a few comments explaining types
- document a limitation / future todo on var type tracking

### CODE REVIEW

**Comment by victorjulien** [comment]
Will investigate the UT error.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 18970

**Comment by victorjulien** [comment]
> Will investigate the UT error.

Turned out to be a nasty one https://github.com/OISF/suricata/pull/10582/commits/7f7afcf3f311c052abe37a80e6bcddf2636dca99

**Comment by victorjulien** [comment]
replaced by #10582

**Pull request closed without merging**
