### PR TITLE
Optimize/60x/file handling/v7

### PR DESCRIPTION
**Pull request by victorjulien**
Describe changes:
- file handling cleanups and optimizations

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
Fails due to cocci.

### CODE REVIEW

**Comment by victorjulien** [comment]
@regit any idea why I get this `struct-flags` error?
```
Testing cocci file: /__w/suricata/suricata/qa/coccinelle/struct-flags.cocci
Invalid usage of FileUpdateFlowFileFlags at /__w/suricata/suricata/src/detect.c:431, flags value is incorrect (wrong family).
make[2]: *** [check] Error 1
Makefile:535: recipe for target 'check' failed
make[2]: Leaving directory '/__w/suricata/suricata/qa/coccinelle'
```

**Comment by regit** [comment]
@victorjulien we have a pattern matching on the value so as you pass computationally build value the test is failing. I can try to find a solution but with current script it won't work.

**Comment by victorjulien** [comment]
I see. I thought the tool was smarter, but I guess it just shows I never really understood it. Thanks.

**Comment by victorjulien** [comment]
Replaced by #4536.

**Pull request closed without merging**
