### PR TITLE
log/diag: Support diagnostic stacktraces on unexpected signals

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #6338   
This PR supports configuring Suricata to emit a one-line diagnostic message containing a stacktrace when a signal that terminates Suricata execution (e.g., SIGABRT or SIGSEGV) occurs.

Updates
- Rebase
- 
Requires:
- Removed configuration option; this feature will always be enabled when libunwind is present during configuration
- `libunwind` must be available for when building Suricata
- Enablement in Suricata's configuration file (`logging.stacktrace-on-signal`)

Example output:
```
[1429359] 24/8/2021 -- 10:15:02 - (suricata.c:1108) <Notice> (LogVersion) -- This is Suricata version 7.0.0-dev running in SYSTEM mode
[1429359] 24/8/2021 -- 10:15:02 - (tm-threads.c:2004) <Notice> (TmThreadWaitOnThreadInit) -- Threads created -> W: 16 FM: 1 FR: 1   Engine started.
[1429373] 24/8/2021 -- 10:15:04 - (suricata.c:332) <Error> (SignalHandlerUnexpected) -- [ERRCODE: SC_ERR_SIGNAL(339)] - stacktrace:sig 6:raise+0x000000cb;AFPReadFromRing+0x00000174;ReceiveAFPLoop+0x00000c06;TmThreadsSlotPktAcqLoop+0x00000ca9;start_thread+0x000000d9;clone+0x00000043
Aborted
```
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4526](https://redmine.openinfosecfoundation.org/issues/4526)

Describe changes:
- Default configuration setting changed to `on`.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on tlpw2_autofp_alerts_cmp.
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.memuse | 542075648 | 509179328 | 106.46% |
| | generic_stats_chk |
| .flow.spare | 1967669 | 1866612 | 105.41% | 

Pipeline 5074

**Comment by jasonish** [comment]
In the first commit the message says:
```
Use --enable-libunwind to check for availability. A diagnostic message
    is displayed if libunwind cannot be found as requested.
```
I don't think this is the case.

**Comment by jasonish** [comment]
One other note. This takes precedence over the more useful ASAN stacktrace.  But thats easily dealt with `--set logging.stacktrace-on-signal=false`.

**Comment by jlucovsky** [comment]
> In the first commit the message says:
> 
> ```
> Use --enable-libunwind to check for availability. A diagnostic message
>     is displayed if libunwind cannot be found as requested.
> ```
> 
> I don't think this is the case.

Thanks ... I've updated the commit message and will create a new PR

**Comment by jlucovsky** [comment]
Continued in #6656

**Pull request closed without merging**
