### PR TITLE
Warnint 64to32 6186 v10

### PR DESCRIPTION
**Pull request by catenacyber**
[Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6186

Describe changes:
- fix `-Wshorten-64-to-32` warnings for some files
- Add CI build with this warning

```
LIBHTP_BRANCH=pr/399
```
https://github.com/OISF/libhtp/pull/399

#9512 with fixed compilation with different flags

There must be some stuff to review more carefully

### CODE REVIEW

**Comment by victorjulien** [comment]
Unclean PR, setting to draft.

**Comment by victorjulien** [comment]
The formatting failure is due to the "log: " commit needing the format fixup, not the next "output: " commit. When I run `git rebase master -x 'git clang-format HEAD~'` that is what gets updated.

**Comment by catenacyber** [comment]
> `git rebase master -x 'git clang-format HEAD~'`

Let's try

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/9530

**Pull request closed without merging**
