### PR TITLE
Remove unified2 logging - v1

### PR DESCRIPTION
**Pull request by jasonish**
Removes unified2 logging from Suricata.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2385

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/437
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/793

### CODE REVIEW

**Comment by jlucovsky** [comment]
1src/log-pcap.c` has mention of `unified2`

```
            if (ParseSizeStringU64(s_limit, &pl->size_limit) < 0) {
                SCLogError(SC_ERR_INVALID_ARGUMENT,
                    "Failed to initialize unified2 output, invalid limit: %s",
                    s_limit);
                exit(EXIT_FAILURE);
            }
```

**Comment by victorjulien** [comment]
I think it would be good if we include documentation on how ppl can migrate from u2 to eve, with some tooling examples/suggestions and a mapping between field names/types.

**Comment by jasonish** [comment]
> I think it would be good if we include documentation on how ppl can migrate from u2 to eve, with some tooling examples/suggestions and a mapping between field names/types.

Sure. I'm thinking a section under upgrading, but not really specific to a version.. "Migration from Unified2 to Eve".

Any thoughts on tools? I think many people use unified2 as they are stuck on that old Snort schema and using legacy tools to keep data flowing into that schema. Meer will help here. Other tools are more about revamping your whole infrastructure.  Can suggest Filebeat and Logstash of course.

The other important thing to point out is that you are not losing any resolution of packet data as well.

**Comment by victorjulien** [comment]
Lets turn the documentation into a ticket.

**Comment by jasonish** [comment]
> Lets turn the documentation into a ticket.

https://redmine.openinfosecfoundation.org/issues/3497

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/4596.

**Pull request closed without merging**
