### PR TITLE
qa: generate struct-flags.cocci at each run

### PR DESCRIPTION
**Pull request by regit**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/2852

Describe changes:
- Build cocci file at build time

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/508
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/284

### CODE REVIEW

**Comment by victorjulien** [comment]
Not strictly related to this PR, but do you any idea why this passes in prscript:
```
make[3]: Entering directory '/var/cache/buildbot/slave/regit/build/suricata-5.0.1-dev/_build/sub/qa/coccinelle'
../../../../qa/coccinelle/struct-flags.py > ../../qa/coccinelle/struct-flags.cocci
TOP_SRCDIR=/var/cache/buildbot/slave/regit/build/suricata-5.0.1-dev/_build/sub/../.. ../../../../qa/coccinelle/run_check.sh
Using concurrency level 16
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/access-pkt-packet.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/action-pkt.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/banned-functions.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/direct-packet.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/malloc-error-check.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/pktnotset-packet.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/realloc.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/siginit.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/size_t.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/sz3.cocci
Testing cocci file: /var/cache/buildbot/slave/regit/build/qa/coccinelle/uint.cocci
make[3]: Leaving directory '/var/cache/buildbot/slave/regit/build/suricata-5.0.1-dev/_build/sub/qa/coccinelle'
```
But fails in my testing:
```
make[2]: Entering directory '/builds/inliniac/suricata-ci/suricata/qa/coccinelle'
TOP_SRCDIR=/builds/inliniac/suricata-ci/suricata ../../qa/coccinelle/run_check.sh
Using concurrency level 48
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/access-pkt-packet.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/action-pkt.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/banned-functions.cocci
Banned function 'strndup' used at /builds/inliniac/suricata-ci/suricata/src/util-mem.h:193
make[2]: Leaving directory '/builds/inliniac/suricata-ci/suricata/qa/coccinelle'
make[2]: *** [Makefile:535: check] Error 1
```
Even after I fixup the `strndup` issue, I get:
```
make[2]: Entering directory '/builds/inliniac/suricata-ci/suricata/qa/coccinelle'
./struct-flags.py > ../../qa/coccinelle/struct-flags.cocci
TOP_SRCDIR=/builds/inliniac/suricata-ci/suricata ../../qa/coccinelle/run_check.sh
Using concurrency level 56
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/access-pkt-packet.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/action-pkt.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/banned-functions.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/direct-packet.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/malloc-error-check.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/pktnotset-packet.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/realloc.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/siginit.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/size_t.cocci
Testing cocci file: /builds/inliniac/suricata-ci/suricata/qa/coccinelle/struct-flags.cocci
Invalid usage of flags field at /builds/inliniac/suricata-ci/suricata/src/app-layer-parser.c:1571, flags value is incorrect (wrong family).
make[2]: Leaving directory '/builds/inliniac/suricata-ci/suricata/qa/coccinelle'
make[2]: *** [Makefile:534: check] Error 1
```

**Comment by victorjulien** [comment]
I get the same failure with master btw, so its a more general issue.

**Comment by victorjulien** [comment]
Actually the output from `prscript` shows an anomaly: the `struct-flags.cocci` file is generated but *not tested*.

**Comment by regit** [comment]
OK, found the issue, gonna propose updated version.

**Pull request closed without merging**
