### PR TITLE
Convert unittests to new fail pass api v 2

### PR DESCRIPTION
**Pull request by Nancyenos**
Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [ ] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [ ] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/6935

Describe changes:
-
-converted applayer/htp to new FAIL/PASS API
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by victorjulien** [comment]
Please make sure to create a clean set of git commits, so no merge commits, no commits fixing other commits in the PR, etc.

**Review by victorjulien — CHANGES_REQUESTED** [review]
see inline

Also, please make sure to fill in the PR template correctly.

**Comment by Nancyenos** [comment]
okay well noted..getting on it

**Comment by Nancyenos** [comment]
di i just close this pr?

**Review by Nancyenos — COMMENTED** [review]
dddd

**Comment by jufajardini** [comment]
> do i just close this pr?

I'll answer this as it's useful for future reference ;)
When you have changes requested in a PR, you can leave it open while you work on a new version. Once you have opened a new PR, you can close the older one, with a reference to the follow up PR :)

**Pull request closed without merging**
