### PR TITLE
Backports port grouping/v7

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- https://redmine.openinfosecfoundation.org/issues/6830
- https://redmine.openinfosecfoundation.org/issues/6520
- https://redmine.openinfosecfoundation.org/issues/6829
- https://redmine.openinfosecfoundation.org/issues/6844
- https://redmine.openinfosecfoundation.org/issues/6845
- https://redmine.openinfosecfoundation.org/issues/6895
- https://redmine.openinfosecfoundation.org/issues/6897

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1776

Previous PR: https://github.com/OISF/suricata/pull/10759

Changes since v6:
- rebased on top of latest main-7.0.x

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 646 | 721 | 111.61% | 

Pipeline 20111

**Comment by catenacyber** [comment]
Why is this a draft ?

**Comment by inashivb** [comment]
> Why is this a draft ?

CI is unclean. Need your PR to be merged first and rebase this else this won't be considered for merge.

**Comment by catenacyber** [comment]
CI is unclean, but not because of this PR, I guess this can be marked as ready for review

**Review by catenacyber — APPROVED** [review]
LGTM

This can also be rebased on main-7.0.x with 5267479134d67dcc400008b57e363c8d5aea7b42 to get green CI

**Comment by inashivb** [comment]
> LGTM
> 
> This can also be rebased on main-7.0.x with [5267479](https://github.com/OISF/suricata/commit/5267479134d67dcc400008b57e363c8d5aea7b42) to get green CI

Done in the latest PR

**Pull request closed without merging**
