### PR TITLE
detect/transform: Case changing transform backport to main-7.0.x

### PR DESCRIPTION
**Pull request by jlucovsky**
Add the transforms for changing the case of a buffer. 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6612](https://redmine.openinfosecfoundation.org/issues/6612)

Describe changes:
- Add to_lowercase and to_uppercase transforms

Updates:
- Add transform validation functions to detect incompatible content.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1460
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.tx.pgsql | 0 | 55 | - |
| .app_layer.error.pgsql.parser | 0 | 55 | - | 

Pipeline 16998

**Comment by ct0br0** [comment]
The QA run is fine, just overlap between merging #10020 and this PR running.

**Comment by victorjulien** [comment]
Can you rebase this and reference a open SV PR?

**Comment by jlucovsky** [comment]
Continued in #10035

**Pull request closed without merging**
