### PR TITLE
Enum dir rust/v8

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3832

suricata-verify-pr: 529

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4346

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 6381 e1b59ff1548ae0a48786adf4d6408bde5f02d5f5 bc5eba67bd8a64165eef164785701dfcb4fe6cd2 51db7788deeb04cfdff93df0e01e6fffe701cc25 f05452d9900464319385187fd34496d3cca394e1 045adbc14ed183a6bde553969f85e85c6e3086f0 8773bfa822a564bca8c31ef945ace275060e39f7 20fc3c9e5b3bfeba69408528b6f8b438b8104623 47b652b639256200561250c62b0f5ff172819f1a 8ed4366f3bd583e08c540a495c2f1dca8f2ac96c 58b76c45f867144d407aeb01bb2d3d3da1fe3063 6d2ee8af65051b4cc8d6d4fb34f74ee0bd51697a 587ccb5e01881cb1da8246c95922f972bb81a5ae 1a07a3585e7d57d05870ca27350f8f0e8946745a 55be5ee06d0ab8433b4e7dc6f3f9ef6eebc5c7e9 b4d8c5aef9103d1b9839769caabd23c1981a3e29

**Comment by suricata-qa** [comment]
Information:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .detect.alert | 3091871 | 4051127 | 76.32% |

Pipeline 4346

**Comment by inashivb** [comment]
Replaced w #6577

**Pull request closed without merging**
