### PR TITLE
smtp: Add 535 Code

### PR DESCRIPTION
**Pull request by coalooball**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ V] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [ V] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ V] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- I add SMTP_REPLY_535 in app-layer-smtp.c cause some SMTP server allow multiple AUTH LOGIN. The entire session flow will be interrupted when a AUTH LOGIN failure is encountered if the 535 status code is considered illegal.

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you also create a ticket, then reference the ticket in the commit and generally add the description in the PR into the commit message? Additionally, a test case for Suricata-Verify would be great. Thanks!

**Comment by coalooball** [comment]
> Can you also create a ticket, then reference the ticket in the commit and generally add the description in the PR into the commit message? Additionally, a test case for Suricata-Verify would be great. Thanks!

Sorry, I cant create a account in Suricata issues website for creating a ticket which as the basis for this commit.

I think you can complete all the status codes that an SMTP server might support, to avoid traffic interruption.

**Comment by catenacyber** [comment]
I created https://redmine.openinfosecfoundation.org/issues/6821

**Review by catenacyber — CHANGES_REQUESTED** [review]
Summing up for Github status : needs a better commit message and some SV test

**Comment by catenacyber** [comment]
Superseded by https://github.com/OISF/suricata/pull/11193

**Pull request closed without merging**
