### PR TITLE
dhcp: Log Vendor Class Identifier if present

### PR DESCRIPTION
**Pull request by yatink**
Log Vendor Class Identifier from dhcp packets if present

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4587

Describe changes:
- Update the dhcp parser and logger to log the vendor class identifier if present
- Added a pcap file to test out the parsing changes

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by yatink** [comment]
I need some help. I don't see log output for the vendor_class_identifier in `eve.json` when I run a pcap through suricata directly, using `suricata -c ./suricata.yaml -r <pcap_file> -vv` (after turning on `extended_mode` for the dhcp logger in `suricata.yaml`). I'm not sure whether pcap file input "mode" of suricata uses a different logger which bypasses my changes. Can someone provide assistance ? 

My parser changes work in the unit test setting. There weren't any existing unit tests to validate the logger functionality and I didn't see any obvious way of adding new ones for that module so I haven't been able to test that. 

_Full disclosure, it's been a while since I've written rust so there's a good chance that my changes are "rustic" enough._

**Comment by inashivb** [comment]
Hi ,@yatink! Thank you for your first contribution to our project! :)

> I need some help. I don't see log output for the vendor_class_identifier in `eve.json` when I run a pcap through suricata directly, using `suricata -c ./suricata.yaml -r <pcap_file> -vv` (after turning on `extended_mode` for the dhcp logger in `suricata.yaml`). I'm not sure whether pcap file input "mode" of suricata uses a different logger which bypasses my changes. Can someone provide assistance ?
> 

Could you please create a [suricata-verify test](https://github.com/OISF/suricata-verify/) for this? Usually, that's what we'd add for any changes w.r.t. logging.
Even if it is not working as expected, it'll become easier for us and you to perhaps see what might be missing.

Also, please assign the ticket to yourself in Redmine since you're working on it already.

**Comment by jasonish** [comment]
> I need some help. I don't see log output for the vendor_class_identifier in `eve.json` when I run a pcap through suricata directly, using `suricata -c ./suricata.yaml -r <pcap_file> -vv` (after turning on `extended_mode` for the dhcp logger in `suricata.yaml`). I'm not sure whether pcap file input "mode" of suricata uses a different logger which bypasses my changes. Can someone provide assistance ?

I do, I see:
```
  "dhcp": {
    "type": "request",
    "id": 3759982360,
    "client_mac": "28:cf:da:dc:8d:76",
    "assigned_ip": "0.0.0.0",
    "client_ip": "0.0.0.0",
    "dhcp_type": "request",
    "client_id": "28:cf:da:dc:8d:76",
    "requested_ip": "192.168.1.111",
    "hostname": "NicksMacBook",
    "vendor_class_identifier": "MSFT 5.0",
    "params": [
      "subnet_mask",
      "domain",
      "router",
      "dns_server"
    ]
  }
```
which is expected based on the code.

**Review by jasonish — CHANGES_REQUESTED** [review]
Thanks for the pull request. A few things tho:

- Remove unit test, convert to suricata-verify test.
- In commit message, just prefix with `dhcp`
- assign the ticket to yourself please
- the actual change to dhcp.rs looks OK
- `etc/schema.json` will need an update to the `dhcp` section. This will become apparent with a suricata-verify test

Thanks!

**Comment by jasonish** [comment]
Oh, a rebase should clear up the CI failure as well.

**Comment by yatink** [comment]
> which is expected based on the code.
Thanks for checking ! That confirms that I'm losing my mind 😄 . @jasonish, I'm assuming that you ran suricata with the `-r` option ? I'll recheck. 

@inashivb, I will convert the unit test to a suricata verify test. Thanks for that suggestion.

**Comment by yatink** [comment]
>     * assign the ticket to yourself please

I don't see an option to do so. It's assigned to "Community Ticket" right now and I don't have the privs to be able to reassign it to myself. 


Screenshot 2023-08-14 at 20 20 59

**Comment by jasonish** [comment]
> > ```
> > * assign the ticket to yourself please
> > ```
> 
> I don't see an option to do so. It's assigned to "Community Ticket" right now and I don't have the privs to be able to reassign it to myself. That screenshot is after I've logged in as my user.
> 
> Screenshot 2023-08-14 at 20 20 59

Fixed,  you should be able to self-assign now.

**Comment by jlucovsky** [comment]
Please don't force-push to existing branches for which a PR exists. Instead, create a new branch and PR.

```
git co -b new-branch old-branch
# make changes
git push origin HEAD
```
Then, create a new PR with a reference to the old one (such as "continuation of #nnnn") and close the old one with a message (e.g., "continued in #yyyyy").

**Comment by yatink** [comment]
I'm going to close this PR and reopen...

**Comment by yatink** [comment]
Continued in https://github.com/OISF/suricata/pull/9397

**Pull request closed without merging**
