### PR TITLE
util-misc: Convert unittests to new FAIL/PASS API - v2

### PR DESCRIPTION
**Pull request by hadiqaalamdar**
Task #6345

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6345) ticket
Previous PR https://github.com/OISF/suricata/pull/9655

Describe changes:
- Update `UtilMiscParseSizeStringTest01` in util-misc unit tests

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
The FAIL/PASS conversions look good, but we must address the clang format CI failure: https://github.com/OISF/suricata/actions/runs/6565660693/job/17835769731?pr=9656#step:14:29

We must confirm if the other CI check is related to this PR or not, probably a good idea to wait for the other checks to finish, to get a better idea if there's more to be address :)

**Comment by hadiqaalamdar** [comment]
> We must confirm if the other CI check is related to this PR or not, probably a good idea to wait for the other checks to finish, to get a better idea if there's more to be address :)

Okay, I'll try to run the git clang command and see if that resolves the issue

**Comment by jufajardini** [comment]
> > We must confirm if the other CI check is related to this PR or not, probably a good idea to wait for the other checks to finish, to get a better idea if there's more to be address :)
> 
> Okay, I'll try to run the git clang command and see if that resolves the issue

This will require clang-format, and then you should be able to run `./scripts/clang-format.sh branch` from your suricata directory to apply the needed formatting changes :)

**Comment by hadiqaalamdar** [comment]
Work continued on new PR: https://github.com/OISF/suricata/pull/9661

**Pull request closed without merging**
