### PR TITLE
detect: Use pcre_copy_substring to avoid leaks 

### PR DESCRIPTION
**Pull request by jlucovsky**
Backport of #4590; Requires [Suricata-verify PR #189](https://github.com/OISF/suricata-verify/pull/189)

Fix memory leaks identified during fuzzing that are caused by rule parse errors. A suricata-verify test is in progress.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [3507](https://redmine.openinfosecfoundation.org/issues/3507)

Describe changes:
- Use `pcre_copy_substring` instead of `pcre_get_substring` to avoid memory leaks on parse errors
- Documentation fixup -- misplaced back-tick characters

### CODE REVIEW

**Comment by victorjulien** [comment]
The commits don't have the '(cherry-picked from ... )' lines, is that deliberate?

**Comment by victorjulien** [comment]
QA fails, but its not clear to me why.

**Comment by jlucovsky** [comment]
> The commits don't have the '(cherry-picked from ... )' lines, is that deliberate?

I'll rebuild this PR using `-x` for the cherry-pick.

**Comment by jlucovsky** [comment]
Continued in #4625

**Pull request closed without merging**
