### PR TITLE
Pcre2 3194 v16

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3194
https://redmine.openinfosecfoundation.org/issues/4446

Describe changes:
- migrate all pcre1 code to pcre2
- fuzz: builds fuzz_sigpcap_aware only when asked (ie ./configure --enable-fuzztargets)
- qa : remove some obsolete files
- pcrexform : checks that we have exactly one substring capture in a signature
- transforms : use generic `Free` functions everywhere

suricata-verify-pr: 502

https://github.com/OISF/suricata-verify/pull/502

Replaces https://github.com/OISF/suricata/pull/6142 with rebase now that signature sets got compatible

Should I make a PR with the first 4 preliminary commits ? (like transform: use generic Free function)
The completeness of the commit about `PCRE2_ERROR_UNSET` needs to be carefully reviewed : should it become the generic case ?

Tested with `git cherry-pick 1986aa95278702f78923efc3b7dfb87d64fa5a27` to check that pcre1 is no longer needed

### CODE REVIEW

**Comment by catenacyber** [comment]
Waiting for https://github.com/OISF/suricata/pull/6320 to be merged so that CI works again

**Comment by suricata-qa** [comment]
ERROR: QA failed on generic_cfg.

Pipeline 3987

**Comment by victorjulien** [comment]
> ERROR: QA failed on generic_cfg.
> 
> Pipeline 3987

@ct0br0 is pcre2 installed in our QA setup?

**Comment by ct0br0** [comment]
> > ERROR: QA failed on generic_cfg.
> > Pipeline 3987
> 
> @ct0br0 is pcre2 installed in our QA setup?

Yes. This may be related to the same issue as last time. Will take a look and let @catenacyber know.

**Comment by catenacyber** [comment]
TODO: rebase

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/6330

**Pull request closed without merging**
