### PR TITLE
smb: fix SMB_COM_WRITE_ANDX record parser - v1

### PR DESCRIPTION
**Pull request by b1tg**
Bug: #6008

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

ticket:
https://redmine.openinfosecfoundation.org/issues/6008

pcap to test: https://www.malware-traffic-analysis.net/2018/04/30/2018-04-30-Trickbot-goes-from-client-to-domain-controller.pcap.zip

Describe changes:
- In function parse_smb1_write_andx_request_record, when wct == 12, offset should use 32-bits value rather than stay 0
- I couldn't found pcap which have `multi-part AndX chain with relocated data` (describe in [MS-CIFS].pdf p.247), so there could be edge cases not be handled.
- I couldn't understand the old parse logic of _padding_evasion, seems it not follows [MS-CIFS].pdf

suricata-verify:

https://github.com/OISF/suricata-verify/pull/1195

### CODE REVIEW

**Comment by victorjulien** [comment]
Several issues in CI:
- rust clippy finds issues
- CI fuzz found a way to panic the code

**Comment by b1tg** [comment]
I leave TODO in the code which may cause the crash, I'll fix it in next pr. Could you help answer the questions in this pr description?

**Comment by victorjulien** [comment]
@catenacyber could you have a look at the questions?

**Comment by catenacyber** [comment]
> I couldn't understand the old parse logic of _padding_evasion, seems it not follows [MS-CIFS].pdf

Did you look also at [MS-SMB].pdf
If I remember correctly., some opcodes are described in both, [MS-SMB].pdf presenting a different encoding as an extension, using the word count to differentiate between them

> I couldn't found pcap which have multi-part AndX chain with relocated data (describe in [MS-CIFS].pdf p.247), so there could be edge cases not be handled.

Do S-V tests smb-eicar-padding and smb-eicar-andx help you ?

> Could you help answer the questions in this pr description?

Are there more questions

**Comment by b1tg** [comment]
As for SMB_COM_WRITE_ANDX, the only difference in [MS-SMB]
is the use of SMB_Parameters.Words.Reserved as DataLengthHigh to support 64-bit data length,
and the layout and encoding remain the same as they are in [MS-CIFS].

smb-eicar-andx has a pcap (smbandx.pcap) with andx chain, but Wireshark marks it as "Malformed Packet", maybe Wireshark does not support it either.

Thank you.

**Comment by catenacyber** [comment]
Indeed, Wireshark is evaded... (for smb-eicar-padding as well)
But Windows 10 received the EICAR file

Replaced by https://github.com/OISF/suricata/pull/8839

**Pull request closed without merging**
