### PR TITLE
detect: case-insensitive comparison for requires (7.0.x backport)

### PR DESCRIPTION
**Pull request by jasonish**
Ticket: https://redmine.openinfosecfoundation.org/issues/6700

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Clean cherry-pick, good for me

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17682

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Can you wait with closing/deleting until after the merge?

**Comment by jasonish** [comment]
> Can you wait with closing/deleting until after the merge?

Oops, bad naming of this branch led to premature garbage collection on my end.

**Comment by victorjulien** [comment]
Merged in #10253, thanks!

**Pull request closed without merging**
