### PR TITLE
prelude output: remove

### PR DESCRIPTION
**Pull request by jasonish**

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 4088

**Comment by catenacyber** [comment]
> +4 −1,623

Feels good

Is there a ticket for this ?

**Comment by catenacyber** [comment]
What about #5518 ?

**Comment by suricata-qa** [comment]
WARNING:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.mgr.rows_maxlen | 539 | 404 | 133.42% |
| .detect.alert | 3090589 | 3947262 | 78.3% |

Pipeline 4088

**Comment by jasonish** [comment]
> Is there a ticket for this ?

Just created one: https://redmine.openinfosecfoundation.org/issues/4668

**Comment by jasonish** [comment]
> What about #5518 ?

We've talked about taking something like that for 6.0 but still removing this output in 7.

**Comment by victorjulien** [comment]
Merged as part of #6383, thanks!

**Pull request closed without merging**
