### PR TITLE
Vxlan backport/v1

### PR DESCRIPTION
**Pull request by shivan1b**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3068

### CODE REVIEW

**Comment by shivan1b** [comment]
Victor, should I fix the deprecated item errors in master and here?

**Comment by victorjulien** [comment]
Can you make a single PR out of this and #3986? That should take care of the warnings I think.

**Comment by shivan1b** [comment]
@victorjulien yes. On it.

**Comment by shivan1b** [comment]
Replaced by #3992

**Pull request closed without merging**
