### PR TITLE
fuzz: add target for DecodeBase64

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6050

Previous PR: https://github.com/OISF/suricata/pull/10954

Changes since v8:
- clean up history
- issues after rebase fixed

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20354

**Comment by catenacyber** [comment]
This looks good.
Could you rebase to get green CI ?
Have you run the target yourself for a few minutes ?

**Comment by inashivb** [comment]
> This looks good. Could you rebase to get green CI ? Have you run the target yourself for a few minutes ?

No. I haven't set it up locally. Does CIFuzz job not do that?

**Comment by catenacyber** [comment]
Not sure CIFuzz handles new targets, did you check the job's log output ?

**Comment by inashivb** [comment]
> Not sure CIFuzz handles new targets, did you check the job's log output ?

I did. I couldn't find any other log of this target than
```
2024-04-25T13:49:09.8495313Z 2024-04-25 13:49:09,847 - root - DEBUG - Diffing against base_ref: master.
2024-04-25T13:49:09.8495906Z 2024-04-25 13:49:09,847 - root - INFO - Diffing against master.
2024-04-25T13:49:09.8524323Z 2024-04-25 13:49:09,851 - root - INFO - Files changed in PR: ['src/Makefile.am', 'src/tests/fuzz/fuzz_decodebase64.c']
```

This means it wasn't run? I'll build it locally nonetheless. Thank you!

**Comment by catenacyber** [comment]
Looks like it was not run cf https://github.com/OISF/suricata/actions/runs/8833562347/job/24253165722?pr=10955#step:6:31

**Comment by catenacyber** [comment]
> 2024-04-25 14:09:32,551 - root - INFO - Fuzz targets: ['/github/workspace/build-out/fuzz_applayerparserparse_imap', '/github/workspace/build-out/fuzz_applayerparserparse_websocket', '/github/workspace/build-out/fuzz_applayerparserparse_quic', '/github/workspace/build-out/fuzz_mimedecparseline', '/github/workspace/build-out/fuzz_applayerparserparse_ftp-data', '/github/workspace/build-out/fuzz_applayerparserparse_http', '/github/workspace/build-out/fuzz_applayerparserparse_dns', '/github/workspace/build-out/fuzz_applayerparserparse_mqtt', '/github/workspace/build-out/fuzz_applayerparserparse_ftp', '/github/workspace/build-out/fuzz_applayerparserparse_snmp', '/github/workspace/build-out/fuzz_applayerparserparse_rdp', '/github/workspace/build-out/fuzz_applayerparserparse_dhcp', '/github/workspace/build-out/fuzz_applayerparserparse_tftp', '/github/workspace/build-out/fuzz_siginit', '/github/workspace/build-out/fuzz_applayerparserparse_ssh', '/github/workspace/build-out/fuzz_applayerparserparse_ike', '/github/workspace/build-out/fuzz_confyamlloadstring', '/github/workspace/build-out/fuzz_predefpcap_aware', '/github/workspace/build-out/fuzz_applayerparserparse_krb5', '/github/workspace/build-out/fuzz_sigpcap', '/github/workspace/build-out/fuzz_applayerparserparse_http2', '/github/workspace/build-out/fuzz_applayerparserparse_ntp', '/github/workspace/build-out/fuzz_applayerparserparse_sip', '/github/workspace/build-out/fuzz_applayerparserparse_telnet', '/github/workspace/build-out/fuzz_applayerparserparse_modbus', '/github/workspace/build-out/fuzz_applayerparserparse_dnp3', '/github/workspace/build-out/fuzz_applayerparserparse_pgsql', '/github/workspace/build-out/fuzz_applayerparserparse', '/github/workspace/build-out/fuzz_applayerparserparse_tls', '/github/workspace/build-out/fuzz_sigpcap_aware', '/github/workspace/build-out/fuzz_applayerparserparse_nfs', '/github/workspace/build-out/fuzz_decodepcapfile', '/github/workspace/build-out/fuzz_applayerparserparse_dcerpc', '/github/workspace/build-out/fuzz_applayerparserparse_enip', '/github/workspace/build-out/fuzz_applayerparserparse_rfb', '/github/workspace/build-out/fuzz_applayerparserparse_smb', '/github/workspace/build-out/fuzz_applayerparserparse_bittorrent-dht', '/github/workspace/build-out/fuzz_applayerprotodetectgetproto', '/github/workspace/build-out/fuzz_applayerparserparse_smtp']

**Pull request closed without merging**
