### PR TITLE
logging: Anomaly logging 

### PR DESCRIPTION
**Pull request by jlucovsky**
This changeset adds anomaly logging to suricata for [issue 2282](https://redmine.openinfosecfoundation.org/issues/2282)

Anomaly logging is controlled via the anomaly section within eve-log.
There is a single option -- packethdr -- for including the packet header
in the anomaly.

Note: continuation of #3784

Example output

Packet hdr logging off:
```json
{"timestamp":"1969-12-31T16:00:03.000000-0800","anomaly":{"event":"decoder.ipv4.wrong_ip_version"}}
{"timestamp":"1969-12-31T16:00:04.000000-0800","pcap_cnt":25,"event_type":"anomaly","src_ip":"208.21.2.184","src_port":0,"dest_ip":"10.1.1.99","dest_port":0,"proto":"UDP","anomaly":{"event":"decoder.udp.pkt_too_small"}}
{"timestamp":"1969-12-31T16:00:04.000000-0800","flow_id":576663784259584,"pcap_cnt":27,"event_type":"anomaly","src_ip":"204.252.102.11","dest_ip":"206.65.98.18","proto":"ICMP","icmp_type":50,"icmp_code":34,"anomaly":{"event":"decoder.icmpv4.unknown_type"}}
```
Packet hdr logging enabled:
```
{"timestamp":"1969-12-31T16:00:03.000000-0800","packethdr":"FF FF FF FF FF FF 01 01 01 01 01 01 08 00 D8 6A 97 67 51 15 EE 99 14 76 A7 1C 8C 17 66 77 D3 72 ","linktype":1,"anomaly":{"event":"decoder.ipv4.wrong_ip_version"}}
{"timestamp":"1969-12-31T16:00:04.000000-0800","pcap_cnt":25,"event_type":"anomaly","src_ip":"208.21.2.184","src_port":0,"dest_ip":"10.1.1.99","dest_port":0,"proto":"UDP","packethdr":"FF FF FF FF FF FF 01 01 01 01 01 01 08 00 45 00 00 3C C5 9E 40 00 FF 11 D7 E0 D0 15 02 B8 0A 01 ","linktype":1,"anomaly":{"event":"decoder.udp.pkt_too_small"}}
{"timestamp":"1969-12-31T16:00:04.000000-0800","flow_id":1392241566547968,"pcap_cnt":27,"event_type":"anomaly","src_ip":"204.252.102.11","dest_ip":"206.65.98.18","proto":"ICMP","icmp_type":50,"icmp_code":34,"packethdr":"FF FF FF FF FF FF 01 01 01 01 01 01 08 00 45 00 00 54 8F B3 40 00 FD 01 8A 99 CC FC 66 0B CE 41 ","linktype":1,"anomaly":{"event":"decoder.icmpv4.unknown_type"}}
```

### CODE REVIEW

**Comment by victorjulien** [comment]
Looks like adding the linktype is still a todo?

**Comment by victorjulien** [comment]
I think it would be good to have a bunch of verify tests for this feature.

**Comment by jlucovsky** [comment]
Check line 117 of output-jason-anomaly.c

**Comment by victorjulien** [comment]
It is missing from the example output in this PR, could you update that?

**Comment by jmtaylor90** [comment]
Thanks for the work on this! I ran some pcap through and was wondering if the following entries are expected or how I would further investigate eve entries like this?

{"timestamp":"2019-04-05T14:09:21.485411-0400","flow_id":1764521173565304,"pcap_cnt":106,"event_type":"anomaly","src_ip":"10.2.2.2","src_port":58235,"dest_ip":"10.1.1.1","dest_port":8080,"proto":"TCP","linktype":1,"anomaly":{"event":"Unknown(168)"},"host":"jttest"}

I can provide pcap privately.

**Comment by jlucovsky** [comment]
Could you provide the output of `suricata --build-info`?

`master` has 170 entries in the table from which the event tag/description is taken. I suspect your base may be behind?

The event tag is taken from https://github.com/OISF/suricata/blame/master/src/decode-events.h#L274

Let's check this before we try anything else.

**Comment by jlucovsky** [comment]
> It is missing from the example output in this PR, could you update that?

Updated.

**Comment by jlucovsky** [comment]
> I think it would be good to have a bunch of verify tests for this feature.

Will add and post the PR number for the `suricata-verify` test.

**Comment by jlucovsky** [comment]
Continued in #3801

**Comment by jmtaylor90** [comment]
> Could you provide the output of `suricata --build-info`?
> 
> `master` has 170 entries in the table from which the event tag/description is taken. I suspect your base may be behind?
> 
> The event tag is taken from https://github.com/OISF/suricata/blame/master/src/decode-events.h#L274
> 
> Let's check this before we try anything else.
[suri.buildinfo.txt](https://github.com/OISF/suricata/files/3087289/suri.buildinfo.txt)

I cloned/built against your weird.4 branch. If that was a mistake or incorrect just let me know.

**Comment by jlucovsky** [comment]
> > Could you provide the output of `suricata --build-info`?
> > `master` has 170 entries in the table from which the event tag/description is taken. I suspect your base may be behind?
> > The event tag is taken from https://github.com/OISF/suricata/blame/master/src/decode-events.h#L274
> > Let's check this before we try anything else.
> > [suri.buildinfo.txt](https://github.com/OISF/suricata/files/3087289/suri.buildinfo.txt)
> 
> I cloned/built against your weird.4 branch. If that was a mistake or incorrect just let me know.

That should be ok provided everything was rebuilt properly. Providing the output of `suricata --build-info` would be helpful.

**Pull request closed without merging**
