### PR TITLE
Http uri spaces 2881 v12

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2881

Describe changes:
- configures libhtp to allow spaces in URIs

Modifies #7915 with rebase

suricata-verify-pr: 837

https://github.com/OISF/suricata-verify/pull/837

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 ERROR: Invalid Signature config error in ASAN_TLPR1_cfg QA test

ERROR: QA failed on ASAN_TLPR1_cfg.
  

Pipeline 10346

**Comment by victorjulien** [comment]
Waiting for rule rebaseline in QA

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 104031 | 81.12% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 1853775 | - |
| .flow.end.state.new | 6272 | 17625 | 281.01% |
| .flow.end.tcp_state.syn_sent | 0 | 3665 | - |
| .flow.end.tcp_state.syn_recv | 0 | 48 | - |
| .flow.end.tcp_state.established | 53996 | 61081 | 113.12% |
| .flow.end.tcp_state.fin_wait1 | 0 | 450 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 165 | - |
| .flow.end.tcp_state.time_wait | 0 | 237 | - |
| .flow.end.tcp_state.last_ack | 0 | 142 | - |
| .flow.end.tcp_state.close_wait | 0 | 620 | - |
| .flow.end.tcp_liberal | 80952 | 139414 | 172.22% |
| .tcp.reassembly_gap | 80952 | 292536 | 361.37% |
| .tcp.overlap | 0 | 22 | - |
| .app_layer.error.http.parser | 0 | 200 | - |
| .app_layer.error.ftp.gap | 0 | 34 | - |
| .app_layer.error.smtp.gap | 0 | 308 | - |
| .app_layer.error.tls.gap | 53852 | 104818 | 194.64% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 131 | - |
| .ftp.memuse | 0 | 128 | - | 

Pipeline 10347

**Comment by ct0br0** [comment]
Looks like both of the runs (QA and manual) have the same increased alert count. Should be good, just will need to update QA baseline after merge.

**Comment by victorjulien** [comment]
Merged in #8165, thanks!

**Comment by catenacyber** [comment]
Actually, this was not merged

**Comment by victorjulien** [comment]
> Actually, this was not merged

Whoops, sorry about that. Looks like there was an issue with a pcap I shared privately. Forgot about it.

**Comment by catenacyber** [comment]
> > Actually, this was not merged
> 
> Whoops, sorry about that. Looks like there was an issue with a pcap I shared privately. Forgot about it.

Indeed, it requires new https://github.com/OISF/libhtp/pull/371

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8169

**Pull request closed without merging**
