### PR TITLE
Output alert applayer v21.1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
https://redmine.openinfosecfoundation.org/issues/3827
Preliminary work for https://redmine.openinfosecfoundation.org/issues/5053

Describe changes:
- output: unify boilerplate code (trying to become a lines-of-code neutral contributor to Suricata ;-) and rising the percentage of rust files )
- output/dns: do not add empty app-layer metadata
- dnp3: restrict function scope to one file

#10300 with keeping the logging direction for each app-layer protocol

does not need SV PR

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 18159

**Comment by ct0br0** [comment]
We've been reworking things but I'm assuming the QA job is accurate. Will check tomorrow.

**Comment by catenacyber** [comment]
There is supposedly no changes to detection here.
How can I reproduce QA deviation ? Or trigger a rerun ?

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/10370

**Pull request closed without merging**
