### PR TITLE
Threshold rework + cache/v8

### PR DESCRIPTION
**Pull request by victorjulien**
Reimplement threshold storage and add a thread local cache, both to reduce lock contention.

https://redmine.openinfosecfoundation.org/issues/426
https://redmine.openinfosecfoundation.org/issues/6967

Replaces #10916 and #9488.

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
  

Pipeline 20217

**Comment by catenacyber** [comment]
What is the relationship with #10910 ?

They look like conflicting at least for src/detect-engine-threshold.c

So, which one should get first ?

**Comment by victorjulien** [comment]
> What is the relationship with #10910 ?
> 
> They look like conflicting at least for src/detect-engine-threshold.c
> 
> So, which one should get first ?

https://github.com/OISF/suricata/pull/10916#issuecomment-2066122797

**Comment by victorjulien** [comment]
replaced by #11024

**Pull request closed without merging**
