### PR TITLE
Output alert applayer v17.2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
https://redmine.openinfosecfoundation.org/issues/3827
https://redmine.openinfosecfoundation.org/issues/5053

Describe changes: 
- https://github.com/OISF/suricata/pull/9870 +
- app-layer plugins

#9812 rebased

```
SV_BRANCH=pr/1490
```
https://github.com/OISF/suricata-verify/pull/1490

### CODE REVIEW

**Comment by catenacyber** [comment]
How can this CI failure be in only one build ?
having `"(null)"` in json output for `app_layer.error.(null).gap` and `app_layer.flow.(null)` (but not for tx)

**Comment by catenacyber** [comment]
Retrying CI without latest d993f43d6eb2c2e9a4a837c41f4cc1ccf2383743

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16707

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 184 | 194 | 105.43% | 

Pipeline 16710

**Comment by catenacyber** [comment]
Current status : wait for merge of first commits in https://github.com/OISF/suricata/pull/10166

@jasonish did you have more questions about this branch for app-layer plugins ?

**Pull request closed without merging**
