### PR TITLE
detect/analyzer: add more details for the flowbits keyword v1

### PR DESCRIPTION
**Pull request by hadiqaalamdar**
Task #6309

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6309) ticket:

Describe changes:
- Added the DETECT_FLOWBITS case to detect-engine-analyzer.c

Request Feedback:
- Am I on the right track?
- The tests I wrote are failing but I've shared my code to see how I can change it.

test.rules:
```
alert ip any any -> any any (msg:"isset rule need an option"; flowbits:isset; sid:1;)
alert ip any any -> any any (msg:"isnotset rule need an option"; flowbits:isnotset; sid:2)
alert ip any any -> any any (msg:"set rule need an option"; flowbits:set; sid:3;)
alert ip any any -> any any (msg:"unset rule need an option"; flowbits:unset; sid:4;)
alert ip any any -> any any (msg:"toggle rule need an option"; flowbits:toggle; sid:5;)
```
test.yaml
```
requires:
    min-version: 7.0.0
    pcap: false

args:
    - --engine-analysis

checks:
- filter:
    filename: rules.json
    count: 1
    match:
      id: 1
      lists.packet.matches[0].name: "flowbits"
      lists.packet.matches[0].flowbits.option: "isset"
- filter:
    filename: rules.json
    count: 1
    match:
      id: 2
      lists.packet.matches[0].name: "flowbits"
      lists.packet.matches[0].flowbits.option: "isnotset"
- filter:
    filename: rules.json
    count: 1
    match:
      id: 3
      lists.packet.matches[0].name: "flowbits"
      lists.packet.matches[0].flowbits.option: "set"
- filter:
    filename: rules.json
    count: 1
    match:
      id: 4
      lists.packet.matches[0].name: "flowbits"
      lists.packet.matches[0].flowbits.option: "unset"
- filter:
    filename: rules.json
    count: 1
    match:
      id: 5
      lists.packet.matches[0].name: "flowbits"
      lists.packet.matches[0].flowbits.option: "toggle"

```

### CODE REVIEW

**Comment by jufajardini** [comment]
Hi, it is easier for us to review SV tests if you submit them as an SV PR - also because then you can list it in your Suricata PR, and our CI checks will run them and show us the results. Could you please do that, for this contribution?

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hi there, good job you are on the right path, there's some work to be done, indeed.

A couple of overall things that require change, to give you a heads-up:
- can you please ensure that the commit message is within the 50-character limit? I think that if you drop `keyword` it would stay within limit
- Can you add some explanation to the commit body, too, to make the message a bit more complete? Thanks a lot :)

Now, about the code:

The flowbits keyword defines or handles a flow variable, and as such is composed of two parts, for most cases (as seen here - https://docs.suricata.io/en/latest/rules/flow-keywords.html#flowbits). So, we should also log the flowbits variable name.

For that name, from the code here  https://github.com/OISF/suricata/blob/master/src/detect-flowbits.c#L123-L124 and from rules such as the ones on this test https://github.com/OISF/suricata-verify/blob/master/tests/bug-1045/smtp.rules, we learn that can be actually a list of variables. In the struct (https://github.com/OISF/suricata/blob/master/src/detect-flowbits.h#L36) `DetectFlowbitsData.or_list_size` will indicate how many flowbits variables are defined for a rule, and then `DetectFlowbitsData.or_list` will have all variable stored. If we have a list of variables, then `DetectFlowbitsData.idx` will store the corresponding index to be checked on the list indicated before, I'm grasping.

Does this info help with you knowing how to move forward?

I'll ask for @inashivb to review the explanation above, though, as I know she has worked with flowbits code before, and I haven't, so I may have gotten some stuff wrong.

**Comment by inashivb** [comment]
> The flowbits keyword defines or handles a flow variable, and as such is composed of two parts, for most cases (as seen here - https://docs.suricata.io/en/latest/rules/flow-keywords.html#flowbits). So, we should also log the flowbits variable name.
> 
Agreed. We should log the flowbit names.

> For that name, from the code here https://github.com/OISF/suricata/blob/master/src/detect-flowbits.c#L123-L124 and from rules such as the ones on this test https://github.com/OISF/suricata-verify/blob/master/tests/bug-1045/smtp.rules, we learn that can be actually a list of variables. In the struct (https://github.com/OISF/suricata/blob/master/src/detect-flowbits.h#L36) `DetectFlowbitsData.or_list_size` will indicate how many flowbits variables are defined for a rule, and then `DetectFlowbitsData.or_list` will have all variable stored. If we have a list of variables, then `DetectFlowbitsData.idx` will store the corresponding index to be checked on the list indicated before, I'm grasping.
> 
Yes, but this is only in the case of or operator in flowbits. So, one can check for `or_list_size` and if it's greater than 0, a list of names should be logged. e.g. https://github.com/OISF/suricata-verify/blob/master/tests/detect-flowbits/test.rules#L3
Separate flowbits like the ones mentioned in smtp.rules example above would be separate objects.

This is a good indicator of including both such rules in the s-v tests that you do. 😉

**Comment by hadiqaalamdar** [comment]
> In the struct (https://github.com/OISF/suricata/blob/master/src/detect-flowbits.h#L36) `DetectFlowbitsData.or_list_size` will indicate how many flowbits variables are defined for a rule, and then `DetectFlowbitsData.or_list` will have all variable stored. If we have a list of variables, then `DetectFlowbitsData.idx` will store the corresponding index to be checked on the list indicated before, I'm grasping.

1. Should I add or_list, or_list_size and idx to the DETECT_FLOWBITS case?
2. Will `jb_set_uint(js, "name", cd->or_list[idx]);` display the variable name? 
3. Does the switch statements I added to find the cmd look good or should I make any edits?

cc: @inashivb @jufajardini

**Comment by jufajardini** [comment]
> > In the struct (https://github.com/OISF/suricata/blob/master/src/detect-flowbits.h#L36) `DetectFlowbitsData.or_list_size` will indicate how many flowbits variables are defined for a rule, and then `DetectFlowbitsData.or_list` will have all variable stored. If we have a list of variables, then `DetectFlowbitsData.idx` will store the corresponding index to be checked on the list indicated before, I'm grasping.
> 
> 1. Should I add or_list, or_list_size and idx to the DETECT_FLOWBITS case?

You'll have to work with those to find the info that you need to be logged in the `DETECT_FLOWBITS` case

> 2. Will `jb_set_uint(js, "name", cd->or_list[idx]);` display the variable name?
No, `jb_set_uint` is used for logging an unsigned integer. As you've done for the `cmd` bit, we should log a string, here. From what Shivani said, I think that you should check if size is greater than 0, and then decide if it you'll have to use idx or just the first index to access the name. Should be easy to test and see, right?

> 3. Do the switch statements I added to find the cmd look good or should I make any edits?
This will have to be double-tested with the SV PR, but from what I saw, it looks good.

**Comment by hadiqaalamdar** [comment]
new PR: https://github.com/OISF/suricata/pull/9685

**Pull request closed without merging**
