### PR TITLE
Iprep/70x/v1

### PR DESCRIPTION
**Pull request by victorjulien**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1814

https://redmine.openinfosecfoundation.org/issues/6986

### CODE REVIEW

**Comment by catenacyber** [comment]
Backport of #11000 for reference

**Review by catenacyber — APPROVED** [review]
Looks like a good backport of #11000 , with a simple conflict fixed ok

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20469

**Review by jasonish — APPROVED** [review]

**Review by jufajardini — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11016, thanks!

**Pull request merged**
