### PR TITLE
github-ci: add eBPF to the builds workflow

### PR DESCRIPTION
**Pull request by lukashino**
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6602) ticket: https://redmine.openinfosecfoundation.org/issues/6602

Describe changes:
- added ebpf dependencies
- added configure flag to enable ebpf build

### CODE REVIEW

**Comment by catenacyber** [comment]
What is done in master with regards to this ?

**Comment by catenacyber** [comment]
Did you cherry pick a commit ? With `-x` ?

**Comment by lukashino** [comment]
No, I did a manual merge because I feared that it might cause too many conflicts. I can add a commit id though if that's desired for porting commits from the old Suri version branch to the new one.

**Review by victorjulien — APPROVED** [review]
Good as is, the cherry-pick line is more important for code changes.

**Comment by victorjulien** [comment]
Merged in #10213, thanks!

**Pull request closed without merging**
