### PR TITLE
Applayer plugin 5053 v2.7

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
Preliminary work for https://redmine.openinfosecfoundation.org/issues/5053

Describe changes:
- get ready to use dynamic number of app-layer protos for some global arrays : run modes and output

Small PR that should be good in itself.

#11373 next round

Based on #11473 with cleaner history, waiting for CI

Still more work to do : I guess stack allocated arrays are fine, but the global variables cf `git grep '\[ALPROTO_MAX'`  in
- app-layer-detect-proto.c
- app-layer-frames.c
- app-layer-parser.c
- app-layer-protos.c
- app-layer.c
need to be allocated and freed, with taking care of the initialization order, so that we know `ALPROTO_MAX` final value...

### CODE REVIEW

**Comment by catenacyber** [comment]
Pushing a fixup commit to fix the leak in engine-analysis mode

It looks like this leak was preexisting, but not detected as long as the pointers lived in a global structure

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21582

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on SURI_TLPW1_suri_time.
  

Pipeline 21598

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata/pull/11532

**Pull request closed without merging**
