### PR TITLE
smb: fix SMB_COM_WRITE_ANDX record parser - v5

### PR DESCRIPTION
**Pull request by b1tg**
Bug: #6008

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

ticket:
https://redmine.openinfosecfoundation.org/issues/6008

Previous PR: https://github.com/OISF/suricata/pull/8905

Changes from last PR:
- update commit message
- remove duplicated tests

SV_BRANCH=pr/1211

### CODE REVIEW

**Comment by victorjulien** [comment]
When staged in #8941/#8942, our internal QA flagged several issues in private tests. We're working on investigating them. Thanks for your patience.

**Comment by catenacyber** [comment]
@ct0br0 Can we run QA on this PR ?
To me, the changes look correct

**Comment by ct0br0** [comment]
What changed? I got the pcaps the other day and I think I saw you say they checked out. Can run but expect a false failure.

**Comment by catenacyber** [comment]
> What changed?

Nothing, but there is no QA report in this GitHub PR (there was one on the newt branch)

**Comment by ct0br0** [comment]
No, there won't be. Since it is not a team member it will not go into the automated pipeline and qa-bot won't comment on this PR

**Comment by catenacyber** [comment]
Ok I did not know this :-)

**Comment by victorjulien** [comment]
Merged in #8965, thanks a lot for this fix!

**Pull request closed without merging**
