### PR TITLE
Smb work sn v1.2

### PR DESCRIPTION
**Pull request by regit**
Update of #7585 with rebase and addressing comments.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- rebase
- Change smb status function type
- fix commit message

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 126063 | 102867 | 81.6% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 152739 | - |
| .flow.end.state.new | 6272 | 7237 | 115.39% |
| .flow.end.tcp_state.syn_sent | 0 | 360 | - |
| .flow.end.tcp_state.syn_recv | 0 | 8 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 49 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 23 | - |
| .flow.end.tcp_state.time_wait | 0 | 34 | - |
| .flow.end.tcp_state.last_ack | 0 | 23 | - |
| .flow.end.tcp_state.close_wait | 0 | 84 | - |
| .flow.end.tcp_liberal | 80952 | 92894 | 114.75% |
| .tcp.reassembly_gap | 80952 | 114366 | 141.28% |
| .tcp.overlap | 0 | 10 | - |
| .app_layer.error.http.parser | 0 | 49 | - |
| .app_layer.error.ftp.gap | 0 | 4 | - |
| .app_layer.error.smtp.gap | 0 | 57 | - |
| .app_layer.error.tls.gap | 53852 | 64470 | 119.72% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 30 | - | 

Pipeline 9463

**Comment by jufajardini** [comment]
Should/could we update sv tests smb2-02 and smb2-03 to include rules with those keywords?

(mentioning those as I see those in our eve outputs there)

**Review by jufajardini — APPROVED** [review]
Doc page looks good to me.

Assigned existing corresponding ticket to you: https://redmine.openinfosecfoundation.org/issues/3030

**Review by victorjulien — CHANGES_REQUESTED** [review]
Needs fixes, check CI

**Pull request closed without merging**
