### PR TITLE
output: adds schema.json

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1369

Describe changes:
- Adds schema.json describing all output fields

So that S-V checks that all fields are present

suricata-verify-pr: 827

cc @jasonish 

Follows #7406 with comments taken into account (thanks for the nice etc tip)

### CODE REVIEW

**Comment by jasonish** [comment]
Added missing fields here: https://github.com/OISF/suricata/pull/7412

**Comment by catenacyber** [comment]
How did you find them ?

**Comment by jasonish** [comment]
> How did you find them ?

These were failing for me when I ran against master due to additional fields not allowed.

**Comment by catenacyber** [comment]
I wonder why CI did not catch them in https://github.com/OISF/suricata/pull/7407

Is CI missing some config options ?

**Comment by jasonish** [comment]
I don't think check-eve was every being run in CI.

**Comment by catenacyber** [comment]
🤔 it had failed before IIRC...

**Pull request closed without merging**
