### PR TITLE
bittorrent-dht: add bittorrent-dht app-layer parser - v9

### PR DESCRIPTION
**Pull request by jasonish**
Parses and logs the bittorrent-dht protocol. 

Feature: https://redmine.openinfosecfoundation.org/issues/3086

Previous PR: https://github.com/OISF/suricata/pull/7731

Changes since last PR:
- parse value lists into a list of peer data structures
- add nodes6 parsing for lists of ipv6 nodes
- log nodes and peers more like wireshark

Reference BitTorrent DHT specification:
https://www.bittorrent.org/beps/bep_0005.html

TODO:
- Revisit documentation

suricata-verify-pr: 930

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on report_failure.

ERROR: QA failed on tlpr1_asan_suri.
  

Pipeline 9050

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on report_failure.

ERROR: QA failed on tlpr1_asan_suri.
  

Pipeline 9051

**Review by jufajardini — COMMENTED** [review]
Documentation is good to me!

I noticed that the newly added files have the copyright year as 2021, though...

**Comment by jasonish** [comment]
> I noticed that the newly added files have the copyright year as 2021, though...

Yeah, the PR is from 2021, its been in review for a long time.

**Comment by jufajardini** [comment]
> > I noticed that the newly added files have the copyright year as 2021, though...
> 
> Yeah, the PR is from 2021, its been in review for a long time.

missed that bit, sorry 😅

**Comment by victorjulien** [comment]
CIFuzz found ways to panic the rust code.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .tcp.rst | 103033 | 125984 | 122.28% | 

Pipeline 9100

**Comment by jasonish** [comment]
Rebased: https://github.com/OISF/suricata/pull/8102

**Pull request closed without merging**
