### PR TITLE
ci: adds CodeQL workflow and LGTM support

### PR DESCRIPTION
**Pull request by Yonah125**
@catenacyber

Link to redmine ticket:
None

Updated lgtm.yml and codeql.yml so :
-Suricata will works on LGTM
-Codeql workflow for C will successfully run

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Looks good to me, thanks

**Comment by victorjulien** [comment]
Maybe something like https://github.com/OISF/suricata/blob/master/.github/workflows/builds.yml#L714

**Comment by Yonah125** [comment]
> Maybe something like https://github.com/OISF/suricata/blob/master/.github/workflows/builds.yml#L714

Very strange, I added it but it still fails, any idea ?

**Comment by catenacyber** [comment]
This is some codecov specifics. You should look in the Github Workflow documentation for the right syntax ;-)

**Comment by catenacyber** [comment]
@Yonah125 we forgot to talk about this.

Did you check https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#defining-the-severities-causing-pull-request-check-failure ?

**Comment by Yonah125** [comment]
> @Yonah125 we forgot to talk about this.
> 
> Did you check https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#defining-the-severities-causing-pull-request-check-failure ?

Just changed it to only critical, might work now

**Comment by Yonah125** [comment]
> @Yonah125 we forgot to talk about this.
> 
> Did you check https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#defining-the-severities-causing-pull-request-check-failure ?

So it must be changed on this repository, not on my fork, right ?

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7246

**Pull request closed without merging**
