### PR TITLE
Tls ja3 avoid null buffer error log

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/6634

Describe changes:
- tls/ja3 : avoid null buffer error log

@lukashino how does this look ?

### CODE REVIEW

**Comment by lukashino** [comment]
Looks good from my side!

**Comment by catenacyber** [comment]
>> What is the error log that is referenced here?
> Buffer should not be NULL

To be precise : https://github.com/OISF/suricata/blob/master/src/util-ja3.c#L175

(We could turn it into a debug assertion)

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11823, thanks!

**Comment by jufajardini** [comment]
I think that this addresses https://redmine.openinfosecfoundation.org/issues/7256

**Pull request closed without merging**
