### PR TITLE
Feature: extract message body for smtp protocol

### PR DESCRIPTION
**Pull request by superway117**
- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5737) ticket

Describe changes:
- extract body message from smtp  protocol
- enable or disable to extract smtp body message in suricata.yaml.in
- enable or disable to save smtp body message to eve-log in suricata.yaml.in

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hello, thanks for your interest in contributing to our project.

Can you check the CI failures?
Once you address them and are ready to submit a new PR, please also make sure to follow our guidelines for code submission, especially regarding commit messages and how to separate changes into commits: https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/code-submission-process.html

This will make the reviewing process easier from our end ;)

**Comment by jufajardini** [comment]
Hello @superway117, did you close this PR on purpose?

**Comment by superway117** [comment]
sorry for that , i just want to redo it.

**Comment by superway117** [comment]
new PR is  https://github.com/OISF/suricata/pull/8303

**Pull request closed without merging**
