### PR TITLE
doc: add tls.cert_chain_len docs

### PR DESCRIPTION
**Pull request by jmtaylor90**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

https://redmine.openinfosecfoundation.org/issues/6386

Describe changes:
- 
-
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by jmtaylor90** [comment]
The code work was done under https://redmine.openinfosecfoundation.org/issues/5191 / https://github.com/OISF/suricata/pull/7884/commits/682e2a07fec0ee705ef67befe72c1849843f4375 it looks like the documentation was missed. So this is the associated doc work. Do we need a new redmine for this?

**Comment by inashivb** [comment]
> The code work was done under https://redmine.openinfosecfoundation.org/issues/5191 / [682e2a0](https://github.com/OISF/suricata/commit/682e2a07fec0ee705ef67befe72c1849843f4375) it looks like the documentation was missed. So this is the associated doc work. Do we need a new redmine for this?

Looking at other Documentation tickets, I'd say yes. Preferably as a subtask of https://redmine.openinfosecfoundation.org/issues/5182

**Comment by jmtaylor90** [comment]
> > The code work was done under https://redmine.openinfosecfoundation.org/issues/5191 / [682e2a0](https://github.com/OISF/suricata/commit/682e2a07fec0ee705ef67befe72c1849843f4375) it looks like the documentation was missed. So this is the associated doc work. Do we need a new redmine for this?
> 
> Looking at other Documentation tickets, I'd say yes. Preferably as a subtask of https://redmine.openinfosecfoundation.org/issues/5182

Thanks! It appears I don't have the redmine permissions to add a subtask to that ticket so I created the new ticket and added it as a related issue to 5182.

**Review by jufajardini — CHANGES_REQUESTED** [review]
Doc changes look good, thanks for catching this :)

Considering now we have a ticket for it, would be good to have it on the commit message :P

**Comment by jmtaylor90** [comment]
continued in https://github.com/OISF/suricata/pull/9597

**Pull request closed without merging**
