### PR TITLE
Smtp server detection 1125 v9

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1125

Describe changes:
- smtp : adds server side detection
- ftp : adds server side detection
- protocoldetect: use stricter max depth

The most special trick is that the (server) probing parser waits for the client side to have seen some data to take a definitive positive decision.
So that If it looks like a SMTP server (it could be a FTP server), let's see if the client looks like SMTP or FTP or something unknown...

Modifies #8135 by relaxing smtp probing parser in case client side was already recognized as SMTP.

I wonder if SMTP parser should also relax its condition to set `state->parser_state |= SMTP_PARSER_STATE_FIRST_REPLY_SEEN;` 

suricata-verify-pr: 1000

https://github.com/OISF/suricata-verify/pull/1000

### CODE REVIEW

**Comment by catenacyber** [comment]
Draft as QA FTP results are still to be investigated

**Comment by catenacyber** [comment]
> I wonder if SMTP parser should also relax its condition to set state->parser_state |= SMTP_PARSER_STATE_FIRST_REPLY_SEEN;

This was kind of illustrated by S-V test based on fuzzed pcap

**Comment by catenacyber** [comment]
S-V needs to be merged first

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10408

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on TREX_GENERIC_collect.
  

Pipeline 10438

**Comment by catenacyber** [comment]
@ct0br0 what are the QA results for this PR ?

**Comment by ct0br0** [comment]
Deleted the comments as they were not accurate (believe the generic issue @pevma found where things were stopping over suricon)

Didn't mess with tracking because this was a draft and figured there would be more pushes. Can have it run if you want.

**Comment by catenacyber** [comment]
> Didn't mess with tracking because this was a draft and figured there would be more pushes. Can have it run if you want.

Please have a run.

This is a draft because latest version was showing something worth investigating in QA ;-p (To be more precise, there were 2 things, one of which got fixed since last PR)

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128237 | 103925 | 81.04% |
| .app_layer.tx.ftp | 647 | 222 | 34.31% |
| .app_layer.error.ftp.gap | 2 | 0 | - |
| .app_layer.error.ftp.parser | 2 | 3 | 150.0% |
| .ftp.memuse | 862 | 3 | 0.35% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 35776 | 11616 | 32.47% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .ftp.memuse | 13827 | 2187 | 15.82% |
| | IPS_AFP_stats_chk | | |
| .app_layer.flow.ftp | 33480 | 1080 | 3.23% |
| .app_layer.tx.ftp | 131760 | 99360 | 75.41% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 14922 | - |
| .flow.end.tcp_state.syn_sent | 0 | 15 | - |
| .flow.end.tcp_state.syn_recv | 0 | 2 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 3 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 2 | - |
| .flow.end.tcp_state.time_wait | 0 | 4 | - |
| .flow.end.tcp_state.last_ack | 0 | 1 | - |
| .flow.end.tcp_state.close_wait | 0 | 7 | - |
| .tcp.segment_from_pool | 15728353 | 16665524 | 105.96% |
| .app_layer.flow.ftp | 18444 | 0 | - |
| .app_layer.tx.ftp | 73776 | 55329 | 75.0% |
| .app_layer.error.http.parser | 0 | 1 | - |
| .app_layer.error.smtp.gap | 0 | 5 | - |
| .app_layer.error.dcerpc_tcp.parser | 0 | 3 | - | 

Pipeline 10750

**Comment by catenacyber** [comment]
@ct0br0 would I have a pcap extract to investigate the difference about ftp flows ?

As flows recognized as FTP by current version and not by this PR...

Thanks

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .app_layer.tx.ftp | 647 | 222 | 34.31% |
| .app_layer.error.ftp.gap | 2 | 0 | - |
| .app_layer.error.ftp.parser | 2 | 3 | 150.0% |
| .ftp.memuse | 862 | 3 | 0.35% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 35776 | 11616 | 32.47% |
| .app_layer.error.ftp-data.gap | 0 | 1 | - |
| .ftp.memuse | 13827 | 2187 | 15.82% |
| | IPS_AFP_stats_chk | | |
| .app_layer.flow.ftp | 33480 | 1080 | 3.23% |
| .app_layer.tx.ftp | 131760 | 99360 | 75.41% |
| | TREX_GENERIC_stats_chk | | |
| .app_layer.flow.ftp | 18444 | 0 | - |
| .app_layer.tx.ftp | 73776 | 55332 | 75.0% | 

Pipeline 11144

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8327

**Pull request closed without merging**
