### PR TITLE
stats: add rules skipped due to missing requirements - v10

### PR DESCRIPTION
**Pull request by jasonish**
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1559

Feature: https://redmine.openinfosecfoundation.org/issues/6637

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 17151

**Comment by victorjulien** [comment]
Does the unix socket side work too? Meaning https://github.com/OISF/suricata/blob/master/src/unix-manager.c#L771

**Comment by jasonish** [comment]
> Does the unix socket side work too? Meaning https://github.com/OISF/suricata/blob/master/src/unix-manager.c#L771

Yes, this is just a subset of `dump-counters`:
```
>>> ruleset-stats
Success:
[
    {
        "id": 0,
        "rules_failed": 1,
        "rules_loaded": 1,
        "rules_skipped": 2
    }
]
```

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #10100, thanks!

**Pull request merged**
