### PR TITLE
Port grouping redo/v10

### PR DESCRIPTION
**Pull request by inashivb**
More fixes to #10451

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 101 | 111 | 109.9% | 

Pipeline 18610

**Comment by victorjulien** [comment]
additional cppcheck warning
```
src/detect-engine-build.c:1269:20: warning: Either the condition 'p1' is redundant or there is possible null pointer dereference: p1. [nullPointerRedundantCheck]
            port = p1->port;
                   ^
src/detect-engine-build.c:1273:21: note: Assuming that condition 'p1' is not redundant
                if (p1 && p1->single) {
                    ^
src/detect-engine-build.c:1269:20: note: Null pointer dereference
            port = p1->port;
                   ^
```

**Comment by victorjulien** [comment]
Seems we can gain a lot by optimizing the way the whitelist grouping is happening
image

**Comment by inashivb** [comment]
> Seems we can gain a lot by optimizing the way the whitelist grouping is happening image This is with the very large test ruleset.

Think I have an idea. Will try it out and share the results.

**Comment by inashivb** [comment]
Replaced w https://github.com/OISF/suricata/pull/10482

**Pull request closed without merging**
