### PR TITLE
source-pcap-file: Pcap Directory Mode (Feature #2222) v11

### PR DESCRIPTION
**Pull request by dbcfd**
Version 11 of 
 - https://github.com/OISF/suricata/pull/3035
 - https://github.com/OISF/suricata/pull/3027
 - https://github.com/OISF/suricata/pull/2992
 - https://github.com/OISF/suricata/pull/2985
 - https://github.com/OISF/suricata/pull/2971
 - https://github.com/OISF/suricata/pull/2964
 - https://github.com/OISF/suricata/pull/2961
 - https://github.com/OISF/suricata/pull/2960
 - https://github.com/OISF/suricata/pull/2958
 - https://github.com/OISF/suricata/pull/2957

Pcap file mode that when passed a directory will process all files in that directory. If continuous flag is set (--pcap-file-continuous), directory will be monitored until the directory is moved/deleted or suricata is interrupted.

Engine state will not reset between files.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2222

Also satisfies:
 * https://redmine.openinfosecfoundation.org/issues/2299
 * https://redmine.openinfosecfoundation.org/issues/724
 * https://redmine.openinfosecfoundation.org/issues/1476

Describe changes:
- If source-pcap-file is passed a directory instead of a file, all files in that directory will be processed in order of modified time, without state resetting between files.
- source-pcap-file will continue to process files until suricata is interrupted or the directory is moved/deleted when using --pcap-file-continuous or continuous json argument.
- runmode-unix-socket is updated to provide a current time to determine what state of processing of the directory is
- Implementation details for file and directory processing are contained in pcap-file-helper and pcap-directory-helper

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

Co-Authors: @dkhelwig Dana Helwig and @dbcfd Danny Browning

### CODE REVIEW

**Comment by victorjulien** [comment]
OSX (10.10 iirc)
<pre>
CC       source-pcap-file-directory-helper.o
source-pcap-file-directory-helper.c:379:9: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, older_than);
        ^
source-pcap-file-directory-helper.c:379:9: note: did you mean 'clock_set_time'?
/usr/include/mach/clock_priv.h:52:15: note: 'clock_set_time' declared here
kern_return_t clock_set_time
              ^
source-pcap-file-directory-helper.c:379:23: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, older_than);
                      ^
source-pcap-file-directory-helper.c:451:19: error: use of undeclared identifier 'CLOCK_REALTIME'
    clock_gettime(CLOCK_REALTIME, older_than);
                  ^
source-pcap-file-directory-helper.c:469:23: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &older_than);
                      ^
4 errors generated.
make[3]: *** [source-pcap-file-directory-helper.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
</pre>

Another error, this is on muslc (instead of libc), not sure if that is related:
<pre>
  CC       source-pcap-file-directory-helper.o
source-pcap-file-directory-helper.c: In function 'PcapDirectoryDispatch':
source-pcap-file-directory-helper.c:57:12: error: 'modified_time.tv_nsec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         if (left->tv_nsec < right->tv_nsec) {
            ^
source-pcap-file-directory-helper.c:267:29: note: 'modified_time.tv_nsec' was declared here
             struct timespec modified_time;
                             ^~~~~~~~~~~~~
source-pcap-file-directory-helper.c:54:15: error: 'modified_time.tv_sec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     } else if (left->tv_sec > right->tv_sec) {
               ^
source-pcap-file-directory-helper.c:267:29: note: 'modified_time.tv_sec' was declared here
             struct timespec modified_time;
                             ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:1694: source-pcap-file-directory-helper.o] Error 1
make[3]: Leaving directory '/home/buildbot/qa/buildbot/donkey/MUSLg/Private/src'
make[2]: *** [Makefile:1138: all] Error 2
make[2]: Leaving directory '/home/buildbot/qa/buildbot/donkey/MUSLg/Private/src'
make[1]: *** [Makefile:493: all-recursive] Error 1
make: *** [Makefile:421: all] Error 2
</pre>

Ah no as it's only debian as well
<pre>
source-pcap-file-directory-helper.c: In function ‘PcapDirectoryDispatch’:
source-pcap-file-directory-helper.c:57:12: error: ‘modified_time.tv_nsec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         if (left->tv_nsec < right->tv_nsec) {
            ^
source-pcap-file-directory-helper.c:267:29: note: ‘modified_time.tv_nsec’ was declared here
             struct timespec modified_time;
                             ^
source-pcap-file-directory-helper.c:54:15: error: ‘modified_time.tv_sec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     } else if (left->tv_sec > right->tv_sec) {
               ^
source-pcap-file-directory-helper.c:267:29: note: ‘modified_time.tv_sec’ was declared here
             struct timespec modified_time;
                             ^
  CC       source-pcap-file-helper.o
  CC       source-pfring.o
cc1: all warnings being treated as errors
Makefile:1683: recipe for target 'source-pcap-file-directory-helper.o' failed
make[3]: *** [source-pcap-file-directory-helper.o] Error 1
make[3]: *** Waiting for unfinished jobs....
</pre>

**Comment by victorjulien** [comment]
OpenBSD:
<pre>
source-pcap-file-directory-helper.c: In function 'PcapDirectoryDispatch':
source-pcap-file-directory-helper.c:476:9: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'time_t' [-Werror=format=]
         SCLogInfo("Processing pcaps directory %s, files must be newer than %ld and older than %ld",
         ^
source-pcap-file-directory-helper.c:476:9: error: format '%ld' expects argument of type 'long int', but argument 6 has type 'time_t' [-Werror=format=]
cc1: all warnings being treated as errors
</pre>

**Comment by victorjulien** [comment]
Is there a reason for not just using gettimeofday?

**Comment by dbcfd** [comment]
Closing for https://github.com/OISF/suricata/pull/3054

**Pull request closed without merging**
