### PR TITLE
Smtp mime base64/v8

### PR DESCRIPTION
**Pull request by victorjulien**
Updates #7479 to address comments and hopefully kick off a new QA run

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on report_failure.

ERROR: QA failed on arg_strap.
  

Pipeline 7690

**Comment by victorjulien** [comment]
This one is green but I don't see how this would fix this CIFuzz issue https://github.com/OISF/suricata/runs/6736456547?check_suite_focus=true

I couldn't reproduce it, but here is the ASAN output for v7 (so line numbers are slightly off)
```
=================================================================
6327
==172==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000ecc93 at pc 0x0000006ab52d bp 0x7ffe117e6a50 sp 0x7ffe117e6a48
6328
READ of size 1 at 0x6020000ecc93 thread T0 (Suricata-Main)
6329
SCARINESS: 12 (1-byte-read-heap-buffer-overflow)
6330
    #0 0x6ab52c in SMTPPreProcessCommands /src/suricata/src/app-layer-smtp.c:1302:29
6331
    #1 0x6ab52c in SMTPParse /src/suricata/src/app-layer-smtp.c:1349:23
6332
    #2 0x6a8174 in SMTPParseClientRecord /src/suricata/src/app-layer-smtp.c:1408:12
6333
    #3 0x6a2e33 in AppLayerParserParse /src/suricata/src/app-layer-parser.c:1304:30
6334
    #4 0x69cd6b in LLVMFuzzerTestOneInput /src/suricata/src/tests/fuzz/fuzz_applayerparserparse.c:153:20
6335
    #5 0x594933 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
6336
    #6 0x59411a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:514:3
6337
    #7 0x5957e9 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:757:19
6338
    #8 0x5964b5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:895:5
6339
    #9 0x585cef in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
6340
    #10 0x5aea02 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
6341
    #11 0x7f03fba73082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
6342
    #12 0x55eded in _start (build-out/fuzz_applayerparserparse_smtp+0x55eded)
6343
6344
DEDUP_TOKEN: SMTPPreProcessCommands--SMTPParse--SMTPParseClientRecord
6345
0x6020000ecc93 is located 0 bytes to the right of 3-byte region [0x6020000ecc90,0x6020000ecc93)
6346
allocated by thread T0 (Suricata-Main) here:
6347
    #0 0x66321d in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
6348
    #1 0x69cd0f in LLVMFuzzerTestOneInput /src/suricata/src/tests/fuzz/fuzz_applayerparserparse.c:148:30
6349
    #2 0x594933 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
6350
    #3 0x59411a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:514:3
6351
    #4 0x5957e9 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:757:19
6352
    #5 0x5964b5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:895:5
6353
    #6 0x585cef in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
6354
    #7 0x5aea02 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
6355
    #8 0x7f03fba73082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
6356
6357
DEDUP_TOKEN: malloc--LLVMFuzzerTestOneInput--fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)
6358
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/suricata/src/app-layer-smtp.c:1302:29 in SMTPPreProcessCommands
6359
Shadow bytes around the buggy address:
6360
  0x0c0480015940: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
6361
  0x0c0480015950: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
6362
  0x0c0480015960: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
6363
  0x0c0480015970: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
6364
  0x0c0480015980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 fa
6365
=>0x0c0480015990: fa fa[03]fa fa fa fd fa fa fa 00 00 fa fa fd fd
6366
  0x0c04800159a0: fa fa 05 fa fa fa fd fa fa fa fd fa fa fa fd fa
6367
  0x0c04800159b0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
6368
  0x0c04800159c0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
6369
  0x0c04800159d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
6370
  0x0c04800159e0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
6371
Shadow byte legend (one shadow byte represents 8 application bytes):
6372
  Addressable:           00
6373
  Partially addressable: 01 02 03 04 05 06 07 
6374
  Heap left redzone:       fa
6375
  Freed heap region:       fd
6376
  Stack left redzone:      f1
6377
  Stack mid redzone:       f2
6378
2022-06-04 07:01:04,791 - root - INFO - Fuzzer: fuzz_applayerparserparse_smtp. Detected bug.
6379
  Stack right redzone:     f3
6380
  Stack after return:      f5
6381
  Stack use after scope:   f8
6382
  Global redzone:          f9
6383
  Global init order:       f6
6384
  Poisoned by user:        f7
6385
  Container overflow:      fc
6386
  Array cookie:            ac
6387
  Intra object redzone:    bb
6388
  ASan internal:           fe
6389
  Left alloca redzone:     ca
6390
  Right alloca redzone:    cb
6391
==172==ABORTING
6392
MS: 3 InsertByte-CopyPart-CMP- DE: "\001\325\312z"-; base unit: 23a8c00e6862de83abed0bbb0f412a5cf4bc4112
6393
artifact_prefix='/tmp/tmpuqx76xbh/'; Test unit written to /tmp/tmpuqx76xbh/crash-7e1ae6ae7bfe71290f223f872a1cc788f3c74300
6394
stat::number_of_executed_units: 2491
6395
stat::average_exec_per_sec:     226
6396
stat::new_units_added:          5
6397
stat::slowest_unit_time_sec:    0
6398
stat::peak_rss_mb:              241
6399
2022-06-04 07:01:04,792 - root - INFO - Trying to reproduce crash using: /tmp/tmpuqx76xbh/crash-7e1ae6ae7bfe71290f223f872a1cc788f3c74300.
6400
2022-06-04 07:01:05,513 - root - INFO - Reproduce command returned: 77. Reproducible on /github/workspace/build-out/fuzz_applayerparserparse_smtp.
6401
2022-06-04 07:01:05,514 - root - INFO - Crash is reproducible.
6402
2022-06-04 07:01:05,514 - root - INFO - Trying to reproduce crash using: /tmp/tmpuqx76xbh/crash-7e1ae6ae7bfe71290f223f872a1cc788f3c74300.
6403
2022-06-04 07:01:06,518 - root - INFO - Reproduce command returned: 0. Not reproducible on /github/workspace/cifuzz-prev-build/fuzz_applayerparserparse_smtp.
6404
2022-06-04 07:01:06,519 - root - INFO - The crash is not reproducible on previous build. Code change (pr/commit) introduced crash.
6405
2022-06-04 07:01:06,519 - root - INFO - Deleting corpus and seed corpus of fuzz_applayerparserparse_smtp to save disk.
6406
2022-06-04 07:01:06,551 - root - INFO - Deleting fuzz target: fuzz_applayerparserparse_smtp.
6407
2022-06-04 07:01:06,554 - root - INFO - Done deleting.
6408
2022-06-04 07:01:06,554 - root - INFO - Bug found. Stopping fuzzing.
6409
2022-06-04 07:01:06,555 - root - INFO - Not uploading crashes because on OSS-Fuzz.
6410
2022-06-04 07:01:06,555 - root - INFO - Bug found.
```

**Comment by victorjulien** [comment]
```c
static int SMTPPreProcessCommands(SMTPState *state, Flow *f, AppLayerParserState *pstate)
{
    bool line_complete = false;
    int32_t input_len = state->input_len;
    for (int32_t i = 0;
            i < input_len && (state->parser_state & SMTP_PARSER_STATE_COMMAND_DATA_MODE); i++) {
        if (state->input[i] == 0x0d) {
            if (i < input_len - 1 && state->input[i + 1] == 0x0a) {
                i++;
                state->current_line_delimiter_len++;
            }
            /* Line is just ending in CR */
            state->current_line_delimiter_len++;
            line_complete = true;
        } else if (state->input[i] == 0x0a) {
            /* Line is just ending in LF */
            state->current_line_delimiter_len++;
            line_complete = true;
        }
        /* Either line is complete or fragmented */
        if (line_complete || (i == input_len - 1)) {
            if ((input_len == 1 && state->input[state->consumed] == '-') ||
                    (input_len > 1 && state->input[state->consumed] == '-' &&
HERE ->                            state->input[state->consumed + 1] == '-')) {
                SCLogDebug("Possible boundary, yield to GetLine");
                return 1;
            }
            int32_t total_consumed = i + 1;
            int32_t current_line_consumed = total_consumed - state->consumed;
            state->current_line = state->input + state->consumed;
            state->current_line_len = current_line_consumed - state->current_line_delimiter_len;
            state->consumed = total_consumed;
            state->input_len -= current_line_consumed;
            BUG_ON(state->consumed + state->input_len != state->orig_input_len);
            if (SMTPProcessRequest(state, f, pstate) == -1) {
                return -1;
            }
            line_complete = false;
            state->current_line_delimiter_len = 0;
        }
    }
    return 0;
}
```

**Comment by victorjulien** [comment]
Replaced by #7482

**Pull request closed without merging**
