### PR TITLE
add batman-adv layer 2 decoder capability

### PR DESCRIPTION
**Pull request by ctr49**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [n/a] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2932

Describe changes:
- add decode capabilities for batman-adv (L2)

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable): n/a

### CODE REVIEW

**Comment by victorjulien** [comment]
Could you also open a PR to https://github.com/OISF/suricata-verify to add some test cases?

**Comment by ctr49** [comment]
I can't see any tests for other decoders, so I don't think that I can provide this right now.

**Comment by victorjulien** [comment]
You could do something as simple as replicating the testmyids test for your protocol.

**Comment by victorjulien** [comment]
I'm closing this for now. Please resubmit a rebased version together with some test cases. Thanks.

**Pull request closed without merging**
