### PR TITLE
Fuzz conf protodetect 4125 v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4125

Describe changes:
- Improves fuzz target for protocol detection
- Fixes bug in ENIP probing parser

### CODE REVIEW

**Comment by catenacyber** [comment]
About the ENIP bug, I am surprised it was not caught by static analysis tools :
```
f(a) {
  if (a < 24) {
    return;
  }
  // much code but no changes to a
  if (a == 0 || a == 4) {
    // this should be tagged as unreachable
  }
}
```
Looks like a good candidate for a codeQL query

**Comment by catenacyber** [comment]
Coming from CIFuzz https://github.com/OISF/suricata/pull/6712

**Comment by suricata-qa** [comment]
Information:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpr1_stats_chk |
| .flow.memuse | 537874368 | 505916608 | 106.32% | 

Pipeline 5323

**Comment by victorjulien** [comment]
merged in #6810, thanks!

**Pull request closed without merging**
