### PR TITLE
Warnint 64to32 6186 v15

### PR DESCRIPTION
**Pull request by catenacyber**
[Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6186

Describe changes:
- fix `-Wshorten-64-to-32` warnings for some files
- Add CI build with this warning

```
LIBHTP_BRANCH=pr/399
```
https://github.com/OISF/libhtp/pull/399

#9563 with compliation warning with debug fixed for good

There must be some stuff to review more carefully

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on ASAN_TLPR1_suri.
  

Pipeline 16259

**Comment by catenacyber** [comment]
@ct0br0 could you get me a minimized reproducer ?

**Comment by catenacyber** [comment]
Oh, I think I see : 
we can use a variable name for depth even if it is not documented in https://docs.suricata.io/en/latest/rules/payload-keywords.html#depth cc @jufajardini 
This variable name can come from `byte_extract` and be a u64, so overflow a u32, right @jlucovsky ?

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/9666

**Comment by ct0br0** [comment]
still want a pcap for that then? or false alarm?

**Comment by catenacyber** [comment]
No need for the pcap

It was not a false alarm.
The added debug assertion found a bug in the code. (or QA found the bug)
The next version should fix it.
@jlucovsky may know a bit more on this part of the code...

**Pull request closed without merging**
