### PR TITLE
Integer overflow 4527 v3

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4527

Describe changes:
- Fix integer warnings in all files beginning with a (like app)

libhtp-pr: 339

There remains one warning about the use of `StreamTcpUpdateAppLayerProgress`
cf discussion in https://github.com/OISF/suricata/pull/6649

Changes #6676 with comments taken into account

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | build_asan |
 

Pipeline 5186

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on tlpw2_single_alerts_cmp.

ERROR: QA failed on tlpw2_autofp_alerts_cmp.
 | field | test | baseline | % |
|--|--|--|--| 
| | generic_stats_chk |
| .capture.kernel_packets | 682402358 | 580685130 | 117.52% |
| .capture.afpacket.polls | 16906434 | 14338680 | 117.91% |
| .capture.afpacket.poll_data | 16903507 | 14338660 | 117.89% |
| .decoder.pkts | 682401532 | 580682468 | 117.52% |
| .decoder.bytes | 588722230431 | 501096057745 | 117.49% |
| .decoder.ipv4 | 682401532 | 580682468 | 117.52% |
| .decoder.ethernet | 682401532 | 580682468 | 117.52% |
| .decoder.tcp | 474428167 | 402035711 | 118.01% |
| .decoder.udp | 207973365 | 178646757 | 116.42% |
| .flow.tcp | 3291787 | 2791210 | 117.93% |
| .flow.udp | 551573 | 469454 | 117.49% |
| .tcp.sessions | 3291787 | 2783889 | 118.24% |
| .tcp.syn | 5459719 | 4617737 | 118.23% |
| .tcp.synack | 3291706 | 2783857 | 118.24% |
| .tcp.rst | 2241846 | 1901273 | 117.91% |
| .tcp.reassembly_gap | 94632 | 79516 | 119.01% |
| .detect.alert | 126233 | 107403 | 117.53% |
| .app_layer.flow.http | 632809 | 535563 | 118.16% |
| .app_layer.flow.ftp | 21480 | 18163 | 118.26% |
| .app_layer.flow.smtp | 21500 | 18150 | 118.46% |
| .app_layer.flow.tls | 2167794 | 1833745 | 118.22% |
| .app_layer.flow.smb | 206069 | 173555 | 118.73% |
| .app_layer.flow.dcerpc_tcp | 18856 | 15984 | 117.97% |
| .app_layer.flow.failed_tcp | 160095 | 135398 | 118.24% |
| .app_layer.flow.dns_udp | 376992 | 318451 | 118.38% |
| .app_layer.flow.failed_udp | 174581 | 151003 | 115.61% |
| .app_layer.tx.http | 632859 | 535604 | 118.16% |
| .app_layer.tx.ftp | 85917 | 72648 | 118.26% |
| .app_layer.tx.smtp | 42949 | 36264 | 118.43% |
| .app_layer.tx.smb | 1694541 | 1425365 | 118.88% |
| .app_layer.tx.dcerpc_tcp | 320472 | 271659 | 117.97% |
| .app_layer.tx.dns_udp | 753976 | 636898 | 118.38% | 

Pipeline 5190

**Comment by victorjulien** [comment]
Can you rebase this? I'll fast track if afterwards.

**Comment by catenacyber** [comment]
> Can you rebase this? I'll fast track if afterwards.

Replaced by https://github.com/OISF/suricata/pull/6778

**Pull request closed without merging**
