### PR TITLE
Organize sources into directories - v5

### PR DESCRIPTION
**Pull request by jasonish**
This PR moves the following types of files into their
own directories:
- sources
- util
- win32
- outputs (outputs, log, alert)
- app-layer
- decoders

I think this covers the very easy to move modules.

Previous PR:
https://github.com/OISF/suricata/pull/4349

Requires suricata-verify PR:
https://github.com/OISF/suricata-verify/pull/147

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/408
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/764

### CODE REVIEW

**Comment by catenacyber** [comment]
And then compile the directories as libraries :-)

**Comment by jasonish** [comment]
> And then compile the directories as libraries :-)

Possible. But does it provide any value?

**Comment by catenacyber** [comment]
>>And then compile the directories as libraries :-)
>Possible. But does it provide any value?

That is a long debate, I was just teasing

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/4609.

**Pull request closed without merging**
