### PR TITLE
[draft] dns: dns.response.answer.name sticky buffer - v1

### PR DESCRIPTION
**Pull request by jasonish**
This implements the sticky buffer `dns.response.answer.name` to match on names on DNS response answers.

The idea is to fill this out with more keywords like:
- dns.response.answer.data.a
- dns.response.answer.data.txt
- dns.response.answer.data.sshfp.fingerprint
and so on.

But before I continue on I want to make sure this is the good example of a stick buffer, with prefiltering and multi-buffer support, as it looks like our template is out of date.  After this is given an OK, I'll apply the changes to the template.

Then I'd also like to isolate the common patterns of the sticky buffers and abstract the boilerplate away.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1444

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16305

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .memcap_pressure_max | 88 | 97 | 110.23% | 

Pipeline 16306

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16307

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16309

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16314

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16320

**Comment by victorjulien** [comment]
Think it makes sense. Not finding the commit separation entirely logical, I would just squash them all together (the keyword commits, not talking about the API rename)

**Comment by jasonish** [comment]
> Think it makes sense. Not finding the commit separation entirely logical, I would just squash them all together (the keyword commits, not talking about the API rename)

Yeah, its more for review of the individual items that were applied over and above the current template for sticky buffers.

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata/pull/9813 right ?

**Pull request closed without merging**
