### PR TITLE
dpdk.eal-param list support

### PR DESCRIPTION
**Pull request by zhiyuan-liao**
dpdk.eal-param list support
    support suricata.yaml dpdk.eal-params list params handle.
    specially with multiple assign params like: --vdev, --allow, --block
    according Ticket: https://redmine.openinfosecfoundation.org/issues/5964

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
Ticket: #5964
Describe changes:
-
- Extend the InitEal function to support list parameters
- Added example in userguide/configuration/suricata-yaml.rst document
- remove dpdk EAL arguments example in suricata.yaml.in

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the pull request number.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by lukashino** [comment]
Hi @zhiyuan-liao 

thank you for reopening the PR! But before we accept your contribution, please complete the requested steps outlined in the previous PR. It also seems that you haven't filled out contribution agreement - you can do that here: https://suricata.io/contribution-agreements/ 

All of the steps are necessary for the final merge.

I also recommend checking out our contribution guide -> https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing

**Comment by lukashino** [comment]
I can see you've done some steps already (Thank you!) - so to mention the remaining ones:
- commit message containing ticket number (do not add URL, just add the number as was outlined) (on a new line add `Ticket: #5964`)
- remove your the line from suricata.yaml.in 
- explain the usage in the docs - I have suggested a place where you can mention the way multiple arguments are supported 
- sign the contribution agreement as mentioned in the comment above

**Review by lukashino — CHANGES_REQUESTED** [review]
Comment above outlines the requested changes

**Comment by zhiyuan-liao** [comment]
I will re-edit as suggested as soon as possible, not familiar with the PR process. Thanks for the guidance from the dpdk run mode code author.

**Comment by zhiyuan-liao** [comment]
Hi @lukashino , I have updated the documentation to demonstrate how the new parameters are configured in userguide. Also, I submitted the OIFS contribution agreement. Thank you so much for your patient help. Very glad to get your approval.

**Comment by lukashino** [comment]
Hi @zhiyuan-liao 

thank you for letting me know! 
I can't seem to find your updated files. One thing that I've thought of, weren't the changes made only locally? If so, please checkout (locally) to a new branch with a name e.g. `dpdk_params_list_v2`, push this branch to your repository, and then create a second pull request - this way the original (this) PR stays the same and we will have the context for future revisions.

**Comment by jasonish** [comment]
> Hi @lukashino , I have updated the documentation to demonstrate how the new parameters are configured in userguide. Also, I submitted the OIFS contribution agreement. Thank you so much for your patient help. Very glad to get your approval.

Hi @zhiyuan-liao. Could you please make sure that you sign the contribution agreement using the same email address you make the commits as?  Thanks!

**Comment by jasonish** [comment]
> NOTE: This PR may contain new authors:
> 
> ```
> liaozhiyuan <liaozhiyuan@fnii.cn>
> ```

CLA signed.

**Comment by zhiyuan-liao** [comment]
> Hi @zhiyuan-liao
> 
> thank you for letting me know! I can't seem to find your updated files. One thing that I've thought of, weren't the changes made only locally? If so, please checkout (locally) to a new branch with a name e.g. `dpdk_params_list_v2`, push this branch to your repository, and then create a second pull request - this way the original (this) PR stays the same and we will have the context for future revisions.

My commit seems to be mixed with upstream updates, so I recreated the v2 branch according to your suggestion, and used the v2 branch as the commit of the new PR:  #8947   , so that everyone can understand my changes more clearly. I resubmitted the Contribution Agreement due to I confused my work and personal email accounts. Thank you for your helpful comments  #

**Comment by victorjulien** [comment]
continued in #8947

**Pull request closed without merging**
