### PR TITLE
rust: update aes and aes-gcm crates

### PR DESCRIPTION
**Pull request by jasonish**
Addresses RUSTSEC-2021-0059, RUSTSEC-2021-0060.

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113267 | 145074 | 128.08% | 

Pipeline 12810

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
@jasonish what is the link with  RUSTSEC-2021-0059 ? 

https://rustsec.org/advisories/RUSTSEC-2021-0059.html states `Please use the aes crate going forward. ` but that was already done...

**Comment by jasonish** [comment]
> @jasonish what is the link with RUSTSEC-2021-0059 ?
> 
> https://rustsec.org/advisories/RUSTSEC-2021-0059.html states `Please use the aes crate going forward. ` but that was already done...

An older version was still being pulled in, cargo audit output that this resolves:
```
Crate:     aes-soft
Version:   0.6.4
Warning:   unmaintained
Title:     `aes-soft` has been merged into the `aes` crate
Date:      2021-04-29
ID:        RUSTSEC-2021-0060
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0060
Dependency tree:
aes-soft 0.6.4
└── aes 0.6.0
    ├── suricata 7.0.0-rc2-dev
    └── aes-gcm 0.8.0
        └── suricata 7.0.0-rc2-dev

Crate:     aesni
Version:   0.10.0
Warning:   unmaintained
Title:     `aesni` has been merged into the `aes` crate
Date:      2021-04-29
ID:        RUSTSEC-2021-0059
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0059
Dependency tree:
aesni 0.10.0
└── aes 0.6.0
    ├── suricata 7.0.0-rc2-dev
    └── aes-gcm 0.8.0
        └── suricata 7.0.0-rc2-dev

Crate:     cpuid-bool
Version:   0.2.0
Warning:   unmaintained
Title:     `cpuid-bool` has been renamed to `cpufeatures`
Date:      2021-05-06
ID:        RUSTSEC-2021-0064
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0064
Dependency tree:
cpuid-bool 0.2.0
└── polyval 0.4.5
    └── ghash 0.3.1
        └── aes-gcm 0.8.0
            └── suricata 7.0.0-rc2-dev
```

**Comment by catenacyber** [comment]
Ok, thanks Jason, (I find the rust advisory confusing...)

**Comment by victorjulien** [comment]
Merged in https://github.com/OISF/suricata/pull/8625, thanks!

**Pull request closed without merging**
