### PR TITLE
doxygen: update config from 1.8.4 to 1.8.17

### PR DESCRIPTION
**Pull request by norg**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
update doxygen config from 1.8.4 to 1.8.17

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

### CODE REVIEW

**Comment by jlucovsky** [comment]
Are the documents produced with the new configuration the same?

**Comment by norg** [comment]
> Are the documents produced with the new configuration the same?

AFAIK yes, that's the version we already use on the server.

**Comment by jlucovsky** [comment]
LGTM

**Comment by victorjulien** [comment]
Merged as part of #4568, thanks Andreas!

**Pull request closed without merging**
