### PR TITLE
smb: add smb.version keyword 5075 v3

### PR DESCRIPTION
**Pull request by jmtaylor90**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5075

Describe changes:
- used initial authors commits
- removed unnecessary NULL checks
- removed unnecessary debug related function calls

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1380
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

### CODE REVIEW

**Comment by catenacyber** [comment]
Looks like rebase was not clean enough as CI is red for commit check : we want Suricata to build at every commit to run `git bisect`

Could you fix this @jmtaylor90 ?

**Comment by jmtaylor90** [comment]
> 
Yeah, will take a look today and get this sorted. Thanks!

**Comment by jmtaylor90** [comment]
@catenacyber should I add the change you made in #9462 here as well?

**Comment by catenacyber** [comment]
> should I add the change you made in #9462 here as well?

Not until it is merged, and you may get merged first ;-)

**Comment by jmtaylor90** [comment]
continued in #9469

**Pull request closed without merging**
