### PR TITLE
runmodes: enable IPS in DPDK runmode v3

### PR DESCRIPTION
**Pull request by lukashino**
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5580#change-24800) :ticket::

Follow up of #8041 

Describe changes:
- change DPDK behavior when setting up IPS mode

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
```
../../../src/runmode-netmap.c:411:9: error: implicit declaration of function 'EngineModeSetIPS' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        EngineModeSetIPS();
        ^
1 error generated.
```

**Comment by victorjulien** [comment]
I wonder if these IPS result changes have something to do with this PR: https://github.com/OISF/suricata/pull/8084#issuecomment-1290190443
image

**Comment by victorjulien** [comment]
Started a manual pipeline on this PR to find out.

**Comment by victorjulien** [comment]
Yes, it seems this PR caused it
```
| .app_layer.flow.ssh | 1080 | 0 | - |
```

**Comment by victorjulien** [comment]
pipeline 10183

**Comment by lukashino** [comment]
Continues in #8204

**Pull request closed without merging**
