### PR TITLE
[draft] libsuricata example with custom capture and custom eve output

### PR DESCRIPTION
**Pull request by jasonish**
This is based on https://github.com/OISF/suricata/pull/10681, but provides an example of what could be a common library user example where the user just wants to provide a custom capture method, and perhaps a custom event handler.

Its not the best DX as Suricata still drives the main loop, many library use cases the application would want to be driving the main loop.

Still very much a draft.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19775

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19836

**Comment by catenacyber** [comment]
What is the status here Jason ?

**Comment by jasonish** [comment]
Replaced by https://github.com/OISF/suricata/pull/11921.

**Pull request closed without merging**
