### PR TITLE
detect: Add byte_math detector

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #4918

This PR adds `byte_math` to the suite of `byte` functions with a strict implementation based on the Snort documents.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [2311](https://redmine.openinfosecfoundation.org/issues/2311)

Describe changes:
- Address review comments

[Suricata-verify PR#229](https://github.com/OISF/suricata-verify/pull/229)

### CODE REVIEW

**Comment by jlucovsky** [comment]
Continued in #4981

**Comment by victorjulien** [comment]
Please make sure the PR references the correct SV PR.

**Comment by jlucovsky** [comment]
> Please make sure the PR references the correct SV PR.

Updated.

**Comment by victorjulien** [comment]
Can you rebase this?

**Comment by jlucovsky** [comment]
Continued in #5152

**Pull request closed without merging**
