### PR TITLE
Dataset user v5

### PR DESCRIPTION
**Pull request by regit**
Rebased of #5859 on latest master.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4239

Describe changes:
- rebase on master

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 5144

**Comment by jasonish** [comment]
While this seems to work, I noticed that datasets defined in rules do not have this issue. So I wonder if it would be better to just change where datasets defined in `suricata.yaml` are initialized?

**Comment by inashivb** [comment]
> While this seems to work, I noticed that datasets defined in rules do not have this issue. So I wonder if it would be better to just change where datasets defined in `suricata.yaml` are initialized?

Ah! thanks! I have been trying to reproduce it and failing as I was only trying load and save dataset in rules.

**Comment by victorjulien** [comment]
Now that #6698 is merged, do we still need to keep this open for something? @jasonish @regit ?

**Comment by jasonish** [comment]
> Now that #6698 is merged, do we still need to keep this open for something? @jasonish @regit ?

No, it should not be needed. Closing.

**Pull request closed without merging**
