### PR TITLE
ci: Backport cherry check v1

### PR DESCRIPTION
**Pull request by ct0br0**
per https://github.com/OISF/suricata/pull/6155#issuecomment-853828357

Changes:

- add backport cherry picker check script
- call script in `commit-check` ci

### CODE REVIEW

**Comment by ct0br0** [comment]
testing2

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | generic_stats_chk |
| .tcp.reassembly_memuse | 2293760 | 1966080 | 86.0% |

**Comment by suricata-qa** [comment]
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.spare | 5216121 | 5890991 | 89.0% |
| .flow.memuse | 1014584448 | 1130221888 | 90.0% |

**Comment by suricata-qa** [comment]
ERROR: ASAN TEST FAIL in tlpr1_asan_suri QA test

Pipeline 3467

**Comment by victorjulien** [comment]
Can you rebase this and fix up the git author for both commits?

**Pull request closed without merging**
