### PR TITLE
Backports/70x/v4

### PR DESCRIPTION
**Pull request by victorjulien**
2 backports for contributions

### CODE REVIEW

**Review by jlucovsky — APPROVED** [review]

**Comment by catenacyber** [comment]
Is https://redmine.openinfosecfoundation.org/issues/6254 missing a backport ticket ?

**Comment by catenacyber** [comment]
Is there a ticket for the ipfw commit ?

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.error.http.parser | 1108 | 724 | 65.34% | 

Pipeline 17690

**Comment by catenacyber** [comment]
> > Is there a ticket for the ipfw commit ?
> 
> Don't think so

Should there be one to track this ?

**Comment by victorjulien** [comment]
Merged in #10253, thanks!

**Pull request closed without merging**
