### PR TITLE
WIP: libhtp-rs

### PR DESCRIPTION
**Pull request by cccs-rtmorti**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2696) ticket.

Describe changes:

WIP for libhtp-rs support. For discussion only. libhtp-rs still has some work to do before it is ready, but the current state is here: 

https://github.com/cccs-rtmorti/libhtp-rs 

Presently this still builds libhtp-rs as a shared library and links it like libhtp-c, but this will also change to build / link as a crate. To build against libhtp-rs, just symlink the `libhtp` subdir to a checkout of libhtp-rs and the libhtp-rs `Makefile` will take care of the rest.

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks for this great work :-)

Generally speaking, I think this will need a bit of commit history cleaning cf 
`Fix conflict in output-json-http`

By the way, every commit must build, so I think, CI commit-check will fail here.

What is the general story for commits here ? (there seem to be many changes)
Preliminary commits, making changes but keeping libhtp-c
A commit switching to libhtp-rs
A commit removing what is remaining of libhtp-c (doc)

> Presently this still builds libhtp-rs as a shared library and links it like libhtp-c, but this will also change to build / link as a crate. 

Are you working on this ?

**Comment by victorjulien** [comment]
Could you do an update that fixes the compilation issues? Don't mind the commit-check, formatting-check failures at this point, but would like to see runtime tests pass. Then we can compare in our QA with some confidence.

**Comment by cccs-rtmorti** [comment]
No problem with cleaning up the commit history, etc. - we were expecting to do this anyway.

The general story is pretty straightforward. The c2rust conversion was initially functionally identical to the C libhtp and it was a drop-in replacement, but as we have been refactoring libhtp-rs to be more idiomatic some things changed, and so suricata had to change to handle the changes to the API. Most of the changes here are just to accommodate making most of the structures opaque, and changes to the names of constants to accommodate the way cbindgen generates names based off structures.

Some of the other changes have been to make the API nicer to use, such as the change to the log API to eliminate the need to track the position inside the log message buffer:

https://github.com/OISF/suricata/pull/6402/commits/6331a09d7eb2923506fe9c0615b9a4ce5b6f4560

Or to make URI normalization a libhtp function instead of something that suricata implements and manages on the side in `SCHTPGenerateNormalizedUri()`:

https://github.com/OISF/suricata/pull/6402/commits/09ae96053dc200bfeae5f2984abccb6cd0691f0e

These kinds of changes have been motivated when we encountered awkwardness in maintaining the existing API, and so considered how we could make the API easier to use and more idiomatic at the same time.

> > Presently this still builds libhtp-rs as a shared library and links it like libhtp-c, but this will also change to build / link as a crate.

> Are you working on this ?

Not right now - we have been focused on getting the last of the libhtp-rs TODOs and FIXMEs all sorted first.

> Could you do an update that fixes the compilation issues?

No problem! Sorry - I thought you were more looking to just see the current diff.

**Comment by victorjulien** [comment]
Almost there it seems
```
Number of concurrent jobs: 2
===> bug-2511: Sub test #1: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'alert'}}
===> bug-2511: Sub test #2: FAIL : expected 1 matches; got 0 for filter {'count': 1, 'match': {'event_type': 'alert', 'alert.signature_id': 1}}

PASSED:  913
FAILED:  1
SKIPPED: 35
```

**Comment by suricata-qa** [comment]
Warning: no commits in this PR have specified the following ticket(s):
- 2696 - https://redmine.openinfosecfoundation.org/issues/2696

Please update the commit(s) and submit a new PR.

**Comment by catenacyber** [comment]
Could you close this PR and open a new one with the rebased changes ?
cf https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Github_work_flow#Create-a-new-branch-for-incorporating-feedback

**Comment by cccs-rtmorti** [comment]
Closed for #7438

**Pull request closed without merging**
