### PR TITLE
Backports/706/v2

### PR DESCRIPTION
**Pull request by victorjulien**
https://redmine.openinfosecfoundation.org/issues/7050

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 140 | 145 | 103.57% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 649 | 685 | 105.55% | 

Pipeline 20858

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20880

**Review by catenacyber — APPROVED** [review]
Looks good to me, I trust you have taken only the interesting commits for the backport, and not the cleanup ones...

**Comment by victorjulien** [comment]
Merged in #11202, thanks!

**Pull request merged**
