### PR TITLE
Packetpool/v3

### PR DESCRIPTION
**Pull request by victorjulien**
Remaining work from #9486, rebased.

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 16604

**Comment by jasonish** [comment]
Will the second commit need to be backported?

> Completes: https://github.com/OISF/suricata/commit/dc40a139acb3c66f5d34074c240a1f81dec3f002 ("packetpool: signal waiter within lock")

**Comment by victorjulien** [comment]
> Will the second commit need to be backported?
> 
> > Completes: [dc40a13](https://github.com/OISF/suricata/commit/dc40a139acb3c66f5d34074c240a1f81dec3f002) ("packetpool: signal waiter within lock")

Probably good to do it, ya.

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #9859, thanks!

**Pull request closed without merging**
