### PR TITLE
Rust/time/v1

### PR DESCRIPTION
**Pull request by victorjulien**
https://redmine.openinfosecfoundation.org/issues/7130

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21737

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21738

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21739

**Comment by victorjulien** [comment]
replaced by #11568

**Pull request closed without merging**
