### PR TITLE
Smb delete v1

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None, should I create one ?

Describe changes:
- recognizes file deletion over SMB2 (main change)
- fix parsing of file deletion over SMB1 
- get file name in case of chained commands 

suricata-verify-pr: 521
https://github.com/OISF/suricata-verify/pull/521

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR: QA failed on .
Pipeline 3619

**Comment by suricata-qa** [comment]
ERROR: QA failed on .
Pipeline 3619

**Comment by suricata-qa** [comment]
ERROR: QA failed on .
Pipeline 3619

**Comment by suricata-qa** [comment]
ERROR: QA failed on .
Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.
Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.
Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by suricata-qa** [comment]
Information: QA ran without warnings.

Pipeline 3619

**Comment by victorjulien** [comment]
"None, should I create one ?" Yes please

**Comment by catenacyber** [comment]
https://redmine.openinfosecfoundation.org/issues/4622

**Comment by victorjulien** [comment]
Merged in #6324, thanks!

**Pull request closed without merging**
