### PR TITLE
stream: add exception policy for midstream flows - v4

### PR DESCRIPTION
**Pull request by jufajardini**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- exception policy midstream: https://redmine.openinfosecfoundation.org/issues/5468
- applayer parser sections merging: https://redmine.openinfosecfoundation.org/issues/5364
- starts to address documenting the exception policy: https://redmine.openinfosecfoundation.org/issues/5475

Describe changes:
- add a stream.midstream-policy option that allows for controlling if a flow should be fully dropped, passed or bypassed. It is also possible to just ignore the policy (keeps normal behavior) if it is a midstream flow (in IPS mode)
- merge the two existing application layer parser configuration sections in the userguide into one
- add a very brief mention to each of the existing exception policy options (that are configurable via suricata.yaml) to the userguide

Updates from last PR (https://github.com/OISF/suricata/pull/7781):
- incorporate feedback from last PR, to ensure we wouldn't implicitly enable midstream pickups if some exception policy for midstream were enabled.
- I changed the indicated log output types from `SCLogNotice` to `SCLogDebug`, to prevent Suri from getting unexpectedly too verbose.

suricata-verify-pr: 921
https://github.com/OISF/suricata-verify/pull/921

### CODE REVIEW

**Comment by jufajardini** [comment]
(force pushed a commit fix header inclusion in the wrong commit)

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw2_single_stats_chk | | |
| .flow.spare | 1949894 | 1835514 | 106.23% |
| | tlpw2_autofp_stats_chk | | |
| .flow.spare | 1961971 | 1812994 | 108.22% |
| .flow.memuse | 518409728 | 550537728 | 94.16% |
| | tlpw1_stats_chk | | |
| .tcp.rst | 126030 | 105279 | 119.71% |
| | tlpr1_stats_chk | | |
| .flow.memuse | 644562688 | 845888448 | 76.2% |
| .http.memuse | 16440 | 49320 | 33.33% |
| | ips_afp_stats_chk | | |
| .flow.end.state.new | 114456 | 10800 | 1059.78% |
| .flow.end.state.closed | 1975896 | 2097352 | 94.21% |
| .flow.end.tcp_state.closed | 1968805 | 2097352 | 93.87% |
| .flow.end.tcp_liberal | 353540 | 108000 | 327.35% |
| .flow.memuse | 873300288 | 1081197888 | 80.77% |
| .tcp.reassembly_gap | 1211712 | 108000 | 1121.96% |
| .app_layer.flow.tls | 921313 | 974152 | 94.58% |
| .app_layer.flow.failed_tcp | 205178 | 218160 | 94.05% |
| .app_layer.tx.ftp | 242551 | 263520 | 92.04% |
| .app_layer.tx.smtp | 130055 | 149040 | 87.26% |
| .app_layer.tx.dcerpc_tcp | 952538 | 1101600 | 86.47% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 4296 | 5654519 | 0.08% |
| .flow.end.state.new | 6294 | 14867 | 42.34% |
| .flow.end.tcp_state.syn_sent | 8 | 183 | 4.37% |
| .flow.end.tcp_state.syn_recv | 1 | 52 | 1.92% |
| .flow.end.tcp_state.established | 54015 | 61527 | 87.79% |
| .flow.memuse | 760950848 | 709384128 | 107.27% |
| .tcp.segment_memcap_drop | 0 | 11729 | 0.0% |
| .tcp.reassembly_gap | 83309 | 114099 | 73.01% |
| .tcp.insert_data_normal_fail | 0 | 11358 | 0.0% |
| .app_layer.error.http.parser | 2 | 55 | 3.64% |
| .app_layer.error.smtp.gap | 7 | 61 | 11.48% | 

Pipeline 8865
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw2_single_stats_chk | | |
| .flow.spare | 1949555 | 1835514 | 106.21% |
| | tlpw2_autofp_stats_chk | | |
| .flow.spare | 1961380 | 1812994 | 108.18% |
| .flow.memuse | 518345728 | 550537728 | 94.15% |
| | tlpr1_stats_chk | | |
| .flow.memuse | 681048768 | 845888448 | 80.51% |
| .http.memuse | 16440 | 49320 | 33.33% |
| | ips_afp_stats_chk | | |
| .flow.end.state.new | 114011 | 10800 | 1055.66% |
| .flow.end.state.closed | 1974923 | 2097352 | 94.16% |
| .flow.end.tcp_state.closed | 1967871 | 2097352 | 93.83% |
| .flow.end.tcp_liberal | 368527 | 108000 | 341.23% |
| .flow.memuse | 873424128 | 1081197888 | 80.78% |
| .tcp.reassembly_gap | 1236520 | 108000 | 1144.93% |
| .app_layer.flow.http | 412379 | 434160 | 94.98% |
| .app_layer.flow.tls | 921257 | 974152 | 94.57% |
| .app_layer.flow.failed_tcp | 204771 | 218160 | 93.86% |
| .app_layer.tx.ftp | 241921 | 263520 | 91.8% |
| .app_layer.tx.smtp | 129878 | 149040 | 87.14% |
| .app_layer.tx.dcerpc_tcp | 951388 | 1101600 | 86.36% |
| .app_layer.error.ftp.parser | 58101 | 64800 | 89.66% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 112417 | 5654519 | 1.99% |
| .flow.end.state.new | 6933 | 14867 | 46.63% |
| .flow.end.tcp_state.syn_recv | 0 | 52 | 0.0% |
| .flow.end.tcp_state.established | 54451 | 61527 | 88.5% |
| .flow.memuse | 761374528 | 709384128 | 107.33% |
| .tcp.segment_memcap_drop | 0 | 11729 | 0.0% |
| .tcp.reassembly_gap | 94840 | 114099 | 83.12% |
| .tcp.insert_data_normal_fail | 0 | 11358 | 0.0% |
| .app_layer.error.http.parser | 15 | 55 | 27.27% |
| .app_layer.error.smtp.gap | 24 | 61 | 39.34% | 

Pipeline 8866
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

**Comment by jufajardini** [comment]
@ct0br0 check! :)

**Pull request merged**
