### PR TITLE
eve/log: FTP logging

### PR DESCRIPTION
**Pull request by jlucovsky**
This changeset is for issue [2315](https://redmine.openinfosecfoundation.org/issues/2315)  and implements eve logging for FTP, including documentation updates.

Continuation of #3887 

Updated to address review comments and incorporate contribution from @imzke
- Reword commits
- Issue with RST format
- Whitespace trimming (thanks @lmzke)
- Banner logging (thanks @lmzke)

FTP logging adds 2 event types:
- ftp
- ftp_data

Each ftp event can contain:
- command
- command_data
- reply (in array format to handle multi-line replies)
- completion_code
- dynamic_port
- mode
- reply_received

ftp_data events contain:

- filename
- command associated with the data transfer.

## Sample `event_type ftp` output
```
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 1170887768480854,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 0,
  "ftp": {
    "reply": [
      "(vsFTPd 3.0.2)",
      "Features:\r\n EPRT\r\n EPSV\r\n MDTM\r\n PASV\r\n REST STREAM",
      "E\r\n TVFS\r\n UTF8\r\n211 End",
      "Always in UTF8 mode."
    ],
    "completion_code": "220",
    "reply_received": "yes"
  }
}
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 1170887768480854,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 17,
  "ftp": {
    "command": "EPRT",
    "command_data": "|2|2a01:e34:ee97:b130:8c3e:45ea:5ac6:e301|41813|",
    "reply": [
      "EPRT command successful. Consider using EPSV."
    ],
    "completion_code": "200",
    "dynamic_port": 41813,
    "mode": "active",
    "reply_received": "yes"
  }
}
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 1170887768480854,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 18,
  "ftp": {
    "command": "RETR",
    "command_data": "index.html",
    "reply": [
      "Opening BINARY mode data connection for index.html (6712 bytes).",
      "Transfer complete."
    ],
    "completion_code": "150",
    "reply_received": "yes"
  }
}
{
  "timestamp": "2019-03-10T15:20:21.104835-0700",
  "flow_id": 1170887768480854,
  "pcap_cnt": 125,
  "event_type": "ftp",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 38970,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 21,
  "proto": "TCP",
  "tx_id": 19,
  "ftp": {
    "command": "QUIT",
    "reply": [
      "Goodbye."
    ],
    "completion_code": "221",
    "reply_received": "yes"
  }
}j
```

## Sample `event_type ftp_data` output
```
{
  "timestamp": "2019-03-10T15:20:01.500157-0700",
  "flow_id": 1615446949360413,
  "parent_id": 274790086810710,
  "pcap_cnt": 68,
  "event_type": "ftp_data",
  "src_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "src_port": 53697,
  "dest_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "dest_port": 51093,
  "proto": "TCP",
  "tx_id": 0,
  "ftp_data": {
    "filename": "uio-app.js",
    "command": "RETR"
  }
}
{
  "timestamp": "2019-03-10T15:20:18.000469-0700",
  "flow_id": 1343493916181127,
  "parent_id": 274790086810710,
  "pcap_cnt": 116,
  "event_type": "ftp_data",
  "src_ip": "2001:0700:0100:0118:0000:0000:0000:0047",
  "src_port": 20,
  "dest_ip": "2a01:0e34:ee97:b130:8c3e:45ea:5ac6:e301",
  "dest_port": 41813,
  "proto": "TCP",
  "tx_id": 0,
  "ftp_data": {
    "filename": "index.html",
    "command": "RETR"
  }
}
```

### CODE REVIEW

**Comment by lmzke** [comment]
Earlier I had suggested squashing my commit, which may have caused confusion (here and in #3887).  I personally like the updated style and flow of https://github.com/jlucovsky/suricata/commit/5188a894ae66da425a830ebef4a58424f3479af1, which perhaps could be added to the log after my commit?  Either way, I leave the integration in your hands!

**Comment by victorjulien** [comment]
```
==19508==ERROR: AddressSanitizer: SEGV on unknown address 0x6021003ca72f (pc 0x563d885b6ac1 bp 0x7f7faee1e5d0 sp 0x7f7faee1e500 T5)
==19508==The signal is caused by a READ memory access.
[19508] 30/5/2019 -- 20:09:28 - (suricata.c:2843) <Notice> (SuricataMainLoop) -- Signal Received.  Stopping engine.
AddressSanitizer:DEADLYSIGNAL
    #0 0x563d885b6ac0 in CopyCommandLine /home/victor/devel/suricata-rust/src/app-layer-ftp.c:484:29
    #1 0x563d885a5ae4 in FTPParseResponse /home/victor/devel/suricata-rust/src/app-layer-ftp.c:806:29
    #2 0x563d886a8a84 in AppLayerParserParse /home/victor/devel/suricata-rust/src/app-layer-parser.c:1187:13
    #3 0x563d883624e6 in AppLayerHandleTCPData /home/victor/devel/suricata-rust/src/app-layer.c:646:17
    #4 0x563d89a652ee in ReassembleUpdateAppLayer /home/victor/devel/suricata-rust/src/stream-tcp-reassemble.c:1070:13
    #5 0x563d89a61e54 in StreamTcpReassembleAppLayer /home/victor/devel/suricata-rust/src/stream-tcp-reassemble.c:1140:12
    #6 0x563d89a78b6e in StreamTcpReassembleHandleSegmentUpdateACK /home/victor/devel/suricata-rust/src/stream-tcp-reassemble.c:1706:9
    #7 0x563d89a7626f in StreamTcpReassembleHandleSegment /home/victor/devel/suricata-rust/src/stream-tcp-reassemble.c:1749:9
    #8 0x563d899d176a in HandleEstablishedPacketToServer /home/victor/devel/suricata-rust/src/stream-tcp.c:2224:9
    #9 0x563d898ee8dc in StreamTcpPacketStateEstablished /home/victor/devel/suricata-rust/src/stream-tcp.c:2598:13
    #10 0x563d8982c23c in StreamTcpStateDispatch /home/victor/devel/suricata-rust/src/stream-tcp.c:4617:17
    #11 0x563d89816f28 in StreamTcpPacket /home/victor/devel/suricata-rust/src/stream-tcp.c:4798:13
    #12 0x563d89830037 in StreamTcp /home/victor/devel/suricata-rust/src/stream-tcp.c:5134:11
    #13 0x563d895294ae in FlowWorker /home/victor/devel/suricata-rust/src/flow-worker.c:216:9
    #14 0x563d89b33673 in TmThreadsSlotVarRun /home/victor/devel/suricata-rust/src/tm-threads.c:128:17
    #15 0x563d89b49227 in TmThreadsSlotVar /home/victor/devel/suricata-rust/src/tm-threads.c:583:17
    #16 0x7f7fb8a136da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #17 0x7f7fb62f188e in clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/victor/devel/suricata-rust/src/app-layer-ftp.c:484:29 in CopyCommandLine
Thread T5 (W#04) created by T0 (Suricata-Main) here:
    #0 0x563d88210ee0 in pthread_create (/home/victor/sync/devel/suricata-rust/src/suricata+0x3e6ee0)
    #1 0x563d89b43f5d in TmThreadSpawn /home/victor/devel/suricata-rust/src/tm-threads.c:1880:14
    #2 0x563d897381fb in RunModeFilePcapAutoFp /home/victor/devel/suricata-rust/src/runmode-pcap-file.c:255:13
    #3 0x563d8974ff73 in RunModeDispatch /home/victor/devel/suricata-rust/src/runmodes.c:379:5
    #4 0x563d89af7197 in main /home/victor/devel/suricata-rust/src/suricata.c:2995:5
    #5 0x7f7fb61f1b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
```

**Comment by victorjulien** [comment]
```
0x0000555555ce0ac1 in CopyCommandLine (dest=0x6030003c1810, 
    src=0x61d0003d6880 "\r\n[US{XPa{egfokvd!egfokvd@72.12.209.242 JOIN :#Top\r\n:hub.us.com 353 n[US{XPa{egfokvd @ #Top :n[US{XPa{egfokvd \r\n", '\037' <repeats 70 times>, "\r\n\r\nokvd!egfokvd@7"..., length=0)
    at app-layer-ftp.c:484
484	            while(length && isspace((unsigned char)where[(--length) - 1]));
```
This looks suspicious:
```
(--length) - 1
```
gdb:
```
(gdb) print length
$1 = 0
```

**Comment by lmzke** [comment]
I'll rework that loop and submit a pull request to @jlucovsky.

**Comment by lmzke** [comment]
Created https://github.com/jlucovsky/suricata/pull/2

**Comment by jlucovsky** [comment]
Continued in #3900.

**Pull request closed without merging**
