### PR TITLE
userguide: http.cookie keyword update v1

### PR DESCRIPTION
**Pull request by jmtaylor90**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Looks good to me, thanks! We have a redmine ticket for updating HTTP keywords in the userguide, so I have assigned it to you: https://redmine.openinfosecfoundation.org/issues/3025

We're trying to enforce the <80 character limit to lines for new contributions, but I wouldn't want to prevent this from being approved because of that, so just pointing out for next contributions.

Imo, there is no need to split this type of contribution into two PR, as both are connected to updating the same keyword's documentation. Again, adding this note for future contributions. :)

**Comment by jmtaylor90** [comment]
> Looks good to me, thanks! We have a redmine ticket for updating HTTP keywords in the userguide, so I have assigned it to you: https://redmine.openinfosecfoundation.org/issues/3025
> 
> We're trying to enforce the <80 character limit to lines for new contributions, but I wouldn't want to prevent this from being approved because of that, so just pointing out for next contributions.

ack
 
> Imo, there is no need to split this type of contribution into two PR, as both are connected to updating the same keyword's documentation. Again, adding this note for future contributions. :)

It wouldn't be a big deal for me, I can fix up the character limit and squash the commits and resubmit if you would like?

**Comment by jufajardini** [comment]
> > Looks good to me, thanks! We have a redmine ticket for updating HTTP keywords in the userguide, so I have assigned it to you: https://redmine.openinfosecfoundation.org/issues/3025
> > We're trying to enforce the <80 character limit to lines for new contributions, but I wouldn't want to prevent this from being approved because of that, so just pointing out for next contributions.
> 
> ack
> 
> > Imo, there is no need to split this type of contribution into two PR, as both are connected to updating the same keyword's documentation. Again, adding this note for future contributions. :)
> 
> It wouldn't be a big deal for me, I can fix up the character limit and squash the commits and resubmit if you would like?

If that's ok with you, then I appreciate it. A few less lines to be fixed in the future :P

**Comment by jmtaylor90** [comment]
Continued in #8370

**Pull request closed without merging**
