### PR TITLE
ci: a bunch of enhancements, fixup, etc - v4

### PR DESCRIPTION
**Pull request by jasonish**
# Notable Changes

## Easier to use PR variables

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

Where a PR is a branch of `pr/xxx`.

## Non-Root Debug Validation ASAN Build

To catch issues like this in https://redmine.openinfosecfoundation.org/issues/5836.  ASAN + Debug validation is not enough, it also has to run as non-root.

## New way to get PR number and PR body.

Hopefully addresses issues we've been seing here.

### CODE REVIEW

**Comment by suricata-qa** [comment]
ERROR:
 

ERROR: QA failed on serial_wait.
  

Pipeline 12347

**Comment by jasonish** [comment]
The `Fedora 37 (non-root...` build test is expected to fail as its ASAN + Debug Validation + Non Root which currently fails test `bug-5198` due to a Suricata issue.

**Comment by ct0br0** [comment]
Re-running QA

**Comment by jasonish** [comment]
This one XDP modification.  But if you're not using XDP in QA, then it shouldn't change things.

**Pull request closed without merging**
