### PR TITLE
Smtp server detection 1125 v7

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/1125

Describe changes:
- smtp : adds server side detection
- ftp : adds server side detection

The most special trick is that the (server) probing parser waits for the client side to have seen some data to take a definitive positive decision.
So that If it looks like a SMTP server (it could be a FTP server), let's see if the client looks like SMTP or FTP or something unknown...

Modifies #8119 by reusing many1

@ct0br0 on your provided pcap with this PR, `jq 'select(.event_type=="flow") | .app_proto' log/eve.json` only gives me smtp...

### CODE REVIEW

**Comment by catenacyber** [comment]
Investigating change in S-V test failure

**Comment by suricata-qa** [comment]
Information:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 128100 | 103923 | 81.13% |
| .app_layer.tx.ftp | 647 | 222 | 34.31% |
| .app_layer.error.ftp.gap | 2 | 0 | - |
| .app_layer.error.ftp.parser | 2 | 3 | 150.0% |
| .ftp.memuse | 862 | 3 | 0.35% |
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.ftp | 35776 | 11616 | 32.47% |
| .ftp.memuse | 13827 | 2187 | 15.82% |
| | IPS_AFP_stats_chk | | |
| .app_layer.flow.ftp | 33480 | 1080 | 3.23% |
| .app_layer.tx.ftp | 131760 | 99360 | 75.41% |
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 559109 | - |
| .flow.end.state.new | 6272 | 9665 | 154.1% |
| .flow.end.tcp_state.syn_sent | 0 | 1055 | - |
| .flow.end.tcp_state.syn_recv | 0 | 12 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 125 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 39 | - |
| .flow.end.tcp_state.time_wait | 0 | 74 | - |
| .flow.end.tcp_state.last_ack | 0 | 35 | - |
| .flow.end.tcp_state.close_wait | 0 | 184 | - |
| .flow.end.tcp_liberal | 80952 | 100985 | 124.75% |
| .tcp.reassembly_gap | 80952 | 140669 | 173.77% |
| .tcp.overlap | 0 | 10 | - |
| .app_layer.flow.ftp | 18444 | 0 | - |
| .app_layer.tx.ftp | 73776 | 55253 | 74.89% |
| .app_layer.error.http.parser | 0 | 62 | - |
| .app_layer.error.ftp.gap | 0 | 2 | - |
| .app_layer.error.smtp.gap | 0 | 89 | - |
| .app_layer.error.tls.gap | 53852 | 71583 | 132.93% |
| .app_layer.error.dcerpc_tcp.parser | 0 | 24 | - | 

Pipeline 10345

**Comment by ct0br0** [comment]
We know which SMTP is missing because of the files that didn't show up. Other traffic we'd have to include everything.

**Comment by catenacyber** [comment]
Thanks Corey, interesting : the traffic shows up as SMTP, but we do not get the files...

**Comment by ct0br0** [comment]
Not famililar with the code, guessing those `FAILED` and `UNKNOWN` back out some how.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/8135

**Pull request closed without merging**
