### PR TITLE
Initial JA3 integration

### PR DESCRIPTION
**Pull request by thus**
This PR contains an initial JA3 integration (https://github.com/salesforce/ja3). This means that there are some features that are not done yet, and that will (hopefully) be added in the future, but it contains the core functionality.

Features implemented:
* Decode more of the TLS CLIENT_HELLO packet, and generate a JA3 string and a JA3 hash (md5sum of the JA3 string).
* Detection (mpm) keyword 'ja3_hash' for matching on the JA3 hash.
* Detection (mpm) keyword 'ja3_str' for matching on the entire or parts of the JA3 string.
* JSON logger for JA3.
* JA3 metadata in alerts.
* Lua functions 'Ja3GetHash' and 'Ja3GetStr' to access the JA3 buffers from Lua scripts.
* 'ja3_hash' and 'ja3_str' as custom fields in the TLS JSON logger.

As I briefly discussed with @inliniac, I also want to implement 'ja3_desc'. To do this I want to read a JSON file with JA3 fingerprints (hash, string and description) when Suricata starts and on rule reload. This file should contain all the known fingerprints and enable us to match on part of the description, e.g. "ja3_desc; content:"Firefox";). It should also enable us to match on all unknown JA3 fingerprints. Since the de_ctx is not available when decoding the TLS packet, I have not added this feature yet, but it is something that (IMO) would add a lot of value to the JA3 integration.

As of now, I have choose to disable generating JA3 fingerprints by default. I have added an entry to enable it to the suricata.yaml file in the repo, but this means that it won't be enabled before the user updates their Suricata config. Please let me know if you disagree on doing this.

Redmine:
https://redmine.openinfosecfoundation.org/issues/2192

Prscript:
- PR thus-pcap: https://buildbot.openinfosecfoundation.org/builders/thus-pcap/builds/147
- PR thus: https://buildbot.openinfosecfoundation.org/builders/thus/builds/147

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you post examples of:
- ja3 record
- tls record with ja3 fields
- alert with ja3 fields?

**Comment by jasonish** [comment]
Something I'd be looking for is that the JA3 values can all be accessed the same way. ie) Across all event types, the hash could be found at ja3.hash (or something consistent). Right now it looks like we have ja3.hash and ja3_hash.

**Comment by thus** [comment]
Example of alert containing ja3 object:
```json
{
  "timestamp": "2017-11-28T20:52:15.379382+0100",
  "flow_id": 824873139034093,
  "pcap_cnt": 7,
  "event_type": "alert",
  "src_ip": "192.168.86.32",
  "src_port": 60596,
  "dest_ip": "192.33.31.104",
  "dest_port": 443,
  "proto": "TCP",
  "tx_id": 0,
  "alert": {
    "action": "allowed",
    "gid": 1,
    "signature_id": 12346,
    "rev": 0,
    "signature": "JA3 str test",
    "category": "",
    "severity": 3
  },
  "tls": {
    "session_resumed": true,
    "sni": "cdn3.kongregate.com",
    "version": "TLS 1.2"
  },
  "ja3": {
    "hash": "2efb07037a97b06201ab4fe7ec0c326e",
    "str": "771,49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-13-21,29-23-24-25,0"
  },
  "app_proto": "tls",
  "flow": {
    "pkts_toserver": 4,
    "pkts_toclient": 3,
    "bytes_toserver": 789,
    "bytes_toclient": 358,
    "start": "2017-11-28T20:52:15.317421+0100"
  }
}
```

Example of entry from ja3 logger:
```json
{
  "timestamp": "2017-11-28T20:52:15.413711+0100",
  "flow_id": 824873139034093,
  "pcap_cnt": 10,
  "event_type": "ja3",
  "src_ip": "192.168.86.32",
  "src_port": 60596,
  "dest_ip": "192.33.31.104",
  "dest_port": 443,
  "proto": "TCP",
  "ja3": {
    "hash": "2efb07037a97b06201ab4fe7ec0c326e",
    "str": "771,49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-13-21,29-23-24-25,0"
  }
}
```

Example of tls log entry with ja3:
```json
{
  "timestamp": "2017-11-28T20:52:15.413711+0100",
  "flow_id": 824873139034093,
  "pcap_cnt": 10,
  "event_type": "tls",
  "src_ip": "192.168.86.32",
  "src_port": 60596,
  "dest_ip": "192.33.31.104",
  "dest_port": 443,
  "proto": "TCP",
  "tls": {
    "session_resumed": true,
    "sni": "cdn3.kongregate.com",
    "version": "TLS 1.2",
    "ja3_hash": "2efb07037a97b06201ab4fe7ec0c326e",
    "ja3_str": "771,49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-13-21,29-23-24-25,0"
  }
}
```

**Comment by thus** [comment]
Would it make more sense to add a ja3 object to the tls logger, like in alert and ja3 logger, instead of ja3_hash and ja3_str?

**Comment by victorjulien** [comment]
I agree all records need to follow the same structure. Whether it should be a sub-object of tls or a root object I think depends on the value we see in having a separate ja3 logger instance.

I'm inclined to tie it to tls, and get rid of the separate ja3 logger, but I can be convinced otherwise.

Is it foreseeable that there is a large volume difference between ja3 and tls? This is really the only reason I can think of to have a separate ja3 logger.

**Comment by thus** [comment]
I have no good arguments for keeping the ja3 logger as a separate logger. The amount of ja3 log entries should be identical to the amount of tls log entries anyway.

What about changing the tls logger with ja3 to look like this instead:
```json
{
  "timestamp": "2017-11-28T20:52:15.413711+0100",
  "flow_id": 824873139034093,
  "pcap_cnt": 10,
  "event_type": "tls",
  "src_ip": "192.168.86.32",
  "src_port": 60596,
  "dest_ip": "192.33.31.104",
  "dest_port": 443,
  "proto": "TCP",
  "tls": {
    "session_resumed": true,
    "sni": "cdn3.kongregate.com",
    "version": "TLS 1.2",
  },
  "ja3": {
    "hash": "2efb07037a97b06201ab4fe7ec0c326e",
    "str": "771,49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-13-21,29-23-24-25,0"
  }
  }
}
```
Then we could keep the separate ja3 object in the alert meta data, instead of having to modify the basic tls log. I like the thought that this is something other than just tls (even if it's not).

I'll just do what you decide, as usual :)

**Comment by victorjulien** [comment]
I think if ja3 only ever is about tls, it should be a tls sub-object. What do you think @jasonish ?

**Comment by jasonish** [comment]
> I think if ja3 only ever is about tls, it should be a tls sub-object. What do you think @jasonish ?

Yes, I agree that it should be sub object of tls. So given a tls record, or an alert record we'd have:
- tls.ja3.hash
- tls.ja3.string (sorry, don't like "str")

**Comment by thus** [comment]
Replaced by #3292

**Pull request closed without merging**
