### PR TITLE
Quic ietf 4967 v17

### PR DESCRIPTION
**Pull request by catenacyber**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4967
https://redmine.openinfosecfoundation.org/issues/5143
https://redmine.openinfosecfoundation.org/issues/5166

Describe changes:
- Parses standardized QUIC IETF v1
- Parses gquic version Q039, 0xfaceb002, etc...
- JA3 logging and detection on quic
- Adds quic events and rules 
- bump up rust carte tls_parser already used by rep, so that it can be used by quic
- Rustfmt previous code

suricata-verify-pr: 783
https://github.com/OISF/suricata-verify/pull/783

Replaces https://github.com/OISF/suricata/pull/7504 with downgrading new crates to be compatible with MSRV, and adding a commit to get Github CI to test MSRV

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8104

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 8185

**Comment by catenacyber** [comment]
CI is green with https://github.com/RustCrypto/traits/issues/1047 having been fixed by crypto-common 0.1.5

**Comment by victorjulien** [comment]
Looks like at least some of the anomaly events are a pretty simple case: "midstream" flow of packets, where we see only data packet and no setup/handshake. These generate:

```json
"anomaly":{"app_proto":"quic","type":"applayer","event":"error_on_data","layer":"proto_parser"}
```

**Comment by catenacyber** [comment]
> Looks like at least some of the anomaly events are a pretty simple case: "midstream" flow of packets, where we see only data packet and no setup/handshake. These generate:
> 
> ```json
> "anomaly":{"app_proto":"quic","type":"applayer","event":"error_on_data","layer":"proto_parser"}
> ```
> 
> These then appear to be raised for each packet, which is quite noisy.

Could you share a pcap ?

I do not manage to get these by taking one midstream packet of my pcaps 

I guess it depends on the quic version + short or long header...

**Comment by catenacyber** [comment]
Based on the code, this event should only happen for long from headers and for `QuicType::Initial`

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata/pull/7669

**Pull request closed without merging**
