### PR TITLE
rust: fix lint warning for clippy::enum's name

### PR DESCRIPTION
**Pull request by hsadia538**
- [X] I have read the contributing guidelines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)fixes lint warnings in the rust code

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4597) ticket:

Previous PR: https://github.com/OISF/suricata/pull/7989

Describe changes:
- Update commit message

### CODE REVIEW

**Comment by jasonish** [comment]
Code looks fine, but the commit message could be one line.  When not one line, it's nice if the body of the commit message is a proper sentence.  However, for this commit, just the first line is needed, the body of the commit message can be dropped.

**Comment by hsadia538** [comment]
> Code looks fine, but the commit message could be one line. When not one line, it's nice if the body of the commit message is a proper sentence. However, for this commit, just the first line is needed, the body of the commit message can be dropped.

Should I make another PR for this?

**Review by jasonish — APPROVED** [review]
Looks good to me.

**Comment by victorjulien** [comment]
Merged in #8042, thanks for your contribution!

**Pull request closed without merging**
