### PR TITLE
next/216/70x/20231207/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #9982

SV_BRANCH=pr/1520

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 181 | 194 | 107.18% | 

Pipeline 16914

**Comment by victorjulien** [comment]
Consistent with https://github.com/OISF/suricata/pull/9982#issuecomment-1844901065, it seems.

**Comment by victorjulien** [comment]
> Consistent with [#9982 (comment)](https://github.com/OISF/suricata/pull/9982#issuecomment-1844901065), it seems.

@ct0br0 can you do a rerun of `main-7.0.x` and this PR in dev ?

**Comment by ct0br0** [comment]
Sync'd up our baseline. This looks good from my end.

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Starting a new run to get clean QA on the PR

**Pull request closed without merging**
