### PR TITLE
Convert the napatech packet source to a plugin

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #11657   

This PR contains the changes to distribute and build the Napatech source modules as a "capture plugin". 

Describe changes:
- Converted the Napatech source modules to be suitable for a capture plugin
- User-level upgrade documentation 

Updates:
- Rebase and manual application of 96a0ffadde9bc1967d2cc9bfbeebe921c882e9b0 to file that was deleted and then added.
- Doc update -- use "Napatech" instead of "NAPATECH"
- Revert unnecessary change to decode module name -- `NapatechDecode`.
- Combine like commits (remove unnecessary fixup commit)
- Doc tweaks per review feedback

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22304

**Comment by jlucovsky** [comment]
@ralpheastwood  I'm requesting your input on this PR. I've built and tested this on a system with a NT40. I'd like to hear of your experience and if there are any items requiring attention.

**Comment by ralpheastwood** [comment]
Hi @jlucovsky - sorry I've been on vacation.  One of my colleagues is testing it now.

**Comment by ralpheastwood** [comment]
Hi @jlucovsky - we're experiencing some issues loading the plugin.  We added

```
  plugins:
    - /usr/local/lib/suricata/napatech.so
```
    
 To the configuration file and ran it using:
 
` suricata -c ./suricata.yaml --runmode workers -vvv`

We also tried it with `--napatech`.

[192.168.0.200_2024-09-19_15-22-04.log](https://github.com/user-attachments/files/17055303/192.168.0.200_2024-09-19_15-22-04.log)

**Comment by jlucovsky** [comment]
> Hi @jlucovsky - we're experiencing some issues loading the plugin. We added
> 
> ```
>   plugins:
>     - /usr/local/lib/suricata/napatech.so
> ```
> 
> To the configuration file and ran it using:
> 
> ` suricata -c ./suricata.yaml --runmode workers -vvv`
> 
> We also tried it with `--napatech`.
> 
> [192.168.0.200_2024-09-19_15-22-04.log](https://github.com/user-attachments/files/17055303/192.168.0.200_2024-09-19_15-22-04.log)

Can you post the output of `suricate --build-info`?

Have you tried adding `--capture-plugin=napatech` to the command line?

**Comment by ralpheastwood** [comment]
Hi @jlucovsky, the `--capture-plugin=napatech` was the missing piece.

My colleague has managed to get it to work with a modified version of his configuration file.  He did notice that with the default `suricata.yaml`, there was packet drops as compared to the one he normally used (with previous versions).  He is comparing the configuration now to see what the differences are.

**Comment by jlucovsky** [comment]
> Hi @jlucovsky, the `--capture-plugin=napatech` was the missing piece.
> 
> My colleague has managed to get it to work with a modified version of his configuration file. He did notice that with the default `suricata.yaml`, there was packet drops as compared to the one he normally used (with previous versions). He is comparing the configuration now to see what the differences are.
> 
> [192.168.0.200_2024-09-20_16-03-48.log](https://github.com/user-attachments/files/17072157/192.168.0.200_2024-09-20_16-03-48.log)

I'd like to hear what changes, if any, were needed to correct the packet drops.

The command line option is [in this README](https://github.com/OISF/suricata/pull/11687/files#diff-c38c338ee4b39c883bea75ed8efd94e7aa8bc133cbc0ed6f5f2706e09cf56a4e)

**Comment by jlucovsky** [comment]
Continued in #11819

**Pull request closed without merging**
