### PR TITLE
base64_data with fast_pattern/v8

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5220

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1821

Previous PR: https://github.com/OISF/suricata/pull/10728

Changes since v7:
- change doc wording as per Jason's suggestion

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 19864

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
Is there a blocker for not merging this ?

**Comment by victorjulien** [comment]
> Is there a blocker for not merging this ?

It required a rule update in various QA/CI systems. Not sure what the status is.

**Comment by inashivb** [comment]
> It required a rule update in various QA/CI systems. Not sure what the status is.

Rules in QA lab were updated.. Only after that QA started to pass..

**Comment by victorjulien** [comment]
Merged in #11072, thanks!

**Pull request closed without merging**
