### PR TITLE
Smtp to comma quote 7060 v2

### PR DESCRIPTION
**Pull request by catenacyber**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7060

Describe changes:
- Needed clean cherry-pick of https://redmine.openinfosecfoundation.org/issues/6906
- Needed clean cherry-pick for json schema addition of missing fields
- smtp: log split by commas with respecting quotes

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1885

#11232 rebased to get green CI

### CODE REVIEW

**Comment by victorjulien** [comment]
@ct0br0 can you prep the baseline update for this? Think it's a minor hashing update right @catenacyber ?

**Comment by suricata-qa** [comment]
WARNING:
 

ERROR: QA failed on SURI_TLPW1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .flow.end.tcp_state.syn_recv | 0 | 1 | - | 

Pipeline 20997

**Comment by catenacyber** [comment]
> @ct0br0 can you prep the baseline update for this? Think it's a minor hashing update right @catenacyber ?

Right, I proposed one MR to qa-prod

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #11348, thanks!

**Pull request closed without merging**
