### PR TITLE
dcerpc: add truncate fn call to registration

### PR DESCRIPTION
**Pull request by inashivb**
Link to ticket: https://redmine.openinfosecfoundation.org/issues/7044

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 20809

**Comment by inashivb** [comment]
> Do you have test case as well?

Not yet, will have to custom create it.

**Review by jufajardini — COMMENTED** [review]
From my observation, this seems to be what we want. But will wait for the SV test, to be on the safe side :)

**Comment by catenacyber** [comment]
What does this truncate function do ?
Why does it call `sc_app_layer_parser_trigger_raw_stream_reassembly` for every tx ?

**Comment by jufajardini** [comment]
> What does this truncate function do ? 

For what it does, I can only resort to the commit that added it: https://github.com/OISF/suricata/commit/8b2886635f2d69e302499971a1a0fde8b2099a50#diff-88368b0c2f03a908440ab63346e55e7561cc93233e0a5c0156959e122a783cbaR186

**Comment by catenacyber** [comment]
Do we still need it ?

**Comment by jufajardini** [comment]
> Do we still need it ?

I guess that'll be answered by the SV tests 🤔

**Comment by inashivb** [comment]
> SV was green, SV is still green
> 
> I think there is generic code to do that now

I feel like I'm making a shot in the dark and I should really first learn what that raw_trigger_reassembly fn does and a bit inside that generic code that you're talking about before I make a test or another attempt
Thanks, both!

**Comment by catenacyber** [comment]
>  I should really first learn what that raw_trigger_reassembly fn

I guess the more important thing is to trigger this `Truncate` (or the code replacing it generically)

**Comment by inashivb** [comment]
> I guess the more important thing is to trigger this `Truncate` (or the code replacing it generically)

I couldn't find any generic code for truncation, there are callback fns in C which ultimately end up calling the respective parser's registered truncate fn..

**Comment by catenacyber** [comment]
Summing up here :
- We should remove `truncate` for all protocols
- We should remove `rs_dcerpc_state_trunc` 

We should add a SV test with the dcerpc.pcap I can share, `--set stream.reassembly.depth=8kb`
- check for "event_type": "dcerpc", "pcap_cnt": 40, (and not flow timeout), "dcerpc": {
    "request": "REQUEST_LOST","call_id": 5360,
This check ensures that when one side for stream depth is reached, the logger (and clean up code does the same) checks it instead of resorting to `StateGetProgress (usage of `FlowGetDisruptionFlags
For detection, we can also add a test, but as detection is direction-dependent, having stream depth reached on one side is not a problem to run detection on the other side.

```
alert dcerpc any any -> any any (msg:"lol"; sid:1;dcerpc.stub_data; bsize:>2100;)
# content: "5|00|E|00|1|00|1";)
```

**Comment by catenacyber** [comment]
Also one remaining question : should `AppLayerParserTriggerRawStreamReassembly` be called in case of `    if (flags & STREAM_DEPTH) {` when we called `AppLayerParserStreamTruncated`

**Comment by inashivb** [comment]
> Also one remaining question : should `AppLayerParserTriggerRawStreamReassembly` be called in case of ` if (flags & STREAM_DEPTH) {` when we called `AppLayerParserStreamTruncated`

I think it makes sense to do that indeed. Basically, process the last of whatever you have and then truncate the rest of the stream bc it can no longer be accommodated.

**Pull request closed without merging**
