### PR TITLE
modbus: move parser from c to rust - v12

### PR DESCRIPTION
**Pull request by cccs-sadugas**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
- [3957](https://redmine.openinfosecfoundation.org/issues/3957)

Describe changes:
- Rebase master.
- Addressed code review comments from v10:
  - added comment that exception code `0xFF` is invalid in test case
  - moved unassigned exception code test change to correct commit
  - removed unused c definitions in app-layer-modbus header
  - moved `MODBUS_CONFIG_DEFAULT_STREAM_DEPTH` to `UNITTESTS` block
  - added comment on how the response is used for inspection
  - stopped allocating transactions during a flood

Link to parser:
- [sawp-modbus-0.4.0](https://github.com/CybercentreCanada/sawp/blob/sawp-modbus-0.4.0/sawp-modbus/src/lib.rs)

Link to previous PR:
- #6055

TODO:
- release `sawp-modbus` fix for #5770 and update `Cargo.toml.in` with new version.

suricata-verify-pr: 486

### CODE REVIEW

**Comment by catenacyber** [comment]
Note : there is still a question pending about `rs_modbus_inspect` from previous PR, and one remark about the suricata-verify PR

**Comment by han-guang-xue** [comment]
1. Can you tell me how to turn on non-optimized compilation for this project
2. Could you please tell me where to submit any bugs in your program

**Review by catenacyber — APPROVED** [review]
Would it be possible to add in the suricata-verify test the modbus part of the alert ?

**Comment by cccs-sadugas** [comment]
> 
> 
> Would it be possible to add in the suricata-verify test the modbus part of the alert ?

Sure, we can look into this.

**Comment by cccs-sadugas** [comment]
> 
> 
> Note : there is still a question pending about `rs_modbus_inspect` from previous PR, and one remark about the suricata-verify PR

I think I responded to all outstanding comments. Still waiting to here what to do with travis.yaml file.

**Comment by catenacyber** [comment]
>  Still waiting to here what to do with travis.yaml file.

What is going on with travis.yml ? the rust min version ? @jasonish should we remove travis.yml ?

**Comment by jasonish** [comment]
> What is going on with travis.yml ? the rust min version ? @jasonish should we remove travis.yml ?

Sorry, I don't follow.  We still have travis.yml in master and it doesn't appear to be an issue.

**Comment by catenacyber** [comment]
> Sorry, I don't follow. We still have travis.yml in master and it doesn't appear to be an issue.

It is an issue to update it if we do not use it anymore. For here, and for pcre2 as well...

**Comment by victorjulien** [comment]
Merged in #6101, thanks!

**Comment by victorjulien** [comment]
> I still don't understand the issue. But looking at Travis, I don't think we've had a build succeed there in months due to their credit system, so we should probably remove this with its own PR, which I can take care of.

I removed `.travis.yml`

**Pull request closed without merging**
