### PR TITLE
Replace Jansson with Rust JsonBuilder - v25

### PR DESCRIPTION
**Pull request by jasonish**

### CODE REVIEW

**Comment by victorjulien** [comment]
Still getting a panic (51c4f05 is applied)
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 64 but the index is 64', /usr/src/rustc-1.41.0/src/libcore/slice/mod.rs:2812:14
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic_bounds_check
   9: <usize as core::slice::SliceIndex<[T]>>::index_mut
             at /usr/src/rustc-1.41.0/src/libcore/slice/mod.rs:2812
  10: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /usr/src/rustc-1.41.0/src/libcore/slice/mod.rs:2667
  11: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /usr/src/rustc-1.41.0/src/liballoc/vec.rs:1883
  12: suricata::jsonbuilder::JsonBuilder::encode_string
             at src/jsonbuilder.rs:475
  13: suricata::jsonbuilder::JsonBuilder::set_string
             at src/jsonbuilder.rs:343
  14: suricata::jsonbuilder::JsonBuilder::set_string_from_bytes
             at src/jsonbuilder.rs:350
  15: suricata::dns::log::dns_log_query
             at src/dns/log.rs:575
  16: rs_dns_log_json_query
             at src/dns/log.rs:593
  17: JsonDnsLoggerToServer
             at ./src/output-json-dns.c:328
  18: OutputTxLog
             at ./src/output-tx.c:273
  19: OutputLoggerLog
             at ./src/output.c:933
  20: FlowWorker
             at ./src/flow-worker.c:289
  21: TmThreadsSlotVarRun
             at ./src/tm-threads.c:117
  22: TmThreadsSlotVar
             at ./src/tm-threads.c:428
  23: start_thread
  24: __clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by victorjulien** [comment]
With a780695 this passes my QA and gives some really nice speedups, esp when dealing with high dns and flow rates.

Happy to consider a new PR for inclusion :)

**Comment by victorjulien** [comment]
Not sure if this is intentional, but I accidentally passed in a NULL-ptr as a string and got
```
Thread 24 "FR#01" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff967fc700 (LWP 32218)]
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120     ../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x0000000000755c7a in std::ffi::c_str::CStr::from_ptr ()
#2  0x000000000068421c in jb_set_string (js=0x7fff8862bf20, key=<optimized out>, val=0x0) at src/jsonbuilder.rs:545
#3  0x000000000055d37b in EveFlowLogJSON (aft=0x7fff80000be0, jb=0x7fff8862bf20, f=0x7fff992ce310) at output-json-flow.c:279
#4  0x000000000055c71e in JsonFlowLogger (tv=0x1c19640, thread_data=0x7fff80000be0, f=0x7fff992ce310) at output-json-flow.c:376
#5  0x000000000053f14b in OutputFlowLog (tv=0x1c19640, thread_data=0x7fff80000bc0, f=0x7fff992ce310) at output-flow.c:115
#6  0x000000000051e51a in Recycler (tv=0x1c19640, output_thread_data=0x7fff80000bc0, f=0x7fff992ce310) at flow-manager.c:652
#7  0x000000000051d037 in FlowRecycler (th_v=0x1c19640, thread_data=0x7fff80000b20) at flow-manager.c:1253
#8  0x00000000005bb478 in TmThreadsManagement (td=0x1c19640) at tm-threads.c:525
#9  0x00007ffff69836db in start_thread (arg=0x7fff967fc700) at pthread_create.c:463
#10 0x00007ffff42ac88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 3
#3  0x000000000055d37b in EveFlowLogJSON (aft=0x7fff80000be0, jb=0x7fff8862bf20, f=0x7fff992ce310) at output-json-flow.c:279
279         jb_set_string(jb, "reason", reason);
(gdb) p reason
$1 = 0x0
```

**Comment by jasonish** [comment]
> The NULL ptr is an easy fix on my end, but was wondering if the `jb_set_string` call should be a bit more forgiving here.

It probably should.  So with Jansson, if you set a NULL value, it does not end up in the output at all.  I wonder if we should still set something.. Either an empty string, or something like "(null)"? Thoughts?

**Comment by victorjulien** [comment]
> > The NULL ptr is an easy fix on my end, but was wondering if the `jb_set_string` call should be a bit more forgiving here.
> 
> It probably should. So with Jansson, if you set a NULL value, it does not end up in the output at all. I wonder if we should still set something.. Either an empty string, or something like "(null)"? Thoughts?

The only place where I've seen this so far in our code is in a mistake I made. So I guess we're already quite good at avoiding the scenario. I think there is probably little overhead in adding a null check though. We can probably follow janssons lead in not outputting anything in the case?

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata/pull/4920.

**Pull request closed without merging**
