### PR TITLE
dpdk: add initial unittests for DPDK codebase v3

### PR DESCRIPTION
**Pull request by lukashino**
Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6927
Follow-up of: #10838

Describe changes:
v3
- comments from Philippe
- I left TAILQ_INIT in the finalize/cleanup functions - all elements of the arrays are cleaned but not the base pointer of the array itself. TAILQ_* functions don't offer reset function but TAILQ_INIT provides the desired outcome
- moved guards around - per Philippe's suggestions

v2
- added a FatalError check on the number of LiveDevices
- changed #if HAVE_DPDK to #if defined(HAVE_DPDK) && defined(UNITTESTS)
- enabled unit tests in the Github workflow runs on Ubuntu and Fedora tasks

v1
- function-guarded variable
- fix the CPU exclude logic
- add DPDK unit tests

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 21539

**Comment by victorjulien** [comment]
```
2024-07-14T21:21:15.6306478Z Test DPDKRunmodeSetThreads01                                      : pass
2024-07-14T21:21:15.6306721Z Test DPDKRunmodeSetThreads02                                      : FAILED
2024-07-14T21:21:15.6307280Z Test DPDKRunmodeSetThreads03                                      : make[2]: Leaving directory '/__w/suricata/suricata/suricata-8.0.0-dev/_build/sub/src'
2024-07-14T21:21:15.6307616Z make[1]: Leaving directory '/__w/suricata/suricata/suricata-8.0.0-dev/_build/sub'
2024-07-14T21:21:15.6319206Z ##[error]Process completed with exit code 2.
2024-07-14T21:21:15.6443130Z Post job cleanup.
```

**Comment by catenacyber** [comment]
Replaced by #11728 right ?

**Comment by lukashino** [comment]
correct, thanks! :1st_place_medal:

**Pull request closed without merging**
