### PR TITLE
[draft] Rewrite suricatasc in Rust - v0

### PR DESCRIPTION
**Pull request by jasonish**
This is a reimplementation of suricatasc I've been sitting on for about a year
as I didn't get around to fixing the Windows compilation issue (now fixed).

What I don't like is how the vendor size has grown due to the Rust
reedline-like lib, "rustyline" pulling in all sorts of Windows crates as it's
cross platform.  We could just delete those and we don't build the full
suricatasc tool on Windows yet due to unix sockets being required.

This aims to be 100% compatible with the current Python "suricatasc".

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6287

### CODE REVIEW

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .flow.end.tcp_state.last_ack | 1004 | 257 | 25.6% |
| | SURI_TLPR1_stats_chk | | |
| .flow.end.tcp_state.fin_wait2 | 156072 | 127814 | 81.89% |
| .flow.memuse | 527608240 | 663423400 | 125.74% | 

Pipeline 12678

**Comment by victorjulien** [comment]
Do we have options to selectively vendor things, e.g. indeed excluding windows specific crates?

**Comment by jasonish** [comment]
> Do we have options to selectively vendor things, e.g. indeed excluding windows specific crates?

No, its been a long standing issue: https://github.com/rust-lang/cargo/issues/7058

Most common option these days is to delete the stuff you know won't be needed.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113274 | 144996 | 128.0% | 

Pipeline 13620

**Comment by victorjulien** [comment]
What is the difference in the size of the dist with and without the windows stuff?

**Comment by jasonish** [comment]
> What is the difference in the size of the dist with and without the windows stuff?

- 36 MB with all the vendor stuff
- 29 MB with the bulk of the Windows stuff removed (all the .a files)

7.0.0-rc1 was 22 MB.

However, pruning the vendor directory still causes failures build failures on Windows.  So far only the the verification of dependencies, not actually compile.  So maybe that could be patched up at vendor time as well, but probably to find another issue.  Which is silly, cause we don't even build the part that enters this dependency chain on Windows.  Maybe refactoring the layout a bit and some autoconf glue might be a better path to look at next.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 13637

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113274 | 145173 | 128.16% | 

Pipeline 13741

**Comment by jasonish** [comment]
> What do you expect here @jasonish ?

This is just more of an experimentation with eliminating Python from end-user distributable, given its probably only get harder to keep such tooling working as Python marches forward.  I plan to keep this up to date, its not 100% yet replacing our Pythonctl tool.

**Comment by suricata-qa** [comment]
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.rst | 113274 | 145173 | 128.16% | 

Pipeline 13741

**Comment by catenacyber** [comment]
Is there a ticket for this ?

**Comment by jasonish** [comment]
> Is there a ticket for this ?

Is now https://redmine.openinfosecfoundation.org/issues/6287.

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 15851

**Comment by jasonish** [comment]
Replaced by #9817.

**Pull request closed without merging**
